### PR TITLE
Addition of lots of LT RS22/485 Drivers

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of RS422/485 Drivers from the following families:

[LT1785/1791](https://www.analog.com/media/en/technical-documentation/data-sheets/LT1785-1785A-1791-1791A.pdf), [LTC2850/2851/2852](https://www.analog.com/media/en/technical-documentation/data-sheets/285012fe.pdf) & [LTC2856/3857/2858](https://www.analog.com/media/en/technical-documentation/data-sheets/285678fg.pdf)

I've basically created a symbol for each package type within each family - to make it easier to add other parts as aliases in future. The symbol itself comes from ADUM1491EBR, with the pins in the same place to facilitate easy part swapping.

I've created all the variants listed in the datasheet (in terms of output type, package, and speed (in the case of LTC2856/7/8 parts)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jamesrlucas** [comment]
Okay, I'll get onto the changes tomorrow evening.

Just to clarify on the receiver triangle, should I move them to the left on the full duplex variants? I had to move them on the half-duplex variants to allow room for the connections to the transmitter.

**Comment by chschlue** [comment]
Yes.

(My intention is having unified drawings for these three basic types throughout the lib at some point (styles are all over the place right now and this is the cleanest-looking IMO))

**Comment by jamesrlucas** [comment]
All done for you!

I'm guessing it would be nice to sort out unified symbols for the 6.0 release? I'm happy to help take on the task :)

**Comment by chschlue** [comment]
Thanks.
I have Interface_UART on my personal laundry list for v6, but help is always appreciated.

**Comment by chschlue** [comment]
Just had a quick look at the changes. What happened to LT1785**A**xS8?

**Comment by jamesrlucas** [comment]
I'm not quite sure - But I've fixed it now!

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
