### PR TITLE
Add ADP2360

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/ADP2360.pdf
Footprint: https://github.com/KiCad/kicad-footprints/pull/2253

Screenshot:
adp2360

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks, I see the symbol is very large. Please check other symbol which are very similar.

**Comment by jneiva08** [comment]
have reduced 2.54mm in each side

image

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] Pin 2 should be Open Collector
- [ ] Use capital letters for pin name (VIN)
- [ ] Component outline should be 10mil (see travis error)
- [ ] Switching regulator are much more compact, you should reduce the height (width is ok). Proposed:

Capture

Cheers,
Joel

**Comment by chschlue** [comment]
Suffix should be `xCP`

**Comment by myfreescalewebpage** [comment]
Good catch of @chschlue it's correct, the name of the symbol should be "ADP2360xCP" @jneiva08

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now :)

**Comment by chschlue** [comment]
FP merged

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
