### PR TITLE
Add several generic BRT symbols

### PR DESCRIPTION
**Pull request by evanshultz**
With https://github.com/KiCad/kicad-symbols/pull/1067 being merged, there is a hole in Device.lib for reference bias resistor transistor symbols in all configurations. I took a look at some parts on DigiKey and made up symbols to fit them as a template for specific components that could be added later.

Below are the new symbols and an example datasheet:
- NPN BRT (EBC pinout) https://www.onsemi.com/pub/Collateral/DTC143Z-D.PDF
- NPN BRT (ECB pinout) https://www.fairchildsemi.com/datasheets/FJ/FJN3303R.pdf
- Dual NPN BRT https://www.onsemi.com/pub/Collateral/DTC114ED-D.PDF
- NPN/PNP BRT https://assets.nexperia.com/documents/data-sheet/PEMD3_PIMD3_PUMD3.pdf
- PNP/NPN BRT
- PNP BRT (EBC pinout) https://www.onsemi.com/pub/Collateral/DTA144E-D.PDF
- PNP BRT (ECB pinout) https://www.fairchildsemi.com/datasheets/FJ/FJN4302R.pdf
- Dual PNP BRT https://www.infineon.com/dgdl/bcr185series.pdf?folderId=db3a30431400ef68011406f3ddb1012e&fileId=db3a30431428a3730114403af22402d4

image

There are some other variations (BRT + non-BRT pair, only base resistor and not B-E resistor, BRT + diode) but I left those out since they seem rare. And with this PR I think we now have all building blocks for users to create them easily.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz 

A single comment during the review:

- [ ] I do not agree with name and pin of device "Q_DUAL_PNP_PNP_BRT_E1B1C2E2B2C1". This is "C1B1B2C2E2E1" or need to change pin numbers.

You have travis errors about footprint filter but I suppose this is wanted as other transistor in the lib.

Cheers,
Joel

**Comment by evanshultz** [comment]
The dual PNP did have the wrong pinout on the symbols, but the naming was correct. Good catch. I've corrected this.

**Comment by myfreescalewebpage** [comment]
Thanks! Reviewed, no more comment on this PR. Merging.

**Pull request merged**
