### PR TITLE
Added AO3401A

### PR DESCRIPTION
**Pull request by DecadoPL**
http://www.aosmd.com/pdfs/datasheet/AO3401A.pdf

image

Please tell me if I'm do something wrong with git branches or anything! Thank You!

### CODE REVIEW

**Comment by evanshultz** [comment]
I believe this symbol can be an ALIAS of `TP0610T`. Otherwise it looks good. Thanks!

**Comment by DecadoPL** [comment]
@evanshultz I did as You said. Hope everything is fine now.
Thank You!

**Comment by DecadoPL** [comment]
@antoniovazquezblanco why did You add this to 5.1.3 milestone instead of merging it?

**Comment by antoniovazquezblanco** [comment]
It was intentional. It is small enought to be reviewed before that but I did not review it. Evan will merge whenever he review it

**Comment by evanshultz** [comment]
@DecadoPL 
Looks good. Thanks!

**Pull request merged**
