### PR TITLE
Add iCHaus iC-MZ differential hall effect speed sensor symbol.

### PR DESCRIPTION
**Pull request by stambaughw**
The datasheet for this symbol can be found at:
https://www.ichaus.de/upload/pdf/MZ_datasheet_B2en.pdf

Datasheet URL:
Add iCHaus iC-MZ differential hall effect speed sensor symbol.

The datasheet for this symbol can be found at:
https://www.ichaus.de/upload/pdf/MZ_datasheet_B2en.pdf
Add iCHaus iC-MZ differential hall effect speed sensor symbol.

The datasheet for this symbol can be found at:
https://www.ichaus.de/upload/pdf/MZ_datasheet_B2en.pdf

Footprint pull request:
https://github.com/KiCad/kicad-footprints/pull/1415

Obligatory screenshot:
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by stambaughw** [comment]
New screenshot to fix CI failures:
image

**Comment by myfreescalewebpage** [comment]
Hi @stambaughw , thanks for contributing,

A few comments I have during my review:

- [ ] Name of pin 2 is `D`, name of pin 4 is `~D`
- [ ] Name of pin 9 is `~A\, name of pin 10 is `A`
- [ ] Name of pin 3 is `VB`
- [ ] Name of pin 8 is `VPA`
- [ ] Pin 8 should be Passive to avoid any ERC errors
- [ ] EP size should be 2.8x3.2mm (datasheet page 3), thus footprint will be `Package_DFN_QFN:DFN-10-1EP_4x4mm_P0.65mm_EP2.8x3.2mm`
- [ ] Footprint filter should be `DFN*1EP*4x4mm*P0.65mm*`
- [ ] I have doubts about the design, the schema page 8 of the datasheet let me think pin 9/10 should be on the right of the symbol below pins 2/4. Pin 6 should be above pin 8 on the left of the symbol, to easily wire the capacitor.

Cheers,
Joel

**Comment by stambaughw** [comment]
Hi @myfreescalewebpage ,

I'm assuming you are basing the pin names on the datasheet.  I just took another look at the KLC, and I didn't see anything about this.  I will change them but the KLC should be updated to request that the datasheet pin names be used rather than than the more descriptive names I used.  As soon as I have an answer on the footprint and 3D model issues, will update the the symbol.

Cheers,

Wayne

**Comment by stambaughw** [comment]
@myfreescalewebpage ,

As for pins 9 and 10, they are configurable.  Pulling the TEST pin up to VPA will put the device in a output driver only mode where the hall effect circuitry is disabled and A and ~A are the inputs that drive the output signals D and ~D.  Even in the normal operating mode where A and ~A are analog outputs, they typically are used during development to set the magnetic field strength of the hall elements correctly.  I don't have a strong preference one way or the other so if the consensus is to move them to the right side of the symbol than I will.

Cheers,

Wayne

**Comment by myfreescalewebpage** [comment]
Hi @stambaughw 

To answer your questions:
- We always use the exact pins name of the datasheet, this is to avoid any error for future users
- I make the suggestion to move the pin because of the reference schematic in the datasheet. If you have another schematic extract to provide in order to get a better idea on how the device is used, please add it to this PR :)

Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
@stambaughw any news here ? Thanks for the update, Joel

**Comment by myfreescalewebpage** [comment]
@stambaughw ping!

**Pull request closed without merging**
