### PR TITLE
Sensor_Motion: Added Kionix KXTJ3-1057.

### PR DESCRIPTION
**Pull request by cederom**
The KXTJ3-1057 is a tri-axis ±2g, ±4g, ±8g or ±16g silicon micromachined accelerometer. The sense element is fabricated using Kionix’s proprietary plasma micromachining process technology. Acceleration sensing is based on the principle of a differential capacitance arising from acceleration-induced motion of the sense element, which further utilizes common mode cancellation to decrease errors from process variation, temperature, and environmental stress. The sense element is hermetically sealed at the wafer level by bonding a second silicon lid wafer to the device using a glass frit. A separate ASIC device packaged with the sense element provides signal conditioning and digital communications. The accelerometer is delivered in a 2 x 2 x 0.9 mm LGA plastic package operating from a 1.71V – 3.6V DC supply. Voltage regulators are used to maintain constant internal operating voltages over the range of input supply voltages. This results in stable operating characteristics over the range of input supply voltages and virtually undetectable ratiometric error. The I2C digital protocol is used to communicate with the chip to configure the part and monitor outputs.

screen shot 2018-05-26 at 01 33 40

Symbol uses existing `LGA-12_2x2mm_Pitch0.5mm` footprint.

### CODE REVIEW

**Comment by evanshultz** [comment]
Can you please always include a datasheet with every submission? Also, your branch is broken and you will need to fix it before this can be merged.

**Comment by cederom** [comment]
Hey there :-) PDF is referenced in Documentation field :-)

Yea, the head has moved since my pull, thus conflicts..

**Comment by evanshultz** [comment]
Review notes:
- Change the decription to `±2g / 4g / 8g / 16g Tri-Axis Digital Accelerometer, I2C, 1.71-3.6V, LGA-12`
- Add a datasheet link. In fact, your commit does not include this.
- Add a default footprint of `Kionix_LGA-12_2x2mm_P0.5mm`. We do not have an existing footprint that is acceptable, but the guidelines to make the footprint are at http://kionixfs.kionix.com/en/document/TN008-PCB-Design-Guidelines-for-2x2-LGA-Sensors.pdf. Are you willing to submit this footprint?
- Change footprint filter to `Kionix*LGA*2x2mm*P0.5mm*`.
- All pin lengths should be 100mil.
- All pin styles should be Line.
- Pin name offset should be 20mil.
- It looks like the symbol can be centered better.
- I assume this is only an I2C slave so SCL should be type Input.
- Make the RES pin of type Passive.
- How did you determine INT to be Output type? I don't see adequate information in the datasheet.

**Comment by cederom** [comment]
Okay, I have switched to KiCAD 5. Will update all stuff next week. Thank you for your time, feedback and hints @evanshultz :-)

**Comment by evanshultz** [comment]
Great! v5 is dramatically better than v4. :)

**Comment by antoniovazquezblanco** [comment]
@cederom Can you fix the merge conflicts?

Thank you!

**Comment by antoniovazquezblanco** [comment]
I have resolved the conflicts. There are still review changes pending. @cederom will you be looking at this?

**Comment by cederom** [comment]
Thank you! Will do this week - after hardware verification almost done - sorry for the delays! :-)

**Comment by antoniovazquezblanco** [comment]
No hurry, just querying! Thank you very much!

**Comment by evanshultz** [comment]
@cederom 
There are more merge conflicts and review comments above. Are you still planning to come back to this?

**Comment by cederom** [comment]
okay will review and update :-)

**Comment by evanshultz** [comment]
@cederom 
Hi! Are you still willing to make the changes requested above so this PR can be merged?

**Comment by cederom** [comment]
Sorry, I forgot about that :-( I have some other symbols added in the meantime so will get into this.. if you can update it yourself so it works please do so and we all save some time :-)

**Comment by cederom** [comment]
Hmm.. I cannot open that commit anymore in KiCAD5.. shall I rewrite that from scratch? Can someone please export that component to a single lib file? Any hints? :-)

**Comment by cederom** [comment]
Allright the branch has been rebased with upstream master and I did a redraw from scratch that was the fastest way :-)

* [X] Change the decription to ±2g / 4g / 8g / 16g Tri-Axis Digital Accelerometer, I2C, 1.71-3.6V, LGA-12
* [X] Add a datasheet link. In fact, your commit does not include this.
* [X] Add a default footprint of Kionix_LGA-12_2x2mm_P0.5mm. We do not have an existing footprint that is acceptable, but the guidelines to make the footprint are at http://kionixfs.kionix.com/en/document/TN008-PCB-Design-Guidelines-for-2x2-LGA-Sensors.pdf. Are you willing to submit this footprint?
* [X] Change footprint filter to Kionix*LGA*2x2mm*P0.5mm*.
* [X] All pin lengths should be 100mil.
* [X] All pin styles should be Line.
* [X] Pin name offset should be 20mil. <- please verify :-)
* [X] It looks like the symbol can be centered better.
* [X] I assume this is only an I2C slave so SCL should be type Input.
* [X] Make the RES pin of type Passive.
* [X] How did you determine INT to be Output type? I don't see adequate information in the datasheet. <- INT is a Push-Pull type output (see Table 4:Pin Description at datasheet Rev5.0).

**Comment by evanshultz** [comment]
Thank you!

1. Please use the official datasheet link of http://kionixfs.kionix.com/en/datasheet/KXTJ3-1057-Specifications-Rev-5.0.pdf.
1. Remove 'kionix' from the keywords.
1. Pin name offset is 40mil. Please adjust to 20mil.
1. RES pin is not Passive type. If you think it should be Input please let me know.
1. I don't see any link for https://github.com/KiCad/kicad-footprints/blob/master/Package_LGA.pretty/LGA-12_2x2mm_P0.5mm.kicad_mod, so I don't know where that footprint came from. Please use http://kionixfs.kionix.com/en/document/TN008-PCB-Design-Guidelines-for-2x2-LGA-Sensors.pdf to verify that footprint is correct or else create one per that document. Our generator at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON may support this package as well, in which case you can use the resulting footprint and not worry about matching exactly what Kionix says.

Can you post a fresh screenshot when you make those updates, please?

**Comment by cederom** [comment]
Thank you @evanshultz for your hints. Stuff updated. I just need to update the footprint - the one was already there and it worked with my board - will look into that generator script tomorrow and generate a new footrpint :-)

image

**Comment by evanshultz** [comment]
The existing footprint might work, but I would like to validate things since merging this will mean the symbol will be available to any user of the library and their expectation should be that the footprint has been verified like we always do. Thanks for checking into it!

I noticed a few other things just now:
1. Page 12 of the datasheet says the GND, VDD, and IO_VDD pins are internally connected to each other, and the power pins share a decoupling cap, so I believe they can be stacked. Is there a reason you didn't stack any of them?
1. Please move the value above the symbol, just underneath the ref des.
1. It looks like the symbol is overly big. Can you smash it vertically and horizontally by 200mil?
1. There are 10 polylines in this symbol but I think a naive implementation only needs 6 and the most elegant implementation only needs 3 (draw from the center out with a single polyline for the stem and arrowhead together). Can you look into simplifying the 3-axis graphic?

**Comment by cederom** [comment]
image

* Symbol redesign.
* Power lines stacked.
* Created footprint using generator.
  * https://github.com/KiCad/kicad-footprints/pull/2478
  * https://github.com/pointhi/kicad-footprint-generator/pull/634
* Triaxis redraw.

**Comment by cederom** [comment]
image
* Only one stacked pin visible.
* Value below Reference on top of symbol.
* Footprint provided in a separate PR.

Please modify further to match your needs :-)

**Comment by evanshultz** [comment]
Thank you! It looks great.

You need to follow https://kicad-pcb.org/libraries/klc/S4.3/, and this is the special case of power pins. One is visible with the expected pin type, and the others are invisible with Passive type.

And please put power pins on top and ground on bottom.

**Comment by cederom** [comment]
Well.. I am not sure if we should apply a quick fix and mark power lines as passive because of current issues with KiCAD / Travis script.. but as you requested I did.. also the pin locations top and bottom.

**Comment by cederom** [comment]
Footprint is updated:

https://github.com/KiCad/kicad-footprints/pull/2478

Symbol will also work with `LGA-12_2x2mm_P0.5mm.kicad_mod` that is already present in a release library.

Thank you for all your support and see you on GitLab side :-)

**Comment by evanshultz** [comment]
Thank you as well.

As noted in the footprint PR, the existing footprint was specific for a ST part. It might have been fine here as well.

**Pull request merged**
