### PR TITLE
Rv 1805

### PR DESCRIPTION
**Pull request by jneiva08**
Created footprint for RTC RV-1805-C3 from MicroCrystal

Datasheet: https://www.microcrystal.com/fileadmin/Media/Products/RTC/Datasheet/RV-1805-C3.pdf

Symbol:
rv_1805-c3_symbol

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] Description has wrong format and should ends with package name, for example `Realtime Clock/Calendar I2C Interface, Extreme Low Power, MicroCrystal DFN-10`
- [ ] Footprint and footprint filter should be fixed, the package is generic, should not be in RTC library, probably in DFN packages. Have you got submitted a Pull Request for it ? Can you give the link here ?
- [ ] How do you know pins 3/8/10 are Open Collector and not Output ?
- [ ] The design can be pack a bit

Cheers,
Joel

**Comment by evanshultz** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1505

**Comment by myfreescalewebpage** [comment]
@jneiva08 Updated my previous comment following integration of the footprint.

**Comment by jneiva08** [comment]
@myfreescalewebpage , have remake the symbol, the size is the same of others RTC in library.
Hope i got footprint filter right.

In the application manual - https://www.microcrystal.com/fileadmin/Media/Products/RTC/App.Manual/RV-1805-C3_App-Manual.pdf page 10, says "It is an open drain output" in each pin.

The symbol now looks:
rtc

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks. Footprint filter is not correct. See my previous comment. Thanks, Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
