### PR TITLE
Added : Ai-Thinker-Ra-02 Module. Updated : Ai-Thinker-Ra-01 Module

### PR DESCRIPTION
**Pull request by marcpiulachs**
Added : Ai-Thinker-Ra-02 Module Symbol, Modified : Make All GND pins visible on Ai-Thinker-Ra-01 Symbol and replaced gnd to GND and 3.3 to VDD

Datasheets:

[Ra-01](https://wiki.ai-thinker.com/_media/lora/docs/c047ps01a1_ra-01_product_specification_v1.1.pdf)
[Ra-02](https://ecksteinimg.de/Datasheet/AI-Thinker/ra-02_product_specification_v1.1.pdf)
---
ra-02
ra-01

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by marcpiulachs** [comment]
Any comment or sugestion to improve the symbol ?

**Comment by myfreescalewebpage** [comment]
@marcpiulachs can your rebase so it's possible to review the PR properly ? Is it also possible to check datasheet link of RA-01 because I'm not able to view it properly too ? Thanks, Joel

**Comment by marcpiulachs** [comment]
Ok [RA-01](http://wiki.ai-thinker.com/_media/lora/docs/c047ps01a1_ra-01_product_specification_v1.1.pdf)

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @marcpiulachs , thanks for rebase and the link

A few comments I have during my review:

Ai-Thinker-Ra-01
- [ ] Can you indicate the datasheet link of the device in the library too (http://wiki.ai-thinker.com/_media/lora/docs/c047ps01a1_ra-01_product_specification_v1.1.pdf) ?
- [ ] Can you improve the description: `Ai-Thinker Ra-01 410-525 MHz LoRa Module, SPI interface, external antenna` is great I think
- [ ] Pin length should be 100mil for this symbol (<100pins)
- [ ] Name of pin 1 should be "ANT" and this pin should be Passive
- [ ] Name of pin 4 should be "~RESET"
- [ ] Pin 12 (SCK) should be Input
- [ ] GND pins should be stacked
- [ ] The position of the pins is not very nice (DIO can be used to switch ANT signal for example). Here is my proposition:

Capture

Ai-Thinker-Ra-02
- [ ] Can you indicate the datasheet link of the device in the library on ai-thinker wiki instead (http://wiki.ai-thinker.com/_media/lora/docs/c048ps01a1_ra-02_product_specification_v1.1.pdf) ?
- [ ] Can you improve the description: `Ai-Thinker Ra-02 410-525 MHz LoRa Module, SPI interface, U.FL antenna connector` is great I think
- [ ] Pin length should be 100mil for this symbol (<100pins)
- [ ] Name of pin 4 should be "~RESET"
- [ ] Pin 12 (SCK) should be Input
- [ ] GND pins should be stacked
- [ ] The position of the pins is not very nice (DIO can be used to switch ANT signal for example). I propose to make the same symbol than Ra-01 without ANT pin.

The Pull Request modify the RA01 symbol and thus it will only possible to merge it during a major release (V6).

Cheers,
Joel

**Comment by marcpiulachs** [comment]
Hi @myfreescalewebpage I Agree with your proposals maybe except for the stacked GND pins, is that a formal requeriment? I can see lots of symbols with independent GND pins. is there a rule for that?

**Comment by myfreescalewebpage** [comment]
When the GND pins are internally connected yes it is a strong requirement of the KLC (https://kicad-pcb.org/libraries/klc/S4.3/).

Many old symbols have not been updated it's why you can found many of them with GND pins separated, but since few years now we try to make the new symbols and the enhancements of the existing symbols to match the KLC the best we can do.

I think this pull request is a great opportunity to enhance Ra-01 symbol as you already started :-)

**Comment by myfreescalewebpage** [comment]
@marcpiulachs ping! These are very cool devices which will be appreciated in KiCad :)

**Comment by marcpiulachs** [comment]
Gi @myfreescalewebpage , I think I solved all the remaining problems with the symbols. 
As a side note the whole process of contributing symbols and footprints feels a little bit complicated. I made the original submission on July and didn't got any feedback till 9 months later. I understand is a voluntary work but from the contributor point of view it's discouraging, i had other symbols in the pipeline that never commited for that reason. May be the process can be optimized somewhay or the reviewer may modify the errors and commit straightaway? Just thinking loud.

**Comment by myfreescalewebpage** [comment]
Hello @marcpiulachs 
Thanks for the update.
First yes I understand your message, I have made the same a long time ago and decided to help the reviews. I started to participate to the reviews and finally integrated the KiCad team. We are not a lot of people to do it, but we have many pull request (about 1000 every years), this is a lot of work and this explain why it is sometimes so long to have some news. I apologize but we have no other solution.
Regarding the Raxx symbols, there are few comments not addressed yet (please check my last message with checkboxes). You also have a GND stacking error reported in travis (the first GND pin should be Power Input and visible, the following should be Passive and Invisible). Let me known if this is still not clear.
Joel

**Comment by marcpiulachs** [comment]
Hello @myfreescalewebpage , thanks for your response. I have solved the remaining issues, let me know if I'm missing something. Excuse me to give you so much work!
Marc

**Comment by myfreescalewebpage** [comment]
No problem, I do it with pleasure and I'm also personally interested by these symbols.
Just remaining the datasheets link, please update with the ones I have given.
Joel

**Comment by marcpiulachs** [comment]
Ok @myfreescalewebpage , done, thank you.

**Comment by myfreescalewebpage** [comment]
Thanks for all this job, no more comment do on this PR. Because this modify Ra01 symbol we need to wait for the next KiCad major release (v6) then can be merged.

**Pull request merged**
