### PR TITLE
Change GPIO pins back to Bidirectional for Microchip AVR symbols

### PR DESCRIPTION
**Pull request by fauxpark**
As pointed out in #2118, the Tri-state pin type for these symbols' GPIO pins is wrong, and they should just be Bidirectional instead.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
https://github.com/KiCad/kicad-symbols/issues/387

**Comment by cpresser** [comment]
image

**Comment by poeschlr** [comment]
@cpresser are you aware of https://github.com/KiCad/kicad-library-utils/blob/master/schlib/comparelibs.py ?

**Comment by cpresser** [comment]
> @cpresser are you aware of https://github.com/KiCad/kicad-library-utils/blob/master/schlib/comparelibs.py ?

Tbh I have not looked at it into detail before.
I just tested it and in this case I don't think it is useful. I already know that basically all symbols in the lib have been changed.

Anyway, related question: Is there also a clever way to feed two git commit-ids to comparelibs?

**Pull request merged**
