### PR TITLE
NVE Angle sensors and Microchip ATSAMC2x 

### PR DESCRIPTION
**Pull request by TiZed**
Hello,

Added the following symbols:
- NVE AAT003 & NVE AAT101 angle sensors, footprint pull request [KiCad/kicad-footprint#1647](https://github.com/KiCad/kicad-footprints/pull/1647).
  AAT003 Datasheet: https://www.nve.com/Downloads/AAT003.pdf
  AAT101 Datasheet: https://www.nve.com/Downloads/AAT101.pdf
  
- Microchip ATSAMC2x microcontrollers, added a Microchip SAMC library. Footprints already in library.
  ATSAMC2xG1xA-A/M Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/SAM-C20C21-Family-Datasheet-DS60001479C.pdf

- Microchip ATSAME51J1xA-M, just added the QFN variant of an existing symbol.

AAT003

AAT101

ATSAMC2x

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @TiZed thanks for this contribution,

Can you upgrade your branch, there is a modification of "MCU_Microchip_SAMC" library that is not expected, see at https://github.com/KiCad/kicad-symbols/pull/1922/files.

For the next time, this is better to separate your PR by families, Sensors in a PR for example, and MCU in another one, but OK for this now, no need to separate I will review both.

Joel

**Comment by TiZed** [comment]
Hi @myfreescalewebpage thanks for the comment, I'll separate PRs next time. I did make a fix to the SAMC library after creating the PR, which can be seen in the last commit. 
Currently Travis fails due to footprints which are pending commit in a PR in the footprint library.

**Comment by myfreescalewebpage** [comment]
> I'll separate PRs next time

No problem.

> I did make a fix to the SAMC library after creating the PR, which can be seen in the last commit.

Actually, the git diff shows you create again the lib but it is not expected, please review.

**Comment by myfreescalewebpage** [comment]
No news of the original author, indicate the PR is abandoned.

**Pull request closed without merging**
