### PR TITLE
Adding CBTL02043A, CBTL02043B

### PR DESCRIPTION
**Pull request by ki5libs**
Adding CBTL02043A, CBTL02043B
[Datasheet](https://www.nxp.com/docs/en/data-sheet/CBTL02043A_CBTL02043B.pdf)

CBTL02043x

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

- [ ] Pin offset should be 20mil (see travis error)
- [ ] Pin length should be 100mil
- [ ] VDD pins should not be stacked

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

I've changed pin offset and length. Could you tell me the reason why VDD pins shouldn't be stacked? I couldn't find any information about separate decoupling capacitors for these pins. So according to KLC I suppose to stack it.

**Comment by myfreescalewebpage** [comment]
In case of no information we give the user the opportunity to do it anyway, so by default the VDD pins are not stacked, except if the datasheet explicitly indicate capacitor are not required on all pins.

**Comment by ki5libs** [comment]
@myfreescalewebpage I'm sorry, but [S4.3 KLC](https://kicad-pcb.org/libraries/klc/S4.3/) tells exactly the opposite:
`Power supply pins must be stacked unless the datasheet specifies the need for decoupling capacitors on every pin.`
Fixing it is a matter of minutes, but on my opinion (and looks like KLC has the same view) user could place several capacitors to single pin on the schematic and then locate it on the PCB any way he wants. And if I'm wrong why KLC doesn't explain it?

**Comment by myfreescalewebpage** [comment]
I was pretty sure of the previous position, but thanks to remind my this point (or maybe the KLC changed recently). Merging current proposition.

**Pull request merged**
