### PR TITLE
Add Analog ADV7611 HDMI Receiver

### PR DESCRIPTION
**Pull request by twam**
Datasheet URL: https://www.analog.com/media/en/technical-documentation/data-sheets/adv7611.pdf
Screenshot: screenshot 2019-03-03 at 14 16 26

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @twam , thanks for contributing,

A few comments I have during my review:

- [ ] Seems the new "Interface_HDMI" library you have created in another commit is a good place for this device, isn't it ?
- [ ] Description can be enhanced and should contain the full package name at the end, `Low Power 165MHz HDMI Receiver, LQFP-64` is very nice
- [ ] I disagree with the footprint (wrong EP size), should be `Package_QFP:LQFP-64-1EP_10x10mm_P0.5mm_EP5.0x5.0mm`, which doesn't exist and should be submitted at https://github.com/KiCad/kicad-footprints/pulls using the script at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO
- [ ] Positive power pins must not be stacked, even if this enlarge a lot the size of the symbol
- [ ] Name of pin 47 is `VS/FIELD/ALSB`

Cheers,
Joel

**Comment by twam** [comment]
@myfreescalewebpage, thanks for your feedback.

Concerning the footprint I created a pull request (https://github.com/pointhi/kicad-footprint-generator/pull/307), however the scripts creating those chooses a slightly different naming (EP5x5mm instead of EP5.0x5.0mm). If I interpret the KLC correctly this should be also fine.

Concerning the positive power pins I understand from http://kicad-pcb.org/libraries/klc/S4.3/ that 'Power supply pins must be stacked unless the datasheet specifies the need for decoupling capacitors on every pin.' which is opposite to your statement.

**Comment by myfreescalewebpage** [comment]
> Concerning the footprint I created a pull request (pointhi/kicad-footprint-generator#307), however the scripts creating those chooses a slightly different naming (EP5x5mm instead of EP5.0x5.0mm). If I interpret the KLC correctly this should be also fine.

Yes it's fine !

> Concerning the positive power pins I understand from http://kicad-pcb.org/libraries/klc/S4.3/ that 'Power supply pins must be stacked unless the datasheet specifies the need for decoupling capacitors on every pin.' which is opposite to your statement.

Do the datasheet indicate the capacitors are not required ? If no information are given, we do not stack the positive power pins to let the end user making the way he wants.

**Comment by twam** [comment]
screenshot 2019-03-08 at 19 49 09

**Comment by myfreescalewebpage** [comment]
Thanks @twam no comment to do. Great job, just need to wait for the footprint now to merge this PR.

**Comment by antoniovazquezblanco** [comment]
@twam Footprint has been merged. If you could restore your branch we would love to merge your symbol!

**Comment by myfreescalewebpage** [comment]
Sorry for the delay, no more comment, merging.

**Pull request merged**
