### PR TITLE
Add USB 2.0-only Type-C receptacle and plug

### PR DESCRIPTION
**Pull request by diegoherranz**
Adding the USB 2.0-only Type-C receptacle, started from the existing USB_C_Receptacle.

Types of plug and receptacle listed in 3.1.1 of USB Type-C Specification Release 1.3
https://www.usb.org/sites/default/files/documents/usb_type-c.zip

Took advantage of this to fix broken documentation links on other type-c connectors as well as adding the official "full-featured" denomination to the existing receptacle.

Although I'm not a big fan of pin stacking, I used it on VBUS and GND to follow KLC. But not on D+/D- since they may be shorted together or routed independently to an USB switch.

The "full-featured" receptacle could use pin stacking too, but I haven't modified it to avoid breaking the library. I think that is what we're doing until KiCad 6. Let me know otherwise.

usb_c_2 0

Thanks!

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by diegoherranz** [comment]
By the way, as an example, a real-world receptacle using the USB 2.0-only spec is GCT's USB4085:
https://gct.co/connector/usb4085
Although they call it "Type C Charging Connector" instead of "USB 2.0-only" which is the official USB name for it...

**Comment by evanshultz** [comment]
Looks OK to me. A dislike having pin stacking just on a subset, though, and I think it's OK since stacking pin smartly on the existing connectors will only make them smaller but all connections can still be present (stacking them poorly could break them, though).

Note https://github.com/KiCad/kicad-symbols/issues/509.

@Ratfink 
Could you take a look since you were invested in this topic already?

**Comment by diegoherranz** [comment]
> A dislike having pin stacking just on a subset, though, and I think it's OK since stacking pin smartly on the existing connectors will only make them smaller but all connections can still be present (stacking them poorly could break them, though).

It's true, I could stack the pins on the other ones as long as we make sure nothing is broken, maybe I give it a try after this PR is done?

Re #509, I knew I had read a thread on USB-C but I couldn't find it anywhere. I've read it again and if you'd prefer to use the number of pins in the name (e.g. USB_C_Receptacle-16 for this one) instead of the USB official names, that's OK with me. Just let me know.

Thanks.

**Comment by diegoherranz** [comment]
I've added the USB 2.0-only plug based on the USB2.0-only receptacle:

usb_c_plug_2 0

Now we should have the 4 more common ones.

**Comment by evanshultz** [comment]
Nice!

@diegoherranz @Ratfink 
Do you agree on a symbol naming convention? Pin names or USB official names? Official names seem like a good way to go, but I'm not terribly familiar so I don't have a strong feeling now.

**Comment by Ratfink** [comment]
Thanks for adding the plug!

@evanshultz I don't feel that there's a disagreement on naming.

**Comment by evanshultz** [comment]
Unclear English. Not that were was any disagreement, but I am checking for agreement. :) There is a question at https://github.com/KiCad/kicad-symbols/pull/937#issuecomment-421821511 about keeping the name here or changing it. I wanted to wrap that up before merging. So... keep it or change it?

@diegoherranz 
Are you willing to stack pins on the other USB symbols after this? You indicated you'd do it above but I would like to confirm before anything gets messy.

**Comment by poeschlr** [comment]
Please do not touch existing symbols in the same PR as adding new ones.

**Comment by diegoherranz** [comment]
Yes, the pin stacking on the existing symbols would happen on a different PR.
However, technically I've modified the existing symbols since I updated their keywords, datasheets etc. on the dcm file. If you want me to, I can rebase my PR to only add new symbols.
Either way, I'll be more careful next time not to mix new stuff and modifications to existing stuff.

**Comment by evanshultz** [comment]
In this case I can handle it since it's just the descriptions of existing parts. Unless I'm told otherwise. Rene feels very strongly about this and he's the head librarian so in the future you know what's preferred. :)

So to wrap this up, @Ratfink and @diegoherranz like this symbol name?

**Comment by diegoherranz** [comment]
Summarising on the name, we could go for:

1.  `USB_C_Receptacle_USB2.0` and `USB_C_Plug_USB2.0` as in the PR currently
2. `USB_C_Receptacle_USB2.0-only` and `USB_C_Plug_USB2.0-only` to be even closer to the official USB naming.
3. `USB_C_Receptacle-16` and `USB_C_Plug-12` as in #509.

I think I would go 1 or 2 (slight preference for 2) unless we plan on adding the plug-9 and plug-24 (which would be the least common ones?), in which case we can go 3 to use the numbering naming scheme for them all, and we'd need to change the name of the existing ones.

I think I'm happy either way (1/2 or 3), and happy to help making the changes required here or further PRs.

**Comment by diegoherranz** [comment]
What do you think on the naming? I think everything else is looking OK now.
Thanks.

**Comment by Ratfink** [comment]
Either 1 or 2 sounds fine.  1 is less verbose, but 2 is closer to what USB-IF calls them, as you point out.  I don't know if "only" will ever be an important distinction though, so I'd slightly favor 1.

**Comment by diegoherranz** [comment]
Thanks @Ratfink.
In that case, everyone happy to merge?

**Comment by evanshultz** [comment]
Alright. It's at 1 now so we'll go with that.

@diegoherranz 
Thanks! You can ping me when you stack pins and shrink the other USB symbols. Make sure you retain an existing VBUS (surely the lower one) and GND pin location so they're backwards compatible.

**Comment by diegoherranz** [comment]
Thanks, @evanshultz. I've raised #1005.

**Pull request merged**
