### PR TITLE
SN65HVD1050

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added 5V CAN transceiver in SOIC-8 package
http://www.ti.com/lit/ds/symlink/sn65hvd1050.pdf

image

image

Symbol copied from existing SN65xxx series of CAN chips for compatibility.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @SchrodingersGat , thanks for contributing,

A few comments I have during my review:

- [ ] Package in the description should be completed: "SOIC-8"
- [ ] VREF should use capital letters
- [ ] According to typical application schematic page 19, I think VREF should be moved between CANH and CANL pins
- [ ] "transceiver" in keywords badly spelled

Cheers,
Joel

**Comment by evanshultz** [comment]
@SchrodingersGat Ping!

**Comment by SchrodingersGat** [comment]
All covered, I think. Thanks for the review

**Comment by myfreescalewebpage** [comment]
I have trouble with the design of the right part of the symbol, because it is not vertically centered.

Your symbol:

Capture

An other symbol I think better in the library (LTC2875-DD), except it is too large and that for this device PAD should be stacked with GND:

ltc

**Comment by SchrodingersGat** [comment]
Should we consolidate all the CAN symbols then? There are a few different sizes and shapes for them.

**Comment by myfreescalewebpage** [comment]
Good question, at least KLC errors can be improved but something more consistent between the symbol is good to have IMO. @evanshultz yours ?

**Comment by evanshultz** [comment]
I fully support the idea, but to follow the devs and Rene we can't until close to v6. But for now we can at least make future contributions attractive.

**Comment by SchrodingersGat** [comment]
image

Updated

**Comment by myfreescalewebpage** [comment]
@SchrodingersGat no more comment here, merging. Thanks for this job!

**Pull request merged**
