### PR TITLE
move ADE-6 to RF_Mixer and add ADEX-10 alias

### PR DESCRIPTION
**Pull request by hvraven**
This adds another Mixer [ADEX-10](https://ww2.minicircuits.com/pdfs/ADEX-10+.pdf) from Mini-Circuits. It is only an alias to the already existing ADE-6. As there is a RF_Mixer library by now I moved ADE-6 to the new library and added the alias there.

Screenshot_20190724_075921

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

- [ ] The datasheet link is wrong, should be `https://www.minicircuits.com/pdfs/ADEX-10.pdf`

You will have to rebase. The pull request will be merged in next major release (V6)

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

I updated the datasheet URL and rebased against the current master.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment.
There is again a new conflict but for the moment i suggest to wait because this pull request need to wait v6 for merging.
Joel

**Comment by hvraven** [comment]
merged current master to get it ready for v6

**Comment by myfreescalewebpage** [comment]
Seems will need to be done again because of other merges. I will ping you when it will be ready.

**Comment by myfreescalewebpage** [comment]
@hvraven can you solve the branch conflict here, need to check the PR and then will be merged

**Comment by hvraven** [comment]
Fixed the merge conflict and I think I did not break anything while doing so...

**Comment by myfreescalewebpage** [comment]
Last comments before merging:

- [ ] Seems ADE-6 is still in "RF.lib" file
- [ ] Descriptions should ends with package name `, CD542`

Joel

**Comment by hvraven** [comment]
Hi @myfreescalewebpage ,

thanks for the check, fixed the issues you spotted.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
