### PR TITLE
Create LT3748

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Creation of LT3748, MSOP-16 package

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing

https://www.analog.com/media/en/technical-documentation/data-sheets/3748fb.pdf

- [x] An example screenshot image is very helpful

capture

- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate

https://github.com/KiCad/kicad-footprints/pull/1457

- [x] Check the output of the Travis automated check scripts - fix any errors as required

No error except pending footprint

- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Let's put RREF on the left side with other Passive pins.
1. In just this lib we have INTVCC pins Power Output, Passive, Power Input, and Output types. It is a complicated pin to classify. I guess this is fine.

**Comment by myfreescalewebpage** [comment]
Done :)

**Comment by evanshultz** [comment]
So here is what we have now, next to a standard FET symbol:
image

What would you think about moving SENSE down relative to GATE, so the wire can connect straight across, and then moving both pins towards the bottom to give more space around RFB?

**Comment by myfreescalewebpage** [comment]
Not a bad idea :)
Done !

**Pull request merged**
