### PR TITLE
Add AD654

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.analog.com/media/en/technical-documentation/data-sheets/AD654.pdf
image
image

This felt like the best library but let me know if we have any V-F converters I didn't find or if there's a better place.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @evanshultz 

I have trouble with the transistor on pins 1/2. Sometimes pin 2 is not Power Input has shown on figure 11 page 9 of the datasheet. Seems the transistor wiring has no specific constraint. I suggest the pins 1 and 2 to be Passive:

Capture

Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Both figures on page 9 show pin 2 going to ground. Can you please check that? Since the pin is named LOGIC COMMON I expect that while it's shown as the output transistor's emitter it's also the ground for all other circuitry and the IC won't work right if it's not grounded. There could be some application where it's not, but I've not seen it and the datasheet doesn't allude to it. Have I overlooked anything?

I don't find anything regarding pin 1's type like I noted above, but it seems Open Collector is valid and isn't likely to result in any ERC or wiring issues. And it probably is truly an open collector pin. Did you find a case where this would cause issues?

**Comment by myfreescalewebpage** [comment]
@evanshultz oupsss sorry, have check again you're right, it's connected to ground.

Anyway, I'm not sure it is mandatory to connect it to the ground. First page of the datasheet it is indicated "The Logic Common terminal can be connected to any level between ground (or –VS) and 4 volts below +VS". I think emitter follower configuration is possible.

**Comment by evanshultz** [comment]
Ah. Thanks for pointing that out. The change you're suggesting seems OK but I'm curious now.

My guess is that emitter follower is not possible as the pin is also the 'bottom' of internal current sources which need 4V+ to operate. I asked ADI for clarification.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Response from ADI:
```
The FOUT signal is referenced to LOGIC COMMON. In the datasheet diagrams, the pin is connected to GND (0V) externally. The NPN emitter is connected to the same potential. 
The LOGIC COMMON can be connected to a DC voltage from –VS to (+VS – 4V). The reference voltage for FOUT changes accordingly.
The LOGIC COMMON is not connected to other circuitry internally.
```

So my guess was wrong. Since pin 2 needs to be connected to a DC voltage I'm still in favor of keeping Power Input type. And would Open Collector still be fine for pin 1?

**Comment by myfreescalewebpage** [comment]
Ok with the current status, you can post a fix later if you have ERC issues for example.

**Pull request merged**
