### PR TITLE
Add DIO6970 24V Buck Converter

### PR DESCRIPTION
**Pull request by awigen**
# Symbol

dio6970

# Datasheet 

https://www.mouser.com/catalog/specsheets/DIOO-07-31-2018-DIO6970%20V0.4.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @awigen 

Not a full review now but the first comments:
- [ ] You should indicate a better datasheet, i.e., not on mouser website
- [ ] Voltage regulators are smaller, the height of your symbol is too much important

Thanks
Joel

**Comment by myfreescalewebpage** [comment]
@awigen ping

**Comment by awigen** [comment]
* Changed datasheet link
* Reduced symbol size

dio

**Comment by myfreescalewebpage** [comment]
Clearly better. Full review below:

- [ ] Description should ends with the package name: `High-Efficiency 2A, 24V Input Synchronous Step Down Converter, SOT-23-6`
- [ ] SW should be Power Output

Else, looks good

Joel

**Comment by myfreescalewebpage** [comment]
@awigen ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by awigen** [comment]
Fixed the last two issues:
* Description updated with `STO-23-6`
* Pin 2 changed to power output

image

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
