### PR TITLE
Add BQ27441 Fuel Guage from TI

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo J <mail@aurabindo.in>

Add TI BQ27441 and its variants. Datasheet: http://www.ti.com/lit/ds/symlink/bq27441-g1.pdf
This footprint was created with git revision b05a40e72815650ab84 of KiCad

Default footprint has been associated to `Package_SON:Texas_S-PDSO-N12.kicad_mod`

Screenshot:
bq27441_kicad

bq27441_alias

bq27441_alias
bq27441_desc
bq27441_settings

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate - *No matching PR, footprint already exists*
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aurabindo** [comment]
Strange, I didn't modify those libraries which are having errors 😕

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution. Nice work!

I spotted two minor problems. Could you please fix them?
1. Please add the package-name to the description field
2. move the NC-pins, so their end lies on the symbol outline ... this way it is much less probable to connect to them unwantedly:
2017-11-07 22_08_36-part library editor -- d__kicad_kicad-library-review_library_atmel lib

**Comment by aurabindo** [comment]
I'm hoping this is it what you meant ?

bq27441_desc

**Comment by aurabindo** [comment]
@jkriege2  In the diff, I notice that in the `.lib` file, Eeschema version is also changed by the tool to 2.4, from 2.3. Somewhere I remember reading that the libraries are not meant to contain any features that are not released in stable. Is this going to be an issue ?

**Comment by jkriege2** [comment]
about version: No, the version should be fine, as the libs here are meant for v5, which will have all the new features. 

about description: No, you should not have the symbol-name in the description, What I meant was simply adding the package/footprint name to the description, e.g. `System Side Li Ion/Polymer Fuel Gauge, 4.30-4.35V, PDSON-12`

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
