### PR TITLE
Added Microchip PIC18F2xK22 I/P microcontrollers.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**
Added Microchip PIC18F2xK22 I/P microcontrollers. Includes PIC18F23K22 I/P, PIC18F24K22 I/P, PIC18F25K22 I/P, PIC18F26K22 I/P.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
http://ww1.microchip.com/downloads/en/DeviceDoc/40001412G.pdf
- [x] An example screenshot image is very helpful
Capture d’écran_2020-04-17_18-18-58

- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [NA] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [NA] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
Thanks for your contribution.


- [ ] Naming: I think that the package suffix should be `SP` for SPDIP and not `P` for PDIP (see "Add to cart" on https://www.microchip.com/wwwproducts/en/PIC18F23K22). There is a dash and not an underscore on the original part number. Also, the temperature rating is replaced with a wildcard (see [KLC S2.2](https://www.kicad-pcb.org/libraries/klc/S2.2/)). The parts should be called `PIC18F23K22-xSP`, `PIC18F24K22-xSP`, etc.
- [ ] VSS pins should be stacked (see [KLC S4.3](https://www.kicad-pcb.org/libraries/klc/S4.3/))
- [ ] MCLR is input only, even when working as GPIO, more like GPI ;)
- [ ] It was agreed for Microcontrollers in the library, that we wouldn't list all the alternate functions of the pins because the symbol gets very verbose. However, for PICs it was accepted to include the alternate functions of the most important ones, e.g. oscillator, reset, debugging. You can see `PIC18F25K83-xSP` as a reference. Could you do something similar?
- [ ] I would place the MCLR pin on the top left. You can move RCx to the right hand side to avoid making the symbol longer. Again, you can use `PIC18F25K83-xSP` as a reference.
- [ ] Can you add `B` (bytes) as applicable in the descriptions?

I will review the pinout carefully after these changes (given that the pins will be modified).

Thanks again for your contribution and I hope it is the first of many!

**Comment by RICCIARDI-Adrien** [comment]
Thank you for your precise answer. I should have fixed all the issues !

**Comment by diegoherranz** [comment]
Looks OK. Just a minor one, to be closer to the datasheet, I think would use the following pin names:

- ~MCLR/RE3 or ~MCLR/VPP/RE3
- RB7/PGD
- RB6/PGC

That is, the Rxy first, except for the MCLR pin.
Could you change that?
Thanks.

**Comment by diegoherranz** [comment]
- Pinout looks correct
- Footprint and footprint filter look OK

Thanks for the quick fix. Merging.

**Pull request merged**
