### PR TITLE
fix electrical type on GPIO pins in ATmega128, ATmega640, ATmega64L

### PR DESCRIPTION
**Pull request by ioch**
On few ATmega MCU PORT C was marked as Output and PORT F was marked as Input. All of these are are capable of  being Inputs, Outputs or high-z  therefore I changed them to be Bidirectional same as other GPIO
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by fauxpark** [comment]
Hi, please have a look at #387. This is next on my todo list, but I'm still waiting on #525 to be merged first :)

**Comment by evanshultz** [comment]
@ioch 
Thanks for contributing to KiCad! It's because of a willing community like you that the library can grow and improve.

You will find a list of rules and guidelines for the KiCad library at http://kicad-pcb.org/libraries/klc/. Please see that webpage for more information about the review items below.

In this case, https://github.com/KiCad/kicad-symbols/pull/661 will likely break your branch and is more important to get done for v5. So I will review and hopefully merge that PR first and then leave it to you and @fauxpark to work out resolving this PR, #525, and then continuing on. Sorry for the bad news but thanks for taking such initiative!

**Comment by evanshultz** [comment]
@ioch @fauxpark 
Is this PR still valid? It looks good to me. Merge?

**Comment by fauxpark** [comment]
I don't see anything wrong with it. I'm surprised there are no conflicts!

**Comment by evanshultz** [comment]
Me too! Then I will merge.

**Pull request merged**
