### PR TITLE
Add CDP1802ACE

### PR DESCRIPTION
**Pull request by joshtyler**
Add CDP1802ACE CPU

Datasheet: http://www.cosmacelf.com/publications/data-sheets/cdp1802.pdf

Screenshot:
screenshot

Footprint is already in official footprint library

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Thanks for contributing,

A few comments I have during my review:
- The pin name position offset should be 20mil (KLC S3.6)
- The pins should be 100mil (KLC S3.1)
- The Clock line should be line
- The SC0 should be first an then SC1

**Comment by jneiva08** [comment]
can you add ", PDIP" at end of description
missed earlier.

@antoniovazquezblanco when this last last request done, I think is ready to merge

**Comment by joshtyler** [comment]
@jneiva08 @antoniovazquezblanco Done!

**Comment by myfreescalewebpage** [comment]
Hi @joshtyler, thanks for contributing,

Some few additional comments I have during my review:

- [ ] You can remove "CPU, CMOS" in front of the description
- [ ] Description must ends with complete package type, so modify to `, DIP-40`
- [ ] The name of pin 1 is CLOCK, not CLK
- [ ] Reference "U?" should be in top left corner of the symbol
- [ ] You can move name closer to the symbol

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@joshtyler up ?

**Comment by joshtyler** [comment]
@myfreescalewebpage sorry I was away over the holidays. This latest commit should fix those issues.
cdp

**Comment by myfreescalewebpage** [comment]
@joshtyler no worries :)
Your commit looks good ! No more comment to do, merging.
Joel

**Pull request merged**
