### PR TITLE
Add OPA1641 operational amplifier + fix erros in Amplifier_Operational.lib

### PR DESCRIPTION
**Pull request by jcyrax**
New part OPA1641 symbol.
No aliases!
http://www.ti.com/lit/ds/symlink/opa1641.pdf
symbol
descr
fp_filter
options

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jcyrax** [comment]
Travis fails because of other parts. My kicad version touches pin ordering. I could fix those errors if its ok to include them together with this PR.

**Comment by jcyrax** [comment]
I left S3.6 because otherwise pin names are very close and otherwise symbol will become very large. This is practically for all opamps in lib.

**Comment by poeschlr** [comment]
A lot of the problems you fixed might have already been fixed by the recently merged pull request https://github.com/KiCad/kicad-symbols/pull/150

For this reason your PR will need manual merging with the current master.

**Comment by jcyrax** [comment]
Should I do a merge locally in my branch and then push update to my PR?

**Comment by jkriege2** [comment]
yes, like that ... you can also rebase your branch onto a current master, so there is no extra commit for the merge.

Best,
JAN

**Comment by poeschlr** [comment]
Just a heads up: rebase requires a forced push.

**Comment by jcyrax** [comment]
OK, this I need help with. OPA330xxYFF fails because it has footprint set, but it doesn't exist. If I add only generic filter like \*DSBGA\* it throws me error that it expects exact footprint. Also part was left like this in #150 so I'm thinking there is some reason to leave it like this even if there is no footprint.

**Comment by evanshultz** [comment]
@jcyrax 
Please use **Texas_DSBGA-5_0.822x1.116mm_Layout2x1x2_P0.4mm** and a matching FPfilter. I've created https://github.com/KiCad/kicad-footprints/issues/253 to capture the need for this missing footprint.

**Comment by jcyrax** [comment]
Changed footprint and filter

**Comment by jkriege2** [comment]
Looks good up to one slight thing: Please addd the package options to the description, i.e. add `, SOIC-8/VSSOP-8`

Then I can merge!

Thanks,
JAN

**Comment by jcyrax** [comment]
Done, I somehow forgot it again.
Could you please explain a bit this rule? It says

> For symbols with a default footprint, the human-readable footprint name should be appended to the description e.g. SOIC-8

Would this mean practically every symbol needs this added? I don't quite get what is default footprint. My intuition was that if you fill footprint field then this would apply.

**Comment by poeschlr** [comment]
Yes, if you fill the footprint field this does apply. And you are also right that most symbols require filling of the footprint field. Only generic symbols are allowed to leave it empty. (New generic symbols are not allowed in most libs. They should only be in libs like device, connector_* and switch.)

**Comment by jkriege2** [comment]
Thanks, Jan

**Pull request merged**
