### PR TITLE
Add LTC-4627Jx 7-segment displays

### PR DESCRIPTION
**Pull request by Schlumpf**
Datasheets:
 - http://optoelectronics.liteon.com/upload/download/DS30-2001-393/C4627JG.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2008-0116/LTC-4627JD-01.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2000-192/C4627JF.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2001-393/C4627JG.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2000-185/LTC-4627JR.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2000-186/LTC-4627JS.pdf

image

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2109

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- ~Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)~
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- ~Give a reason behind any intentional library convention rule violation.~

### CODE REVIEW

**Comment by Schlumpf** [comment]
Travis is complaining about not merged footprint: https://github.com/KiCad/kicad-footprints/pull/2109

**Comment by myfreescalewebpage** [comment]
Hi @Schlumpf , thanks for contributing,

A few comments I have during my review:

- [ ] LTC-4627JF: color is "yellow orange", not orange only
- [ ] LTC-4627JR: color is "super red", not red only
- [ ] LTC-4627JD and LTC-4627JD-01: color is "hyper red", not red only

Else no comment, just need to wait the footprint.

Cheers,
Joel

**Comment by Schlumpf** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging following integration of the fp

**Pull request merged**
