### PR TITLE
converter-acdc: add HLK module series

### PR DESCRIPTION
**Pull request by karlp**
HLK-5Mxx and HLK-PMxx are cheap ac/dc modules, readily available on ali
express and friends. Symbol copied from a meanwell module.

HLK-5Mxx: http://www.hlktech.net/product.php?CateId=9
HLK-PMxx: http://www.hlktech.net/product.php?CateId=10

Signed-off-by: Karl Palsson <karlp@tweak.net.au>

screenshot from 2018-11-16 23-33-26

Footprints PR in https://github.com/KiCad/kicad-footprints/pull/1092

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by karlp** [comment]
S5.1: yes, can't have a footprint until the corresponding footprint PR lands: https://github.com/KiCad/kicad-footprints/pull/1092

S6.2: what?  Datasheet field must be EMPTY ?what? how does this work?

S6.3 "Part meta-data is filled in as appropriate
    Component HLK-PM01 has metadata errors:
     - Missing DOCUMENTATION FILE NAME field on 'Properties > Description' tab"  I'm sorry, I don't know what this means, wrt to the KLC.  I'm happy to work with this, I just don't follwo what I need to do.

S5.2 yes, I didn't make a footprint for this version.  Is that really required? How do we move forward in this chicken and egg world?  If the xxx-PMxx footprint lands I cna work on the xxx-5M parts, but I don't really follow the requirement here.

**Comment by antoniovazquezblanco** [comment]
Hi @karlp I will be reviewing your PR.

1. I would like to ask you to add vertical dashed lines indicating that the power supply has galvanic isolation. It is not yet in the KLC but it will soon be added to it (see https://github.com/KiCad/kicad-website/issues/284 for more information). Lets get ahead and add it please.

> S5.1: yes, can't have a footprint until the corresponding footprint PR lands: KiCad/kicad-footprints#1092

2. I will be having a look at the footprint PR. Don't worry about the message footprint not found. On the other hand your current Footprint Filter is set to `Converter*ACDC*MeanWell*IRM*02*`, please change it to match your footprint name.

> S6.2: what? Datasheet field must be EMPTY ?what? how does this work?

3. Yes, that field must be empty. It is meant for the user to fill in case the user wants to go for another documentation file other than the one we provide.

> S6.3 "Part meta-data is filled in as appropriate
Component HLK-PM01 has metadata errors:
> Missing DOCUMENTATION FILE NAME field on 'Properties > Description' tab" I'm sorry, I don't know what this means, wrt to the KLC. I'm happy to work with this, I just don't follwo what I need to do.

To fix that complaint click on the button shown with a 1 in the image and fill the field marked with a 2 with the link to the apropiate datasheet to the component.

imagen

> S5.2 yes, I didn't make a footprint for this version. Is that really required? How do we move forward in this chicken and egg world? If the xxx-PMxx footprint lands I cna work on the xxx-5M parts, but I don't really follow the requirement here.

Don't worr about it. Just provide a link to the corresponding pull request with the footprint.

Thank you

**Comment by antoniovazquezblanco** [comment]
It seems there has been some changes to the behaviour of that field. Let's wait for it to get resolved.

See https://lists.launchpad.net/kicad-developers/msg38378.html for more info.

**Comment by antoniovazquezblanco** [comment]
I think the bug has been fixed in the latest nightly. Could you please update and check if the latest version works?

Thank you @karlp

**Comment by karlp** [comment]
Updated kicad, got a new field I can fill in, and filled in the right fields now :)

**Comment by karlp** [comment]
Ok, fixed the ? in the PMxx filter.

I haven't added the HLK-5Mxx footprints yet, I've been making sure I can competently land the PMxx footprint first.  I've added the appropriate footprint filter, but there simply isn't a footprint for the 5M yet.

**Comment by antoniovazquezblanco** [comment]
Ohh I see. I will be waiting for the review process on the footprints. No worries.

Thank you for your contribution btw!

**Comment by karlp** [comment]
OK, so there really is absolutely no point in submitting symbols until footprints have been accepted then.  I asked that at the beginning.  I included the 5M versions because they are all the same symbol, but I'm not even _starting_ on a footprint for them until any other footprints are accepted.  Would you really rather just drop the 5M parts altogether? That seems wasteful.    I reallllllly don't understand why you have these in two separate repositories, it makes the contribution process significantly more complicated.  It would be fine if they were allowed to develop independently, but if you're tying them together this tightly, it seems just unnecessary hurdls.

**Comment by poeschlr** [comment]
The point would be that you get feedback on the symbol in general. The only requirement is that the footprint PR is started at the same time. We can then review everything except footprint assignment. As soon as the footprint is accepted we can re trigger travis. If no other problem persists in the symbol PR at that point in time then it can be merged immediately. If however there are still issues remaining then they need of course be fixed.

There is a reason we typically request one pull request per contribution ;) (Aliases can be included in the same PR. But not full on symbols.)
I don't quite understand why you insist on making the live of us maintainers that hard. We have our processes. These have been matured over a long time now. (Really we know what we are doing.)

**Comment by karlp** [comment]
And I'm trying, I am, otherwise I wouldn't still be here.  It just seems like all the actual steps to take are only found by submitting, and getting multiple rounds feedback.  It has felt _wildly_ difficult to actually just read a contributors guide and then just _do the right thing_

Moving forward, would it be best to then just drop the 5M modules from this PR?  I can keep it locally, so it can be "easily" re-added later if/when I make a footprint for them.

**Comment by antoniovazquezblanco** [comment]
I am ok with you dropping one of the symbols if you want to submit them in the future.

I understand your frustration, but in order to keep a minimum quality level over the libs, we cannot accept symbols that do not have a footprint. That would be quite confusing for newcomers.

Thank you

**Comment by karlp** [comment]
Ok, I've dropped this down to just the symbols that have a matching footprint PR, I believe both of these should now be "ready"

**Comment by poeschlr** [comment]
@antoniovazquezblanco do you have anything to add here or can this be merged? (Too much discussion about unreleated stuff for me to care to read through it all)

**Comment by antoniovazquezblanco** [comment]
Yes, looks fine to me. 

Thank you both!

**Pull request merged**
