### PR TITLE
Converter_DCDC_ACDC

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Work in progress.

Issues:
- [ ] FSDH321L filters & footprint
- [ ] FSDL321L filters & footprint
- [ ] FSL136MRT filters & footprint
- [ ] FSQ0565RSLDTU filters & footprint
- [ ] FSQ0565RSWDTU filters & footprint
- [ ] FSQ0565RQLDTU filters & footprint
- [ ] FSQ0565RQWDTU filters & footprint

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Can you also please split these into:

* Converter_ACDC
* Converter_DCDC

Thanks :)

**Comment by antoniovazquezblanco** [comment]
I was just having a look at the lib. It is quite a little mess. Will take some time as I cannot script this...

**Comment by SchrodingersGat** [comment]
Check out this script - https://github.com/KiCad/kicad-library-utils/blob/master/schlib/move_symbols.py

It is what I have been using to transfer all the symbols across from the old library. It allows you to redirect symbols based on wildcard pattern matches.

**Comment by antoniovazquezblanco** [comment]
I was trying to have a look at them because many of them have footprint and filter problems. The thing is that I have found myself burried in a pile of work for the next two weeks that I fear will not let me work on this during that time.

If you need me to finish this before then I am sorry but I will not be able to.

Thank you for your patience

**Comment by SchrodingersGat** [comment]
@antoniovazquezblanco how is this progressing? We are nearing the stage that we will need to mark the libraries for release, so this needs to be completed quite soon.

**Comment by antoniovazquezblanco** [comment]
I have not worked on it for quite a while. From what I remember AC DC modules need little to no work but DC DC modules seem to need quite some work.

I am not sure when I will have time to tackle this. I was also having a look at the 3d models for this elements but I fear this may be more important for you isn't it?

**Comment by jkriege2** [comment]
How many of these are already in the new repo? Look there (e.g.):
- https://github.com/KiCad/kicad-symbols/blob/master/Regulator_Switching.dcm
- https://github.com/KiCad/kicad-symbols/blob/master/Converter_DCDC.dcm
- https://github.com/KiCad/kicad-symbols/blob/master/Regulator_Controller.dcm

best,
JAN

**Comment by antoniovazquezblanco** [comment]
Following PR replaces this one:

https://github.com/KiCad/kicad-symbols/pull/151

**Pull request closed without merging**
