### PR TITLE
Add WE-TVS-82400102 TVS Diode

### PR DESCRIPTION
**Pull request by cp-aquila**
Add WE-TVS-82400102 TVS Diode

Datasheet: https://katalog.we-online.de/pbs/datasheet/82400102.pdf
grafik
grafik

This is pretty similar to USBLC6-2SC6, but has an additional diode, so I made a new symbol.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cp-aquila** [comment]
I choose this style over the one of USBLC6-2SC6 which is already in the library since it looks nicer in the schematic:
grafik

**Comment by myfreescalewebpage** [comment]
Hi @cp-aquila , thanks for contributing,

A few comments I have during my review:

- [ ] You can improve the description and it should be terminated with the package name, I propose: `Low Capacitance TVS Diode Array, 2 Channels, SOT-23-6`

Else, no comment to do.

Cheers,
Joel

**Comment by cp-aquila** [comment]
Thanks for the review @myfreescalewebpage 

Since most other diodes in the library are 'unfilled'  I applied the same here (some unfills were made here: https://github.com/KiCad/kicad-symbols/pull/2301).

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Merging.

**Pull request merged**
