### PR TITLE
Added FE1.1s 4 Port USB Hub Controller

### PR DESCRIPTION
**Pull request by jamesrlucas**
Added FE1.1s USB hub. Again, I've included an schematic example, aiming for a clean look without too many crossed wires!

[Datasheet](https://cdn-shop.adafruit.com/product-files/2991/FE1.1s+Data+Sheet+(Rev.+1.0).pdf) - There is an error in the datasheet - Pin DMU is listed as 25 - it is actually 15, and I have confirmed this on a working board. Also listed are pin numbers for a LQFP package - but there is no pinout diagram or package dimensions for it.

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @jamesrlucas , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name: `USB 2.0 High Speed 4-Port Hub Controller, SSOP-28`
- [ ] Pin 15 and 16 are crossed. Pin 15 should be DMU and pin 16 should be DPU !!
- [ ] VD33_O, VD33, VD18_O and VD18 should go to the top of the symbol

Cheers,
Joel

**Comment by jamesrlucas** [comment]
All done!

James

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Merging.

**Pull request merged**
