### PR TITLE
Various symbol fixes 2

### PR DESCRIPTION
**Pull request by evanshultz**
Follow on from https://github.com/KiCad/kicad-symbols/pull/276, but branched from an updated master so there aren't conflicts.

ADC128D818 image:
image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Note that all of the "removed" symbols have actually been made into an ALIAS. They haven't actually been removed from our library.

**Comment by jkriege2** [comment]
Hi!

could you please (in future) split the different groups of devices in future PRs (e.g. by library). That would make review much easier.

1. The ADC looks good to me.
2. But when I check out this branch and load it in KiCAD I get this (rather long) error message:
```
21:32:15: Alias 'BSB008NE2LX' not found in library: 'Transistor_FET.dcm' at line 99 offset 17
21:32:15: Alias 'BSB012NE2LXI' not found in library: 'Transistor_FET.dcm' at line 105 offset 18
21:32:15: Alias 'BSB013NE2LXI' not found in library: 'Transistor_FET.dcm' at line 111 offset 18
21:32:15: Alias 'BSB014N04LX3' not found in library: 'Transistor_FET.dcm' at line 117 offset 18
21:32:15: Alias 'BSB015N04NX3' not found in library: 'Transistor_FET.dcm' at line 123 offset 18
21:32:15: Alias 'BSB028N06NN3' not found in library: 'Transistor_FET.dcm' at line 129 offset 18
21:32:15: Alias 'BSB044N08NN3' not found in library: 'Transistor_FET.dcm' at line 135 offset 18
21:32:15: Alias 'BSB056N10NN3' not found in library: 'Transistor_FET.dcm' at line 141 offset 18
21:32:15: Alias 'BSB104N08NP3' not found in library: 'Transistor_FET.dcm' at line 147 offset 18
21:32:15: Alias 'BSB165N15NZ3' not found in library: 'Transistor_FET.dcm' at line 153 offset 18
21:32:15: Alias 'BSB280N15NZ3' not found in library: 'Transistor_FET.dcm' at line 159 offset 18
21:32:15: Alias 'BSF030NE2LQ' not found in library: 'Transistor_FET.dcm' at line 369 offset 17
21:32:15: Alias 'BSF035NE2LQ' not found in library: 'Transistor_FET.dcm' at line 375 offset 17
21:32:15: Alias 'BSF450NE7NH3' not found in library: 'Transistor_FET.dcm' at line 381 offset 18
21:32:15: Alias 'IRF40DM229' not found in library: 'Transistor_FET.dcm' at line 1269 offset 16
21:32:15: Alias 'IRF60DM206' not found in library: 'Transistor_FET.dcm' at line 1287 offset 16
21:32:15: Alias 'IRF6613' not found in library: 'Transistor_FET.dcm' at line 1293 offset 13
21:32:15: Alias 'IRF6614' not found in library: 'Transistor_FET.dcm' at line 1299 offset 13
21:32:15: Alias 'IRF6616' not found in library: 'Transistor_FET.dcm' at line 1305 offset 13
21:32:15: Alias 'IRF6617' not found in library: 'Transistor_FET.dcm' at line 1311 offset 13
21:32:15: Alias 'IRF6618' not found in library: 'Transistor_FET.dcm' at line 1317 offset 13
21:32:15: Alias 'IRF6620' not found in library: 'Transistor_FET.dcm' at line 1323 offset 13
21:32:15: Alias 'IRF6621' not found in library: 'Transistor_FET.dcm' at line 1329 offset 13
21:32:15: Alias 'IRF6622' not found in library: 'Transistor_FET.dcm' at line 1335 offset 13
21:32:15: Alias 'IRF6623' not found in library: 'Transistor_FET.dcm' at line 1341 offset 13
21:32:15: Alias 'IRF6628' not found in library: 'Transistor_FET.dcm' at line 1347 offset 13
21:32:15: Alias 'IRF6631' not found in library: 'Transistor_FET.dcm' at line 1353 offset 13
21:32:15: Alias 'IRF6635' not found in library: 'Transistor_FET.dcm' at line 1359 offset 13
21:32:15: Alias 'IRF6636' not found in library: 'Transistor_FET.dcm' at line 1365 offset 13
21:32:15: Alias 'IRF6637' not found in library: 'Transistor_FET.dcm' at line 1371 offset 13
21:32:15: Alias 'IRF6641' not found in library: 'Transistor_FET.dcm' at line 1377 offset 13
21:32:15: Alias 'IRF6643' not found in library: 'Transistor_FET.dcm' at line 1383 offset 13
21:32:15: Alias 'IRF6644' not found in library: 'Transistor_FET.dcm' at line 1389 offset 13
21:32:15: Alias 'IRF6646' not found in library: 'Transistor_FET.dcm' at line 1395 offset 13
21:32:15: Alias 'IRF6648' not found in library: 'Transistor_FET.dcm' at line 1401 offset 13
21:32:15: Alias 'IRF6655' not found in library: 'Transistor_FET.dcm' at line 1407 offset 13
21:32:15: Alias 'IRF6662' not found in library: 'Transistor_FET.dcm' at line 1413 offset 13
21:32:15: Alias 'IRF6665' not found in library: 'Transistor_FET.dcm' at line 1419 offset 13
21:32:15: Alias 'IRF6668' not found in library: 'Transistor_FET.dcm' at line 1425 offset 13
21:32:15: Alias 'IRF6674' not found in library: 'Transistor_FET.dcm' at line 1431 offset 13
21:32:15: Alias 'IRF6710S2' not found in library: 'Transistor_FET.dcm' at line 1437 offset 15
21:32:15: Alias 'IRF6711S' not found in library: 'Transistor_FET.dcm' at line 1443 offset 14
21:32:15: Alias 'IRF6712S' not found in library: 'Transistor_FET.dcm' at line 1449 offset 14
21:32:15: Alias 'IRF6713S' not found in library: 'Transistor_FET.dcm' at line 1455 offset 14
21:32:15: Alias 'IRF6714M' not found in library: 'Transistor_FET.dcm' at line 1461 offset 14
21:32:15: Alias 'IRF6715M' not found in library: 'Transistor_FET.dcm' at line 1467 offset 14
21:32:15: Alias 'IRF6716M' not found in library: 'Transistor_FET.dcm' at line 1473 offset 14
21:32:15: Alias 'IRF6717M' not found in library: 'Transistor_FET.dcm' at line 1479 offset 14
21:32:15: Alias 'IRF6718L2' not found in library: 'Transistor_FET.dcm' at line 1485 offset 15
21:32:15: Alias 'IRF6721S' not found in library: 'Transistor_FET.dcm' at line 1491 offset 14
21:32:15: Alias 'IRF6722M' not found in library: 'Transistor_FET.dcm' at line 1497 offset 14
21:32:15: Alias 'IRF6724M' not found in library: 'Transistor_FET.dcm' at line 1503 offset 14
21:32:15: Alias 'IRF6725M' not found in library: 'Transistor_FET.dcm' at line 1509 offset 14
21:32:15: Alias 'IRF6726M' not found in library: 'Transistor_FET.dcm' at line 1515 offset 14
21:32:15: Alias 'IRF6727M' not found in library: 'Transistor_FET.dcm' at line 1521 offset 14
21:32:15: Alias 'IRF6728M' not found in library: 'Transistor_FET.dcm' at line 1527 offset 14
21:32:15: Alias 'IRF6775M' not found in library: 'Transistor_FET.dcm' at line 1533 offset 14
21:32:15: Alias 'IRF6785' not found in library: 'Transistor_FET.dcm' at line 1539 offset 13
21:32:15: Alias 'IRF6795M' not found in library: 'Transistor_FET.dcm' at line 1545 offset 14
21:32:15: Alias 'IRF6797M' not found in library: 'Transistor_FET.dcm' at line 1551 offset 14
21:32:15: Alias 'IRF6798M' not found in library: 'Transistor_FET.dcm' at line 1557 offset 14
21:32:15: Alias 'IRF6802SD' not found in library: 'Transistor_FET.dcm' at line 1563 offset 15
21:32:15: Alias 'IRF6810S' not found in library: 'Transistor_FET.dcm' at line 1569 offset 14
21:32:15: Alias 'IRF6811S' not found in library: 'Transistor_FET.dcm' at line 1575 offset 14
21:32:15: Alias 'IRF6892S' not found in library: 'Transistor_FET.dcm' at line 1581 offset 14
21:32:15: Alias 'IRF6893M' not found in library: 'Transistor_FET.dcm' at line 1587 offset 14
21:32:15: Alias 'IRF6894M' not found in library: 'Transistor_FET.dcm' at line 1593 offset 14
21:32:15: Alias 'IRF6898M' not found in library: 'Transistor_FET.dcm' at line 1599 offset 14
21:32:15: Alias 'IRF7171M' not found in library: 'Transistor_FET.dcm' at line 1605 offset 14
21:32:15: Alias 'IRF7480M' not found in library: 'Transistor_FET.dcm' at line 1647 offset 14
21:32:15: Alias 'IRF7483M' not found in library: 'Transistor_FET.dcm' at line 1653 offset 14
21:32:15: Alias 'IRF7486M' not found in library: 'Transistor_FET.dcm' at line 1659 offset 14
21:32:15: Alias 'IRF7580M' not found in library: 'Transistor_FET.dcm' at line 1665 offset 14
21:32:15: Alias 'IRF7665S2' not found in library: 'Transistor_FET.dcm' at line 1683 offset 15
21:32:15: Alias 'IRF7739L1' not found in library: 'Transistor_FET.dcm' at line 1689 offset 15
21:32:15: Alias 'IRF7748L1' not found in library: 'Transistor_FET.dcm' at line 1695 offset 15
21:32:15: Alias 'IRF7759L2' not found in library: 'Transistor_FET.dcm' at line 1701 offset 15
21:32:15: Alias 'IRF7769L1' not found in library: 'Transistor_FET.dcm' at line 1707 offset 15
21:32:15: Alias 'IRF7779L2' not found in library: 'Transistor_FET.dcm' at line 1713 offset 15
21:32:15: Alias 'IRF7780M' not found in library: 'Transistor_FET.dcm' at line 1719 offset 14
21:32:15: Alias 'IRF7799L2' not found in library: 'Transistor_FET.dcm' at line 1725 offset 15
21:32:15: Alias 'IRF7946' not found in library: 'Transistor_FET.dcm' at line 1731 offset 13
21:32:15: Alias 'IRF8301M' not found in library: 'Transistor_FET.dcm' at line 1737 offset 14
21:32:15: Alias 'IRF8302M' not found in library: 'Transistor_FET.dcm' at line 1743 offset 14
21:32:15: Alias 'IRF8304M' not found in library: 'Transistor_FET.dcm' at line 1749 offset 14
21:32:15: Alias 'IRF8306M' not found in library: 'Transistor_FET.dcm' at line 1755 offset 14
21:32:15: Alias 'IRF8308M' not found in library: 'Transistor_FET.dcm' at line 1761 offset 14
21:32:15: Alias 'IRF8327S' not found in library: 'Transistor_FET.dcm' at line 1767 offset 14
21:32:15: Alias 'IRF9383M' not found in library: 'Transistor_FET.dcm' at line 1779 offset 14
21:32:15: Alias 'IRF9394M' not found in library: 'Transistor_FET.dcm' at line 1785 offset 14
21:32:15: Alias 'IRF9395M' not found in library: 'Transistor_FET.dcm' at line 1791 offset 14
21:32:15: Alias 'IRL6283M' not found in library: 'Transistor_FET.dcm' at line 1803 offset 14
21:32:15: Alias 'IRL6297SD' not found in library: 'Transistor_FET.dcm' at line 1809 offset 15
21:32:15: Alias 'IRL7472L1' not found in library: 'Transistor_FET.dcm' at line 1815 offset 15
```

Could you check that and fix it?

Thanks,
JAN

**Comment by jkriege2** [comment]
PS: Please also mention ALL changes you did in the PR description ... I would possibly have overlooked the FET-changes!

**Comment by evanshultz** [comment]
@jkriege2 
Ummm... something must have happened. Only off-grid pins were supposed to be fixed in Transistor_FET.lib. See the list of fixes at https://github.com/KiCad/kicad-symbols/issues/272.

However, https://github.com/KiCad/kicad-symbols/pull/276 should be merged first. Hopefully before the branch breaks again...

**Comment by evanshultz** [comment]
All should be well after Travis checked it. One ADC symbol was renamed, generating an error, and two FET symbols were removed because they're now an ALIAS of IRF7309. I would really like to get this into v5 as well as https://github.com/KiCad/kicad-symbols/pull/276 because they're complimentary.

**Comment by jkriege2** [comment]
Hi!

looks mostly good. One thing left: You used a stable v4 to edit? This switched the lib file format back to 2.3 and creates some reordering noise (which will reappear back when somebody edits the files with nightly/v5). So could you use a nightly to edit (for now open and save again), so the file-formats stay in one standard? Also in the end these libs are meant to be used with v5 (nighly), so I think we should use that format and @poeschlr proposed to do a one-time back-port, so people can download v4-libs derived from these with NEARLY all freatures.

Thanks,
JAN

**Comment by poeschlr** [comment]
I would say as long as the dcm file is not wiped we could accept contributions made with the stable release. Yes there will be additional noise in the git history but we can't really expect every contributor to use the same version of nightly builds. (The line ordering can change even between different versions of the nightlies. I fear the developers are not even aware of the problems this creates for us.)

---

Of course recontribution with a newer version is the optimal outcome.

**Comment by evanshultz** [comment]
Can this be merged then to get these fixes into v5?

**Comment by evanshultz** [comment]
But let me clarify that this should only be merged after https://github.com/KiCad/kicad-symbols/pull/276. For example, ADC128D818 is fixed here and not there.

**Comment by jkriege2** [comment]
OK; I merged your other PR, now this one has conflicts ... could you rebase your branch, so I can merge?

Thanks,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
This is too messy. I started a new PR at https://github.com/KiCad/kicad-symbols/pull/332. Could you take a look at that?

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-symbols/pull/332 will cover these changes.

**Pull request closed without merging**
