### PR TITLE
Added TSV994 Quad Op Amp

### PR DESCRIPTION
**Pull request by aris-kimi**
Add TSV994 Quad Op Amp

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aris-kimi** [comment]
tsv994

**Comment by aris-kimi** [comment]
Datasheet: https://www.st.com/resource/en/datasheet/tsv994.pdf

**Comment by aris-kimi** [comment]
tsv994

**Comment by myfreescalewebpage** [comment]
@aris-kimi can you have a look to the git diff at https://github.com/KiCad/kicad-symbols/pull/1673/files before we can review this, you have a large modification of the whole file, I think you have a problem with line endings.
Thanks,
Joel

**Comment by aris-kimi** [comment]
Thank you Joel. I really am trying to understand how to do some actions. I hope it is ok now.

Thanks again,
Aris

**Comment by myfreescalewebpage** [comment]
That's better. I have made a review, this symbol should be an alias of the LM2902. Moreover, there is still some diff I do not understand in the git diff, for example on symbols LMH6551MA, LMH6551MM etc.
Joel

**Comment by aris-kimi** [comment]
Those confused me to, and to be honest i am not sure how to proceed from this point. Should i close the PR work it some more and try again with a new PR? Is it a problem if we ommit this alias issue?

**Comment by myfreescalewebpage** [comment]
Please, you should continue on this PR, that's too much complicated and unuseful to open a new one, this complicates the reviews.

For the first point: I note the symbol is the same than LM2902, so you should NOT create a new symbol for that but simply add an alias to the LM2902, called TSV994. The LM2902 as already other aliases. See following screenshot:

Capture

For the second point: you have probably to update your local branch due to other merge in the master and that's why you have unwanted modifications ? Or maybe you have make them ?

Joel

**Comment by aris-kimi** [comment]
output

**Comment by myfreescalewebpage** [comment]
@aris-kimi thanks for the modification, no worries about the travis warning, it is normal for this symbol. The SOIC package in the description should be "SOIC-14" not "SO-14".
Thanks,
Joel

**Comment by aris-kimi** [comment]
@myfreescalewebpage Joel thank you very much for the assistance. I think we are ok now.
Thank you,
aris-kimi

**Comment by myfreescalewebpage** [comment]
@aris-kimi thanks for your modification, this was great before the last commit. I think you have miss something....

**Comment by myfreescalewebpage** [comment]
@aris-kimi one branch for each pull request is required. I'm no more able to merge the op amp.

**Comment by evanshultz** [comment]
It is possible to cherry-pick a specific commit to merge, but this works too.

**Comment by myfreescalewebpage** [comment]
@evanshultz the symbol has been submitted again by the author at #1686

**Comment by aris-kimi** [comment]
I am sorry for all the trouble caused. I will practice with github some more and i will check again. Thank you.

**Comment by myfreescalewebpage** [comment]
No worries @aris-kimi :)

**Pull request closed without merging**
