### PR TITLE
Add FETs in new packages

### PR DESCRIPTION
**Pull request by evanshultz**
Here are a number of FETs I've collected which didn't have symbols using the footprint I wanted. Hopefully this makes it easier for other users to select FETs in packages available in the market.

- DMN3033LDM https://www.diodes.com/assets/Datasheets/ds31345.pdf
image

- FDC2512 https://www.onsemi.com/pub/Collateral/FDC2512-D.pdf
- FDC86244 https://www.onsemi.com/pub/Collateral/FDC86244-D.pdf
image

- STB15N80K5 https://www.st.com/resource/en/datasheet/stb15n80k5.pdf
- STB33N65M2 https://www.st.com/resource/en/datasheet/stb33n65m2.pdf
- STB40N60M2 https://www.st.com/resource/en/datasheet/stp40n60m2.pdf
- IRFS4115 https://www.infineon.com/dgdl/irfs4115pbf.pdf?fileId=5546d462533600a401535636e5d2218f
- IRFS4127 https://www.infineon.com/dgdl/irfs4127pbf.pdf?fileId=5546d462533600a401535636ee7b2192
- IRFS4227 https://www.infineon.com/dgdl/irfs4227pbf.pdf?fileId=5546d462533600a401535639ef64219b
- IRFS4229 https://www.infineon.com/dgdl/irfs4229pbf.pdf?fileId=5546d462533600a401535639fdc421a1
- IRFS4310Z https://www.infineon.com/dgdl/irfb4310zpbf.pdf?fileId=5546d462533600a4015356161b4d1e2d
- IRFS4321 https://www.infineon.com/dgdl/irfs4321pbf.pdf?fileId=5546d462533600a40153563a20dd21ad
image

- PMN48XP https://assets.nexperia.com/documents/data-sheet/PMN48XP.pdf
image

 - STD7NK40Z https://www.st.com/resource/en/datasheet/std7nk40zt4.pdf
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @evanshultz 

PMN48XP
- [ ] The device is not centered (too much)

Else, no comment to do, just need to rebase your branch.

Joel

**Comment by evanshultz** [comment]
GH says there are conflicts, but looking at them in the web interface I don't see anything conflicting with master. Um... do you know what is best to do in this situation?

**Comment by chschlue** [comment]
There were no real conflicts, you just added symbols at the same spot where there had been changes to master in the meantime and Git hates you for that. Probably also a kitten died.

You can "fix" this sort of conflict by simply removing the conflict markers in the web interface.
(Note that you have to pull your PR branch now before making further changes)

**Comment by myfreescalewebpage** [comment]
@evanshultz seems ok now, just need to move PMN48XP

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Moved that symbol. Ready to merge, I think.

@chschlue 
What did you do? Specifically, what steps did you do? And command line or some Git client or GH web interface? I saw merge conflicts that wouldn't let me automatically merge in master using GitHub Desktop.

**Comment by chschlue** [comment]
@evanshultz In cases like this (the conflict is just that you added something in a spot where somebody else removed something) you can either
1. Remove `<<<<<`, `=====`, `>>>>>` conflict markers using the web interface
1. On the command line: `git merge master` -> git interrupts the merge, complaining about conflicts -> `git checkout --ours <file name>` for every conflicting file (telling git to use the version from your PR branch) -> `git merge --continue`
1. `git rebase master` followed by `git push -f` (the conflict usually disappears because you're telling git to effectively alter history such that the removal happened _before_ your addition, not concurrently.

When there really are conflicting changes (say you fix a description on line 1000 while someone else's (slightly different) fix has been merged to master in the meantime):
1. Choose the version either above or below `=====` (removing the other one _and_ `=====`) as you see fit, then remove `<<<<<` and `>>>>>` using the web interface.
1. Command line: `git merge master` -> do the same as above using a text editor -> `git merge --continue`

I don't know of any cleaner way.

**Comment by myfreescalewebpage** [comment]
Merging.

**Pull request merged**
