### PR TITLE
Clean up MSP430 lib

### PR DESCRIPTION
**Pull request by evanshultz**
https://github.com/KiCad/kicad-symbols/pull/678 revealed a ton of errors in the lib. Some fixes:
- Fix pin text size (replaced all " <number> <number> 1 1 " with " 50 50 1 1 ")
- Fixed pin name offset (replaced " 40 Y Y " with " 20 Y Y ")
- Added trailing asterisk to footprints filters where missing
- Fixed MSP430F2232IDA/MSP430F2234IDA footprint filter
- MSP430F5524IYFF/MSP430F5630IZQW/MSP430F5633IZQW/MSP430F5636IZQW pin name V18 to Passive type (it cannot source current but has a capacitor connected at http://www.ti.com/lit/ug/slau278ad/slau278ad.pdf shows a cap connected)
- MSP430FR5720IRGE/MSP430FR5722IRGE removed DeMorgan pin commonality
- MSP430FR5720IRGE/MSP430FR5722IRGE changed power pins to Power Input type
- MSP430G2102IPW14/MSP430G2111IN14/MSP430G2111IPW14/MSP430G2112IPW14/MSP430G2121IN14/MSP430G2121IPW14/MSP430G2131IN14/MSP430G2131IPW14/MSP430G2132IPW14/MSP430G2152IPW14 removed pin count in footprint filter
- MSP430G2210ID/MSP430G2230ID placed power pins on top and bottom
- Fixed duplicated pin numbers on MSP430F5217IYFF/MSP430F5227IYFF from http://www.ti.com/lit/ds/slas718g/slas718g.pdf

Lines in output of checklib.py from 12269 to 3475.

I am not planning to do any more work here. Remaining errors are:
1. Symbol not centered (we know sometimes this isn't valid)
1. Pins off grid
1. Pin types (may be bogus)

Many (or all?) of them have 150mil pin length, but making that 100mil would require so much manual work I think it's best to write a generator script later if we want to improve these symbols further.

Also, I do some pin text overlapping but we've talked about using short pin names and so I think a script generator is the best way to resolve this item as well.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
The following serious errors (IMO) remain. However, I'm out of time now. I'd prefer to see them moved into a new issue and this PR merged, if possible.

MSP430G2444IDA38
Footprint file Package_SO:TSSOP-38_6.1x12.5mm_P0.65mm was not found

MSP430F5227IYFF
Footprint file Package_BGA:Texas_RXBGA-64_3.415x3.535mm_Layout8x8_P0.4mm was not found

MSP430F2234IDA
Footprint file Package_SO:TSSOP-38_6.1x12.5mm_P0.65mm was not found

MSP430F5658IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430F1101AIDGV
Footprint file Package_SO:TVSOP-20_4.4x5mm_P0.4mm was not found

MSP430G2444IYFF
Footprint file Package_BGA:Texas_RXBGA-49_3.33x3.488mm_Layout7x7_P0.4mm was not found

MSP430F5217IYFF
Footprint file Package_BGA:Texas_RXBGA-64_3.415x3.535mm_Layout8x8_P0.4mm was not found

MSP430F2234IYFF
Footprint file Package_BGA:Texas_RXBGA-49_3.33x3.488mm_Layout7x7_P0.4mm was not found

MSP430F2232IYFF
Footprint file Package_BGA:Texas_RXBGA-49_3.33x3.488mm_Layout7x7_P0.4mm was not found

MSP430F2101IDGV
Footprint file Package_SO:TVSOP-20_4.4x5mm_P0.4mm was not found

MSP430F5358IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430F5630IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430F5636IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430F5333IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430G2121IN14
Footprint file Package_SO:TSSOP-38_6.1x12.5mm_P0.65mm was not found

MSP430F5633IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430G2755IDA38
Footprint file Package_SO:TSSOP-38_6.1x12.5mm_P0.65mm was not found

MSP430F5524IYFF
Footprint file Package_BGA:Texas_RXBGA-64_3.415x3.535mm_Layout8x8_P0.4mm was not found

MSP430F5336IZQW
Footprint file Package_BGA:Texas_MicroStar_Junior_BGA-113_7.0x7.0mm_Layout12x12_P0.5mm was not found

MSP430F5237IRGC
Footprint file Package_BGA:Texas_RXBGA-49_3.33x3.488mm_Layout7x7_P0.4mm was not found

**Comment by evanshultz** [comment]
I'll add the missing footprints. Please keep this open.

**Comment by evanshultz** [comment]
Footprints submitted at https://github.com/KiCad/kicad-footprints/pull/718.

**Comment by Ratfink** [comment]
I really wouldn't feel good about releasing 5.0.0 with symbols that look like this:
screenshot from 2018-07-05 18-56-11
But I really want to fix this part of #520 before the new stable release.  So I see three options:

1. Undo the pin text size change, making this PR a smaller step in the right direction.
2. Enlarge all the symbols with overlapping pin text, making this PR a bigger step in the right direction.
3. Make a new PR that only fixes the footprint associations, and finish this one after 5.0.0.

Pick your poison.

**Comment by evanshultz** [comment]
Ugh. Awful. Let me take a look. This library was in terrible shape.

**Comment by evanshultz** [comment]
I enlarged symbols where needed and moved pins to avoid overlapping elements. Intended as a quick fix, but I hope I didn't miss anything and it's acceptable. Let me know if you find anything I didn't catch.

**Comment by Ratfink** [comment]
Looking better!  However, the MSP430F2002* and MSP430F2003* symbols still look like the screenshot above.  Also, the following symbols have varying degrees of overlapping text remaining:

* MSP430F5232IRGZ
* MSP430F5237IRGC
* MSP430F5242IRGZ
* MSP430F5247IRGC
* MSP430F5340IRGZ
* MSP430F5500IRGZ
* MSP430F5508IRGZ
* MSP430F5633IZQW
* MSP430F5636IZQW
* MSP430F5658IZQW
* MSP430G2001IRSA16
* MSP430G2111IPW14
* MSP430G2132IPW14
* MSP430G2755IDA38

**Comment by evanshultz** [comment]
All fixed except `MSP430G2132IPW14`: I didn't see anything overlapping on that symbol (or any of the `MSP430G2132*` symbols, although some are close):
image

Anything else?

**Comment by Ratfink** [comment]
I think the problem I saw in the symbol you posted a screenshot of was actually that the text for pin 6 is hitting the left edge of the body rectangle.  Also, in MSP430F2002IRSA, the text for pins 13 and 14 overlaps the text for pin 8.  Other than those two problems, I think this is ready to merge.

**Comment by evanshultz** [comment]
Done.

**Comment by Ratfink** [comment]
Looks good now, thanks for taking the time to improve these symbols!

**Comment by evanshultz** [comment]
@Ratfink 
Thanks!

A thought popped into my head: You wrote a very nice generator script for some ST MCUs and the existing MSP430 lib contains all the info on symbol names, ALIASes, pin names, pin numbers, etc. It seems feasible to extract that info from the existing MSP430 lib into a file that would be an input to your (or a modified version of your) ST MCU symbol generator script, which would bring this lib into compliance with KLC. And then we could use that infrastructure over and over again to clean up the other MCU, DSP, FPGA, etc. libs. Unless you see a reason why this shouldn't work, or have some concerns, I may take a look at this in several weeks when I have more time.

**Pull request merged**
