### PR TITLE
Adding SiFive FU540-C000 MCU

### PR DESCRIPTION
**Pull request by ki5libs**
Adding SiFive FU540-C000 MCU
[Datasheet](https://static.dev.sifive.com/FU540-C000-v1.0.pdf)
Part A (from 6 parts total) screenshot:
u540_a

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Sorry for the late feedback.

Is this generated by any sort of script?
Is there a chance to reduce the length of the pin names?

**Comment by ki5libs** [comment]
@poeschlr thanks for starting reviewing.
Actually I was waiting for consulting with somebody :)

Firstly - it's not generated by any script. It's based on [schematic](https://sifive.cdn.prismic.io/sifive%2Ff7173056-bf37-4407-87cb-d5ab76abf61a_hifive-unleashed-a00-schematics.pdf) of reference board by chip developer. I've tried to make it with minimum of changes. But it's one of my first PRs and now I see that some things should be changed.

1) Pins names. There are no any table in the [documentation](https://static.dev.sifive.com/FU540-C000-v1.0.pdf) which describes pins. Only few pins have mentions in the text (`PORESET_N`
 `ERESET_N` `HFXOSCIN` `HFXOSCOUT` `HFXSEL` `GND` `VCC`). Pin names were taken from reference schematic "as is". I have some ideas for reducing:
- remove `IO` from the beginning of name;
- replace `PINS` in GPIO names with `P`;
- replace second `PWM` in PWM with `P`;
- replace `CHIPLINK` in CHIPLINK with `CL`;
- replace `DATA` in CHIPLINK with `D`;
- replace `DATA` in DDR with `D`;
- replace `ADDRESS` in DDR with `ADDR`.
Example results:
- `IO_CHIPLINK_0_B2C_DATA_0` becomes `CL_0_B2C_D_0`;
- `IO_DDR_MEM_ADDRESS[0]` becomes `DDR_MEM_ADDR[0]`;
- `IO_DDR_MEM_ECC_DATA[0]` becomes `DDR_MEM_ECC_D[0]`;
- `IO_GPIO_0_PINS_0` becomes `GPIO_0_P_0`;
- `IO_PWM_0_PWM_0` becomes `PWM_0_P_0`.
I could also squeeze blocks after that.

2) Power pins. I want to leave block F as power pins block but completely rework it: combine all `VDD` and `VSS` pins, move all power pins from another block (DDR, IO) parts to this one.

What do you think?

**Comment by poeschlr** [comment]
Sounds good in general.

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

Amazing symbol and so much pins to review !!! A few comments I have:

General:
- [ ] Pin name position offset should be 20mil (travis log)
- [ ] Footprint filter should be `BGA*23.0x23.0mm*P1.0mm*`

Unit F:
- [ ] Can you move pins VSS in front of pins VDD ?
- [ ] Can you move pins GEMGXLPLL_AVSS in front of pins GEMGXLPLL_AVDD ?
- [ ] Can you move pins GIVSS in front of pins GIVDD ?
- [ ] Can you move pins IVSS in front of pins IVDD ?
- [ ] Can you move pin COREPLL_AVSS in front of pin COREPLL_AVDD ?

I have check every pins, name, number and types. I agree with this.
Looks very good, so few errors on a so large symbol !!!

Cheers,
Joel

**Comment by evanshultz** [comment]
Here are a couple more things:
1. If the symbol is too tall to fit on a A4 schematic sheet, let's think about breaking it up more.
1. Pin length should be 150mil long since I believe all pin numbers use 3 characters or less.
1. Don't place the ref des and value inside the symbol. Usually ref des is at the top left and value is the top right, while both can be on the right for the power symbol since it is full of pins on the top.

**Comment by myfreescalewebpage** [comment]
@evanshultz 
1- it fit actually and it is divided in unit as shown in the manufacturer example so for me it's the best choice
2- Some pins have 4 characters, for example "AA22" in the top left of the first unit
3- the ref des and value position is common to all unit so it's not very convenient when the units have not the same size. Additionally, they are placed by the schematic editor... So I don't think the current proposition is a problem.

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage , sorry for some delay. I've fixed symbol according to your comments. I have to make part F a little bit larger (on the picture).
FU540_F

**Comment by myfreescalewebpage** [comment]
@ki5libs great job, no worries for the delay, we also took a lot of time to review it.
On unit F, can you fix the position of pin J11, see problem below:

Capture

Else, this will be ready to merge.
Cheers,
Joel

**Comment by ki5libs** [comment]
Oh, sure, I was inattentive. Thanks @myfreescalewebpage  It's fixed now.

**Comment by myfreescalewebpage** [comment]
@ki5libs no worries, thanks! No more comments, merging !

**Pull request merged**
