### PR TITLE
KLC-fixes for Transistor_Array.lib:

### PR DESCRIPTION
**Pull request by jkriege2**
- better split symbols by available package types
- improved description
- added missing variants of existing (ULQ... as copy of existing symbol due to different footprints)
- removed MC1417 for which no information is available
- reworked A2982 symbol (made pins shorter, now 100mil, were 200mil)

### CODE REVIEW

**Comment by jkriege2** [comment]
see my comment there: https://github.com/KiCad/kicad-symbols/pull/203#issuecomment-359492302

**Comment by jkriege2** [comment]
@evanshultz This also fixes the issue you raised in #203

**Comment by jkriege2** [comment]
I reworked the style, does this adress everything?
2018-01-23 06_41_09-eeschema devproject _ d__kicad_devproject

Note that The A2982 is actually open-emitter instead of open-collector as all others. Thus the "inverter"/"driver"-symbol difference

**Comment by evanshultz** [comment]
@jkriege2 
Sorry that I forgot to review this earlier! Thanks for making all the updates!

**Pull request merged**
