### PR TITLE
Updateting fujitsu FRMA serie MB85

### PR DESCRIPTION
**Pull request by Misca1234**
The WLP package needed for Fujitsu FRM serie have been merged so this push is an update of those
(https://github.com/KiCad/kicad-footprints/pull/976)

This push have changed the following

Changed the symbol text distance from 40 to 20 on all
M85RS1MT and MB85RS2MT got their own symbols
Updated the data sheet links
M85RS1MT  is now two different symbols, one specific for the WLP package

MB85RS16
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS16-DS501-00014-8v0-E.pdf
SOP-8 (or a soic-8 in kicad case)

MB85RS64
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS64-DS501-00012-6v0-E.pdf
SOP-8 (or a soic-8 in kicad case)

MB85RS128B
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS128B-DS501-00020-4v0-E.pdf
SOP-8 (or a soic-8 in kicad case)

MB85RS256B
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS256B-DS501-00021-4v0-E.pdf
SOP-8 (or a soic-8 in kicad case)

MB85RS512T
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS512T-DS501-00029-3v0-E.pdf
SOP-8 (or a soic-8 in kicad case)

MB85RS1MT
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS1MT-DS501-00022-6v0-Z.pdf
SOP-8 (or a soic-8 in kicad case)
DIP-8

MB85RS1MT-WLP
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS1MT-DS501-00022-6v0-Z.pdf
WLP-8 (https://github.com/KiCad/kicad-footprints/pull/976)

MB85RS2MT
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS2MT-DS501-00023-5v0-E.pdf
SOP-8 (or a soic-8 in kicad case)
DIP-8

bild

bild

bild

bild

bild

bild

bild

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @Misca1234 

Few comments during my review:

MB85RS16 and alias:
- [ ] I do not agree with the package, it is SOP, not SOIC

MB85RS1MT:
- [ ] Datasheet is in Japanese, do you have a link for English ?
- [ ] You have separated WLP version, but not SOP and DIP. I would suggest to do the job for the three and name the parts according to ordering information available in the datasheet page 22
- [ ] Not agree with SOIC package too, it is SOP

MB85RS2MT:
- [ ] Some aliases are still possible with MB85RS1MT version.

I would suggest to have three symbol definition, SOP, DIP and WLP, and create the expected alias.
Also, adding the memory size in the description for each alias should be nice (see 24LCxx series).

Cheers,
Joel

**Comment by Misca1234** [comment]
The reason for the SOIC choice (even it says SOP in the documentation) is that this one exist
SOIC-8_3.9x4.9mm_P1.27mm
which match very well, there is no SOP foot print that match, so I reused the SOIC, do yo uwant me to create a SOP foot print instead?

> MB85RS1MT:
>  Datasheet is in Japanese, do you have a link for English ?

We could change to this one
https://www.fujitsu.com/uk/Images/MB85RS1MT.pdf

> You have separated WLP version, but not SOP and DIP. I would suggest to do the job for the three 
> and name the parts according to ordering information available in the datasheet page 22

The pin naming is different for the WLP one, they are not numbers


> Also, adding the memory size in the description for each alias should be nice

I add that

**Comment by myfreescalewebpage** [comment]
> do yo uwant me to create a SOP foot print instead?

Yes please.

> The pin naming is different for the WLP one, they are not numbers

Yes I know. My proposition is to split also the other variants. These are atomic parts, which is best to have already ready to be used in KiCad (http://kicad-pcb.org/libraries/klc/G2.1/)

Cheers,
Joel

**Comment by Misca1234** [comment]
changed the foot print to 
SSOP-8_3.9x5.05mm_P1.27mm

**Comment by myfreescalewebpage** [comment]
@poeschlr is SSOP and SOP the same ? I have seen both in the generator at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO so I'm not sure....

**Comment by Misca1234** [comment]
They are, sort of, depending who you talk to (JEDEC or EIAJ)
https://en.wikipedia.org/wiki/Small_Outline_Integrated_Circuit

SSOP is just a smaller variant of SOP, but generally a SSOP should have a lead space of 0.65 or less

So given that, the foot print I point to in this thread, SSOP-8_3.9x5.05mm_P1.27mm, should actually be renamed into "SOP-8_3.9x5.05mm_P1.27mm

**Comment by Misca1234** [comment]
I guess that explain why it is called SOP in the data sheet, it is a Japanese chip and they probably follow EIAJ which define a SOIC as something with a with of 5.3 while JEDEC define a SOIC as a something with a width of 3.8.

So for a Japanese person this is a SOP capsule but for a JEDEC it is a SOIC.

**Comment by myfreescalewebpage** [comment]
@Misca1234 I think you have given the response, package are not the same. If the user wants a proper BOM/3D etc the right package should be used. There are several SOP/SOIC/SSOP packages already available, it is probably for a good reason, else everything would have been SOIC.
Using the generation scripts is really trivial, so I don't see any reason to not use the correct footprint.

**Comment by myfreescalewebpage** [comment]
@Misca1234 my previous answer is also the choice on another PR: https://github.com/KiCad/kicad-footprints/issues/1450#issuecomment-468728773 approved by @evanshultz and @poeschlr 
Thanks to update this.
Joel

**Comment by Misca1234** [comment]
SOIC-8_3.9x5.05mm_P1.27mm is in this push
https://github.com/KiCad/kicad-footprints/pull/1473

**Comment by myfreescalewebpage** [comment]
@Misca1234 SOIC do not matter, we need SOP here !

**Comment by Misca1234** [comment]
This is not what you agreed above in earlier discussion

**Comment by myfreescalewebpage** [comment]
Please let me know where by indicating a link to my comment.

**Pull request closed without merging**
