### PR TITLE
Added TVS0500DRV

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: http://www.ti.com/lit/ds/symlink/tvs0500.pdf
imagen
imagen
imagen

### CODE REVIEW

**Comment by chschlue** [comment]
- [x] Documentation
- [x] Footprint
- [x] Pinout
- [ ] This being an integrated circuit and not a discrete component, symbol needs an outline and filled background

**Comment by cnieves1** [comment]
imagen

**Comment by chschlue** [comment]
Can you make the symbol a little narrower?
D&D circuitry conveys very little information for its size.

**Comment by cnieves1** [comment]
imagen

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
