### PR TITLE
Replace WSON-8_4x4mm with generated footprint

### PR DESCRIPTION
**Pull request by cpresser**
The existing footprint did not have the EP in its name.
Its filename also differed from the kicad-name (WSON8_4x4mm_P0.8mm), there
is a missing dash.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@cpresser review of each modifications:

- [ ] LP2987-5.0_WSON8 and LP2988-5.0_WSON8 the EP size is not correct, another fp should be created (EP 2.2x3mm)
- [ ] LM5017SD the EP size is not correct, another fp should be created (EP 1.98x3mm)

Joel

**Comment by cpresser** [comment]
Looks like there were quite a few bugs hidden with the existing WSON8 parts.
I will also create FPs for those variants later today.

**Comment by myfreescalewebpage** [comment]
Yes it seems. Thanks.

**Comment by cpresser** [comment]
More footprints are here. https://github.com/KiCad/kicad-footprints/pull/2503
@myfreescalewebpage  Can you please check the naming?

**Comment by myfreescalewebpage** [comment]
Name looks great @cpresser thanks. Wait review of footprint by @chschlue you have assigned on

**Comment by myfreescalewebpage** [comment]
Merging following integration of the fp

**Pull request merged**
