### PR TITLE
74HC(T)164

### PR DESCRIPTION
**Pull request by mpkopec**
Added 8-bit serial-in parallel-out shift register.

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by mpkopec** [comment]
The symbol is off-center, since its asymmetry.

**Comment by rjj100** [comment]
Thank you! Would be nice to have a 74HC165 which is similar and not in the library.

**Comment by evanshultz** [comment]
@mpkopec 
A couple of quick things:
1. Please always include a datasheet. For consistency of pin names, please select from the most common vendor in the library already (as best you can).
1. I can't read the pin types above, but I'm sure they shouldn't all be the same for left and right pins.
1. Pin 8 shouldn't use the clock pin style (all pins in the lib are normal style).

**Comment by mpkopec** [comment]
@evanshultz 
1. There is a datasheet. Checked other 2 or 3 symbols for shift registers and I can't find any major difference from my symbol.
2. In Polish "Wejście" is "Input" and "Wyjście" is "Output", so everything is ok, however, for a foreigner. it might be confusing. :)
3. Done.

Thanks a lot for the input and sorry for the delay.

**Comment by evanshultz** [comment]
Thanks!

I meant please include the datasheet in the PR body, but somehow I didn't write that. Sorry.

**Pull request merged**
