### PR TITLE
add ADA4077-1 OpAmps

### PR DESCRIPTION
**Pull request by hvraven**
Simple aliases to existing symbols. [Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADA4077-1_4077-2_4077-4.pdf). Adds a unicode √ to the description, I hope thats fine. Didn't cause any issues on my system.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. The square root symbol isn't allowed. See http://kicad-pcb.org/libraries/klc/G1.1/. It seems to work OK for me too, and I suspect other illegal symbols are used as well, but we need to stick with the rules. You are welcome to park this and take up an issue to make square root an accepted character and see if it's accepted, if you like.
1. I'm not sure if we should wildcard the grade for the MSOP package. ADI could always release a 'B' grade version. But not required.

If you can address the first item I will merge. Thanks!

**Comment by lorem-ipsum** [comment]
Wildcarding probably makes sense, will change that.

Do you have any suggestions how to specify the noise in this case? I could just drop it.

**Comment by evanshultz** [comment]
Not particularly, unfortunately. `LT6234` and `LT6237` also have a square root sign but I don't see other examples in this library. Probably leaving it out and just having `xxxV/Hz` would be understandable, but `xxxV/sqrtHz` would be a more complete option. Your thoughts?

**Comment by lorem-ipsum** [comment]
I think /sqrtHz looks rather ugly. Whos interested in it probably understands V/Hz, so I will change it to that

**Comment by lorem-ipsum** [comment]
I should actually do this if I say so... Looking at this again with some distance I decided to go for sqrtHz. While it looks a bit ugly it is at least correct.

**Comment by hvraven** [comment]
rebased to fix merge conflict

**Comment by myfreescalewebpage** [comment]
@evanshultz do you wantto terminate this PR ? I can check if you want

**Comment by evanshultz** [comment]
@hvraven 
I really lost track of things around here. Sorry. And thank you for coming back to this!

@myfreescalewebpage 
I assume I checked things in the past and a quick look now seems fine. If you want to review more thoroughly, please go ahead. Then let me know and I'll merge or feel free to do it yourself.

**Comment by myfreescalewebpage** [comment]
@hvraven @evanshultz the letter just after "-1" is the grade; should be discarded for the MSOP package too.

- [ ] ADA4077-1ARM should be renamed "ADA4077-1xRM"

Joel

**Comment by myfreescalewebpage** [comment]
@hvraven ping

**Comment by hvraven** [comment]
Hi @myfreescalewebpage ,

thanks for checking, replaced the grade marking with an x.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
