### PR TITLE
Add LM22676MR.

### PR DESCRIPTION
**Pull request by matthuszagh**
Adding:
http://www.ti.com/lit/ds/symlink/lm22676.pdf

image

Note that I placed the power input on the left and not the top in line with the conventions followed by the other switching regulators.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh, thanks for contributing,

A few comments I have during my review:

- [ ] pin 4 FB should be moved to the right bottom corner of the symbol, and pin SW in the right top corner, for consistency with other devices
- [ ] pin 9 should be called `EP` for consistency with other devices

KLC S4.2 accepted for this symbol.

Cheers,
Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage, amended.

**Comment by myfreescalewebpage** [comment]
@matthuszagh thanks.

- [ ] You have moved VIN, would suggest to keep it in front of SW pin.
- [ ] Just seen the footprint is missing at the end of the description, please add `, SOIC-8`(KLC SS6.3)

Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage, fixed those two. Let me know if that's better.

**Comment by myfreescalewebpage** [comment]
@matthuszagh very nice, okay for me.

@antoniovazquezblanco according to me this PR is ready to be merged.

**Comment by antoniovazquezblanco** [comment]
The FB pin is similar to the ADJ pin in other devices of the lib. Should we wait to have consensus on wether that pin should be input/passive?

**Comment by myfreescalewebpage** [comment]
You are right ! Obviously we usually set it as input, as describe in the datasheet of this part.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco it has been decided on the other PR that FB should be an input, so no more modifications to do here. Ready to be merged according to me.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
