### PR TITLE
Add PIC16F1786-xML

### PR DESCRIPTION
**Pull request by juanjorojash**
**Addition of PIC16F76-IML** to the MCU_Microchip_PIC16 library. The _PIC16F73-IML_ was used base symbol and the footprint is: _Package_DFN_QFN:QFN-28-1EP_6x6mm_P0.65mm_EP4.25x4.25mm_

**Datasheet:** http://ww1.microchip.com/downloads/en/DeviceDoc/40001637C.pdf
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
This is not a review in detail but some things that should be corrected at first sight:
- [ ] Pin length should be 100mils
- [ ] In pin naming, please only include the primary function. If there is a very important secondary function include it also (for example MCLR). See https://github.com/KiCad/kicad-symbols/pull/750 for example.
- [ ] Lets wildcard the temperature indicator on the device name: `PIC16F76-xML`.
- [ ] Please stack VSS pins.
- [ ] Add a wildcard to the end of your FP filter: `QFN-28*6x6mm*P0.65mm*`.

Thank you!

**Comment by juanjorojash** [comment]
I applied your corrections.  

Thank you! 

image

**Comment by myfreescalewebpage** [comment]
@juanjorojash @antoniovazquezblanco RA6/RA7/RE3 pin names have been lost!
Moreover, I sugegst that RA6 and RA7 should be grouped with other RA pins
Joel

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco do you want to assign you or maybe it was just a first review that still need complete review ?

**Comment by antoniovazquezblanco** [comment]
It is missing a complete review. I can go over it but I will need time as I am really really overloaded at work. If you find time for it and want to do it go for it @myfreescalewebpage .

Thanks!

**Comment by myfreescalewebpage** [comment]
Thanks @antoniovazquezblanco for your response, will do a full review now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
@juanjorojash thanks for this contribution.

First of all, can you sign the CLA for this PR, this is a mandatory condition to accept your contribution.

About this symbol, here are my comments:
- [ ] Description format is not the last one and some information are not relevant, I propose `8-bit Flash MCU, 32MHz, 16KB Flash, 1KB RAM, 256B EEPROM, QFN-28`
- [ ] Same comment for keywords, I propose `8-bit Flash MCU Microcontroller`
- [ ] Footprint filter should be `QFN*1EP*6x6mm*P0.65mm*`
- [ ] Name of pin 6 is "RA7"
- [ ] Name of pin 7 is "RA6"
- [ ] RA6 and RA7 should be grouped with other RAx pins
- [ ] Name of pin 16 is VSS and should be stacked with pin 5
- [ ] Name of pin 26 is "RE3/~MCLR/VPP"
- [ ] Name of pin 14 is RC6
- [ ] Name of pin 15 is RC7

It is possible to add several aliases if you want, according to product identification system page 462 of the datasheet: `PIC16F1784-xML`, `PIC16LF1784-xML`, `PIC16LF1786-xML`, `PIC16F1787-xML` and `PIC16LF1787-xML`

Cheers,
Joel

**Comment by juanjorojash** [comment]
Hi @myfreescalewebpage 

I applied your corrections

image

Juan Jo

**Comment by juanjorojash** [comment]
Travis CI failed because of lack of metadata in the aliases, so I added it. Is giving error because the the VSS pin is set as passive.

**Comment by antoniovazquezblanco** [comment]
You should stack the passive pin and put it on top of the other VSS pin. That should solve the error ;)

**Comment by juanjorojash** [comment]
Thanks Antonio. I added a new version with the corrections. I don't know why I thought that stacking as a concept that is achieved by naming the pins, but no, it is literal stacking... 

image

Juan Jo

**Comment by myfreescalewebpage** [comment]
Thanks @juanjorojash and @antoniovazquezblanco 
If you wish to add the aliases, you should describe them properly, they have not all the same quantity of memory. Descriptions should be fixed. See datasheet page 3. 
Also, I have made a mistake in my previous comment about pin 26, name should be `RE3/~MCLR~/VPP` (one missing ~)
Joel

**Comment by juanjorojash** [comment]
Yeah, I'm all in til the end. I want to add all the aliases correctly. I will fix them tomorrow. 

Thanks guys.

Juan Jo

**Comment by juanjorojash** [comment]
I eliminated the aliases that had different pin count. I created three package options QFN, SPDIP and PDIP, each one with is own symbol and one alias for low voltage. 

If this works well I will add the other packaging options. 

image

Juan Jo

**Comment by juanjorojash** [comment]
I forgot to put new name of the package in the metadata for each package. 

Now it is ok.

Juan Jo

**Comment by myfreescalewebpage** [comment]
@juanjorojash great job, this is very nice. Just one fix to do:

PIC16LF1786-xML:
- [ ] Description: 16KB of Flash, not 8

Joel

**Comment by juanjorojash** [comment]
Done!!

Thanks guys!

Juan Jo

**Comment by myfreescalewebpage** [comment]
Thanks for the last fix, no more comment, merging!

**Pull request merged**
