### PR TITLE
LM26480: Dual 2MHz/1.5A buck converters + dual 300mA LDOs.

### PR DESCRIPTION
**Pull request by ObKo**
This PR adds LM26480 - dual 2MHz/1.5A buck converters + dual 300mA LDOs.

http://www.ti.com/lit/ds/symlink/lm26480.pdf

lm26480

Example schematic:
lm26480_sch

LM26480 uses QFN24 4mmx4mm, so no new footprint needed.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ObKo , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be `LM26480SQ` to avoid conflict if the manufacturer add package options
- [ ] Description should be `Dual 1.5A 2MHz Buck Regulators and Dual 300mA LDOs, WQFN-24` for consistency with other devices and package type at the end
- [ ] Package should be `Package_DFN_QFN:WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm` (WQFN, not QFN, if it does not exist you should submit it)
- [ ] Footprint filter will be `WQFN*1EP*4x4mm*P0.5mm*`
- [ ] Can you move Reference and Symbol Name outside of the symbol itself, for example Reference in the top left and Name in the top right corners
- [ ] Pin 25 name should be EP, and type Passive (the datasheet to not require the pin to be connected to GND)
- [ ] SW1 and SW2 type should be Power Output

Cheers,
Joel

**Comment by ObKo** [comment]
- [x] Name of the device should be `LM26480SQ` to avoid conflict if the manufacturer add package options
- [x] Description should be `Dual 1.5A 2MHz Buck Regulators and Dual 300mA LDOs, WQFN-24` for consistency with other devices and package type at the end
- [x] Package should be `Package_DFN_QFN:WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm` (WQFN, not QFN, if it does not exist you should submit it)
https://github.com/pointhi/kicad-footprint-generator/pull/361 https://github.com/KiCad/kicad-footprints/pull/1608
- [x] Footprint filter will be `WQFN*1EP*4x4mm*P0.5mm*`
- [x] Can you move Reference and Symbol Name outside of the symbol itself, for example Reference in the top left and Name in the top right corners
- [x] Pin 25 name should be EP, and type Passive (the datasheet to not require the pin to be connected to GND)
- [x] SW1 and SW2 type should be Power Output

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment.
Just need to wait the footprint before merging the symbol.
Joel

**Comment by myfreescalewebpage** [comment]
Footprint has been merged, merging the symbol.
Thanks
Joel

**Pull request merged**
