### PR TITLE
Added several components

### PR DESCRIPTION
**Pull request by RensBloom**
Hi,

I started using KiCad on a new PCB-design project. Several components I needed were missing in the libraries, so I have added those:

Potentiometers:
- MCP401x http://ww1.microchip.com/downloads/en/DeviceDoc/21978c.pdf
- MCP402x http://ww1.microchip.com/downloads/en/DeviceDoc/21945e.pdf (similar, but with WiperLock technology. I have added those as aliases of the MCP401x)

Operational Amplifier:
- OPA2325 http://www.ti.com/lit/ds/symlink/opa2325.pdf

ADC:
- MCP3201 http://ww1.microchip.com/downloads/en/DeviceDoc/21290D.pdf

Phototransistors (optical sensors):
- BPW85 https://www.vishay.com/docs/81531/bpw85a.pdf
- TEPT4400 https://www.vishay.com/docs/81341/tept4400.pdf

Virtual Ground (reference voltage):
- TLE2425 http://www.ti.com/lit/ds/symlink/tle2425.pdf

Linear Regulator:
- AMS1117 http://www.advanced-monolithic.com/pdf/ds1117.pdf

kicadadd

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you at least split this into 1 pull request per library? this will make reviewing a lot easier and does reduce the risk of running into merge conflicts.

**Comment by RensBloom** [comment]
Yes, I think I can do that

**Comment by RensBloom** [comment]
split into multiple pull requests

**Comment by RensBloom** [comment]
split into multiple pull requests

**Pull request closed without merging**
