### PR TITLE
remove trademarked USB superspeed logos from USB3 connectors

### PR DESCRIPTION
**Pull request by dlharmon**
I don't believe the USB 3.0 A/B and USB C connector symbols are usable by anyone in the USA who is not a USB licensee due to a trademark. https://trademarks.justia.com/775/82/ss-77582723.html

All USB trademarks:
https://trademarks.justia.com/owners/usb-implementers-forum-inc-2584569/

Example of modified symbol.
screenshot from 2018-10-08 17-35-15

The USB trident does not appear to be trademarked, so I left it. They were not as aggressive with such things in the past.

### CODE REVIEW

**Comment by evanshultz** [comment]
@poeschlr @stambaughw

**Comment by diegoherranz** [comment]
A few days after working on #937 and #1005, I started wondering whether we can use the USB logos or not.

In case we had to remove the SuperSpeed from the logo (don't know the legal/trademark stuff), I think we should at least make it look pretty and not just remove the "SS". E.g. having the complete USB logo (that screenshot above is missing the big dog at the bottom end which looks weird), recentring the logo, etc.

Thanks.

**Comment by myfreescalewebpage** [comment]
@KiCad/librarians anybody able to help here ?

**Comment by cpresser** [comment]
I did a quick search and read some pages.
The most important seems to be this: https://www.usb.org/logo-license

This is what I learned so far:
 * The USB logo must be reproduced exactly, which is not the case here since "SS" is written in the KiCAD font.
* There are no Test-Requirements for the SS-Trident-Logo in this case (N/A) in this document: https://www.usb.org/sites/default/files/trademark_license_agreement_licensed_mark_requirements_final_as_of_november_30_2018_locked_0.pdf
* There is a licence-agreement required for the use of any usb logos: https://www.usb.org/sites/default/files/trademark_license_agreement_fall_2018_clean_final_0.pdf
* I don't assume that this agreement is compatible with the librarys open-source-licence.
* Besides, one has to pay $3500 to enter that agreement

As a next step I wrote an email to the usb-if and asked about the requirements of using the logos in the context of EDA software. Lets see If I get a usefull answer.

**Comment by cpresser** [comment]
I actually got an answer from the USB-IF Administration:
>The USB-IF logos may only be used with products that are certified and posted to the Integrators List under that company's name, and the company must execute a USB-IF Trademark License agreement. 
> Please note the USB-IF does not certify software.

My interpretation is that all USB logos that are managed by the USB-IF should be removed from KiCad.

**Comment by poeschlr** [comment]
@cpresser does this include the normal usb symbol or just the superspeed one? (meaning is the "trident" ok as indicated by @dlharmon?)

**Comment by cpresser** [comment]
> @cpresser does this include the normal usb symbol or just the superspeed one? (meaning is the "trident" ok as indicated by @dlharmon?)

That includes all USB Logos in this file: https://www.usb.org/sites/default/files/trademark_license_agreement_licensed_mark_requirements_final_as_of_november_30_2018_locked_0.pdf

The "trident" in its standalone-version is not included in that file.
My other research also suggests it is not trademarked. So the conclusion is that we can keep it.

For clarification, this is what I am calling the trident-logo:
image

**Comment by poeschlr** [comment]
Perfect. So we can at least include something that will show it is a usb connector. @dlharmon if you could add the missing circle then this should be good to go.

**Pull request merged**
