### PR TITLE
Add AP9101 symbols

### PR DESCRIPTION
**Pull request by thatoddmailbox**
Add AP9101 symbols

Datasheet: https://www.diodes.com/assets/Datasheets/AP9101C.pdf

I've included both the SOT-25 (AP9101CK) and SOT-26 (AP9101CK6) parts. While the manufacturer uses the names SOT-25 and SOT-26 for the packages, I used the terms SOT-23-5 and SOT-23-6 for the descriptions in the documentation of the symbols, because that seemed to be the terminology other symbols used.

AP9101CK:
AP9101CK

AP9101CK6:
AP9101CK6

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by thatoddmailbox** [comment]
Sorry about that! It seems like, for whatever reason, my local copy of KiCad has the package name `TO_SOT_Packages_SMD` instead of `Package_TO_SOT_SMD`...

I've also fixed some issues that the Travis script caught. Here are screenshots of the updated symbols:

AP9101CK:
Screen Shot 2019-03-18 at 3 26 54 PM

AP9101CK6:
Screen Shot 2019-03-18 at 3 27 03 PM

**Comment by myfreescalewebpage** [comment]
Hi @thatoddmailbox , thanks for contributing,

A few comments I have during my review:

AP9101CK
- [ ] VM should be Passive to avoid ERC errors
- [ ] The symbol can be a little bit more compact as shown below:

Capture

AP9101CK6
- [ ] VM should be Passive to avoid ERC errors
- [ ] The symbol can be a little bit more compact
- [ ] Can you move pin 4 anywhere else on the symbol, this look like stacked with pin 2 which is not very clear

Cheers,
Joel

**Comment by thatoddmailbox** [comment]
Thanks for the review @myfreescalewebpage ! I've made the changes you described, could you look at the updated symbols?

Thanks,
Alex

**Comment by myfreescalewebpage** [comment]
@thatoddmailbox good fixes except for the NC pin on AP9101CK6, this should be kept on the border outline of the symbol. For example:

Capture

**Comment by thatoddmailbox** [comment]
@myfreescalewebpage Sorry about that, should be fixed now!

**Comment by myfreescalewebpage** [comment]
@thatoddmailbox no worries, I'm here to review it :)
No more comment to do, merging.

**Pull request merged**
