### PR TITLE
Add CEM3310, CEM3320, CEM3330 and CEM3340 ICs

### PR DESCRIPTION
**Pull request by robkam**
CEM3310, CEM3320, CEM3330 and CEM3340 analogue synthesizer ICs 

https://static.miraheze.org/sdiywiki/f/ff/CEM3310_datasheet_long.pdf
https://static.miraheze.org/sdiywiki/d/d1/CEM3320_datasheet_long.pdf
https://static.miraheze.org/sdiywiki/5/5c/CEM_3330-3335_long.pdf
https://static.miraheze.org/sdiywiki/e/e4/CEM_3340-3345_long.pdf

cem3310
cem3320
cem3330
cem3340

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi @robkam!
Thanks for making a first contribution to the KiCad libraries!

First, you will see a number of errors caught by our check scripts at the Details link above. Please resolve those errors (and warnings, if possible) or justify any deviations before we can merge your symbols. It looks like all of the errors and warnings can be easily fixed.

The checks are based on the KLC, our set of rules for the official library. You can find this at http://kicad-pcb.org/libraries/klc/. I know there's a lot of info there so please ask.

To help speed up review, posting an image of the symbols right here in the body of the PR is great.

And also, please sign the CLA above. We cannot merge until you do that.

Thanks again! Please ask if you have any questions.

**Comment by evanshultz** [comment]
@robkam 
Are you having problems getting all the errors and warning addressed? It can sometimes be tricky, but please ask what's getting you stuck and we can figure it out. You can continue piling on the fixes to this PR until it's ready to merge.

**Comment by Ratfink** [comment]
@evanshultz I'm a little unsure as to why, but this PR was resubmitted here: https://github.com/KiCad/kicad-symbols/pull/368

**Comment by robkam** [comment]
@evanshultz @Ratfink thanks yes I was making a mess of the PR using Git CLI so I started again, using GitHub instead at #368.

**Pull request closed without merging**
