### PR TITLE
Adding INA226

### PR DESCRIPTION
**Pull request by thomasonw**
This pull request is for the addition of the INA226

Datahsheet is located here:
www.ti.com/lit/ds/symlink/ina226.pdf

image

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution. Could you please change a few things, so this matches with other symbols in this lib and follows all the KLC rules?
1. Please mirror the symbol, so the analog inputs are on the left and I2C and other digital-pins on the right. This orientation is used by most ADCs in the lib.
2. The FPFilter should be `*:MSOP*3x3mm*P0.5mm*`
3. Please remove the commas from the tags/keywords
4. Please add `, MSOP-10` to the end of the description 
5. Finally there is a typo in the description analor --> analog. Pleae correct
6. The datasheet link should be http://www.ti.com/lit/ds/symlink/ina226.pdf
7. I think the description should be more aligned with what's in the datasheet-title, i.e. `High-Side or Low-Side Measurement, Bi-Directional Current and Power Monitor (0-36V) with I2C Compatible Interface, MSOP-10`

Thanks,
JAN

**Comment by thomasonw** [comment]
Jan,  Thank you for the coaching.  I have made the corrections and pushed them up.

**Comment by Ratfink** [comment]
I'd like to suggest shortening the pins to 100 mil, and reducing the pin name position offset to 20 mil.

**Comment by thomasonw** [comment]
Like this?   Yes, I never have understood why the default pin length was so long…

**Comment by jkriege2** [comment]
Nice work!

THanks,
JAN

**Comment by thomasonw** [comment]
OK, thanks to all - on to more!

**Pull request merged**
