### PR TITLE
Add Texas Instruments TS3DS10224

### PR DESCRIPTION
**Pull request by cronJ**
Add the Texas Instruments TS3DS10224 1:4 Differential Multiplexer

Datasheet: http://www.ti.com/lit/ds/symlink/ts3ds10224.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cronJ** [comment]
Build fails because of missing footprint (S5.1). PR for footprint is referenced.

**Comment by myfreescalewebpage** [comment]
Hi @cronJ , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "TS3DS10224RUK"
- [ ] Description is too long and should ends with the package name. I propose: `High-Speed Differential Crosspoint, WQFN-20`
- [ ] Footprint filter to be reviewed after the package is ready

Else no comment on the symbol itself.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Footprint and fp filter will need to be updated here.

**Comment by myfreescalewebpage** [comment]
Thanks. Fp filter should be `WQFN*1EP*3x3mm*P0.4mm*`

**Pull request merged**
