### PR TITLE
Added LTC7138

### PR DESCRIPTION
**Pull request by SchrodingersGat**
* 400mA 140V buck converter
* Symbol copied from LTC3638
* Slight pinout differences (LTC7138 has a "ANODE" pin)
* https://www.analog.com/en/products/ltc7138.html#product-overview
* https://www.analog.com/media/en/technical-documentation/data-sheets/7138f.pdf

image

image

### CODE REVIEW

**Comment by evanshultz** [comment]
Just one comment: If there was a bit more room between SW and ANODE would a diode symbol fit better?

**Comment by SchrodingersGat** [comment]
To accomplish this I think the SW pin should be moved up - should I do this for the LTC3638 symbol too?

**Comment by evanshultz** [comment]
No, just this one. That would break existing designs using LTC3638 and we want to keep that stable through the v5 cycle.

**Comment by SchrodingersGat** [comment]
Ok, I have moved the SW pin upwards a little

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
