### PR TITLE
Added TFA9879xx to Amplifier_Audio.lib

### PR DESCRIPTION
**Pull request by UsairemAlamgeer**
Added TFA9879xx Class D Audio Amplifier to the Amplifier_Audio.lib

Datasheet: https://www.nxp.com/docs/en/data-sheet/TFA9879.pdf

image
image

image
image

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @UsairemAlamgeer , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "TFA9879HN"
- [ ] Space in front of description to be removed, and description should ends with package name: `Mono BTL class-D audio amplifier for portable applications with digital input, HVQFN-24`
- [ ] Footprint should be `Package_DFN_QFN:HVQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias`
- [ ] Fp filter `HVQFN*1EP*4x4mm*P0.5mm*`
- [ ] VDDP should be stacked
- [ ] GNDP should be stacked
- [ ] Name of pin 25 should be "EP", it hsould be Passive and at the bottom of the symbol
- [ ] You can reduce the size of the symbol a lot 

Cheers,
Joel

**Comment by UsairemAlamgeer** [comment]
> * [x]  Name of the symbol should be "TFA9879HN"
> * [x]  Space in front of description to be removed, and description should ends with package name: `Mono BTL class-D audio amplifier for portable applications with digital input, HVQFN-24`
> * [x]  Footprint should be `Package_DFN_QFN:HVQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias`
> * [x]  Fp filter `HVQFN*1EP*4x4mm*P0.5mm*`
> * [x]  VDDP should be stacked
> * [x]  GNDP should be stacked
> * [x]  Name of pin 25 should be "EP", it hsould be Passive and at the bottom of the symbol
> * [x]  You can reduce the size of the symbol a lot
> 
> Cheers,
> Joel

**Comment by myfreescalewebpage** [comment]
Great job done here, thanks !
Last comment : can you align VDD and GNDD ?
Joel

**Comment by UsairemAlamgeer** [comment]
Yeah Sure.

**Comment by myfreescalewebpage** [comment]
@UsairemAlamgeer ping

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
