### PR TITLE
Added OPA551/OPA552 (from #1154)

### PR DESCRIPTION
**Pull request by JonathSpirit**
This is the continuation of the abandoned Pull-Request #1154 : 

summary : 

Adding the OPA551 / OPA552 U and P package

https://www.ti.com/lit/ds/symlink/opa551.pdf
https://www.ti.com/lit/ds/symlink/opa552.pdf

On the left the new fixed symbol and on the right the old abandoned one

(P package)
OPA55xP

(D package)
OPA55xD

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks!!

- At the end of the description use `DIP-8` or `SOIC-8` to indicate the package.
- The SOIC package suffix is U, not D.
- Add SR and/or BW to the description to differentiate the parts.
- Footprint filters should be `SOIC*3.9x4.9mm*P1.27mm*` and `DIP*W7.62mm*`.
- Set pin name offset to 5mil (typically 20mil but 5mil works well for these triangle symbols).
- DIP: Pins 1 and 5 should be named `NC`.
- DIP: Push the NC pins inside the part body.
- SOIC: Stack the V- pins.
- You may be able to increase the Flag pin text size when that is all done.

**Comment by JonathSpirit** [comment]
1) wow i don't really why i put D for the SOIC :/

2) can you just explain, why putting SR and/or BW to the description

3) "DIP: Push the NC pins inside the part body."
    is that ok ? : 
NC

**Comment by JonathSpirit** [comment]
Change : 

OPA551P

OPA551U

Description : 
(OPA551P/U)
High-Voltage High-Current Operational Amplifier, bandwidth 3MHz, slew-rate 15V/us, DIP-8 Package
(OPA552P/U)
High-Voltage High-Current Operational Amplifier, bandwidth 12MHz, slew-rate 24V/us, DIP-8

**Comment by evanshultz** [comment]
2. Yes, SR = slew rate and BW = bandwidth. The reason is so someone can search for parts in Eeschema and be able to tell these symbols apart. The description shouldn't be identical.
3. Yes, that looks good.

Just two more things:
- Remove ` package` from the description.
- Make pin 1 the visible V- pin on the SOIC symbol.

**Comment by JonathSpirit** [comment]
Why put the pin 1 visible ? The pin 4 is common for the 2 packages.

**Comment by evanshultz** [comment]
Thank you. We have traditionally made visible the lowest-numbered pin in a stack.

**Comment by JonathSpirit** [comment]
all is ok ! I think

**Comment by evanshultz** [comment]
Yes, indeed. Thank you!

**Pull request merged**
