### PR TITLE
Add OPA847 as alias of OPA890

### PR DESCRIPTION
**Pull request by ferdymercury**
http://www.ti.com/lit/ds/symlink/opa847.pdf

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ferdymercury** [comment]
Add SO-8 package version
image

**Comment by evanshultz** [comment]
Only two things:
1. Footprint should be `Package_SO:SOIC-8_3.9x4.9mm_P1.27mm`.
2. Footprint filter should then be `SOIC*3.9x4.9mm*P1.27mm*`.

Please take a look at footprints in the future, including other symbols in this library.

**Comment by ferdymercury** [comment]
Fixed, thanks for the hint.

**Comment by evanshultz** [comment]
Certainly! Looks good now. Thank you!

**Pull request merged**
