### PR TITLE
Add Texas Instruments TPS61322 series boost converters

### PR DESCRIPTION
**Pull request by MacroYau**
Added the following variants of the TPS61322 series:
- TPS61322DBZ
- TPS61322xADBZ (where `x` is 1 to 6)
- TPS61322xADBV (where `x` is 1 to 6)

Datasheet: http://www.ti.com/lit/ds/symlink/tps61322.pdf

TPS61322

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @MacroYau , thanks for contributing,

A few comments I have during my review:

TPS613221ADBV:
- [ ] The footprint filter should be `SOT?23*` 
- [ ] NC pins should be added to the symbol, called NC, invisible, passive, on the border outline of the symbol

No comment on the other symbols.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@MacroYau any news here following the review ?

**Comment by MacroYau** [comment]
@myfreescalewebpage Fixed, thanks for reviewing!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
