### PR TITLE
Add 93LCxxAxxOT.

### PR DESCRIPTION
**Pull request by matthuszagh**
http://ww1.microchip.com/downloads/en/DeviceDoc/20001749K.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] Would say the design should be the same than 93LCxxA without the NC pin: move CS pin 100mil to the top
- [ ] Keyword `EEPROM memory Microwire` is good and more consistent with other devices

else, sounds good !

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@matthuszagh any news here ? thanks

**Comment by matthuszagh** [comment]
Currently traveling with limited computer/internet access but hopefully can get to it soon.

**Comment by myfreescalewebpage** [comment]
@matthuszagh no worries, was just to get news from you, take the time you need to address it :)

**Comment by matthuszagh** [comment]
Change made. Let me know if anything else.

**Comment by matthuszagh** [comment]
image

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment to do. Merging.

**Pull request merged**
