### PR TITLE
Nordic nrf52840

### PR DESCRIPTION
**Pull request by ChristianHirsch**
Add symbol for [nRF52840](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52%2Fdita%2Fnrf52%2Fchips%2Fnrf52840.html) Multiprotocol Bluetooth 5/BLE/IEEE 802.15.4/2.4GHz Cortex-M4F SoC.
image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @ChristianHirsch now that we have transferred the old RF libraries across, please fix the conflicts so we can merge :)

**Comment by jkriege2** [comment]
Hi!

I think the FPFilters hould be specific to that special package: `Nordic*AQFN*1EP*7x7mm*P0.5mm*`

Best,
JAN

**Comment by ChristianHirsch** [comment]
Fixed that :+1:

**Comment by jkriege2** [comment]
Your PR emoties the DCM-file. Please fix that. Also please have a look at our continuous integration check scripts:

```
Checking symbol 'nRF52840':
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Specified footprint does not exist
     - Footprint file Package_DFN_QFN:Nordic_AQFN-73-1EP_7x7mm_P0.5mm was not found
  Violating S6.3
    Part meta-data is filled in as appropriate
    Component nRF52840 has metadata errors:
     - Missing all fields on 'Properties > Description' tab
```

**Comment by evanshultz** [comment]
@ChristianHirsch 
Will you be able to finish off this PR?

**Comment by evanshultz** [comment]
@ChristianHirsch 
Please let me know if you can finish this. I'll close this PR if I don't get a response in 24 hours.

**Comment by ChristianHirsch** [comment]
@evanshultz, yes I will fix it today ;)

**Comment by evanshultz** [comment]
@ChristianHirsch 
Great! Thank you! Please copy the symbol style we settled on at https://github.com/KiCad/kicad-symbols/pull/247.

**Comment by ChristianHirsch** [comment]
@evanshultz 
I did the redesign based on #247:
image
but I'm violating rule _S4.3_: the checks say either
```
- Pin VSS (EP) : POWER INPUT should be visible (power-in/power-out pins may never be invisible, unless in a power-net tag/symbol)
```
or
```
- Pinstack @ (0,2700) must have exactly one (1) visible pin
```
How can I fix that?

The second thing is that I named the ports differently in order to have the `PX.XX` near the pins to have them nicely aligned.

**Comment by poeschlr** [comment]
If you stack power pins the hidden one needs to be of type passive. Invisible power input pins are global labels. (This is how power labels are implemented.)

But there is a catch. The symbol editor is unhappy about a stack where the pin types differ. If you open the pin properties dialog of one of the stacked pins, it changes the pin name and electrical type of all stacked pins. So you need to finish the pins before you move them on top of each other.

**Comment by ChristianHirsch** [comment]
Ok, I broke something.. I'll try to fix this..

**Comment by ChristianHirsch** [comment]
@evanshultz 
Now, it's ready

**Comment by evanshultz** [comment]
Thanks for the updates!
- In the description and keywords I see "15.4". Is that supposed to be "802.15.4"? If so, please fix.
- I see the package as AQFN-73 in the datasheet (http://infocenter.nordicsemi.com/pdf/nRF52840_OPS_v0.5.1.pdf), so please fix the description. You have assigned the correct footprint.
- Would you add an empty pin space between the P0 bank and P1 bank and USB pins?
- Page 14 of the datasheet shows P0.11 as ball B19 and again as ball T2. Which is correct?
- Shouldn't SWDCLK be type Input?

Can you help me understand what you mean by naming the ports differently? Pages 13-15 of the datasheet list the pin functions but I don't see it specifies an order for the pin functions. You mean, for example, "AIN7/P0.31" instead of "P0.31/AIN7", right?

One more thing: If you can show the pin types in the screenshot it really helps speed up the review. This is available in KiCad version 5 pre-releases. It's fine if you're using version 4.0.x.

**Comment by ChristianHirsch** [comment]
Hi @evanshultz 
I'm sorry, still too many mistakes. But they are fixed now.
image
Regarding the double assignment: You're right. There is P0.11 assigned to B19 and T2. But obviously one of them should be P1.11. In the reference circuitry, starting from page 688, you can see that the missing P1.11 is assigned to B19, and P0.11 is assigned to T2. I did it that way, but I'm not sure if TRACEDATA2 belongs to P0.11 or P1.11. I left it at B19 because of page 14. I sent an e-mail to Nordic Semiconductor regarding this issue.

> You mean, for example, "AIN7/P0.31" instead of "P0.31/AIN7", right?

Yes, that's what I meant.

**Comment by evanshultz** [comment]
No need to say sorry! You've made a nice symbol and this is your first contribution. Thank you!

I think your symbol is wrong, unfortunately. See https://devzone.nordicsemi.com/f/nordic-q-a/21626/nrf52840-trace-pins-mapping. There, page 3 of PCA10056_Schematic_And_PCB.pdf shows this:
image

You have TRACEDATA2 on P1.11, but their schematics show P0.11. Even though the Nordic guy says "should be the correct ones", I'll assume it is correct. Can you please fix it?

**Comment by ChristianHirsch** [comment]
So, I got the correct pinout from Nordic, and you're right @evanshultz. It is:
- B19: P1.11
- T2: P0.11/TRACEDATA2

I'll fix that on Monday.

**Comment by ChristianHirsch** [comment]
Fixed the pinout.
image

**Comment by evanshultz** [comment]
Ugh... you must be using nightlies? KiCad has apparently re-arranged all the lines in this symbol.

Anyway, balls B19 and T2 look great now. Thanks!

Could you please revert the commit to the footprint filter and go back to `Nordic*AQFN*1EP*7x7mm*P0.5mm*`? Then I will merge.

**Comment by ChristianHirsch** [comment]
Done :)

**Comment by evanshultz** [comment]
@ChristianHirsch 
Thanks so much! I hope to see more contributions from you in the future!

**Pull request merged**
