### PR TITLE
Add MCP1643 LED driver

### PR DESCRIPTION
**Pull request by davidf2281**
Add fully specified symbol for MCP1643 LED driver in MSOP-8 footprint.
Datasheet is [here
](https://ww1.microchip.com/downloads/en/DeviceDoc/20005208A.pdf).

Screenshot 2020-08-25 at 19 04 36

Screenshot of the symbol editor pin table:
Screenshot 2020-08-26 at 01 46 50

Screenshot of the pin table in the datasheet:
Screenshot 2020-08-26 at 01 43 48

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @davidf2281 , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "MCP1643xMS"
- [ ] Fp filter: `MSOP*3x3mm*P0.65mm*`
- [ ] NC pin should be moved on the border outline of the symbol
- [ ] Use capital letters for VIN and VOUT
- [ ] Signal on the left and power on the right, you can cross SGND and PGNDm
- [ ] Position of the pin is strange when I look at schematic in the datasheet page 2. proposition below:

Capture

Cheers,
Joel

**Comment by davidf2281** [comment]
Hi @myfreescalewebpage and thanks so much for taking the time to review. I believe I've made all requested changes; screenshot below.
Best,
David
Screenshot 2020-08-26 at 21 22 53

**Comment by myfreescalewebpage** [comment]
Thanks for the update.
One small error on fp filter, missing "mm". Please check.
Joel

**Comment by davidf2281** [comment]
@myfreescalewebpage Apologies -- done!

**Comment by myfreescalewebpage** [comment]
No worries :)
Merging

**Pull request merged**
