### PR TITLE
added diodes inc ZXBM5210

### PR DESCRIPTION
**Pull request by g-gg**
added the symbol for the reversible DC Motor Driver ZXBM5210 from diodes inc in SO-8
Screen Shot 2019-07-29 at 23 43 09
https://www.diodes.com/assets/Datasheets/ZXBM5210.pdf
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Add `, SOIC-8` to the end of the description.
1. Change pin text offset to 20mil. You may then be able to shrink the symbol.
1. Remove `?8` from the footprint filter.
1. We want to have `-S` added on the symbol to indicate there is no thermal pad. If you want both variants, make another symbol with an `-SP` suffix and then you need a pin 9, stacked on pin 8, for the thermal pad.

**Comment by g-gg** [comment]
Shrinked version of the symbol (here in -SP variant)
Screen Shot 2019-07-30 at 22 09 16

Thanks, Evan!

**Comment by evanshultz** [comment]
Thanks! This symbol looks very nice.
1. I forgot to mention that pins should be 100mil long. Sorry about that.
1. Please change the non-EP symbol to use the `SOIC` footprint and not the `SO` one.
1. Lastly, the symbol text is cramped. What about if VDD moves right or FWD moves down?

**Comment by g-gg** [comment]
Thanks Evan for your friendly and accurate comments! You're absolutely right, I've rearranged and shortened the pins a bit, I hope you like the result.

Screen Shot 2019-08-01 at 21 46 23

**Comment by evanshultz** [comment]
Thank you once again! This looks very nice. Since We require power pins to be on the top, please move VM there. I can see that it may be a bit unbalanced but we should stick to the guidelines at http://kicad-pcb.org/libraries/klc/.

**Comment by g-gg** [comment]
Sure, that's possible. I've shifted the pins around a bit to make the symbol as compact as possible without (willingly) compromising the convention.

Screen Shot 2019-08-01 at 22 25 19

**Comment by evanshultz** [comment]
Everything looks good. Thanks so much!

**Pull request merged**
