### PR TITLE
Added Microchip LAN7500-ABJZ

### PR DESCRIPTION
**Pull request by awjlogan**
Added Microchip LAN7500-ABJZ USB 2.0 -> 10/100/1000 ethernet converter

(tidy up of horrible original PR, sorry!)

**Datasheet:** http://ww1.microchip.com/downloads/en/DeviceDoc/00001734B.pdf

**Unit A:**  
image

**Unit B:** 
image

**Properties:** 
image

CI **failed** due to missing footprint, link to matching PR: [https://github.com/KiCad/kicad-footprints/pull/2208](url)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] ~Give a reason behind any intentional library convention rule violation.~

### CODE REVIEW

**Comment by awjlogan** [comment]
Resolved merge issues from updates.

**Comment by myfreescalewebpage** [comment]
Hi @awjlogan , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "LAN7500-ABJZ"
- [ ] Footprint should be `Package_DFN_QFN:QFN-56-1EP_8x8mm_P0.5mm_EP5.9x5.9mm`
- [ ] Footprint filter should be `QFN*1EP*8x8mm*P0.5mm*`
- [ ] Description shoud ends with the package name: `Hi-Speed USB 2.0 to 10/100/1000 Ethernet Controller, QFN-56`
- [ ] I suggest to have only one unit like other LANxxxx devices. You should have positive poser pin on the top. For this device we can accept to stack positive poser pins has done for example on LAN9514

Will review the pins later when all will be on one unit.

Cheers,
Joel

**Comment by awjlogan** [comment]
Hi Joel - thanks for the review. Inline comments below:

* [X]  Name of the device should be "LAN7500-ABJZ" **Done**
* [X]  Footprint should be `Package_DFN_QFN:QFN-56-1EP_8x8mm_P0.5mm_EP5.9x5.9mm` ** Will need to open a PR for the new footprint as it doesn't exist yet **
* [X]  Footprint filter should be `QFN*1EP*8x8mm*P0.5mm*`**Done**
* [X]  Description shoud ends with the package name: `Hi-Speed USB 2.0 to 10/100/1000 Ethernet Controller, QFN-56` **Done**
* [ ]  I suggest to have only one unit like other LANxxxx devices. You should have positive poser pin on the top. For this device we can accept to stack positive poser pins has done for example on LAN9514 **In the previous (botched) PR, I had it similar to the other LANxxxx devices, but was asked to change it to the current style, as the old ones do not conform to the latest KLC, and will be a breaking change for v6. I'd prefer not to group the power pins, happy to combine into a single unit (although it will be a very big symbol). Thoughts?**

I'll push the changes on confirmation of the last point :)

**Comment by myfreescalewebpage** [comment]
Which PR do you speak about ?
Well actually it is a bid symbol if we consider the two units !

**Comment by awjlogan** [comment]
Hi Joel - I originally pushed this as #2540 but made a mess of merging so resubmitted. Comments from @cp-aquila 

> * Power-Pins should not get stacked if each of them requires a decoupling cap (S4.3, 2)
> * The symbols can be more compact. Spacing between pins in unitB should be 100mil

Re being that same as LANxxxx components, ie, ones that are not compatible with KLC anymore:

> If legacy symbols can be improved without breaking compatibility then changes are welcome and will be merged.
 
Implies that this symbol should be updated with the presumed style for v6. And yes, it's going to be a big symbol regardless..! :)

**Comment by myfreescalewebpage** [comment]
Reviewed again and understood position you have. It is true that LAN95xx have 2 units which is great.

Let's say we will keep 2 units for the LAN7500. But we need power pin on the top. Two possibilities: 1- we have a very large symbol for no reason or 2- we stack the power pins has it is done for LAN95xx.

I 'm in favor of the second solution (stack of power pin) to have something consistent in the lib. But you can design without stacking and make a screenshot so we can decide if it's nice or not ?

Full review below:

- [ ] Footprint should be `Package_DFN_QFN:QFN-56-1EP_8x8mm_P0.5mm_EP5.9x5.9mm`
- [ ] Footprint filter should be `QFN*1EP*8x8mm*P0.5mm*`
- [ ] Description should ends with the package name: `Hi-Speed USB 2.0 to 10/100/1000 Ethernet Controller, QFN-56`
- [ ] Pin XO should be Output
- [ ] Name of pin 42 should be `~RESET`
- [ ] VBUS_DET should be Input

Joel

**Comment by awjlogan** [comment]
Hi Joel - thanks, comments below :)
 
> Let's say we will keep 2 units for the LAN7500. But we need power pin on the top. Two possibilities: 1- we have a very large symbol for no reason or 2- we stack the power pins has it is done for LAN95xx.
> 
> I 'm in favor of the second solution (stack of power pin) to have something consistent in the lib. But you can design without stacking and make a screenshot so we can decide if it's nice or not ?

**Tried unstacked pins across the top, makes the symbol far too large horizontally, so have gone for stacked pins as suggested.**

* [X]  Footprint should be `Package_DFN_QFN:QFN-56-1EP_8x8mm_P0.5mm_EP5.9x5.9mm`
* [X]  Footprint filter should be `QFN*1EP*8x8mm*P0.5mm*`
* [X]  Description should ends with the package name: `Hi-Speed USB 2.0 to 10/100/1000 Ethernet Controller, QFN-56`
* [X]  Pin XO should be Output
* [X]  Name of pin 42 should be `~RESET`
* [X]  VBUS_DET should be Input
 
> EDIT: the width of unit A and unit B on LAN95xx is the same, which is good I think i just opened an old schematic I have done with LAN9514, and it's not a bad design.
**Unit A and B are different widths in this symbol, can change if requested**

**Comment by myfreescalewebpage** [comment]
I think the result is not bad :) We can keep like that.
Just need to wait the footprint (https://github.com/KiCad/kicad-footprints/pull/2208)

**Comment by awjlogan** [comment]
Hi Joel  - just wondered if there was any update on this PR? Footprint and footprint generator PRs both submitted as well. Thanks for your time :)

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
No more comment to do.
Sorry for the delay, I was not available last days.
Merging now.

**Comment by awjlogan** [comment]
> 
> 
> No more comment to do.
> Sorry for the delay, I was not available last days.
> Merging now.

No worries, thanks for your time Joel :) @myfreescalewebpage

**Pull request merged**
