### PR TITLE
Adding ASP-134602-01

### PR DESCRIPTION
**Pull request by ki5libs**
Adding Samtec ASP-134602-01 connector
[Datasheet](http://suddendocs.samtec.com/prints/asp-134602-01-mkt.pdf)
Part A (from 10 parts total) screenshot:
asp

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/768)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
I don't quite have time yet to sit down and review this, but I noticed a contradiction right off the bat. Your datasheet link and symbol RefDes list `ASP-134602-01`, but your PR name and description list `ASP-134604-01`.

The intent was for `ASP-134602-01`, right?

**Comment by ki5libs** [comment]
@DanSGiesbrecht yes, you are right. I've fixed it now.

**Comment by ki5libs** [comment]
@DanSGiesbrecht done

**Comment by DanSGiesbrecht** [comment]
Thanks for your contribution! :smile:

**Pull request merged**
