### PR TITLE
Add AMC1100/AMC1300

### PR DESCRIPTION
**Pull request by evanshultz**
http://www.ti.com/lit/ds/symlink/amc1100.pdf
http://www.ti.com/lit/ds/symlink/amc1300.pdf

image

I used the pin names from the AMC1100 datasheet.

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1595

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@evanshultz nice device!

ADC1100DWV
- [ ] There is an extra space in front of the description, to be removed

AMC1300DWV
- [ ] Datasheet link should be `http://www.ti.com/lit/ds/symlink/amc1300.pdf`
- [ ] This should be a separated device because pin have not the same name...

Cheers,
Joel

**Comment by evanshultz** [comment]
Fixed the extra space and datasheet link. Regarding the pin names, as these symbols are compatible I wanted to keep them the same. It's unclear to me why the datasheets use different names but they're interchangeable.

**Comment by myfreescalewebpage** [comment]
Same comment at https://github.com/KiCad/kicad-symbols/pull/1842#issuecomment-491969301

**Comment by evanshultz** [comment]
Would anybody prefer a triangle symbol here? I could shrink pin number text to avoid collisions.
image

@myfreescalewebpage 
I don't think the comments at that PR apply here. Maybe I'm missing something?

@poeschlr 
What is your opinion on this? Both parts have the same function and are interchangeable. We do pin name substitution on other opamp symbols, like for power and input pins. However, I do like having pin names match the datasheet for clarity.

**Comment by myfreescalewebpage** [comment]
@evanshultz not bad the triangle here, I like it :) The comment was that the part should be atomic here, like on the other PR. You can have the same design so the parts remain interchangeable.

**Comment by evanshultz** [comment]
The maintenance considerations of having two otherwise identical symbols is my concern, and why I made them an ALIAS. This has nothing to do with the footprint assignment and they're using a generic footprint so the use of the word 'atomic' isn't following with the most recent use since KiCon. Perhaps you can clarify?

**Comment by myfreescalewebpage** [comment]
Well, we claim to the contributor for atomic part very often, even if the design of the symbol are the same.... And in this specific case, the symbol is not totally the same because of the pin names. I understand your position but I think this will be better to have to separated symbol here.

**Comment by evanshultz** [comment]
@poeschlr 
Can you provide input on pin names and symbol commonality as discussed above?

**Comment by evanshultz** [comment]
@poeschlr ?

**Comment by myfreescalewebpage** [comment]
@evanshultz @poeschlr ping

**Comment by evanshultz** [comment]
@chschlue 
You're the new big dog. Do you mind taking a minute to review the above and share your thoughts on pin naming here?

**Comment by chschlue** [comment]
I'm fine with the triangle symbol and simplified pin names.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Updated with a triangle symbol:
image

It turns out the one above wasn't quite even (back corners at -200 and front corner at 300). So the one in this comment doesn't quite match the one I sent earlier. It looks a little funny to me; not too bad, just a little funny. If you have some other ideas please let me know.

**Pull request merged**
