### PR TITLE
Fix some invalid NXP URLs

### PR DESCRIPTION
**Pull request by antonblanchard**
A number of URLs no longer resolve after the NXP to Nexperia
change. Fix them.

### CODE REVIEW

**Comment by antonblanchard** [comment]
The BC337 URL still doesn't resolve, looks like they removed it from the datasheet:

https://assets.nexperia.com/documents/data-sheet/BC817W_SER.pdf

**Comment by evanshultz** [comment]
Thanks for this nice fix! I assume this was all search and replace within the text files?

The link in your last comment confuses me because BC337 is in a TO-92 package. How about using the same datasheet for BC338: https://diotec.com/tl_files/diotec/files/pdf/datasheets/bc337.pdf? If you can update BC337's datasheet this looks good to me.

**Comment by antonblanchard** [comment]
@evanshultz Yes, it was a search and replace. I only modified the URLs that were obviously bad (they return a one liner "File not found.")

Update pushed with your suggestion to use the Diotec bc337 datasheet. Thanks.

**Comment by evanshultz** [comment]
Thanks! Looks good!

In the future, we would prefer incremental commits so that it's easier to track what happened commit-by-commit.

**Comment by antonblanchard** [comment]
Thanks @evanshultz, will do so next time.

**Pull request merged**
