### PR TITLE
Diode: Add BAV199DW

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://www.diodes.com/assets/Datasheets/ds30417.pdf

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

This device should be an alias of BAV99S (and the design with two separated units is better in a schematic).

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Will do, but must wait untill tomorrow. Thanks!

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks @antoniovazquezblanco 

Just realized the package in the description is badly written, should be "SOT-363" instead of "SOT363".
Then this is ready to be merged.

Joel

**Comment by antoniovazquezblanco** [comment]
Sorry, fixed!

Thanks!

**Comment by myfreescalewebpage** [comment]
Thanks @antoniovazquezblanco , merging !

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
