### PR TITLE
Add LT1461 voltage reference in SOIC-8

### PR DESCRIPTION
**Pull request by yankee14**
Add LTC1461 family precision voltage reference in SOIC-8

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/LT1461.pdf

Screencaps:

LT1461Axx8-2

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @yankee14 , i noticed that you kept the 7th digit from MPN but you can still keep and the 9th. The second x you have if you could replace it with S. And i think that the footprint filter should be `SOIC*8*3.9x4.9mm*P1.27mm*`

**Comment by yankee14** [comment]
image

My thought process was to keep only those characters of the manufacturer part number which were required to describe all functional differences for this part.

In variants like:

- LTC1461A..
- LTC1461B..
- LTC1461C..
- LTC1461D..

This letter is required because it refers to the functional tolerance/accuracy of the part.

In variants like:

- LTC1461..-2.5
- LTC1461..-3
- etc

That is required because it refers to the functional output voltage of the part.

As far as the middle part goes:

- LTC1461..CS..
- LTC1461..IS..

These refer to the temperature rating of the component, which according to [KLC S2.2](https://kicad-pcb.org/libraries/klc/S2.2/) is a non-functional variation which should be recorded by wildcards. I would have to create additional symbol aliases that describe non-functional part variations. Now that I look at it, I'm not sure I should keep the 8 either, e.g. LTC1461Axx8-2.5 maybe should be LTC1461Axxx-2.5. Or maybe as you've suggested it should be LTC1461AxS8-2.5 I'm not sure what is right... For now I'll do as you've suggested, but I am confused about:

> but you can still keep and the 9th

Keep what and the 9th? Keep the 8th and the 9th?

Thanks

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 , thanks for contributing,

A few comments I have during my review:

- [ ] Use capital letter for VIN pin
- [ ] Name of pin 6 is VOUT
- [ ] Fp filter should be `SOIC*3.9x4.9mm*P1.27mm*` (never put the number of pins in fp filter)

Cheers,
Joel

**Comment by aris-kimi** [comment]
I am sorry for misinformation @yankee14 .
At least @myfreescalewebpage , was naming suggestion appropriate??

I have learnt my leasson for pin numbers in footprint filter, i will have this on my mind from now on. But it migh be also wrong on some open PRs.

**Comment by chschlue** [comment]
LT temp rating is just a single letter, S and 8 belong together, indicating the package.
(Meaning LT1461AxS8-2.5 and so on is correct)

**Comment by myfreescalewebpage** [comment]
@aris-kimi yes the -1 was for the fp filter. Never put the number of pins in fp filter.

**Comment by myfreescalewebpage** [comment]
@yankee14 ping

**Comment by yankee14** [comment]
Updated screenshot:
LT1461AxS8-2

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
