### PR TITLE
Add ADM3488E/ADM3490E/ADM3491E RS-422/RS-485 transceivers

### PR DESCRIPTION
**Pull request by whitequark**
Add symbols for ADM3488E/ADM3490E/ADM3491E RS-422/RS-485 transceivers. The ADM3491E symbol is a direct copy of the ADM1491 symbol. The ADM3488E/ADM3490E symbols are derived from it by removing enables and reassigning pins.

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/ADM3483E_3486E_3488E_3490E_3491E.pdf

Screenshots:
Screenshot_20200119_025304
Screenshot_20200119_025308

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by whitequark** [comment]
@evanshultz Friendly ping

**Comment by poeschlr** [comment]
We librarians are volunteers here. We will get to your review when we have the time. (There are nearly 400 symbol pull requests open so we clearly lack manpower.)

**Comment by whitequark** [comment]
Sorry, I'll be more patient.

**Comment by whitequark** [comment]
Thanks for the review. I've addressed all changes. Here's the updated ADM3490ExR screenshot:
Screenshot_20200209_131455

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
