### PR TITLE
Add G6SK-2 symbol

### PR DESCRIPTION
**Pull request by evanshultz**
While checking out https://github.com/KiCad/kicad-footprints/issues/1499, I realized we have footprints with no symbol. So here it is.

https://omronfs.omron.com/en_US/ecb/products/pdf/en-g6s.pdf
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @evanshultz thyanks for this nice symbol !

No comment except the violations indicated by travis:
- [ ] Symbol not centered, to be fixed
- [ ] The footprint is not set, is it intentional ?

For G6S-2 and G6SU-2 on which you have fixed pin name offset,  the footprint is missing too. Is it intentional ?

Cheers,
Joel

**Comment by evanshultz** [comment]
OK. I didn't worry about centering but I will move it.

There are THT and SMD relay footprints, the footprint filter allows the user to select either one in CvPcb, and this new symbol continues that paradigm.

**Comment by myfreescalewebpage** [comment]
Ok, thanks for the answer!

**Comment by evanshultz** [comment]
I got as close as I can while keeping pins on grid and not totally changing the symbol. Hope that's OK.

**Comment by myfreescalewebpage** [comment]
I'm happy with it :) Merging. Thanks!

**Pull request merged**
