### PR TITLE
Add Linear LTC2451 16-bit ADC

### PR DESCRIPTION
**Pull request by yankee14**
Add Linear LTC2451, 16-bit delta-sigma ADC, 30 or 60 samples per second, I2C interface, in DFN-8 and TSOT-23-6 packages.

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/2451fg.pdf

kicad-symbols: https://github.com/KiCad/kicad-symbols/pull/2791
kicad-footprints: https://github.com/KiCad/kicad-footprints/pull/2312
kicad-footprint-generator: https://github.com/pointhi/kicad-footprint-generator/pull/569

Screencaps:

LTC2451_DFN

LTC2451_TSOT

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by yankee14** [comment]
Continuous integration error is due to pending footprint PR. See OP body.

**Comment by aewallin** [comment]
- the DFN symbol description should end with the DFN footprint (now both end with TSOT)
- symbols are usually not named _TSOT and _DFN like here, but rather following the datasheet part numbers (p2 of the datasheet) so they would be LTC2451xTS8 and LTC2451xDDB (where x is the temperature-code)

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 , thanks for contributing,

A few comments I have during my review:

LTC2451xDDB
- [ ] Fp filter: `DFN*1EP*2x3mm*P0.5mm*`

LTC2451xTS8
- [ ] Footprint is missing
- [ ] Fp filter: `TSOT?23*`

Else just need to wait the pending footprint

Cheers,
Joel

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
