### PR TITLE
Re-add lost Infineon (IR) symbols

### PR DESCRIPTION
**Pull request by evanshultz**
All of the symbols at https://github.com/KiCad/kicad-library/pull/1564 appear to not have made it into the new v5 repo. So here they are.

Screenshots and links are at the linked PR, but since it was accepted and it only copy and paste (changing "Pitch" to "P" and fixing one typo in a description was the only change) I'm hoping this is fine to merge without further review and documentation.

I deleted L6599 from Sensor_Current since it doesn't belong there and was already present in the correct repo (Regulator_Controller).

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Forgot to mention that missing footprints are at https://github.com/KiCad/kicad-footprints/pull/981.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz will try to make this large review step by step in several comment (one by lib I think), starting below. Cheers, Joel

**Comment by myfreescalewebpage** [comment]
Amplifier Audio

IR4301:
- [ ] Device has two units but the second unit is empty, to be removed

IR4302:
- [ ] Pin 15 is missing, to be stacked with pin 31
- [ ] Pin 18 is missing, to be stacked with pin 20
- [ ] Pin 25 is missing, to be stacked with pin 23
- [ ] Pin 28 is missing, to be stacked with pin 31

IRS2452AM:
- [ ] Package in the description is not correct, this one has only 32 pins

Other devices are OK.

**Comment by myfreescalewebpage** [comment]
Driver FET

IR2010:
- [ ] Wrong voltage/current in the description

IR2010S:
- [ ] Wrong voltage/current in the description

IR2105:
- [ ] This part has been removed, is it wanted ?

IR7106S:
- [ ] Datasheet link is not correct

IRS2302S:
- [ ] Wrong datasheet link

Else sounds good to me for this library, hope I have not forget anything for this large modification!

**Comment by myfreescalewebpage** [comment]
Power Management

AUIPS6044G:
- [ ] VCC pins all appear on all untis, I think this can make troubble during the schematic design and should be avoided. VCC pins on units B, C and D to be removed according to me.

AUIPS7142G:
- [ ] VCC pins all appear on all untis, I think this can make troubble during the schematic design and should be avoided. VCC pins on unit B to be removed according to me.

AUIPS7221R:
- [ ] Name of pin 4 is missing

AUIR3316S:
- [ ] Voltage in the description is not correct, should be 26V

AUIR33402S:
- [ ] Name of pin 5 is missing

Else ok for this library.

**Comment by myfreescalewebpage** [comment]
Regulator Controller

IR1153S:
- [ ] One strange character instead of µ in the description before "PFC" (see git diff)
- [ ] "Ccontrol" in the description => "Control"

IR1155S:
- [ ] "Ccontrol" in the description => "Control"

IR1161L:
- [ ] "Ccontrol" in the description => "Control"

IR11662S:
- [ ] "Ccontrol" in the description => "Control"

IR11672A:
- [ ] "Ccontrol" in the description => "Control"

IR1167S:
- [ ] "Ccontrol" in the description => "Control"

IR1169S:
- [ ] "Ccontrol" in the description => "Control"

Else ok for this lib.

**Comment by myfreescalewebpage** [comment]
Sensor Current

L6599:
- [x] Ok to delete it

IR2175
- [ ] Pin 5 (NC) should be moved on the border outline of the symbol

IR25750L:
- [ ] "SOT-23" leading in the description to be removed

Else ok for this library.

**Comment by myfreescalewebpage** [comment]
@evanshultz all parts of this PR reviewed, comments above library by library. Please, can you separate the commits to make the modifications ? Thanks

Joel

**Comment by evanshultz** [comment]
Thanks for checking! I'm working on the above.

There is one footprint needed for these symbols which I have split off from https://github.com/KiCad/kicad-footprints/pull/981 and put in it's own PR at https://github.com/KiCad/kicad-footprints/pull/1414. But I'm asking Infineon one question about the footprint so let's hold off on merging until we get an answer.

**Comment by evanshultz** [comment]
Yep. Just saw you make a final comment. I'll wrap these fixes up soon. Thanks again!

**Comment by evanshultz** [comment]
Driver FET

IR2010(S): I believe the issue was a wrong datasheet. See https://www.infineon.com/dgdl/ir2010.pdf?fileId=5546d462533600a4015355c48f901660.

IR2105: It is obsolete and should be removed. See https://www.digikey.com/product-detail/en/infineon-technologies/IR2105/IR2105-ND/360236.

IRS2302S: I find https://www.infineon.com/dgdl/Infineon-IRS2302-DS-v02_01-EN.pdf?fileId=5546d462533600a40153567a87382800 and that is the datasheet used. Can you clarify the problem?

**Comment by evanshultz** [comment]
@myfreescalewebpage Joel, there are 3 notes above from me and the issues are fixed. Thanks for the review!

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks, IR2010 and IRS2302S re-reviewed, ok. IR2105 ok for the obsolescence.

No more comment to do on this PR, just need to wait for the footprint :)

**Pull request merged**
