### PR TITLE
Add DRV2605L

### PR DESCRIPTION
**Pull request by fauxpark**
A haptic driver for LRAs and ERMs, with an integrated library of effects. 3x3mm VSSOP-10 package.

sym
pinout
package

Datasheet: http://www.ti.com/lit/ds/symlink/drv2605l.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by fauxpark** [comment]
Hi, any update here?

**Comment by poeschlr** [comment]
We have a lack in manpower for reviews (as you might notice from the number of open pull requests awaiting review). We are aware of open pull requests, and we go through them in any order we deem appropriate (I personally always start with "least recently updated" meaning a ping by the contributor automatically moves it to the back of the queue.

If you want to speed up the process in general then help out by reviewing contributions made by others. If you want to speed up only your review then add screenshots of the datasheets pin list plus one of the pinlist from kicad (to check the electrical types without needing to search the datasheet or open kicad). 
Add a screenshot of the package definition plus the parameters used for generating the footprint you have chosen. (So anything that reduces our time needed will improve your chances of a fast review as we might just prioritize stuff that can be done fast.)

---

By the way me needing to explain this held me back from making a review so you made the situation worse.

**Comment by fauxpark** [comment]
> as you might notice from the number of open pull requests awaiting review

I did not notice this, I haven't kept up with KiCad stuff in a good while. The queue seems just as lengthy as it was back when I was fixing up the Atmel libs, but I was always aware of the lack of manpower.

> I personally always start with "least recently updated" meaning a ping by the contributor automatically moves it to the back of the queue

Good to know. Thanks for explaining.

**Comment by poeschlr** [comment]
Well the number of open pull requests is shown quite well:
Screenshot from 2020-01-15 10-10-29

**Comment by fauxpark** [comment]
I am aware.

**Comment by chschlue** [comment]
Why is the value in the lower right corner?
While there's no rule on its position, it's unusual.

**Comment by fauxpark** [comment]
@chschlue I always place it there (I think I picked it up from the original ATmega symbols). It looks a little top-heavy otherwise 🤷‍♂

**Comment by chschlue** [comment]
I see.
Thanks.

**Pull request merged**
