### PR TITLE
Onion2 s

### PR DESCRIPTION
**Pull request by fandres77**
Added Library Onion2S

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

DataSheet: https://github.com/OnionIoT/Omega2/raw/master/Documents/Omega2S%20Datasheet.pdf
Footprint in Development
screenshot_20190303_171348

Footprint request: https://github.com/KiCad/kicad-footprints/pull/1464

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @fandres thanks for this contribution,

You have many travis warnings and errors, please can you check and fix them before we can make a review of this symbol. Thanks.

Joel

**Comment by myfreescalewebpage** [comment]
@fandres I do not clearly understand the aliases you have made. The attached datasheet has only OM-O2S / OM-O2SP, what are the 3 other variants 2AJVP-OMEGA2S, OM-2SP and Omega-2S ?
The description is too long, and moreover, you should use it to indicate the differences between the aliases.
Thanks.
Good omega PR recently merged for reference: https://github.com/KiCad/kicad-symbols/pull/1430
Joel

**Comment by fandres** [comment]
Hi @myfreescalewebpage  
This is the Omega 2 / Omega 2 SMT version (It is not the same as the development module)

The Alias 2AJVP-OMEGA2S is the [FCC ID](https://fccid.io/2AJVP-OMEGA2S)
The Alias OM-O2SP is Model (see Figure)
Omega-2S is just another name that is known and available in some stores
I am Spanish speaking, what the Aliases mean, I may understand another thing by Alias. Are not names by which the product is also known?

photo_2019-03-04_13-03-40

About the long description the KLC document does not clarify that it should be short and highlight the differences

**Comment by myfreescalewebpage** [comment]
> Are not names by which the product is also known?

No, alias are device that share the same symbol and package. For example BC547 and BC548 transistors (same symbol, same package, but not the same characteristics I/U).

I think you can keep only "Omega2S" and "Omega2S+". Please also enhance the description to include the differences between the two, as indicated page 6 of the datasheet.

**Comment by fandres** [comment]
Ok, have free time I fix it.

**Comment by fandres** [comment]
@myfreescalewebpage 
Already corrected the aliases and changed a short description.
I am already working on the Footprint

**Comment by myfreescalewebpage** [comment]
Thanks @fandres, starting a complete review from this point.

**Comment by myfreescalewebpage** [comment]
Omega2S:
- [ ] You can set description to `Onion Omega2S Module, 64MB RAM, 16MB FLASH` (more consistent with other symbols)
- [ ] You can set keywords to `onion omega module`like on the Omega2+ symbol, it's good for me

Omega2S+:
- [ ] You can set description to `Onion Omega2S+ Module, 128MB RAM, 32MB FLASH` (more consistent with other symbols)
- [ ] You can set keywords to `onion omega module`like on the Omega2+ symbol, it's good for me

Common to both symbols:
- [ ] Name of pin 2 should be `GPIO_36/~PERST`
- [ ] Name of pin 5 should be `~HW_RST`, type of pin 5 should be Input
- [ ] Name of pin 7 should be `GPIO_40/LINK3`
- [ ] Types of pins 10, 11, 14 and 15 should be Output
- [ ] Types of pins 12 and 13 should be Input
- [ ] Name of pin 19 should be `GPIO_44/~WLED`
- [ ] Type of pin 24 should be Passive
- [ ] Name of pin 53 should be `SD_WP/GPIO_22`
- [ ] Name of pin 55 should be `SD_D1/GPIO_24`
- [ ] Name of pin 56 should be `SD_D0/GPIO_25`
- [ ] Type of pins 53 to 60 should be Bidirectional
- [ ] GND pins must be stacked
- [ ] I have troubles with the positions of the pins, why grouping HW_RST with some GPIO, PERST should be groupped with PCIE, SPI_CS0 next to SPI_CS1, SD_D0 next to SD_D1, next to SD_D2, next to SD_D3 etc ? If there is any reason, please indicate, else I can perform a suggestion after you made the fixes of the previous points above.

Cheers,
Joel

**Comment by fandres** [comment]
@myfreescalewebpage you can make a suggestion, I was a little lost in this.
Tnks

**Comment by myfreescalewebpage** [comment]
@fandres ok, will do, please first fix the other points

**Comment by fandres** [comment]
@myfreescalewebpage 
I upload the changes?

screenshot_20190305_134341

**Comment by fandres** [comment]
Footprint request: https://github.com/KiCad/kicad-footprints/pull/1464

**Comment by myfreescalewebpage** [comment]
Yes you can push to your branch, this automatically update your pull request.

**Comment by myfreescalewebpage** [comment]
You have forgotten two points (keywords + pins 53 TO 60 bidirectional). See my checklist above.
The rule for GND stacking is: first pin visible type power input, following pins invisible type passive.
KLC S6.3 error accepted for this symbol.

**Comment by myfreescalewebpage** [comment]
Still one keyword not updated.

I have made the following screenshot proposition for you. This is with consistency with existing Omega2+ in the library (same function at the same place). Size of the symbol has been changed a little bit in width and height, and please note the arrangement of the pin name in the left vs in the right to always get the first function (GPIOx) near to the border of the symbol.
I'm not able to push to the PR so I let you drawing it yourself and update the PR.

capture

**Comment by fandres** [comment]
Ok, @myfreescalewebpage I hope all this well this time

**Comment by myfreescalewebpage** [comment]
@fandres that's better. Some comments:
- [ ] USB pins are outside of the symbol -> to be flipped
- [ ] I2C pins are on the symbol border -> to be moved
- [ ] The guideline for GPIO pins is to keep "GPIO" near to the border of the symbol (we do this for all modules and also MCUs). For example, pin 4 "GPIO_38/SW_RST" becomes "SW_RST/GPIO_38", etc. Please carefully look at my screenshot, several pin on the right need to be renamed.
Cheers,
Joel

**Comment by fandres** [comment]
How terrible, I was careless. I already correct it.

**Comment by myfreescalewebpage** [comment]
Thanks @fandres just need the footprint now to merge the PR.

**Comment by fandres** [comment]
@myfreescalewebpage, Thank you for the patience and the experience.

**Comment by myfreescalewebpage** [comment]
@fandres no worries we are here to help you in the process and in the future you will be better and I will have pleasure to review your PRs :)

**Comment by myfreescalewebpage** [comment]
@fandres there is a branch conflict, can you solve it ? Thanks.

**Comment by fandres** [comment]
@myfreescalewebpage What is the correct way to resolve the conflict?

**Comment by fandres** [comment]
I have edited the text file, but special coding is not required

**Comment by myfreescalewebpage** [comment]
Solving branch conflict depends of the tool you are using, or if y ou are doing with command line :)

**Comment by myfreescalewebpage** [comment]
Anyway, what you have done is correct, addition of pin 64 ok for me.

**Comment by myfreescalewebpage** [comment]
@fandres77 merging following integration of the footprint :) Thanks for all the job done on this device !

**Comment by fandres77** [comment]
Thank you again

**Pull request merged**
