### PR TITLE
Adding TMC2130-TA (from #873)

### PR DESCRIPTION
**Pull request by JonathSpirit**
This is the continuation of the abandoned pull-request #873 

Summary :

Adding the high voltage driver for two-phase bipolar stepper motor TMC2130-TA
(this is the TQFP version of the TMC2130-LA)

datasheet :
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2130_datasheet.pdf

Please see the QFN PR here : #1830 

TMC2130-TA

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by JonathSpirit** [comment]
Thanks for the tags, but i do not wait for any footprint :)

**Comment by myfreescalewebpage** [comment]
Hi @JonathSpirit , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter should be `TQFP*1EP*7x7mm*P0.5mm*`
- [ ] Name of pin 3 should be `~CS~_CFG3` 
- [ ] Can you move GNDP on the right of GNDA ?
- [ ] GNDD does not exist, can you stack pin 6, 31, 36 and pin 37 with GNDP ?
- [ ] Name of pin 29 should be `~DRV_EN~_CFG6`

Cheers,
Joel

**Comment by JonathSpirit** [comment]
For the 4 point : 

> GNDD does not exist, can you stack pin 6, 31, 36 and pin 37 with GNDP ?

Please see https://github.com/KiCad/kicad-symbols/pull/1830#issuecomment-491396282

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes on this PR too. There is a merge conflict due to #1830, can you solve it, then it is ready to merge.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
