### PR TITLE
fix symbol to match footprint pr

### PR DESCRIPTION
**Pull request by matthuszagh**
Modifies the [SE5004L rf amp](https://www.skyworksinc.com/-/media/SkyWorks/Documents/Products/601-700/SE5004L_202393B.pdf) to match the [proposed footprint PR](https://github.com/KiCad/kicad-footprints/pull/2162).

se5004l-sch

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh thanks for this fixes,

- [ ] The datasheet link seems broken, can you also update it ? "https://www.skyworksinc.com/-/media/SkyWorks/Documents/Products/601-700/SE5004L_202393B.pdf"
- [ ] I do not agree for changing pin 1, it is not connected in the datasheet... Or maybe you have another information ?
- [ ] Same comment for the EP, where have you found it is to be connected to GND ?

Joel

**Comment by matthuszagh** [comment]
Hey @myfreescalewebpage thanks for the review. Pin 1 etc and EP are connected. Check the land pattern in the first image of the footprint PR I referenced (taken from the datasheet). Let me know if any further concerns, I'll update the datasheet link.

**Comment by myfreescalewebpage** [comment]
I have seen you connected them on the footprint. But I refer to the datasheet. Why connecting these pins together ?

**Comment by matthuszagh** [comment]
I'm referring to the datasheet too, which is what I was discussing in my last comment. I'll post the image from the datasheet again.

77214172-0a2f5180-6acb-11ea-8829-13153744247d

That first image on the left is the land pattern. As you can see, the EP and all ground pins are connected together. In order for the symbol to match this footprint, EP and ground must be connected.

Does this make sense, or am I missing your point?

**Comment by myfreescalewebpage** [comment]
No worry, I haven't checked the footprint in the datasheet, only the description of pins.
The symbol is not broken, so no need to wait V6, and I don't anything which need the footprint to be merged first.
Can you update the datasheet link first ?
Thanks,
Joel

**Comment by matthuszagh** [comment]
Datasheet updated.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
