### PR TITLE
Added MCP2542FD

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- MCP2542WFD alias
- DFN-8 3x3mm package (matches existing footprint)

image

Datasheet - http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en585412

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @SchrodingersGat , thanks for contributing,

A few comments I have during my review:

- [ ] Can you explain from where the name of the device comes from ? I do not found any information about "FD" of "WFD" you have set in the name of the symbols
- [ ] Chapter 1.7.10 in the datasheet recommends to stack PAD pin with VSS
- [ ] I disagree with EP size, I think the footprint should be `Package_DFN_QFN:DFN-8-1EP_3x3mm_P0.65mm_EP1.47x2mm`

Cheers,
Joel

**Comment by SchrodingersGat** [comment]
Hi @myfreescalewebpage thanks for the review;

From the first page of the datasheet:

image

image

The other points can easily be addressed. I'll await your feedback from the other PR

**Comment by myfreescalewebpage** [comment]
@SchrodingersGat thanks to point me this. What I do not understand is that there is no difference between the package version.... Have you got more details about that ? Else, you will need to rename the symbol to "MCP2542FD_DFN8" for example

**Comment by SchrodingersGat** [comment]
There is a difference on Pin 5 - one package has VIO and one package has NC

**Comment by myfreescalewebpage** [comment]
> There is a difference on Pin 5 - one package has VIO and one package has NC

Sure. However I was speaking about the package name. How the difference is made between DFN and SOIC for example . I do not found the information...

**Comment by SchrodingersGat** [comment]
Oh, sorry you are correct, I see what you mean now.

The ordering guide at the end of the datasheet has this:

So a suffix of ```MF``` would be appropriate here.

image

**Comment by myfreescalewebpage** [comment]
Thanks, so your devices should be `MCP2542FDxMF` with alias `MCP2542WFDxMF` (added to previous checklist).
Joel

**Comment by SchrodingersGat** [comment]
I have updated the part numbering as suggested.

I think the footprint selection is correct based on the exposed-pad sizes given in the datasheet:

image

**Comment by SchrodingersGat** [comment]
Also fixed the datasheet links which were incorrect

**Comment by myfreescalewebpage** [comment]
Thanks! Made a complete review, no more comment now. Merging.

**Pull request merged**
