### PR TITLE
Added TMC2130-LA to Motor_Driver

### PR DESCRIPTION
**Pull request by G-Pereira**
I added Trinamic TMC2130-LA bipolar stepper motor driver since I've created for a personal project. Hope this is useful to you!

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing: https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2130_datasheet.pdf
- [x] An example screenshot image is very helpful
tmc2130-LA
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
All Good!

### CODE REVIEW

**Comment by G-Pereira** [comment]
Is this good?

**Comment by Misca1234** [comment]
Hi

Your description is a little bit long, you can shorten it to something like this
"Driver for two-phase bipolar stepper motor. 2.0A, SPI, QFN36"

There is a foot print that match your component better
QFN-36-1EP_5x6mm_P0.5mm_EP3.6x4.1mm

you should change your foot print filter into
QFN*1EP*5x6mm*P0.5mm*EP3.6x4.1mm*


Pin 11, 12,24 and 35 should be connected to GND
This component have an exposed and connected pad
GND pins should be stacked, you do it like this

1. Rename pin 12 to GND
2. Rename pin 11 to GND, make it passive and invisible and place it ontop of pin 12
3. Rename pin 24 to GND, make it passive and invisible and place it ontop of pin 12
4. Rename pin 35 to GND, make it passive and invisible and place it ontop of pin 12
5. Create a pin, number it 37, call it GND, make it passive and invisible and place it ontop of pin 12

**Comment by G-Pereira** [comment]
Should this have the name TMC2130 and have two footprints? see #873

**Comment by G-Pereira** [comment]
see #1070 too please

**Comment by Misca1234** [comment]
Hi

I checked the already merged TMC-2100-LA/TMC2041-LA, what do you say to move the pins around in your symbol so they match the rest of TRIMAC's symbols already in there (Move TST pin for example)

You can also see that your FP should be 
(correction related to above comment)
`QFN*1EP*5x6mm*P0.5mm*`

**Comment by G-Pereira** [comment]
I can make libraries for the following drivers and make them look a like to be easier to used them as you said since it is a really nice idea.
TMC2100
TMC2130
TMC2208
TMC5160
TMC2160
TMC2660
And put it all on the same pull request?

**Comment by Misca1234** [comment]
> There's too many wrong things with the TMC2100-LA library.

Note that -LA is the QFN-36 Pin variant.

have you updated your repository ?
TMC2041-LA, TMC2100-LA 36 pin, TMC2100-LA 48 pin was merged a couple days ago

https://github.com/KiCad/kicad-symbols/pull/796

> And put it all on the same pull request?

Try to avoid that, the review will take so much longer time, better to split them in 3 pushes or in seperate ones

**Comment by G-Pereira** [comment]
Ok, so is this one ready? I've followed all your instructions

**Comment by Misca1234** [comment]
Hi

Please change the description from
Driver for two-phase bipolar stepper motor. 2.0A, SPI, QFN36
into
Driver for two-phase bipolar stepper motor, 2.0A, SPI, 4.75-46V, QFN-36

Change name of Pin 9 to DNC
Separate the GND pins into GNDA, GNDP and GNDD (like TMC2100-LA)
Stack pin 37 ontop on GNDD

Change pin 14, 27, 28, 29 and 33 to passive

**Comment by G-Pereira** [comment]
Are you kidding me... You 've asked me to join the ground pins above... which didn't made sense since the groundpad is different than the ground pin but I have changed it. I is this a joke? Are you even capable of being a kicad librarian?

**Comment by G-Pereira** [comment]
And btw GNDD is pin 37...

**Comment by G-Pereira** [comment]
Done, please merge it so I can follow the same patterns and submit all the others

**Comment by Misca1234** [comment]
Lets see if someone else is interested to work on this

**Comment by G-Pereira** [comment]
Please unassign yourself

**Comment by evanshultz** [comment]
@G-Pereira 
All librarians are volunteers and are working  in our spare time to grow and improve the library as a team and with community contributions. Your comments above are not helpful. Please do not attack or be so sarcastic towards Stefan or any librarian and use a more positive attitude even when something doesn't make sense to you.

@Misca1234 was never assigned to this PR from the GH history I see above.

Let me take a look at this in the next day or so and we can figure out this symbol and get it merged. I appreciate your willingness to contribute more symbols and I'm looking forward to that.

**Comment by evanshultz** [comment]
I'm going to approach this fresh and ignore any discussion above. Please keep that in mind and start over with me from this point.

- Put ref des at top left and value at top right.
- Should pin 11 be stacked on 37? Pin 11 only says connect to GND and not which ground.
- Along the top from left to right, I'd like to see VCC_IO, 5VOUT, VCC, VSA, and VS. That puts the digital power input on the left side by the digital pins and seems like the best flow for wiring up the IC. It also puts VS and VCP close together. I assume you're familiar with this part so is there a better way?
- This is my preference, but if you move the CP* pins towards the top of the right side then all the charge pump pins will be together.
- Let's put all pins that interface with the processor on the left, and motor pins on the right. So move DIAG0, DIAG1, and DCO to the left side.
- Once the pins are moved as mentioned above, spread apart the BRA and BRB pins so the resistors can fit in there nicely. Alternatively, you could move both of those pins to the bottom of the symbol and closer to ground. But it's fine where they are as they can easily share a ground and are close to the drive output pins.
- Making DIAG0 and DIAG1 Open Collector type may avoid some false ERC errors if they're paralleled with other pins. If they're push-pull, of course, Output is the correct type and they can't be paralleled. This is ambiguous case so I'll leave it to you to decide.
- Why does pin 22 have an overbar?
- Pin 5 should be Bidirectional type.
- On the left side, I'm thinking of a different pin arrangement. What do you think about the below image? Pin 5 could go lower for easy daisy-chaining of ICs. Pin 10 could go at the top to get it out of the way, but I don't know if there's a clear preference for using SPI or not.
image

**Comment by myfreescalewebpage** [comment]
Hello @G-Pereira 

Can you process the recommandations made by @evanshultz above ? Or indicate if you do not wish do work on this subject again.

Thanks.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Closing as a new PR substitutes it.

**Pull request closed without merging**
