### PR TITLE
Add analog switch TS5A23159

### PR DESCRIPTION
**Pull request by tommag**
Add the TI TS5A23159 dual analog switch, based on the TS3A24159 (different pinout).
Datasheet link : http://www.ti.com/lit/ds/symlink/ts5a23159.pdf
Capture d’écran du 2020-03-30 10-03-21
Capture d’écran du 2020-03-30 10-03-35
Capture d’écran du 2020-03-30 10-03-50

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by tommag** [comment]
Fixed KLC violations : symbol not centered on origin, bad footprint filter. 

New screenshots : 
Capture d’écran du 2020-03-30 10-25-22
Capture d’écran du 2020-03-30 10-25-41
Capture d’écran du 2020-03-30 10-25-58

**Comment by myfreescalewebpage** [comment]
Hi @tommag , thanks for contributing,

A few comments I have during my review:

VSSOP version:
- [ ] Footprint filter should be `VSSOP*3x3mm*P0.5mm*`

UQFN version:
- [ ] Footprint filter should be `Texas?R*PUQFN*`

Cheers,
Joel

**Comment by tommag** [comment]
Thanks for your comments ! I have updated the library accordingly.
Cheers, 
Tom

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
