### PR TITLE
Bq24090dgq

### PR DESCRIPTION
**Pull request by lukh**
Add BQ24090DGQ, 1A, single cell, single input li-ion and lipo charger

[Link](https://www.ti.com/lit/ds/symlink/bq24090.pdf?&ts=1589185554844)

Screenshot from 2020-08-27 11-32-48

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by lukh** [comment]
I 'll provide a new footprint, script based as soon as possible..

**Comment by myfreescalewebpage** [comment]
@lukh KiCad v6 is coming soon, if you want to have this symbol integrated, please provide the footprint asap. I will review the symbol, for that can you solve the branch conflict please ?
Joel

**Comment by myfreescalewebpage** [comment]
Hi @lukh thanks

A few comments I have during my review:

- [ ] Package in the description should be "HVSSOP-10"
- [ ] Footprint should be `Package_SO:HVSSOP-10-1EP_3x3mm_P0.5mm_EP1.57x1.88mm_ThermalVias`
- [ ] Fp filter: `HVSSOP*1EP*3x3mm*P0.5mm*`
- [ ] TS, PRETERM, ISET and ISET2 should be Passive
- [ ] TS on the right will be better to wire the battery thermistance This will also permit to reduce a bit the size of the symbol (200mil in height and 200mil in width I think)
- [ ] NC pin should be on the border outline of the symbol

Cheers,
Joel

**Comment by lukh** [comment]
- [ ]  Package in the description should be "HVSSOP-10"
- [ ] Footprint should be Package_SO:HVSSOP-10-1EP_3x3mm_P0.5mm_EP1.57x1.88mm_ThermalVias
- [ ] Fp filter: HVSSOP*1EP*3x3mm*P0.5mm*
- [ ] TS, PRETERM, ISET and ISET2 should be Passive
- [ ] TS on the right will be better to wire the battery thermistance This will also permit to reduce a bit the size of the symbol (200mil in height and 200mil in width I think)
- [ ] NC pin should be on the border outline of the symbol

**Comment by myfreescalewebpage** [comment]
Thanks for the update, looks very great. Just need to wait the footprint.

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
