### PR TITLE
Add Flash Memory GD25DxxCT

### PR DESCRIPTION
**Pull request by ikuo**
Datasheet: http://www.elm-tech.com/en/products/spi-flash-memory/gd25d10/gd25d10.pdf

image

## Checklist
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ikuo , thanks for contributing,

A few comments I have during my review:

GD25D10CT
- [ ] Description should ends with the correct package name: `1Mbit, 3.0V Standard and Dual Serial Flash, SOP-8`
- [ ] Footprint filter should be `SOP*3.9x4.9mm*P1.27mm*`
- [ ] Pin length should be 100mil
- [ ] Symbol is a bit large and tall, you can reduce it
- [ ] Name of pin 2 should be "O1/SO" to have the main function on the border of th symbol
- [ ] Name of pin 4 should be VSS
- [ ] Name of pin 6 should be SCLK
- [ ] NC pin should be Invisible and move on the border outline of the symbol

GD25D05CT
- [ ] Description should ends with the correct package name: `512kbit, 3.0V Standard and Dual Serial Flash, SOP-8`

Cheers,
Joel

**Comment by ikuo** [comment]
image

**Comment by ikuo** [comment]
Hi @myfreescalewebpage

Thank you for the review.
I reflected them.

**Comment by ikuo** [comment]
@myfreescalewebpage Thank you for the example.

I've updated as follows:

image

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
