### PR TITLE
Add ADP5091/ADP5092

### PR DESCRIPTION
**Pull request by jneiva08**
Add Analog ADP5091/ADP5092

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/ADP5091-5092.pdf
Footprint: https://github.com/KiCad/kicad-footprints/pull/1932

ADP5091

ADP5092

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

ADP5091
- [ ] The expose pas should be stacked with AGND according to the datasheet
- [ ] SW can be Power Input

ADP5092
- [ ] The expose pas should be stacked with AGND according to the datasheet
- [ ] SW can be Power Input
- [ ] REG_GOOD is Output

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
For the input of regulators yes we have the pins mainly on the left.
Merging.

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
