### PR TITLE
fixed some wrong footprint links to THT TO-XYZ packages

### PR DESCRIPTION
**Pull request by jkriege2**
fixes a few bugs and renames according to this: https://github.com/KiCad/kicad-footprints/pull/470

### CODE REVIEW

**Comment by Ratfink** [comment]
I just re-ran the Travis CI build, and it found some footprint name errors; could you please fix those before merging?  I assume this happened because some further name changes were made between creating this PR and merging the other one.

**Comment by evanshultz** [comment]
Great Jan!

Just one thing: for 2SC1815 can you use another link? Perhaps https://media.digikey.com/pdf/Data%20Sheets/Toshiba%20PDFs/2SC1815.pdf (I prefer Toshiba) or http://www.unisonic.com.tw/datasheet/2SC1815.pdf or even https://www.centralsemi.com/get_document.php?cmp=1&mergetype=pd&mergepath=pd&pdf_id=2SC1815.PDF.

**Comment by jkriege2** [comment]
Done @evanshultz !
Can be merged?

cu
JAN

**Comment by poeschlr** [comment]
Looks good to me. This does fix the original problem reported in #520.

Thanks for this.

**Pull request merged**
