### PR TITLE
Add MCP120/MCP130 supervisory family

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/11184d.pdf

Probably the names of symbols are not the best... didn't add the value to be more generic.
The symbol was created for all variations of pinout and footprint.

Screenshots: 

TO-92 with‘D’ Bondout

MCP120-DITO

TO-92 with‘G’ Bondout

MCP120-GITO

TO-92 with‘H’ Bondout

MCP120-HITO

150mil SOIC

MCP120-ISN

SOT-23-3

MCP120-ITT

TO-92 WITH‘F’ BONDOUT

MCP130-FITO

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] Name of positive power pin is `VDD`
- [ ] Name of negative power pin is `VSS`
- [ ] "pull-up" in the keywords is only for MCP130 versions
- [ ] RST should be Open Collector
- [ ] "I" in the device names indicate the temperature range and should be discarded, i.e. replaced with "x" (so MCP120-xxxDITO becomes MCP120-xxxDxTO, etc)

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage have made almost all the changes.
Probably the RST in MCP130 should be output and MCP120 can be Open Collector.
For that, MCP130 cannot be a alias. What you think?

**Comment by myfreescalewebpage** [comment]
Thanks for the changes already made.
No, for me both are Open Collector, the difference is only that the MCP130 provide an internal pull up, but it is Open Collector, not Output (i.e. not push pull output).
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage have made the changes you requested.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
