### PR TITLE
Add LT3580

### PR DESCRIPTION
**Pull request by jneiva08**
Add LT3580 DFN and MSOP

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/3580fg.pdf

Symbol: 
lt3580

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 

I have not yet made a full review, but based on the screenshot:
- [ ] You should define a symbol for each package option (atomic parts)
- [ ] SW type is Open Collector

Cheers,
Joel

**Comment by jneiva08** [comment]
Hi @myfreescalewebpage .

Probably the names should be LT3580xDD and LT3580xMS8E, because of the first letter is temperature rating.
You mean to have two independent symbols for each package?

The VC, RT, SS and FB probably should be passive.

**Comment by myfreescalewebpage** [comment]
> You mean to have two independent symbols for each package?

Yes axactly, with correct footprint set for each symbol.

> The VC, RT, SS and FB probably should be passive.

Probably :)

**Comment by jneiva08** [comment]
@myfreescalewebpage , have made the changes, now it looks like:
lt3580

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks for the fixes ! Just look to make to a complete review, one comment for both symbols:

- [ ] FB should be Input

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks for the fixes. The pull request has a branch conflict, can you solve it so I wille be able to merge ? Thanks. Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage , hope it is already fixed

**Comment by myfreescalewebpage** [comment]
The merge has failed, the library can't be opened. A line "$ENDCMP" is missing in the dcm file just before the definition of "LT3580xDD" (when opening with kicad, the line where the problem is is indicated as shown below).

Capture

**Comment by jneiva08** [comment]
@myfreescalewebpage fixed

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
