### PR TITLE
Interface_UART: Add SC16IS740

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: https://www.nxp.com/docs/en/data-sheet/SC16IS740_750_760.pdf

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
All looking good except the IRQ pin which should be open collector.
As soon as you fix that, I'll merge.

Thanks!

**Comment by antoniovazquezblanco** [comment]
Done deal! Thank you!

**Comment by diegoherranz** [comment]
Thanks, @antoniovazquezblanco.

I've just noticed one more thing. There is an extra comma in the keywords.
Sorry I didn't notice the other day.

Thanks!

**Comment by antoniovazquezblanco** [comment]
Also done! Thanks!

**Comment by diegoherranz** [comment]
Thanks for the changes. I've checked:
- Pinout
- Pin types
- Pin arrangement
- Description
- Datasheet link
- Footprint
- Footprint filter

All ready to be merged.

Thanks!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
