### PR TITLE
Add AD5691RxMRZ and AD5693RxMRZ I2C DACs

### PR DESCRIPTION
**Pull request by pgrudzinski**
Screenshot:
image
Datasheet:

[AD5693R, AD5692R, AD5691R and AD5693](http://www.analog.com/media/en/technical-documentation/data-sheets/AD5693R_5692R_5691R_5693.pdf)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- VREF: Make this Passive type.
- Swap positions of ~LDAC and ~RESET to make connecting them easier.
- SDA should be Bidirectional type.
- Replace first char of footprint filter (`?`) with `M`.
- I believe the trailing `Z` in the PN is for RoHS compliance so you can remove it. I do see several other symbol names with the Z so if you leave it alone that's OK too.

Remove AD985x from this PR.

**Comment by pgrudzinski** [comment]
i have implemented your comments, although I am not sure about VREF, as it is software programmable whether it is input or output.

**Comment by evanshultz** [comment]
Making VREF Passive type means whichever direction it goes won't cause a problem. The library pin types are chosen to avoid issues with the ERC engine right now and this matches our convention.

- Delete the newly-added AD5693RxRMZ symbol.
- There is still a Z suffix description for 5693.
- You still left the AD985x parts in this PR.

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
