### PR TITLE
PCF8523TS Addition of TSSOP-14 Symbol

### PR DESCRIPTION
**Pull request by johnfwhitmore**
This is the last of the PCF8523 variants, this time the TSSOP device. I number of stacked NC pins, and the addition of ~INT2 and CLKOUT.

---

Datasheet - https://www.nxp.com/docs/en/data-sheet/PCF8523.pdf

Screenshot from 2019-04-16 17-51-51

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
Though I had posted an updated screen shot without NC pins stacked, but perhaps I got distracted.


Screenshot from 2019-04-17 19-32-29

**Comment by myfreescalewebpage** [comment]
Hi @johnfwhitmore , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter should be `TSSOP*4.4x5mm*P0.65mm*`
- [ ] Pin 8 is Open Collector
- [ ] Pin 13 is Output
- [ ] NC pin orientation is not correct, the other extremity should be on the border outline of the symbol

Cheers,
Joel

**Comment by johnfwhitmore** [comment]
I think Pin 13 is still Open Drain

Screenshot from 2019-04-17 21-15-16

**Comment by myfreescalewebpage** [comment]
I wonder about pin 13 when it is INT1, in this I think it's an output, isn't it ?
NC pin should be IN the symbol anyway, as shown below.

Capture

**Comment by johnfwhitmore** [comment]
Screenshot from 2019-04-18 16-40-18

**Comment by myfreescalewebpage** [comment]
@johnfwhitmore thanks for the fixes, no more comment. Merging.

**Pull request merged**
