### PR TITLE
Cleaned up issues from MCU_NXP_Kinetis.lib

### PR DESCRIPTION
**Pull request by DerekGn**
Cleanup from #25
Fixed footprints
Stacked power pins
Modified symbols to use datasheet labels

**Question:**
A number of symbols have an extra pin called EPAD for example MKL04Z32VFM4 should this be removed?
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
About the EPAD pin:
I assume this represents the exposed pad found in the packages. Normally these pins should have the pin number one higher than the normal pin numbers. The footprint should then have the name [package name]-[number of pins]-1EP-...

Your example MKL04Z32VFM4 has `Package_DFN_QFN:QFN-32-1EP_5x5mm_P0.5mm` assigned.
As you can see here it has a pad with number 33 (Same number as the pin EPAD):
screenshot from 2018-01-04 00-03-29

**Comment by DerekGn** [comment]
Cool just wanted to check. Thanks.

**Comment by poeschlr** [comment]
Kicad can not have vias that are not connected to a pad (Either using a trace to connect to a pad or placing the via directly into the pad work.)

**Comment by DerekGn** [comment]
OK thanks for the info

**Comment by poeschlr** [comment]
Re running scripts can be triggered by closing and reopening the pull request.

Is this ready for review?

**Comment by DerekGn** [comment]
Yes this branch can be reviewed.
The footprints where merged recently.

**Comment by poeschlr** [comment]
Looks good. Thanks

**Pull request merged**
