### PR TITLE
atsamv71qxxb-aab added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
atsamv71qxxb-aab added.
(duplicated from atsame70q family)

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/SAM-E70-S70-V70-V71-Family-Data-Sheet-DS60001527D.pdf
image

image
image
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi,

thanks for the addition.
Did you change anything? Or is it a 1:1 copy of the `E70` part?
Assuming its exactly the same, the alias feature could be used. The downside would be that the `SAMV70` part is in the `SAME` library. To be honest I am not sure if that's a good solution. But duplication is not good either :unamused:

**Comment by serkanxselcuk** [comment]
Hi @cpresser,

yes, it is 1:1 copy of E70.

- How would you find to change library name into 'SAME_SAMV'? 
 - Or reorder libraries as 'SAMx70' format?

**Comment by cpresser** [comment]
Hi @serkanxselcuk,
* Renaming or re-ordering the library would be a breaking change, we don't want that in between major releases. Any re-organization will have to wait for the 6.0 release.
* Adding a copy is probably the way to go since we are out of alternatives.

@KiCad/librarians Does anyone have an idea that's better then making a new library that has a copy of an existing symbol?

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk @cpresser I don't think all the SAMV are aliases of the SAME devices, so event if the SAMV family is just starting, there will be others in the future and we will only have 1 duplicated item (with 2 aliases) which is not so much.

I think creating the SAMV family now is the best option.

@serkanxselcuk can you solve the branch conflict please ?

Joel

**Comment by cpresser** [comment]
> @serkanxselcuk @cpresser I don't think all the SAMV are aliases of the SAME devices, so event if the SAMV family is just starting, there will be others in the future and we will only have 1 duplicated item (with 2 aliases) which is not so much.
> 
> I think creating the SAMV family now is the best option.

Okay. That is exactly the input I wanted to hear from another maintainer. Thanks!
And yes, I agree. Lets make a new library.

**Comment by cpresser** [comment]
I took the liberty of fixing the merge issues in the github frontend. Lets see if travis likes it.

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk any news here ?

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage ,
I am back active on this PR. I didn't make any change out of merging master into this branch. But travis seems to be very busy now :)

**Comment by myfreescalewebpage** [comment]
Yes i have seen there was a sort or interruption of the service. It's back now.

**Comment by serkanxselcuk** [comment]
Do I need to make any changes?

**Comment by myfreescalewebpage** [comment]
At least the package in the description: "LQFP-144". @cpresser would you like to continue the review of this PR ?

**Comment by cpresser** [comment]
@myfreescalewebpage If you have the capacity for this, please take care of it. I am low on motivation and rather invest my time in footprints.

**Comment by myfreescalewebpage** [comment]
Will do

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk full review below:

- [ ] Names should be "ATSAMV71Q21B-A", etc (the two last letters are to be removed, discarded in the kicad lib). Comment apply to the aliases too.
- [ ] Package in the description: "LQFP-144"

All pins correct according to SAME reference (check with text compare tool)

Else looks great, there is 1 or 2 rules which are not followed but the compatibility with the SAME device is great to keep.

Joel

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage ,
the two last letters are to be removed, description fixed with 'LQFP-144'.

Do you mean I must compare with ATSAME70 or do you mean you checked it? Anyway, I compared ATSAME70Q21A-AN and ATSAMV71Q21B-A using meld. All pins are 1:1 same.

Thank you for your effort.
Serkan

**Comment by myfreescalewebpage** [comment]
No I just mean I have checked it :)

**Comment by myfreescalewebpage** [comment]
No more comment, merging.

**Pull request merged**
