### PR TITLE
Added TI DS25BR100/101/110/120 LVDS Buffer Series

### PR DESCRIPTION
**Pull request by Wardstein**
Added TI DS25BR100/101/110/120 LVDS Buffer Series

Dahasheets:
100/101: https://www.ti.com/lit/ds/symlink/ds25br100.pdf
110: https://www.ti.com/lit/ds/symlink/ds25br110.pdf
120: https://www.ti.com/lit/ds/symlink/ds25br120.pdf

grafik
grafik
grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by cp-aquila** [comment]
Hi,

pin names, numbers and package seem to be identical for all devices. That is a good indicator that the alias feature can be used.
Why did you choose Interface.lib? Why not Buffer.lib?

**Comment by Wardstein** [comment]
Hi,

not all the pins are identical, the PE and EQ pins are different for all devices and also pin numbers are swapped (1 & 4).

Did not saw/thought about the Buffer.lib. Makes also sense there, as there is already a high speed buffer/line driver IC.
Shall I move it there and send a new commit?

**Comment by cpresser** [comment]
> Hi,
> 
> not all the pins are identical, the PE and EQ pins are different for all devices and also pin numbers are swapped (1 & 4).
> 
My bad, I did not check properly.

> Did not saw/thought about the Buffer.lib. Makes also sense there, as there is already a high speed buffer/line driver IC.
> Shall I move it there and send a new commit?
Yes, please move them.

I also saw some items that are buffer-like in interface.lib. Bu I think that's not correct. If there is no conversion of signals buffer.lib is the correct choice.

**Comment by myfreescalewebpage** [comment]
@Wardstein ping, are you still alive on this subject ?

**Comment by myfreescalewebpage** [comment]
No news of the author, indicate this is Abandoned

**Pull request closed without merging**
