### PR TITLE
Tps61230drc

### PR DESCRIPTION
**Pull request by lukh**
Add Tps61230drc, Step Up converter with 5A switchs
[Link](http://www.ti.com/lit/ds/symlink/tps61230.pdf?&ts=1589185383516)
Screenshot from 2020-05-11 10-24-38

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lukh , thanks for contributing,

A few comments I have during my review:

- [ ] Symbol too large and too tall, please have a look to other recent regulator
- [ ] I disagree with the footprint, probably a specific one should be submitted
- [ ] EP missing in fp filter
- [ ] Pin offset 20mil

Will do a full review after that

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@lukh ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by lukh** [comment]
- [ ] Symbol too large and too tall, please have a look to other recent regulator
- [ ] I disagree with the footprint, probably a specific one should be submitted
- [ ] EP missing in fp filter
- [ ] Pin offset 20mil

**Comment by myfreescalewebpage** [comment]
Thanks for the update.

- [ ] Still wrong fp filter, should be: `VSON*1EP*3x3mm*P0.5mm*`
- [ ] Still not the correct footprint (the EP size is not correct).

Important note: the repo will be locked on 2020-09-01 in preparation of v6. I recommend you to create the footprint asap, else the symbol can't be merged.

Joel

**Comment by lukh** [comment]
"Oh look ! There is the right footprint in the lib already !" (Package_SON:Texas_S-PVSON-N10_ThermalVias)
Well well well. Updated.

Didn't see it, my bad ! Should be better now !

**Comment by myfreescalewebpage** [comment]
Yes you're right ! TI has sometimes special naming.
We escape Thermal Vias in fp filter. Should be `Texas*S*PVSON*N10*`
Joel

**Comment by lukh** [comment]
Done :)

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
