### PR TITLE
Add PCA9557 I2C GPIO expander.

### PR DESCRIPTION
**Pull request by jmgao**
Add PCA9557 I2C GPIO expander.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
   - https://www.nxp.com/docs/en/data-sheet/PCA9557.pdf
- [X] An example screenshot image is very helpful
   - https://i.imgur.com/MGFdoRF.png
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.
  - This matches the existing PCA9554 symbols, which violate the rule on being centered, probably because having the symbol be centered and have the pins aligned to 100mil means there'll be a large gap at the top and/or bottom.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jmgao , thanks for contributing,

A few comments I have during my review:

PCA9557BS
- [ ] The description should ends with the complete package name : `8-bit I2C-bus and SMBus I/O port with reset, HVQFN-16`
- [ ] The footprint should be HVQFN, not QFN. You should submit it if it does not exists. Example at https://github.com/KiCad/kicad-footprints/pull/2077
- [ ] Footprint filter to be fixed according to the footprint (`HVQFN*1EP*3x3mm*P0.5mm*`)
- [ ] I/O are named "IOx", not Px, to be fixed
- [ ] Name of pin 6 is "VSS"
- [ ] RESET is Input, not Open Collector

PCA9557D
- [ ] The description should ends with the complete package name : `8-bit I2C-bus and SMBus I/O port with reset, SO-16`
- [ ] The footprint should be SO, not SOIC. We always create the exact footprint to avoid confusion later. You should submit it if it does not exists. Example at https://github.com/KiCad/kicad-footprints/pull/2077
- [ ] Footprint filter to be fixed according to the footprint
- [ ] I/O are named "IOx", not Px, to be fixed
- [ ] Name of pin 8 is "VSS"
- [ ] RESET is Input, not Open Collector

PCA9557PW
- [ ] The description should ends with the complete package name : `8-bit I2C-bus and SMBus I/O port with reset, TSSOP-16`
- [ ] I/O are named "IOx", not Px, to be fixed
- [ ] Name of pin 8 is "VSS"
- [ ] RESET is Input, not Open Collector

Cheers,
Joel

**Comment by jmgao** [comment]
Thanks for the review and sorry for the delay, I haven't had very much free time lately. I'll try to fix this PR up this weekend.

**Comment by myfreescalewebpage** [comment]
@jmgao no worries, take the time to do it.

**Comment by jmgao** [comment]
Okay, I think I've cleaned everything up. SO-16 pull requests at https://github.com/KiCad/kicad-footprints/pull/2195 and https://github.com/pointhi/kicad-footprint-generator/pull/521, HVQFN-16 ones at https://github.com/KiCad/kicad-footprints/pull/2194 and https://github.com/pointhi/kicad-footprint-generator/pull/520

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes, just need to wait the footprints now, no more comments on the symbol. Joel

**Comment by chschlue** [comment]
FPs merged.
Please fix conflicts.

**Comment by myfreescalewebpage** [comment]
@jmgao yes please fix the branch conflict here to permit the merge. Thanks, Joel

**Comment by myfreescalewebpage** [comment]
@jmgao ping

**Comment by jmgao** [comment]
Sorry, I'll take a look at this over the weekend.

**Comment by jmgao** [comment]
Rebased.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
