### PR TITLE
Isolator: add 5kV ADuM64xx series parts

### PR DESCRIPTION
**Pull request by karlp**
Copied from the 2.5kV ADuM54xx series, updated to remove the RCout pin.

Signed-off-by: Karl Palsson <karlp@tweak.net.au>

Datasheet:
https://www.analog.com/media/en/technical-documentation/data-sheets/ADuM6400_6401_6402_6403_6404.pdf

Screenshot from 2019-04-27 11-56-28
Example of 2x2 version, others are similarly based on the existing parts.

### CODE REVIEW

**Comment by karlp** [comment]
will presumably get the same review comments as https://github.com/KiCad/kicad-symbols/pull/1791

**Comment by myfreescalewebpage** [comment]
@karlp yes ! Can you fix this before we start the review here ? Thanks, Joel

**Comment by karlp** [comment]
I won't do anything to these until the other one lands, I added that comment here to try and flag that.

**Comment by karlp** [comment]
https://github.com/KiCad/kicad-symbols/pull/1791 has been updated, will update this one based on progress there

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this PR is abandoned.

**Comment by karlp** [comment]
Was only updating this one for consistency, not going to work on it by itself, compared to #1791, so yes, abandoned.

**Pull request closed without merging**
