### PR TITLE
Added two new transistor symbols

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Dual FET (N + P) in small no-lead packages

* QH8MA3 - http://rohmfs.rohm.com/en/products/databook/datasheet/discrete/transistor/mosfet/qh8ma3tcr-e.pdf
* Si5504 - https://www.vishay.com/docs/74483/si5504bdc.pdf

New footprints are here - https://github.com/KiCad/kicad-footprints/pull/832

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Only travis errors are due to the footprints not yet being merged

**Comment by evanshultz** [comment]
Can you post screenshots? Easier to review but also quicker future reference.

Footprint names:
- See https://github.com/KiCad/kicad-footprints/pull/832.

Common questions:
- For ROHM, could you beef up the description to something like `7/5.5A, +/-30V Vds, Dual N-/P-Channel MOSFET, 29/48mOhm Ron`? (And something similar for Vishay, too.)
- What about stacking the drain pins (7 and 8, 5 and 6)? Is there ever a reason not to connect together these adjacent pins of the same signal?
- Should pins 1,2,7,8 be for transistor 1 and pins 3-6 for transistor 2? For example, right now pin 1 is S1 and pin 2 is G2. Shouldn't they be S1 and G1? (The Vishay datasheet explicitly shows this.)

**Comment by evanshultz** [comment]
@SchrodingersGat 
Planning to wrap this up?

**Comment by evanshultz** [comment]
@SchrodingersGat Ping!

**Comment by SchrodingersGat** [comment]
Closing this one for now. I may have a chance to return to it later.

**Pull request closed without merging**
