### PR TITLE
Added ISO3082DW and ISO3088DW

### PR DESCRIPTION
**Pull request by jcyrax**
Added new symbol for parts ISO3082DW and ISO3088DW (alias of 3082 with only higher data rate)
Datasheet: [http://www.ti.com/lit/ds/symlink/iso3082.pdf](url)

I added to UART library as I found there other RS-485 devices.

symbol
description
description_iso3088dw
alias
footprint
options

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jcyrax** [comment]
Failed output is: "Specified footprint does not exist - Footprint file Package_SOIC:SOIC-16W_7.5x10.3mm_P1.27mm.kicad_mod was not found", but I think it is present in repository. Am I missing something?

**Comment by poeschlr** [comment]
the footprint field should not include the file ending, only the footprint name. So remove ".kicad_mod" from it.

**Comment by jcyrax** [comment]
I just saw that my commit changes pin orders for other library elements. Is that a problem?

**Comment by SchrodingersGat** [comment]
@jcyrax this is fine, some version differences in KiCad mean that the library items are saved in a different order.

**Pull request merged**
