### PR TITLE
Small update of FTDI symbols

### PR DESCRIPTION
**Pull request by jneiva08**
Have made small change to FTDI symols, the changes are:
- Replace datasheet links of webpage to pdf
- Fix S3.6
- Moved Package name to be more easy to read

The FT245BM is absolete and it is replaced by FT245BL

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jneiva08** [comment]
Have now find FT2232H/FT2232H/FT232H should add or duplicate symbol because don't have right footprint filter.
FT232BM is also obsolete it was replaced by: FT232BL

**Comment by evanshultz** [comment]
Two things to the existing commits:
1. Can you change the description of `FT4232H` to remove `FT2232Hx, `?
1. Should that symbol's packages in the description also mention `VQFN-56`?

Otherwise it looks good and thanks for taking the time to fix up this library!

From your last comment I'm not sure if you want to make other changes here or are making notes that could be addressed in a later PR. Can you please clarify?

**Comment by jneiva08** [comment]
Made footprint for FT2232H and FT4232H, in earlier commit updated footprint filter, it was incomplete

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1741

**Comment by evanshultz** [comment]
@jneiva08 
Thanks!

I made some comments on the footprint's script. Can you please address the items I wrote above?

Lastly, are there any other changes you would like to make to this PR, or is everything to be changed captured above?

**Comment by jneiva08** [comment]
@evanshultz 
Have caught another symbol without footprint, soon will create script.
Have created alias for FT232H/FT2232H/FT4232H to identify better the footprint it uses.
Hope i didn't messed with footprint filter.
In regards of  FT232H/FT2232H have VQFN-56. I wasn't planning to create the symbol.

Probably did have the most obvious changes.

**Comment by diegoherranz** [comment]
The fact that FT2232H/FT2232H/FT232H will stop existing, won't that break existing schematics?

I think this change is the right thing to do, but given that the schematic symbols are not embedded in the schematic file (yet) as opposed to the PCB layout file, we may need to leave this one until V6 when breaking changes are allowed?

Thanks!

**Comment by jneiva08** [comment]
@diegoherranz @evanshultz 
Have reverted earlier modification, when separated footprints by alias

Have open PR for missing footprint QFN-48 for FT232H, and have moved QFN-64 to other yaml file
PR QFN-48: https://github.com/KiCad/kicad-footprints/pull/1746

**Comment by evanshultz** [comment]
OK. So the scope of this PR is:
1. Update the datasheet field for FTDI ICs.
1. Add `FTDI` at the front of the description for FTDI ICs if it's missing.
1. Add a documentation entry for `FT4232H`.
1. Change pin name offset to 20mil for FTDI symbols.

Did I miss anything?

`FT2232H` needs the footprint filters changed to `QFN*1EP*9x9mm*P0.5mm*` and `LQFP*10x10mm*P0.5mm*`. Similar changes are needed for `FT232H` and `FT4232H`.

You can rename, essentially duplicating symbols, if you like to add package-specific symbols. Just don't remove symbols. Or if you just want to make the footprint filter fixes I mentioned above we're good to merge this PR.

**Comment by jneiva08** [comment]
@evanshultz 
Have pointed all modifications have made.

Have made last modifications requested.
Probably to make footprint specific FT232Hx, FT4232Hx, FT4232Hx only for v6. Right?

**Comment by jneiva08** [comment]
@evanshultz , need do more modifications?

**Comment by evanshultz** [comment]
@jneiva08 
Sorry that I've fallen behind. I don't see anything left to do.

And yes, splitting symbols by package should be done for v6.

@diegoherranz 
I looked at this now and it seems OK to me. I'm prepared to merge, but I want to check with you. Do you see anything that needs to be addressed before merging?

**Comment by diegoherranz** [comment]
I had a quick look and I don't see any issues. I think it is OK to merge.

> And yes, splitting symbols by package should be done for v6.

+1

Thanks!

**Comment by evanshultz** [comment]
Thanks all!

**Comment by jneiva08** [comment]
Thanks, Probably later create new branch to have the changes for v6

**Comment by twam** [comment]
@jneiva08 The FT2232H footprint now also mentions the QFN48 package, but I miss the EP pin. Do I miss something>

**Pull request merged**
