### PR TITLE
Audio: Add CS4272 Codec

### PR DESCRIPTION
**Pull request by dokthar**
The CS4272 is a 24-Bit, 192 kHz Stereo Audio CODEC in a TSSOP-28
package.

The datasheet is here:
https://statics.cirrus.com/pubs/proDatasheet/CS4272_F1.pdf

This codec has two mode SW or HW, alternate pin function in HW mode are in parenthesis.

cs4272

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by dokthar** [comment]
Footprint has been updated: `AGND` and `DGND` pins are now power inputs. (footprint picture does not reflect this correction).

**Comment by myfreescalewebpage** [comment]
Hi @dokthar , thanks for contributing,

A few comments I have during my review:

- [ ] Package in the description should be "TSSOP-28"
- [ ] Name of pin 1 is XTO and this pin is Output
- [ ] Name of pin 2 is XTI
- [ ] You can decrease the height of the symbol by 200mil at the top

Cheers,
Joel

**Comment by dokthar** [comment]
Thanks for your review and nice catch of the package typo in the description (took me a moment to find it).

I've shrunk the symbol height by 200mil, and center everything.
I've also renamed pin 1 and 2 as you suggested and pin 1 is not output.

Please not that pin 1 and 2 (XTO and XTI) select for a SW mode when no clock is selected...
I choose to write the pin name in HW mode between parenthesis, I am not sure if this is a good idea.

**Comment by myfreescalewebpage** [comment]
"I choose to write the pin name in HW mode between parenthesis, I am not sure if this is a good idea." 

I have notice this and think to it but finally I don't think it is a trouble. No more comment now, merging.

**Pull request merged**
