### PR TITLE
Add LMZ13608

### PR DESCRIPTION
**Pull request by ottojo**
Add LMZ13608

This adds the symbol for the LMZ13608 Power Module ([TI Product Page](http://www.ti.com/product/LMZ13608))
8A DC/DC Buck Converter, 6-36V Input

PR for footprint at https://github.com/KiCad/kicad-footprints/pull/1532.

LMZ13608

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ottojo , thanks for contributing,

A few comments I have during my review:

- [ ] Description package name should be Texas NDY0011A: `8A Adjustable Step-Down DC/DC Power Module in 15x15mm, Texas NDY0011A` is great
- [ ] Footprint can be `Package_LGA:Texas_NDY0011A` according to me and footprint filter should be `Texas*NDY0011A*`
- [ ] Name of pin 9 should be NC
- [ ] Number of pin PAD should be 12
- [ ] Symbol is too tall compared to other similar devices, proposition below

Capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes, no more comment, just need to wait for the footprint now :)

**Comment by evanshultz** [comment]
I'm reviewing the footprint. A couple thoughts:
1. Should the ground pin be named AGND? Usually we will copy the datasheet pin names and the main pin name, and the visible pin name, is AGND.
1. Is U the right ref des prefix for a module? https://github.com/KiCad/kicad-symbols/blob/master/Converter_DCDC.lib uses a mixture of U and PS. For what it's worth, IEE 315-1975 shows PS is used for "power supply" and "rectifier (complete power-supply assembly)".

**Comment by myfreescalewebpage** [comment]
@evanshultz 
1- I was wondering about the same think during the review. I have not asked the modification, "AGND" looks strange for me since this is a regulator.
2- Not bad, I have no personal preference. Maybe we need to log an issue to decide about that and parse the whole library to get it consistent with U or PS ?

**Comment by evanshultz** [comment]
1. That's what the datasheet says...
2. Agreed. Would you mind to start the issue?

**Comment by myfreescalewebpage** [comment]
1. It's also PGND depending if you consider the PGND to be the main GND pin (see block diagram page 14 of the datasheet)
2. Sure!

**Comment by myfreescalewebpage** [comment]
Issue about references at https://github.com/KiCad/kicad-symbols/issues/1727

**Comment by myfreescalewebpage** [comment]
@ottojo ok for this proposition separating the ground pins.
Waiting for the footprint before merging.
Joel

**Comment by myfreescalewebpage** [comment]
@ottojo footprint has been merged but you need to change the footprint here (footprint library has changed).
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
