### PR TITLE
Correct TI TUSB7340 footprint name

### PR DESCRIPTION
**Pull request by evanshultz**
From https://github.com/KiCad/kicad-footprints/pull/981#issuecomment-451771137. This should be merged after the footprint PR is merged.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@evanshultz agree with the changes, just need to wait for the footprint before we can merge.

Joel

**Comment by myfreescalewebpage** [comment]
@evanshultz maybe you can also separate the missing footprint from https://github.com/KiCad/kicad-footprints/pull/981 for this PR too ?
Joel

**Comment by evanshultz** [comment]
Sure can. https://github.com/KiCad/kicad-footprints/pull/1459

**Comment by myfreescalewebpage** [comment]
Merging following integration of the footprint.

**Pull request merged**
