### PR TITLE
Add Kemet Ex2 Series Mechanical Relays

### PR DESCRIPTION
**Pull request by yankee14**
This PR adds a family of DPDT relays from Kemet. They differ by package type, size, functionality, and coil voltage.

Datasheet: https://content.kemet.com/datasheets/KEM_R7002_EC2_EE2.pdf

Symbol PR: https://github.com/KiCad/kicad-symbols/pull/2631
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2230
Packages3D-source PR: https://github.com/KiCad/kicad-packages3D-source/pull/280

* 2 general package types
  * DIP --> PN beginning with `EC2`
  * SMD --> PN beginning with `EE2`
* 3 or 5 different coil voltages, these make up the symbol aliases
  * 3V, available on all variants
  * 4.5V, available on all variants
    * I don't like decimal point in part name, should replace with underscore? Or maybe `4V5`?
  * 5V, available on all variants except `NKX`
  * 12V, available on all variants
  * 24V, available on all variants except `NKX`
* 3 different functional variants, these must make up separate symbols since the symbol artwork will differ
  * Non-latch type --> No letter after coil voltage
  * Single coil latch type --> `S` after coil voltage
  * Double coil latch type --> `T` after coil voltage
* 4 different general footprints, length and width differ depending on relay lead type
  * THT for non-latch and single coil type
  * THT for double coil latch type
  * SMD for non-latch and single coil type
  * SMD for double coil latch type
* 4 different lead types, each of these types have unique footprint
  * Standard --> `NU` after latching type
  * High density footprint --> `NUH` after latching type
  * High solder retention --> `NUX` after latching type
  * High solder retention and high breakdown voltage --> `NKX` after latching type

@evanshultz I saw that you recently broke some relays into separate units. Would you prefer this PR to have broken-up relays instead of, or in addition to, what is already here?

Screencap of general non-latch type:
EC2-3NU

Screencap of general single coil latch type:
EC2-3SNU

Screencap of general double coil latch type:
EC2-3TNU

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @yankee14 I don't see any description, keywords and footprint+footprint filter in your commit. Joel

**Comment by yankee14** [comment]
@myfreescalewebpage that's right. I explained why in my OP. Are there any issues with submitting this many symbols at once? I don't want to spend another hour on this if I'm just going to have to break it into multiple PR's or delete symbols.

Thanks.

**Comment by myfreescalewebpage** [comment]
Well, the pull request is nice, but these information are mandatory. I can't accept the pull request without descriptions, keywords etc. I have just converted the pull request to draft. When it is ready (you can do it in multiple steps), you can indicate this is ready.
Joel

**Comment by yankee14** [comment]
@myfreescalewebpage I understand, thank you. I am just waiting on advice on whether to split the symbols into units, which I saw @evanshultz do recently to a few relays.

**Comment by yankee14** [comment]
260c4bc touched the omron relays for some reason. I don't think I changed anything by accident; maybe kicad moved blocks of code around?

**Comment by myfreescalewebpage** [comment]
Yes @evanshultz proposed some relays in multiple units too, but keeping the single unit version (which is the primary to be created in my opinion).

**Comment by myfreescalewebpage** [comment]
Here is my review:

EC2-3NU
- [ ] Footprint filter should be `Relay*THT*Kemet*EC2*`

EC2-3SNU
- [ ] Footprint filter should be `Relay*THT*Kemet*EC2*`

EC2-3TNU
- [ ] Footprint filter should be `Relay*THT*Kemet*EC2*Double*Coil*`

**Comment by yankee14** [comment]
@myfreescalewebpage I'm not sure whether KLC S5.2 about replacing '-' with '*' applies in this case. The dash isn't really being used as a delimiter or anything. For example, "Double-Coil" would never vary as "Double-Foo" or "Double-Bar".

**Comment by myfreescalewebpage** [comment]
Travis reports the following:

Capture

So, I'm not in the details of the KLC but it seems it should be replaced :)
Will se what the footprint experts will say about the name of the footprint (DoubleCoil or Double-Coil). I have no preference and I don't found other symbol with this. Then you can change the footprint and footprint filter here accordingly.

Joel

**Comment by chschlue** [comment]
The point of S5.2 isn't replacing non-delimiting dashes with asterisks or question marks, the script just can't tell the difference.
Switching perpsective, I'd suggest using `DoubleCoil` _because_ it's a single logical / semantic unit here and shouldn't get a delimiter in the middle ;)

**Comment by yankee14** [comment]
@chschlue and @myfreescalewebpage thank you for your help in clarifying! I will fix it later today

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now before merging.

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
