### PR TITLE
add TPS22917 power switch from TI

### PR DESCRIPTION
**Pull request by penoud**
add TPS22917 power switch from TI
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
http://www.ti.com/lit/ds/symlink/tps22917.pdf
- [X] An example screenshot image is very helpful
image
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @penoud , thanks for contributing,

A few comments I have during my review:

- [ ] IN should be named VIN according to the datasheet
- [ ] QCD should be named QOD according to the datasheet
- [ ] keywords are redundant with the description, maybe you can write "high-side power distribution switch" for consistency with the TPS22929D
- [ ] Pins are very closed together, particularly GND, isn't it possible to enlarge the symbol a little bit ? You can solve KLC error S3.1 at teh same time (see travis result)
- [ ] You have modified a lot of devices (see git diff and also travis results, I do not understand why ?

Cheers,
Joel

**Comment by poeschlr** [comment]
You did not modify other files. But you modified other symbols (In fact it looks like you deleted some of them)
The following symbols would be deleted with your pull request.
- BTS40K2-1EJC
- BTS50055-1TMA
- BTS50080-1TEA
- BTS724G
- CAP002DG
- IPS6011PBF
- IPS6011RPBF
- IPS6011SPBF
- LT1641-1
- LTC4364CDE
- LTC4364CMS
- LTC4364CS
- LTC4365DDB
- LTC4365TS8
- LTC4417CGN
- LTC4417CUF
- NPC45560-H
- STM6600
- TSM102
- TSM103W

My guess is you worked on an old copy of the lib and copied the file into this branch instead of properly working directly inside of your local git repo. (This is the only way how this can happen without leaving a trace in the git history.)

**Comment by myfreescalewebpage** [comment]
Agreed with @poeschlr it is not possible to merge the PR now @penoud you should fix the modifications proposed. Please look at the git diff, you should see only your modifications, not so much differences.

- [ ] Just seen also you have not the footprint at the end of the description, KLC S6.3. Please add `, SOT23-6` at the end of the description so description can be `1V to 5.5-V, 2-A, 80-mΩ Ultra-Low Leakage Load Switch, SOT23-6`
- [ ] Keywords not corrected
- [ ] Footprint filter should not contains the pad count (KLC S5.2), please modify to `SOT?23*`
- [ ] Datasheet link in the lib is not correct, you point to the wrong device, please modify to `http://www.ti.com/lit/ds/symlink/tps22917.pdf`
- [ ] QOD type is not Power Output, it should be Open Collector.

Joel

**Comment by myfreescalewebpage** [comment]
Hi @penoud are you still alive on this subject ? Thanks.

**Comment by penoud** [comment]
Yes, I will correct this soon.

**Comment by penoud** [comment]
@poeschlr Yes you're right I worked on a fork and struggle to update it from the official repo. I fork official repo in my github account. From my PC I fetch update from the official repo and then I push changes to my fork. But when i work for a long time on a component ad I struggle to update the branch. Any tips?

@myfreescalewebpage I tried to apply all your request but I strugle for the keywords, could you precise your request? Thanks in advance

**Comment by myfreescalewebpage** [comment]
> I tried to apply all your request but I strugle for the keywords, could you precise your request? Thanks in advance

This is about keywords in the first review comment I have made: https://github.com/KiCad/kicad-symbols/pull/1166#issuecomment-446217070

**Comment by myfreescalewebpage** [comment]
You need to update your branch with the remote modifications, that's usual because we are making many additions to the symbols libraries and often create conflicts or such kind of trouble.

**Comment by myfreescalewebpage** [comment]
@penoud here is a comment of @poeschlr in another PR that will be a good memorandum: https://github.com/KiCad/kicad-symbols/pull/145#issuecomment-356436694

**Comment by myfreescalewebpage** [comment]
@penoud sorry for being late to review following the mast commit, the merge issue is solved. Here are the following comment which remain on this PR:

- [ ] Can you remove the extra "-" between values and units in the description:  `1V to 5.5V, 2A, 80-mΩ Ultra-Low Leakage Load Switch, SOT23-6`
- [ ] Keywords not corrected, should be "high-side power distribution switch" for consistency with the TPS22929D
- [ ] QOD type is not Power Output, it should be Open Collector.

Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
Just also notice the part should be called `TPS22917DBV` to avoid conflict if the manufacturer add future packages options. Then OK to merge !
Cheers,
Joel

**Comment by penoud** [comment]
Done and agree need to be futur proof. I start to feel that I will ask my manager if I could quit Altium and use kicad at work to. So more efficient

**Comment by myfreescalewebpage** [comment]
Thanks! Merging.

**Pull request merged**
