### PR TITLE
Added AK7452 magnetic sensor IC

### PR DESCRIPTION
**Pull request by SchrodingersGat**
image

https://www.akm.com/akm/en/file/datasheet/AK7452.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Also added MA730 sensor - https://www.monolithicpower.com/pub/media/document/m/a/ma730_r1.01.pdf

**Comment by SchrodingersGat** [comment]
Also fixed some KLC issues across the Sensor_Magnetic library.

**Comment by evanshultz** [comment]
Requested changes for both:
- MOSI and MISO types are flipped (this is a slave device)
- The SPI chip select pin is active-low
- Please use 100mil pin lengths and then place NC pins on the symbol outline
- One the above is done, can the symbol shrink just a bit?
- Add package to end of the description

**Comment by evanshultz** [comment]
Thanks! I don't see the changes made to MA730, though, only the AKM part. Also, can you please post screenshots of any symbols you changed for easy reference?

Once this is done we can make an issue to capture the outstanding fixes in this library.

**Comment by SchrodingersGat** [comment]
image

image

image

image

image

image

**Comment by evanshultz** [comment]
Thanks! I still don't see fixes applied that I requested above for MA730. No package type in the description, etc. Can you fix that?

**Comment by SchrodingersGat** [comment]
Sorry, missed that one. Updated now:

image

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
