### PR TITLE
Add Adafruit Feather Bluefruit LE module

### PR DESCRIPTION
**Pull request by fauxpark**
A microcontroller development board with a BLE module. Uses Arduino pin naming for the most part, `SCK`/`MOSI`/`MISO` are connected between the MCU and the BLE module, but also broken out. `EN` is the enable input for the LDO, pulled to either VBAT or VBUS.

image

"Datasheet": https://learn.adafruit.com/adafruit-feather-32u4-bluefruit-le/downloads
Footprint and pinout is the same for both ATmega and ATSAMD flavours.

Footprint: ~~https://github.com/KiCad/kicad-footprints/pull/2074~~
https://github.com/KiCad/kicad-footprints/pull/1657

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@fauxpark thanks for this symbol.
The position of the pin is strange and the name can be enhanced.
Have a look to Arduino_UNO_R2 for example in the lib.
Will do a full review after that.
Joel

**Comment by fauxpark** [comment]
Okay, I've rearranged the pins to be more like the Leonardo (as that also uses an ATmega32U4) and updated the image in OP. Not sure what you mean about the name though. It seems fine to me.

**Comment by myfreescalewebpage** [comment]
Was speaking of pin name, seems it's better. Full review:

- [ ] Datasheet links "https://cdn-learn.adafruit.com/downloads/pdf/adafruit-feather-32u4-bluefruit-le.pdf" and "https://cdn-learn.adafruit.com/downloads/pdf/adafruit-feather-m0-bluefruit-le.pdf" will be better

Else no comment, thanks for the fixes.
Joel

**Comment by fauxpark** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Footprint at https://github.com/KiCad/kicad-footprints/pull/1657

**Comment by matthijskooijman** [comment]
Great, with your and my changes to #1933, our symbols are nearly compatible. Still some suggestions about your symbol, though:
 - You've replaced the footprint with my version, but I used different pin numbering, so you'll have to update your symbol pin numbers to match (unless you think your numbering is somehow better, but it seems pretty arbitrary).
 - You still have the M0 bluefruit as an alias, but the logical pin numbers (Dxx) in the pin names are no longer correct for the SPI pins for that board. I think this needs a duplicate symbol with modified pin names.
 - You used the name `Adafruit_Feather_BluefruitLE_32U4`, but adafruit calls their board "Adafruit Feather 32u4 Bluefruit LE" (and they seem to consistently use this ordering for all their feather boards). Maybe the symbol should be `Adafruit_Feather_32u4_Bluefruit_LE` instead?

**Comment by fauxpark** [comment]
I do think my numbering is better - it's more consistent with eg. DIP packages, with the USB connector doubling as a pin 1 marker of sorts.

> You still have the M0 bluefruit as an alias, but the logical pin numbers (Dxx) in the pin names are no longer correct for the SPI pins for that board. I think this needs a duplicate symbol with modified pin names.

Yep, I'll fix that up.

> You used the name Adafruit_Feather_BluefruitLE_32U4, but adafruit calls their board "Adafruit Feather 32u4 Bluefruit LE"

Done. How's this?

image
image

**Comment by matthijskooijman** [comment]
> Done. How's this?

Looks good!

> I do think my numbering is better - it's more consistent with eg. DIP packages, with the USB connector doubling as a pin 1 marker of sorts.

Yeah, I guess that makes sense. I've updated my footprint and symbol to match.

**Comment by matthijskooijman** [comment]
@fauxpark, I've taken the liberty of including your symbols in my Feather PR, since I was adding a bunch more feathers. Probably easiest to just merge them all in one go once we figure out the remaining open issues.

**Comment by fauxpark** [comment]
@matthijskooijman thanks! This can be closed then?

**Comment by matthijskooijman** [comment]
> @matthijskooijman thanks! This can be closed then?

Yeah, think so.

**Pull request closed without merging**
