### PR TITLE
Adding PCB Edge PCI Express connectors

### PR DESCRIPTION
**Pull request by ki5libs**
Adding PCB Edge PCI Express connectors:
x1
x1
x4
x4
x8
x8
x16
x16

[Datasheet - PCIe Standard](http://www.ritrontek.com/uploadfile/2016/1026/20161026105231124.pdf#page=63)
[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/1938)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

For all symbols:
- [ ] Pins length should be 150mil
- [ ] I'm not sure the text "PCIe xxx" in the symbol is really required, we usually don't do that, you can remove it
- [ ] RSVD should not be stacked at all, they can be used separately
- [ ] If my understanding is correct, the PRSNT2 pins should not be stacked, only the two opposite PRSNT pins need to be connected together, isn't it ?
- [ ] Settings the pin type as done for "BUS_PCI_Express_Mini" (ie from card point of view) is great to have, you should add them

The compatibility of the pins between the 4 variants is nice to have 👍 

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@ki5libs please ping me when you think it's ready for next step of the review. Thanks

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

sorry for that, but looks I've broken this PR. I've finished changes and just made `git rebase` for resolving a conflict. I don't know why but it shows 222 changed files with 801 commits here.

I decide to make another one [PR](https://github.com/KiCad/kicad-symbols/pull/2981) based on the same branch. And it seems good (2 changed files with 13 commits), but as I realized it can not be opened cause of migration.

Actually I'm very upset and don't know what to do...

**Comment by chschlue** [comment]
Reopened #2981

**Pull request closed without merging**
