### PR TITLE
Memory_Flash: Add SST25VF080B device from Microchip

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://ww1.microchip.com/downloads/en/DeviceDoc/20005045C.pdf

Screenshot from 2019-05-16 12-40-46

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1601
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Footprint merged

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A few comments I have during my review:

- [ ] Description can be `8-Mbit, 2.7 to 3.6V, SPI Flash Memory, SOIC-8`
- [ ] Keywords `flash memory spi` can be great, I do not support the 2.7V in your proposition because the device does not operate only at 2.7V
- [ ] Pin length should be 100mil (symbol < 100pins) and size of the device can be reduced even if I understand you copied from another symbol.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Done

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco thanks for the fixes, I think the design is great and will re reused for the next similar symbols.
Merging.
Joel

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
