### PR TITLE
DSP_Microchip_DSPIC33: Add DSPIC33FJ64MC802-ISP

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/70291G.pdf

imagen

imagen

imagen

imagen

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- Wildcard temp by changing symbol name to `DSPIC33FJ64MC802-xSP`
- Add package type (`DIP-28`) to the end of the description.
- Set pin name offset to 20mil.
- Provide a default footprint.
- Would it make more sense for the RB pins to increment top to bottom? Or you did this so the symbol can be a little thinner?
- Pin 17: 4th field has a double `8`
- Pin 21: 6th function has an extraneous `W`
- Pin 25: 5th function has the `W` and `M` swapped
- Stack VSS pins.

**Comment by antoniovazquezblanco** [comment]
I will get back to this as soon as I find some time. Thank you

**Comment by antoniovazquezblanco** [comment]
I think travis checks are a bit optimistic. Although I was violating a rule, the check passed, see: https://travis-ci.org/KiCad/kicad-symbols/builds/389173224?utm_source=github_status&utm_medium=notification

**Comment by poeschlr** [comment]
Travis can not check everything. Some rules need manual checking by us maintainers.

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
Thanks! Can you post a new screenshot?

**Comment by antoniovazquezblanco** [comment]
imagen

**Comment by evanshultz** [comment]
Until we go with shorter pin names, this is probably as good as we're going to get.

Sorry that I forgot to get back to this and merge it. Thank you!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
