### PR TITLE
Add SMLVN6RGB

### PR DESCRIPTION
**Pull request by asukiaaa**
I add an symbol of full color led.

Datasheet: https://www.rohm.com/datasheet/SMLVN6RGB1U

screenshot from 2018-09-24 22-19-49

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- The description could be enhanced with something like `High Brightness Tri-Color LED, RGB, 3.5x2.8mm`.
- Set the pin name offset to 20mil.
- All pin types should be Passive for diodes.
- Instead of pin names, it might be more salient to name all pins `~` and show the 3 diode symbols with one letter for their color. Here are two examples from our current lib (filled symbols should be hollow, though):
image

Apologies for popping in, Dan.

**Comment by DanSGiesbrecht** [comment]
@evanshultz beat me to it! Haha that's ok. The more input the merrier.

I was going to bring up - what's the benefit of having this symbol in the LED library, rather than Devices? It seems to me that the symbol would be better served as a generic, rather than atomic symbol.

**Comment by evanshultz** [comment]
Device.lib is for simple parts which don't have a manufacturer attached. It functions as a reference from which symbols can be copied and adapted into other libraries when a manufacturer-specific component is created. These generic parts also could apply to many footprints or physical parts, whereas other libraries can have a specific footprint attached that matches a tangible component.

LED.lib is therefore correct for this part.

If there is a missing symbol permutation in Device then it can be added, but it should be done in a separate PR to avoid cluttering things up.

LED direction isn't controlled, as far as I know. The anode is normally the "input", I suppose, but that's not an argument. To me it makes sense to have diodes point to the right. But for whatever reason KiCad's generic diodes have pointed left with cathode as pin 1 since before I started helping out.

**Comment by DanSGiesbrecht** [comment]
@evanshultz That clears up my confusion a lot. I thought that the generic LED symbols were to be used whenever possible. It sounds like the primary path for LED addition should always be atomic.

**Comment by asukiaaa** [comment]
Thanks for the information.
I updated this symbol by copying LED_RGB.
screenshot from 2018-09-27 22-17-47

**Comment by evanshultz** [comment]
Nice.
- Pins 1 to 3 are B, R, G in this ROHM part. Please update the text on this symbol.
- Remove the period from the end of the description.
- Footprint filter should be `LED*ROHM*SMLVN6*` or `LED*SMLVN6*`.

**Comment by evanshultz** [comment]
@DanSGiesbrecht 
Please review. That's all I see so if you're good you can merge if you like.

**Comment by asukiaaa** [comment]
Thanks for reviewing.
I update the symbol.

**Comment by DanSGiesbrecht** [comment]
Looks good! Thank you for your contribution. :)

**Comment by asukiaaa** [comment]
Thanks for checking and merging.

**Pull request merged**
