### PR TITLE
Added symbol for Vl53l1x ToF distance sensor

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.st.com/resource/en/datasheet/vl53l1x.pdf
Footprint depends on:
  https://github.com/KiCad/kicad-footprints/pull/1995

imagen

imagen

### CODE REVIEW

**Comment by cnieves1** [comment]
Regarding S4.3: all stacked pins are GND, and there are already symbols with GND stacked pins in the library...

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by cnieves1** [comment]
Done:
Captura de pantalla de 2020-04-03 08-20-48

**Comment by myfreescalewebpage** [comment]
Thanks. Pin stacking is not respected for GND: first pin should be Power Input visible, the two other should be Passive Invisible (see travis error output). Then ready to merge. Joel

**Comment by cnieves1** [comment]
Done. Please review!

**Comment by myfreescalewebpage** [comment]
It's OK now. Merging.

**Comment by myfreescalewebpage** [comment]
The symbol is OK now.
Just notice you also need to modify the "sym-lib-table" file because it's a new library.
Joel

**Comment by myfreescalewebpage** [comment]
@cnieves1 ping, please check my last comment, need to make a modification on sym-lib-table

**Comment by cnieves1** [comment]
Hi Joel,
Sorry! I missed that one!
It should be fixed now.

Thanks,

**Comment by myfreescalewebpage** [comment]
Thanks for this last update, now merging your pull request :)

**Pull request merged**
