### PR TITLE
add Mini-Circuits LRPS-2-1 power splitter/combiner

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/LRPS-2-1.pdf

lrps-2-1

Footprint: https://github.com/KiCad/kicad-footprints/pull/1135

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] We usually put reference in top left corner and name in top right corner - Actually you have reference at a strange position which not very convenient...
- [ ] The footprint is not correct, you should update it (but footprint filter don't need modification)
- [ ] You should add NC pins 2 and 5 (Type Not Connected, not visible) because the pin count is not specified in the footprint (KLC S4.5 http://kicad-pcb.org/libraries/klc/S4.5/)
- [ ] You can center GND pins, but maybe you want consistency with other MiniCircuit symbols ?
- [ ] Type of pin 6 is Output (in my understanding of the device)

Cheers,
Joel

**Comment by aewallin** [comment]
centered GND-pins would just obscure readability of symbol and port-pin IMO.
after revision:
lrps-2-1

**Comment by myfreescalewebpage** [comment]
@aewallin, missing the impedance and you are violating S4.1 with the NC pins.

Joel

**Comment by aewallin** [comment]
same question as elsewhere: if hidden NC-pins should be on the box-boundary, do I have to change the box to be on 100mil grid?

**Comment by myfreescalewebpage** [comment]
Right, but this will violate S4.6 which absolutely requires that the NC pins must terminates on the outline box of the symbol. So I prefer violating S4.1 and keep your symbol like that.

No other comment, merging.

Joel

**Pull request merged**
