### PR TITLE
Add X02xxxN

### PR DESCRIPTION
**Pull request by twam**
Screenshot:
image

Datasheet:
https://www.st.com/resource/en/datasheet/x02.pdf
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @twam thanks for this symbol

You have strange modification with "copy", please look at the git diff: https://github.com/KiCad/kicad-symbols/pull/2483/files
For the symbol X02xxxN you should create one with the real name and then make some aliases. Put the right current/voltage for each aliases in the descriptions.

Will do a review after.

Joel

**Comment by myfreescalewebpage** [comment]
@twam ping

**Comment by twam** [comment]
There you go :)

**Comment by myfreescalewebpage** [comment]
Hello @twam 
Thanks for the update.
For the symbol X02xxxN you should create one with the real name and then make some aliases. Put the right current/voltage for each aliases in the descriptions.
Joel

**Comment by twam** [comment]
That's what I did, or? Don't get it.

**Comment by myfreescalewebpage** [comment]
Oups sorry, probably I didn't checked the right commit.
Have made a full review just now, no comment to do, merging.
Thanks

**Pull request merged**
