### PR TITLE
Adding PIC16F18324-xSL

### PR DESCRIPTION
**Pull request by persus**
Adding symbol for PIC16F18324-xSL.

(Now with just the symbol based on the upstream-master. Sorry for any inconvenience with creating pull-requests with mixed symbols.)

- Violation of S3.1: Moving whole symbol to match exact center is not possible. The pins would not be in a 100mils grid anymore (like with PIC16F18325-I/SL).
- Violation of S3.6: I made a copy of PIC16F18325-I/SL in the beginning and modified it to the PIC16F18324-xSL. I am not aware of any changes in the offset of pin-name.

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
- [ ] Please fix S3.6 violation. An existing broken symbol is no excuse for adding a new broken symbol.
- [ ] Actually add a link to the datasheet when you check that template item.
- [ ] Limit pin names to at most two functions.

**Comment by persus** [comment]
[X] Actually add a link to the datasheet when you check that template item.
I thought the URL to the datasheet in the symbol would suffice. I didn't know I have to link the datasheet in the comments, too. Sorry. Here it is. :)
http://ww1.microchip.com/downloads/en/devicedoc/40001800c.pdf
image

[X] Please fix S3.6 violation. An existing broken symbol is no excuse for adding a new broken symbol.
Done.

[X] Limit pin names to at most two functions.
Done. Sorry, I am new to this stuff.

**Comment by persus** [comment]
image

**Comment by chschlue** [comment]
Please check (or leave out) alternate pin functions.
ADCs are called ANA and ANC and TX has no default pin, for example.

**Comment by persus** [comment]
image

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
