### PR TITLE
add IFX27001 linear voltage regulators

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the [IFX27001](https://static6.arrow.com/aropdfconversion/dc75757ae45a88e5f69bdce3f2a651a5fe0ca07d/ifx27001_ds_10.pdf) linear voltage regulators (fixed and adjustable). I couldn't find any link to the datasheet on the manufacturers page, so I've used the one from Arrow instead.

Screenshot_20190731_154652

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

IFX27001TFV:
- [ ] The format of the description is not the last one we use, can you set description to `1A Low Dropout regulator, positive, adjustable output, TO-252`
- [ ] Footprint filter should be `TO?252*`

IFX27001TFVxx:
- [ ] The format of the description is not the last one we use, can you set description to `1A Low Dropout regulator, positive, 5.0V fixed output, TO-252` (adapt voltage to the regulator)
- [ ] Footprint filter should be `TO?252*`

Else no comment on the symbol itself.

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage,

thanks for the review, I integrated your feedback.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by evanshultz** [comment]
FYI, I pinged Infineon and they will work to fix the website so the datasheet is there.

**Pull request merged**
