### PR TITLE
Add MCP23008 i2c IO expander

### PR DESCRIPTION
**Pull request by nivekg**
Hey people,

Here's a symbol for the MCP23008 i2c IO expander. Since they come in three different packages, I made three symbols with the package name abbreviations added to the end of the symbol name. 
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/MCP23008-MCP23S08-Data-Sheet-20001919F.pdf

The screenshot of the symbols are attached.

MCP23008_P:
mcp23008_p

MCP23008_SO:
mcp23008_so

MCP23008_SS:
mcp23008_ss

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
- [ ] Rename to MCP23008-x{P,SO,SS}
- [ ] Fix SSOP pinout
- [ ] Move ~RESET to top left
- [ ] Change INT to output

**Comment by nivekg** [comment]
I applied the fixes based on your comments. The MCP23008 only comes in the extended temperature package so I set the names of the chip as: MCP23008-EP, MCP23008-ESO, MCP23008-ESS and MCP23008-EML. I also missed out the QFN-20 package so added it in. 
Screenshots below.

MCP23008-EP:
mcp23008-ep

MCP23008-ESO:
mcp23008-eso

MCP23008-ESS:
mcp23008-ess

MCP23008-EML:
mcp23008-EML

**Comment by chschlue** [comment]
Please wildcard temp range anyway, we cannot know Microchip will never release other variants.

**Comment by nivekg** [comment]
ok, the symbols names are now: MCP23008-xP, MCP23008-xSO, MCP23008-xML and MCP23008-xSS

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
