### PR TITLE
Add FDS6930B

### PR DESCRIPTION
**Pull request by mike7b4**
Add FDS6930B Dual MOSFET
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by mike7b4** [comment]
[
screenshot_20180329_152951
](url)

**Comment by evanshultz** [comment]
@mike7b4 
I see this was your first contribution to KiCad. Thanks for being willing to add to the library!

While this PR was closed, this part does not exist in the library now and would be welcome. You could add it as an ALIAS to `IRF7309IPBF`. If you would like to reopen this PR and fix it or have other questions please comment.

**Comment by Ratfink** [comment]
@evanshultz This was resubmitted slightly differently as #433, so I guess there's no need to reopen this PR.

**Comment by mike7b4** [comment]
Thank for the responses. I will take a look at alias.

**Pull request closed without merging**
