### PR TITLE
Added AX−SIP−SFEU and AX−SIP−SFEU-API

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.onsemi.com/pub/Collateral/AX-SIP-SFEU-D.PDF
Footprint: https://github.com/KiCad/kicad-footprints/pull/2186

Captura de pantalla de 2020-03-31 13-25-21
Captura de pantalla de 2020-03-31 13-25-58

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Matching between SIP and uC pins are provided in a PDF included in the SDK, and can not be linked here. For reference:
Captura de pantalla de 2020-03-31 15-00-11

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] The two devices should not be alias, they differ on pins 22 to 24.
- [ ] Footprint filter should be `OnSemi*SIP*6EP*9x7mm*P0.65mm*`
- [ ] Word spelling error at "propietary" in the description
- [ ] You should group UARTTX and UARTRX pins
- [ ] Name of pin 27 is VDD_IO
- [ ] I suggest to keep only the primary function of GPIO pins. This will permit to reduce the width of the symbol a lot
- [ ] You should group DBG pins
- [ ] I suggest to have all GPIO on the same side, and the other pins on the other side

Cheers,
Joel

**Comment by cnieves1** [comment]
Hi Joel,
If you don't mind, I'd like to keep Pxx in symbol names. This SIP has a MCU die and a RF transceiver die in the same package. GPIOx naming shown in the datasheet is related to SIP package, while Pxx is related to MCU die, and the matching between them is somehow hidden. 
Keeping both will make life easier, knowing which MCU Pxx each pin is at first glance.

Captura de pantalla de 2020-04-27 11-11-19
Captura de pantalla de 2020-04-27 11-11-29

**Comment by myfreescalewebpage** [comment]
Great job! Ok for GPIO pin name, this is nice like that.

- [ ] For DBG_EN the type should be Input

Else just need to wait the footprint

Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint.

**Comment by myfreescalewebpage** [comment]
@cnieves1 can you solve the branch conflict here please?

**Comment by cnieves1** [comment]
@myfreescalewebpage I think it is done. Please review. Thanks

**Comment by myfreescalewebpage** [comment]
@cnieves1 you need to update the footprint name (EP size changed). (travis error)

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
