### PR TITLE
Add DS1882 audio log volume digital potentiometer with i2c.

### PR DESCRIPTION
**Pull request by hubijoo**
*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @hubijoo thanks for this symbol,
You have plenty of errors to solve before we start the review, please check the travis results.
Joel

**Comment by myfreescalewebpage** [comment]
Thanks. Few comments during my review:

- [ ] Name of the symbol should be "DS1882E"
- [ ] Description can be enhanced and should be terminated by the package name: `Dual Log Audio Digital Potentiometer, 64 positions, TSSOP-16`
- [ ] Footprint filter should be `TSSOP*4.4x5mm*P0.65mm*`
- [ ] Pin length for this device should be 100mil
- [ ] Style of pin 12 should be line
- [ ] Name of pin 12 should be `~CE`
- [ ] Hx, Wx and Lx pins should be Passive

Joel

**Comment by hubijoo** [comment]
> Thanks. Few comments during my review:
> 
>     * [ ]  Name of the symbol should be "DS1882E"
> 
>     * [ ]  Description can be enhanced and should be terminated by the package name: `Dual Log Audio Digital Potentiometer, 64 positions, TSSOP-16`
> 
>     * [ ]  Footprint filter should be `TSSOP*4.4x5mm*P0.65mm*`
> 
>     * [ ]  Pin length for this device should be 100mil
> 
>     * [ ]  Style of pin 12 should be line
> 
>     * [ ]  Name of pin 12 should be `~CE`
> 
>     * [ ]  Hx, Wx and Lx pins should be Passive
> 
> 
> Joel

Hello Joel,

Thank you for your review and help. I have corrected this points.

Jonathan

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes, no more comment, merging.

**Pull request merged**
