### PR TITLE
SAW filter in Filter library

### PR DESCRIPTION
**Pull request by calebns**
SAW filters. I couldn't find a place for them so created a new library. Let me know if that's not a good approach so I'll move it somewhere else.

https://www.mouser.com/ds/2/842/B8813-1092540.pdf
https://www.mouser.com/ds/2/40/AVX_140127%20Connectivity-1158389.pdf

image

Footprints:
https://github.com/KiCad/kicad-footprints/pull/381

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
- This looks mostly fine to me ... is there a standard symbol for SAW-filters? I didn't any, so I figure going with the symbol proposed by TDK is fine for me ...
- I will comment on the footprint naming over on the footprint-PR
- new library is fine for me.

**Comment by jkriege2** [comment]
@poeschlr @evanshultz Ideas on the symbol?

These are notch filters (filter out one small frequency range), right?

I got one IEC-symbol table that proposes this for SAW notch filter:
2018-02-17 16_34_49-iec-60617 pdf - adobe acrobat reader dc
 And for "normal" band-pass and  notch filters:
2018-02-17 16_35_00-iec-60617 pdf - adobe acrobat reader dc

Should we use these fo such filters or the one proposed above?

**Comment by Misca1234** [comment]
I guess the datasheet link to the SF14-1575F5 should be 
https://global.kyocera.com/prdct/electro/product/pdf/sf14_gnss.pdf

And there is two variants of the 
SF14-1575F5UUA1
SF14-1575F5UUC1

**Comment by jkriege2** [comment]
Just saw, they are band-pass filters ... Then the IEC symbol would be the same as for a SAW resonator: 
2018-02-17 16_50_00-iec-60617 pdf - adobe acrobat reader dc

**Comment by evanshultz** [comment]
This symbol is OK with me. It's too bad that the bandreject filter symbol isn't a bandpass upside-down. :( The caret-like image is much more clear than a single cycle of a sine wave with a line through it.

**Comment by calebns** [comment]
image

**Comment by jkriege2** [comment]
Looks good mostly. I would only suggest to edit the descriptions abit. Instead of naing the package like `Filter_1109-5, 1.1x0.9mm`, mybe put it a bit simpler `SMD 1109` and `SMD 1411`

**Comment by jkriege2** [comment]
Great work!

Thanks,
JAN

**Pull request merged**
