### PR TITLE
Fix Memory_UniqueID

### PR DESCRIPTION
**Pull request by jneiva08**
Made a refresh on the library.
Datasheet: https://pdfserv.maximintegrated.com/en/ds/DS2401.pdf

On DS2401P:
- Right footprint - https://github.com/KiCad/kicad-footprints/pull/1248
- Added NC pins
ds2401p

DS2401Z
- Changed pins number to be in the same position of SOT-223
- Added NC pin
ds2401z

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Created an issue for the missing footprint after the fix. I will review this but I need some time!

**Comment by antoniovazquezblanco** [comment]
footprint merged, re-triggering travis

**Comment by antoniovazquezblanco** [comment]
Thank you!

Fixes https://github.com/KiCad/kicad-symbols/issues/962

**Comment by jneiva08** [comment]
Thanks

**Comment by antoniovazquezblanco** [comment]
To you!

**Pull request merged**
