### PR TITLE
Fix MAX453 according to KLC

### PR DESCRIPTION
**Pull request by jcyrax**
Fixed symbol of MAX453 to KLC. This device is obsolete so maybe it even shouldn't be added to library.
But if you do, hope this will be better.

Test fails on S4.4, but this is because op amp output type is marked as output and not power output. Pin name is VOUT (as in datasheet). I decided to leave it output.

Datasheet: [https://datasheets.maximintegrated.com/en/ds/MAX452-MAX455.pdf](url)
symbol
descr
filter
prop

Alias is empty.
No associated footprint - comes in DIP and SOIC

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Looks good, thanks for that contribution. Could you please change a few minor issues, before I can merge:
1. please add the packages (`, DIP-8/SOIC-8`) to the description, separated with a comma
2. The FPFilters should also include the dimensional information, i.e. `DIP*W7.62mm*` and `SOIC*3.9x4.9mm*Pitch1.27mm*`

Thanks ... 
JAN

**Comment by jcyrax** [comment]
Regarding 2. there is a problem that, datasheet has no exact description of package sizes. Only DIP and SOIC. Thats why I left it without sizes.

**Comment by jkriege2** [comment]
The sizes I gave above are for the standard footprints, which usually fit the SOIC-8 and DIP-8 packages as they are pretty standardized. Also we use these for most (if not all) other Maxim ICs in DIP8/SOIC8

best,
JAN

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
