### PR TITLE
Add MUN12AD01-SH and MUN12AD03-SH Switching DC/DC regulator symbol

### PR DESCRIPTION
**Pull request by rleh**
* **MUN12AD01-SH** Switching DC/DC regulator
  * Datasheet: http://www.cyntec.com/upfile/products/download/Cyntec%20MUN12AD01-SH_Datasheet.pdf
* **MUN12AD03-SH** Switching DC/DC regulator
  * Datasheet: http://www.cyntec.com/upfile/products/download/Cyntec%20MUN12AD03-SH_Datasheet.pdf

Footprint PR: KiCad/kicad-footprints#2100

---

### MUN12AD01-SH
MUN12AD01-SH
MUN12AD01-SH

---

### MUN12AD03-SH
MUN12AD03-SH
MUN12AD03-SH

### CODE REVIEW

**Comment by rleh** [comment]
The footprint (KiCad/kicad-footprints#2100) has been merged, I have updated the symbol because of the changed footprint name.

**Comment by myfreescalewebpage** [comment]
Hi @rleh , thanks for contributing,

A few comments I have during my review:

For both devices:
- [ ] Pin length should be 100mil (symbol < 100pins)
- [ ] For regulators we have VIN on the left in front of VOUT
- [ ] NC pin should be moved on the border outline of the symbol
- [ ] The switching regulator symbol are usualy less large. Check AAT1217ICA-1.2 dimensions for example

Cheers,
Joel

**Comment by rleh** [comment]
@myfreescalewebpage Thank you for reviewing!
I addressed all your comments, pins length is 100mil, VIN is on the left and the size is equal to the _AAT1217ICA-*_ symbols.

grafik
grafik

Ready to merge from my side!

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes. I agree this is ready, no more comment. Merging.

**Comment by rleh** [comment]
Thank you very much!

**Pull request merged**
