### PR TITLE
Add PSoC 4200M series (64-TQFP package)

### PR DESCRIPTION
**Pull request by dogtopus**
Datasheet: https://www.cypress.com/file/139956/download

Symbol for PSoC 4200M series microcontroller manufactured by Cypress. Only the 64-TQFP (0.5mm and 0.8mm pitch) packaged variant is included.

CY8C4247AZI-M485

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @dogtopus thanks for this contribution. You should create one symbol per footprint and set the footprint in the right field. Then will be able to review. Thanks Joel

**Comment by dogtopus** [comment]
@myfreescalewebpage even if they are fully pin-to-pin compatible?

**Comment by myfreescalewebpage** [comment]
Yes, we create one symbol per package even if it is the same pinout. This permit to fully specify the exact footprint in the library to prevent errors.

**Comment by myfreescalewebpage** [comment]
@dogtopus any news here ?

**Comment by dogtopus** [comment]
@myfreescalewebpage Sorry completely forgot about this. Now it's done.

**Comment by myfreescalewebpage** [comment]
Thanks. However, still not one symbol per package :)

**Comment by dogtopus** [comment]
@myfreescalewebpage Should I specify the exact # of pins for the footprint as well or leaving it as a wildcard is enough

**Comment by myfreescalewebpage** [comment]
No you are not correct.
Look at STM32 or other manufacturer of MCUs for example.
One symbol for each footprint variant.
The exact footprint should be indicated in the properties of the symbol too.
Joel

**Comment by dogtopus** [comment]
@myfreescalewebpage Then I think it's done. Please review.

**Comment by myfreescalewebpage** [comment]
Will do. By the way, I don't see the footprint in the symbol properties. Can you add them ? Screenshot below.

Capture

Joel

**Comment by dogtopus** [comment]
Done.

**Comment by myfreescalewebpage** [comment]
Thanks, here is finaly the complete review for this PR:

CY8C4245AXI-M445
- [ ] The description should ends with  the package name with the following format: `PSoC 4200M series, 48MHz CPU, 32KB Flash, 4KB SRAM, 64-TQFP` 

CY8C4245AZI-M445
- [ ] See above comment about the description

CY8C4246AXI-M445
- [ ] This should be an alias of CY8C4245AXI-M445 (same package)

CY8C4246AZI-M445
- [ ] This should be an alias of CY8C4245AZI-M445 (same package)

CY8C4246AZI-M475
- [ ] This should be an alias of CY8C4245AZI-M445 (same package)

CY8C4247AXI-M485
- [ ] This should be an alias of CY8C4245AXI-M445 (same package)

CY8C4247AZI-M475
- [ ] This should be an alias of CY8C4245AZI-M445 (same package)

CY8C4247AZI-M485
- [ ] This should be an alias of CY8C4245AZI-M445 (same package)

Else good job !

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@dogtopus ping

**Comment by dogtopus** [comment]
@myfreescalewebpage Done.

**Comment by myfreescalewebpage** [comment]
Thanks, great job done here. Merging !

**Pull request merged**
