### PR TITLE
Fix PowerIntegrations parts

### PR DESCRIPTION
**Pull request by jkriege2**
- fixes remaining issues from https://github.com/KiCad/kicad-symbols/pull/90 (footprints, moving of some remaining legacy symbols)
- footprints available at: https://github.com/KiCad/kicad-footprints/pull/194
- all KLC-violations are due to "missing footprints", which are part of the PR above

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Still two footprints "missing" - OK to merge or will you address these also?

**Comment by jkriege2** [comment]
I will have a look after new year (I'm not at homne at the moment ;-)

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

I added the missing footprint (https://github.com/KiCad/kicad-footprints/pull/205)  and fixed one footprint field.

OK to merge?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan :)

**Pull request merged**
