### PR TITLE
Create aliases for LP5907MFX-1.8.

### PR DESCRIPTION
**Pull request by matthuszagh**
http://www.ti.com/lit/ds/symlink/lp5907.pdf

Created aliases for the various output voltages.

I also removed the leading asterisk from the footprint filter.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- The footpilter filter should also not have the pin count. Can you change it to `SOT?23*`?
- At the end of each description please add the voltage and package, like `, 1.8V, SOT-23`.
- And one more silly thing: would you mind making the lowest voltage the symbol name and higher voltages as ALIASes?

**Comment by matthuszagh** [comment]
@evanshultz, all suggestions fixed, let me know if anything else.

**Comment by evanshultz** [comment]
Thanks! :)

Would you mind to order the ALIASes in increasing voltage? That means moving the 1.8V from the end.

**Comment by matthuszagh** [comment]
Done

**Comment by evanshultz** [comment]
Thanks for doing more then the minimum! :)

**Comment by matthuszagh** [comment]
Absolutely! Might as well do it right.

**Pull request merged**
