### PR TITLE
Interface: Add CP2615-A02 USB to I2S bridge

### PR DESCRIPTION
**Pull request by dokthar**
The CP2615-A02 is an USB Audio to I2S Digital Audio bridge.

The datasheet is here:
https://www.silabs.com/documents/public/data-sheets/cp2615-datasheet.pdf

cp2615-a02

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
     PR https://github.com/KiCad/kicad-footprints/pull/2011
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by dokthar** [comment]
changed the footprint to:
Package_DFN_QFN:QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm
Footprint PR https://github.com/KiCad/kicad-footprints/pull/2011

**Comment by myfreescalewebpage** [comment]
Hi @AUTHOR, thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "CP2615-xx-xM"
- [ ] Footprint should be `QFN*1EP*5x5mm*P0.5mm*`
- [ ] REGIN should be on the top of the symbol
- [ ] Pin 10 should be on the border outline of the symbol

Cheers,
Joel

**Comment by dokthar** [comment]
thanks for the feedback I will update this asap

**Comment by dokthar** [comment]
Hi @myfreescalewebpage, I've updated the symbol with your remarks, but
Travis CI is still giving me an error for pin 33 (GND), although it might not be the same:
```
Power pins should be of type POWER INPUT or POWER OUTPUT
 - Pin GND (33) @ (0,-1100) is of type PASSIVE
```
cp2615

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Maybe the travis test which fails but I don't see the reason... Merging anyway after double check the symbol on a real schematic.
Joel

**Pull request merged**
