### PR TITLE
Add TPS7A7200RGW.

### PR DESCRIPTION
**Pull request by matthuszagh**
http://www.ti.com/lit/ds/symlink/tps7a7200.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh, thanks for contributing,

A few comments I have during my review:

- [ ] footprint filter should be `Texas*VQFN*RGW*` (without the first `*`)
- [ ] pins 5/6/7/9/10/11 are Input, not Power input, and should be placed on the left of the symbol (this will enlarge the size of the symbol vertically and reduce horizontally, check at other LDOs to get the size width for example)
- [ ] pin 21 should be called `EP` for consistency with other devices
- [ ] pin 21 EP should be Passive, not power Input, the datasheet indicates it is possible to leave it floating, not connected to GND
- [ ] pin 4 PG is active low, and should be name `~PG`
- [ ] pin 4 PG should be moved to the right bottom corner of the symbol, and pins OUT in the right top corne, for consistency with other devices

Cheers,
Joel

**Comment by matthuszagh** [comment]
The datasheet describes PG as "Active-high power good pin." Did I get that wrong? I made the rest of the modifications. Let me know about PG and I'll adjust accordingly.

**Comment by myfreescalewebpage** [comment]
@matthuszagh you're right for logic of PG, that's a mistake.

All other done. GND not centered at the bottom troubles me, can you get it centered on the symbol ?

Joel

**Comment by matthuszagh** [comment]
Better?

**Comment by myfreescalewebpage** [comment]
@matthuszagh looks great for me !

@antoniovazquezblanco this PR is ready to be merged according to me.

Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage, added footprint to description.

**Comment by myfreescalewebpage** [comment]
@matthuszagh thanks, okay for me.

@antoniovazquezblanco I think this PR is ready to be merged.

**Comment by antoniovazquezblanco** [comment]
The FB pin is similar to the ADJ pin in other devices of the lib. Should we wait to have consensus on wether that pin should be input/passive?

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
