### PR TITLE
Add Inolux IN-PI554FCH and IN-PI556FCH RGB addressable LEDs

### PR DESCRIPTION
**Pull request by diegoherranz**
They are similar to WS2812B and WS2812 respectively and the
symbols have been created using those as starting point.

New footprint for IN-PI554FCH at https://github.com/KiCad/kicad-footprints/pull/756.
IN-PI556FCH uses existing WS2812 footprint.

IN-PI554FCH
in-pi554fch_symbol

IN-PI556FCH
in-pi556fch_symbol

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by diegoherranz** [comment]
Travis fails on:

- `Pin offset outside allowed range. Pin offset (10) should not be below 20mils.` I didn't modify that from the original symbols. I've tried with 20 mils and it looks less tidy in my opinion (see screenshot).
bigger_offset
- `Specified footprint does not exist`: KiCad/kicad-footprints#756
- `Footprint filters should match all appropriate footprints. Minuses and underscores in footprint filter 'LED*IN-PI554FCH*PLCC*5.0x5.0mm*P3.2mm*' should be escaped with '?' or '*'. ` Even if the "minus" is part of the part name? e.g. IN-PI554FCH

**Comment by diegoherranz** [comment]
Gentle reminder. Did anyone have a chance of looking at this?

**Comment by antoniovazquezblanco** [comment]
It seems that nobody has started reviewing thing yet. Please be patient as librarians have a ton of pending work as you can see. Thank you :)

**Comment by poeschlr** [comment]
In this case the minus in the footprint filter is allowed (travis will always complain about that. This is something that can not be checked automatically)

thanks for your contribution. all is well.

**Pull request merged**
