### PR TITLE
Add Driver_FET/ITS724G and aliases

### PR DESCRIPTION
**Pull request by chschlue**
https://www.infineon.com/dgdl/Infineon-ITS724G-DS-v01_01-en.pdf?fileId=db3a304412b407950112b428d6083e90

ITS724G

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @chschlue , thanks for contributing,

A few comments I have during my review:

- [ ] Name of pin 2 is "GND1/2" and name of pin 6 is "GND3/4" and they should not be stacked.

Cheers,
Joel

**Comment by chschlue** [comment]
Done.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
