### PR TITLE
Adding LM22678TJ-5, LM22678TJ-ADJ regulator

### PR DESCRIPTION
**Pull request by JonathSpirit**
Adding LM22678TJ-5, LM22678TJ-ADJ regulator
5-A Step-Down Voltage Regulator

datasheet : https://www.ti.com/lit/ds/symlink/lm22678.pdf

image

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @JonathSpirit , thank you for the addition. I want to ask for some changes,
i think you should move NC and EN pin to be symetrical with BOOT and FB,
EP and GND pins i think should be stacked, since it is mentioned in the datasheet to connect them both to ground,
and last, footprint filter i think should be something like `TO*263*7*TabPin8*`.

**Comment by JonathSpirit** [comment]
I applied the changes
image

**Review by aris-kimi — APPROVED** [review]
I think this PR can be merged.
Thank you for the changes.

**Comment by myfreescalewebpage** [comment]
Hello @JonathSpirit thanks for this contribution and thanks to @aris-kimi for the first steps review.

Some few additional comments:
- [ ] Footprint filter should be `TO?263*`
- [ ] BOOT should be Passive to avoid ERC errors
- [ ] The height of the symbol is too important. See for example TPS56339DDC which is a good example in the library.

Joel

**Comment by JonathSpirit** [comment]
Thanks i will change that after my vacation (2 weeks max)

**Comment by myfreescalewebpage** [comment]
@JonathSpirit no problem, I will finish here when it will be fixed.

**Comment by JonathSpirit** [comment]
image

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
