### PR TITLE
WCH CH330N USB-UART interface

### PR DESCRIPTION
**Pull request by jeanthom**
Hi again !

ch330n

Datasheet is chinese-only : [CH330N datasheet download page](http://www.wch.cn/download/CH330DS1_PDF.html)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Quite a lot of interest in the CH330 series. Let's take some cues from https://github.com/KiCad/kicad-symbols/pull/814.
- Change the datasheet link to http://www.wch.cn/downloads/file/240.html (at least for now).
- In the description, change "SOIC8" to "SOIC-8".
- Set pin name offset to 20mil.
- Move V3 to the left side.
- Put an empty pin space between RXD and ~RTS.
- Put ref des on top left and value on top right.
-  The symbol merged above is +/-300mil wide; can this one shrink to match?

I received an official English version 2 datasheet from WCH but it doesn't include CH330N. I've asked for that and if the English datasheet(s) are online. Let's see if we can get an official datasheet from their website before merging.

**Comment by jeanthom** [comment]
Thank you for your precious feedback. I tried to follow your advices, except for the pin name offset : how can I adjust that parameter ?

ch330n

**Comment by jeanthom** [comment]
ch330n

Pin name offset now have the correct value.

**Comment by evanshultz** [comment]
Thanks!

Everything here looks good to me. Let's wait a day to see if WCH responds to me with an English datasheet.

@poeschlr 
At https://github.com/KiCad/kicad-symbols/pull/814 we talked about datasheets from the company WCH. They sent me a newer English datasheet for that PN and said I can share it but it's not hosted on their website. In this rare and odd circumstance, can I host the file on our GH page and then link the symbol to it? Similarly, if the same thing happens with the CH330 datasheet for the IC in the PR, can I do the same thing?

**Pull request merged**
