### PR TITLE
Adding TPD4E02B04

### PR DESCRIPTION
**Pull request by ki5libs**
Adding TPD4E02B04
[Datasheet](http://www.ti.com/lit/ds/symlink/tpd4e02b04.pdf)

TPD4E02B04DQA

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "TPD4E02B04DQA"
- [ ] Description should ends with full package name : "4-Channel ESD Protection Diode for USB Type-C and HDMI 2.0, USON-10"
- [ ] The design is a bit strange, maybe you can reworked it based on D3V3XA4B10LP or SP0504BAJT examples in the library ?

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

thanks for review. I've reworked symbol based on SP0504BAJT design. I hope it looks better now.

**Comment by myfreescalewebpage** [comment]
Thanks.
One error I haven't seen before: pin 3 should be Passive.

There is some space left, I propose the following a lit bit smaller, what do you think:

Capture

Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

pin 3 type changed. I tried to squeeze symbol, but your variant leads to this Travis error:

`Pins not located on 100mil (=2.54mm) grid:`

Maybe we can use this one?

TPD4_N

**Comment by myfreescalewebpage** [comment]
@ki5libs I don't really like the last proposition, we lose the information how the pin 3 is connected inside the device. You can use my proposition but with a shift of the center by 50mil to the bottom or the top. This will make the pins on the 100mil grid and we will only have a warning about the center of the device.

**Comment by ki5libs** [comment]
OK, let's do it this way


TPD4_2

**Comment by myfreescalewebpage** [comment]
Clearly better :) Merging.

**Pull request merged**
