### PR TITLE
Update footprint pointers for Murata based components

### PR DESCRIPTION
**Pull request by JacobEFO**
Updating Murata naming convention to 'Murata'.

This PR solves the last bit with symbol -> footprint association: https://github.com/KiCad/kicad-footprints/issues/545

**Other PRs:**
kicad-packages3D: https://github.com/KiCad/kicad-packages3D/pull/595
kicad-3d-models-in-freecad: https://github.com/easyw/kicad-3d-models-in-freecad/pull/309
kicad-footprint-generator: https://github.com/pointhi/kicad-footprint-generator/pull/394
kicad-footprints: https://github.com/KiCad/kicad-footprints/pull/1681

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@JacobEFO thanks, need to wait the footprint and this is to be done in release 6.0.0. Else no comment to do here. Joel

**Comment by myfreescalewebpage** [comment]
@JacobEFO we are closed to V6 and breaking changes are now allowed.
Can you rebase for all the repo (this one for example has branch conflict), double check Murata is correctly spelled everywhere.
Then I will review the 3 PR at the same time and merge.
Thanks
Joel

**Comment by myfreescalewebpage** [comment]
@JacobEFO ping

**Comment by JacobEFO** [comment]
@myfreescalewebpage I totally forgot to reply. I have been trying to fix this MR, but I have quite some troubles with rebasing and not doing an ordinary merge.

**Comment by myfreescalewebpage** [comment]
@JacobEFO did you find a solution ?

**Comment by JacobEFO** [comment]
@myfreescalewebpage Not yet, but I also haven't had a chance to spend much time on this matter. There's just too much going around. I'll try to see, if I can manage to fix the rebase tonight.

**Comment by JacobEFO** [comment]
@myfreescalewebpage Have a look at the commit now. I suspect Travis might break on the fact, that the footprint PR is not merged yet.

**Comment by myfreescalewebpage** [comment]
@JacobEFO looks good!

I have checked for all the remaining "muRata". Can you fix also:

CMWX1ZZABZ-078
- [ ] In the description "muRata" => "Murata"

CMWX1ZZABZ-091
- [ ] In the description "muRata" => "Murata"

Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
@JacobEFO if you have not the time to update everything, I suggest to give the priority to symbol and footprints.

**Comment by myfreescalewebpage** [comment]
Do with the time you want to spend on this subject of course, no worries

**Comment by JacobEFO** [comment]
@myfreescalewebpage changes should be implemented.

**Comment by myfreescalewebpage** [comment]
@JacobEFO thanks, just need to wait the integration of footprints to merge this one

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging following integration of the fp

**Pull request merged**
