### PR TITLE
Add tps62056dgs step-down converter

### PR DESCRIPTION
**Pull request by sudhi345**
Add symbol for tps62056dgs.
This PR is to add switching regulator TPS62056DGS by Texas Instruments.

---
- [ ] URL to the [datasheet](http://www.ti.com/lit/ds/symlink/tps62056.pdf) for the symbol.
Screenshot from 2019-09-21 18-01-56
- [ ] An example screenshot image.
- [ ] Associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] Reason behind the violation of S4.2: 
It is more convenient to have the Vin pin on the left.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @sudhi345 , thanks for contributing,

A few comments I have during my review:

- [ ] The description should ends with the package name and has not the usual format, I propose: `800 mA Step-Down Converter, Adjustable Output Voltage, 0.7-6V Input Voltage, VSSOP-10`
- [ ] Footprint filter should be `VSSOP*3x3mm*P0.5mm*`
- [ ] FB should be Input
- [ ] SW should be Power Output
- [ ] PG and LBO should be Open Collector

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@sudhi345 ping

**Comment by sudhi345** [comment]
Hello @myfreescalewebpage, 

I have pushed the modified library as you suggested. I had missed few obvious pin type, sorry for that. 

Thank you.
Sudheendra

**Comment by myfreescalewebpage** [comment]
No worries. Thanks for the fixes, no more comment to do.
Can you fix the branch conflict so I can merge the symbol ?

**Comment by sudhi345** [comment]
Hi,

I have removed conflicts and committed the changes. 

Thank you.

**Comment by myfreescalewebpage** [comment]
Sorry for the delay, merging now.

**Pull request merged**
