### PR TITLE
Adding USB3250 UTMI PHY

### PR DESCRIPTION
**Pull request by ki5libs**
Adding USB3250 UTMI PHY
[Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/00002142A.pdf)

USB3250

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/2026)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Footprint is now merged.

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

- [ ] Datasheet link is not correct, should be `http://ww1.microchip.com/downloads/en/DeviceDoc/00002142A.pdf`
- [ ] Description should ends with package name: `Hi-Speed USB Device Transceiver with UTMI Interface, QFN-56`
- [ ] Footprint filter should be: `QFN*1EP*8x8mm*P0.5mm*`
- [ ] XO should be Output
- [ ] RBIAD should be Passive

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@ki5libs ping

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage sorry for delay, I've missed that for some reason. It's fixed now. Thanks for review!

**Comment by myfreescalewebpage** [comment]
Thanks, no worries! No more comment, merging.

**Pull request merged**
