### PR TITLE
Add Mini-Circuits ADP-2-1W

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/ADP-2-1W.pdf

adp-2-1w

footprint https://github.com/KiCad/kicad-footprints/pull/1130

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to update the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

The branch conflict prevent to checkout your contribution. Can you solve the conflict so I will be able to make the review ? Thanks.

Obviously, you can proceed with comments from https://github.com/KiCad/kicad-symbols/pull/1216 at the same time.
 
Cheers,
Joel

**Comment by aewallin** [comment]
git is just a mess with these merge-conflicts :(
Now I seem to have two symbols added here - and I don't know why.

**Comment by aewallin** [comment]
Now:
adp-2-1w

**Comment by aewallin** [comment]
this resulted in a git-mess.
continuing instead at: #1372

**Pull request closed without merging**
