### PR TITLE
TPS7A7200RGW should be in Regulator_Linear.

### PR DESCRIPTION
**Pull request by matthuszagh**
I made a mistake with this earlier. It is an LDO regulator not a switching regulator and should really be in the Regulator_Linear library, not the Regulator_Switching library.

www.ti.com/lit/ds/symlink/tps7a7200.pdf

I understand that this breaks existing designs. However, since the original branch was merged only 7 days ago the damage should be minimal. Let me know of any thoughts/concerns.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@matthuszagh thanks for this, we have missed the regulator type in the previous PR.

No comment to do, can you just fix the branch conflict (due to another merge) so I can merge the modification in Regulator_Linear ?

Joel

**Comment by poeschlr** [comment]
This would even be acceptable if the original symbol has been part of kicad for a long time. (Reason: This fixes a bug that could lead to users misinterpreting what the symbol stands for.)

**Comment by myfreescalewebpage** [comment]
Agree with @poeschlr

**Comment by matthuszagh** [comment]
Should be fixed now. Thanks for explaining that, @poeschlr.

**Comment by matthuszagh** [comment]
@evanshultz done.

**Pull request merged**
