### PR TITLE
Add Rayac MDBT50Q Module

### PR DESCRIPTION
**Pull request by soburi**
Add Rayac MDBT50Q Module

Datasheet: 
https://www.raytac.com/download/index.php?index_id=43
https://www.raytac.com/download/index.php?index_id=46

ScreenShot:
mdbt50q-1mv
mdbt50q-512k

Footprint PR is KiCad/kicad-footprints#2390.

--------------------------------------------------------------

- [x] Provide a URL to a datasheet for [the] symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprint
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by soburi** [comment]
``` 
   Specified footprint does not exist

     - Footprint file RF_Module:Raytac_MDBT50Q was not found
```

Footprint file will be available with KiCad/kicad-footprints#2390 accepted, I think there should be no problem at this point.

**Comment by myfreescalewebpage** [comment]
Hi @soburi , thanks for contributing,

A few comments I have during my review:

MDBT50Q-1MV2
- [ ] Pin length should be 100mil for this symbol
- [ ] Name of pin 17 should be `XL1/P0.00` to have main function on the border
- [ ] Name of pin 18 should be `XL2/P0.01` to have main function on the border
- [ ] Name of pin 23 should be `TRACECLK/P0.07` to have main function on the border + same comment for TRACEDATA pins
- [ ] Pin 25 P1.08 should be below pin 58 P1.07
- [ ] Pin 51 SWDIO is Bidirectional
- [ ] D+ and D- are Bidirectional

MDBT50Q-512K
- [ ] Pin length should be 100mil for this symbol
- [ ] Name of pin 17 should be `XL1/P0.00` to have main function on the border
- [ ] Name of pin 18 should be `XL2/P0.01` to have main function on the border
- [ ] Name of pin 23 should be `TRACECLK/P0.07` to have main function on the border + same comment for TRACEDATA pins
- [ ] Pin 25 P1.08 should be below pin 58 P1.07
- [ ] Pin 51 SWDIO is Bidirectional
- [ ] D+ and D- are Bidirectional
- [ ] Pin 42 is NC

Cheers,
Joel

**Comment by soburi** [comment]
Hi! @myfreescalewebpage.

Thank you for reviewing.

Fix problems that pointing out in your comments.

And additionally fix the function name order of P0.18/~RESET.
(The pin act as GPIO at default. Change the same as MCU_Nordic:nRF52840 symbol's notation.)


Regards.

SnapCrab_Symbol Editor — RF_ModuleMDBT50Q-1MV2_2020-8-27_18-26-53_No-00

SnapCrab_Symbol Editor — RF_ModuleMDBT50Q-512K_2020-8-27_18-27-6_No-00

**Comment by myfreescalewebpage** [comment]
Thanks, great job ! No more comment to do, just need to wait the footprint.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging following integration of fp

**Pull request merged**
