### PR TITLE
Add BQ24392

### PR DESCRIPTION
**Pull request by EvilMav**
[Datasheet](http://www.ti.com/lit/ds/symlink/bq24392.pdf)

kicad_bq24392

~~Requires footprint: https://github.com/KiCad/kicad-footprints/pull/1310~~
Footprint has been merged.

I've kept spacing and order on the left side to exactly match those of the USB-connectors in the library.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
datasheet link above has some github-url at the front...

**Comment by myfreescalewebpage** [comment]
Hi @EvilMav , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter never contains number of pin, I suggest `Texas*R*PUQFN*` (format which is also consistent with other Texas devices)
- [ ] VBUS should be moved to the top of the symbol (that's the main supply) and I do not understand the position of the pins on the symbol. I'm referring to typical applications chematic page 10 of the datasheet and would like to suggest the following:

capture

Else, no comment to do.

Cheers,
Joel

**Comment by EvilMav** [comment]
Hi @myfreescalewebpage, thank you for taking the time.

The reasoning behind putting VBUS to the left was to make it fit directly to an usb connector, as DP/DM and VBUS will always be just connected there. Vbus will be usually connected to a power bus too, so having it on top still works if it is preferred.

I've fixed the footprint filter and changed the layout exactly to the one you've suggested.

**Comment by myfreescalewebpage** [comment]
Thanks @EvilMav 
Yes power pin on the top is preferred.
Merging.

**Pull request merged**
