### PR TITLE
Added symbol for ASMB-MTB0-0A3A2

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Added symbol for ASMB-MTB0-0A3A2

I have done a footprint in another PR https://github.com/KiCad/kicad-footprints/pull/2137

Datasheet: https://www.farnell.com/datasheets/2608172.pdf

Screenshot from 2020-03-14 13-49-22

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
Have to go now but return to this later. Today.

**Comment by myfreescalewebpage** [comment]
@johnfwhitmore have you got another PR for the footprint ?

**Comment by myfreescalewebpage** [comment]
Not a complete review, but I see several defects:

- [ ] Pin name to be hidden
- [ ] No datasheet
- [ ] Description should ends with the package name "PLCC-4" and can be enhanced
- [ ] Footprint / footprint filter seems to not be correct according to travis
- [ ] I recommend to look at the other ASMB RGB LED in the library to fix the issues on this one.

Joel

**Comment by johnfwhitmore** [comment]
I did have a PR for the footprint but I got caught out using a more recent version of KiCad so a few things had to be redone after I re-installed. I'll do a footprint on the correct version and fix your corrections. 

Thanks.

**Comment by johnfwhitmore** [comment]
It appears that there's already a footprint for the LED in the kicad libs, just have to get the correct footprint filter

**Comment by johnfwhitmore** [comment]
There are still a lot of errors but they appear to be related to other symbols, rather then the ASMB-MTB0-0A3A2 symbol

**Comment by myfreescalewebpage** [comment]
Thanks @johnfwhitmore 
I see plenty of unwanted modifications, or maybe I miss something. Please check at https://github.com/KiCad/kicad-symbols/pull/2543/files and confirm if this is the wanted mofiications.
Joel

**Comment by johnfwhitmore** [comment]
Sorry about that. I'll got over this again

**Pull request closed without merging**
