### PR TITLE
add AAT1217 step-up converter

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the AAT1217 step-up converter in the different existing variants. I was not really sure about the type of the top pin and decided on passive in the end. The FB pin is also set to passive as it may be disconnected in the fixed voltage variants. [Datasheet](http://www.skyworksinc.com/uploads/documents/AAT1217_202050B.pdf)
AAT1217ICA-1

---
All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

AAT1217ICA-1.2:
- [ ] Footprint filter should be `TSOT?23*`

AAT1217IGU-3.3:
- [ ] Footprint filter should be `SOT?23*`
- [ ] Package name in the description should be "SOT-23-6", not "TSOT"

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage,

thanks for the review, the issues should be fixed now.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
