### PR TITLE
Tps65130rge

### PR DESCRIPTION
**Pull request by lukh**
Adding TPS65130RGE, Positiveand NegativeOutputDC-DCConverter
[Link](http://www.ti.com/lit/ds/symlink/tps65130.pdf?&ts=1589185215924)

Screenshot from 2020-05-11 10-21-21

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lukh , thanks for contributing,

A few comments I have during my review:

- [ ] Space in front of the description to be removed
- [ ] Fp filter should be `VQFN*1EP*4x4mm*P0.5mm*`
- [ ] Pin offset 20mil
- [ ] NC pin should be added, invisible, type not connected, on the border outline of the symbol
- [ ] Name of pin 25 should be "EP"

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@lukh ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by lukh** [comment]
- [ ] Space in front of the description to be removed
- [ ] Fp filter should be VQFN*1EP*4x4mm*P0.5mm*
- [ ] Pin offset 20mil
- [ ] NC pin should be added, invisible, type not connected, on the border outline of the symbol
- [ ] Name of pin 25 should be "EP"

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
