### PR TITLE
add HMC799 high-speed transimpedance amplifier

### PR DESCRIPTION
**Pull request by aewallin**
Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/hmc799.pdf
HMC799LP3E

Possible issues for discussion:
* In what library should transimpedance amplifiers go? I now placed it in the op-amps library
* There are three VCC-pins and the datasheet example circuit shows separate decoupling caps for each. I wanted to stick with an op-amp sized symbol, so the VCC pins are stacked.
* No NC pins are drawn
* pin name text size reduced to fit within triangle without overlap
* the only GND-connection is through EP, so I am calling pin25 "GND" (not EP)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aewallin** [comment]
I don't understand the Travis error about pin stacking. Once visible VCC is Power Input, and the others are invisble and Passive.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Package in the description should be QFN-16 not QFN-24
- [ ] Footprint filter has never EP size, it should be `QFN*1EP*3x3mm*P0.5mm*`
- [ ] NC pins should be added (invisible, inside the symbol, not stacked)
- [ ] GND is pin 17

Do not worry about VCC in travis result.

Cheers,
Joel

**Comment by aewallin** [comment]
thanks for catching the obvious errors!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
