### PR TITLE
Add MP1470

### PR DESCRIPTION
**Pull request by lorenz**
This adds the Monolithic Power Systems MP1470 (https://www.monolithicpower.com/pub/media/document/MP1470_r1.02.pdf) DC/DC converter.
MP1470

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by lorenz** [comment]
OT: Is there any way I can tell KiCad not to rewrite the entire library if I add a symbol? I've manually staged only the new symbol, but why is it rewriting half the file?

**Comment by myfreescalewebpage** [comment]
Hi @lorenz , thanks for contributing,

A few comments I have during my review:

- [ ] The symbol should be added to the "Regulator_Switching" library, not with DC/DC converters
- [ ] Keywords can be `buck converter`
- [ ] Description should ends with complete package name: `High-Efficiency, 2A, 16V, 500kHz Synchronous, Step-Down Converter, TSOT-23-6`
- [ ] Footprint filter should be `TSOT?23*` (no pin count in the fp filters)
- [ ] Type of pin 6 should be Passive to avoid ERC errors

Cheers,
Joel

**Comment by lorenz** [comment]
I've fixed these issues, can you take a look?

**Comment by myfreescalewebpage** [comment]
Thanks @lorenz , reviewed, no more comment. Merging.

**Pull request merged**
