### PR TITLE
Added TI SimpleLink CC1312r

### PR DESCRIPTION
**Pull request by ppielorz**
Added TI SimpleLink MCU library with CC1312R microcontroller.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

Datasheet: http://www.ti.com/lit/ds/symlink/cc1312r.pdf

image

### CODE REVIEW

**Comment by ppielorz** [comment]
After Travis suggestions:
image


Really don't know what to do with sym-table error.

**Comment by myfreescalewebpage** [comment]
@ppielorz the error is because you created a new library that need to be declared in the "sym-lib-table" file (root directory of the repository).
Can you update it before we start the review ? Thanks.
Joel

**Comment by ppielorz** [comment]
@myfreescalewebpage I have added entry in sym-lib-table. The symbol is ready to be reviewed.

Paweł

**Comment by myfreescalewebpage** [comment]
Hi @ppielorz , thanks for contributing,

A few comments I have during my review:

- [ ] Part name should be `CC1312R1F3RGZ`
- [ ] Description should not contain the part name, has a wrong format and should ends with the full package name, please modify to `ARM Cortex-M4 SimpleLink High-Performance Sub-1GHz Wireless MCU, 48MHz, 352KB Flash, 8KB SRAM, 1.8-3.6V, 30 GPIO, VQFN-48`
- [ ] Keywords should be `32-bit ARM Cortex-M4 MCU Microcontroller`
- [ ] Footprint is not correct, package is VQFN-48, it this should be `Package_DFN_QFN:VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm`. If it does not exist, you should submit it.
- [ ] Footprint filter should be `VQFN*1EP*7x7mm*P0.5mm*`
- [ ] DCOUPL should be Power Output and move to the top of the symbol
- [ ] Name of pin 26 should be `DIO_16/JTAG_TDO`
- [ ] Name of pin 27 should be `DIO_17/JTAG_TDI`
- [ ] Name of pin 35 should be `~RESET` (it is active low)
- [ ] RF_P, RF_N and RX_TX should be Passive to avoid ERC errors
- [ ] I'm not sure of the position of the X32K and X48M pins, is it really easy to wire the crystals like that ? We usually put crystal at the bottom of left and right sides.
- [ ] Position and drawing of the symbol at the top can be better, more symmetrical, Power Input on the top left, Power Output on the top right for example.

Cheers,
Joel

**Comment by ppielorz** [comment]
Hi,
Your remarks:
> * [ ]  Part name should be `CC1312R1F3RGZ`

Done
> * [ ]  Description should not contain the part name, has a wrong format and should ends with the full package name, please modify to `ARM Cortex-M4 SimpleLink High-Performance Sub-1GHz Wireless MCU, 48MHz, 352KB Flash, 8KB SRAM, 1.8-3.6V, 30 GPIO, VQFN-48`

Done
> * [ ]  Keywords should be `32-bit ARM Cortex-M4 MCU Microcontroller`

Done
> * [ ]  Footprint is not correct, package is VQFN-48, it this should be `Package_DFN_QFN:VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm`. If it does not exist, you should submit it.

Footprint changed but I have to create it.
> * [ ]  Footprint filter should be `VQFN*1EP*7x7mm*P0.5mm*`

Done.
> * [ ]  DCOUPL should be Power Output and move to the top of the symbol

Done
> * [ ]  Name of pin 26 should be `DIO_16/JTAG_TDO`

Done.
> * [ ]  Name of pin 27 should be `DIO_17/JTAG_TDI`

Done.
> * [ ]  Name of pin 35 should be `~RESET` (it is active low)

Done.
> * [ ]  RF_P, RF_N and RX_TX should be Passive to avoid ERC errors

Done.
> * [ ]  I'm not sure of the position of the X32K and X48M pins, is it really easy to wire the crystals like that ? We usually put crystal at the bottom of left and right sides.

Done.
> * [ ]  Position and drawing of the symbol at the top can be better, more symmetrical, Power Input on the top left, Power Output on the top right for example.

Done
> 
> Cheers,
> Joel

**Comment by myfreescalewebpage** [comment]
Thaks @ppielorz for all the fixes, looks very great, just need to wait the footprint for me here !
Joel

**Comment by ppielorz** [comment]
Changed footprint PR: https://github.com/KiCad/kicad-footprints/pull/1542.

**Comment by poeschlr** [comment]
thanks

**Comment by myfreescalewebpage** [comment]
Thanks @poeschlr to merge it!

**Pull request merged**
