### PR TITLE
Adding TFP410

### PR DESCRIPTION
**Pull request by ki5libs**
Adding TFP410
[Datasheet](http://www.ti.com/lit/ds/symlink/tfp410.pdf)

TFP410

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Is there a reason the data ports are not sorted ascending? (KLC S4.2 requires this)

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "TFP410PAP"
- [ ] Pin offset should be 20mil (see travis error)
- [ ] Pin length should be 100mil for this symbol (< 100 pins)
- [ ] Footprint filter should be `HTQFP*1EP*10x10mm*P0.5mm*`
- [ ] Description should ends with the full exact package name (HTQFP-64)
- [ ] DSEL/SDA should be Bidirectional
- [ ] Name of pin 65 should be "EP"
- [ ] You can align positive power pins to negative power pins
- [ ] You can decrease the height of the symbol by 100mil

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

thank you for review. Your notices are fixed.

**Comment by myfreescalewebpage** [comment]
Thanks, great job, merging.

**Pull request merged**
