### PR TITLE
Add MIC2025

### PR DESCRIPTION
**Pull request by jneiva08**
Add MIC2025

Datasheet: https://ww1.microchip.com/downloads/en/DeviceDoc/MIC2025-2075-Single-Channel-Power-Distribution-Switch-DS20006030A.pdf

Symbol:
mic2025

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] This kind of symbol should be atomic, i.e. one symbol for each package version, footprint set for each version
- [ ] FLG should be Open Collector
- [ ] NC pins should be on the border outline of the symbol
- [ ] IN should be on the left and OUT on the right. Heigh can be the same than some similar devices in the library, I propose the following design:

Capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks.
Footprint and footprint filter not fixed.
Else, good job.
Joel

**Comment by jneiva08** [comment]
Sorry totally forgot to remove it.

**Comment by myfreescalewebpage** [comment]
Footprint filter ok :) but still missing the footprint itself :)

**Comment by jneiva08** [comment]
@myfreescalewebpage sorry took a wile to understand what was missing :disappointed:

**Comment by myfreescalewebpage** [comment]
@jneiva08 no worries :) Merging now!

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
