### PR TITLE
Battery_Management: Add BQ24005 and BQ24006

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://www.ti.com/lit/ds/symlink/bq24006.pdf

imagen

FP PR: https://github.com/KiCad/kicad-footprints/pull/1441

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A few comments I have during my review:

- [ ] First, the two devices can't be alias because type of pins 14 and 15 is not the same. It is Open Collector on BQ24005, Output on BQ24006.
- [ ] "Li-ION" in the descriptions and keywords should be "Li-Ion" for consistency with other devices
- [ ] The footprint is not correct (wrong EP size), should be `Package_SO:HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP2.4x3.4mm` (does not exist, should be submitted)
- [ ] Footprint filter should be `HTSSOP*1EP*4.4x6.5mm*P0.65mm*`
- [ ] Pin 19 type should be "Output" (even if stacked)
- [ ] Name of pin 13 should be `TMR SEL`
- [ ] The datasheet indicate that GND must be connected to the expose pad, thus, please stack pin 21 with pin 10.

If you want to submit also BQ25004 (the same with one STAT pin removed if I'm right), that's a pleasure to review it too.

Cheers,
Joel

**Comment by evanshultz** [comment]
This symbol also looks overly large to me.

**Comment by myfreescalewebpage** [comment]
Yes @evanshultz particularly when the expose pad will be stacked, I expect @antoniovazquezblanco will reduce the width too when doing the modifications.

**Comment by antoniovazquezblanco** [comment]
About the footprint I am not to sure on how to proceed. Below you can find the recommended layout pattern of the device. Minimum EP should be `Package_SO:HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP2.4x3.7mm` but the greater the copper area of the EP the better. Should we assign the minimum copper size possible or should we create a slightly bigger alternative?

imagen

**Comment by antoniovazquezblanco** [comment]
> Pin 19 type should be "Output" (even if stacked)

```
  Violating S4.3
    Rules for pin stacking
     - Pin OUT (19) : OUTPUT should be visible in a power-in/power-out/output pin stack
     - Pin OUT (19) : OUTPUT should be an invisible PASSIVE pin power-in/power-out/output pin stack
```

How should I proceed?

**Comment by evanshultz** [comment]
I vote we stick with the datasheet footprint. If users want to add alternatives they can do so, including to our own library. And in the PCB a zone can always be added to fatten up copper. To me we are doing _at least_ what TI suggests and more is an implementation choice.

**Comment by evanshultz** [comment]
http://kicad-pcb.org/libraries/klc/S4.3/ says that stacked Output pin should be Passive type.

**Comment by antoniovazquezblanco** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1441

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco sorry for the stacking of Output, it's an error, your version is correct as indicated by @evanshultz .

About the footprint, is "Package_SO:HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.4x3.7mm" the correct name for this device ?

STAT1 on BQ24004 should be Output, not Open Collector.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
> About the footprint, is `Package_SO:HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.4x3.7mm` the correct name for this device ?

I've extracted the name from existing footprints, if there is a more recent standard please report at the footprint thread.

**Comment by evanshultz** [comment]
FYI, I merged the footprint and I think the footprint name is good so this may be good to merge. It's all yours, Joel.

**Comment by myfreescalewebpage** [comment]
Thanks @evanshultz for the info, ok for me on the symbol after a final review, merging.

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
