### PR TITLE
Isolator: Add ISO1541

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://www.ti.com/lit/ds/symlink/iso1541.pdf

imagen

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco

A few comments I have during my review:

- [ ] You should move reference in the top left corner and name in the top right corner for consistency with other devices
- [ ] VCC1/2 and GND1/2 pins should be Power Input
- [ ] You should add package at the end of the description : `SOIC-8`
- [ ] SCL2 should be Output
- [ ] SDA1 and SDA2 should be Bidirectional

Maybe you can also add ISO1540 which is the same device but with bidirectional clock ?

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
I have addressed all the issues above. I've added another sym for the 1540 version also. KiCad decided to reorder one element in the libs. I am sorry about that.

What a poor job I made with that sym. Sorry about that!

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco thanks !

Still one error to fix:
- [ ] ISO1540, SCL1 and SCL2 should be Bidirectional

Also, why the HCPL-9000 is being modifying ?

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Done.

> Also, why the HCPL-9000 is being modifying ?

Not modified. Just KiCad reordering the file. That sym was not changed.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco OK, this is what I was thinking.

No more comment to do after your last commit, ready to be merged according to me.

Joel

**Comment by antoniovazquezblanco** [comment]
There is a non written rule in place. No one merges their own work. I will wait for @evanshultz @Misca1234 @SchrodingersGat  or @poeschlr to merge this.

**Comment by myfreescalewebpage** [comment]
Sure, you are right :)

**Pull request merged**
