### PR TITLE
Add Texas Instruments LPV811 and LPV812, nano power operational amplifiers

### PR DESCRIPTION
**Pull request by edp-d6labs**
This PR adds a TI dual-channel op-amp called LPV812. It features very low quiescent and input bias currents.

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing:

https://www.ti.com/lit/ds/symlink/lpv812.pdf

- [x] An example screenshot image is very helpful

lpv812_a
LPV812_b
LPV812_c

- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.

The package is VSSOP 3.0x3.0mm P0.65, which already exists in kicad-footprints

- [x] If there are matching footprint PRs, provide link(s) as appropriate:

There are none.

- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
Thanks for your contribution, @edp-d6labs.

I think this could be an alias of the just-released OPA2197xDGK.
Can you double-check and if it looks OK, convert this into an alias?
That way everything is easier to maintain with fewer symbols in the library.

Thanks!

**Comment by chschlue** [comment]
What @diegoherranz said should work.
Perhaps you could also add LPV811 as an alias to MCP6L91RT-EOT to complete the series?

**Comment by edp-d6labs** [comment]
@chschlue , @diegoherranz , I'm on it!

**Comment by chschlue** [comment]
Thanks.
Just the description of LPV811 still reads SOIC-8.

**Comment by edp-d6labs** [comment]
@chschlue , @diegoherranz , please take a look when you get a second.

**Comment by chschlue** [comment]
This is @diegoherranz 's baby, but before it gets forgotten:
Please add package suffixes, i.e. LPV811DBV and LPV812DGK.

**Comment by edp-d6labs** [comment]
@diegoherranz @chschlue something happened in master, not sure what to do

**Comment by edp-d6labs** [comment]
I think I finally did that right...

**Comment by diegoherranz** [comment]
Thanks for the changes, and thanks @chschlue for the comments.
I've noticed a couple of things:
- The datasheet URLs are duplicated
- The pinout of the original MCP6401RT-xOT is wrong!! Unless I missed something, power pins are swapped! Could you fix that too?
- The description of LPV811 still reads SOIC-8.
Thanks!

**Comment by chschlue** [comment]
> * The pinout of the original MCP6401RT-xOT is wrong!! Unless I missed something, power pins are swapped! Could you fix that too?

Good catch.

**Comment by edp-d6labs** [comment]
@diegoherranz 
> The description of LPV811 still reads SOIC-8
I think you meant LPV812? Either way thanks for catching all that! I'm working on it now.

**Comment by diegoherranz** [comment]
> Nope. That's what the R in the name is all about. So LPV811DBV should be an alias of MCP6L91T-EOT, not MCP6L91RT-EOT.

Very well spotted!! Thanks for that.

Thanks for the changes, @edp-d6labs. One of them still has the duplicated datasheet URL.

Thanks!

**Comment by edp-d6labs** [comment]
@diegoherranz sorry about that! Duplicate removed

**Comment by diegoherranz** [comment]
Looks good now. Thanks for your contribution, @edp-d6labs, I hope it's the first of many :)
Thanks for your help, @chschlue, too.

**Comment by yankee14** [comment]
@diegoherranz this is hardly my first!

Thanks guys

**Comment by chschlue** [comment]
Ed P. from D6 Labs... who was supposed to spot that?

**Comment by yankee14** [comment]
> Ed P. from D6 Labs... who was supposed to spot that?

@chschlue Sorry about that, I forgot I was submitting that from my work amount

**Pull request merged**
