### PR TITLE
Adding LFE5UM5G-85F, LFE5UM-85F and LFE5U-85F in 381 and 756 pin packages

### PR DESCRIPTION
**Pull request by ki5libs**
Adding LFE5UM5G-85F, LFE5UM-85F and LFE5U-85F in 381 and 756 pin packages
[Datasheet](https://www.latticesemi.com/view_document?document_id=50461)
[Pinout Information](https://www.latticesemi.com/view_document?document_id=51579)
Example screenshots for LFE5UM5G-85F-8BG756x
Part A
LFE_A
Part B
LFE_B
Part C
LFE_C
Part D
LFE_D
Part E
LFE_E
Part F
LFE_F
Part G
LFE_G
Part H
LFE_H
Part I
LFE_I
Part J
LFE_J
Part K
LFE_K
Part L
LFE_L

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/1924)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
I assume you did script this? If yes, can you please link to the source files?
Looking at the screenshots I don't see anything seriously wrong.
 - [ ] `PROGRAMN` and `INITN` might be inverted pins, http://kicad-pcb.org/libraries/klc/S4.7/

**Comment by ki5libs** [comment]
Hi @cpresser

- you are right about `PROGRAMN` and `INITN`, I've fixed them;
- looks like scripting makes sense in this case, but actually I didn't use any. I'm newbie in Python so I couldn't do it from scratch and there is no tool (like pointhi footprint generator), which could be used as a template.

**Comment by chschlue** [comment]
Please also remove double negatives, i.e. the `~PROGRAM` and `~INIT`

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

LFE5U-85F-8BG381x
- [ ] Datasheet should be the PDF document link (apply to the aliases too)
- [ ] Fp filter should be `Lattice*caBGA*17.0x17.0mm*Layout20x20*P0.8mm*`
- [ ] I haven't checked the pinout yet, but the footprint has only 355 pins while 381 are expected. Why ?

LFE5U-85F-8BG756x
- [ ] Datasheet should be the PDF document link (apply to the aliases too)
- [ ] Fp filter should be `Lattice*caBGA*27.0x27.0mm*Layout27x27*P0.8mm*`
- [ ] For the SERDES pins not available on this device, I have not a lot of information. I refer to table at the bottom of page 93 at https://www.latticesemi.com/view_document?document_id=50461. VCCAx is indicated to be connected to VCC,k but you have connected to GND, and I have no information for the other pins. Have you got some other document or somewhere else in the datasheet ? SERDES pins listed below for reference.

pin | footprint | datasheet
-- | -- | --
AC13 | GND | VCCHTX0_D0CH0
AC14 | GND | VCCHRX0_D0CH0
AC15 | GND | VCCHRX1_D0CH1
AC16 | GND | VCCHTX1_D0CH1
AC17 | GND | VCCHTX0_D1CH0
AC18 | GND | VCCHRX0_D1CH0
AC19 | GND | VCCHRX1_D1CH1
AC20 | GND | VCCHTX1_D1CH1
AF22 | GND | VCCA1
AG12 | GND | VCCA0
AG19 | GND | VCCA1
AG22 | GND | VCCA1
AG9 | GND | VCCA0
AH12 | GND | VCCA0
AH19 | GND | VCCA1
AH22 | GND | VCCA1
AH9 | GND | VCCA0
AJ10 | GND | VCCA0
AJ12 | GND | VCCA0
AJ13 | GND | VCCA0
AJ15 | GND | VCCAUXA0
AJ16 | GND | VCCAUXA0
AJ18 | GND | VCCA1
AJ19 | GND | VCCA1
AJ21 | GND | VCCA1
AJ22 | GND | VCCA1
AJ24 | GND | VCCAUXA1
AJ25 | GND | VCCAUXA1
AJ9 | GND | VCCA0
AK10 | RESERVED | HDTXN0_D0CH0
AK12 | RESERVED | HDTXP0_D0CH1
AK13 | RESERVED | HDTXN0_D0CH1
AK18 | RESERVED | HDTXP0_D1CH0
AK19 | RESERVED | HDTXN0_D1CH0
AK21 | RESERVED | HDTXP0_D1CH1
AK22 | RESERVED | HDTXN0_D1CH1
AK9 | RESERVED | HDTXP0_D0CH0
AM11 | GND | HDRXP0_D0CH1
AM12 | GND | HDRXN0_D0CH1
AM14 | GND | REFCLKP_D0
AM15 | GND | REFCLKN_D0
AM17 | GND | HDRXP0_D1CH0
AM18 | GND | HDRXN0_D1CH0
AM20 | GND | HDRXP0_D1CH1
AM21 | GND | HDRXN0_D1CH1
AM23 | GND | REFCLKP_D1
AM24 | GND | REFCLKN_D1
AM8 | GND | HDRXP0_D0CH0
AM9 | GND | HDRXN0_D0CH0

LFE5UM5G-85F-8BG381x
- [ ] Datasheet should be the PDF document link (apply to the aliases too)
- [ ] Fp filter should be `Lattice*caBGA*17.0x17.0mm*Layout20x20*P0.8mm*`
- [ ] I haven't checked the pinout yet, but the footprint has only 355 pins while 381 are expected. Why ?

LFE5UM5G-85F-8BG756x
- [ ] Datasheet should be the PDF document link (apply to the aliases too)
- [ ] Fp filter should be `Lattice*caBGA*27.0x27.0mm*Layout27x27*P0.8mm*`

Pin compatibility between 381 and 756 pins versions is good to have for these devices, so ok for the 200mil pin length on the 381pins version.

Can you also solve the branch conflict please ?

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@ki5libs I see you are working on this, I let you ping me when it is ready for review

**Comment by ki5libs** [comment]
@myfreescalewebpage I've fixed it and think it's ready for review now.

Couple more comments:
* I suppose you actually mean `Lattice*caBGA*27.0x27.0mm*Layout32x32*P0.8mm*` as a FP filter for LFE5U-85F-8BG756x and LFE5UM5G-85F-8BG756x
* On [this page](https://www.latticesemi.com/Products/FPGAandCPLD/ECP5) in `Pin & Package` category you could find pinout .csv files for all packages. [This one](https://www.latticesemi.com/view_document?document_id=50487) is for LFE5U-85F-8BG381x and LFE5U-85F-8BG756x. You could see that pins that have SERDES function in LFE5UM connected to GND (sometimes RESERVED) in LFE5U.

**Comment by myfreescalewebpage** [comment]
> I suppose you actually mean Lattice*caBGA*27.0x27.0mm*Layout32x32*P0.8mm* as a FP filter for LFE5U-85F-8BG756x and LFE5UM5G-85F-8BG756x

Yes sure, my bad!

> On this page in Pin & Package category you could find pinout .csv files for all packages. This one is for LFE5U-85F-8BG381x and LFE5U-85F-8BG756x. You could see that pins that have SERDES function in LFE5UM connected to GND (sometimes RESERVED) in LFE5U.

Thanks for the clarification

**Comment by myfreescalewebpage** [comment]
Pins check also for the 381 version, thanks for the addition
No more comment, merging

**Pull request merged**
