### PR TITLE
Add LTC6994-2

### PR DESCRIPTION
**Pull request by ferdymercury**
https://www.analog.com/media/en/technical-documentation/data-sheets/699412fb.pdf

Use with Package_DIP:DIP-6_W7.62mm_LongPads

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the official footprint library
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ferdymercury** [comment]
image

**Comment by ferdymercury** [comment]
Symbol reworked
image

**Comment by aewallin** [comment]
See also #1231 for a related symbol. Could be reviewed/revised together.

**Comment by ferdymercury** [comment]
style matches now https://github.com/KiCad/kicad-symbols/pull/1231 Both ready to merge.

**Comment by ferdymercury** [comment]
> Hello @ferdymercury
> 
> Seems the LTC6994_S6 can be an alias of LTC6993xS6-1 proposed in #1231, isn't it ?
> 
> Cheers,
> Joel

According to https://github.com/KiCad/kicad-symbols/pull/1231#issuecomment-445532434 they have to be different symbols

**Comment by myfreescalewebpage** [comment]
Have made my comment to much quickly, one input is not the same you are right. I'm currently reviewing your PR.

**Comment by myfreescalewebpage** [comment]
@ferdymercury seems there is a big problem in the lib file at the end of the LTC6994xS6 definition... Look at the "Files Changed" in the PR. Missing some pins and the END keywords of the definition.

Well making my first review just looking at your commit, not with the editor:
- [ ] I suggest to rename LTC6994xS6 to LTC6994xS6-1 and add LTC6994xS6-2 as an alias. Same for DCB package too. This permit to indicate difference between -1 and -2 in the descriptions.
- [ ] LTC6994xDCB have datasheet link indicated twice
- [ ] commas are not useful in the keywords
- [ ] Description of DCB symbol to be consistent with the LTC6993: `TimerBlox Delay Block/Debouncer, Programmable, Noise Discriminator, DFN-6`
- [ ] Description of S6 symbol to be consistent with the LTC6993: `TimerBlox Delay Block/Debouncer, Programmable, Noise Discriminator, TSOT-23-6`
- [ ] DFN footprint filter is not correct, should be `DFN*1EP*3x2mm*P0.5mm*`
- [ ] SOT footprint filter is not correct, should be `TSOT*23*` 

Thanks for your work,
Joel

**Comment by ferdymercury** [comment]
Ooops, sorry about the missing pins, that was a problem when resolving git conflicts. I fixed it now.

**Comment by ferdymercury** [comment]
Fixed the other issues, too

**Comment by myfreescalewebpage** [comment]
Hi @ferdymercury 

Thanks, great job on these symbols. A last few comment:
- [ ] It's good to indicate difference between -1 and -2 versions. You can add `, Rising or Failing Edge` for -1 and `, Rising and Failing Edges` for -2 in the description before the package for both S6 and DCB packages to achieve that.

Joel

**Comment by ferdymercury** [comment]
good point, done, thanks

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment, merging.
Joel

**Pull request merged**
