### PR TITLE
- added ATSAMD21J15/16/17/18A-A

### PR DESCRIPTION
**Pull request by daviid5**
Datasheet:
http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf

grafik

How should be different possible Packages for the same part be handled?
In this case there is also QFN64 possible
I could an Alias, the Footprint in the "Field" Section is set for the whole part (including the aliases).
Is there another possibility?

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @daviid5 , thanks for contributing,

A few comments I have during my review:

- [ ] Datasheet link is not correct, to be fixed, I have used `http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf` for the review
- [ ] Footprint filter should be `TQFP*10x10mm*P0.5mm*`
- [ ] As indicated page 35 of the datasheet, VDDCORE is Power Output

Else, good contribution!

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@daviid5 thanks for the fixes, still missing the fix of the datasheet link. Actually your link redirect to the microchip.com home page.

**Comment by myfreescalewebpage** [comment]
I'm speaking of the link in the library of course, not in the PR !

**Comment by myfreescalewebpage** [comment]
@daviid5 any news here ? Still missing fix of datasheet link. Thanks, Joel

**Comment by myfreescalewebpage** [comment]
@daviid5 ping :)

**Comment by daviid5** [comment]
@myfreescalewebpage 
In my opinion the datasheet link is fixed since the last commit
see:
https://github.com/KiCad/kicad-symbols/pull/1623/commits/be33614cee2127b18b2df57cb293e6d802110d43
datasheet link is: http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf
That one works for me

**Comment by myfreescalewebpage** [comment]
@daviid5 it works for the ATSAMD21G18A-AUT device but not for the others !
I also just realize you have a modification of the "MCU_Microchip_SAME.dcm" library that is not expected (a datasheet link !)
Please have a look at the git diff at https://github.com/KiCad/kicad-symbols/pull/1623/files
Cheers,
Joel

**Comment by daviid5** [comment]
@myfreescalewebpage 
Now I've got it.
I reverted the changes in the SAME Library now ;)

**Comment by myfreescalewebpage** [comment]
@daviid5 ok for SAME library, thanks.
However, the following devices have still a bad datasheet link: `ATSAMD21J15A-A`, `ATSAMD21J16A-A`, `ATSAMD21J17A-A`, `ATSAMD21J18A-A`
Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this PR is abandoned.

**Comment by daviid5** [comment]
@myfreescalewebpage 
sorry, had forgotten this PR, should be fixed now
github says there are 'conflicting files', but I don't understand the problem, could somebody help me out with this?

**Comment by myfreescalewebpage** [comment]
@daviid5 no worries. master branch on github has moved and you should now update your fork here to reflect the changes.

More help: https://github.com/KiCad/kicad-symbols/pull/145#issuecomment-356436694

**Comment by cpresser** [comment]
https://github.com/KiCad/kicad-symbols/pull/2336

**Comment by myfreescalewebpage** [comment]
Still need to update your fork, I'm not able to finalize the review actually.

**Comment by myfreescalewebpage** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by cpresser** [comment]
This is a duplicate of https://github.com/KiCad/kicad-symbols/pull/2336
I plan to merge #2336 soon. It is almost finished, is currently active and has a really good quality.

**Comment by myfreescalewebpage** [comment]
OK thanks @cpresser! Closing this issue.

**Pull request closed without merging**
