### PR TITLE
Added TSV524xIQ4T

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Quad op-amp in QFN-16 package
- Based symbol on existing quad op-amp
- Datasheet: https://www.st.com/content/ccc/resource/technical/document/datasheet/4a/50/94/16/69/af/4b/58/DM00047334.pdf/files/DM00047334.pdf/jcr:content/translations/en.DM00047334.pdf
- Footprint required here - https://github.com/KiCad/kicad-footprints/pull/1166

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @SchrodingersGat 

Some comment during my review:
- [ ] Datasheet link can be reduced to https://www.st.com/resource/en/datasheet/tsv521.pdf
- [ ] Pin 17 "PAD" should be called "EP" for consistency with other devices
- [ ] Unit E is very unusual design, we are used to put no box for op amp power supply, ins't it ?
- [ ] You are violating KLC S3.1
- [x] Violation of KLC S5.1 accepted till the merge of the footprint

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Footprint no longer pending. Re-triggering travis.

**Comment by poeschlr** [comment]
@antoniovazquezblanco you should be able to restart travis without needing to close and reopen the pull request. On the travis report page you can choose "login with github". As you are a member you should get a button for restarting travis on that page as soon as you are logged in.

**Comment by antoniovazquezblanco** [comment]
Sorry for the annoyance

**Comment by myfreescalewebpage** [comment]
@SchrodingersGat looks great, thanks. No more comments.

@antoniovazquezblanco this PR can now be merged according to me

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco up ?

**Pull request merged**
