### PR TITLE
Addition of LM5118 Buck Boost Controller

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of LM5118 Buck Boost Controller.

I've tried my best on the layout of the pins, aiming for the cleanest schematic, using the schematic on Page 24 of the datasheet as a guide. (This is why the VCC Pin is on the right)

Travis is also suggesting the VOUT terminal should be an OUTPUT - in this case it's a sense of the output, hence why it's a power input.

Datasheet Link: https://www.ti.com/lit/ds/symlink/lm5118.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jamesrlucas , thanks for contributing,

A few comments I have during my review:

- [ ] The package format is not correct in the description: `Wide Voltage Range Buck-Boost Controller, HTSSOP-20`
- [ ] The footprint should be `Package_SO:Texas_PWP0020A`
- [ ] The footprint filter will be `Texas*PWP0020A*`
- [ ] Pin length should be 100mil
- [ ] RAMP should be Passive
- [ ] VCC should be on the top
- [ ] Name of pin 21 should be EP and type should be Passive
- [ ] I would suggest to have pins position similar to the symbol on page 1 of the datasheet

Can you rebase your branch also ?

Cheers,
Joel

**Comment by jamesrlucas** [comment]
RIght, so I've updated the following: (This is one of my early commits - I should have updated this ages ago...)

- Fixed the package name in the description
- Updated the footprint & filter
- fixed the pin offset
- Fixed the pintype on RAMP
- Fixed the name & type of the thermal pad

As for the VCC pin being on top, and the pin layout, I've rearranged all the pins, aiming for the cleanest schematic look. I though it wasn't necessary for Power pins to be on the top of a symbol for voltage regulator devices? (Mentioned on another PR I submitted not so long ago [Here](https://github.com/KiCad/kicad-symbols/pull/2572))

Here is an example showing the new pin layout (trying to avoid too many crossed wires in a typical use case)

image

Apologies for the number of screw-ups on this one... I should have double checked my work here!

I've run `git rebase` but I'm not too clued up on git - I've only really started using it for the Kicad libraries. Is this to remove the conflicts?

**Comment by myfreescalewebpage** [comment]
"Is this to remove the conflicts?" Yes exactly.

**Comment by jamesrlucas** [comment]
Well, I got there in the end!

Sometimes you learn by fixing your own mistakes...

**Comment by myfreescalewebpage** [comment]
Ok with the current design, no more comment. Merging.

**Pull request merged**
