### PR TITLE
Addition - DMG2301L

### PR DESCRIPTION
**Pull request by gcormier**
Just another MOSFET, added an alias. **Please** double check my alias selection for pins/GDS.

image

image

https://www.diodes.com/assets/Datasheets/DMG2301L.pdf

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @gcormier , thanks for contributing,

A single comment I have during my review:

- [ ] Package name in the description should be simply "SOT-23", not "SOT-23-3"

Your alias is correct.

Cheers,
Joel

**Comment by gcormier** [comment]
51aaa93 should fix that up!

**Comment by myfreescalewebpage** [comment]
@gcormier good catch for the TP0610T package name, but your new symbol DMG2301L has still wrong package format :)

**Comment by gcormier** [comment]
Ahh gotcha. Okay, I updated all of them to SOT-23 which is the standard. Might as well clean them up.

**Comment by myfreescalewebpage** [comment]
Thanks! Merging

**Pull request merged**
