### PR TITLE
Add Potentiometer AD5254

### PR DESCRIPTION
**Pull request by asukiaaa**
Screenshot from 2019-10-20 20-53-32

datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/AD5253_5254.pdf

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Nice symbol, i like the graphics...
- [ ] but it has the American style resistors. All other digi-pots use a different style. See `MCP4251-xxxx-P`.
- [ ] Pin15 is called `DGND`
- [ ] I would prefer to have all potentiometer outputs on the right side, similar to `X9258`
- [ ] Please add `, TSSOP-20` to the description
- [ ] It would be nice to also have the alias for 64-position part

**Comment by asukiaaa** [comment]
Thank you for the feedback.

> but it has the American style resistors. All other digi-pots use a different style. See MCP4251-xxxx-P.
 Pin15 is called DGND
 I would prefer to have all potentiometer outputs on the right side, similar to X9258
 Please add , TSSOP-20 to the description

I updated about them.
Screenshot from 2019-11-05 20-15-02


> It would be nice to also have the alias for 64-position part

I'm not sure the expected values for alias.
Could you show some example?

**Comment by cpresser** [comment]
Thanks for you changes. Looking good.

If you want to add the alias, go to the alias-tab (press `+` on the bottom).
Like so:
image
The resulting diff might look like so: 
image

**Comment by asukiaaa** [comment]
Thank you for the explanation.
I understood about alias.
I add alias to AD5254 about AD5253 like this.
Screenshot from 2019-11-07 19-49-59

**Comment by asukiaaa** [comment]
Thank you for checking and merging.

**Pull request merged**
