### PR TITLE
Added FDMC8032L mosfet

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Datasheet: https://www.fairchildsemi.com/datasheets/FD/FDMC8032L.pdf

image

image

image

image

Footprint PR - https://github.com/KiCad/kicad-footprints/pull/975

### CODE REVIEW

**Comment by evanshultz** [comment]
There are now two S2 and two D1 pins.

**Comment by SchrodingersGat** [comment]
Good catch @evanshultz I had the "edit all units" button pressed by mistake..

**Comment by evanshultz** [comment]
Looks good now. Just waiting for the footprint to be merged.

**Comment by evanshultz** [comment]
And it is!

**Pull request merged**
