### PR TITLE
Added Microchip LAN7500

### PR DESCRIPTION
**Pull request by awjlogan**
Added Microchip LAN7500(i) USB 2.0 to 10/100/1000 Ethernet.

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/00001734B.pdf

Unit A: 
image

Unit B: 
image

Violations: none intentional

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] ~If there are matching footprint PRs, provide link(s) as appropriate~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by awjlogan** [comment]
Problem removing the old commits from previous - can try and sort out again if this is still a problem.

**Comment by cp-aquila** [comment]
Hi and thanks for your contribution.
This is not a full review, just stuff that is easily visible
* Remove the `I` part. Its a temperature-variant (S2.2)
* Pin43 name is wrong
* The symbols can be more compact. Spacing between pins in unitB should be 100mil
* Power-Pins should not get stacked if each of them requires a decoupling cap (S4.3, 2)
* `Etherbias` and `Usbbias` should be of type passive

**Comment by awjlogan** [comment]
Changes made, thank you! Should the other parts in this library, eg, LAN9512 be updated with the same, or are they retained for backward compatibility?

**Comment by cp-aquila** [comment]
> 
> 
> Changes made, thank you! Should the other parts in this library, eg, LAN9512 be updated with the same, or are they retained for backward compatibility?

No. Breaking changes are only allowed for a major release (upcoming 6.0).
If legacy symbols can be improved without breaking compatibility then changes are welcome and will be merged.

**Comment by awjlogan** [comment]
Problems with Git - removing this, and will reopen a clean PR.

**Pull request closed without merging**
