### PR TITLE
Add ICS525-01/-02 User configurable clock with pll

### PR DESCRIPTION
**Pull request by fhw72**
Added: ICS525-01RILF and ICS525R-02ILF
"User configurable clock" to Timer_PLL library.

Device is using standard SSOP-28 package.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] https://www.idt.com/document/dst/525-01-02-datasheet

ics525r-02ilf
ics525-01rilf

### CODE REVIEW

**Comment by fhw72** [comment]
Several version of the device exist. However all version without "I" (consumer temp. range) are marked obsolete (Last buy: mid 2019). Therefore I only created the two version with "I" (industrial) marking.

**Comment by myfreescalewebpage** [comment]
Hi @fhw72, thanks for contributing,

A few comments I have during my review:

- [ ] Regarding to the name, "LF" is Pb-Free which doesn't matter in the library, Temperature doesn't matter too. I would suggest that the part should be simply named "ICS525-01R" and "ICS525R-02".
- [ ] Description can include the frequency range for each device to make them different
- [ ] The two symbols are the same, isn't it ? Define only one and the second should be an alias.
- [ ] We don't put manufacturer in the keywords, maybe you can write `configurable clock`, that's a little bit redundant with the description but I do not know what we can indicate here...
- [ ] You have not selected the right footprint, it should be `Package_SO:SSOP-28_3.9x9.9mm_P0.635mm` (take care to the dimensions). Footprint filter to be modified too: `SSOP*3.9x9.9mm*P0.635mm*`.
- [ ] Pin length should be 100mil (symbol<100pins)
- [ ] You can order R0-R6, S0-S2, V0-V8 from up to bottom, I think its better
- [ ] GND pins should be stacked
- [ ] CLK and REF are Output, not Tri-State
- [ ] The symbol is globally very large, you can reduce the width.

Cheers,
Joel

**Comment by fhw72** [comment]
Hi Joel,
I've changed the symbol according to your review.
As you can see it's now less wide; I could even reduce a little bit more but readability gets worse then.
Cheers,
Frank

**Comment by fhw72** [comment]
Just a short question on top:

According to the manual both outputs are tri-stated when PD# (Pin19) is low.
Should they be "output" nonetheless? I'm not entirely sure.
Cheers,
Frank

**Comment by myfreescalewebpage** [comment]
> According to the manual both outputs are tri-stated when PD# (Pin19) is low.
Should they be "output" nonetheless? I'm not entirely sure.

Not seen this previously, yes keep Tri-State in this case.

**Comment by fhw72** [comment]
Done. Reverted back to tri-state.

**Comment by myfreescalewebpage** [comment]
Regarding to the stacking of the GND pin, you have a KCL error (see travis output), pin 20 should be Passive.

Else, everything is okay for me, great job !

Joel

**Comment by fhw72** [comment]
Cool... learning with every commit. Now I know how to stack pins correctly.
Cheers,
Frank

**Comment by myfreescalewebpage** [comment]
Thanks for being responsive ! No more comment to do on this PR, merging.

Joel

**Pull request merged**
