### PR TITLE
add lt1963eq (alias lt1963aeq)

### PR DESCRIPTION
**Pull request by aewallin**
LT1963EQ and LT1963AEQ adjustable 1.5A voltage regulators in in TO-263-5 package.

Datasheets
https://www.analog.com/media/en/technical-documentation/data-sheets/1963fc.pdf
https://www.analog.com/media/en/technical-documentation/data-sheets/1963aff.pdf

Screenshot (symbol based on existing LT1962)
lt1963

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
Note that the screenshot is out-of-date! I made the symbol more compact!

**Comment by myfreescalewebpage** [comment]
To be treated according to #1171

**Comment by myfreescalewebpage** [comment]
@aewallin can you fix the footprint filter to `TO?263?5*` ?

**Comment by DanSGiesbrecht** [comment]
Referencing @evanshultz's comment from https://github.com/KiCad/kicad-symbols/pull/1171:
> Footprint filters should not have pin count, so don't include the ?5 part. Furthermore, use asterisks instead of question makes wherever possible and that applies to all instances here.

**Comment by myfreescalewebpage** [comment]
@DanSGiesbrecht and @aewallin yes the footprint of this PR should be changed to `TO*263*`, not `TO?263?5*`.

**Comment by myfreescalewebpage** [comment]
@aewallin great, this sounds good !

@antoniovazquezblanco according to me this PR is ready to be merged

Cheers,
Joel

**Comment by aewallin** [comment]
after changes:
lt1963eq

**Comment by myfreescalewebpage** [comment]
@aewallin great, thanks

@antoniovazquezblanco PR ready to be merged according to me

**Comment by antoniovazquezblanco** [comment]
One less to go. Thanks!

**Pull request merged**
