### PR TITLE
Removed obsolete RF9394/5M

### PR DESCRIPTION
**Pull request by marecl**
Separated IRF9394M (and its alias IRF9395M) into two separate parts.
Part A:
image
Part B:
image

It's linked to a footprint DirectFET_MC_DOUBLE (PR in a few minutes)

[edit] 
New footprint:
image

https://github.com/KiCad/kicad-footprints/pull/2411

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by marecl** [comment]
Fix for #2925

**Comment by marecl** [comment]
Travis will obviously fail because the proper footprint is in a different repo : P
https://github.com/KiCad/kicad-footprints/pull/2411

**Comment by cpresser** [comment]
TBH, I would remove this device and the footprint completely.
As @chschlue pointed out it is an obsolete part. I could not find a place where one can buy it. It is not on octopart. And I don't see any 'retro-value' for a P-Fet.

**Comment by chschlue** [comment]
Plus, we would need to work around the duplicate drain pin on both units.
(Unit C containing a floating drain, analogous to separate power units?)

**Comment by marecl** [comment]
Fair enough. I can *again* rename the pr and remove the part. as well as close https://github.com/KiCad/kicad-footprints/pull/2411
You call the shots here @cpresser :D

**Comment by cpresser** [comment]
Yep, please remove the part.
Also, remove the footprint. It is not used for something else. If we want it back, there is a git history.

**Comment by myfreescalewebpage** [comment]
No comment to add. Milestone v6.

**Pull request merged**
