### PR TITLE
Added diode MBRA340 as aliases to the existing B120-E3 symbol

### PR DESCRIPTION
**Pull request by Trubochkin**
- Added diode MBRA340 as aliases to the existing B120-E3 symbol

- Datasheet: https://www.onsemi.com/pub/Collateral/MBRA340T3-D.PDF

- Fotprint: https://github.com/KiCad/kicad-footprints/blob/master/Diode_SMD.pretty/D_SMA.kicad_mod

- Screenshot: 
SharedScreenshot

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
We don't accept automotive-qualified parts, so can you please remove the NRV* prefix symbol? What is unique about the SBRA part?

I believe whatever diodes you end up adding can be an ALIAS to the existing `B120-E3` symbol. Please confirm and make that change if you agree.

**Comment by poeschlr** [comment]
Clarification of:
> We don't accept automotive-qualified parts, so can you please remove the NRV* prefix symbol?

It is not that we do not accept symbols for such parts. It is that we do not include this qualifier in the part name. (It is a non functional qualifier. To avoid ballooning the lib such qualifiers are left out if they are at the end of the part number or replaced with wildcard "x" if in the middle.)

**Comment by Trubochkin** [comment]
> We don't accept automotive-qualified parts, so can you please remove the NRV* prefix symbol? What is unique about the SBRA part?
> 
> I believe whatever diodes you end up adding can be an ALIAS to the existing `B120-E3` symbol. Please confirm and make that change if you agree.

Done

**Comment by evanshultz** [comment]
This is good now. Thanks!

@poeschlr 
Appreciate the extra clarity where I didn't do a great job of explaining.

**Pull request merged**
