### PR TITLE
Add NC7SVU04P5X.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://www.onsemi.com/pub/Collateral/NC7SVU04-D.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh 

Few comments:

- [ ] Description should end with the package name, please add `, SOT-353`
- [ ] VCC is pin 6 (missing) while pin 5 is NC
- [ ] I wonder if the design should be done with 2 units, one for the inverter, the other one for the power pins, like 74LS04 for example (even if there is only one gate), what do you think ? it's probably better in a schematic...

Cheers,
Joel

**Comment by evanshultz** [comment]
Single-gate logic symbols have power pins on a single unit, at least for now. See https://github.com/KiCad/kicad-symbols/issues/190 for the backstory.

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks, I was trying to found other examples :)

**Comment by myfreescalewebpage** [comment]
@matthuszagh sorry, have not looked at the right package !

**Comment by myfreescalewebpage** [comment]
Merging.

**Pull request merged**
