### PR TITLE
Add LTC4412

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/4412fb.pdf

Symbol:
ltc4412

Don't know if the name is the right, exists various versions because of temperature range

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] Package in the description is not correct, should be "TSOT-23-6"

Else, no comment.

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage Have made the change you requested

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
