### PR TITLE
new symbol: VCXO Abracon Ablno

### PR DESCRIPTION
**Pull request by aewallin**
Abracon VCXO ABLNO

datasheet: https://abracon.com/Precisiontiming/ABLNO.pdf

Screenshot:
vcxo_abracon_ablno

footprint PR merged: https://github.com/KiCad/kicad-footprints/pull/1110

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
footprint PR: https://github.com/KiCad/kicad-footprints/pull/1110

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

Good to see you have made consistency with #1199. Few comments:

- [ ] Part name is very long for no reason. I would suggest "ABLNO".
- [ ] You are violating KLC S3.2 because you have reduce etxt size of the pin. Should be 50mil. I suggest to reduce pin 1 name to "Vctrl" to get 50mil text but with enough space to keep the symbol clear. Example below, let me known.

capture

Else, no more comment to do. Footprint has been merged so no need to wait for it.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Footprint has been merged

**Comment by myfreescalewebpage** [comment]
Thanks @aewallin, no more comment to do, merging.

Joel

**Pull request merged**
