### PR TITLE
Add ublox lea series

### PR DESCRIPTION
**Pull request by jneiva08**
LEA M8S
Datasheet: https://www.u-blox.com/sites/default/files/LEA-M8S-M8T-FW3_HardwareIntegrationManual_%28UBX-15030060%29.pdf

lea_m8s

LEA M8F
Datasheet: https://www.u-blox.com/sites/default/files/products/documents/LEA-M8F_HIM_%28UBX-14000034%29.pdf

lea_m8f

LEA M8T
Datasheet: https://www.u-blox.com/sites/default/files/LEA-M8S-M8T-FW3_HardwareIntegrationManual_%28UBX-15030060%29.pdf

lea_m8t

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
update symbol of LEA_M8F

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08, thanks for contributing,

A few comments I have during my review, basically the same already discussed on https://github.com/KiCad/kicad-symbols/pull/1097:

- [ ] Indicate the datasheet in datasheet field, not the hardware reference manual (https://www.u-blox.com/sites/default/files/LEA-M8S-FW3_DataSheet_%28UBX-16010205%29.pdf, https://www.u-blox.com/sites/default/files/products/documents/LEA-M8F_DataSheet_%28UBX-14001772%29.pdf and https://www.u-blox.com/sites/default/files/NEO-LEA-M8T-FW3_DataSheet_%28UBX-15025193%29.pdf respectively).
- [ ] Fix part names without manufacturer inside, i.e. "LEA-M8S" instead of "ublox_LEA-M8S", etc. I know other parts include manufacturer in the name but they should not.
- [ ] SCL is indicated Bidirectional at the beginning of the datasheet, but it also indicates DDC interface is slave only, so SCL is an Input only. I would suggest to modify the type to Input.
- [ ] According to the datasheet RESET should be called RESET_N.
- [ ] According to the datasheet SAFEBOOT should be called SAFEBOOT_N.
- [ ] According to the datasheet SAFEBOOT_N is an Input, not a Bidirectional pin.
- [ ] According to the datasheet VCC_RF is a Power Output, not an Output.
- [ ] According to the datasheet V_ANT is a Power Input, not an Input. KLC S4.2 indicates it should be placed on the top of the symbol. I will suggest to move V_ANT on the top and to switch RF_IN and VCC_RF so it is possible to wire VCC_RF to V_ANT easily).
- [ ] KLC S4.2 also recommend to put Inputs on the left so I will suggest to move DSEL / EXTINT0 / EXTINT1 / FREQ_PHASE_IN0 / FREQ_PHASE_IN1 / SAFEBOOT_N and RESET_N on the left of the symbol.
- [ ] To be conformed with your MAX-8 series, I would also suggest to arrange positive power pins on the top of the symbol in this order : VCC, VDD_USB, V_BCKP, VCC_OUT, V_ANT.

LEA-M8F only:
- [ ] According to the datasheet SDA/CS_N should be called SDA2/SPI_CS_N.
- [ ] According to the datasheet SCL/SCLK should be called SCL2/SPI_CLK.
- [ ] According to the datasheet TxD1/MISO/Tx_ready should be called TxD1/SPI_MISO.
- [ ] According to the datasheet RxD1/MOSI should be called RxD1/SPI_MOSI.
- [ ] According to the datasheet FREQ_PHASE_IN1/EXTINT1 should be called FREQ_PHASE_IN1.
- [ ] According to the datasheet FREQ_PHASE_IN0/EXTINT0 should be called FREQ_PHASE_IN0.
- [ ] According to the datasheet TIMEPULSE/TP2/SAFEBOOT should be called TIMEPULSE/TP2/SAFEBOOT_N.
- [ ] According to the datasheet REF_FREQ_OUT is an Output, not an Input pin.
- [ ] VCC_OUT (pin 8) is missing

LEA-M8T only:
- [ ] According to the datasheet SDA/SPI_CS should be called SDA/SPI_CS_N.
- [ ] According to the datasheet TP2/SAFEBOOT should be called TP2/SAFEBOOT_N.

After process, can you post again the screenshots of the devices please ?

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@jneiva08 up ?

**Comment by jneiva08** [comment]
The symbols looks like this:

LEA-M8F
m8f

LEA-M8S
m8s

LEA-M8T
m8t

**Comment by jneiva08** [comment]
@myfreescalewebpage hope i didn't forgot anything

**Comment by myfreescalewebpage** [comment]
Hello @jneiva08 

Sorry for the long delay. Thanks for all these modifications, great job !!
I have no comment to do on these symbols, merging.

Cheers,
Joel

**Pull request merged**
