### PR TITLE
Amplifier_Audio: add MAX9715

### PR DESCRIPTION
**Pull request by zonque**
2.8W, Low-EMI, Stereo, Filterless Class D Audio Amplifier, TQFN-16

The datasheet is here:

  https://datasheets.maximintegrated.com/en/ds/MAX9715.pdf

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)

image

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Change the footprint filter to `TQFN*1EP*5x5mm*P0.8mm*` (remove pin count and EP size).
1. Let's make BIAS Passive type.
1. Space apart the left side pins to three groups: audio in, config, and bias cap.

Please don't force push further commits to it's easier to review. Thanks!

**Comment by zonque** [comment]
Thanks for the review. All done.

**Comment by zonque** [comment]
image

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
