### PR TITLE
Add IS31AP4991 audio power amplifier

### PR DESCRIPTION
**Pull request by vsergeev**
Add IS31AP4991 audio power amplifier

Datasheet: http://www.issi.com/WW/pdf/31AP4991.pdf

sop8

msop8

The symbol was drawn to match the datasheet and in the style of PAM8302. Symbols for both SOP-8 and MSOP-8 are included.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] (N/A) If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] (N/A) Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @vsergeev , thank you for your first contribution.
I will have to ask for guidelines from @cpresser ,( i would like to ask for a quick view of this review. I have some points that i need assistance.) as we get through this, since this is also my first official review.

I noticed in the datasheet(DS):
εικόνα
so i think it is wise to propose active low pin declaration, right?

One more thing i need guidance is that force-push. I remember i read somewhere that should be avoided. I do need some input about that.

Also needed some info here. Most amps from library have this form:
εικόνα

This rectangular form presented looks good to me but i need confirmation for an appropriate comment.

Comments:

- [ ] Symbol names should be `IS31AP4991-GRLS2` and `IS31AP4991-SLS2`

`-TR `should be ommited since (i think it is reel packaging relevant) it does not provide useful info (codemarks for reel/tray/tube packaging purposes and temperature related stuff for example are ommited too)

- [ ] Make SDB active low by using `~` as a pin name prefix

As stated from DS screenshot.

- [ ] Dimmensions can be reduced by at least 200mil on both axes. (This might be applied if rectangular form is acceptable, else you might need to convert to amp-generic symbol)
εικόνα

screenshot from 100mil grid.

- [ ] Pins to be moved according to previous screenshot.

I think it keeps a consistency with some similar parts from the lib.

- [ ] Pin name offset must be 0.508 mm
εικόνα

- [ ] For description i would suggest something like `1.2W, 2.7-5.5V, Audio Power Amplifier, Active-Low Standby, SOP-8`

In order to reduce extra words and add some functional info.

- [ ] Keywords i think it is better as `ultra low consumption distortion`

For keywords it is better not to include words from description.

- [ ] Previous comments also aply for both symbols. Logic is the same between both.

Thank you for your time,
Aris.

**Comment by aris-kimi** [comment]
Hi @cpresser , quetion, if author does not respond, is it considered as a good move to edit (his)files (me for example) and ask for review and merge from other librarian?

**Comment by vsergeev** [comment]
@aris-kimi, thanks for your review and sorry about the delay in response. I'll push up the changes tonight.

**Comment by cpresser** [comment]
> Hi @cpresser , quetion, if author does not respond, is it considered as a good move to edit (his)files (me for example) and ask for review and merge from other librarian?

No. At least not after such a 'short' amount of time. The KiCad repos are slow. More than 4 Weeks of inactivity are quite common.

The usual approach would be to mark the original PR as abandoned. Then create your own PR with the 're-push' label and link to the old one.

**Comment by aris-kimi** [comment]
Thank you. Informative mostly. I do understand that this is everyone's spare time and under any circumstances i will never try to "push" someone to" work faster". I thought i should have asked this though.

**Comment by vsergeev** [comment]
* [x] Symbol names should be IS31AP4991-GRLS2 and IS31AP4991-SLS2
`* e22af57e Amplifer_Audio: IS31AP4991-{GRL,S}LS2: Remove packaging code from symbol names`

* [x] For description i would suggest something like `1.2W, 2.7-5.5V, Audio Power Amplifier, Active-Low Standby, SOP-8`
`* 4dac12f1 Amplifer_Audio: IS31AP4991-{GRL,S}LS2: Improve part description`

* [x] Keywords i think it is better as `ultra low consumption distortion`
`* 690c07b5 Amplifer_Audio: IS31AP4991-{GRL,S}LS2: Improve part keywords`

* [x] Make SDB active low by using ~ as a pin name prefix
`* 66fe29cd Amplifer_Audio: IS31AP4991-{GRL,S}LS2: Make SDB pin name active low`

* [x] Pin name offset must be 0.508 mm
`* b8fd5d3c Amplifer_Audio: IS31AP4991-{GRL,S}LS2: Change pin name offset to 0.508mm`

* [x] Symbol should change to triangle-style like LM4990
`* e66961bb Amplifer_Audio: IS31AP4991-{GRL,S}LS2: Change symbol to triangle style`
Note: I had to change the pin name offset to 0.127mm (consistent with LM4990MM) to make the pin names readable.

* [x] Previous comments also aply for both symbols. Logic is the same between both.

is31ap4991-grls2-triangle

is31ap4991-sls2-triangle

My only concern with the triangle symbol is that the output pins are missing the OUT+ and OUT- annotations, which are important for configuring the negative feedback of the amplifier. I tried adding `+` and `-` labels but they look bad with this symbol design.

**Comment by chschlue** [comment]
You could add them as graphic lines somwhere at the tip.

**Comment by vsergeev** [comment]
OK, I added the polarity markings with graphic lines.

`Amplifer_Audio: IS31AP4991-{GR,S}LS2: Add output pin polarity markings`

is31ap4991-grls2-triangle

is31ap4991-sls2-triangle

**Comment by aris-kimi** [comment]
I believe the reason behind the existance of rectangular shaped amps was KLC violations.

I think we are good with current violations in order to try to keep consistency

εικόνα

On both parts names are not as in ds, also name offset 0.127mm

εικόνα

@cpresser @chschlue do you agree?

KLC output:
εικόνα


@vsergeev thank you for appling changes as asked,
one last change after confirmation of the above and this will be ready.

- [ ]  Part `IS31AP4991-SLS2` description must ends to` MSOP-8` instead of `SOP-8`

**Comment by chschlue** [comment]
@aris-kimi Not sure what the question is.

**Comment by vsergeev** [comment]
@aris-kimi 

* On both parts names are not as in ds, also name offset 0.127mm

Assuming you mean pin names. Yeah, I couldn't fit VCC without the text overlapping with GND. BYPASS barely fits, but it is pretty close to ~SDB. I left the LM4990MM ones for now.

* [x]  Part IS31AP4991-SLS2 description must ends to MSOP-8 instead of SOP-8

Whoops, sorry about that. Good catch.

`* 3269f87f Amplifier_Audio: IS31AP4991-SLS2: Fix package in part description`

**Comment by aris-kimi** [comment]
@vsergeev , i am terribly sorry. I have to ask you to change outputs once again, negative is on top on other symbols, and i just noticed that. Please apply that last change and i am merging.

**Comment by vsergeev** [comment]
@aris-kimi the negative output should be on the same side of the symbol as the negative input -- otherwise it's not possible to wire the feedback (e.g. like an inverting amplifier) without crossing nets.

**Comment by chschlue** [comment]
@aris-kimi Yes

**Comment by vsergeev** [comment]
@aris-kimi so should I put swap the inputs and outputs so both negative input and output are on the top? This would be a departure from LM4990MM.

**Comment by aris-kimi** [comment]
Thank you @vsergeev , i am ok with this.(No do not swap). I am just thinking that something needs to be done with current dual output symbols.
Do you have the time/want to fix them in a seperate PR?

I will merge this i think we are good.
Thank you for your time spent here.

**Pull request merged**
