### PR TITLE
Powerint

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR moves across the powerint lib

There is one set of components that I have not idea what to do with (see CAP002DG etc in legacy/powerint.lib)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
All the KLC errors here are relating to the lack of footprints...

**Comment by jkriege2** [comment]
Maybe put all the `CapZero Automatic Capacitor Discarger` into Analog.lib for now ... @poeschlr @evanshultz Any ideas on where to put these?

**Comment by poeschlr** [comment]
I have no better idea.

**Comment by SchrodingersGat** [comment]
Can we merge this and fix the parts in legacy/ at a later stage?

**Comment by jkriege2** [comment]
Hi!

I'm currently adding the missing footprints and will do (most of) the remaining fixes for the powerint parts!

cu
JAN

**Comment by jkriege2** [comment]
OK, I completed this PR in
- https://github.com/KiCad/kicad-symbols/pull/104
- https://github.com/KiCad/kicad-footprints/pull/194

Can someone have a look? Thanks,
JAN

**Pull request merged**
