### PR TITLE
Add symbols for connectors with mounting pins.

### PR DESCRIPTION
**Pull request by poeschlr**
As discussed in https://github.com/KiCad/kicad-footprints/issues/117

Script: https://github.com/KiCad/kicad-library-utils/pull/210

@Shackmeister here the symbols i promised you over on the forum.

I am not sure if my symbolic for mounting pins is any good.

screenshot from 2018-02-10 00-36-04

### CODE REVIEW

**Comment by evanshultz** [comment]
The MP pin design looks like a screw terminal to me.

**Comment by poeschlr** [comment]
That was kind of my inspiration. Screws are normally used to mount things.

**Comment by jkriege2** [comment]
Maybe we can have a pin-label "mounting" in 20mil or 10mil text next to the MP-pin? This should make it clearer!

**Comment by Shackmeister** [comment]
just pitching ideas here
mounting_pins

**Comment by poeschlr** [comment]
@Shackmeister i like that design. Will look into it later this week.

**Comment by Shackmeister** [comment]
Let's just hope nobody mistakes it for a capacitive coupled shield :p

**Comment by poeschlr** [comment]
I combined both your suggestions:
screenshot from 2018-02-21 23-43-46

**Comment by poeschlr** [comment]
@Shackmeister you wanted these. It might be time to take a look at it.

**Comment by evanshultz** [comment]
@poeschlr 
Can you fix branch conflicts?

@Shackmeister 
Can you review once that's done?

**Comment by Shackmeister** [comment]
I really like the look of the symbols, to be honest I dont know too much about the FP filter etc so can someone else check that part?

**Comment by poeschlr** [comment]
The merge is required because i accidentally added changes that where intended for another pull request. I will try to reset this in this PR but if i fail i will close it and make a new PR.

**Comment by poeschlr** [comment]
@Shackmeister this PR would require the footprint changes you promised. Without the changed footprints this is kind of useless.

**Comment by Shackmeister** [comment]
@poeschlr I know, im currently working on the footprints and was not intending to merge this until the footprints are ready

**Comment by poeschlr** [comment]
Replaced by https://github.com/KiCad/kicad-symbols/pull/372 (I could not figure out how to revert the changes to the connector_specialized lib without major hacks.)

**Pull request closed without merging**
