### PR TITLE
Fix 74LS24[014]

### LINKED ISSUE #2668: 74LS241 incorrect gate symbol on pin 19 / OEb
The default library has an inverted input for both output enable pins (1 / OEa and 2 / OEb), however in the '241 only OEa is inverted.

Refer to section 8.2 on the datasheet: http://www.ti.com/lit/ds/symlink/sn74ls241.pdf

This was an easy fix for me, just passing along so it can make its way into the official library someday.

### PR DESCRIPTION
**Pull request by chschlue**
fixes #2668

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by evanshultz** [comment]
Could you make the descriptions be unique so '240, '241, and '244 are more easily differentiated?

**Comment by chschlue** [comment]
Done

**Comment by evanshultz** [comment]
This violates https://kicad-pcb.org/libraries/klc/S4.7/ as there should be an overbar and not the 'bubble' pin style. However, with this library being in the state it is this KLC violation doesn't really make a difference so I'll merge. Thanks!

**Comment by chschlue** [comment]
Yes, I figured any clear indication of inversion is better than a wrong one.

**Pull request merged**
