### PR TITLE
Added FXMA108BQX bidirectional level shifter

### PR DESCRIPTION
**Pull request by awygle**
Added FXMA108BQX bidirectional level shifter from ON Semi

Datasheet: http://www.onsemi.com/pub/Collateral/FXMA108-D.pdf
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/477

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Pin 21 is a NC pin, make it invisible and place the "x" on the edge of the symbol.
Pin 11 should not really be placed on the bottom.

I suggest the following
Place pin 21 on the right side
Place pin 11 where pin 21 is now (upper left)

If you want, you can move pin 1 one step to the right got more space in the upper left corner.
Or you can change the "pin text offset" to 20 to squeeze it little more.
bild

**Comment by awygle** [comment]
Made these changes, also fixed a name/pin number mixup on NC and OE.

**Comment by awygle** [comment]
Pin name position offset changed to 20mil.

**Comment by awygle** [comment]
Is there anything else you would like me to do for this PR?

**Comment by evanshultz** [comment]
- I think the suffix `BQX` isn't need since this part only comes in a single package.
- It seems this symbol is a bit overly tall (from the screenshot above). Can it be shrunk?
- The datasheet calls the package `DQFN` but the product page and footprint are named `WQFN`. Why?
- Use the PDF datasheet for the documentation link. It is `http://www.onsemi.com/pub/Collateral/FXMA108-D.pdf`.
- The footprint assigned to this symbol does not match the footprint name that was merged.

It is easier for librarians if you do incremental changes instead of overwriting with each commit.

**Comment by whitequark** [comment]
@evanshultz The manufacturer can't make up their mind as to how the package is called. Datasheet:
screenshot_20180417_013209
Package drawing:
screenshot_20180417_013233

**Comment by evanshultz** [comment]
Yes, I noticed that and found it awkward. I've asked ON Semi for clarification. If you make the rest of the changes we should be very close to merging. Thanks!

**Comment by evanshultz** [comment]
I should be called WQFN. Fairchild had different names, but now that this is an On Semi part the nomenclature is WQFN. So we'll use that term and I believe all info to finish off this symbol is now known.

**Comment by whitequark** [comment]
> It seems this symbol is a bit overly tall (from the screenshot above). Can it be shrunk?

Cannot. This is what happens:

```
Checking symbol 'FXMA108':
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin VCCA (1), @ (-100, 650)mil
     - Pin GND (10), @ (0, -650)mil
     - Pin VCCB (20), @ (100, 650)mil
     - Pin NC (21), @ (100, -550)mil
```

**Comment by whitequark** [comment]
Addressed all comments other than shrinking the package for the reason stated above.

**Comment by evanshultz** [comment]
Thanks for making all the fixes! None of the CI issues are related to this symbol.

Looks like it can be shrunk to me without errors (perhaps you were moving the pins only 50mil when 100mil would still be OK?):
image

```
# FXMA108
#
DEF FXMA108 U 0 20 Y Y 1 F N
F0 "U" -250 550 50 H V C CNN
F1 "FXMA108" 300 550 50 H V C CNN
F2 "Package_DFN_QFN:WQFN-20-1EP_2.5x4.5mm_P0.5mm_EP1x2.9mm" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 WQFN*2.5x4.5mm*P0.5mm*EP1x2.9mm*
$ENDFPLIST
DRAW
S -300 500 300 -500 1 1 10 f
X VCCA 1 -100 600 100 D 50 50 1 1 W
X GND 10 0 -600 100 U 50 50 1 1 W
X ~OE 11 -400 400 100 R 50 50 1 1 I
X B8 12 400 -400 100 L 50 50 1 1 B
X B7 13 400 -300 100 L 50 50 1 1 B
X B6 14 400 -200 100 L 50 50 1 1 B
X B5 15 400 -100 100 L 50 50 1 1 B
X B4 16 400 0 100 L 50 50 1 1 B
X B3 17 400 100 100 L 50 50 1 1 B
X B2 18 400 200 100 L 50 50 1 1 B
X B1 19 400 300 100 L 50 50 1 1 B
X A1 2 -400 300 100 R 50 50 1 1 B
X VCCB 20 100 600 100 D 50 50 1 1 W
X NC 21 100 -500 100 U 50 50 1 1 N N
X A2 3 -400 200 100 R 50 50 1 1 B
X A3 4 -400 100 100 R 50 50 1 1 B
X A4 5 -400 0 100 R 50 50 1 1 B
X A5 6 -400 -100 100 R 50 50 1 1 B
X A6 7 -400 -200 100 R 50 50 1 1 B
X A7 8 -400 -300 100 R 50 50 1 1 B
X A8 9 -400 -400 100 R 50 50 1 1 B
ENDDRAW
ENDDEF
#
```
@awygle @whitequark 
Are these accounts for the same person?

@Misca1234 
If you have any other input please jump in. Otherwise I'll merge this when it's ready.

**Comment by whitequark** [comment]
@evanshultz No, we're different people, working on the same board.

**Comment by evanshultz** [comment]
If you can shrink this symbol then I think it's ready to merge.

@whitequark 
Ahh. OK.

**Comment by whitequark** [comment]
Done, and Travis is happy with the FXMA108.

**Comment by evanshultz** [comment]
Thanks! It would be nice if the ref des and PN were just above the symbol instead of 50 mil above it. A Y location of 550mil instead of 600mil will work. Are you willing to change that?

**Comment by evanshultz** [comment]
Thank you! You two have made some great contributions lately and I grateful for the time you've spent to help expand and improve the KiCad libraries. I hope you will keep it up!

**Pull request merged**
