### PR TITLE
Added Vishay oled 128x64 symbol

### PR DESCRIPTION
**Pull request by kajusK**
Datasheet: https://www.vishay.com/docs/37902/oled128o064dbpp3n00000.pdf
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1789

2019-08-25-164257_1920x1080_scrot

### CODE REVIEW

**Comment by kajusK** [comment]
Regarding the failed checks:

S4.6 pins 1 and 30 should be not connected instead of passive. Well, these pins are used to improve mechanical characteristics of the soldered display flex cable, should be connected to GND according to the datasheet. But these pins serve no electrical purpose. Passive makes sense to me here...

**Comment by chschlue** [comment]
The datasheet says **must** be connected to GND.
Perhaps better use their alternative name GND, set one as power input stacked with the other one as passive?

**Comment by myfreescalewebpage** [comment]
Hi @kajusK , thanks for contributing,

A few comments I have during my review:

- [ ] Pins 2 to 5 should be Passive
- [ ] Should use capital letters for pin name
- [ ] IREF and VCOMH should be Passive

Cheers,
Joel

**Comment by kajusK** [comment]
@myfreescalewebpage 

Thank you for the review, updated as requested

**Comment by myfreescalewebpage** [comment]
Hi @kajusK thanks for the quick fixes.
Regarding the first comment, "Pins 2 TO 5 should be Passive", you only have changed pins 2 and 5 but I was expecting pins 3 and 4 too.
Joel

**Comment by kajusK** [comment]
@myfreescalewebpage oops, sorry, fixed

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by kajusK** [comment]
The footprint was merged.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Pull request merged**
