### PR TITLE
Added SM712 and SD-C series TVS diodes

### PR DESCRIPTION
**Pull request by chschlue**
Added SM712 and SD-C series TVS diodes
SM712_SOT23
SD05_SOD323
https://www.littelfuse.com/~/media/electronics/datasheets/tvs_diode_arrays/littelfuse_tvs_diode_array_sm712_datasheet.pdf.pdf
https://www.littelfuse.com/~/media/electronics/datasheets/tvs_diode_arrays/littelfuse_tvs_diode_array_sd_c_datasheet.pdf.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
Violating S3.1: Same with generic symbol, presumably with good reason.
Violating S5.[12]: Not sure how to match packages correctly using only * and ? wildcards.

**Comment by myfreescalewebpage** [comment]
Hi @chschlue , thanks for contributing,

A few comments I have during my review:

SDxx series:
- [ ] I suggest to have the right names for the symbols: "SD05C-01FT", "SD12C-01FT", etc. No need to have the package in the name here.

SM712_SOT23:
- [ ] Same comment: "SM712-02H" is great

Else no comment to do.

Cheers,
Joel

**Comment by chschlue** [comment]
Thanks for the review, I almost forgot about this PR.

These are also manufactured by Bourns and ON (possibly more), which use different suffixes. That's why I used `_package` as per [S2.1](https://kicad-pcb.org/libraries/klc/S2.1/)

**Comment by myfreescalewebpage** [comment]
I wasn't aware of the availability at other manufacturers. In this case OK.
No more comment to do, merging.

**Pull request merged**
