### PR TITLE
Fix pins for ADT1.5-1

### LINKED ISSUE #2343: ADT1.5-1 wrong pin assignment
ADT1.5-1 which is an alias of ADT1-1WT has different CT and NC pins  
ADT1.5-1 has pin 2 as secondary CT and pin 5 not connected

### PR DESCRIPTION
**Pull request by drid**
ADT1.5-1 which is an alias of ADT1-1WT has different CT and NC pins  
ADT1.5-1 has pin 2 as secondary CT and pin 5 not connected
Fixes #2343
image
image

https://www.minicircuits.com/pdfs/ADT1.5-1+.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@drid 
Sorry for this mistake and thanks for reporting it.

We also need to reference https://www.minicircuits.com/pdfs/ADT1-1WT.pdf to check this.

I see the pin table is different so they can't be the same symbol.
ADT1-1WT:
image

ADT1.5-1+:
image

But there are no dots so we can't fully check this. You will need to add dots to both symbols to fully verify them. Can you please do that?

Here is the referenced footprint:
image

**Comment by drid** [comment]
Is something like 
image
 ok or should i use the inverted style on pins?

**Comment by drid** [comment]
or even better
image

**Comment by evanshultz** [comment]
@drid 
The symbol needs the NC pin, pin 5, added so the pin count filter in CvPcb works. Can you please add it? And I believe this is also missing from the `ADT1-1WT` symbol. Then I think this is good.

Sorry for the long, long delay. And thank you for fixing this!

**Comment by drid** [comment]
Added NC pin 5.
There seems to be some inconsistencies with ADT1-1WT aliases and CT pins.
I think i'll do a separate MR for these

**Comment by evanshultz** [comment]
Thanks!

ADT1.5-1 looks great now, but there is one visual thing: Please push the NC pin a bit right so it's under the part symbol and thus not easy to accidentally connect. It could be at [-100,0] or even [0,0]. Also, please make that pin 100mil long.

In addition, ADT-1AT touched in this PR and it's not right:
image

Pin 2 should be the secondary CT. See https://www.minicircuits.com/pdfs/ADT1-1WT.pdf. And there's no NC pin. It was wrong before but I hesitate to merge this when I still see problems in a symbol that was modified. Would you mind correcting it too?

Lastly, it's easier to incrementally review if you don't force push. Thank you.

**Comment by drid** [comment]
It looks like ADT1-1WT is wrong regarding pin 2/5 but all its aliases are correct.
So ADT1-1WT should be an alias of ADT1.5-1

**Comment by evanshultz** [comment]
I didn't check all the ALIASes, but if so then yes, we needs a new symbol. It's not required to merge this PR since it's fixing another symbol, but if you are willing to do it that would be great.

BTW, I'm not sure about all the ALIASes but I looked at the first one, https://www.minicircuits.com/pdfs/ADT1-1WT-1.pdf, and it doesn't match the screenshot I posted above. Pin 4 should be the dot on that part.

**Comment by drid** [comment]
I checked all the aliases and it they have to be split into 3 parts if we want to be precise.
I'll do that now

**Comment by drid** [comment]
image
image image

**Comment by evanshultz** [comment]
Thank you! I verified the pinout of all parts and it looks good to me too.

Only one small thing: NC pins on `ADT1-1WT-1` and `ADT1.5-1` aren't named `NC`. That will match the other symbols.

**Comment by drid** [comment]
Just to clarify, NC pins should me named NC or ~ ?

**Comment by evanshultz** [comment]
Normally we name them `NC`. However, there's no rule that I know of. And I just looked at https://kicad-pcb.org/libraries/klc/S4.4/ and the next few KLC clauses and don't see anything. So I will merge them with a tilde.

Thank you so much for fixing so many things, and sticking with this PR to get it finished even after I dropped the ball!

**Pull request merged**
