### PR TITLE
Add Conn_ST_STDC14 (STM32 debug connector, compatible with ARM debug conn.)

### PR DESCRIPTION
**Pull request by diegoherranz**
https://www.st.com/content/ccc/resource/technical/document/user_manual/group1/99/49/91/b6/b2/3a/46/e5/DM00526767/files/DM00526767.pdf/jcr:content/translations/en.DM00526767.pdf (see table 7 on page 22).

14-pin connector debug connector. Started from Conn_ARM_JTAG_SWD_10.

Middle 10 pins are the same as ARM Cortex debug connector (except key),
so it is completely compatible with existing cables, connectors, etc.

Extra connections for UART.

`T_` prefix removed from pin names because in my opinion, doesn't add much value,
are harder to read and the symbol would have to be bigger.

stdc14

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
By the way, this connector is used on the [STLINK-V3SET](https://www.st.com/content/ccc/resource/technical/document/user_manual/group1/99/49/91/b6/b2/3a/46/e5/DM00526767/files/DM00526767.pdf/jcr:content/translations/en.DM00526767.pdf) as well as the [STLINK-V3MINI](https://www.st.com/content/ccc/resource/technical/document/user_manual/group1/00/14/17/68/0f/01/48/01/DM00555046/files/DM00555046.pdf/jcr:content/translations/en.DM00555046.pdf).

**Comment by diegoherranz** [comment]
Gentle ping :)

**Comment by tuankiet65** [comment]
Looking forward to this, I'm designing a breakout to 2.5mm pitch board, guess I'll have to use the universal 1.27mm connector.

**Comment by myfreescalewebpage** [comment]
Hello @diegoherranz 
Just reviewed this pull request. Don't know why it was not done before because there is no comment to do. Merging now.
Joel

**Comment by diegoherranz** [comment]
Thanks!

**Pull request merged**
