### PR TITLE
Adding TLV62080DSGx, TLV62084DSGx, TLV62084ADSGx

### PR DESCRIPTION
**Pull request by ki5libs**
Adding TLV62080DSGx, TLV62084DSGx, TLV62084ADSGx
[Datasheet](http://www.ti.com/lit/ds/symlink/tlv62080.pdf)
tlv62080dsgx

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
could you put all gnd together?
what you think to shrunk a little?

**Comment by antonlysak** [comment]
Did it. Do you think it's OK now or shrunk too much?

**Comment by SchrodingersGat** [comment]
Hi @ki5libs can you please fix conflicts here?

**Comment by ki5libs** [comment]
@SchrodingersGat it looks OK now

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
