### PR TITLE
Regulator_SwitchedCapacitor: add TPS60151DRV

### PR DESCRIPTION
**Pull request by zonque**
Add TPS60151, a 5V, 140mA charge pump in a WSON-6 package.

The datasheet is here:

  https://www.ti.com/lit/ds/symlink/tps60151.pdf

Some space is left between the pins on the right side so a cap can fit in
the schematics.

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @zonque , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be `TPS60151DRV`to avoid issues if the manufacturer add new packages options
- [ ] VIN pin should be on left side, in front of VOUT, not on the top for this kind of symbol
- [ ] Footprint filter should be `WSON*1EP*2x2mm*P0.65mm*`
- [ ] Pin 7 should be added to the bottom of the symbol, called "EP", type Passive, NOT stacked with GND (it is not expected according to the datasheet)

Cheers,
Joel

**Comment by zonque** [comment]
Thanks! All done now.

image

**Comment by myfreescalewebpage** [comment]
@zonque thanks for the fixes. TPS60151 (without DRV) is still in the pull request. Can you remove it ? Then able to merge this. Joel

**Comment by zonque** [comment]
You mean in the title of the PR or in the commit log message?

**Comment by myfreescalewebpage** [comment]
In the git diff, look at https://github.com/KiCad/kicad-symbols/pull/1715/files

**Comment by zonque** [comment]
Ah, okay. The editor does strange things sometimes when symbols are renamed. Haven't really found a pattern to report that though. Anyway, removed now with the latest commit.

**Comment by myfreescalewebpage** [comment]
Thanks, yes it's sometimes strange :) Looks good now, merging.

**Pull request merged**
