### PR TITLE
Add RAK Wireles RAK811 LoRa module schematic symbol

### PR DESCRIPTION
**Pull request by alnunez**
RAK Wireles RAK811 LoRa modules: RAK811-LF (433 MHz), and RAK811-HF (868MHz & 915MHz) versions

Datasheet:[https://downloads.rakwireless.com/LoRa/RAK811/Hardware_Specification/RAK811_LoRa_Module_Datasheet_V1.4.pdf](https://downloads.rakwireless.com/LoRa/RAK811/Hardware_Specification/RAK811_LoRa_Module_Datasheet_V1.4.pdf)

Footprint PR#[2323](https://github.com/KiCad/kicad-footprints/pull/2323)

RAK811-HF-EU868
RAK811-LF-EU433

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by alnunez** [comment]
> Hi @alnunez , thanks for contributing,
> 
> A few comments I have during my review:
> 
> RAK811-HF
> 
> * [ ]  I don't know what is the exact part name, I suggest "RAK811-EU868", with "RAK811-IN865", "RAK811-US915" etc aliases
> * [ ]  Description: "RAK Wireless RAK811 EU868 LoRa Module" (just modify the region for the aliases)
> * [ ]  Name of pin 8 "PA12" only, name of pin 9 "PB4" only, name of pin 27 "PB2" only
> * [ ]  Name of pin 11 is VCC
> * [ ]  Name of pin 24 `~RST`
> * [ ]  The height and the width of the symbol can be reduced a bit
> 
> RAK811-LF
> 
> * [ ]  See previous comment about name of symbol
> * [ ]  See previous comment about description of symbol
> * [ ]  See previous comments about pin names
> * [ ]  See previous comment about the size of the symbol
> 
> I suggest to have the symbol inter-changeable: the same pin name at the same place on both variant.
> 
> Cheers,
> Joel

Done!

**Comment by myfreescalewebpage** [comment]
Thanks.

Both versions:
- [ ] RST and BOOT should be Input
- [ ] You can reduce the width of the symbol again

Joel

**Comment by alnunez** [comment]
> Thanks.
> 
> Both versions:
> 
> * [ ]  RST and BOOT should be Input
> * [ ]  You can reduce the width of the symbol again
> 
> Joel

Ok. Fixed!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment to do, great job done here !
Just need to wait the footprint now.
Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Pull request merged**
