### PR TITLE
fixing 40374, and add 74AHC/AHCT244 alias

### PR DESCRIPTION
**Pull request by JonathSpirit**
for the 40374 :
pin '1' is not a reset pin '~R' but a enable pin '~E'
and the 40374 is a tri-state output buffer, not a simple output buffer.
(and try to fix Travis error)

https://www.cmos4000.com/cmos/40374.html
https://www.digchip.com/datasheets/download_datasheet.php?id=369790&part-number=HEF40374BDB

(before change)

40374_b

(after change)
40374_a

For the 74HC244 :

adding 74AHC244/74AHCT244 alias.

the keyword for the 74HC244 say 'TTL' but it's 'HCMOS'.
same for the 74HCT244 the keyword say 'TTL' but it's 'HCTMOS'.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by JonathSpirit** [comment]
A small question,
is that ok to create an CMOS alias '74HCxxx' on a TTL '74LSxxx' ? Or it must be 2 separate component ?

**Comment by evanshultz** [comment]
As long as the symbols are compatible you can use an ALIAS. I think it's OK here.

Two things to do, both on 40374:
1. Make the power pin invisible. We know this is bad practice but that's the way things are for now.
2. There are 4 polylines now instead of just two. Can you revert this?

**Comment by JonathSpirit** [comment]
I redo the polylines and set the power pin invisible.

**Comment by evanshultz** [comment]
Thank you. I'd really prefer to see the diff only include the pin 1 name change and pin name offset change on 40374. We don't want users with this symbol in their schematics already to run into problems. Can you revert any other changes to the symbol, which might be easiest to do by hand?

**Comment by JonathSpirit** [comment]
All change is reverted and i only add pin change (pin 1 '~R' to '~E' and output pin to tri-state).

**Comment by evanshultz** [comment]
Thank you! The logic symbols are all bad but breaking schematics is worse.

**Pull request merged**
