### PR TITLE
Rework according to KLC, update descriptions, datasheets, footprints.

### PR DESCRIPTION
**Pull request by bobc**
Part 1/4 for Issue #18 

[demo_Memory_EEPROM.pdf](https://github.com/KiCad/kicad-symbols/files/1661104/demo_Memory_EEPROM.pdf)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Submit PR for new footprints
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by bobc** [comment]
There are some unexpected footprint issues, I will look into them...

**Comment by bobc** [comment]
We don't have a footprint matching some of the DFN-8 parts, I will submit a PR for that...

**Comment by jkriege2** [comment]
Great work so far on this ... I pressume you used your symbol generator scripts?

I poked through this PR and found some things that you could possibly fix in the process:
1. I think we should move the 27(C)xxx-devices to Memory_EPROM as they are UV-erasable EPROM not EEPROMs.
2. There are some devices with strange names, like `25LC_EEPROM` Also the latter is (according to DS) available in several different packages, but here only the DIP is listed. Could you make proper symbols from them? I think you will need two versions, one with 8-pins and one with 8+1EP (see http://ww1.microchip.com/downloads/en/DeviceDoc/21832H.pdf), or even split completely by package.
3. Also there are several devices `..._EEPROM` could you change their name to a KLC-conforming naming and also add all possible packages?

Thanks,
JAN

PS: Will you also tend to the RAMs (maybe at a later point).
PPS: Could you also post your scripts (if used), so people can reuse them to rework other parts of the lib?

**Comment by bobc** [comment]
> I pressume you used your symbol generator scripts?

Of course :) 

I moved 27* to Memory_EPROM, I marked some of them obsolete according to the proposal made by @poeschlr with the tag "[Obsolete YYYY-MM]"

I cleaned up the _EEPROM names, and added some more footprint filters.

I was planning to do the other Memory_* libs, some of them require more extensive rework.
I'm publishing the scripts in the symgen repo https://github.com/bobc/kicad-symgen/tree/master/symgen/data.

**Comment by jkriege2** [comment]
Are you done so far? Should I have another look?

**Comment by bobc** [comment]
I just noticed a couple of other issues with part names and sizing after adding the DFN parts, let me fix those up.

**Comment by jkriege2** [comment]
OK, let me know when you're done

**Comment by bobc** [comment]
Ok, ready now for re-review! 

I added a new feature to symgen to automatically stack "power in" pins, so this is a trial. I checked manually and it passed Travis, so I think it has worked correctly.

**Comment by jkriege2** [comment]
1. 2018-01-28 14_08_32-symbol library editor - memory_eeprom d__kicad_review pretty_kicad-symbols_memo
2. For the `24LC16` you specifically set the SOIC-8 package, but then the name should include the proper designation from the DS (i.e. `24LC16-SN`for SOIC). If you stick to that approach, could you also add the other variants from the datasheet (DIP-8, SOT-23-5, TSSOP-8, and the DFN-8 with its exposed pad)? that would be great. I see that for 25Lxx you've done just that with two symbols. I'm not sure how naming should be in that case, I opened an issue to answer that question: https://github.com/KiCad/kicad-symbols/issues/237
3. Also please add the package name to the descriptions (e.g. `, SOIC-8`, ... or `, DIP-8/SOIC-8/TSSOP-8`, ...)
4. in the `AT24CS01`-devices the pins are longer than  in the other devices ...
5. Maybe the AT24CS-devices should use the same symbols (maybe even ALIASes) of the "plain" 24LC-devices? This way they are exchangeable

**Comment by bobc** [comment]
Thanks for the comments, I will look into them.

I also noticed there are many parts with similar symbols. I am planning to add a new feature to symgen to allow inheritance of 'template' parts. This will help with parts that are similar but require a different default footprint (which is not possible with aliases). Also, this should be transferable to the new sweet library file, which may support inheritance directly.

**Comment by jkriege2** [comment]
sounds like a great idea!

**Comment by bobc** [comment]
> For the 24LC16 you specifically set the SOIC-8 package,

A note on that point, **I** didn't specifically set it, that was how it was defined before I made any changes! For the rationale of why it is like that you have to ask whoever originally submitted it. 

I'd like to stress what I am trying to do here is reworking _existing_ parts to comply with the current KLC, it is not my intention to add "missing" parts. That could take forever! AFAIK, there is nothing in the KLC that says if you submit one part, you must submit all possible variations from the same datasheet. I think that would be an unreasonable request.

I've modified symgen to handle a simple form of inheritance, it worked out easier than I thought. Any part can be used as a template for a new part, and properties can be selectively over-ridden. e.g

```
#
# 93AAxxC-P
#
COMP 93AAxxC-P U
FIELD $FOOTPRINT "Package_DIP:DIP-8_W7.62mm"
FPLIST
DIP*W7.62mm*
DESC Serial EEPROM, 93 Series, with ORG Pin, 1.8V, DIP-8
KEYW EEPROM memory Microwire
DOC http://ww1.microchip.com/downloads/en/DeviceDoc/20001749K.pdf
UNIT
1 CS I L
2 SCLK I L
3 DI I R
4 DO T R
7 NC NN R
6 ORG I R
UNIT PWR
5 GND PI B
8 VCC PI T
END
#
# 93AAxxC-SN
#
COMP 93AAxxC-SN U FROM 93AAxxC-P
FIELD $FOOTPRINT "Package_SOIC:SOIC-8_3.9x4.9mm_P1.27mm"
FPLIST
SOIC*3.9x4.9mm*
DESC Serial EEPROM, 93 Series, with ORG Pin, 1.8V, SOIC-8
END
```
This makes it a lot easier to create atomic part variants.

It would be great if we can come to a decision on #237 , I would like to get this PR finalised and then move on to other libraries, Memory_xxx, FPGA_Xilinx_xxx, Logic_xxx, MCU_STM32_xxx...

**Comment by poeschlr** [comment]
@bobc wrote:
> I'd like to stress what I am trying to do here is reworking existing parts to comply with the current KLC, it is not my intention to add "missing" parts. That could take forever! AFAIK, there is nothing in the KLC that says if you submit one part, you must submit all possible variations from the same datasheet. I think that would be an unreasonable request.

You are totally correct about that. I think the request by jan was not meant as a "you must" but more as a "i would be really happy if you could". I think we are allowed to ask contributors if they are willing to go one step further. However we should make it more clear in the future that fulfilling such a request is in no way necessary for the pull request to go forward.

I hope this clears that part up a bit. And thanks for your great work so far. All your contributions (and the contributions by others) will make the version 5 library that much better than our old v4 lib.

**Comment by jkriege2** [comment]
Hi @bobc!

also from my side: I'm extremely glad you put in all the work you do (especially the rework of logic ICs.

When I'm reviewing, I try to point out any issue that I find. But anything is usualy up for discussion (IMHO): We do exceptions to KLC if there is a good reason, If something is too much work at any given point, there is always the possibility to bring the PR into an "acceptable" shape and open an issue to complete it (that could be a way for this PR and additional devices)... and if you put in the work to fulfill all suggestions, that's even better!

In this case here, I reviewed, based on how I reworked several of the other libs (see e.g. the updated regulator libs). My idea was that since you script the stuff anyways it would be easy for you to add the modifications I mentioned (e.g. packages, splitting by the new KLC-rules, naming-conventions, ...). 

I hope that clears up my comments a bit.

Best,
JAN

**Comment by bobc** [comment]
> My idea was that since you script the stuff anyways it would be easy for you to add the modifications I mentioned

Changing the script is easy, the slow part is getting the data from datasheets etc. Even if that takes only 10 minutes per part, for a lot of symbols that is hours of effort.

My original goal was to rework symbols to remove gross errors like hidden power pins, off grid pins etc. I figured that if a symbol was an improvement to an existing one, it would still be useful even if didn't have all the metadata such as description, keywords, datasheet etc according to the letter of the KLC.

A single PR does not need to be definitive IMO, there is always an opportunity to improve the data in future.

Maybe I was mistaken? I think the current PR is a useful improvement to users over the current library, even though there might be improvements possible beyond what the KLC requires. OTOH, I would like to rework libs like Logic_TTL_IEE which is very poor. If the bar is set so high that I don't ever have time to complete a satisfactory PR, then there is probably no point in me trying to start!

I could submit reworked symbols on a per symbol basis, but that is much less efficient than a bulk approach. Anyway, I am still in a limbo position, not knowing what is needed to complete this PR, and not knowing whether further rework to other libs is going to be a waste of my time or not.

Awaiting further advice regarding this PR...

**Comment by jkriege2** [comment]
Then I think it's very simple: State what you're doing and let us know how far you can/want to go (i.e. how much effort/time you're willing to put into this) ... Then we can see how to proceed after this PR has been merged. You asked for a review, so I gave a review and pointed to some problems that seemed to be easy to fix to me. If you read carefully, I asked whether you **could** add the other variants. My point was: If it's the one variant only, it would be great if you could alter the symbol-names so they follow KLC (i.e. include packge-postfix of MPN), or you add all the variants (both options seem easy and quick to me to do and would make later extensions way easier) ... so if you don't have the time, just say so and we will possibly simpl merge this PR in a certain stage (which is for sure an enhancement over the symbols now in the lib) and simply open an issue for the remaining problems. then one can even simply point to this PR-thread for more problems to fix.

**Comment by poeschlr** [comment]
Jan are there any outstanding problems that would be in the way of merging this?
If the PR does increase the library quality without introducing new problems i would say it can be merged. Every further issue (outside the scope of this PR) can be handled in a separate PR.
For now such problem could be documented in an issue.

If @bobc wants to fix these additional problems later on he can simply open a new pull request and reference the issue that documents the problems he does fix.

**Comment by jkriege2** [comment]
No, I think everything that I requested was fixed ... this went a bit off-rail due to the discussion above (+ I was quite busy this week, so it slipped from my attention).

@bobc Please fix ther conflicts, so we can merge this.

**Comment by poeschlr** [comment]
@jkriege2 could you take another look at this before another merge is necessary?

**Comment by jkriege2** [comment]
Will do this evening!

**Comment by jkriege2** [comment]
Hi!

One request that would be really nice for this PR (I will merge without, but if you can do it quickly, that would safea lot of work later):
- Could you move the NC-pins in, so they END ON the bounding box and the pin-line sticks inside. this way it's unprobable to connect to them by accident:
2018-02-05 18_27_16-symbol library editor - memory_eeprom d__kicad_review pretty_kicad-symbols_memo
- Also could you group the EPOROM-pins equally for all devices ... sometimes the PGM/VPP-pins are close the the adress-pins, sometimes not ...
2018-02-05 18_29_57-symbol library editor - memory_eprom d__kicad_review pretty_kicad-symbols_memor



I had another closer look ... If you're willing/have some more time, could you in addition fix these
1. 27C512PLCC and 27C010 have a different symbol with (left pins @ x=-600/-400mil, while for all others x=-50mil) ... could you unify that width with your scripts, or is there a reason for it?
2. label-placement could be improved, if you move the name-label to the right and make it left-aligned, then it grows niver without covering the GND-pin for longer names, e.g.: 
2018-02-05 18_28_27-symbol library editor - memory_eeprom d__kicad_review pretty_kicad-symbols_memo

**Comment by jkriege2** [comment]
Hi!

thanks for the quick fixes ... I also noticed that on some devices the SPI-bus is split between left and right, e.g. 93LCxxxC or 
2018-02-06 07_02_04-symbol library editor - memory_eeprom d__kicad_review pretty_kicad-symbols_memo

whereas for others the 3 SPI-pins or 2 IIC-pins are on the right and all extra-pins (adress, CS, ...) are on the left ... I think we should also unify that layout? Are you willing to still do that?

Otherwise this looks good to me now ... Let me know if you will fix the pin-layout ...

Thanks,
JAN

**Comment by jkriege2** [comment]
Thanks for all the work you put into this!!!

JAN

**Pull request merged**
