### PR TITLE
Transistor_FET: Add a couple of TI CSD transistors

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://www.ti.com/lit/ds/symlink/csd17313q2.pdf

https://www.ti.com/lit/ds/slps234b/slps234b.pdf

imagen
imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A single comment I have during my review: CSD17313Q2 should be an alias of CSD16301Q2.

CSD25302Q2: no comment to do.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Pull request merged**
