### PR TITLE
Fixed STM32F042F*: renamed pin 15 from VSSA to VSS

### PR DESCRIPTION
**Pull request by pegasus17**
* Renamed pin 15 from VSSA to VSS. According the datasheet the F-variant (TSSOP20) does not have a ground for the analog domain. 
Datasheet: https://www.st.com/resource/en/datasheet/stm32f042f6.pdf
* Also fixed  Violating S3.1

STM32F042F4Px
STM32F042F6Px

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@pegasus17 
Thanks for making this contribution and fixing things.

However, there is an annoying problem with KiCad in which different versions change the line ordering. I don't know why the devs periodically decide to change things, or allow it to vary.

Anyway, what it means is that this library hasn't been touched for a while and your version of KiCad introduces a huge number of changes, mostly line re-ordering. It's very difficult to check your changes. Would you be willing to make one commit that saves the file with no changes in KiCad, and then a second commit which includes just the fixes you are making? That will be much easier to review. Thank you!

**Comment by pegasus17** [comment]
@evanshultz 
I have re-done the fix in the two steps you suggested. It should be now easrier to review.

**Comment by evanshultz** [comment]
Thanks! Re-naming the pin is fine, but changing the locations of other pins is not because it will cause a disconnection is schematics that are opened that were designed with the old symbol in mind. If you can revert changing the VDD pin location and symbol size, even though it creates an error, this will be OK. So to be clear, I should only see pin 15 renamed to get this PR merged.

**Comment by pegasus17** [comment]
No problem. I have reverted the change in the symbol size and pin location.

**Comment by evanshultz** [comment]
Even with all the messiness, I don't see anything wrong in the diff (but it is noisy). The branch opens in KiCad 5.1.2 and I see the pins renamed to `VSS` on the two symbols that should be affected. So I'll merge. Thanks for your effort to correct this and hope to see you again!

**Pull request merged**
