### PR TITLE
Discussion about template for RPi

### PR DESCRIPTION
**Pull request by jstjst**
Previous discussion see here: https://github.com/KiCad/kicad-symbols/pull/1744#issuecomment-485093620
In this PR, I want to check the template for the final symbol variants.
grafik

### CODE REVIEW

**Comment by jstjst** [comment]
Things to do:
- [ ] Decision about designator `A` or `U`
- [ ] Check description and keywords
- [ ] Check footprint naming and filter

**Comment by myfreescalewebpage** [comment]
@jstjst we do not allow "templates" in the library. I have opened an issue with the list of all RPi at #1772.
Two other points: all GND should be stacked, else this is not valid, and we were agree to not stack positive power pins, I think it's better too to allow various configurations.

**Comment by jstjst** [comment]
Here is a footprint PR about the name: 
In the end the decided for `Raspberry_Pi_Zero_Socketed_THT_FaceDown_MountingHoles`

@myfreescalewebpage Forgot to mention it: It is not my intention, that this PR is merged, just wanted a Travis output and also a new topic fr discussions.

**Comment by myfreescalewebpage** [comment]
Ok, added to the issue at the moment, you can update it after if required.

**Comment by jstjst** [comment]
The remaining GND Pins will be stacket, but they are not needed for all symbols, so I left them aside for now.
I will revert the power pin stacking

**Comment by myfreescalewebpage** [comment]
Ok, can you update it in #1772 ? For now, I will close this PR since it's not to be merged.

**Pull request closed without merging**
