### PR TITLE
Added PTN780x0 Series of DC-DC Converters from Texas Instruments

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of these non-isolated DC-DC converters

[PTN78000](https://www.ti.com/lit/ds/symlink/ptn78000w.pdf)
[PTN78020](https://www.ti.com/lit/ds/symlink/ptn78020w.pdf)
[PTN78060](https://www.ti.com/lit/ds/symlink/ptn78060w.pdf)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jamesrlucas** [comment]
The datasheets do list different part suffixes for through THT & SMD versions, using the PTN78000 as an example, the suffixes are xAH for the THT, xAS or xAZ for SMD. 

I'll update the part numbers accordingly tomorrow.

**Comment by chschlue** [comment]
> xAH for the THT, xAS or xAZ for SMD.

That's the point. The same place is used to encode package and RoHS status.

**Comment by jamesrlucas** [comment]
Ah, I understand now! I'll update the symbol names tomorrow then.

**Comment by jamesrlucas** [comment]
Done! :)

**Comment by chschlue** [comment]
Please update the descriptions.

**Comment by jamesrlucas** [comment]
Done - apologies for missing it the first time!

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
