### PR TITLE
Add Texas Instruments CDCLVP1102

### PR DESCRIPTION
**Pull request by cronJ**
Add Texas Instruments CDCLVP1102

From datasheet [http://www.ti.com/lit/ds/symlink/cdclvp1102.pdf](http://www.ti.com/lit/ds/symlink/cdclvp1102.pdf)

image

Footprint PR [https://github.com/KiCad/kicad-footprints/pull/1605](https://github.com/KiCad/kicad-footprints/pull/1605)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@cronJ thanks for this contribution.
Some similar devices already exist in the "Interface" library so I suggest to move your new one there.
Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @cronJ, thanks for moving the symbol

A few comments I have during my review:

- [ ] Name of the device should be `CDCLVP1102RGT` to avoid conflict if the manufacturer add packages option
- [ ] Description should ends with package name, "VQFN-16"
- [ ] Footprint filter will be `VQFN*1EP*3x3mm*P0.5mm*`
- [ ] The height of the symbol can be reduced. You can move the NC pin to achieve that.
- [ ] The NC pins should be move on the border outline of the symbol.
- [ ] The grouping of output pins is strange, I suggest P0 should be grouped with P1, and N0 with N1. I suggest the following design:

Capture

Tell me.

Cheers,
Joel

**Comment by cronJ** [comment]
I disagree with the grouping because this part is a one differential signal in, two differential signals out component. So OUTP0 and OUTN0 is the positive and negative signal of one differential output.

I will implement the rest soon.

**Comment by myfreescalewebpage** [comment]
Just reviewed again the grouping, I agree and was wrong in my previous message, thanks to point it.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, just need to wait the footprint before merging.

**Comment by myfreescalewebpage** [comment]
@cronJ thanks to point this, was forgotten, merging.

**Pull request merged**
