### PR TITLE
Added ADP5090

### PR DESCRIPTION
**Pull request by kajusK**
Added a ADP5090 symbol

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/ADP5090.pdf
2020-01-07-190828_3840x1080_scrot

Rule violation:
Power input is not placed on top - it's a regulator, power input is on the left, output on the right to look good.

### CODE REVIEW

**Comment by aewallin** [comment]
description should end with the footprint, so probably "LFCSP-16"

the example schematics in the datasheet have the placement of CBP higher up - is there any particular reason not to follow the datasheet symbol?

**Comment by kajusK** [comment]
Aaaha, ok, added the footprint to description.

The CBP at the bottom of the IC simplifies the resulting schematic as usually a capacitor is connected between CBP and ground. Also the MINOP pin is connected to ground through a resistor.

**Comment by myfreescalewebpage** [comment]
Hi @kajusK , thanks for contributing,

A few comments I have during my review:

- [ ] The name of the device should be ADP5090ACP
- [ ] Can you add a comma before the package name in the description: `Ultralow Power Boost Regulator with MPPT and Charge Management, LFCSP-16`
- [ ] Pin 4 should be Passive
- [ ] Pin 6 should be Passive
- [ ] Pin 12 should be Passive (it is optional)
- [ ] Pin 17 (EP) must be stacked with AGND according to the datasheet

Cheers,
Joel

**Comment by kajusK** [comment]
Hi @myfreescalewebpage,
thank you for the review, the issues were fixed.

Jakub

**Comment by myfreescalewebpage** [comment]
Seems the branch has a conflict, can you rebase so I can continue the review ? Thanks

**Comment by kajusK** [comment]
@myfreescalewebpage 
Resolved merge conflicts

**Comment by myfreescalewebpage** [comment]
@kajusK thanks for the fixes. stacking of EP is not correct, the name of pin 17 should be "AGND" (see also travis error log).
Joel

**Comment by kajusK** [comment]
@myfreescalewebpage Fixed the stacking, regarding the travis warning, the Vin pin is not placed on top as this would make resulting schematics hard to understand, it's a voltage regulator, input on the left makes sense.

**Comment by myfreescalewebpage** [comment]
Yes don't worry about this warning for this symbol.
No more comment to do, merging.

**Pull request merged**
