### PR TITLE
Added π120U30 and π120U31

### PR DESCRIPTION
**Pull request by G-Pereira**
Alias for this two digital isolators.
[Datasheet](http://www.rpsemi.com/public/doc/2Pai_%CF%8012xUxx_20200416_EN.pdf)

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
Guess this had to happen... there was a discussion about manufacturers' sanity just yesterday...

@stambaughw @sethhillbrand are there still reasons not to include multibyte chars in symbol names or do you believe it's safe?

@G-Pereira how about calling them τ/2?

**Comment by sethhillbrand** [comment]
U+0C30 is in our standard font, so it should be no problem.

**Comment by aris-kimi** [comment]
I want to suggest to add a translated version of MPN at the keyword field as `pi120u30/1`. I think this might ease the search process.

**Comment by G-Pereira** [comment]
> I want to suggest to add a translated version of MPN at the keyword field as `pi120u30/1`. I think this might ease the search process.

I was about to suggest the same

**Comment by aris-kimi** [comment]
@G-Pereira one last change, parent symbol's name offset i think it is good to change to 20mil / 0.508mm

**Comment by G-Pereira** [comment]
Hi, I already fixed that on a separate PR that already has been merged, check https://github.com/KiCad/kicad-symbols/pull/2939

**Comment by G-Pereira** [comment]
@aris-kimi and @chschlue is this ready to merge?

**Review by chschlue — APPROVED** [review]
Yes, thanks.

**Pull request merged**
