### PR TITLE
Sensor_Audio: add Knowles SPH0641LU4H digital MEMS microphone

### PR DESCRIPTION
**Pull request by zonque**
This adds a new symbol for a digital MEMS microphone. The datasheet can be found here: https://media.digikey.com/pdf/Data%20Sheets/Knowles%20Acoustics%20PDFs/SPH0641LU4H-1.PDF

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @zonque , thanks for contributing,

A few comments I have during my review:

- [ ] Descriptions should ends with package name:  `, LGA-5`
- [ ] Fp filter: `Knowles*LGA*3.5x2.65mm*`
- [ ] Position offset: 20mil (see travis warning)

Cheers,
Joel

**Comment by zonque** [comment]
> A few comments I have during my review:

All fixed now, thanks!

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Oops thanks for this fix, haven't notice before the datasheet was wrong. It's better now.

**Comment by zonque** [comment]
It was found during a review of the footprint. Which is merged now, btw.

On September 16, 2020 5:00:34 PM GMT+02:00, Joel <notifications@github.com> wrote:
>Oops thanks for this fix, haven't notice before the datasheet was
>wrong. It's better now.

-- 
Sent from my mobile. Please excuse typos and brevity.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
