### PR TITLE
Interface USB: Rework CY7C6521x symbols

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Following bug report https://github.com/KiCad/kicad-symbols/issues/1717, fix bug and KLC errors, also fix other issues about pin types, expose pad, etc and rework design of the symbols to get a more consistent family. New screenshot below.

CY7C65211:
cy7c65211

CY7C65213-28:
cy7c65213-28

CY7C65213-32:
cy7c65213-32

CY7C65215:
cy7c65215

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
I'm wary of changing this much right now when 5.1.1 and 5.1.2 will be released soon. Renaming pins for clarity or to correct their names, fixing VSSD, and making the EP pin exposed are all good for me. But moving pins around and changing the symbol is more than I'd like to see change right now. Are you OK only pushing a subset of these changes, that don't break schematics, for merging now? While I know fixing bugs opens the door to changing symbols this is a but much for me.

**Comment by evanshultz** [comment]
Datasheets for future reference.

65211:
https://www.cypress.com/file/139886/download

65213:
https://www.cypress.com/file/139881/download

65215:
https://www.cypress.com/file/129956/download

**Comment by myfreescalewebpage** [comment]
> 5.1.1 and 5.1.2 will be released soon

I'm not aware of that, sure it's better to wait v6 here !! The issue is not major has the original author of https://github.com/KiCad/kicad-symbols/issues/1717 has a solution to use the symbol anyway.

Joel

**Comment by evanshultz** [comment]
But if the core library isn't fixed, other people will catch this error. I fully support re-naming the pin now because that's a bug, but I'm not in favor of changing symbol size and pin positions at this time. Would you be OK for you?

**Comment by myfreescalewebpage** [comment]
@evanshultz I can do it yes. I will create another pull request for that this evening.

**Comment by myfreescalewebpage** [comment]
Here it is: https://github.com/KiCad/kicad-symbols/pull/1726

**Comment by antoniovazquezblanco** [comment]
The PR only contains enhancements as the bug has been corrected in another PR. Dropping the bug tag.

**Pull request closed without merging**
