### PR TITLE
Add Allegro AMT49413 3-Phase BLDC Driver

### PR DESCRIPTION
**Pull request by wingrime**
Allegro AMT49413 3-Phase BLDC Driver symbol
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [*] Provide a URL to a datasheet for the symbol(s) you are contributing
- [*] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [*] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @wingrime , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with package name: `3-Phase BLDC Controller and MOSFET Driver, QFN-48`
- [ ] Footprint filter: `QFN*1EP*7x7mm*P0.5mm*`
- [ ] Pin position offset: 20mil instead of 40 (see travis error)
- [ ] NC pin must be moved on the border outline of the symbol.
- [ ] V5 and V5DB are Power Output
- [ ] Pin 18 should be Passive
- [ ] Pin 14 is Input
- [ ] Pin 17 should be on the left or on the right, not on the bottom
- [ ] Pin 17 is Input
- [ ] Pin 16 should be Passive
- [ ] Pins 5 and 6 are Open Collector
- [ ] Pin 23 is Input
- [ ] Pin 19 is Input
- [ ] Pins 21 and 22 are Input
- [ ] Pin 20 is Input
- [ ] Pin 38 is Input
- [ ] Pin 40 is Power Output
- [ ] Pin 49 must be stacked with AGND
- [ ] You should cross CSN and CSP for more convenience (schematic page 3 of the datasheet)
- [ ] REF near to CSOUT is also better

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@wingrime ping

**Comment by wingrime** [comment]
Thanks for review!, fix soon as I have some free time

**Comment by myfreescalewebpage** [comment]
@wingrime are you still alive ?

**Comment by wingrime** [comment]
yeax, need free weekend

**Comment by myfreescalewebpage** [comment]
Thanks, sorry for the ping, that was just to have news :)

**Comment by wingrime** [comment]
Thanks for review, I have fixed all mentioned problems (I hope, not creating new one in process....)

**Comment by myfreescalewebpage** [comment]
@wingrime thanks this is a great enhancement. Few comments remains:
- [ ] Stacking of GND pins is not correct. You must have two pins, at the same place. The first pin is 41 with name GND, it is Power Input and Visible. The second pin is 49 name GND, Passive and Invisible. See other device ( MCU for example, we have plenty of example).
- [ ] You should center GND
- [ ] You can reduce the height of the symbol by 100mil at the bottom
- [ ] NC pin are not correct. "on the border outline of the symbol" means:

Capture

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
