### PR TITLE
Add NCS*325 AOP serie from ONsemi

### PR DESCRIPTION
**Pull request by suzizecat**
Hi all !
Here I come with some AOP from ONSemi.

Here's the datasheet : http://www.onsemi.cn/PowerSolutions/document/NCS325-D.PDF

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Having the power pins on both units will result in wrong netlists if the user ever connects them both. For this reason please split the powerpins into a third unit and set the "all units are not interchangable" flag. (See other dual opamps in this lib.)

**Comment by poeschlr** [comment]
The new file format will support interchangeability between a subset of units. (If support for it gets implemented in the near future is a different matter.)

And yes for now the only real option we have (other than using only one unit) is to ditch that feature.

**Comment by suzizecat** [comment]
The split is done

**Comment by evanshultz** [comment]
@suzizecat 
I want to touch the opamp lib. Will you be able to make these changes soon? Ideally within the next day or so?

**Comment by evanshultz** [comment]
@suzizecat 
After not hearing anything from you, I submitted https://github.com/KiCad/kicad-symbols/pull/578 which should break this PR when it's merged. To get these symbols into the lib I can add them to my PR or you can fix the conflicts.

**Comment by suzizecat** [comment]
@evanshultz Sorry, i missed your lasts messages. Hadn't lot of time recently.
I can correct the points you raised next week, but if you wanna fix those problems and get those symbols into your PR, please do !

**Comment by evanshultz** [comment]
@suzizecat 
No problem on the short delay. If you're able to make the changes above then these symbols will be ready to merge, either way it gets merged. Can you do that?

**Comment by suzizecat** [comment]
@evanshultz Well... missed some things... was late... But hey ! I solved the conflicts !

I'm editing the points you raised and push another commit

**Comment by suzizecat** [comment]
How should I add the package in the dual version description (multiple packages) ?
I removed the DFN package and may add it in another PR but, unless required, I don't think making it quickly, and other points should be fine by now

**Comment by evanshultz** [comment]
The dual isn't ready because it lists two packages but doesn't include them in the description at all. And since only a subset of the total number of packages are provided they should each use the suffix to make this clear.

But, I'll merge this anyway. I can sort this out and add the DFN package. And also and sort out ALIASes. I have more work to do on these libs anyway.

Thanks! The notes above are to help you in the future.

**Comment by evanshultz** [comment]
Um. Since I merge the line endings fix in another PR this one is broken. Can you please merge from master again? Sorry.

I assume even if you need to touch this you don't want to make more edits.

**Comment by suzizecat** [comment]
I don't mind editing a little bit more the symbols (and descriptions and so on...) I just don't really know what to do (and it make take some time since i'm not really involved in ECAD those times.

So I should add the suffix to the dual versions (and therefore create a full component for each version), add the package in the description and eventually create the right DFN footprint ? (I'll really praise some lord when there will be a followed standard in SMD packages... :sob: )

**Comment by suzizecat** [comment]
I'll try to do that this afternoon since it's really a small work.
Since the DFN component isn't orderable (didn't saw that) shouldn't we NOT release a symbol for it (to avoid stupid design mistake which cost a lot :angel: ) ?

**Comment by evanshultz** [comment]
Yes, that's what I'm saying about the DFN package as well. Thanks for getting this patch ready to merge!

**Comment by suzizecat** [comment]
Well, so I edited the NCS2325 to NCS2325D with the OnSemi  and SOIC footprint, since these have the same pin mapping and name (minimum differentiation).
I also edited the description.

It may be useful to create an alias of the 2325D called 2325DM but I don't think that it's really relevant...

According to that choice and KLC (I believe) I didn't added the default FP.

**Comment by suzizecat** [comment]
I don't get your point...
I won't argue more after your reply to this, but the KLC clearly state
 > A single symbol should be drawn for each footprint variation of an atomic part. Other variations (as listed above) do not require their own symbol alias.

Since MSOP and SOIC have the same pinout and the MPN NCS2325D may describe SOIC as well as MSOP (which is DM) without including the DFN. Why should we create a separate atomic symbol ?

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-symbols/issues/237

Let me know if you just want this merged; I can take it from here.

**Comment by suzizecat** [comment]
It's funny how there is always a case which mess up with KLC even with all the hard work you guys put in ^^'
I think that this goes against the original KiCad workflow but I tend to prefer atomic part so I won't complain :wink: 
I do the edition and this will be (finally) ready to go !

**Comment by suzizecat** [comment]
@evanshultz And with that, it SHOULD be ok ;)

**Comment by suzizecat** [comment]
Done

**Comment by evanshultz** [comment]
Thanks for all your effort on this! Sorry you got caught up in the middle of changes to this lib.

**Comment by suzizecat** [comment]
No problem, thanks for the time you took on this (and the time you take for KiCAD :+1: )

**Pull request merged**
