### PR TITLE
Added LM5161PWP

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: http://www.ti.com/lit/ds/symlink/lm5161.pdf#page=34
Footprint: https://github.com/KiCad/kicad-footprints/pull/2144

Captura de pantalla de 2020-03-16 12-28-17
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Regarding S4.2: I think this is not applicable to regulators, so the contributed symbol is correct.
Regarding S5.1: Footprint PR is linked above.

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] Terminate the description with the name of the package: `1A Synchronous Buck/Fly-buck Converter, 4.5V-100V input, adjustable output voltage, HTTSOP-14`
- [ ] The footprint filter should be `HTSSOP*1EP*4.4x5mm*P0.65mm*`
- [ ] NC pins 7 and 14 should be added called "NC", Passive, Invisible, on the border outline of the symbol

Cheers,
Joel

**Comment by cnieves1** [comment]
Done
Captura de pantalla de 2020-03-28 16-20-21

**Comment by myfreescalewebpage** [comment]
Position of NC pins not correct. should be: 

Capture

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
