### PR TITLE
Added TPA6132A2RTE DirectPath stereo audio amplifier

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.ti.com/lit/ds/symlink/tpa6132a2.pdf

Captura de pantalla de 2020-04-07 09-23-43

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] The package should be "WQFN". If it does not exist you should submit it.
- [ ] You should align HPVDD with HPVSS
- [ ] Name of pin 17 should be "EP"

Cheers,
Joel

**Comment by cnieves1** [comment]
Hi Joel,
All changes done but one: TQFN footprint already existed, and matches the dimensions for this device. Are you sure that a new one is needed?
Thanks,

**Comment by cnieves1** [comment]
Captura de pantalla de 2020-04-08 23-59-14

**Comment by myfreescalewebpage** [comment]
Yes please, we always create the exact footprint. This remove any future questions when using the symbol.
Joel

**Comment by myfreescalewebpage** [comment]
Thanks.

Package name to be fixed in the description too.

Joel

**Comment by cnieves1** [comment]
Sorry! I missed that one. Fixed now.

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by chschlue** [comment]
FP https://github.com/KiCad/kicad-footprints/pull/2207 merged.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
