### PR TITLE
Added new foot print for MPL115A1

### PR DESCRIPTION
**Pull request by Misca1234**
To save the 3D model of the MPL115A1
https://github.com/KiCad/kicad-packages3D/pull/515

A new foot print need to be created
NXP_MPL115A1_LGA-8_3x5mm_P1.25mm.kicad_mod

Data sheet
https://www.nxp.com/docs/en/data-sheet/MPL115A1.pdf

The symbol is not aligned to newer KiCad standard, this push only concerned the foot print change.
Question is, should the symbol be updated in other ways, such as 20 instead of 40 of "Pin Name Position Offset", out pins on the right etc?

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1342

Symbol push
https://github.com/KiCad/kicad-symbols/pull/1467

foot print script push
https://github.com/pointhi/kicad-footprint-generator/pull/277

bild

bild

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by Misca1234** [comment]
Yes it does
The meaning of Question" is "The Author is asking something"

The Author (that is me) is asking something in the first comment

**Comment by myfreescalewebpage** [comment]
Ok, response is no, this will break existing schematics. For this PR we can only change metadata.

**Comment by Misca1234** [comment]
Then we are ready to go

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
@Misca1234 seems everything is okay here, merging. Thanks !

**Pull request merged**
