### PR TITLE
Intersil

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR transfers the old `intersil.lib` into:

* Battery_Management
* Driver_FET

It also moved `infineon` library across to `Power_Management`

### CODE REVIEW

**Comment by poeschlr** [comment]
This seems to include some other things than you listed in the pull request description. Is this on purpose or did you mix up your branches somehow?

**Comment by SchrodingersGat** [comment]
I had simply failed to add that information to the PR message. Fixed now :)

**Comment by SchrodingersGat** [comment]
Fixed conflicts

**Comment by SchrodingersGat** [comment]
Too many changes have been made through other merges. I'll close this and start again.

**Pull request closed without merging**
