### PR TITLE
Added initial support to ST L620x H-bridges.

### PR DESCRIPTION
**Pull request by colombojrj**
I added initial support to ST L620x H-bridges. Link to item's description page (which includes the datasheet): https://www.st.com/en/motor-drivers/l6201.html

- L6201

image

- L6202

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @colombojrj, thanks for contributing,

A few comments I have during my review:

For both devices:
- [ ] Pins length should be 100mil (symbol < 100pins)
- [ ] GND pins should be stacked
- [ ] You can move reference and name closer to the device
- [ ] Pin name position offset should be 20mil
- [ ] You should provide datasheet link in the Documentation File Name field, not in the Field Properties, where it should remains blank
- [ ] NC pins must be added, named NC, Type Not Connected, not visible, placed on the border outline of the symbol
- [ ] Type of VREF should be Passive to avoir ERC errors and you can place it in the bottom left corner to simplify wiring
- [ ] VS must be moved on the top of the symbol
- [ ] BOOT2 should be moved below OUT2 to simplify wiring
- [ ] BOOT1 and BOOT2 should be Passive to avoid ERC errors
- [ ] Current sense output pin name should be "SENSE" only
- [ ] I not agree with "double" in keywords, you can set simply "full-bridge h-bridge" in the keywords (I have copy/paste from another similar device in the lib)

L6201:
- [ ] Description can be enhanced, for example `1A, DMOS Full Bridge Driver, Maximum Supply Voltage 48V, SOIC-20`
- [ ] Footprint filter should be `SOIC*7.5x12.8mm*P1.27mm*`

L6202:
- [ ] Description can be enhanced, for example `1.5A, DMOS Full Bridge Driver, Maximum Supply Voltage 48V, DIP-18`
- [ ] Footprint filter should be `DIP*W7.62mm*`
- [ ] Why "long pad" footprint ?

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@colombojrj ping! Are you still alive on this subject ?

**Comment by colombojrj** [comment]
Hello Joel,
Sorry for the delayed response. I am really busy these days. I have appreciated your suggestions, but unfortunately I will not be able to help in this matter for the next days.
See ya.

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this is abandoned.

**Pull request closed without merging**
