### PR TITLE
Use updated KiCad .gitignore from https://github.com/github/gitignore/blob/master/KiCad.gitignore

### PR DESCRIPTION
**Pull request by McNeight**
Use updated KiCad .gitignore from https://github.com/github/gitignore/blob/master/KiCad.gitignore

### CODE REVIEW

**Comment by chschlue** [comment]
Welcome and thanks for your first contribution.
However, this .gitignore template is meant for versioned KiCad project directories, not libraries.
The file extensions you added wouldn't usually turn up in a symbol library, or am I missing something here?

**Comment by McNeight** [comment]
Generally speaking, you are correct that most wont be seen in a normal library. I guess I look at it as 2 separate use cases:
1) Regular users who install a release version of KiCad which doesn't have any git information.
2) Power users and developers who use this as a versioned KiCad project.

The file is only seen in the second case. I don't recall the specific reason I needed to change the file, but I figured I'd update it to the latest from the public gitignore repo.

**Comment by myfreescalewebpage** [comment]
I'm not really in favor of this. If we go in this direction, plenty of extension will need to be escaped. *.docx, mp3, and so more.
People committing to the repo should just look after their commits. It's a very good exercice.

**Comment by diegoherranz** [comment]
@McNeight, for your second case with power users, if anyone creates a project including a versioned version of this library, the .gitignore should belong to that project and not to the libraries if I understand your use case correctly.

I agree with @chschlue and @myfreescalewebpage and I would vote to reject this PR. In fact, I don't see the need for a .gitignore at all, same as @myfreescalewebpage.

Thanks.

**Comment by chschlue** [comment]
Fully agree. If you're mixing library and project directories, you're probably doing it wrong.
Closing.

**Pull request closed without merging**
