### PR TITLE
Add NXP MCU MKV11Z128VLH7

### PR DESCRIPTION
**Pull request by michalkona**
NXP MCU MKV11Z128VLH7 for motor control applications was added.

Datasheet: https://www.nxp.com/docs/en/data-sheet/KV11P64M75.pdf

Screenshot:
Screenshot MKV11Z128VLH7

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @michalkona , thanks for contributing,

A few comments I have during my review:

- [ ] Can you sign the CLA, which is a mandatory condition to accept your contribution ? Thanks.
- [ ] Description should have the same format than other devices in the same lib, I propose `Kinetis KV11 series, 75-MHz/32-bit ARM Cortex-M0+, 128 kB flash, 16 kB RAM, Entry-Level, Real-time Motor Control, LQFP-64`
- [ ] Same comment for keywords: `Kinetis KV11 ARM Cortex M0+` is great
- [ ] Footprint filter should be `LQFP*10x10mm*P0.5mm*` (no leading *)
- [ ] VSS pins 4/31/47 should be stacked (i.e. all at the same place, first pin is Power Input visible, other pins are Passive invisible)

Else, great job.

Cheers,
Joel

**Comment by michalkona** [comment]
Ready to review.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the travis tests.

**Comment by myfreescalewebpage** [comment]
@michalkona you have moved VDD pins, but they should NOT be stacked. Only VSS pins should be stacked according to KLC.

**Comment by michalkona** [comment]
VDD pins are already fixed.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
