### PR TITLE
Added CD4051B and CD4052B

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.ti.com/lit/ds/symlink/cd4052b.pdf

image

image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
**Note: I have fixed the names of these parts, previously (and incorrectly) CD504x - now CD405x**

**Comment by evanshultz** [comment]
- Could you add appropriate footprints to the descriptions?
- Both symbols have the same description.
- The pin names are a bit changed from the TI datasheet, but I think it's clear so I'm OK with that.
- SOIC16 footprint dimensions are 3.9x9.9, not 9.8 as in your footprint filter.
- The SOP package footprint filter should match `SOIC-16W_5.3x10.2mm_P1.27mm` and include the pin pitch.
- I think perhaps these symbols could be a bit smaller with no detriment. Below is an example and I've thrown in CD4053B as well to verify that the whole family fits together nicely. I tried to minimize the little tiny lines since the symbol editor doesn't have line styles. Would you accept this proposal and also add the 4rd member of the family?
```
# CD4051B
#
DEF CD4051B U 0 20 Y Y 1 F N
F0 "U" -400 650 50 H V L CNN
F1 "CD4051B" 150 650 50 H V L CNN
F2 "" 150 -750 50 H I L CNN
F3 "" -20 100 50 H I C CNN
$FPLIST
 TSSOP*4.4x5mm*P0.65mm*
 DIP*W7.62*
 SOIC*3.9x9.8mm*P1.27mm*
 SOP*5.3x10.3mm*
$ENDFPLIST
DRAW
C -240 100 20 0 1 10 N
C -90 100 20 0 1 10 N
C 140 -500 20 0 1 10 N
C 140 -400 20 0 1 10 N
C 140 -300 20 0 1 10 N
C 140 -200 20 0 1 10 N
C 140 -100 20 0 1 10 N
C 140 0 20 0 1 10 N
C 140 100 20 0 1 10 N
C 140 200 20 0 1 10 N
S -400 250 -200 550 0 1 10 N
S -400 600 400 -600 0 1 10 f
P 2 0 1 10 -320 100 -260 100 N
P 2 0 1 10 -220 110 -130 140 N
P 2 0 1 10 -180 0 -205 0 N
P 2 0 1 10 -180 10 -180 35 N
P 2 0 1 10 -180 60 -180 85 N
P 2 0 1 10 -180 400 -200 400 N
P 2 0 1 10 -150 400 -125 400 N
P 2 0 1 10 -70 110 90 200 N
P 2 0 1 10 -70 400 -90 400 N
P 2 0 1 10 -20 150 -20 175 N
P 2 0 1 10 -20 200 -20 225 N
P 2 0 1 10 -20 250 -20 275 N
P 2 0 1 10 -20 300 -20 325 N
P 2 0 1 10 -20 340 -20 360 N
P 2 0 1 10 -20 380 -20 400 N
P 2 0 1 10 -20 400 -40 400 N
P 2 0 1 10 160 -500 230 -500 N
P 2 0 1 10 160 -400 230 -400 N
P 2 0 1 10 160 -300 230 -300 N
P 2 0 1 10 160 -200 230 -200 N
P 2 0 1 10 160 -100 230 -100 N
P 2 0 1 10 160 0 230 0 N
P 2 0 1 10 160 100 230 100 N
P 2 0 1 10 160 200 230 200 N
X X4 1 500 -200 100 L 50 50 1 1 B
X B 10 -500 400 100 R 50 50 1 1 I
X A 11 -500 500 100 R 50 50 1 1 I
X X3 12 500 -100 100 L 50 50 1 1 B
X X0 13 500 200 100 L 50 50 1 1 B
X X1 14 500 100 100 L 50 50 1 1 B
X X2 15 500 0 100 L 50 50 1 1 B
X VDD 16 100 700 100 D 50 50 1 1 W
X X6 2 500 -400 100 L 50 50 1 1 B
X X 3 -500 100 100 R 50 50 1 1 B
X X7 4 500 -500 100 L 50 50 1 1 B
X X5 5 500 -300 100 L 50 50 1 1 B
X INH 6 -500 0 100 R 50 50 1 1 I
X VEE 7 -100 -700 100 U 50 50 1 1 W
X VSS 8 0 -700 100 U 50 50 1 1 W
X C 9 -500 300 100 R 50 50 1 1 I
ENDDRAW
ENDDEF
#
# CD4052B
#
DEF CD4052B U 0 20 Y Y 1 F N
F0 "U" -400 650 50 H V L CNN
F1 "CD4052B" 150 650 50 H V L CNN
F2 "" 150 -750 50 H I L CNN
F3 "" -20 200 50 H I C CNN
$FPLIST
 TSSOP*4.4x5mm*P0.65mm*
 DIP*W7.62*
 SOIC*3.9x9.8mm*P1.27mm*
 SOP*5.3x10.3mm*
$ENDFPLIST
DRAW
C -240 -300 20 0 1 10 N
C -240 200 20 0 1 10 N
C -90 -300 20 0 1 10 N
C -90 200 20 0 1 10 N
C 140 -500 20 0 1 10 N
C 140 -400 20 0 1 10 N
C 140 -300 20 0 1 10 N
C 140 -200 20 0 1 10 N
C 140 0 20 0 1 10 N
C 140 100 20 0 1 10 N
C 140 200 20 0 1 10 N
C 140 300 20 0 1 10 N
S -400 350 -200 550 0 1 10 N
S -400 600 400 -600 0 1 10 f
P 2 0 1 10 -320 -300 -260 -300 N
P 2 0 1 10 -320 200 -260 200 N
P 2 0 1 10 -220 -290 -130 -260 N
P 2 0 1 10 -220 210 -130 240 N
P 2 0 1 10 -180 -400 -205 -400 N
P 2 0 1 10 -180 -390 -180 -365 N
P 2 0 1 10 -180 -340 -180 -315 N
P 2 0 1 10 -180 -230 -180 -205 N
P 2 0 1 10 -180 -180 -180 -155 N
P 2 0 1 10 -180 -130 -180 -105 N
P 2 0 1 10 -180 -80 -180 -55 N
P 2 0 1 10 -180 -30 -180 -5 N
P 2 0 1 10 -180 20 -180 45 N
P 2 0 1 10 -180 80 -180 105 N
P 2 0 1 10 -180 130 -180 155 N
P 2 0 1 10 -180 180 -180 205 N
P 2 0 1 10 -180 450 -200 450 N
P 2 0 1 10 -150 450 -125 450 N
P 2 0 1 10 -70 -290 90 -200 N
P 2 0 1 10 -70 210 90 300 N
P 2 0 1 10 -70 450 -90 450 N
P 2 0 1 10 -20 -210 -20 -185 N
P 2 0 1 10 -20 -160 -20 -135 N
P 2 0 1 10 -20 -110 -20 -85 N
P 2 0 1 10 -20 -60 -20 -35 N
P 2 0 1 10 -20 -10 -20 15 N
P 2 0 1 10 -20 50 -20 75 N
P 2 0 1 10 -20 100 -20 125 N
P 2 0 1 10 -20 150 -20 175 N
P 2 0 1 10 -20 200 -20 225 N
P 2 0 1 10 -20 250 -20 275 N
P 2 0 1 10 -20 300 -20 325 N
P 2 0 1 10 -20 350 -20 370 N
P 2 0 1 10 -20 350 -20 375 N
P 2 0 1 10 -20 390 -20 410 N
P 2 0 1 10 -20 430 -20 450 N
P 2 0 1 10 -20 450 -40 450 N
P 2 0 1 10 160 -500 230 -500 N
P 2 0 1 10 160 -400 230 -400 N
P 2 0 1 10 160 -300 230 -300 N
P 2 0 1 10 160 -200 230 -200 N
P 2 0 1 10 160 0 230 0 N
P 2 0 1 10 160 100 230 100 N
P 2 0 1 10 160 200 230 200 N
P 2 0 1 10 160 300 230 300 N
X Y0 1 500 -200 100 L 50 50 1 1 B
X A 10 -500 500 100 R 50 50 1 1 I
X X3 11 500 0 100 L 50 50 1 1 B
X X0 12 500 300 100 L 50 50 1 1 B
X X 13 -500 200 100 R 50 50 1 1 B
X X1 14 500 200 100 L 50 50 1 1 B
X X2 15 500 100 100 L 50 50 1 1 B
X VDD 16 100 700 100 D 50 50 1 1 W
X Y2 2 500 -400 100 L 50 50 1 1 B
X Y 3 -500 -300 100 R 50 50 1 1 B
X Y3 4 500 -500 100 L 50 50 1 1 B
X Y1 5 500 -300 100 L 50 50 1 1 B
X INH 6 -500 -400 100 R 50 50 1 1 I
X VEE 7 -100 -700 100 U 50 50 1 1 W
X VSS 8 0 -700 100 U 50 50 1 1 W
X B 9 -500 400 100 R 50 50 1 1 I
ENDDRAW
ENDDEF
#
# CD4053B
#
DEF CD4053B U 0 20 Y Y 1 F N
F0 "U" -400 650 50 H V L CNN
F1 "CD4053B" 150 650 50 H V L CNN
F2 "" 150 -750 50 H I L CNN
F3 "" -20 200 50 H I C CNN
$FPLIST
 TSSOP*4.4x5mm*P0.65mm*
 DIP*W7.62*
 SOIC*3.9x9.8mm*P1.27mm*
 SOP*5.3x10.3mm*
$ENDFPLIST
DRAW
C -240 -400 20 0 1 10 N
C -240 -100 20 0 1 10 N
C -240 200 20 0 1 10 N
C -90 -400 20 0 1 10 N
C -90 -100 20 0 1 10 N
C -90 200 20 0 1 10 N
C 140 -500 20 0 1 10 N
C 140 -400 20 0 1 10 N
C 140 -200 20 0 1 10 N
C 140 -100 20 0 1 10 N
C 140 100 20 0 1 10 N
C 140 200 20 0 1 10 N
S -400 250 -200 550 0 1 10 N
S -400 600 400 -600 0 1 10 f
P 2 0 1 10 -320 -400 -260 -400 N
P 2 0 1 10 -320 -100 -260 -100 N
P 2 0 1 10 -320 200 -260 200 N
P 2 0 1 10 -220 -390 -130 -360 N
P 2 0 1 10 -220 -90 -130 -60 N
P 2 0 1 10 -220 210 -130 240 N
P 2 0 1 10 -180 -500 -205 -500 N
P 2 0 1 10 -180 -490 -180 -465 N
P 2 0 1 10 -180 -440 -180 -415 N
P 2 0 1 10 -180 -330 -180 -305 N
P 2 0 1 10 -180 -280 -180 -255 N
P 2 0 1 10 -180 -230 -180 -205 N
P 2 0 1 10 -180 -180 -180 -155 N
P 2 0 1 10 -180 -130 -180 -105 N
P 2 0 1 10 -180 -30 -180 -5 N
P 2 0 1 10 -180 20 -180 45 N
P 2 0 1 10 -180 80 -180 105 N
P 2 0 1 10 -180 130 -180 155 N
P 2 0 1 10 -180 180 -180 205 N
P 2 0 1 10 -180 450 -200 450 N
P 2 0 1 10 -150 450 -125 450 N
P 2 0 1 10 -70 -390 90 -300 N
P 2 0 1 10 -70 -90 90 0 N
P 2 0 1 10 -70 210 90 300 N
P 2 0 1 10 -70 450 -90 450 N
P 2 0 1 10 -20 -310 -20 -285 N
P 2 0 1 10 -20 -260 -20 -235 N
P 2 0 1 10 -20 -210 -20 -185 N
P 2 0 1 10 -20 -160 -20 -135 N
P 2 0 1 10 -20 -110 -20 -85 N
P 2 0 1 10 -20 -10 -20 15 N
P 2 0 1 10 -20 50 -20 75 N
P 2 0 1 10 -20 100 -20 125 N
P 2 0 1 10 -20 150 -20 175 N
P 2 0 1 10 -20 200 -20 225 N
P 2 0 1 10 -20 250 -20 275 N
P 2 0 1 10 -20 300 -20 325 N
P 2 0 1 10 -20 350 -20 370 N
P 2 0 1 10 -20 350 -20 375 N
P 2 0 1 10 -20 390 -20 410 N
P 2 0 1 10 -20 430 -20 450 N
P 2 0 1 10 -20 450 -40 450 N
P 2 0 1 10 160 -500 230 -500 N
P 2 0 1 10 160 -400 230 -400 N
P 2 0 1 10 160 -200 230 -200 N
P 2 0 1 10 160 -100 230 -100 N
P 2 0 1 10 160 100 230 100 N
P 2 0 1 10 160 200 230 200 N
X Y1 1 500 -200 100 L 50 50 1 1 B
X B 10 -500 400 100 R 50 50 1 1 I
X A 11 -500 500 100 R 50 50 1 1 I
X X0 12 500 200 100 L 50 50 1 1 B
X X1 13 500 100 100 L 50 50 1 1 B
X Y 14 -500 -100 100 R 50 50 1 1 B
X X 15 -500 200 100 R 50 50 1 1 B
X VDD 16 100 700 100 D 50 50 1 1 W
X Y0 2 500 -100 100 L 50 50 1 1 B
X Z1 3 500 -500 100 L 50 50 1 1 B
X Z 4 -500 -400 100 R 50 50 1 1 B
X Z0 5 500 -400 100 L 50 50 1 1 B
X INH 6 -500 -500 100 R 50 50 1 1 I
X VEE 7 -100 -700 100 U 50 50 1 1 W
X VSS 8 0 -700 100 U 50 50 1 1 W
X C 9 -500 300 100 R 50 50 1 1 I
ENDDRAW
ENDDEF
#
```
image

**Comment by SchrodingersGat** [comment]
Changes made as requested :)

**Comment by evanshultz** [comment]
Just add the packages to the end of the description and it's ready to merge. Thanks!

I also wouldn't mind to see the description include the word "CMOS" and use "single"/"double"/"triple" instead of different nomenclature for the various symbols.

**Comment by SchrodingersGat** [comment]
Are these changes now sufficient? :)

**Comment by evanshultz** [comment]
LOL. Actually, almost all of the descriptions in this library meet the normal criteria for showing pin numbers (for example `DIP-16/SOIC-16/TSSOP-16`). But otherwise, yes! :)

**Comment by SchrodingersGat** [comment]
I write these rules and I can't even follow them! Thanks for the intense scrutiny :)

**Comment by evanshultz** [comment]
I reckon we can keep you around anyway. :)

**Comment by SchrodingersGat** [comment]
Very generous :) Thanks @evanshultz

**Pull request merged**
