### PR TITLE
Analog ADC: create ADS8684 and ADS8688

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Creation of TI ADC ADS8688 and ADS8644.

Datasheet : http://www.ti.com/lit/ds/symlink/ads8688.pdf

Screenshot:

ads8688

No error with checklib.py, using existing TSSOP38 footprint.

### CODE REVIEW

**Comment by evanshultz** [comment]
- Since your symbols are individual, we need to make the datasheet description singular. Change `ADCs with Bipolar Input Ranges` to `ADC with Bipolar Input Range`.
- It might be nice to add `, SPI Interface` after that in the description, but you have `spi` in the keywords so it's not required.
- Add `, TSSOP-38` to the end of the description.
- Use only Line style for the pins (no bubbles). Put an overbar on the letters instead.
- All pins should be 100mil long.
- I'd like to see SDO at the bottom of the SPI pins and DAISY at the top for easiest signal routing.
- Maybe scoot pin 2 closer to the SPI pins since it will go the host. Same with pin 4.
- Pin 5 isn't logic so it doesn't matter what pin type it may be connected to, and it may only connect to a capacitor, thus we've used Passive in the past for this type of pin.
- Pin 7 can be Passive type also.
- Pin 35 should be named DNC and push it in so the terminus is on the edge of the symbol body.
- AGND pins 28, 29, and 32 can be stacked. I would argue that page 58 (and elsewhere) is clear enough to stack all AGND pins; the description giving pin numbers is actually just telling the user to keep the analog decoupling paths as ideal as possible.
- These 2 parts need unique symbols since the `84 version has NC pins for inputs 4-7.

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks for the review, I agree with most of your points (I have lean a lot since this PR by reviewing and reading the KLC !) I will do the modifications asap.

Joel

**Comment by myfreescalewebpage** [comment]
Comment by comment:

> Since your symbols are individual, we need to make the datasheet description singular. Change ADCs with Bipolar Input Ranges to ADC with Bipolar Input Range.

Agree. Was copy/paste from datasheet.

> It might be nice to add , SPI Interface after that in the description, but you have spi in the keywords so it's not required.

OK, no modification.

> Add , TSSOP-38 to the end of the description.

Done.

> Use only Line style for the pins (no bubbles). Put an overbar on the letters instead.

Done.

> All pins should be 100mil long.

Done.

> I'd like to see SDO at the bottom of the SPI pins and DAISY at the top for easiest signal routing.

Agree. New arrangement of the pins looking at datasheet page 35.

> Maybe scoot pin 2 closer to the SPI pins since it will go the host. Same with pin 4.

Agree. I keep an extra space because that's not the same block.

> Pin 5 isn't logic so it doesn't matter what pin type it may be connected to, and it may only connect to a capacitor, thus we've used Passive in the past for this type of pin.

> Pin 7 can be Passive type also.

Still the same behavior and still my point of view, you can't do anything you want with this pin so it can't be Passive.

> Pin 35 should be named DNC and push it in so the terminus is on the edge of the symbol body.

Agree, done.

> AGND pins 28, 29, and 32 can be stacked. I would argue that page 58 (and elsewhere) is clear enough to stack all AGND pins; the description giving pin numbers is actually just telling the user to keep the analog decoupling paths as ideal as possible.

Agree for pins 8, 28, 29, 31, 32.

> These 2 parts need unique symbols since the `84 version has NC pins for inputs 4-7.

Agree, splitting in two devices.

Cheers,
Joel

**Comment by evanshultz** [comment]
Please change "Ranges" in the description to "Range". Also please update the screenshot in the first post or add fresh ones with all the visual changes done above.

I don't understand your objection to Passive type, which is what we've done elsewhere in the library. Especially for pin 7 since it only goes to a cap and should not really factor into any ERC checking. The ERC engine is extremely basic and making these pins Passive will avoid false positives (such as REFIO being an input coming from a linear regulator output which is of type Power Output). Input, Output, and Bidirectional types can catch a few issues with logic pins but it doesn't help with analog pins like this with the current capability of the KiCad ERC engine. I'm making suggestions so this PR conforms to the method that's been used on other recent symbols and thus will be consistent and require less discussion. https://github.com/KiCad/kicad-symbols/issues/381 and https://github.com/KiCad/kicad-website/issues/342 are a couple of discussions about pin types which would allow conversation about pin types to stay in one place and also avoid bogging down a PR with a bigger topic.

**Comment by myfreescalewebpage** [comment]
@evanshultz I understand the reason and I agree it will be better for ERC checking and consistency with other devices if already used like that.
I still have doubt the term "Passive" is correctly chosen, but for the above reason I agree to change my symbol.
Joel

**Comment by myfreescalewebpage** [comment]
@evanshultz additional comments ?

Cheers
Joel

**Comment by evanshultz** [comment]
Here is the current screenshot of the "big" one:
image

The position of SDO and DAISY should be flipped for the easiest signal routing.

I suppose you could shove the power pins to the right and squeeze down the symbol if you wanted to make it shorter, but I'm happy how it is already.

**Comment by myfreescalewebpage** [comment]
> The position of SDO and DAISY should be flipped for the easiest signal routing.

Depends where you place the first/last device of the chain. Here is an example that's works great with current symbol, with the first device at the top of the chain:

capture

Cheers,
Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Sorry that I'd forgotten about this. It looks like this is ready to merge. Yes?

**Comment by myfreescalewebpage** [comment]
@evanshultz no worries :) I have just checked again, on my side this is ready to merge.

**Comment by evanshultz** [comment]
Sounds good. Thanks and sorry for the delay!

**Pull request merged**
