### PR TITLE
Add EP to SE5004L.

### PR DESCRIPTION
**Pull request by matthuszagh**
SE5004L should have an EP pin.

datasheet: http://www.skyworksinc.com/uploads/documents/SE5004L_202393B.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Good catch @matthuszagh was forgotten at https://github.com/KiCad/kicad-symbols/pull/1258.

Seems the land pattern indicate that the EP must be connected to GND, isn't it ? Datasheet page 7. I would like to suggest that the EP pin need to be stacked with GND.

Joel

**Comment by matthuszagh** [comment]
I'm not seeing the part that says it should be connected to GND, I'm just seeing the dimensions and thermal via info. Mind sending a quote or screenshot of where you're seeing that?

**Comment by myfreescalewebpage** [comment]
You're right, no information. Just the pattern below:

capture

If you prefer keeping EP separated, let me known.

**Comment by matthuszagh** [comment]
Yeah I think we probably should keep them separate. I'm not sure why you wouldn't want to connect it, but if it's not explicitly required by the datasheet I think we should give people the option.

**Comment by myfreescalewebpage** [comment]
> I think we should give people the option.

OKay for me.

Merging.

**Pull request merged**
