### PR TITLE
Sensor_Optical: Add APDS-9306 and APDS-9306-065

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://docs.broadcom.com/docs/AV02-4755EN

imagen

imagen

Missing footprints. Will contribute when I make them.
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- The package name doesn't seem to be given, but I think `LGA-8` and `DFN-6` would be fine for the description.
- This is a bit pedantic, but I like to see ` with` replaced with a `,` in the description for brevity.
- Can you put ref des on the left and value on the right?
- Unless these packages are specific to these exact PNs, perhaps a more generic footprint name is best? It can still start with `Broadcom_` but maybe use the package description and not the MPN?
- As the INT pin is open drain, can you make it Open Collector type?

**Comment by antoniovazquezblanco** [comment]
> Unless these packages are specific to these exact PNs, perhaps a more generic footprint name is best? It can still start with Broadcom_ but maybe use the package description and not the MPN?

I will do as you ask me to but I am not sure on how to name them or wether theese are used for any other part.

**Comment by evanshultz** [comment]
We'll continue the footprint naming at that PR.

All other changes are good. Thanks!

**Comment by antoniovazquezblanco** [comment]
FP Merged, re triggering travis

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
