### PR TITLE
Add Honeywell CSLW Current Sensor

### PR DESCRIPTION
**Pull request by cp-aquila**
Add Honeywell CSLW Current Sensor

---
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

Datasheet: https://sensing.honeywell.com/honeywell-sensing-cslw-series-product-sheet-005861-1-en.pdf

grafik
grafik

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1540

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cp-aquila , thanks for contributing,

A few comments I have during my review:

- [ ] Name of pin 1 should be VS
- [ ] Name of pin 3 should be OUT

Else, just need to wait the footprint, please indicate the link to the footprint PR here when it will be submitted.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@cp-aquila ping :)

**Comment by cp-aquila** [comment]
Hi,
I do have a FP, but its hard to review/verify since most measurements are not in the datasheet.
So I am still stuck with the FP. Its not submitted yet since the datasheet is really sparse. I was hoping to get some more info about the part from honyewell. But it looks like that hope was in vain.
I will try again, if that fails I will submit the current FP (I already build a PCB with it and its working^^).

**Comment by myfreescalewebpage** [comment]
Great, thanks for your message. Take time to double check and if there is no information but you confirm it's working on your board, indicate it in the footprint pull request for the reviewer.
Joel

**Comment by cp-aquila** [comment]
Related FP: https://github.com/KiCad/kicad-footprints/pull/1540

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait for the integration of the footprint now :)

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the travis build.

**Comment by myfreescalewebpage** [comment]
@cp-aquila Just seen the footprint has been merged, no more comment here, merging the PR. Thanks!

**Comment by cp-aquila** [comment]
thanks!

**Pull request merged**
