### PR TITLE
Added ERM19264 192x64 graphic display

### PR DESCRIPTION
**Pull request by Dovgalyuk**
Added ERM19264 192x64 graphic display
datasheet: https://www.displayfuture.com/Display/datasheet/monographic/ERM19264-1.pdf
url: https://www.buydisplay.com/default/4-inch-192x64-lcd-module-graphic-display-ks0107-ks0108-black-on-white

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by Dovgalyuk** [comment]
Footprint pull request: https://github.com/KiCad/kicad-footprints/pull/1781

**Comment by myfreescalewebpage** [comment]
@Dovgalyuk thre is an unwanted modification of another library. Please check.

**Comment by Dovgalyuk** [comment]
Removed non-related changes.

**Comment by myfreescalewebpage** [comment]
Thanks

A few comments I have during my review:

- [ ] Footprint filter should be `ERM19264*`
- [ ] Name of pin 1 is VSS
- [ ] Name of pin 2 is VDD
- [ ] Name of pin 4 is RS
- [ ] Name of pin 19 is VOUT
- [ ] Name of pin 20 is BLA

Else, just need to wait the footprint.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes. One comment I have forgotten:

- [ ] Pin offset should be 20mil (see travis error)

Joel

**Comment by Dovgalyuk** [comment]
> Thanks for the fixes. One comment I have forgotten:
> 
> * [ ]  Pin offset should be 20mil (see travis error)
> 
> Joel

Sorry, but I don't understand this error. What is pin offset?

**Comment by myfreescalewebpage** [comment]
This is the distance between the name of the pin and the pin itself. Screenshot:

Capture

**Comment by Dovgalyuk** [comment]
Fixed. I didn't use GUI and copy-pasted the symbol specification with value of 40.

**Comment by myfreescalewebpage** [comment]
No worries. Thanks for the fix. Just need to wait the footprint now. Joel

**Comment by myfreescalewebpage** [comment]
@Dovgalyuk branch conflict to be solved here to merge the PR

**Comment by Dovgalyuk** [comment]
> @Dovgalyuk branch conflict to be solved here to merge the PR

Fixed.

**Comment by myfreescalewebpage** [comment]
Thanks, merging

**Pull request merged**
