### PR TITLE
Add Rohm EMH3, IMH3A and UMH3N dual NPN transistors

### PR DESCRIPTION
**Pull request by stefanct**
All three are described in http://rohmfs.rohm.com/en/products/databook/datasheet/discrete/transistor/digital/emh3t2r-e.pdf

Additionally (no pun intended) the first commit also fixes the pin names of MUN5211DW1 of which these are based on. However, there are some additional problems with those that I don't address here regarding grid alignment and resistor outline thickness. My new symbols don't have those issues though.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @stefanct , thanks for contributing,

A few comments I have during my review:

EMH3
- [ ] Fp filter: `SOT?563*`

UMH3N
- [ ] Fp filter `SOT?363*`

Else no comment to do and thanks also for the bug fix!

Cheers,
Joel

**Comment by stefanct** [comment]
Thanks. Fixed, rebased and pushed again.

**Comment by myfreescalewebpage** [comment]
Thanks. Merging.

**Comment by cp-aquila** [comment]
Hi @stefanct can you please elaborate what exactly those issues are? Perhaps open a bug-ticket?

**Comment by stefanct** [comment]
@cp-aquila I can't remember exactly other than what I wrote back then. If you look at the output of the [checker output](https://travis-ci.org/github/KiCad/kicad-symbols/builds/720930061) for MUN5211DW1 it is not aligned to the 100 mil grid. And I presume (from what I wrote) that the line thickness of the resistor does not comply to the KLC either but I did not check it.

I can't remember exactly but I think I did not fix those problems to not break existing designs or something... if you think it warrants an issue please open it after verifying what I just wrote.

**Comment by myfreescalewebpage** [comment]
@cp-aquila are you speaking of this PR ?

**Comment by cp-aquila** [comment]
No, I was refering to the 'problems' mentioned regarding the `MUN5211DW1`.

**Pull request merged**
