### PR TITLE
Add DirectFET transistors

### PR DESCRIPTION
**Pull request by evanshultz**
All non-automotive DirectFETs (including the Infineon name of CanPAK) list at https://www.infineon.com/cms/en/product/power/mosfet/ are included. They are all copies of a single N- or P-channel symbol, with only the default footprint and FPfilter changed.

Because of the symbol similarities I haven't shown them. And because of the large number of parts I haven't listed datasheets individually.

Notes:
- I used the Rds(on) that Infineon lists, which is sometimes typical and other times maximum.
- If the Ids was limited by silicon or package, I chose the lower of the two.
- Several footprints are currently missing, and I will create them soon.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
For simplicity of tracking, here are the missing footprints:
- L6
- MC
- MD
- MF
- S3C
- SA (note that this one is for _two_ transistors with a common drain)
- SB

**Comment by jkriege2** [comment]
From a few peeks that I took, this looks good to me ... should we merge this before the additioanl package are merged, or should we wait?

**Comment by evanshultz** [comment]
@jkriege2 
Thanks for checking! I'd like to merge now. The missing footprints will come shortly, and most of the symbols already have footprints.

**Comment by jkriege2** [comment]
OK

**Pull request merged**
