### PR TITLE
Added BelFuse SI-60062-F.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://belfuse.com/resources/drawings/magneticsolutions/dr-mag-si-60062-f.pdf
Footprint depends on PR: https://github.com/KiCad/kicad-footprints/pull/1954
Same symbol as RJ45_Amphenol_RJMG1BD3B8K1ANR, changed footprint, alias
and datasheet link.

imagen

imagen

### CODE REVIEW

**Comment by jneiva08** [comment]
@cnieves1 have checked the pin order and don't make much sense.

Have found the following links:
https://componentsearchengine.com/SI-60062-F/Bel
http://ww1.microchip.com/downloads/en/DeviceDoc/61166A.pdf page 22

SI-60062-F

**Comment by cnieves1** [comment]
You were right. They should be correct now.
L3 and L4 were exchanged in the footprint PR, to have a consistent numbering from left to right.

imagen

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] The tx/rx pins are called "T" in the datasheet, why choosing "R" ?

Else ok with the pinout according to the current latest revision of the footprint. Will check again when the footprint will be merged.

Cheers,
Joel

**Comment by cnieves1** [comment]
At the time I draw it, there was another RJ footprint I based this footprint PR on, with pin names R[1-8].
Isn't this right?

Captura de pantalla de 2020-04-29 08-42-17

Captura de pantalla de 2020-04-29 08-42-09

**Comment by myfreescalewebpage** [comment]
It's probably correct for the other device, but you should simply create your new symbol and your new footprint according to the right datasheet.

**Comment by myfreescalewebpage** [comment]
@cnieves1 ping

**Comment by cnieves1** [comment]
Hi Joel,
Sorry for the long delay... Life got complicated... I will try to fix it...

**Comment by myfreescalewebpage** [comment]
Thanks for the news, I keep an eye on it

**Comment by cnieves1** [comment]
Hi Joel,
In case you missed it, the requested changes are done, if I am not mistaken...

Thanks

**Comment by myfreescalewebpage** [comment]
Yes I know, waiting the footprint before the symbol can be merged :)

**Comment by myfreescalewebpage** [comment]
Personal note: pin name to be checked again after integration of the footprint

**Comment by myfreescalewebpage** [comment]
@cnieves1 can you update the pin names here following the integration of the footprint ? Then I think this will be ok.

**Comment by cp-aquila** [comment]
Pin13 should be called `SH`: https://kicad-pcb.org/libraries/klc/S3.7/

**Comment by myfreescalewebpage** [comment]
@cp-aquila yes we already change this on the footprint, I just wait @cnieves1 to make the symbol according to the footprint (see my previous comment)

**Comment by cp-aquila** [comment]
Sorry for the noise, I looked at an outdated screenshot.

**Comment by myfreescalewebpage** [comment]
No problem :)

**Comment by myfreescalewebpage** [comment]
@cnieves1 number of pin SH should be "SH", not 13, to match with the footprint
Joel

**Comment by cnieves1** [comment]
@myfreescalewebpage  Sorry! I changed pin name instead changing pin number... Fixed now. Thanks!

**Comment by myfreescalewebpage** [comment]
Thanks. May I require one more change, please: the pin length should be 100mil for this symbol. Other RJ45 symbol have 150mil but it's an error. I would like to improve all of them and starting with yours is a good point. Just set to 100mil and increase a little bit the size of the border outline to not draw again all the symbol.

**Comment by myfreescalewebpage** [comment]
Would like to have this before going to GitLab, accept the previous defect because it's already present for most RJ45, I know we have to make a global rework of them

**Comment by cnieves1** [comment]
Thanks Joel! I'm on a trip with no access to kicad, so I could do nothing...

**Comment by myfreescalewebpage** [comment]
No problem

**Pull request merged**
