### PR TITLE
TC7662Bx0A and TC7662BxPA V+ was misplaced.

### PR DESCRIPTION
**Pull request by sebastianbasierski**
Signed-off-by: Sebastian Basierski <sebastian@basierski.pl>

I noticed that power pins (V+) was misplaced and buried inside TC7662Bx0A and TC7662BxPA symbols.
This PR is fixing this issue.

### CODE REVIEW

**Comment by evanshultz** [comment]
@sebastianbasierski 
Confirmed the issue and this PR looks good. Why is it marked as a draft? This is a bug, properly marked as such by @chschlue, and should be merged into the library.

**Comment by chschlue** [comment]
Oops.
Meant to ask that exactly that.

**Comment by chschlue** [comment]
@sebastianbasierski ping

**Comment by sebastianbasierski** [comment]
Sorry, i was our of reach for a some time.
I will submit it today.

**Comment by chschlue** [comment]
Thanks

**Pull request merged**
