### PR TITLE
FSUSB42MUX: Addition of USB2.0 switch

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add FSUSB42MUX device to the library. Design based on USB3740 already in the library.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing

https://www.onsemi.com/pub/Collateral/FSUSB42-D.PDF

- [X] An example screenshot image is very helpful

Capture

- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [NA] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @cpresser thank for looking at my symbol! Any comments ?

**Comment by cpresser** [comment]
Sorry for the delay. I grabbed this because it seemed simple and wanted to do it right away. But I closed the browser tab and did forget about it. My bad!

Anyway, lets do some checks
- [x] pin electrical types
- [x] Data-sheet, description, keywords
- [x] Pin numbering
- [x] package and FP filter
- [x] Overall layout / pin locations
- [ ] PartName: I am not sure if we should wildcard some parts of the name (the last `X`?) I am not sure what all the letters stand for, I can't find it in the data-sheet.
- [ ] GND and VCC Text overlapping the pins on the right side. That looks ugly, But I don't see a really good solution. According to S3.2 it is allowed to change the Text size. To me changing the text size in this case does not feel right. What do you think?

**Comment by myfreescalewebpage** [comment]
@cpresser thanks for the review.
- The last "X" in the part name is not a wildcare (we use xx in lowercase for that in the lib). Instead, it's a letter which is part of the real name of the device.
- Yes the letters are not properly displayed on the right. I made myself the same remark but was waiting your position. The main interest to keep this design is because it is the same than the USB3740 (similar device in the lib). I have reduce the text size to 1mm, this give the following result:

Capture

**Comment by cpresser** [comment]
Thanks, the smaller font looks good.

Regarding the wildcard thing: That was a misunderstanding. I was asking if we want to replace any of the `MUX` with a lower case `x` to wildcard them. 
I don't know what the letters are for (I could also not find a onsemi reference for that), but I think it can be assumed that they somehow represent the package and perhaps the temperature range.
But since we don't know for sure if the letters are code for some properties, lets keep them in the name.

**Comment by myfreescalewebpage** [comment]
Yes we don't know exactly today.
Thanks for the review.

**Pull request merged**
