### PR TITLE
Added TMP1075 temperature sensors family

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.ti.com/lit/gpn/tmp1075
Based on PCT2075 (as an alias, or copying the symbol for new footprint).

Captura de pantalla de 2020-08-31 12-03-24
Captura de pantalla de 2020-08-31 12-04-20
Captura de pantalla de 2020-08-31 12-04-31
Captura de pantalla de 2020-08-31 12-04-44
Captura de pantalla de 2020-08-31 12-05-10

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @cnieves1 , thanks for the addition.

For part `TMP1075DSG `:

- [ ]  `OS `pin needs to be renamed to `ALERT`

- [ ] Package needs to be `Package_SON:WSON-8-1EP_2x2mm_P0.5mm_EP0.9x1.6mm_ThermalVias`
Not sure about `_ThermalVias`, i know this must not be default but this is how fp is presented at the datasheet.
εικόνα

- [ ] Filter must be changed accordingly with previous note

- [ ] Description should ends to `, WSON-8`

@myfreescalewebpage , please some input here.
About fp selection above.
And
About alliases, parent's symbols pin name is different for one pin, also not fp assigned to them.
I think it is better for new symbols to be added instead of alliases, can you please confirm?

Packages required for new symbols exist: `Package_SO:SOIC-8_3.9x4.9mm_P1.27mm` and `Package_SO:VSSOP-8_3.0x3.0mm_P0.65mm`

**Comment by cnieves1** [comment]
TravisCI build failed but no symbol's error is shown...

**Comment by evanshultz** [comment]
The error is because https://github.com/KiCad/kicad-symbols/pull/2789 was merged without adding entries into the sym-lib-table. That is the error at the bottom (error code is 2, while 0 means all is well). So not your fault, but that needs to get fixed. Sorry for the hassle.

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

First sorry for the travis question, this is my fault as mentioned by @evanshultz 

A few comments I have during my review:

All symbols:
- [ ] Name of pin 8 is "V+"

TMP1075DSG
- [ ] Where have you found EP is connected to GND ? I haven't. In this case, EP should not be stacked.

Cheers,
Joel

**Comment by aris-kimi** [comment]
Sorry, i missunderstood example layout. Checked again, nowhere mentioned..

**Comment by myfreescalewebpage** [comment]
@cnieves1 thanks for the update.

TMP1075DSG
- [ ] EP should be on the bottom, this is a convention we always use in the lib

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
