### PR TITLE
Added ADS1220IPWR ADC

### PR DESCRIPTION
**Pull request by G-Pereira**
ADC from TI symbol developed with ADS1120-PW (symbol already in library) as reference.
Datasheet: http://www.ti.com/lit/ds/symlink/ads1220.pdf

ADS1220IPWR
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @G-Pereira , thanks for contributing,

A few comments I have during my review:

- [ ] The symbol should be an alias of ADS1120-PW
- [ ] The name of the symbol should be "ADS1220xPW"

Cheers,
Joel

**Comment by G-Pereira** [comment]
That's smart, I will make those changes somewhere in the weekend.
Cheers!

**Comment by G-Pereira** [comment]
Ok, I've rebased and started over my contribution. 

>     * The name of the symbol should be "ADS1220xPW"
About this, I believe you misunderstood the part numbers. Please check again

**Comment by myfreescalewebpage** [comment]
"About this, I believe you misunderstood the part numbers. Please check again"

No, the "I" is the temperature ngae, which is always discard with an x in Kicad.
PW instead of PWR because the package is "PW" (page 64 of the datasheet).

=> ADS1220xPX

**Comment by myfreescalewebpage** [comment]
PS : please do not force push, we have to review again since the beginning because of this. When you just commit it is possible for us to review your new commit and validate the modifications. Thanks.

**Comment by G-Pereira** [comment]
> => ADS1220xPX only should be added.

Ok, thanks for the information. I didn't know that.

> please do not force push

Sorry, that makes total sense

**Comment by G-Pereira** [comment]
It should be ok now

**Comment by myfreescalewebpage** [comment]
Just notice I have made a mistake in my last comment. The first one was correct. The device should be "ADS1220xPW" instead of ADS1220xPX.

**Comment by G-Pereira** [comment]
Ok, fixed

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
