### PR TITLE
symbol: ACPL-336J

### PR DESCRIPTION
**Pull request by atari91**
Adds a new symbol: ACPL-336J into library Driver_FET
- datasheet: https://docs.broadcom.com/docs/AV02-4391EN

grafik

- Footprint associated with the symbol
- output of the outomated check script:
```
Checking symbol 'ACPL-336J':
  Violating S4.4
    Pin electrical type should match pin function
    Pin types should match pin function
```
I was not able to solve this warning. Pin type should match pin function.

---
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the official footprint library
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by atari91** [comment]
I changed the representation of the isolation barrier to a dashed line:
grafik

**Comment by myfreescalewebpage** [comment]
Hi @atari91 , thanks for contributing,

A few comments I have during my review:

- [ ] Use capital letters for all pin names
- [ ] UVLO and FAULT should be Open Collector
- [ ] VE should be on the top of the symbol
- [ ] VCLAMP should be Bidirectional
- [ ] VEE2 pins should be stacked

Cheers,
Joel

**Comment by atari91** [comment]
Hi @myfreescalewebpage ,
thanks for the review. I changed the symbol according your comments.

BR,
Dirk

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes. There is plenty of space lost, you can reduce on the left and on the right by 100mil:

Capture

**Comment by atari91** [comment]
You are right. I shrinked it even more:
grafik

**Comment by myfreescalewebpage** [comment]
Not bad, thanks!
Merging.

**Pull request merged**
