### PR TITLE
Adds Intel 8080 microprocessor

### PR DESCRIPTION
**Pull request by RobertBaruch**
Adds Intel 8080 microprocessor.

Datasheet: http://datasheets.chipdb.org/Intel/MCS-80/intel-8080.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @RobertBaruch , thanks for contributing,

A few comments I have during my review:

- [ ] Have you got more information about the packages ? Is it DIP ? PDIP ? Is there several versions ? It will be nice if footprint and footprint filter can be enhanced.
- [ ] Length of the pins should be 100mil (symbol < 100pins)
- [ ] The symbol is too large
- [ ] I have doubts about the position of the control pins, is it very convenient like that ? I have found http://0xdemo.com/wpsite/blog/wp-content/uploads/2017/09/8080and8228.png for example which seems great.

Cheers,
Joel

**Comment by RobertBaruch** [comment]
Thanks for the review!

* DIP only. I originally copied the footprint filters from the existing MCU_Intel components, but I narrowed down the filter to just DIP*W15.24*.
* Length changed to 100mil
* Symbol beshrankened
* The control pins are... not as random as before. The issue is that with specific helper chips, the control pins get bunched one way, and using other chips (e.g. Altair 8800) you get different groupings. I've changed the groups around a bit, mainly putting control and status pins that are related across from each other.

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes. I trust in you for pin grouping. Several new comments:

- [ ] Footprint field not filled, should be `Package_DIP:DIP-40_W15.24mm` (see also travis warning)
- [ ] Package should be added at the end of the description for both symbols: `8-bit N-channel Microprocessor, DIP-40`
- [ ] Height of the symbol can be reduced above A0 and below SYNC.

Joel

**Comment by RobertBaruch** [comment]
Done!

8080_v3

**Comment by myfreescalewebpage** [comment]
Thanks, no more comments, merging.

**Pull request merged**
