### PR TITLE
AT45DB161-RC, -JC, -TC Pin Alignment Fixes....And Then Some.

### PR DESCRIPTION
**Pull request by daab4848**
**Push Details** 
-----------------------------------------------------------------
**Part Name**: AT45DB161 (-RC, -JC, -TC suffixes denote different package types)
**Part Manufacturer**: Microchip
**Datasheet URL**: http://www.mouser.com/ds/2/268/atmel_doc0807-1066387.pdf
**Current Symbol Library**: Memory_Flash

**Symbol screenshots**:
image

image

image

**Additional comments/notes**
-Besides the pin-alignments, I noted that the SO pin (output type) is on the symbol(s) input side and the !RESET and !WS pins (input types) are on the symbol(s) output side. I did not fix this (yet) since the sole purpose of this PR was to fix the pin-alignment issues. However, I'll happily fix this mis-matching pin issue now if I am allowed to do so. Below is the proposed fix (this has not been committed yet)

image

-Since there are more inputs than outputs, the symbol seems unbalanced, aesthetically speaking, but it certainly fulfills the KLC requirements.

-In another note, the -TC and -RC version of the symbols do not appear to have valid footprints. I have no idea whether these footprints currently exist, in the process of a merge, or are still being made. 
 
######################################################################  

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@daab4848 
Thanks! The big list of fixes is almost cleaned up! I've checked these off the list.
1. Change all 161 datasheet links to http://ww1.microchip.com/downloads/en/devicedoc/doc0807.pdf and all 161B to http://ww1.microchip.com/downloads/en/devicedoc/doc2224.pdf.
1. Put the package type at the end of the description. And separate the package type and pin count by a hyphen. That would make AT45DB161B-RC-2.5 be `16Mb Serial DataFlash, 2.5V, SOIC-28`.
1. Change "TSSOP" in the description to "TSOP" (just one "S").
1. Set pin text offset to 20mil.
1. After doing the above, you may be able to shrink these symbols just a bit.
1. The JC part should use `Package_LCC:PLCC-32` as the default footprint and add a footprint filter of `PLCC?32*`.
1. All RC parts should use `Package_SO:SOIC-28W_8.7x18.25mm_P1.27mm` as the default footprint (it does not currently exist) and add a footprint filter of `SOIC?28*8.7x18.25mm*P1.27mm*`.
1. All TC parts should use `Package_SO:TSOP-28_11.8x8mm_P0.55mm` as the default footprint (it does not currently exist) and add a footprint filter of `TSOP?28*11.8x8mm*P0.55mm*`.
1. There is a pin named `RDY/~BUSY`, and it's missing the "S" in all symbols.
1. Set pin name text size to 50mil on all pins.

It doesn't matter if the pins look unbalanced on the symbol, but thanks for thinking of aesthetics! To me, since all pins only connect to a processor, I'd put all pins on the same side. That makes the interface cleaner if the KiCad user is drawing actual wires. If they're using net labels, it should be fine too. So what you do truly prefer? It will be fine to make a few additional changes in this PR.

**Comment by daab4848** [comment]
> Change all 161 datasheet links to http://ww1.microchip.com/downloads/en/devicedoc/doc0807.pdf and all 161B to http://ww1.microchip.com/downloads/en/devicedoc/doc2224.pdf.

-Fixed all datasheet links.

> Put the package type at the end of the description. And separate the package type and pin count by a hyphen. 
That would make AT45DB161B-RC-2.5 be 16Mb Serial DataFlash, 2.5V, SOIC-28.

-Fixed all descriptions.

> Change "TSSOP" in the description to "TSOP" (just one "S").

-Also fixed.

> Set pin text offset to 20mil.
> After doing the above, you may be able to shrink these symbols just a bit.

-Fixed pin text offset to 20mil.
-Decreased width of symbols by 100mil from each side.


> The JC part should use Package_LCC:PLCC-32 as the default footprint and add a footprint filter of PLCC?32*.
> All RC parts should use Package_SO:SOIC-28W_8.7x18.25mm_P1.27mm as the default footprint (it does not currently exist) and add a footprint filter of SOIC?28*8.7x18.25mm*P1.27mm*.
> All TC parts should use Package_SO:TSOP-28_11.8x8mm_P0.55mm as the default footprint (it does not currently exist) and add a footprint filter of TSOP?28*11.8x8mm*P0.55mm*.
> ...
> Set pin name text size to 50mil on all pins.

-All symbols have correct packages and footprint filters
-Pin names text sized to 50mil.

> There is a pin named RDY/~BUSY, and it's missing the "S" in all symbols.

-Do you mean the pin is missing a "U"? If so, I've included the "U" so the pin now reads "RDY/~BUSY" instead of "RDY/~BSY".


> It doesn't matter if the pins look unbalanced on the symbol, but thanks for thinking of aesthetics! To me, since all pins only connect to a processor, I'd put all pins on the same side. That makes the interface cleaner if the KiCad user is drawing actual wires. If they're using net labels, it should be fine too. So what you do truly prefer? It will be fine to make a few additional changes in this PR.

-See below for symbol screenshots. Personally, I think the functionality of the symbol precedes its aethetics 
(although it doesn't hurt to have neat and concise symbols either) and so I've decided to move the 
input and output pins to their respective sides of the symbol. 

image

image

image

**Comment by evanshultz** [comment]
I'm fine with everything except the pin number text size is 40mil and it needs to be 50mil. If you can make that change I'll merge.

Also, would you be willing to make either of the missing footprints? If not, that's fine.

**Comment by daab4848** [comment]
@evanshultz 

> I'm fine with everything except the pin number text size is 40mil and it needs to be 50mil. If you can make that change I'll merge.

-Pin number text size changed to 50mil. Pin lengths increased by 50mils to accommodate changes.

 > Also, would you be willing to make either of the missing footprints? If not, that's fine.

-I can make the missing footprints. I'll try getting a PR going sometime tomorrow

**Comment by evanshultz** [comment]
@daab4848 
You've now created all pins off-grid.

The library convention is to use 50mil pin names, 50mil pin numbers, and 100mil pin length if the pin names have two characters. There are surely symbols that are old or don't conform for some other reason, but the vast majority of symbols do. Check any library. This is the recommended style used because it's part of KLC, the rules for the official KiCad libraries.

Please change the pin lengths back to 100mil without changing anything else and I can merge.

If you dislike this style, that's fine and I encourage you to create an issue about it. State what you dislike and how it can be better. However, I don't want any discussion to delay getting this nice improvement you've made into the library. That's why I'm asking you to make the symbols conform now.

**Comment by daab4848** [comment]
> Please change the pin lengths back to 100mil without changing anything else and I can merge.

-Fixed (again). Apologies for the slight backwardness of the last commit, I had some confusion.

**Comment by evanshultz** [comment]
Thank you! This is a great improvement.

Please link to this PR if you submit footprints, and thanks for volunteering to do that!

**Pull request merged**
