### PR TITLE
Add ZXGD3009E6

### PR DESCRIPTION
**Pull request by strombom**
ZXGD3009E6
https://www.diodes.com/assets/Datasheets/ZXGD3009E6.pdf

image

image

Symbol copied from ZXGD3001E6 with pin 5 changed to no connect.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
I guess you should add the capsule to the description, that is
from
2A (peak) Gate driver, 40V
to
2A (peak) Gate driver, 40V, SOT-23-6

**Comment by strombom** [comment]
Added, thank you!

**Comment by strombom** [comment]
Added SOT-23-6 to the existing ZXGD symbols also.

**Comment by jkriege2** [comment]
Nice work!

thanks,
JAN

**Pull request merged**
