### PR TITLE
Add new high-power SMD diodes

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.vishay.com/docs/85153/bzd27series.pdf

https://assets.nexperia.com/documents/data-sheet/PMEG4050EP.pdf

https://www.vishay.com/docs/94987/vs-6esu06hm3.pdf

image

This is add in symbols for new footprints at:
- https://github.com/KiCad/kicad-footprints/pull/1724
- https://github.com/KiCad/kicad-footprints/pull/1725

And a corrected footprint at https://github.com/KiCad/kicad-footprints/pull/1727.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
I think GH just loses it's mind if MASTER changes an adjacent line to the changes in this PR. I tried hacking around manually but it seems no dice. I'm not a Git wizard and I'm sure there's a way to fix this with more Googling and experimentation. If anyone has suggestions I'm happy to hear it, otherwise time for a new PR?

**Comment by chschlue** [comment]
Not completely sure I didn't miss anything, but this one is actually easy to resolve by just taking the version from your `new-diodes` branch.

**Comment by evanshultz** [comment]
Do you mean take the changes into a new branch (and then PR)? If not, I don't follow you.

**Comment by chschlue** [comment]
No... not sure how to express it...

Git essentially complains that BZD27Cxx from your new-diodes conflicts with... well.. nothing between BYV79-200 and BZM55Bxx in kicad-master (don't ask).

Give me a second.

**Comment by chschlue** [comment]
There you go.

**Comment by evanshultz** [comment]
Thanks! Neither GitHub Desktop nor the command line would let me merge master into my branch. They both whined about the conflict.

**Comment by chschlue** [comment]
PMEG4050EP looks good.
Why the wildcards at the end of BZD27C?
And why the RoHS and automotive suffixes after VS-6ESU06?

**Comment by evanshultz** [comment]
- Because BZD27C is a series of zener diodes. See our other zener symbols which have a similar `xx` in the symbol name.
- I didn't realize that this part of the MPN was non-functional stuff. Good catch. Fixed.

**Comment by chschlue** [comment]
I get that it's a series.
But the Zener voltages are 2-3 characters + P _and_ they're trailing, so I was wondering what value the xx adds here.

**Comment by evanshultz** [comment]
All zener symbols I see use two `x` for the zener voltage which can be 2-4 characters. Do you want me to add a trailing `P`? Or you have another suggestion?

**Comment by chschlue** [comment]
If xx-means-voltage-trailing-or-not is the way to go in the diodes lib, fine by me.
Just asking because the existing symbols are far from consistent (some xx, some xxx, a lot of DZ2S... aliases for every available voltage).

**Comment by evanshultz** [comment]
Yeah, I went with the "not adding more entropy even in the face of messiness" solution here.

**Pull request merged**
