### PR TITLE
MCU_Microchip_PIC16: Add PIC16F18325 QFN variants

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Hand made, not scripted. Please note that the datasheet asks for a 2.6mm nominal size EP while this is not available in the current footprint library. I have chosen the 2.5mm EP footprint.

ww1.microchip.com/downloads/en/DeviceDoc/40001795E.pdf

imagen

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Plese beware that the library format has been updated and for that reason travis thinks that many symbols have changed.

I have only added `PIC16F18325-xJQ` and an alias `PIC16LF18325-xJQ`

**Comment by antoniovazquezblanco** [comment]
Solved:
imagen

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by evanshultz** [comment]
Thanks! All looks good. Just need the footprint.

**Comment by evanshultz** [comment]
Thanks!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
