### PR TITLE
add Mini-Circuits High Pass Filter SCHF-31+

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/SCHF-31+.pdf

schf-31

land-pattern PL-049, to-do.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
ToDo: Footprint PL-049 was merged, but name was changed!

**Comment by antoniovazquezblanco** [comment]
Footprint merged

**Comment by myfreescalewebpage** [comment]
Hi @aewallin 

Same comments already fixed at #1215 

Cheers,
Joel

**Comment by aewallin** [comment]
after revision:
schf-31

**Comment by myfreescalewebpage** [comment]
@aewallin thanks.

One question, for the footprint filter we previously put PLxxx. What is the real name of the footprint according to you, it's not clear for me ?

Actual footprint filter: Mini?Circuits*YY161*``
If following the previous lofic: `Mini?Circuits*PL?049*`

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@aewallin Understood thanks. In this case, can you propsoe a modification of the fp filter (+description) for the ADE-6, SXBP-140 and LRPS-2-1 we previously merged ?

No more comment on this one, merging.

Joel

**Pull request merged**
