### PR TITLE
Add MAX17263 Fuel Gauge symbol

### PR DESCRIPTION
**Pull request by MatthewStephenson**
Add symbol for the MAX17263 Fuel Gauge

Datasheet: [https://datasheets.maximintegrated.com/en/ds/MAX17263.pdf](https://datasheets.maximintegrated.com/en/ds/MAX17263.pdf)

Screenshot:
image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @MatthewStephenson , thanks for contributing,

A few comments I have during my review:

- [ ] The name of the device should be "MAX17263xxTE"
- [ ] Double spaces in the description and also missing the package at the end: `Single/Multi-Cell Fuel Gauge, ModelGauge m5 EZ, Integrated LED ControlD, TDFN-14` is great
- [ ] Footprint filter should be `DFN*1EP*3x3mm*P0.4mm*`
- [ ] You should align GND with BATT
- [ ] Pin 11 should be Power Output
- [ ] Pin 1 should be Passive

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@MatthewStephenson ping

**Comment by myfreescalewebpage** [comment]
No news of the original author, indicate the PR is abandoned.

**Comment by MatthewStephenson** [comment]
@myfreescalewebpage Sorry for the radio silence - I had a baby.

Hope these changes are correct.

**Comment by myfreescalewebpage** [comment]
> I had a baby.

No worries and congrats !!!

Yes the update are perfect. No more comment, merging.

Joel

**Pull request merged**
