### PR TITLE
Add Finder 36.11 10A SPDT relay symbol

### PR DESCRIPTION
**Pull request by chschlue**
Add Finder 36.11 10A SPDT relay symbol

Datasheet: https://gfinder.findernet.com/public/attachments/36/EN/S36EN.pdf
Footprint: https://github.com/KiCad/kicad-footprints/pull/1728

Violating S5.1: Pending footprint

3611sym

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Depends on https://github.com/KiCad/kicad-website/issues/418

**Comment by chschlue** [comment]
@evanshultz 
This poor symbol feels very sad and lonely. It wants to join its brother https://github.com/KiCad/kicad-footprints/pull/1728

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Not sure the conclusion about relay naming will be done soon, and this is only 1 symbol in the entire library. Will not be an important work to change this one later (v6?). Merging now.

**Pull request merged**
