### PR TITLE
Added 4009, 4010 Hex Buffers with separated VCC, VDD and high sink cu…

### PR DESCRIPTION
**Pull request by xennonflash**
Added 4009, 4010 Hex Buffers with separated VCC, VDD and high sink current capability.
4009 (inverter) and 4010 can be used to convert cmos level (Vcmos=VDD) to ttl level (Vttl=Vcc)
and invert (4009) or not (4010) the logic.
4009 and 4010 have high current sink capability.

I generated them from the 4000 lib based on 4049 and 4050 which are pin compatible but lack the VCC and VDD split feature. So I edited the file with an editor and checked with KICAD library editor if my edits were correct.
Also I checked the pinning according to the data sheets.

Cheers xennonflash

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @xennonflash , thanks for contributing,

A few comments I have during my review:

- [ ] For both symbols, pin 13 (NC) is missing, should be added to the symbol, Passive, Invisible, on the border outline of the symbol
- [ ] For both symbols, the keywords are too much, just write "cmos" like the other 4xxx is enought

Cheers,
Joel

**Comment by evanshultz** [comment]
@xennonflash 
Please take a look at the auto-generated notes in the first post above. One of the requirements is to post an image of the symbols. Could you please do that?

Having hidden power pins is a problem across this library and should be addressed for the next major KiCad release. I would like to maintain the style in this library even if it's bad at this time.

**Comment by myfreescalewebpage** [comment]
@evanshultz do you suggest I should merge right now without the NC pin ?

**Comment by evanshultz** [comment]
I'm only suggesting that we stick with the style in the library already for consistency, even if the current style is bad. I'm not sure how this particular symbol could work with hidden power pins, since there are two positive supplies for I and O, but in general I wouldn't deviate from the current style since v6 is going to take a while.

@xennonflash 
In addition to an image of the symbols, you're requested to provide the datasheet link.

Thanks for contributing and welcome!

**Comment by myfreescalewebpage** [comment]
Ok, merging now :) The library should be unified later.

**Pull request merged**
