### PR TITLE
Add SKY65404.

### PR DESCRIPTION
**Pull request by matthuszagh**
http://www.skyworksinc.com/uploads/documents/SKY65404_31_201512K.pdf

image

footprint: https://github.com/KiCad/kicad-footprints/pull/1289

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] The package is "QFN", not "DFN". To be changed in footprint, footprint filter and description.
- [ ] Name of pin 1 should be "V_ENABLE"

Cheers,
Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage, this confused me because although the datasheet says qfn there are only pins on two sides.

As for V_ENABLE, I also changed RF_IN and RF_OUT to RFIN and RFOUT to make them fit on the symbol. What do you think here? Do I need to go with the exact names on the datasheet? Otherwise I will have to either:
1. make the symbol bigger (probably quite a bit bigger because it's hard to make triangles bigger while keeping the 100mil pin grid)
2. move the input lower
3. or something else that will probably also look bad.

**Comment by myfreescalewebpage** [comment]
> this confused me because although the datasheet says qfn there are only pins on two sides.

Agree, but I think this makes confusion if not following the datasheet.

> As for V_ENABLE, I also changed RF_IN and RF_OUT to RFIN and RFOUT to make them fit on the symbol. What do you think here? Do I need to go with the exact names on the datasheet? Otherwise I will have to either:

That's right, haven't cached the RF pins. That's always better to avoid confusion. However here I think this is not a priority, I don't see any possibility to get confused. You can keep current names.

**Comment by matthuszagh** [comment]
I made the footprint changes.

**Comment by myfreescalewebpage** [comment]
No worries.
Just need to wait for the footprint now here.
Joel

**Comment by matthuszagh** [comment]
Changes made.

**Comment by myfreescalewebpage** [comment]
@matthuszagh thanks, no more comment to do here, merging.

**Pull request merged**
