### PR TITLE
add ADCH-80[A] RF chokes

### PR DESCRIPTION
**Pull request by hvraven**
This adds the RF Chokes [ADCH-80](https://ww2.minicircuits.com/pdfs/ADCH-80+.pdf) and [ADCH-80A](https://ww2.minicircuits.com/pdfs/ADCH-80A+.pdf) (they only differ by pins used).

No drawing inside as I could not find an inductor without increasing the symbol a lot. But I used `L` for the reference as they are inductors.

Screenshot_20190724_080254

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by lorem-ipsum** [comment]
I've added a second unit containing the NC pins. In the datasheet they are listed as "not connected" (opposed to "do not connect") and for RF applications it can be interesting to tie them to something (GND most likely). Also fixed the datasheet URL from ww2 -> www  as for the other Mini-Circuits components.

The library check complains about the stacking of the NC pins. I could also separate them into individual pins, but I thought a stack would be better. The symbol now looks like this:
Screenshot_20190905_100259
Screenshot_20190905_100328

**Comment by myfreescalewebpage** [comment]
Hello @lorem-ipsum 

I'm not sure of the design, the second unit is ... strange. I sugegst to make only one unit:

Capture

Also, if you succeed to make an inductor symbol inside, it can be very nice, as done for the other mini circuit symbols.

Joel

**Comment by lorem-ipsum** [comment]
I could fit an inductor drawing by extending the symbol towards the top. I don't see a solution how to fit in the current space. I don't find the extra size to bad as it makes the symbol symmetric, but it makes it larger. Your opinion on this?
Screenshot_20200514_115401

**Comment by myfreescalewebpage** [comment]
Not bad, the design is great! I'm thinking to NC pins, why stacking ? I also wonder why I have made a proposition with NC visible....

- [ ] ADCH-80 the pin 5 is not properly placed

**Comment by myfreescalewebpage** [comment]
@hvraven ping

**Comment by myfreescalewebpage** [comment]
@hvraven ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by hvraven** [comment]
Hi @myfreescalewebpage ,

I had in mind there was some note to connect the NC pins to GND, thats why I made them visible in the first place. There doesn't appear to be such a note, so I burried them in the body now. Also fixed the pin 5 of ADCH-80A. Looks like this now:
Screenshot_20200826_102341

**Comment by myfreescalewebpage** [comment]
Looks great here too!

**Pull request merged**
