### PR TITLE
Added Si7141DP

### PR DESCRIPTION
**Pull request by 0xdec**
Datasheet: https://www.vishay.com/docs/65596/si7141dp.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@0xdec 
Thanks for contributing to the libraries! I see this is your first time but this symbol looks great so you know what to do already! :)

Can you please make one change: Add `Single*` onto the end of the footprint filter so that the dual version of this footprint won't be caught by CvPcb?

**Comment by 0xdec** [comment]
@evanshultz Thanks for the kind words! I copied the standard PFET symbol already in the libraries so the credit does not belong to me :).

Just made the change you requested!

**Comment by evanshultz** [comment]
Thank you!

In the future, please don't force push commits. We can squash merge to keep the commit history clean, but incremental commits make reviewing each PR easier.

**Comment by 0xdec** [comment]
Ah, sorry about that, force push was the preferred method in some other projects I've contributed to, I'll calibrate my future practices here.

**Pull request merged**
