### PR TITLE
Add ATtiny202/402/212/412

### PR DESCRIPTION
**Pull request by fauxpark**
Datasheets:
202/402 http://ww1.microchip.com/downloads/en/DeviceDoc/ATtiny202-402-AVR-MCU-with-Core-Independent-Peripherals_and-picoPower-40001969A.pdf

212/412 http://ww1.microchip.com/downloads/en/DeviceDoc/40001911A.pdf

The 212/412 are also added in #798 and #848, however all of the symbols in those two PRs can in fact be aliases of lower-end devices (ATtiny202, ATtiny204, ATtiny406 and ATtiny807).

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Is this symbol maintaining compatibility with any other symbol? Would spreading out PA3 and PA6 make it more interchangeable with any other symbol(s)?

You reference two PRs above which now have broken branches. Can you please confirm if this PR is merged that nothing in those two PRs would be missed?

**Comment by fauxpark** [comment]
> Is this symbol maintaining compatibility with any other symbol? Would spreading out PA3 and PA6 make it more interchangeable with any other symbol(s)?

Looks like this is the only one, but there is the ATtiny204/404/214/414 up next, it has the full port A and PB0-3 on the left side. However the pin assignment is different (SOIC-14 vs SOIC-8):



> Can you please confirm if this PR is merged that nothing in those two PRs would be missed?

This PR should cover the 212/412 symbols added in both.

**Comment by evanshultz** [comment]
Then I'll leave it up to you. If you want to change anything for the upcoming symbols you mentioned that's fine. If not, let me know and I'll merge this and close the other PRs. Thanks!

**Comment by fauxpark** [comment]
I think we're good to merge.

**Comment by evanshultz** [comment]
Merged and the other PRs are closed. Thanks again!

**Pull request merged**
