### PR TITLE
Added Johanson CC11xx baluns, for 433, 868 and 915Mhz

### PR DESCRIPTION
**Pull request by cnieves1**
Symbol derived from Johanson 5400BL15B050, changing pin 6 from NC to GND.
Footprint: https://github.com/KiCad/kicad-footprints/pull/2191
Datasheets:
  https://www.johansontechnology.com/datasheets/0433BM15A0001/0433BM15A0001.pdf
  https://www.johansontechnology.com/datasheets/0868BM15C0001/0868BM15C0001.pdf
  https://www.johansontechnology.com/datasheets/0896BM15A0001/0896BM15A0001.pdf
  https://www.johansontechnology.com/datasheets/0915BM15A0001/0915BM15A0001.pdf
Symbol:
Captura de pantalla de 2020-04-02 12-04-29
0433BM15A0001:
Captura de pantalla de 2020-04-02 12-05-29
0868BM15C0001:
Captura de pantalla de 2020-04-02 12-05-14
0896BM15A0001:
Captura de pantalla de 2020-04-02 12-05-42
0915BM15A0001:
Captura de pantalla de 2020-04-02 12-05-55

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Regarding S3.1, the symbol is centered. TravisCI calculation offset is due to GND pin, which is vertical instead of horizontal as the others. Anyway, center is exactly the same as 5400BL15B050 symbol.

**Comment by myfreescalewebpage** [comment]
hello @cnieves1 
No comment to do here, just need to wait the footprint.
Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging the symbol now

**Pull request merged**
