### PR TITLE
add MAX5717 and MAX5719 DACs

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the [MAX5717/MAX5719](https://datasheets.maximintegrated.com/en/ds/MAX5717-MAX5719.pdf) ADCs (16/20 bit variant).

Screenshot_20190717_222554

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

MAX5717
- [ ] The name of the device should be `MAX5717GSD+`

MAX5719
- [ ] The name of the device should be `MAX5719GSD+`

Else no comment to do.

Cheers,
Joel

**Comment by chschlue** [comment]
> * [ ]  The name of the device should be `MAX5717GSD+`

`G` indicates temp range, `+` indicates RoHS status.
See https://www.maximintegrated.com/en/design/packaging/package-information/maxim-naming-conventions.html

**Comment by myfreescalewebpage** [comment]
I wasn't aware of this page, thanks for the link !
Thus the name of the devices should be "MAX5717xSD" and "MAX5719xSD" (fix my previous comment)
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

thanks for the review, I appended the ending to the name of the chips.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
