### PR TITLE
Added BQ24166RGE and BQ24167RGE battery chargers.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.ti.com/lit/ds/symlink/bq24166.pdf
Captura de pantalla de 2020-04-06 11-37-09
Captura de pantalla de 2020-04-06 11-41-24

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Captura de pantalla de 2020-04-06 13-24-46

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter should be `Texas*RGE0024H*`
- [ ] BGATE should be Output
- [ ] DRV should be Output
- [ ] USB should be Power Input
- [ ] VDPM should be Input

Cheers,
Joel

**Comment by cnieves1** [comment]
Done:
Captura de pantalla de 2020-04-10 12-31-43

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
