### PR TITLE
Added symbols for TE PE0xxFxx bistable latching relays.

### PR DESCRIPTION
**Pull request by amil109**
Added symbols for TE PE0xxFxx bistable latching relays.

Based on OMRON G5Q-1 footprint.

https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FPE_bistable%7F0919%7Fpdf%7FEnglish%7FENG_DS_PE_bistable_0919.pdf%7F3-1415390-1

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ x ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ x ] An example screenshot image is very helpful

TE_PE0xxFxx_CO_symbol
TE_PE0xxFxx_NO_symbol

- [ x ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ x ] If there are matching footprint PRs, provide link(s) as appropriate

https://github.com/KiCad/kicad-footprints/pull/2225

- [ TBC ] Check the output of the Travis automated check scripts - fix any errors as required
- [ NA ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @amil109 

You have unwanted modifications on this PR (MAX4820 and MAX4821), see https://github.com/KiCad/kicad-symbols/pull/2649/files

Can you cleanup before I start the review ?

Thanks
Joel

**Comment by amil109** [comment]
Hi Joel,

Sure - I've removed the files, sorry about that!

Kind regards,

Andrew

**Comment by myfreescalewebpage** [comment]
Well, I do not expect you to remove the file. Git diff still not correct I think. See above link.

**Comment by amil109** [comment]
Hi Joel,

Sorry - I had misunderstood - I think it should be correct now. Driver_Relay.dcm and Driver_Relay.lib are not related to this pull request, they snuck in there because they are also changed in my library (and I'm not very good with Git yet sorry!).

I've updated the Relay.dcm and Relay.lib files to only include the additions I made - I'm honestly not sure why the other relay moved in the library, but it should be sorted now in any case.

Cheers,

Andrew

**Comment by myfreescalewebpage** [comment]
> Driver_Relay.dcm and Driver_Relay.lib are not related to this pull request, they snuck in there because they are also changed in my library

I understood that but they should not be modified in the pull request. I cannot merge a part of the pull request only. The content of the git diff on the pull request should be the EXACT modifications you made.

You can recreate again the pull request if you think it will be easier.

Joel

**Comment by amil109** [comment]
Right - I think I understand now. Sorry for the confusion, and thank you for explaining it!

Closing this PR, replaced with #2946 .

**Pull request closed without merging**
