### PR TITLE
Add Ublox ZED F9P

### PR DESCRIPTION
**Pull request by jneiva08**
Add symbol for Ublox ZED F9P

Datasheet: https://www.u-blox.com/sites/default/files/ZED-F9P_DataSheet_(UBX-17051259).pdf
Footprint: https://github.com/KiCad/kicad-footprints/pull/1600

Symbol:
ublox_zed

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] The format of the description can be enhanced for consistency with previous GPS modules, I propose `GNSS Module ZED F9, VCC 2.7V to 3.6V`
- [ ] VCC_RF should be Power Output
- [ ] Pin 31 is not placed correctly
- [ ] Pin 54 is missing
- [ ] The position of the pins is not consistent with previous ublox modules, for example NEO series, I suggest the following:

Capture

```
#
# ZED-F9P
#
DEF ZED-F9P U 0 20 Y Y 1 F N
F0 "U" -550 1050 50 H V C CNN
F1 "ZED-F9P" 450 1050 50 H V C CNN
F2 "RF_GPS:ublox_ZED" 0 -1550 50 H I C CNN
F3 "" -600 -400 50 H I C CNN
$FPLIST
 ublox*ZED*
$ENDFPLIST
DRAW
S -600 1000 600 -1000 0 1 10 f
X GND 1 0 -1100 100 U 50 50 1 1 P N
X Reserved 10 -600 300 100 R 50 50 1 1 N N
X Reserved 11 -600 0 100 R 50 50 1 1 N N
X GND 12 0 -1100 100 U 50 50 1 1 P N
X Reserved 13 -600 -300 100 R 50 50 1 1 N N
X GND 14 0 -1100 100 U 50 50 1 1 P N
X Reserved 15 -600 -500 100 R 50 50 1 1 N N
X Reserved 16 -300 -1000 100 U 50 50 1 1 N N
X Reserved 17 -200 -1000 100 U 50 50 1 1 N N
X Reserved 18 -100 -1000 100 U 50 50 1 1 N N
X GEOFENCE_STAT 19 700 -600 100 L 50 50 1 1 O
X RF_IN 2 700 200 100 L 50 50 1 1 I
X RTK_STAT 20 700 -500 100 L 50 50 1 1 O
X Reserved 21 100 -1000 100 U 50 50 1 1 N N
X Reserved 22 200 -1000 100 U 50 50 1 1 N N
X Reserved 23 300 -1000 100 U 50 50 1 1 N N
X Reserved 24 600 -300 100 L 50 50 1 1 N N
X Reserved 25 600 -200 100 L 50 50 1 1 N N
X RXD2 26 -700 100 100 R 50 50 1 1 I
X TXD2 27 -700 200 100 R 50 50 1 1 O
X Reserved 28 600 -100 100 L 50 50 1 1 N N
X Reserved 29 600 0 100 L 50 50 1 1 N N
X GND 3 0 -1100 100 U 50 50 1 1 P N
X Reserved 30 600 100 100 L 50 50 1 1 N N
X Reserved 31 600 300 100 L 50 50 1 1 N N
X GND 32 0 -1100 100 U 50 50 1 1 P N
X VCC 33 -200 1100 100 D 50 50 1 1 P N
X VCC 34 -200 1100 100 D 50 50 1 1 W
X Reserved 35 600 700 100 L 50 50 1 1 N N
X V_BCKP 36 -100 1100 100 D 50 50 1 1 W
X GND 37 0 -1100 100 U 50 50 1 1 P N
X V_USB 38 0 1100 100 D 50 50 1 1 W
X USB_DM 39 -700 800 100 R 50 50 1 1 B
X ANT_DETECT 4 700 500 100 L 50 50 1 1 I
X USB_DP 40 -700 700 100 R 50 50 1 1 B
X GND 41 0 -1100 100 U 50 50 1 1 P N
X TXD/SPI_MISO 42 -700 500 100 R 50 50 1 1 O
X RXD/SPI_MOSI 43 -700 400 100 R 50 50 1 1 I
X SDA/~SPI_CS 44 -700 -100 100 R 50 50 1 1 B
X SCL/SPI_CLK 45 -700 -200 100 R 50 50 1 1 B
X TX_READY 46 700 -700 100 L 50 50 1 1 O
X D_SEL 47 -700 -800 100 R 50 50 1 1 I
X GND 48 0 -1100 100 U 50 50 1 1 W
X ~RESET 49 -700 -700 100 R 50 50 1 1 I
X ANT_OFF 5 700 600 100 L 50 50 1 1 O
X ~SAFEBOOT 50 -700 -600 100 R 50 50 1 1 I
X EXTINT 51 -700 -400 100 R 50 50 1 1 I
X Reserved 52 600 800 100 L 50 50 1 1 N N
X TIMEPULSE 53 700 -400 100 L 50 50 1 1 O
X Reserved 54 600 900 100 L 50 50 1 1 P N
X GND 55 0 -1100 100 U 50 50 1 1 P N
X ~ANT_SHORT 6 700 400 100 L 50 50 1 1 I
X VCC_RF 7 200 1100 100 D 50 50 1 1 w
X Reserved 8 -600 900 100 R 50 50 1 1 N N
X Reserved 9 -600 600 100 R 50 50 1 1 N N
ENDDRAW
ENDDEF
```

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage changes made, probably is only missing the footprint

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes, yes just need to wait the footprint now.
Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh Travis.

**Comment by myfreescalewebpage** [comment]
Travis fails but unknown reason....
Verified manually, seems ok.
Merging the symlbol, thanks !!

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
