### PR TITLE
Adding CAT24C128 (alias for 24LC16)

### PR DESCRIPTION
**Pull request by ki5libs**
Adding CAT24C128 (alias for 24LC16)
[Datasheet](https://www.onsemi.com/pub/Collateral/CAT24C128-D.PDF)
cat24c128

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
I'll allow it since it's an ALIAS and the symbol already exists in this format, but I note the following issues:
1. The SOIC footprint filter doesn't have the pin pitch specified.
2. The DFN package should be a separate symbol because there is no pin 9.

Please let me know if you're willing make any of those updates. If not, I'll merge and they can be done later.

**Comment by ki5libs** [comment]
@evanshultz I think that all of the issues of this symbol are the same for CAT24C256, which is already an alias of the 24LC16 in the library. And there are some more aliases for that symbol which have similar issues. For example 24LC16 do not have DFN package at all though it's present in the footprint  filter because of aliases. I don't know the exactly right way to resolve all of issues, but anyway I think that resolving of that should not be part of this small PR.
Please merge it, and tell me if you know how to fix these issues. I could do it later.

Why footprint filter is not unique for each alias like description or documentation?

**Comment by antoniovazquezblanco** [comment]
Closing and reopening for CLA.

**Comment by antoniovazquezblanco** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
Missed this. Done now.

To answer the question above: There are two different ways to handle a part that comes in multiple packages. We can either put no default footprint and many FP filters (done here) or make many unique symbols, one for each footprint. The library is gravitating towards the latter for new symbols and when updates are made.

**Pull request merged**
