### PR TITLE
Add microMELF diode symbols

### PR DESCRIPTION
**Pull request by evanshultz**
Simple copies of the existing diode symbols with an updated package and some ALIASes.

http://www.vishay.com/docs/85597/bzm55.pdf
image

http://www.vishay.com/docs/85566/mlc4148.pdf
http://www.vishay.com/docs/85545/bav300.pdf
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by lorem-ipsum** [comment]
MLC and BZM look good. Two comments about the BAV-series:
- BAV303 has a lower current in the description. Couldn't find any differences in the datasheet
- Wouldn't it make more sense to use the reverse voltage in the description instead of the repetitive peak reverse voltage?

**Comment by evanshultz** [comment]
- Oops. Fixed!
- I've changed it as you mentioned. KLC doesn't really control descriptions and there is a conversation about it at https://github.com/KiCad/kicad-symbols/issues/1617. Without any guidance or consistency I selected the value that I like to see, which is why the descriptions for many parts vary greatly within a library.

Thanks for checking!

**Comment by cpresser** [comment]
I dont quite understand the 4148 datasheet. It says 
> Electrical data identical with the devices 1N4148 
and 1N4448 respectively

But then there is this table:
image

Anyway, this looks good. Drawing and Footprints+Filter look good. As do description, keywords and data-sheet links.

**Comment by evanshultz** [comment]
Thanks!

I believe the datasheet is saying that 1N4148 and MCL4148 are the same electrically, just like 1N4448 and MCL4448. Not that MCL4148 and MCL4448 are the same electrically.

**Pull request merged**
