### PR TITLE
Amplifier_Operational: Add TLV9064 quad CMOS OpAmp

### PR DESCRIPTION
**Pull request by zonque**
Add TI TLV9064 in 16-pin PWQFN package.

The symbol is split in 4 amp units and one power unit.

image
image

The footprint is pending in the footprint generator repository: https://github.com/pointhi/kicad-footprint-generator/pull/590

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @zonque , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "TLV9064xRTE"
- [ ] You have to push the footprint on footprint repo too, not only on the generator repo
- [ ] Fp filter: `Texas*S*PWQFN*N*`
- [ ] Description should ends with package name: `Quad 10-MHz RRIO CMOS Operational Amplifier, Texas S-PWQFN-N16`
- [ ] You should cross negative and positive inputs (negative input above positive input generally in the lib)
- [ ] NC pins should be added, called NC, Invisible, type Not connected, on the border outline of the symbol (one on unit A and one on unit B for example)

Cheers,
Joel

**Comment by zonque** [comment]
Footprint is now in a PR here: https://github.com/KiCad/kicad-footprints/pull/2450

**Comment by zonque** [comment]
Changed the following things now:

    * Swapped + and - pins
    * Added SHDN12 and SHDC34 pins to units A and C, respectively
    * Changed symbol name
    * Fixed footprint filter

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
@zonque
- [ ] Package at the end of the description should be `QFN-16`
- [ ] Fp filter should be `QFN*1EP*3x3mm*P0.5mm*`

Joel

**Pull request closed without merging**
