### PR TITLE
Add Texas Instruments LM5023, QR PWM controller for off-line supplies

### PR DESCRIPTION
**Pull request by yankee14**
Add Texas Instruments LM5023, QR PWM controller for off-line supplies

The pin arrangement pretty much breaks [KLC S4.2](https://kicad-pcb.org/libraries/klc/S4.2/), but the purpose is to facilitate easy connection as shown in the screenshot below.

Datasheet: https://www.ti.com/lit/ds/symlink/lm5023.pdf
Video: https://www.youtube.com/watch?v=OKAVhEBNeZw

Screencaps:

image

LM5023

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by yankee14** [comment]
**Question for any seasoned EE's that may be reading this**:  I've never worked with quasi-resonant (QR) supplies before, but it seems appropriate for my application. QR supplies seem to wait until the energy in the transformer is completely depleted, at which point a tank circuit is formed between the parasitic transformer primary winding inductance, and the drain capacitance of the MOSFET. Both of these seem to me like parameters that are probably not very well defined, and can vary a lot based on layout. If I have to wait for the drain voltage to "ring down" close to ground, isn't there going to be a crapload of EMI in the meantime? If I hope to pass compliance testing, I might have to stick a shield over the entire transformer and MOSFET assembly.

**Comment by poeschlr** [comment]
This is the wrong place to ask electronic design questions. I would suggest a forum like https://www.eevblog.com/ or https://electronics.stackexchange.com

**Comment by yankee14** [comment]
@poeschlr okay, thanks.

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 , thanks for contributing,

A few comments I have during my review:

- [ ] Fp filter: `VSSOP*3.0x3.0mm*P0.65mm*`
- [ ] SS should be Passive
- [ ] Position of the pin is strange. I suggest the following:

Capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
