### PR TITLE
Sensor_Humidity: HDC1080: disconnect DAP (EP)

### PR DESCRIPTION
**Pull request by diegoherranz**
From the device datasheet (https://www.ti.com/lit/ds/symlink/hdc1080.pdf):
"DAP - Die Attach Pad. Should be left floating."
"The DAP may be soldered to a floating pad on the board, but the
board pad should NOT be connected to GND."

Old:
old

New:
new

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

Thanks!

### CODE REVIEW

**Comment by cp-aquila** [comment]
I took a look at the patch and the datasheet.
Just one pin moved, I don't see anything wrong with it. Pintype and position is correct.
The only small issue is that Pins 3&4 are called "NC" in that Datasheet, the Symbol has them named as "DNC".

**Comment by diegoherranz** [comment]
Thanks for having a look.

> The only small issue is that Pins 3&4 are called "NC" in that Datasheet, the Symbol has them named as "DNC".

I didn't modified those. But it can be done if we want so.

**Comment by cp-aquila** [comment]
I would suggest to do so while you are at it anyway. But thats only a suggestion, I am not a maintainer here.

**Comment by poeschlr** [comment]
@cp-aquila 
> I am not a maintainer here.

We can change that if you would be interested ;)

**Comment by diegoherranz** [comment]
> I would suggest to do so while you are at it anyway. But thats only a suggestion, I am not a maintainer here.

Done.

**Comment by cp-aquila** [comment]
OT:

> 
> 
> @cp-aquila
> 
> > I am not a maintainer here.
> 
> We can change that if you are interested ;)

Unsure. I would like to help, but feel that I still make to much mistakes.
If I become a maintainer I would start with focusing on the really simple PRs.

@poeschlr Are you aware of any maintainers coming to cccamp19? or froscon? I would like to meet some in person.

**Comment by evanshultz** [comment]
Thanks! This looks good and is a bug so I'll merge.

That being said, I don't want to discourage the above conversation. We welcome you in whatever capacity you can give. I'm not going to be at either event.

**Comment by diegoherranz** [comment]
Thanks, @evanshultz!

@cp-aquila, even if it's only helping with minor/easy pull requests, any help is welcome.
Maybe you can give it more time if you prefer, so you're sure that you keep coming here often enough? I did when I was first offered to be a librarian.

Thanks!

**Comment by poeschlr** [comment]
@cp-aquila sorry for my long absence. (Life just doesn't allow me to be as active as i used to be)

We are aware that new maintainers will need support by experienced ones from time to time. The best way to learn is however to simply do it. I therefore sent you an invitation just now. If you ever need help just ask for it.

**Comment by cp-aquila** [comment]
> 
> We are aware that new maintainers will need support by experienced ones from time to time. The best way to learn is however to simply do it. I therefore sent you an invitation just now. If you ever need help just ask for it.

Thanks for the invitation.
Would you be so kind to send that invitation to user @cpresser, thats my regular/private account.
The @cp-aquila is my work account. I won't be able to contribute much during work hours. The recent weeks were more active because everyone is on vactaion and regular tasks/work was slow. My Bosses won't allow much open-source in the future :/
However, as stated above, my private account @cpresser will be more active.

**Comment by poeschlr** [comment]
Ok will do.

**Pull request merged**
