### PR TITLE
Add NHD-0420H1Z

### PR DESCRIPTION
**Pull request by strombom**
NHD-0420H1Z
http://www.newhavendisplay.com/specs/NHD-0420H1Z-FSW-GBW-33V3.pdf

This part has the same pinout as HY1602E, so I made NHD-0420H1Z an alias to that part.

image

Footprint: https://github.com/KiCad/kicad-footprints/pull/380

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

NHD-0420H1Z 
http://www.newhavendisplay.com/specs/NHD-0420H1Z-FSW-GBW-33V3.pdf
HY1602E 
http://www.icbank.com/data/ICBShop/board/HY1602E.pdf

is not of the same size for example HY1602E is 44 mm "high" and the NHD-0420H1Z is 36,5 mm "high"
Their pin out is not the same either NHD-0420H1Z have its pins on the short sides while HY1602E have it on it's long sides

I guess you should keep HY1602E  as it is and make a new symbol for NHD-0420H1Z.

**Comment by strombom** [comment]
Thank you, I meant to use RC1602A, I don't know how I managed to end up with HY1602E...

Now I have made a separate copy instead of alias.

image

image

**Comment by poeschlr** [comment]
The symbol looks good, could you rebase your changes to the current git master?

**Comment by strombom** [comment]
Ok, updated, thanks.

**Comment by evanshultz** [comment]
Thank you!
- Name pins 15 and 16 according to the datasheet.
- Those pins should be of type passive.
- Move VO pin to the top
- Spread apart the data and control pins just a bit (100mil is fine).

**Comment by strombom** [comment]
Ok updated, thank you.

image

**Comment by evanshultz** [comment]
Just one question: The exact MPN of `NHD-0420H1Z-FSW-GBW-33V3` has a lot more info than the symbol needs. I think the omitted info does not affect the symbol, but reflectivity, backlight color, etc. will affect the physical 3D model (which is 1:1 with a footprint). Perhaps there should be no default footprint and only a FPfilter so that if multiple LCDs in this family are in our footprint library the user will have a choice without one being selected for them. I'm OK merging like this for now if you like, just thinking ahead...

**Comment by strombom** [comment]
Yes, there are a few variations, I removed the footprint.

**Comment by evanshultz** [comment]
A whole load of stuff in the STM32 libraries was changed. Please revert that.

**Comment by strombom** [comment]
Sorry about that, I use github desktop, it automatically selects all new and modified files.

**Pull request merged**
