### PR TITLE
Tlp35 xx dip6

### PR DESCRIPTION
**Pull request by Misca1234**
TLP3542  
https://toshiba.semicon-storage.com/info/docget.jsp?did=1284&prodName=TLP3542

TLP3543
https://toshiba.semicon-storage.com/info/docget.jsp?did=12660&prodName=TLP3543
Aliases
TLP3544  https://toshiba.semicon-storage.com/info/docget.jsp?did=12661&prodName=TLP3544
TLP3545  https://toshiba.semicon-storage.com/info/docget.jsp?did=12663&prodName=TLP3545
TLP3546  https://toshiba.semicon-storage.com/info/docget.jsp?did=12671&prodName=TLP3546

Others
LCC110
checklib.py reported that LCC110 was not centered aligned, this was also fixed

TLP148G
checklib.py reported that TLP148G did not have a specific footprint specified, this was also fixed

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
I only got two minor requests:
2018-02-05 18_56_54-symbol library editor - relay_solidstate d__kicad_review pretty_kicad-symbols_r

**Comment by Misca1234** [comment]
Changed the symbols into 

bild

bild

**Comment by jkriege2** [comment]
OK, thanks.

I just noticed, the TLP3542 has not quite the right package: The datasheets say that the pin 5 is missing (see package sketch at top), but you choose the full DIP-6. I don't think we have a matching DPI-6-variant yet, could you make that footprint? the name should be `DIP-5-6_W7.62mm` or `Toshiba_11-7A9` (I would prefer the first!).

best,
JAN

**Comment by Misca1234** [comment]
Ok, no problem, I fix it

**Comment by Misca1234** [comment]
Now so 

bild

**Comment by Misca1234** [comment]
This push waits for the foot print in this push
https://github.com/KiCad/kicad-footprints/pull/350

**Comment by jkriege2** [comment]
Please use `DIP-5-6` in the description (we usually have the pin-number as a postfix to the package type there!

**Comment by jkriege2** [comment]
I think you forgot the ALIASed components with the DIP-5-6 ;-)

**Comment by Misca1234** [comment]
TLP3542 does not have any aliases
TLP3543 and their aliases are "full" 6 pin

**Comment by Misca1234** [comment]
Fixed

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
