### PR TITLE
Add Meanwell IRM-20-xx ACDC converters

### LINKED ISSUE #157: Missing symbols for MeanWell IRM-20 family
The footprint exists (`Converter_ACDC_MeanWell_IRM-20-xx_THT.kicad_mod`) but no symbol for it is present.

### PR DESCRIPTION
**Pull request by Sthing**
Added symbols for Meanwell IRM-20 series 20W AC-DC converters.
http://www.meanwell.com/Upload/PDF/IRM-20/IRM-20-SPEC.PDF

A mathing footprint already exists and is referenced (Converter_ACDC_MeanWell_IRM-20-xx_THT).

There is no 3D-model. I considered making one, but https://github.com/KiCad/kicad-packages3D/pull/174 and https://github.com/KiCad/kicad-packages3D/issues/273 made me think otherwise (I have never used FreeCAD before, and I cannot find any source scripts for the existing Meanwell IRM-0x 3D models.)

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

Closes #157.

### CODE REVIEW

**Comment by Shackmeister** [comment]
There is already a scripted 3D model, but some renaming is needed as you can see in the issue, if you want Ill be happy to help you get started with the freecad scripting :)
Off topic: danish?

**Comment by Sthing** [comment]
Hi @Shackmeister.
It would be great if you could get me started on FreeCAD. I'd like to try and add the 20W models then.
An yes, I'm Danish, living in Aalborg.

**Comment by Shackmeister** [comment]
Great! 
For starters you will need
Freecad (I recommend daily build, its quite stable) 
Cadquery 1.0.0
A clone of https://github.com/easyw/kicad-3d-models-in-freecad

Ill write some more details tomorrow. 
And Im from Copenhagen :)

**Comment by Misca1234** [comment]
You find the script for the ACDC_DCDC converters in
`https://github.com/easyw/kicad-3d-models-in-freecad`

In directory `FCAD_script_generator/Converters_DCDC_ACDC`

You can add the 3D model to the script

**Comment by Misca1234** [comment]
Also, this ACDC is galvanic isolated between AC and DC, so I guess you should have a "division" line as well in the symbol, like this DCDC one

bild

**Comment by Misca1234** [comment]
@Sthing 
Fyi: you are of course welcome to experiment with freecad and the 3d scripts but I looked into the 3D models for acdc and dcdc and saw it is needed some fixes wit hthe new split and new file names so 
i am fixing them atm

**Comment by Sthing** [comment]
@Misca1234 
Thank you for the 3D-model.s
Isolation lines added as requested.
image

**Comment by Misca1234** [comment]
Are you still interested of making 3D models (even if you will not make one for MeanWell-IRM-20 if you accept the one that already exists) perhaps for other devices ?

**Comment by Sthing** [comment]
Thanks for asking, @Misca1234.
I would like to, but realistically I will not get anything done. I have to many projects going already.
(It takes much less time to come up with another big idea than to actually plan, implement, debug, fix and test it. Strange...)
Thank you for your work!

**Comment by Sthing** [comment]
I'll wait for https://github.com/KiCad/kicad-packages3D/pull/285 to be merged and then update this PR.

**Comment by Misca1234** [comment]
Ok, but I give yo ua short introduction in ase you want to start later


Common:
You can use any CAD tool you want but you will get into so much trouble if you choose something else than FreeCad, 
the reason is the export from the finnished model to the wrl and .step format that KiCad will use, you have to figure out right scale factor and colour replacement.
The recomended tool is FreeCad becaosue there is a macro, kicad-stepup, that make it possible for you to freely design the model with right scale and colours as you want and then 
use the tool to the scale and coulour replacement as KiCad wants them when you export to the .wrl and .step file.

So I will describe the way with FreeCad.
Download FreeCad version higher or equal to 0.17.11223
(the older official 0.17 version have a bug in the export function to .step files)

In General:
Look in https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator
Is there already a script that generates similar models, if so, it might be better or easier to modify  
the script to generate the model you want.

If the model is fairly easy, that is, simple boxes, "ordinary devices" etc. use script to generate them

All scripts are written in Python


Script based
1. Modify or add a new script to repository https://github.com/easyw/kicad-3d-models-in-freecad
2. Make a push to https://github.com/KiCad/kicad-packages3D for the .step .wrl file
3. Make a push to https://github.com/easyw/kicad-3d-models-in-freecad with your script change/creation.

You create the models "via" FreeCad like this this example create a specific DCDC converter 
you stand in the {your path to the kicad-3d-models-in-freecad repository}/kicad-3d-models-in-freecad/cadquery/FCAD_script_generator/Converter_DCDC
$ {your path to the FreeCad binary}/FreeCAD_0.17.11223_x64_dev_win/bin/FreeCAD.exe main_generator_Converter_DCDC.py Converter_DCDC_Cincon_EC6Cxx_Single_THT

FreeCad will start and render the model and save the correct .step and .wrl files into 
{your path to the kicad-3d-models-in-freecad repository}/kicad-3d-models-in-freecad/cadquery/FCAD_script_generator/_3Dmodels


Handmade:
Download the kicad-stepup macro from and install it
https://sourceforge.net/projects/kicadstepup/

1. In FreeCad, create your model in accurate scale and those colours you want 
	the belly of the device should be "against" the XY plane, where the z cordinate should be 
	0 where you want the device to touch the topside of the PCB.
2. Use stepup macro to export to .wrl and .step files, in this process the macro will 
	ask you to replace those colours you used in your model to the "official" kicad colours.
3. Make a push to https://github.com/KiCad/kicad-packages3D for the .step .wrl file
4. Make a push to https://github.com/KiCad/kicad-packages3D-source of the .Fcstd file

The following images show the steps to generate step and wrl fiels from a handmade model


bild

bild

bild

**Comment by antoniovazquezblanco** [comment]
Thanks @Sthing 

When I had a look at the ACDC converters I did not add the isolation lines. Many other symbols should add this. I will open an issue for this. Thanks for pointing this out @Misca1234!

**Comment by Sthing** [comment]
Thanks for the instructions, @Misca1234.

In my last comment I wrote that I would update this PR when the 3D-models was merged. Come to think of it, there is no need to wait: The reference to the 3D-model is in the footprint-files, not in this repo.

**Comment by Misca1234** [comment]
No, the push
https://github.com/KiCad/kicad-packages3D/pull/285
is based on the new names of the splitted ACDC_DCDC libraries, 
so the scripts are updated as well in push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/161

so, everything should be solved over time

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
