### PR TITLE
Move CH376 from Memory_Controller to to Interface (#1144)

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Re push of https://github.com/KiCad/kicad-symbols/pull/1144 now targeting a future release to avoid breaking the libs in a minor release.

Related to issue #18.

Details:
* Move CH376 from Memory_Controller to to Interface
* Interface: Change pin name offset in CH376
* Interface: Fix CH376T pin types and description

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Closed & reopened for CLA.

@poeschlr I would like to get your input on when to merge this. Would you like to go 5.1.0 or 6.0.0?

Thanks!

**Comment by evanshultz** [comment]
@poeschlr 
Ping!

**Comment by evanshultz** [comment]
@poeschlr 
5.1 or 6?

**Comment by antoniovazquezblanco** [comment]
V6 window open!

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Comment by poeschlr** [comment]
This one sadly needs to be reverted as we can not delete  a library in the middle of a release cylce.
Sorry about the inconvenience.

**Pull request merged**
