### PR TITLE
Added CD4098

### PR DESCRIPTION
**Pull request by BigET**
*Added CD4098*

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
http://www.ti.com/lit/ds/symlink/cd4098b.pdf
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
It uses vanila DIP16.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by BigET** [comment]
I have signed CLA, but the bot still says otherwise.
When following the Deatils link, I get to a page that confirms the CLA signing.

**Comment by antoniovazquezblanco** [comment]
Your commits seem to have been signed with an account corresponding to `Eduard BUDULEA`. Looks like you configured git with a different email address than the one used to create the github account.

**Comment by evanshultz** [comment]
I know it sounds optional, but please include a screenshot of the symbol. Virtually any PR, such as https://github.com/KiCad/kicad-symbols/pull/1183, will give an example of what we like to see.

**Comment by BigET** [comment]
screenshot_2018-12-03_09-09-39

**Comment by BigET** [comment]
Should I redo a pull request with the github e-mail in the commits?

**Comment by antoniovazquezblanco** [comment]
> Should I redo a pull request with the github e-mail in the commits?
Either do that or sign the CLA with the email used to commit.

Thank you!

**Pull request closed without merging**
