### PR TITLE
Addition of MAX1615 Linear Regulator for Notebooks

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of MAX1615 Linear Voltage Regulator.

Datasheet: https://datasheets.maximintegrated.com/en/ds/MAX1615-MAX1616.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jamesrlucas** [comment]
Hello! Is anybody around to have a look at this?

Thanks!

**Comment by chschlue** [comment]
Incomplete review ahead:
- [x] Pins look good
- [x] FP looks good
- [ ] Name looks bad. Please change to MAX1615xUK.

**Comment by jamesrlucas** [comment]
All done :)

**Comment by chschlue** [comment]
Thanks.
Can you also move pin 1 down so that an R_Small fits between 1 and 3 and perhaps even add MAX1616 as well?

**Comment by jamesrlucas** [comment]
Done! - I've moved the shutdown pin down so an R_Small just fits - I'd rather not make the symbol any bigger! Also added the MAX1616, with the FB pin instead of 3.3/5V

**Comment by chschlue** [comment]
Oops.

I was talking about the other pin 1 which should be pin 4 :)

**Comment by jamesrlucas** [comment]
I moved that one down as well - more for the MAX1616 which needs a resistor between those pins for the feedback. Should I make the outline bigger?
Screenshot from 2019-11-30 13-37-06

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
