### PR TITLE
Converter_ACDC: Add CUI PBO power supply series

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://www.cui.com/product/resource/pbo-3.pdf

Screenshot from 2019-05-16 16-03-33

Pending footprint PR!

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco thanks for this symbol

- [ ] Do you plan to submit the horizontal or vertical footprint ? Or both ? Right angle terminates with "B".

Else, no comment to do, just need to wait the footprint.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
For the time being I am only going to submit the vertical one.

Thanks!

**Comment by poeschlr** [comment]
Footprint merged, so this is merged in accordance with the previous review. (No separate review necessary.)

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
