### PR TITLE
Added new component NB3N511

### PR DESCRIPTION
**Pull request by jeremysiebers**
Added new component NB3N511 in the Oscillator group.

http://www.onsemi.com/PowerSolutions/product.do?id=NB3N511
http://www.onsemi.com/pub/Collateral/NB3N511-D.PDF

nb3n511

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for this contribution! I see you started a new PR and that's great.

Review comments:
- Put a comma before the package name in the description.
- The footprint filter needs the body dimensions and should be `SOIC*3.9x4.9mm*P1.27mm*`.
- Can you capitalize all pin names?
- All pins should be 100mil long.
- Pin 1 is named `X1/ICLK`; you're missing the letter `I`.
- Pin 3 should be Power Input type.
- I think pin 8 should be Passive type since it will only go to a crystal.
- Can this symbol be shrunk a bit? It seems like a lot of dead space in there, but maybe this is the best.

This is a great first submission to the library. Thanks again for adding to it!

**Comment by jeremysiebers** [comment]
Thank you Evan for the review comments, I updated the component:

- [X] Put a comma before the package name in the description.
- [X] The footprint filter needs the body dimensions and should be SOIC*3.9x4.9mm*P1.27mm*.
- [X] Can you capitalize all pin names?
- [X] All pins should be 100mil long.
- [X] Pin 1 is named X1/ICLK; you're missing the letter I.
- [X] Pin 3 should be Power Input type.
- [ ] I think pin 8 should be Passive type since it will only go to a crystal. --> Shouldn't this be a Ouput type because pin 1 is also a direct clock input, so pin 8 (X2) must be the crystal driver?
- [X] Can this symbol be shrunk a bit? It seems like a lot of dead space in there, but maybe this is the best.

nb3n511

**Comment by jeremysiebers** [comment]
Hello Evan,

- [X] Pin 8 type: Inside the IC, yes, it's probably the output of an inverter. But the pin types drive the ERC engine in KiCad and are set depending on what other pins are connected. Since only a crystal should go here, Passive will be fine. As the output of pin 8 is not intended to drive other pins, Output is probably not the best choice. But in actuality it's rather unlikely to matter what type is used.

- [X] One more thing: can you please move the text closer to the body?

The component looks now like:

nb3n511

**Comment by evanshultz** [comment]
Thank you! I see you have more PRs open so thanks for continuing to contribute!

**Comment by jeremysiebers** [comment]
Hello Evan,

Also thank you for continuing to review these components and give feedback!

**Pull request merged**
