### PR TITLE
Ltc2358

### PR DESCRIPTION
**Pull request by jeremysiebers**
Added new component LTC2358-16 and LTC2358-18

http://www.analog.com/media/en/technical-documentation/data-sheets/235816f.pdf

ltc2358

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
This PR also adds the MAX3284E and MAX14783E, both of which you have already submitted in other PRs.  Please remove them from this one.

**Comment by jeremysiebers** [comment]
- [X] This PR also adds the MAX3284E and MAX14783E, both of which you have already submitted in other PRs.

**Comment by Ratfink** [comment]
[KLC]: http://kicad-pcb.org/libraries/klc/ "KiCad Library Convention"
[G1.1]: http://kicad-pcb.org/libraries/klc/G1.1/ "Only standard characters are used for naming libraries and components"
[G1.2]: http://kicad-pcb.org/libraries/klc/G1.2/ "Each library is limited to 250 items"
[G1.3]: http://kicad-pcb.org/libraries/klc/G1.3/ "Libraries are organized by functionality"
[G1.4]: http://kicad-pcb.org/libraries/klc/G1.4/ "English language should be used throughout libraries"
[G1.5]: http://kicad-pcb.org/libraries/klc/G1.5/ "Plural naming is to be avoided"
[G1.6]: http://kicad-pcb.org/libraries/klc/G1.6/ "Capitalization conventions"
[G1.7]: http://kicad-pcb.org/libraries/klc/G1.7/ "Library files use Unix style line endings"
[G1.8]: http://kicad-pcb.org/libraries/klc/G1.8/ "Components can only contain features supported in latest stable release"
[G1.9]: http://kicad-pcb.org/libraries/klc/G1.9/ "Dimensional units"
[G2.1]: http://kicad-pcb.org/libraries/klc/G2.1/ "Defining generic and atomic parts"
[S1.1]: http://kicad-pcb.org/libraries/klc/S1.1/ "Symbol libraries should be categorized by function"
[S2.1]: http://kicad-pcb.org/libraries/klc/S2.1/ "General symbol naming guidelines"
[S2.2]: http://kicad-pcb.org/libraries/klc/S2.2/ "Non-functional variations in part number should be replaced with wildcard"
[S2.3]: http://kicad-pcb.org/libraries/klc/S2.3/ "Where atomic parts are available in multiple footprint options, a separate symbol must be drawn for each footprint"
[S3.1]: http://kicad-pcb.org/libraries/klc/S3.1/ "Origin is centered on the middle of the symbol"
[S3.2]: http://kicad-pcb.org/libraries/klc/S3.2/ "Text fields should use a common text size of 50mils"
[S3.3]: http://kicad-pcb.org/libraries/klc/S3.3/ "Symbol outline and fill requirements"
[S3.4]: http://kicad-pcb.org/libraries/klc/S3.4/ "Symbols with complex functionality may incorporate simple functional diagrams"
[S3.5]: http://kicad-pcb.org/libraries/klc/S3.5/ "Pin connection points must be placed outside of the symbol"
[S3.6]: http://kicad-pcb.org/libraries/klc/S3.6/ "Pin name position offset"
[S3.7]: http://kicad-pcb.org/libraries/klc/S3.7/ "Pin numbering for exposed pads"
[S3.8]: http://kicad-pcb.org/libraries/klc/S3.8/ "Multi unit symbols"
[S4.1]: http://kicad-pcb.org/libraries/klc/S4.1/ "General pin requirements"
[S4.2]: http://kicad-pcb.org/libraries/klc/S4.2/ "Pins should be grouped by function"
[S4.3]: http://kicad-pcb.org/libraries/klc/S4.3/ "Rules for pin stacking"
[S4.4]: http://kicad-pcb.org/libraries/klc/S4.4/ "Pin electrical type"
[S4.5]: http://kicad-pcb.org/libraries/klc/S4.5/ "Pins not connected on the footprint may be omitted from the symbol"
[S4.6]: http://kicad-pcb.org/libraries/klc/S4.6/ "Hidden pins"
[S4.7]: http://kicad-pcb.org/libraries/klc/S4.7/ "Active low pins should be designated using a bar above the symbol name"
[S5.1]: http://kicad-pcb.org/libraries/klc/S5.1/ "Symbols with a default footprint link to a valid footprint file"
[S5.2]: http://kicad-pcb.org/libraries/klc/S5.2/ "Footprint filters should match all appropriate footprints"
[S6.1]: http://kicad-pcb.org/libraries/klc/S6.1/ "Component Reference Designator (RefDes)"
[S6.2]: http://kicad-pcb.org/libraries/klc/S6.2/ "Component fields must be filled appropriately"
[S6.3]: http://kicad-pcb.org/libraries/klc/S6.3/ "Component metadata is added to symbol (and all aliases)"
[S7.1]: http://kicad-pcb.org/libraries/klc/S7.1/ "Power flag symbols"
[S7.2]: http://kicad-pcb.org/libraries/klc/S7.2/ "Graphical symbols"
[F1.1]: http://kicad-pcb.org/libraries/klc/F1.1/ "Footprint libraries are categorized by function"
[F1.2]: http://kicad-pcb.org/libraries/klc/F1.2/ "Connector footprint libraries"
[F2.1]: http://kicad-pcb.org/libraries/klc/F2.1/ "General footprint naming conventions"
[F2.2]: http://kicad-pcb.org/libraries/klc/F2.2/ "Footprint naming field prefixes"
[F2.3]: http://kicad-pcb.org/libraries/klc/F2.3/ "Manufacturer specific version of generic footprints"
[F2.4]: http://kicad-pcb.org/libraries/klc/F2.4/ "Footprint naming for non-standard pin numbering"
[F2.5]: http://kicad-pcb.org/libraries/klc/F2.5/ "Footprint naming conventions for specific components"
[F3.1]: http://kicad-pcb.org/libraries/klc/F3.1/ "SMD chip package naming conventions"
[F3.2]: http://kicad-pcb.org/libraries/klc/F3.2/ "Resistor naming conventions"
[F3.3]: http://kicad-pcb.org/libraries/klc/F3.3/ "Capacitor naming conventions"
[F3.4]: http://kicad-pcb.org/libraries/klc/F3.4/ "SMD IC package naming conventions"
[F3.5]: http://kicad-pcb.org/libraries/klc/F3.5/ "THT IC package naming conventions"
[F3.6]: http://kicad-pcb.org/libraries/klc/F3.6/ "Connector naming conventions"
[F3.7]: http://kicad-pcb.org/libraries/klc/F3.7/ "Fuse naming conventions"
[F4.1]: http://kicad-pcb.org/libraries/klc/F4.1/ "Datasheet recommendations take priority"
[F4.2]: http://kicad-pcb.org/libraries/klc/F4.2/ "Pin 1 should be located at the top left"
[F4.3]: http://kicad-pcb.org/libraries/klc/F4.3/ "Connected copper elements have the same pad number"
[F4.4]: http://kicad-pcb.org/libraries/klc/F4.4/ "Thermal pads"
[F4.5]: http://kicad-pcb.org/libraries/klc/F4.5/ "Specifying footprint keepout areas"
[F4.6]: http://kicad-pcb.org/libraries/klc/F4.6/ "Local clearance and settings should be set to zero"
[F5.1]: http://kicad-pcb.org/libraries/klc/F5.1/ "Silkscreen layer requirements"
[F5.2]: http://kicad-pcb.org/libraries/klc/F5.2/ "Fabrication layer requirements"
[F5.3]: http://kicad-pcb.org/libraries/klc/F5.3/ "Courtyard layer requirements"
[F6.1]: http://kicad-pcb.org/libraries/klc/F6.1/ "Footprint placement type must be set to surface mount"
[F6.2]: http://kicad-pcb.org/libraries/klc/F6.2/ "Footprint anchor should be placed in the middle of the component body"
[F6.3]: http://kicad-pcb.org/libraries/klc/F6.3/ "Pad requirements for SMD footprints"
[F7.1]: http://kicad-pcb.org/libraries/klc/F7.1/ "Footprint placement type must be set to Through Hole"
[F7.2]: http://kicad-pcb.org/libraries/klc/F7.2/ "Footprint anchor should placed at the location of Pin-1"
[F7.3]: http://kicad-pcb.org/libraries/klc/F7.3/ "Pin 1 should be rectangular, and other pads circular or oval"
[F7.4]: http://kicad-pcb.org/libraries/klc/F7.4/ "Pad requirements for THT footprints"
[F7.5]: http://kicad-pcb.org/libraries/klc/F7.5/ "Minimum annular ring width"
[F7.6]: http://kicad-pcb.org/libraries/klc/F7.6/ "Minimum hole diameter"
[F8.1]: http://kicad-pcb.org/libraries/klc/F8.1/ "Virtual components"
[F9.1]: http://kicad-pcb.org/libraries/klc/F9.1/ "Footprint meta-data is filled in as appropriate"
[F9.2]: http://kicad-pcb.org/libraries/klc/F9.2/ "Footprint properties are as default values unless otherwise required in datasheet"
[F9.3]: http://kicad-pcb.org/libraries/klc/F9.3/ "Footprint 3D model requirements"
[M1.1]: http://kicad-pcb.org/libraries/klc/M1.1/ "Models should be created by contributor"
[M1.2]: http://kicad-pcb.org/libraries/klc/M1.2/ "Manufacturer models should not be duplicated"
[M1.3]: http://kicad-pcb.org/libraries/klc/M1.3/ "Source files for 3D models should be supplied"
[M2.1]: http://kicad-pcb.org/libraries/klc/M2.1/ "Permitted 3D model file types"
[M2.2]: http://kicad-pcb.org/libraries/klc/M2.2/ "Model alignment and scaling"

Thanks for the contribution!

* Please set the documentation fields to uniquely describe each alias.  The descriptions should only have the number of bits for the individual alias, and the datasheet URL should be different for the -18 alias.  The keywords shouldn't contain the wrong number of bits either.
  * [LTC2358-18 datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/235818f.pdf)
* Please name the pins as in the datasheet.
  * `IN?P` and `IN?N` should be `IN?+` and `IN?-`
  * `REF_IN` should be `REFIN`
  * `PWR_DWN` should be `PD`
  * `START_CONV` should be `CNV`
  * `VDD_BYPASS` should be `VDDLBYP`
  * `SDO-?` should be `SDO?`
* Electrical type changes.
  * Pins 19 and 21 should be Passive (I think?  They either get external voltage references or capacitors to ground.  I think the discussion in #381 is relevant here, and that seemed to be tending towards calling pins like this Passive).
  * Pin 40 should be Passive (technically it's a power output, but the datasheet says to only connect it to a bypass capacitor and no other circuitry).  It might be better placed on the right side.
  * Pins 25 and 36 should be Tri-state (in LVDS mode they're high impedance, in CMOS mode they're outputs)
  * Pins 32-35 should also be Tri-state (they're high impedance when CS is high)
* Pin grouping and stacking
  * I feel like `SDI` and `~CS` should probably be grouped together with the pins below them.  What do you think?
  * Since `VCC` and `VEE` are positive and negative high-voltage power inputs, please keep them on the same side of the top and bottom as one another.  Right now `VCC` is on the left and `VEE` is on the right, which seems counter-intuitive.
  * The `VDD` and `GND` pins could be stacked.  If you'd rather not stack them, that's okay too.
* The visible text fields should be moved closer to the symbol body.  You might consider moving the reference to the top left corner to avoid having any text fields interfere with the pins.

@poeschlr @jkriege2 @evanshultz I'd appreciate it if someone could please review what I said about electrical types.

**Comment by poeschlr** [comment]
Electrical types look good to me.

You could take a look at this post of mine to get an understanding of how i think of them: https://forum.kicad.info/t/electrical-type-of-schematic-symbol-pins/9439

**Comment by jeremysiebers** [comment]
- [X] Please set the documentation fields to uniquely describe each alias. The descriptions should only have the number of bits for the individual alias, and the datasheet URL should be different for the -18 alias. The keywords shouldn't contain the wrong number of bits either.

- [X] LTC2358-18 datasheet

Please name the pins as in the datasheet.

- [X] IN?P and IN?N should be IN?+ and IN?-
- [X] REF_IN should be REFIN
- [X] PWR_DWN should be PD
- [X] START_CONV should be CNV
- [X] VDD_BYPASS should be VDDLBYP
- [X] SDO-? should be SDO?

Electrical type changes.

- [X] Pins 19 and 21 should be Passive (I think? They either get external voltage references or capacitors to ground. I think the discussion in #381 is relevant here, and that seemed to be tending towards calling pins like this Passive).
- [X] Pin 40 should be Passive (technically it's a power output, but the datasheet says to only connect it to a bypass capacitor and no other circuitry). It might be better placed on the right side.
- [X] Pins 25 and 36 should be Tri-state (in LVDS mode they're high impedance, in CMOS mode they're outputs)
- [X] Pins 32-35 should also be Tri-state (they're high impedance when CS is high)
- [X] Pin grouping and stacking
- [ ] I feel like SDI and ~CS should probably be grouped together with the pins below them. What do you think? --> These are "separate" signals from the SDOx so in a application some space between them would help in distinguishing them from each other I think.
- [X] Since VCC and VEE are positive and negative high-voltage power inputs, please keep them on the same side of the top and bottom as one another. Right now VCC is on the left and VEE is on the right, which seems counter-intuitive.
- [X] The VDD and GND pins could
 be stacked. If you'd rather not stack them, that's okay too. --> Also stacked VEE, according to datasheet these must be connected together.

- [X] The visible text fields should be moved closer to the symbol body. You might consider moving the reference to the top left corner to avoid having any text fields interfere with the pins.

ltc2358


- I have a question:
When I select the symbol in the schematic editor, it moves the visible text fields to another place then specified in the symbol editor, why?

**Comment by poeschlr** [comment]
A manual merge is required as the lib has been changed via another pull request

**Comment by Ratfink** [comment]
The footprint field auto-placement is a setting, which is enabled by default in KiCad 5.  It can be disabled via Preferences→General Options→Editing→Automatically place symbol fields.

Just a few little changes I can see now:

* The descriptions should have the number of pins on the LQFP, e.g. `LQFP-48`.
* It looks like the symbol could be shrunk by 200 mil on both the top and bottom (the bottom will require moving VEE and GND closer so there's only a 200 mil gap between them), making it 400 mil shorter overall.
* Also, if you could move the text fields down another 50 mil, that would be ideal.

I'll handle the manual merging once it's time.

**Comment by jeremysiebers** [comment]
- [X] The descriptions should have the number of pins on the LQFP, e.g. LQFP-48.
- [X] It looks like the symbol could be shrunk by 200 mil on both the top and bottom (the bottom will require moving VEE and GND closer so there's only a 200 mil gap between them), making it 400 mil shorter overall.
- [X] Also, if you could move the text fields down another 50 mil, that would be ideal.

ltc2358-16

**Comment by Ratfink** [comment]
Oh, I see one last change that needs to be made: SDI should be type Input, not Tri-state.  Once that's fixed, I think this will be ready to merge.

**Comment by jeremysiebers** [comment]
- [X] SDI should be type Input, not Tri-state.

done :-)

ltc2358-16

**Comment by Ratfink** [comment]
Thanks for all the good work!

**Pull request merged**
