### PR TITLE
Request M2GL090T-FG484

### PR DESCRIPTION
**Pull request by eeyrjmr**
Requesting schematic symbol for M2GL090T-FG484.
Flash-based FPGA from Actel/Microsemi/Microchip. The M2GL series covers the 060, 050,025,005 with vary compatibility of pins.

The 484pin device has been split into the 8 banks, each with their local bank IO rail. A 9th representing common GND and additional rails (core, PLL etc...) 
Part was originally generated via kiPART and the Microsemi provided excel of the pins. This was tweaked to perform the bulk of the generation before visual tweaks within KiCAD.

Untitled

Datasheet: https://www.microsemi.com/document-portal/doc_download/132042-ds0128-igloo2-and-smartfusion2-datasheet
Pinout description: https://www.microsemi.com/document-portal/doc_download/132041-ds0124-igloo2-pin-descriptions-datasheet
Pinout xls: https://www.microsemi.com/document-portal/doc_download/132145-igloo2-fg484-pinouts

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @eeyrjmr , will finally review this PR :)

A few comments I have during my review:

Unit A:
- [ ] All DDRIOxxxx pins are Bidirectional
- [ ] For pin on the right, the main function should be near to the outline border. The name need to be swapped. For example "DDRIO77PB1/GB12/CCC_NE1_CLKI2/MDDR_DQ12" becomes "MDDR_DQ12/CCC_NE1_CLKI2/GB12DDRIO77PB1", etc
- [ ] You can reduce the height of t he symbol

Unit B:
- [ ] You can reduce the height of t he symbol

Unit C:
- [ ] For pin on the right, the main function should be near to the outline border.
- [ ] You should center VDDI3 pins

Unit D:
- [ ] You can reduce the height of t he symbol
- [ ] I propose to put all JTAG pins on the same side if this is easier to wire on the schematic

Unit G:
- [ ] Positions of pins M8 and N8 are crossed (MSIOD188NB7 and MSIOD188PB7)

Unit F:
- [ ] You can reduce the height of t he symbol

Unit H:
- [ ] Positions of pins H3 and G3 are crossed (MSIO154NB8 and MSIO154PB8)
- [ ] For pin on the right, the main function should be near to the outline border.
- [ ] You can reduce the height of the symbol by 100mil

Unit I:
- [ ] You should align VDD with VSS and VPPNVM with VSSNVM

Cheers,
Joel

**Comment by eeyrjmr** [comment]
Ha! almost forgot I submitted this part. 
I will act on these comments. I also have the 060 and the 010 so might as well have a microsemi fpga library

**Comment by myfreescalewebpage** [comment]
Hello @eeyrjmr 
Thanks for all those fixes. No comment except the two warnings of Travis : you have units D and F which are not vertically centered.
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, amazing work done here !
No more comment, merging.
Joel

**Pull request merged**
