### PR TITLE
HMC213 active mixer

### PR DESCRIPTION
**Pull request by calebns**
http://www.analog.com/media/en/technical-documentation/data-sheets/hmc213a.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
You forgot to specify the capsule type in the description, please change 

1.5-4.5GHz double-balanced mixer
into
1.5-4.5GHz double-balanced mixer, MSOP-8

**Comment by evanshultz** [comment]
@Misca1234 
The correct English word is "package", not "capsule".

**Comment by calebns** [comment]
Fixed.

**Comment by calebns** [comment]
Done. I've also split this part to HMC213A and HMC213B. 
I suggest we add also an obsoleted part (HMC213A), as in forseeable future it is the only chip you can buy on the market.

image

**Comment by evanshultz** [comment]
@calebns 
Looks good, and fine to include the old version since it's compatible with the upcoming B version. Thanks for posting a new image when there were visual changes.

**Pull request merged**
