### PR TITLE
add NCV8402xSTT1G

### PR DESCRIPTION
**Pull request by fvollmer**
Datasheet: https://www.onsemi.com/pub/Collateral/NCV8402-D.PDF

grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @fvollmer , thanks for contributing,

A few comments I have during my review:

- [ ] Name of this symbol should be "NCV8402xSTT"
- [ ] The symbol is very large and tall for no reason, on a schematic this is very strange. Is it possiblet o make it more compact, maybe removing the text and/or some details in the design (the resistor can be smaller, etc)

Cheers,
Joel

**Comment by fvollmer** [comment]
@myfreescalewebpage  Thanks for the review!

I changed the name and made the symbol smaller. I could reduce the top by another 100mil, but the symbol would be slightly off center.

**Comment by chschlue** [comment]
I think this has too many `T`s.
The name should be `NCV8402xST`. `ST` is the package, `T#` is reel size and `G` is green.

**Comment by fvollmer** [comment]
Your naming scheme makes sense. Fixed.

**Comment by myfreescalewebpage** [comment]
Thanks, it's nice like that. no more comment, merging.

**Pull request merged**
