### PR TITLE
Fix footprint errors for texas symbols

### PR DESCRIPTION
**Pull request by poeschlr**
Fix for travis errors reported in https://github.com/KiCad/kicad-symbols/pull/109

### CODE REVIEW

**Comment by poeschlr** [comment]
Ok my kicad version did change the line ordering compared to the current state of the lib. This means more errors are reported. I will fix them as well.

**Comment by poeschlr** [comment]
We don't have a correct footprint for the SSOP-20 FT231XS and FT221XS symbols. (I removed the footprint field and the filter for now, will open an issue about this.) I think the correct footprint name would be Package_SSOP:SSOP-20_3.9x8.7mm_P0.635mm (same body size as ssop-24)

**Comment by jkriege2** [comment]
Then I would say: set the footprint field accordingly with the new name and we should create the footprints for it ... If I find some time next week, I can do that.

**Comment by poeschlr** [comment]
Done

**Comment by jkriege2** [comment]
added missing footprint: https://github.com/KiCad/kicad-footprints/pull/206

**Pull request merged**
