### PR TITLE
Add FT5HN and FT5HV

### PR DESCRIPTION
**Pull request by bitglue**
Datasheet: https://www.mouser.com/datasheet/2/160/T5HN_T5HV-1662393.pdf

Footprint: https://github.com/KiCad/kicad-footprints/pull/2293
3D model: https://github.com/KiCad/kicad-packages3D/pull/699
3D model source: https://github.com/KiCad/kicad-packages3D-source/pull/282

image

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by bitglue** [comment]
Travis is failing just because the footprint doesn't exist, which will be resolved by https://github.com/KiCad/kicad-footprints/pull/2293

**Comment by aewallin** [comment]
For FT5HN, could you stack the two GND pins?

if you look at the existing oscillator symbols they seem to have a square or sine waveform drawn inside the symbol - consider that.

mouser is probably not the original datasheet source? is there an alternative link from the manufacturer?

**Comment by bitglue** [comment]
That's a good idea. I'll make the changes but it will be a few days until
I'm at a computer.

**Comment by bitglue** [comment]
@aewallin thanks for the review, changes made:

- changed datasheet links to go to foxonline.com
- stacked GND pins
- added square-wavey symbol

**Comment by bitglue** [comment]
@aewallin any more changes requested?

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hello @bitglue and thanks @aewallin for the first steps of the review

Complete review of the symbols:

FT5HN
- [ ] The footprint filter should be `Oscillator*SMD*Fox*FT5H*5.0x3.2mm*`
- [ ] Incorrect GND pin stacking (see travis error)

FT5HV
- [ ] The footprint filter should be `Oscillator*SMD*Fox*FT5H*5.0x3.2mm*`

Else, just need to wait the footprint

Joel

**Comment by myfreescalewebpage** [comment]
@bitglue ping

**Comment by myfreescalewebpage** [comment]
No news of the original author, indicate the PR is abandoned.

**Comment by bitglue** [comment]
@myfreescalewebpage rebump

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by bitglue** [comment]
@myfreescalewebpage footprint has been merged. There are also 3D models, not sure who to ping on those since there haven't been any comments yet:

https://github.com/KiCad/kicad-packages3D-source/pull/282
https://github.com/KiCad/kicad-packages3D/pull/699

Also I have some 3D models for a different component, if you could nudge them along I'd appreciate it:

https://github.com/KiCad/kicad-packages3D-source/pull/281
https://github.com/KiCad/kicad-packages3D/pull/698

**Comment by myfreescalewebpage** [comment]
Thanks to ping me on this, no more comment and merging.

For the packages 3D we are not a lot to be confortable with the review, this may take more time.

**Pull request merged**
