### PR TITLE
Add MAX14778 multiplexer

### PR DESCRIPTION
**Pull request by chschlue**
Add MAX14778 multiplexer
https://datasheets.maximintegrated.com/en/ds/MAX14778.pdf

max14778

https://github.com/KiCad/kicad-footprints/pull/1745

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by calebreister** [comment]
It may be worth trying to modify this to more closely match the CD4052 symbol.

**Comment by chschlue** [comment]
Why? Those are quite different parts.

**Comment by calebreister** [comment]
@chschlue Good point. I forgot that the '14778 has independent control bits for channels A and B. However, it might be worth splitting it into multiple units (A, B, and power).

Disclaimer: I'm not a maintainer/librarian, so you can disregard these comments/suggestions if you want.

**Comment by chschlue** [comment]
As these are suppossed to mux differential signals, maybe it would be more useful to split them into AB0, AB1, AB2, AB3, AB4 and power?

Comments welcome.

**Comment by evanshultz** [comment]
Either one-unit or two-unit designs could be used here. Up to you. Single-unit is a bit easier to design, but if you handle the pins carefully a split symbol can work too.

1. If you keep a single symbol, can you line up the four 'A' pins on the left and right sides and also the four 'B' pins? Right now they're split up.
1. All the switch pins should be Passive type since they're just a FET source and drain and not a logic symbol so that will fit best with the ERC engine in KiCad.
1. Pin 13 should be named VDD.
1. Please put positive power pins on the top. Perhaps VDD and GND on the vertical centerline, and then VP and VN above and below each other as well.
1. VP and VN should be Power Input type.
1. Please put the value on the top right.
1. Remove the disallowed character in the description as mentioned at http://kicad-pcb.org/libraries/klc/G1.1/.
1. Put the package type at the end of the description. In this case, `, TQFN-20`.
1. I don't see `T2055+4` at https://pdfserv.maximintegrated.com/package_dwgs/21-0140.PDF, but if I replace the `+` with a `-` I find the EP size should be 3.1mm square. The footprint you've assigned doesn't match, but you can make one easily with the framework at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON. (I see that https://pdfserv.maximintegrated.com/land_patterns/90-0009.PDF shows 3.15mm so I haven't missed that.)
1. Footprint filter should be `QFN*1EP*5x5mm*P0.65mm*`, removing pin count and EP size and using asterisks wherever possible.
1. I can see in the file that the symbol has two rectangle objects. Please delete the unneeded one.

**Comment by chschlue** [comment]
> 1. If you keep a single symbol, can you line up the four 'A' pins on the left and right sides and also the four 'B' pins? Right now they're split up.

Ok

> 2. All the switch pins should be Passive type since they're just a FET source and drain and not a logic symbol so that will fit best with the ERC engine in KiCad.

Ok

> 3. Pin 13 should be named VDD.

Ok

> 4. Please put positive power pins on the top. Perhaps VDD and GND on the vertical centerline, and then VP and VN above and below each other as well.

Ok

> 5. VP and VN should be Power Input type.

Ok, but why?
Is this purely an ERC workaround? I'm always willing to learn

> 6. Please put the value on the top right.

Ok

> 7. Remove the disallowed character in the description as mentioned at http://kicad-pcb.org/libraries/klc/G1.1/.

Ok

> 8. Put the package type at the end of the description. In this case, `, TQFN-20`.

Ok

> 9. I don't see `T2055+4` at https://pdfserv.maximintegrated.com/package_dwgs/21-0140.PDF, but if I replace the `+` with a `-` I find the EP size should be 3.1mm square. The footprint you've assigned doesn't match, but you can make one easily with the framework at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON. (I see that https://pdfserv.maximintegrated.com/land_patterns/90-0009.PDF shows 3.15mm so I haven't missed that.)

Ok

> 10. Footprint filter should be `QFN*1EP*5x5mm*P0.65mm*`, removing pin count and EP size and using asterisks wherever possible.

Ok

> 11. I can see in the file that the symbol has two rectangle objects. Please delete the unneeded one.

Ok

**Comment by evanshultz** [comment]
Oops. I didn't read enough datasheet pages. Passive is fine for VP and VN. My mistake.

The package is called TQFN so we should do that here. The package height is thinner.

How about this for a pin position:
image
```
# MAX14778
#
DEF MAX14778 U 0 20 Y Y 1 F N
F0 "U" -300 550 50 H V C CNN
F1 "MAX14778" 350 550 50 H V C CNN
F2 "Package_DFN_QFN:TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm" 0 -800 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 TQFN*1EP*5x5mm*P0.65mm*
$ENDFPLIST
DRAW
S -300 500 300 -500 0 1 10 f
X BCOM 1 -400 -100 100 R 50 50 1 1 P
X ENA 10 -400 300 100 R 50 50 1 1 I
X SA0 11 -400 200 100 R 50 50 1 1 I
X SA1 12 -400 100 100 R 50 50 1 1 I
X VDD 13 0 600 100 D 50 50 1 1 W
X SB1 14 -400 -400 100 R 50 50 1 1 I
X SB0 15 -400 -300 100 R 50 50 1 1 I
X ENB 16 -400 -200 100 R 50 50 1 1 I
X B3 17 400 -400 100 L 50 50 1 1 P
X B2 18 400 -300 100 L 50 50 1 1 P
X B1 19 400 -200 100 L 50 50 1 1 P
X VP 2 100 600 100 D 50 50 1 1 W
X B0 20 400 -100 100 L 50 50 1 1 P
X VN 21 100 -600 100 U 50 50 1 1 P N
X GND 3 0 -600 100 U 50 50 1 1 W
X VN 4 100 -600 100 U 50 50 1 1 W
X ACOM 5 -400 400 100 R 50 50 1 1 P
X A0 6 400 400 100 L 50 50 1 1 P
X A1 7 400 300 100 L 50 50 1 1 P
X A2 8 400 200 100 L 50 50 1 1 P
X A3 9 400 100 100 L 50 50 1 1 P
ENDDRAW
ENDDEF
```

**Comment by chschlue** [comment]
I like to keep differential pairs together (yes, even in the schematics).

I think spreading ACOM and BCOM just clutters things up, but I can live with it.

**Comment by evanshultz** [comment]
I see what you're after now. Is there an alternate symbol design you would prefer? Maybe like the above but with pins 1 and 5 just above and below the middle?

**Comment by chschlue** [comment]
Sounds good

max14778

**Comment by evanshultz** [comment]
Thank you for this symbol and the footprint!

**Pull request merged**
