### PR TITLE
Transfer symbols from old infineon lib

### PR DESCRIPTION
**Pull request by poeschlr**
This PR transfers the symbols from the old infineon lib. Because currently all smart fets are in power_management i put them in there as well.

### CODE REVIEW

**Comment by poeschlr** [comment]
Screenshots for the symbols i transferred over from my personal lib. (All of them have been already tested in combination with the footprints i added in PR https://github.com/KiCad/kicad-footprints/pull/202)

screenshot from 2017-12-30 22-57-31
screenshot from 2017-12-30 22-57-08
screenshot from 2017-12-30 22-56-42
screenshot from 2017-12-30 22-56-24

**Comment by poeschlr** [comment]
Travis errors are from:
- reduced text size for pin numbers (i have the name outside to allow internal graphics. size 50 would create problems here)
- missing footprints (PR has not yet been merged)
- missing symbol lib entries (my linear pr screwed this up. will create a separate pr that does fix that)

**Comment by jkriege2** [comment]
Hi!

I like the artwork! 
I indicated a few things to change in the image below:
2018-01-01 12_40_49-symbol library editor - power_management d__kicad_review pretty_kicad-symbols_p

**Comment by poeschlr** [comment]
Stacked power pins and made inverted pins compliant with the KLC.
screenshot from 2018-01-01 21-32-47
screenshot from 2018-01-01 21-30-06
screenshot from 2018-01-01 21-29-46

**Comment by jkriege2** [comment]
Hi!

could you please fix these (of the remaining) KLC-errors/warnings:
```
Checking symbol 'IPS7091SPBF':
  Violating S5.2
    Footprint filters should match all appropriate footprints
    No footprint filters defined
Changed symbol 'Power_Management.lib:IPS6011SPBF'
Checking symbol 'IPS6011SPBF':
  Violating S5.2
    Footprint filters should match all appropriate footprints
    No footprint filters defined
New symbol 'Power_Management.lib:ITS5215'
Checking symbol 'ITS5215':
  Violating S5.2
    Footprint filters should match all appropriate footprints
    Minuses and underscores in footprint filter 'INF-PG-DSO-12-11-EP*' should be escaped with '?' or '*'.
```

**Comment by poeschlr** [comment]
@jkriege2 Fixed these 3 footprint filters

**Pull request merged**
