### PR TITLE
NXP SA636

### PR DESCRIPTION
**Pull request by joemadeus**
Adding component SA636, the low-power version of the SA605. Footprints are set to SSOP20.

Data sheet: https://www.nxp.com/docs/en/data-sheet/SA636.pdf

nxp sa636dk

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Please post a link to a datasheet, an image of the symbol and check travis output to see an error report about your symbol.

Thanks!

**Comment by joemadeus** [comment]
A question: this component has two forms, a SSOP-20 and a QFN. Travis is saying I have to either select one footprint or no footprints (unless I'm misinterpreting.) It seems unfortunate to have to create two components for two footprints, or let the footprint definition be completely unbounded. Is it possible to specify the two footprints, and only the two footprints?

**Comment by joemadeus** [comment]
@antoniovazquezblanco I finally located the symbol guidelines and I think this is ready to go! 

BTW, MCS3142 got moved in the file and travis was complaining about it. I think that one follows the guidelines now as well.

**Comment by myfreescalewebpage** [comment]
@joemadeus ping! Are you still alive on this subject ?

**Comment by joemadeus** [comment]
So sorry! Yes, I'm still here. Let me make the changes you suggest (likely this evening or Saturday) and I'll ping you when they're done. Sorry for the delay!

**Comment by joemadeus** [comment]
@myfreescalewebpage just updated the part with changes based on your comments.

**Comment by myfreescalewebpage** [comment]
@joemadeus thanks, no worries, that was just to checked if you want to continue the integration. Your changes are okay for me, not more comment to do and merging your contribution now.
Thanks
Joel

**Pull request merged**
