### PR TITLE
MCU_Microchip_PIC16: Add PIC16F18325-xGZ

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://ww1.microchip.com/downloads/en/DeviceDoc/40001795E.pdf

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A few comments I have during my review:

- [ ] Pin length should be 100mil (symbol<100pins)
- [ ] The footprint should be `Package_DFN_QFN:UQFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm` (wrong EP size)
- [ ] The footprint filter will be `UQFN*1EP*4x4mm*P0.5mm*` (no EP size in fp filter)

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
There are two sections in the datasheet, package size and recommended layout pattern. EP size should be 2.8x2.8mm as shown below:

screenshot from 2019-02-26 11-15-59

Will do the rest whenever I find time today. Thanks!

**Comment by antoniovazquezblanco** [comment]
Done. Thanks!

**Comment by myfreescalewebpage** [comment]
Hello @antoniovazquezblanco 

Agree with you about the EP size, sorry I have made the mistake.
You have forgotten pin length of VDD and VSS.

Joel

**Comment by antoniovazquezblanco** [comment]
My bad! Fixed ;)

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco no more comment here, merging.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
