### PR TITLE
Fixing XC2C256-VQ100 symbol info/visual

### PR DESCRIPTION
**Pull request by JonathSpirit**
Fixing XC2C256-VQ100 symbol info/visual

- Pin offset to 20mils
- Fixing grid to 100mils
- Apply background color
- Adding the datasheet link : https://www.xilinx.com/support/documentation/data_sheets/ds094.pdf
- Adding footprint
- Adding description
- Pin length to 200mils
- Fixing power pins not power-input

Old symbol : 
image

New symbol : 
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @JonathSpirit 

Thanks for the enhancements of this symbol. This will be merged with v6.

If you have time I have several comments (if you have no time, will be merged anyway like that):
- [ ] Description should ends with package name: `CoolRunner-II CPLD, 256 macrocells, VQFP-100`
- [ ] Fp filter should be `VQFP*14x14mm*P0.5mm*`
- [ ] Pin length should be 150mil (3 digits to encode "100" = 150mil, 50mil per digit)
- [ ] GND pins can be stacked

Joel

**Comment by JonathSpirit** [comment]
The pin length to 150mil will break the 100mil grid, and many symbols have 200mil in the pin length. Do I still have to change or can I keep the length ?

image

I changed the description to : CoolRunner-II CPLD, 256 macrocells, VQFP-100
Fp filter is now : VQFP*14x14mm*P0.5mm*
GND pins stacked

**Comment by myfreescalewebpage** [comment]
Yes 150mil. You can decrease a bit the size of the rectangle to keep the pin at the same place.
Thanks for the enhancements you made on this symbol!

**Comment by JonathSpirit** [comment]
image

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment.
Will be merged for v6 (beginning of September).
Joel

**Pull request merged**
