### PR TITLE
Add TCA9554

### PR DESCRIPTION
**Pull request by tpambor**
This adds a symbol for TCA9554. The symbol is based on TCA9534.

Datasheet: http://www.ti.com/lit/ds/symlink/tca9554.pdf

tca9554

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@tpambor thanks for this symbol.

One main remark: new symbol should be atomic for this kind of device. This means you should create 4 symbols, one for each package version, and use complete names from the manufacturer.

Also, even if it is based on an existing symbol, new symbol should follow the new KLC rules, and thus, for this symbol, pin length should be 100mil (symbol < 100pins)

Cheers,
Joel

**Comment by tpambor** [comment]
@myfreescalewebpage Thanks for the quick review. I incorporated your feedback.

**Comment by myfreescalewebpage** [comment]
@tpambor thanks, making a full review now.

The last letter (T or R) on these symbols is the packaging option, not relevant in KiCad, thus:

TCA9554DBQR
- [ ] The name of the symbol should be `TCA9554DBQ`

TCA9554DBR
- [ ] The name of the symbol should be `TCA9554DB`

TCA9554DWR
- [ ] The name of the symbol should be `TCA9554DW`
- [ ] Alias to be removed

TCA9554PWR
- [ ] The name of the symbol should be `TCA9554PW`

Else, no comment to do.

Cheers,
Joel

**Comment by tpambor** [comment]
I prefer it that way too, fixed it. Thanks @myfreescalewebpage

**Comment by myfreescalewebpage** [comment]
Thanks, great job ! Merging.

**Pull request merged**
