### PR TITLE
 Added SN6505ADBVR SN6505BDBVR under regulators_switching

### PR DESCRIPTION
**Pull request by aris-kimi**
*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
Hi there. Please consider adding screenshots of the symbols being added, and links to their datasheet.

**Comment by aris-kimi** [comment]
output

**Comment by aris-kimi** [comment]
http://www.ti.com/lit/ds/symlink/sn6505b.pdf

**Comment by aris-kimi** [comment]
Thank you for your comment. Now i think we are ok right??

**Comment by DanSGiesbrecht** [comment]
I'll have a look this evening.

**Comment by evanshultz** [comment]
Let me pop in to get the ball rolling. Plus, I'm personally interested in these parts...

1. Wrong library. We don't have a `Driver_Transformer` and I think this type of part is quite rare. How about following Digi-Key and putting them in `Power_Management`?
1. In the description, change `SOT23` to `SOT-23-6`.
1. Add the oscillator freq to the description (just before the package type) so we can see a difference between them when choosing symbols.
1. Remove the last `R` from the symbol name. This is a non-functional character.
1. Remove the final `6*` from the footprint filter and change the remaining `*` to `?`. CvPcb can match on pin count and we don't want to accidentally match SOT-223 footprints.
1. Change pin name offset to 20mil.
1. Swap the left and right pins so inputs are on the left and outputs on the right. Spread apart the EN and CLK pins to give some symmetry like D1 and D2. Compact the symbol as it looks overly big.
1. Put the ref des at top left and PN at top right.

Lastly, as Dan asked, please include a screenshot and datasheet in the first post. If there are significant changes during the review please post another screenshot. This will help the review start faster and go more smoothly. Thank you.

**Comment by evanshultz** [comment]
Here is the current symbol:
image

1. Remove `SN6505x, ` from the descriptions.
1. Footprint filter should be `SOT?23*`.
1. Set all pin lengths to 100mil.

I assume KiCad reordered the lines with `AAT461*`. It sometimes does that. And Git then surfaces that as a change. However, there is a lot of noise above. Please try to make your commits clean so it's easier to review by seeing just changes to the symbol in the PR. And give your commits a good name; "Add files via upload" doesn't tell anyone what the commit contains. Lastly, I know Git can be tough to get started so this is all in the interest of helping you and giving guidance.

**Comment by aris-kimi** [comment]
Things look a little more clear than used to.. Thank you for your help, i think it is ok now.

Best regards,
Aris

**Comment by evanshultz** [comment]
@DanSGiesbrecht 
Do you want to review this? I didn't catch anything else.

**Comment by evanshultz** [comment]
@aris-kimi 
Thanks for your contribution!

@DanSGiesbrecht 
Didn't see any comment from you so I went ahead and merged.

**Pull request merged**
