### PR TITLE
Ice40UL1K-16WCLSP

### PR DESCRIPTION
**Pull request by chmorgan**
Lattice ICE40UL1K footprint.

https://www.latticesemi.com/view_document?document_id=50945

Footprint pull request: https://github.com/KiCad/kicad-footprints/pull/2365

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

Travis errors of missing footprint are due to this part using a footprint that does not currently exist in kicad footprints. A footprint for this part, generated by the footprint generator, has been submitted, as well as a PR for the footprint generator script file change.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by chmorgan** [comment]
Hi @myfreescalewebpage. The pin assignments are in this excel table (https://www.latticesemi.com/view_document?document_id=50947) linked from this page (https://www.latticesemi.com/en/Products/FPGAandCPLD/iCE40Ultra).

Should I add these to the part anywhere or to the commit?

**Comment by chmorgan** [comment]
@myfreescalewebpage I also tried to make the part smaller but also didn't want the text to be too tight. I was able to take a little bit out of the height.

**Comment by myfreescalewebpage** [comment]
Thanks for the update. Few comments:

- [ ] I disagree with the name of the symbol. We always discard temperature and packaging. "ICE40UL1K-SWG16" is more correct.
- [ ] Thanks for the pinout file link. The pin name should be the same than the one indicated in column A of this file.

Proposition below to have something more compact. If you prefer everything on the left it's good also but please reduce spaces between group of pins.

Capture

Joel

**Comment by cpresser** [comment]
Regarding the stylistic question: I like the tall version (pins on only one side) better than the wide version. But that is no real argument, its just that it looks better for me.

**Comment by myfreescalewebpage** [comment]
Yes I let the possibility to do every thing on same side but the current design lost to much space.
@chmorgan are you still working on this ?

**Comment by chmorgan** [comment]
@myfreescalewebpage you bet. @cpresser @myfreescalewebpage you want me to move the pins back to the single side? I can fix that and remove the temperature naming at the same time.

**Comment by myfreescalewebpage** [comment]
Why ? I have just read my full review below just above and I have written "Proposition below to have something more compact. If you prefer everything on the left it's good also but please reduce spaces between group of pins.". You are the author and as soon as the proposition you made is not totally away of the design we usually have in the lib, it's fine :)

**Comment by myfreescalewebpage** [comment]
@chmorgan thanks for the update.
There is still plenty of space lost, what a pity !
The name of C3 is "IOB_8A_G4_CDONE"
Joel

**Comment by chmorgan** [comment]
@myfreescalewebpage I could shift the left and right pins up a bit but that puts them pretty close and might be harder to visually distinguish from the long name of B3. Thoughts on how to compress space given the requirement for power and ground on top and bottom and the long pin names?

Good catch on that pin mistake...pushing a fix for that right now

**Comment by chmorgan** [comment]
@myfreescalewebpage btw there is a ICE 5K part that has the ITR extension on it, I believe that's why I had earlier copied that approach.

**Comment by myfreescalewebpage** [comment]
> Thoughts on how to compress space given the requirement for power and ground on top and bottom and the long pin names?

Sure. We can merge now and if a better solution is found in the future (with new devices for example) then it is still possible to change this one.

Thanks for the fix of the pin name!

**Pull request merged**
