### PR TITLE
Bugfix: fix position of VZCR pin on ACS730 (and aliases)

### PR DESCRIPTION
**Pull request by gkeeth**
ACS730xLCTR-20AB (and its aliases) has a pin placed inside the body. The pin is intended to be connected to the external circuit so it shouldn't be inside the body. Also, the incorrect placement causes a cosmetic issue with overlapping pin name text.

Git archaeology suggests this symbol was pulled in from the old repos. I didn't track the history further back.

Datasheet link:
https://www.allegromicro.com/~/media/Files/Datasheets/ACS730-Datasheet.ashx

Before:
before

After:
after

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by gkeeth** [comment]
Travis suggests VOUT should be type power output instead of output -- in this case travis doesn't know what it's talking about :)

**Comment by aris-kimi** [comment]
Hi @gkeeth , i would suggest to rename it as VIOUT, same as the datasheet...

**Comment by gkeeth** [comment]
Done. Updated screenshot: 

renamed

Datasheet for comparison:
renamed

**Comment by gkeeth** [comment]
I understand moving pins is a breaking change, but the symbol is essentially unusable in its current state. In cases like that don’t bug fixes get merged even if they’re breaking?

**Comment by aris-kimi** [comment]
Based on older similar PRs, i think no.
If you draw the wire you can connect to that pin (old symbol), so i do not think it is unusable,
so the change proposed here, will breake current schematics.
Keep this PR open and wait for a librarian to label and comment. I hope this helped.

**Comment by gkeeth** [comment]
Understood. Thanks for the review.

**Comment by myfreescalewebpage** [comment]
Hello @gkeeth 
Thanks for this fix. I think @aris-kimi is right, merging for v6 is preferable.
I have no comment to add, just put tags and milestone.
Joel

**Comment by gkeeth** [comment]
Great, thanks!

**Comment by evanshultz** [comment]
I would consider this worth doing now. If the wire goes directly right, it will still be connected. And if it doesn't, ERC will catch an unconnected pin. IMO it's a clear bug fix so moving pins is fine. But it's assigned to you, @myfreescalewebpage , so your call.

**Comment by myfreescalewebpage** [comment]
Considering v6 is very closed now we may think this will not a be an important disturbance, so merging according to your opinion @evanshultz

**Pull request merged**
