### PR TITLE
Fix 4068 IEEE symbol

### PR DESCRIPTION
**Pull request by chschlue**
Fix 4068 IEEE symbol

* add non-inverted output
* fix pin types

Datasheet: http://www.ti.com/lit/ds/symlink/cd4068b.pdf

Violations: kept style of whole 4xxx_IEEE lib

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for another fix PR! And sorry that things need fixing.

Can you please include before/after screenshots? That makes the review easier. Here it is:
image

This is a correction to a clear error, so it's welcomed as-is if you don't want to put in any more effort. But if you're willing, would you consider adding keywords (perhaps just `cmos nand and`) and a datasheet link? Other errors and warning aren't worth taking any action.

**Comment by chschlue** [comment]
Will do.

BTW, do almost all the generic logic symbols look like that for a reason or has just nobody cared to polish them yet?

**Comment by evanshultz** [comment]
There has been quite a bit of discussion about how to design the logic symbols, but it didn't get wrapped up for the KiCad v5 release. Everything needs to be ironed out and then the rest of the work done to update symbols for v6. So it's in a holding pattern right now. Because of the design of the symbol libraries and KiCad, the devs prefer not to make massive symbol changes during a major release.

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
