### PR TITLE
Sensor: Set footprint of SHT1x

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
PR with the footprint: [#1332](https://github.com/KiCad/kicad-footprints/pull/1332)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Thanks @piotr-wiszowaty for this PR.

- [ ] The footprint should be `Sensor_Temperature:SHT1x.kicad_mod` according to the footprint PR which has been merged
- [ ] The footprint filter should be added and should be `SHT1x*`

Cheers,
Joel

**Comment by diegoherranz** [comment]
> The footprint should be Sensor_Temperature:SHT1x according to the footprint PR which has been merged

See https://github.com/KiCad/kicad-footprints/pull/1332 which originated from https://github.com/KiCad/kicad-footprints/pull/1297#issuecomment-456582713

**Comment by myfreescalewebpage** [comment]
Sorry, just read the footprint PR too much quickly, I have understood the opposite.
By the way, can you add the footprint filter ?

**Comment by piotr-wiszowaty** [comment]
Sure. Done.

**Comment by myfreescalewebpage** [comment]
Thanks. Merging.

**Pull request merged**
