### PR TITLE
add analog switch MAX14761

### PR DESCRIPTION
**Pull request by penoud**
add analog switch MAX14761
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
https://datasheets.maximintegrated.com/en/ds/MAX14759-MAX14763.pdf
- [x] An example screenshot image is very helpful
image
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
The EP pad must be exposed, as it should be connected to VN:

image

**Comment by penoud** [comment]
Correct by changing EP pin to visible:
image

**Comment by evanshultz** [comment]
- Correct the description as discussed before.
- Note that the package has 10 pins.
- Put EP on the bottom.
- This is quite cramped. Space apart the two switches to the pins aren't jammed together or use two units.
- Stack pins as noted at https://github.com/KiCad/kicad-symbols/pull/991#issuecomment-423851359.

And, of course, branch conflicts.

**Comment by poeschlr** [comment]
If we go with a multi unit approach than i would guess we would have two units for the switches plus one for supporting stuff (power pins plus maybe VP and VN depending on what these two pins do.)

**Comment by penoud** [comment]
Updated screenshoots:
Unit A:
image
Unit B:
image
Unit C:
image

**Comment by evanshultz** [comment]
Push the ref des slightly to the right so it sits above the symbol better.

Looks fine to me otherwise. On second, though, perhaps EP should be on the size next to VN?

@poeschlr @SchrodingersGat 
Any other comments and/or requests?

**Comment by penoud** [comment]
I correct the ref pos.
image

**Comment by evanshultz** [comment]
Thanks for stacking pins! If you fix the branch conflicts and Travis is green I can merge.

**Comment by penoud** [comment]
Updated unit c:
image

**Comment by evanshultz** [comment]
Thanks again!

**Pull request merged**
