### PR TITLE
Add Si5351 series of programmable clock generators

### PR DESCRIPTION
**Pull request by pgrudzinski**
Datasheet: 
https://www.silabs.com/documents/public/data-sheets/Si5351-B.pdf

Screenshots:

SI5351A-B-GM
image

SI5351A-B-GT
image

SI5351B-B-GM
image

SI5351C-B-GM
image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @pgrudzinski , thanks for contributing,

A few comments I have during my review:

SI5351A-B-GM:
- [ ] Descriptions should ends with package name, `, QFN-20`
- [ ] Footprint should be `Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm` (wrong EP size)
- [ ] Footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`

SI5351A-B-GT:
- [ ] Descriptions should ends with package name, `, MSOP-8`
- [ ] Footprint filter should be `MSOP*3x3mm*P0.5mm*`

SI5351B-B-GM:
- [ ] Descriptions should ends with package name, `, QFN-20`
- [ ] Footprint should be `Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm` (wrong EP size)
- [ ] Footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`

SI5351C-B-GM:
- [ ] Descriptions should ends with package name, `, QFN-20`
- [ ] Footprint should be `Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm` (wrong EP size)
- [ ] Footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`

Please, can you also fix the branch conflict ? Thanks.

Cheers,
Joel

**Comment by pgrudzinski** [comment]
Yes, I am still intending to implement those changes. It probably will take
some time, as I have hardware issues at the moment.

**Comment by myfreescalewebpage** [comment]
Thanks @pgrudzinski no worries, I understand that was just to ping you, thanks for your quick answer :)

**Comment by pgrudzinski** [comment]
Parts already in the library, added with PR #1603

**Pull request closed without merging**
