### PR TITLE
Small improve in INA226

### PR DESCRIPTION
**Pull request by jneiva08**
Changes made is:
- Changed Ax pins to Input
- Renamed Vs to VS

The footprint shoudn't be VSSOP-10_3x3mm_P0.5mm instead of MSOP-10_3x3mm_P0.5mm?
The pads appears to be in same place but the hight is different.

Before:
ina226_b

After:
ina226_a

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Both bullets above look OK to me.

The VSSOP footprint does exist, so if you want to change that too go ahead and then I'll merge.

Thank you!

**Comment by jneiva08** [comment]
Hope I didn't miss anything.
Thanks for the wait.

**Comment by evanshultz** [comment]
Looks good to me. Thank you!

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
