### PR TITLE
Oscillator: Add Abracon ASDMB device family

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://abracon.com/Oscillators/ASDMB.pdf

imagen

FP PR: https://github.com/KiCad/kicad-footprints/pull/1435
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A single comment I have during my review:

- [ ] Footprint filter will be `Oscillator*SMD*Abracon*ASDMB*2.5x2.0mm*` (no pin count in fp filter)

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, just need to wait the integration of the footprint.

**Comment by evanshultz** [comment]
Footprint has been merged.

**Comment by myfreescalewebpage** [comment]
Thanks, merging the symbol.

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
