### PR TITLE
add BQ76200

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: http://www.ti.com/lit/ds/symlink/bq76200.pdf

Screenshot:
bq76200

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] The name of the device should be `BQ76200PW`
- [ ] Footprint filter should be `TSSOP*4.4x5mm*P0.65mm*`
- [ ] PACK should be Power Input and should be on the top of the symbol, I suggest to have pin position as shown on page 9 of the datasheet

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage, have made the changes requested.

Screenshot:
bq76200pw

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
