### PR TITLE
Add ST LK112 LDO with shutdown function.

### PR DESCRIPTION
**Pull request by Misaka0x2730**
Adding LK112 LDO regulator.
[Datasheet](https://www.st.com/resource/ja/datasheet/lk112.pdf)
image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by diegoherranz** [comment]
I've checked the pinout and the part names and they look OK.
Thanks for submitting this.

**Comment by Misaka0x2730** [comment]
> Remove output current up to in the description.

I believe that the current still needs to be specified, I wrote "150mA with a 0.35V output drop". It's all right?

> Add package type of SOT-23-5 to the end of the description.

Fixed.

**Comment by evanshultz** [comment]
The package looks good. I put in monospace the text to be removed, which would have still left the `150mA` part. Perhaps if you're reading an email that's not clear. Vdropout is overly detailed so if you remove " with a 0.35V output drop" (leaving the Iout value) this is good. Thanks!

**Comment by evanshultz** [comment]
Thank you! I hope to see more contributions from you in the future!

**Pull request merged**
