### PR TITLE
Added BQ24230 (based on pull request #2417).

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**
Add needed changes to pull request #2417.
See original pull request for details.
I assumed the footprint was already checked (datasheet says VQFN while selected footprint seems to be QFN).

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue do you want to continue the review of this symbol after https://github.com/KiCad/kicad-symbols/pull/2417 ?

**Comment by chschlue** [comment]
Not necessarily. Feel free to take it if you want it.

**Comment by myfreescalewebpage** [comment]
Hi @RICCIARDI-Adrien , thanks for contributing,

A few comments I have during my review (I have not necessary read the previous PR):

- [ ] The name of the symbol should be "BQ24230RGT"
- [ ] Footprint is in the lib and shoudl be: `Package_DFN_QFN:VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm_ThermalVias`
- [ ] Fp filter: `VQFN*1EP*3x3mm*P0.5mm*`
- [ ] Description ends with package name: `USB-Friendly Lithium-Ion Battery Charger And Power-Path Management IC, VQFN-16`
- [ ] TS, ISET, TMR and ILIM should be Passive
- [ ] PGOOD and CHG should be Open Collector
- [ ] Pin 17 should be stacked with VSS
- [ ] height of the symbol can be reduced by 100mil

Cheers,
Joel

**Comment by RICCIARDI-Adrien** [comment]
Hi @myfreescalewebpage , here are the requested changes.

- [x] The name of the symbol should be "BQ24230RGT"
- [x] Footprint is in the lib and shoudl be: `Package_DFN_QFN:VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm_ThermalVias`
- [x] Fp filter: `VQFN*1EP*3x3mm*P0.5mm*`
- [x] Description ends with package name: `USB-Friendly Lithium-Ion Battery Charger And Power-Path Management IC, VQFN-16`
- [x] TS, ISET, TMR and ILIM should be Passive
- [x] PGOOD and CHG should be Open Collector
- [x] Pin 17 should be stacked with VSS
- [x] height of the symbol can be reduced by 100mil : **I had to adjust size a bit to avoid violating S3.1 and S4.1 rules.**

`checklib.py` was also reporting S4.3 rule violation, due to pin `EP` stacking with `VSS`. I renamed `EP` in `VSS` to avoid violating the rule.

Don't hesitate to ask if more changes are needed.

Capture d’écran_2020-09-06_00-04-02

**Comment by myfreescalewebpage** [comment]
Hello @RICCIARDI-Adrien thanks for the update.
For the height you can do it, it will only be an info in travis result.
Joel

**Comment by RICCIARDI-Adrien** [comment]
Here is the symbol with decreased height :
Capture d’écran_2020-09-06_21-11-36

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
