### PR TITLE
Add P-MOS - Vishay SiS415DNT

### PR DESCRIPTION
**Pull request by jneiva08**
Add Mosfet P from Vishay

Datasheet: https://www.vishay.com/docs/63684/sis415dnt.pdf
Symbol:
sis415dnt

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08, thanks for contributing,

A single comment I have during my review:

- [ ] Pins 6 to 8 are missing, should be connected to Drain.

Cheers,
Joel

**Comment by jneiva08** [comment]
Updated description, forgot to add footprint name.
Updated footprint filter.

@myfreescalewebpage, i didn't add the Drain pin (6 ~ 7), because the footprint don't have it. Because the Drain pad is "Custom Shape Primitives", you can see on the following [link](https://github.com/KiCad/kicad-footprints/pull/998)

**Comment by myfreescalewebpage** [comment]
@jneiva08 

> @myfreescalewebpage, i didn't add the Drain pin (6 ~ 7), because the footprint don't have it. Because the Drain pad is "Custom Shape Primitives", you can see on the following link

Great, I only looked at the datasheet and wasn't aware the footprint in Kicad has pin 5 like that.

@antoniovazquezblanco according to me this PR is ready to be merged.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco up!

**Comment by antoniovazquezblanco** [comment]
Done! Thanks to both!

**Comment by jneiva08** [comment]
Thanks

**Comment by myfreescalewebpage** [comment]
Thanks @antoniovazquezblanco

**Pull request merged**
