### PR TITLE
Added TPS7A7001DDA.

### PR DESCRIPTION
**Pull request by matthuszagh**
www.ti.com/lit/ds/symlink/tps7a7001.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
minor style comments: looking at other parts in the lib I would move pins 2 and 7 up by 100mils, and place GND in the middle of the symbol.

**Comment by matthuszagh** [comment]
@aewallin I've modified per your comments.

**Comment by aewallin** [comment]
consider "http" at the start of the documentation link.

otherwise ready to be merged as far as I can tell.

**Comment by matthuszagh** [comment]
Fixed.

**Comment by matthuszagh** [comment]
Thanks @myfreescalewebpage. Those are now fixed.

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment to do, merging.

Joel

**Pull request merged**
