### PR TITLE
MP2303A added

### PR DESCRIPTION
**Pull request by EpeR1**
## MP2303 Added
Dataset: https://www.monolithicpower.com/pub/media/document/MP2303A_r1.1.pdf

### NOTE
(Violating S4.2)
I placed the BS and FB pins to the right side, for a better wiring up.

Image from dataset:
mp2303_o

Created symbol:
mp2303

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Put `, DIP-8/SOIC-8` on the end of the description.
1. The SOIC footprint filter should be `SOIC*1EP*3.9x4.9mm*P1.27mm*`.
1. Pin 2 can move to the top.
1. Pin 1 can be Passive type.
1. Center pin 4.
1. Perhaps move pin 6 to the left side and spread out the remaining 3 pins on the right side.

**Comment by EpeR1** [comment]
Done.
mp23

**Comment by EpeR1** [comment]
ping..
Any news?

**Comment by evanshultz** [comment]
@EpeR1
Sorry. I missed your update. Can you please center pin 2 on the top? Then, if my former self didn't miss anything, this is ready to merge once the branch conflicts are resolved. Thank you for taking this time to make updates.

For the future, we now request symbols to be split by package and not combine SOIC and DIP packages into a single symbol, but since this was apparently started before that rule was in place we'll go ahead and allow it.

**Comment by evanshultz** [comment]
@EpeR1 
Ping!

**Comment by EpeR1** [comment]
Done.
But I can split the symbol for different footprint.
(It requires just only a copy, because the pinout is the same.)
Do I split them?

**Comment by evanshultz** [comment]
@EpeR1 
Sure, if you don't mind to split them that would be great. Once they're split, be sure to assign the correct default footprint and remove one of the footprint filters (leaving the correct one). Thank you!

**Comment by EpeR1** [comment]
Done.

**Comment by evanshultz** [comment]
Thanks!

Two things remain:
1. Assign the correct default footprint.
1. The symbol names should replace '_SOIC' with 'ADN' per the MPN in the datasheet. And similar for the DIP package.

**Comment by EpeR1** [comment]
done

**Comment by evanshultz** [comment]
@EpeR1 
Great. Thank you!

The only issue is that the SOIC thermal pad nominal dimensions are 2.41x3.31mm. And our footprint generator might use the max size; I can't quite remember. I know it seems pedantic, but it appears we don't have quite the correct footprint and in similar cases, even if the difference is very small, we've required correct footprints. Are you willing to use our footprint generator script for this package type (https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO) to submit a footprint that exactly matches the package in the datasheet? After all of this time and the work you've just done I feel sad to ask, but that's what we're required in the past. Thank you once again.

**Comment by EpeR1** [comment]
@evanshultz 
Sorry, for the big late.
Here is the requested footprint:
https://github.com/KiCad/kicad-footprints/pull/2502

**Comment by evanshultz** [comment]
This looks great now. Thank you! Once the footprint is merged this should be ready to go.

**Comment by evanshultz** [comment]
With the footprint merged CI is now all green here. Thanks again!

**Pull request merged**
