### PR TITLE
Add TJA1145 CAN Transceivers

### PR DESCRIPTION
**Pull request by HubertD**
Add Support for NXP CAN Transceivers with SPI configuration interface and FD-active/FD-passive partial networking support

Datasheet link: https://www.nxp.com/docs/en/data-sheet/TJA1145.pdf

TJA1145TK package is named "HVSON-14" in the datasheet, I suspect that's just NXPs name for our Package_DFN_QFN:DFN-14-1EP_3x4.5mm_P0.65mm_EP1.65x4.25mm - At least the kicad DFN package seems to be a perfect fit.

---

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by HubertD** [comment]
tja1145t
tja1145tk

**Comment by SchrodingersGat** [comment]
Hi @HubertD these look good, only change I'd suggest is to suffix the footprint info in the description field, so it can be displayed in the part selector:

e.g.

```High-speed CAN transceiver for partial networking, SOIC-14```

```High-speed CAN transceiver for partial networking, DFN-14```

**Comment by myfreescalewebpage** [comment]
Hi @HubertD , thanks for contributing,

Additionally to comment of @SchrodingersGat, for both devices, 
- [ ] Pin 14 name should be `~SCS`

Cheers,
Joel

**Comment by HubertD** [comment]
@myfreescalewebpage @SchrodingersGat agreed. fixed.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
