### PR TITLE
Add PCF8523 RTC

### PR DESCRIPTION
**Pull request by johnfwhitmore**
This is an initial commit of symbol for the PCF8523 RTC,
Upload for CI check, but struggling with datasheet entry for base symbol. Earlier today for another
component it's flagged as missing but if you add it to the general tab it gets flagged for being included.

Datasheet - https://www.nxp.com/docs/en/data-sheet/PCF8523.pdf

screenshot from 2018-10-17 20-02-06

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
I seem to have lost the knack of this. I thought that PCF8523T and PCF8523TK could be added together as they share the same symbol, but I'm struggling with footprints. 

Should my base class be "PCF8523" and then have two alias components?

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @johnfwhitmore 

For this PR, see also my comment at https://github.com/KiCad/kicad-symbols/pull/1073. Devices need to be duplicated. See also for example RTC already in the library: DS1302 and all the variants.

Joel

**Comment by johnfwhitmore** [comment]
I responded to #1073, but same applies to this one. Getting started but I'll have to try and find that work. It's been a while and out of site out of mind, or vice versa. Thanks for the pointer to DS1302, I'll have to look at it as I'm a bit confused it sounds like the process has changed somewhat.

**Comment by johnfwhitmore** [comment]
Have to add a new footprint for this as the SO-8 in the libs is different?

https://github.com/KiCad/kicad-footprints/pull/1309

**Comment by myfreescalewebpage** [comment]
Hi @johnfwhitmore I have seen SO-8 package has been merged for this device, can you address the above comment, i.e. create two symbols, so we can review and merge. Thanks, Joel

**Comment by myfreescalewebpage** [comment]
@johnfwhitmore ping :)

**Comment by johnfwhitmore** [comment]
Sorry been distracted. Working it now.

**Comment by johnfwhitmore** [comment]
Bare with me it's been a while and I usually build kicad from source. Then
I usually hop between distros so I'm building on this machine for the first
time. This takes a while. Sorry.

**Comment by myfreescalewebpage** [comment]
@johnfwhitmore no worries my previous message was just to get news from you :) Thanks for the pong :)

**Comment by evanshultz** [comment]
We have been driving towards unique symbols if footprints are different, so things indeed may have changed a bit. At since since you and I worked through some PRs. However, between T and TK there would always have needed to be unique symbols because there is a thermal pad on the TK package, so that part should be the same for years.

**Comment by myfreescalewebpage** [comment]
I do not clearly understand you previous message. T and TK versions are different because they have not the same package. Moreover the TK version has one more pin (the exposed pad); So the symbol are different.
Joel

**Comment by johnfwhitmore** [comment]
Sorry deleting this to start afresh.

**Comment by myfreescalewebpage** [comment]
Ok.

**Comment by johnfwhitmore** [comment]
This time #1707

So far so good, but pin placement might be an issue. Trade off between
clearance & size

**Comment by myfreescalewebpage** [comment]
Thanks!

**Comment by johnfwhitmore** [comment]
No problem, hope it's close. Going to sort other footprints.

**Pull request closed without merging**
