### PR TITLE
Add LME49600 high current audio buffer

### PR DESCRIPTION
**Pull request by qberthet**
[Datasheet](http://www.ti.com/lit/ds/symlink/lme49600.pdf)

Screenshot from 2019-10-04 00-23-06
)
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for contributing and welcome!
1. Can you change `250mA Audio Buffer` in the description to `Headphone Buffer, 250mA`?
1. Then add the package (`TO-263`) at the end of the description with a comma separator.
1. Pin 3 should be Power Input type.

**Comment by qberthet** [comment]
Done, V- as passive was a vestige of an aborted stacked pin approach, sorry

Updated screenshots:
Screenshot from 2019-10-08 19-44-18
Screenshot from 2019-10-08 19-44-36

**Comment by evanshultz** [comment]
The changes above are done correctly, but the datasheet should not be in the LIB file, only the DCM file. See the latest commit. Can you fix that and then I can merge?

**Comment by qberthet** [comment]
Hum, didn't change that, is it because I updated my kicad install to current master since I started the symbol?

Should I edit it by hand?

**Comment by evanshultz** [comment]
Yes. See http://kicad-pcb.org/libraries/klc/G1.8/. In fact, a more strongly-worded and complete guideline for this clause is under review now.

**Comment by qberthet** [comment]
Ok, thanks, will update my other pull request

**Pull request merged**
