### PR TITLE
Addition of OPA1692 as a variant

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of OPA1692 Audio Opamps

I've added these as variants of LM2904 - however is this the right way of doing this? (some of the footprints listed under the parent are not compatible with the OPA1692.) Should I create a separate part with only the correct footprints?

Datasheet Link: https://www.ti.com/lit/ds/symlink/opa1692.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
Please add these aliases to fully specified symbols (symbols with package suffix and the correct default FP) like NCS2325D and OPA2197xDGK, respectively.

**Comment by jamesrlucas** [comment]
Done :)

**Comment by chschlue** [comment]
One more thing: add VFA and whatever you can think of that people might use to search for this part to the keywords. `dual` is unnecessary as that word is already in the description.
Looks good otherwise.

**Comment by jamesrlucas** [comment]
Okay - I've added VFA to the keywords instead of dual, I can't think of anything else that isn't already in the description or keywords that I would search for...

**Comment by chschlue** [comment]
Thanks

**Pull request merged**
