### PR TITLE
Added HT12E

### PR DESCRIPTION
**Pull request by G-Pereira**
Similar to #1932 
[Datasheet](https://www.holtek.com/documents/10179/116711/2_12ev120.pdf)
Pending [footprint](https://github.com/KiCad/kicad-footprints/pull/2427)
image

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by G-Pereira** [comment]
Ready to merge!

**Comment by G-Pereira** [comment]
@chschlue This uses the same footprint as HT12D #1932

**Comment by aris-kimi** [comment]
Hi @G-Pereira , thanks. This is ok, only need now is to resolve branch conflict and it can be merged.

**Comment by G-Pereira** [comment]
@aris-kimi Done! I am not sure if the error Travis is throwing is relevant

**Comment by myfreescalewebpage** [comment]
@aris-kimi would you like to finalize this ?
The travis error is due to another pull request (working on this). No issue with your symbol.

**Comment by aris-kimi** [comment]
Merged. Thank you both once again.

**Pull request merged**
