### PR TITLE
Add MCP6V67EMNY Op Amp in TDFN-8

### PR DESCRIPTION
**Pull request by yankee14**
Add TDFN-8 version of op amp from earlier PR https://github.com/KiCad/kicad-symbols/pull/2778

`kicad-symbols`: https://github.com/KiCad/kicad-symbols/pull/2822
`kicad-footprints`: https://github.com/KiCad/kicad-footprints/pull/2334
`kicad-footprint-generator`: https://github.com/pointhi/kicad-footprint-generator/pull/573

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/MCP6V66-Family-Data-Sheet-DS20006266A.pdf

Screencaps:

MCP6V67EMNY_A

MCP6V67EMNY_B

MCP6V67EMNY_C

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by chschlue** [comment]
FP merged

**Comment by myfreescalewebpage** [comment]
Thanks!

@yankee14 
- [ ] Fp filter should be `TDFN*1EP*3x2mm*P0.5mm*` (no "_" at the end), sorry this is an error in my previous comment! I apologize for this

Joel

**Comment by myfreescalewebpage** [comment]
@yankee14 ping

**Comment by yankee14** [comment]
@myfreescalewebpage hi Joel, no worries! Sorry I haven't responded, I have not had time to work on any of my PRs, but I should be able to in the next day or so

**Comment by yankee14** [comment]
I see the libraries are due to be locked soon! That's exciting, but I guess I'd better go clean up my PRs

**Comment by myfreescalewebpage** [comment]
Yes no new PR are now possible but we have few weeks to finalize the current work.
No more comment for this one, merging.

**Pull request merged**
