### PR TITLE
Improve IS31FL3216/A

### PR DESCRIPTION
**Pull request by fauxpark**
Fixing up the IS31FL3216 LED controller.

Before:
sym-1
After:
sym-2

 - Stacked GND pins, changed `1EP` pin to `GND`
 - Flipped `OUT9` to `OUT16` pin names so `OUTx` is along the body
 - Tweaked description and keywords
 - Shrunk and centered symbol
 - Corrected pin name offset

The `CLK` pin is used for synchronising multiple controllers, so I left it as bidirectional instead of input as Travis suggests: http://www.issi.com/WW/pdf/IS31FL3216.pdf#page=2
I also did not swap `SCL` and `SDA` as I figured that would be too disruptive.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
The symbol shrinking/moving will break existing schematics, and we don't want to do that during v5. Can you revert that part of it?

Agreed that CLK should be bidirectional.

**Comment by fauxpark** [comment]
Done.

**Comment by evanshultz** [comment]
Thank you!

With that done and the diff much less noisy, I took a look at the changes. This is mergeable now, but let me propose one thing: Remove temp from the description. KLC would wildcard this so it can be considered extraneous in this context.

**Comment by fauxpark** [comment]
Yeah, I did think that shouldn't have been there but left it alone just in case. Removed.

**Comment by evanshultz** [comment]
Great. Thanks!

**Pull request merged**
