### PR TITLE
Align FE310-G000 with KLC, add FE310-G002 alias

### PR DESCRIPTION
**Pull request by 0xdec**
Fixed some KLC inconsistencies (wrong pin lengths, body not on grid, double-negated active-low inputs, stacked the power pins). Also added the [FE310-G002](https://sifive.cdn.prismic.io/sifive%2F3d777659-a0dd-49ed-a011-5bebba17aecf_fe310-g002-ds.pdf) as an alias.

FE310-G000

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @0xdec , thanks for contributing,

A few comments I have during my review:

- [ ] The descriptions can be enhanced: ` RISC-V MCU, 8KB OTP Program Memory, 8KB ROM, 16kB Instruction Cache, 16KB SRAM, 320MHz, 1.8 and 3.6V, 24 GPIO, QFN-48` is great

Else, no comments to do, this is a great job !

Cheers,
Joel

**Comment by 0xdec** [comment]
Edited the description to match what you recommended, thanks!

Jordi

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Need to wait v6 for merging.

**Comment by 0xdec** [comment]
Awesome, is there a v6 tag that should be added?

**Comment by myfreescalewebpage** [comment]
The milestone is set :)

**Pull request merged**
