### PR TITLE
New Symbol THVD1451 (RS485 line driver)

### PR DESCRIPTION
**Pull request by atari91**
New Symbol THVD1451 based on DS89C21 but with some changes in the functional drawing to match better with the datasheet description and labeling.

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
* [datasheet](http://www.ti.com/lit/ds/symlink/thvd1451.pdf)
- [x] An example screenshot image is very helpful
grafik
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
* No errors
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
* This belongs in Interface_UART
* If this is supposed to be fully specified for SOIC-8, please call it THVD1451D
* Otherwise, add VSON
* [Remove ±](http://kicad-pcb.org/libraries/klc/G1.1/)

**Comment by atari91** [comment]
Thanks for your review.
- I moved the IC to interfaces_UART
- I renamed it to THVD1451D. 
- I removed the ± symbol and adjusted the description to `line driver and receiver, 3.3-V to 5-V, RS-485, ±18kV IEC ESD Protection, SOIC-8`

**Comment by chschlue** [comment]
Keywords:
- [ ] remove commas
- [ ] transceiver is misspelled and duplicated

**Comment by atari91** [comment]
- [x] remove commas
- [x] transceiver is misspelled and duplicated

Done. Thanks for the review.

**Pull request merged**
