### PR TITLE
Added ESDA6V1-5SC6 symbol

### PR DESCRIPTION
**Pull request by jneiva08**
Added symbol for ESD suppressor for data lines - ESDA6V1-5SC6

Datasheet: www.st.com/resource/en/datasheet/esda6v1-5sc6.pdf

Symbol:
esd

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- The symbol name does not have a hyphen in it.
- Change description to `Quad bidirectional transil, Suppressor for ESD protection, 6V1 Breakdown, SOT-23-6`.
- Change datasheet link to `http://www.st.com/resource/en/datasheet/esda6v1bc6.pdf`.
- Pin 2 should be Passive type.
- Your symbol has 5 back-to-back diodes but the actual part only has 4.
- Add a dot where the lines are interconnected inside the symbol.
- Stack pin 5 on pin 2.

**Comment by jneiva08** [comment]
Sorry, the datasheet i out os wrong
When arrive at home i Will fix ir.

**Comment by jneiva08** [comment]
Already fix the datasheet link on dcm file. Now should be right.

**Comment by evanshultz** [comment]
@jneiva08 
Are you interested in making the rest of the changes I requested above so I can merge this?

**Comment by jneiva08** [comment]
@evanshultz 
Sorry for the confusion, in the first post put the datasheet of ESDA6V1BC6, it was already on power_protection. Forgot to remove the zener extra.

the symbol for ESDA6V1-5SC6 look now:
esd

**Comment by evanshultz** [comment]
Many items I mentioned above are not done:
- Change description to `Quad bidirectional transil, Suppressor for ESD protection, 6V1 Breakdown, SOT-23-6`.
- Change datasheet link to `http://www.st.com/resource/en/datasheet/esda6v1bc6.pdf`.
- Pin 2 should be Passive type.
- Add a dot where the lines are interconnected inside the symbol.

Also:
- Use the datasheet pin names of `IO1` and so forth (I believe KiCad doesn't handle slashes in pin names).
- Your diode symbols are Schottky and they should be zener/TVS style

**Comment by jneiva08** [comment]
Connection of datasheet shows:
esd

Now the symbol looks like:
diode

**Comment by evanshultz** [comment]
Thanks! All is good except where I mis-typed the quantity of diodes above. Please update your description and change `Fifth` to `Quintuple` or otherwise indicate there are five diodes (could be something like `Transil Array For ESD Protection, Five Diodes, 6.1V Breakdown, SOT-23-6`). Then I can merge!

**Comment by jneiva08** [comment]
Should pin 2 not be power input?
I renamed it to GND like datashhet says. Now travis is giving error.

**Comment by evanshultz** [comment]
Pin 2 should not be Power Input type, it should stay as Passive type. This is an assumption of the scripts and it can be merged if you make the description adjustment I mentioned above.

**Comment by jneiva08** [comment]
changed description

esd

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
