### PR TITLE
New part MQ-6

### PR DESCRIPTION
**Pull request by gggfred**
New part, MQ-6 Semiconductor Sensor for Flammable Gas

[Datasheet](https://www.winsen-sensor.com/d/files/semiconductor/mq-6.pdf)

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
- [ ] Pin length should be 100mil
- [ ] There is no Footprint or Footprint-Filter yet
- [x] Pin electrical types are good 
- [x] Pin names seem to be okay. I could not find them in the datasheet. Did you make them up?

**Comment by cpresser** [comment]
I took a look again, the description is still missing the package name. It should look like the bottom two parts in this screenshot:
image

See http://kicad-pcb.org/libraries/klc/S6.3/

**Comment by gggfred** [comment]
I don't know if this is needed because this FP does not have a standard name

**Comment by cpresser** [comment]
> I don't know if this is needed because this FP does not have a standard name

That is a valid point that I did not consider. Following the rule it is not necessary to change the description.

**Pull request merged**
