### PR TITLE
Add IPD50R3K0CEAUMA1 and IPD50R380CEAUMA1

### PR DESCRIPTION
**Pull request by strombom**
Datasheets:
[`IPD50R3K0CEAUMA1`](https://www.infineon.com/dgdl/IPx50R3K0CE_2_0.pdf?folderId=db3a3043163797a6011637d4bae7003b&fileId=db3a304339dcf4b10139e7e9ff592ce4
)
[`IPD50R380CEAUMA1`](https://www.infineon.com/dgdl/Infineon-IPD50R380CE-DS-v02_01-en.pdf?fileId=db3a30433ecb86d4013ed0a2ef580f38
)

image

image

Symbols copied from existing symbol IPT012N08N5ATMA1.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Electrical specs should go `<param><unit> <value>`, so change `Qg (typ) 24.8nC` to `24.8nC Qg (typ)`.
1. We do not include packaging information, so please cut the PN after `K0CE`. This is a problem with other symbols in the lib, I know.
1. You're not taking advantage of the ALIAS function. This will allow both PNs to share a symbol since they do have the same symbol (logical match) and footprint (physical match). Create one symbol and then add logically and physically matching parts as an ALIAS to that symbol. Here is the dialog in the UI:
image

**Comment by evanshultz** [comment]
Thank you! Can you address the first item above and I will merge?

**Comment by strombom** [comment]
Oh missed that, updated.

**Comment by evanshultz** [comment]
Thanks again!

**Pull request merged**
