### PR TITLE
Add XP Power DC converters IA1205S and IH1205S and ITX1205S

### PR DESCRIPTION
**Pull request by ferdymercury**
https://www.xppower.com/pdfs/SF_IA.pdf
https://www.xppower.com/pdfs/SF_IH.pdf
https://www.xppower.com/pdfs/SF_ITX.pdf
https://www.xppower.com/pdfs/SF_ITQ.pdf
@stambaughw

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the official footprint library
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ferdymercury** [comment]
image
image
image

**Comment by ferdymercury** [comment]
Started working on this again. Symbol IA reworked:
image

**Comment by ferdymercury** [comment]
Here the ITX version. The IH is an alias of IA.
image

**Comment by antoniovazquezblanco** [comment]
Please use single lines to indicate galvanic isolation (Documented at https://github.com/KiCad/kicad-website/issues/284)

Also, there is a conflict to be resolved. Sorry and thanks!

Thanks!

**Comment by myfreescalewebpage** [comment]
Hello @ferdymercury 

That's a lot of devices but I wonder about the generic names they have. I think it's better to have some devices like the "TMR_1*" DC-DC converter already in the library. I mean, one device for each type and then some alias for each voltage/power.

There is also a major error when opening the editor that need to be fixed before making a review:

capture

Also, I don't find any footprint for these devices, have you make a PR for that ?

Thanks,
Joel

**Comment by ferdymercury** [comment]
Fixed missing symbol, thanks for noticing

**Comment by myfreescalewebpage** [comment]
Hello @ferdymercury 

The PR is very large, I try to make a review step by step. This will require some modifications several times I think, it is difficult to list every thing at the same time.

IAxxxx series:
You cannot have the same symbol for both the S and D package because the number of pads is not the same, this will make errors. I suggest for more clarity:
- [ ] To define IA0305S device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IA0503S to IA2424S to it.
- [ ] To define IA0305D device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IA0503D to IA2424D to it.
- [ ] To define IA4803S device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IA4805S to IA4824S to it.
- [ ] To define IA4803D device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IA4805D to IA4824D to it.

IHxxxx series:
You cannot have the same symbol for both the S and D package because the number of pads is not the same, this will make errors. I suggest for more clarity:
- [ ] To define IH0503S device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IH0505S to IH4824S to it.
- [ ] To define IH0503D device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IH0505D to IH4824D to it.

IHxxxx-H series:
You cannot have the same symbol for both the S and D package because the number of pads is not the same, this will make errors. I suggest for more clarity:
- [ ] To define IH0503S-H4 device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IH0505S-H4 to IH4824S-H4, alias IH0505S-H5 to IH4824S-H5 and alias IH0505S-H6 to IH4824S-H6 to it.
- [ ] To define IH0503D-H4 device, with complete description including output voltage, output current, isolation voltage, the right footprint, a single footprint filter ; And then to add alias IH0505D-H4 to IH4824D-H4, alias IH0505D-H5 to IH4824D-H5 and alias IH0505D-H6 to IH4824D-H6 to it.

Same logic for ITQxxxxS, ITQxxxxSA, ITQxxxxS-H, ITQxxxxSA-H, ITXxxxxS, ITXxxxxSA, ITXxxxxS-H, ITXxxxxSA-H series.

This is all for more clarity in the library, this is the logic applied for Murata DC-DC converter too. I know this is a lot of work, if you want to split it in several times this is possible of course.

Thanks,
Joel

**Comment by ferdymercury** [comment]
I fixed the error of the SIP and DIP packages not having the same number of pins. Now it should be correct.

**Comment by ferdymercury** [comment]
I splitted now the symbols so that each one has a default footprint.

**Comment by ferdymercury** [comment]
If we split now all symbols in aliases, this will add around 100 aliases. Is this needed?

**Comment by myfreescalewebpage** [comment]
Yes it's better to indicate a detailed description of the parts. Please look at the other DC/DC converter, they are all done with this logic.

**Comment by ferdymercury** [comment]
Added the description for the IA series. Please review it before I continue with the other series

**Comment by myfreescalewebpage** [comment]
@ferdymercury Will do.

**Comment by ferdymercury** [comment]
added IH series

**Comment by ferdymercury** [comment]
Added ITQ and ITX series. All symbols are now done. @myfreescalewebpage This is ready to be reviewed and merged.

**Comment by myfreescalewebpage** [comment]
@ferdymercury starting a new complete review from here. Sorry for the delay. However, I have a kicad error on opening, can you check this first ?

capture

Thanks,
Joel

**Comment by ferdymercury** [comment]
Fixed, thanks for pointing out.

**Comment by myfreescalewebpage** [comment]
@ferdymercury here is the review:

IA0305D/IA4803D/IH0503D/IH0503DH:
- [ ] Wrong pin numbers, not consistent with the footprints

ITQ2403SA-H:
- [ ] Pin 8 (NC) should be moved to the border outline of the symbol, and should be renamed "NC" only

ITX0505S:
- [ ] NC pins should be renamed "NC" only

ITX0505S-R:
- [ ] NC pin should be renamed "NC" only

ITX0503SA
- [ ] Pins 3 and 5 (NC) should be addedto the symbol.
- [ ] NC pins should be renamed "NC" only

ITX0503SA-R:
- [ ] Pin 8 (NC) should be moved to the border outline of the symbol, and should be renamed "NC" only
- [ ] NC pins should be renamed "NC" only
- [ ] Isolation barrier should be a single dash line

Cheers,
Joel

**Comment by ferdymercury** [comment]
Changed.

Why should I add pins 3 and 5 in ITX0503SA?

They are marked as N.P. (no pin). This is different from N.C. (not connected)

**Comment by myfreescalewebpage** [comment]
@ferdymercury seems very nice now, no more comment to do on this PR.

> Why should I add pins 3 and 5 in ITX0503SA?

Mistake during the review, you are right they are not populated.

Cheers,
Joel

**Pull request merged**
