### PR TITLE
Added L6491 Driver

### PR DESCRIPTION
**Pull request by aris-kimi**
Under Driver_FET

Edit:

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2409

Datasheet: https://www.st.com/resource/en/datasheet/l6491.pdf

l6491

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aris-kimi , thanks for contributing,

A few comments I have during my review:

- [ ] I disagree with the package, it's not so large. You should probably create and submit it.
- [ ] Pin number to be fixed according to the datasheet (you made some errors)

Will do a new review after that

Cheers,
Joel

**Comment by aris-kimi** [comment]
Hi @myfreescalewebpage , don't know why this happened, i have fixed pin errors, also added one NC pin11.
(Fixes weren't committed yet, i will edit this line when i do)

I feel that this footprint needs to be scripted, but i am sorry because i will have to ask for guidance about footprint generator usage, if/what files needed to be modified and where to submit a PR..
If it is only about manualy design a new one, i feel more confident..

**Comment by chschlue** [comment]
FP merged

**Comment by myfreescalewebpage** [comment]
Thanks @chschlue for the footprint.
@aris-kimi there is still issues with pin number on the symbol. For example the datasheet indicate pin 1 is LIN, etc.
Joel

**Comment by aris-kimi** [comment]
Changes have been applied.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
