### PR TITLE
Add Nexperia PMEG SOD-123W Schottky diodes

### PR DESCRIPTION
**Pull request by chschlue**
PMEG40T10ER

https://github.com/KiCad/kicad-footprints/pull/1880

https://assets.nexperia.com/documents/data-sheet/PMEG40T10ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG40T20ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG40T30ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG60T10ELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG60T20ELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG60T30ELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2010BER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2010ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3010BER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3010ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3020BER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3020ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4010ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4020ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4030ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6010ELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6010ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6020AELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6020ELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6020ER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG10010ELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG10020AELR.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG10020ELR.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue can you rebase your branches so it will be possible to review this PR ? Thanks, Joel

**Comment by chschlue** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks. No comment on the symbol and the aliases. Just need to wait the footprint to merge this PR. Joel

**Comment by myfreescalewebpage** [comment]
@chschlue can you fix the branch conflict here ?

**Comment by chschlue** [comment]
Done.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
