### PR TITLE
Added symbol for the BAV756S diode

### PR DESCRIPTION
**Pull request by Duckle29**
Added a symbol for the BAV756S, which is a chip with 4 diodes, 2 common Anode, 2 common cathode

------------

[datasheet](https://assets.nexperia.com/documents/data-sheet/BAV756S_BAW56_SER.pdf)
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
It is desirable that you provide in the text both the data sheet link and a screen shot of the symbol showing the pin types etc.

something like this, then it is much easier and faster to give feedback 

bild

bild

bild

bild

**Comment by Misca1234** [comment]
If so, then you can get the following feedback back rather quickly


Move the "Package_TO_SOT_SMD:SOT-363_SC-70-6" to just beneath the symbol, it is placed to far away

to the description
"Quad diode package with one pair CA and one pair CC" 
add the package
"Quad diode package with one pair CA and one pair CC, SOT323/SC-70"

Change the foot print filter to 
SOT?363?SC?70?6*

**Comment by Duckle29** [comment]
Thank you, yes that makes a lot of sense :)

**Comment by Duckle29** [comment]
image
image
image
image

There we go :)

**Comment by evanshultz** [comment]
The diodes should be "open" (unfilled) with a line in the middle like IEC shows and other diodes in our library.

I often find these dual diodes don't go on circuit right next to each other. What about making this a dual-unit symbol and copying the existing CA diode symbol?

**Comment by Duckle29** [comment]
image
image
image
image

There we go. Made the symbol into a 2 unit symbol. and changed the filter back to the more generic filter.

I decided to center the diodes based on their pin positions, I don't know if I'd prefer the diode with the 2 horizontal pins on Y0, but I'll leave that up to you :)

**Comment by Duckle29** [comment]
image
image

**Comment by evanshultz** [comment]
This symbol type, like the existing generic diodes, is preferred.

- There should be a line through the middle of the diode symbols.
- Change description to `High-speed switching diodes, dual common anode/common cathode, SOT-363`.
- Pin name offset to 1mil.
- Remove underscore in pin names.

**Comment by evanshultz** [comment]
- What about pins names of A1, K2, CA, K3, A4, and CK. That would change pin names for pins 3 and 6.
- What about this symbol (removing overlapping lines, use common graphical elements where possible, all pin lengths to 100mil, and add junction dot):
```
# BAV756S
#
DEF BAV756S D 0 1 Y N 2 L N
F0 "D" 0 100 50 H V C CNN
F1 "BAV756S" 0 200 50 H V C CNN
F2 "Package_TO_SOT_SMD:SOT-363_SC-70-6" 0 -400 50 H I C CNN
F3 "" 0 -400 50 H I C CNN
$FPLIST
 SOT?363*
$ENDFPLIST
DRAW
C 0 0 10 0 1 0 F
P 2 0 1 0 -200 0 200 0 N
P 2 0 1 0 0 0 0 -100 N
P 3 1 1 8 -50 -50 -50 50 -50 50 N
P 3 1 1 8 50 -50 50 50 50 50 N
P 6 1 1 8 -150 50 -50 0 -150 -50 -150 50 -150 50 -150 50 N
P 6 1 1 8 150 -50 50 0 150 50 150 -50 150 -50 150 -50 N
X A1 1 -300 0 100 R 50 50 1 1 P
X A4 5 300 0 100 L 50 50 1 1 P
X CK 6 0 -200 100 U 50 50 1 1 P
P 3 2 1 8 -150 50 -150 -50 -150 -50 N
P 3 2 1 8 150 50 150 -50 150 -50 N
P 6 2 1 8 -50 -50 -150 0 -50 50 -50 -50 -50 -50 -50 -50 N
P 6 2 1 8 50 50 150 0 50 -50 50 50 50 50 50 50 N
X K2 2 -300 0 100 R 50 50 2 1 P
X CA 3 0 -200 100 U 50 50 2 1 P
X K3 4 300 0 100 L 50 50 2 1 P
ENDDRAW
ENDDEF
```
image

**Comment by evanshultz** [comment]
@Duckle29 
Visually this is fine. Probably many of our diodes can be updated later. Thanks!

**Pull request merged**
