### PR TITLE
Add AD5272/4

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/AD5272_5274.pdf
Footprint: https://github.com/KiCad/kicad-footprints/pull/1931

screenshot:
ad5272

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @AUTHOR, thanks for contributing,

A few comments I have during my review:

AD5272BCPZ
- [ ] Z is for "ROHS", the device name should be "AD5272BCP" in the lib
- [ ] ADDR should be passive

AD5272BRMZ
- [ ] Same comment, "AD5272BRM"

Can you rebase your branch to permit the merge ?

Cheers,
Joel

**Comment by jneiva08** [comment]
Hi @myfreescalewebpage , have made the changes requested.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
