### PR TITLE
Align BTS* symbols

### PR DESCRIPTION
**Pull request by evanshultz**
Continuing from https://github.com/KiCad/kicad-symbols/pull/572, a quick visual alignment of these related symbols.

image

https://www.infineon.com/dgdl/Infineon-BTS724G-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aa3a2f1030ff1 might be the only datasheet needed for review.

@johnfwhitmore 
Tagging you so you can see and provide feedback.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
Much better BTS724G symbol.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz 

Some few comments during my review:

BTS724G:
- [ ] Pin 1 should be Power Input, not Passive

BTS40K2-1EJC:
- [ ] Footprint filter should be `Infineon*DSO*43*`

Cheers,
Joel

**Comment by evanshultz** [comment]
Thanks for the review. Done!

**Comment by myfreescalewebpage** [comment]
@evanshultz no more comment, merging.

Joel

**Pull request merged**
