### PR TITLE
I80186 i80188

### PR DESCRIPTION
**Pull request by nickysn**
Added the 80186 and 80188 CPUs to the MCU_Intel library.

Datasheet:
http://datasheets.chipdb.org/Intel/x86/8018x/datashts/27243002.PDF

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by bobc** [comment]
Aren't these parts obsolete?

**Comment by nickysn** [comment]
There are compatible replacements for them still being manufactured, so I'm guessing they're still in use:
https://www.mouser.com/ProductDetail/Analog-Devices/IA186XLPLC68IR2?qs=sGAEpiMZZMutXGli8Ay4kLHstgsUE2tJOVYDMNmtmBI%3d
https://www.mouser.com/ProductDetail/Analog-Devices/IA188XLPLC68IR2?qs=sGAEpiMZZMvfhsTlJjecMCIli3epcke2Ru18qe15uWoVYf1VJ0EDpQ%3d%3d

**Comment by bobc** [comment]
I guess classic chips never die!

It seems Analog acquired Innovasic who designed these parts, maybe link to datasheets at http://www.innovasic.com/products/product-literature (I didn't find any on analog.com, maybe they will be there later).

**Comment by nickysn** [comment]
I think I'll add the new Analog Devices/Innovasic parts as an alias, with links to their datasheet as well.

**Comment by nickysn** [comment]
Ok, I added the Analog Devices/Innovasic parts as aliases:

IA186XLPLC68IR2
IA188XLPLC68IR2

As well as several other CMOS versions (with links to datasheets that were available on datasheets.chipdb.org), that are pin compatible with the original NMOS parts:

80C186
80C186XL
M80C186
M80C186XL
80C188
80C188XL

I have intentionally not included variants in packages, that are not compatible with one of the original ones, because these have different pin numbers and therefore require a different symbol and I wanted to have the symbols to the original parts reviewed and merged first.

**Comment by myfreescalewebpage** [comment]
Hi @nickysn , thanks for contributing,

A few comments I have during my review:

80188:
- [ ] All pin length should be 100mil (symbol < 100pins)
- [ ] VCC pins should not be stacked
- [ ] Name of pin 47 is `~TEST` according to the datasheet
- [ ] Name of pin 38 is `~MCS0` according to the datasheet
- [ ] Name of pin 37 is `~MCS1` according to the datasheet
- [ ] Name of pin 35 is `~MCS3` according to the datasheet

80188:
- [ ] All pin length should be 100mil (symbol < 100pins)
- [ ] VCC pins should not be stacked
- [ ] Name of pin 64 should be `S7`
- [ ] Type of pin 62 is Bidirectional

All devices: the description and keywords should be enhanced with some information about memory, etc, see format on other MCUs.

On 80186 and 80188 can you arrange the pins so that the CLKOUT pin is at the same place on both symbol, to allow easy swapping from one to another ?

When making some alias, they should have the same pin names and types and package. Here you have some alias with different pins names. You should not define them as alias but they should be define completely.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@nickysn any news here ? Thanks for the update!

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this is abandoned.

**Comment by antoniovazquezblanco** [comment]
There is activity again! Thanks @nickysn !

**Comment by nickysn** [comment]
Yep, sorry for the long delay, I'll try to finish this in the next few weeks. Even though I'm still kind of busy this week (especially the upcoming weekend), I should have much more free time starting next week. :)

**Comment by poeschlr** [comment]
Don't stress yourself. Your contribution will be ready when it is ready ;)

**Comment by myfreescalewebpage** [comment]
@nickysn thanks for the enhancements, please refer to my previous list to the remaining job to do, just updated.
Joel

**Comment by myfreescalewebpage** [comment]
@nickysn great job, looks completed :) Merging. Thanks for this!

**Pull request merged**
