### PR TITLE
Added SA15-11SRWA 7 segment display

### PR DESCRIPTION
**Pull request by kajusK**
Added SA15-11SRWA 7 segment display
2018-11-09-195250_1920x1080_scrot

Datasheet:http://www.farnell.com/datasheets/2047536.pdf

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @kajusK, thanks for contributing,

A single comment I have during my review:

- [ ] Can you have a look at the footprint, you are currently violating KLC S5.1 and S5.2 (travis output) that should be fixed.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@kajusK up ?

**Comment by kajusK** [comment]
@myfreescalewebpage Sorry, didn't have much time recently, I'll fix it during Christmas holidays.

**Comment by kajusK** [comment]
Added the footprint in https://github.com/KiCad/kicad-footprints/pull/1246

**Comment by myfreescalewebpage** [comment]
Hello @kajusK thanks for the footprint. Please proceed the modifications on it first. You will also have to rename the symbol according to the footprint and fix the KLC errors here.

Joel

**Comment by myfreescalewebpage** [comment]
@kajusK can you solve the branch conflict here, this prevent terminating the review... Thanks.

**Comment by kajusK** [comment]
@myfreescalewebpage Never done that before, I hope the merge is ok

**Comment by myfreescalewebpage** [comment]
@kajusK It is ! Can you complete the footprint field, you are currently violating KLC S5.1.

**Comment by kajusK** [comment]
Default footprint added

**Comment by myfreescalewebpage** [comment]
@kajusK just seen the footprint filter cannot contains "-" character (travis error S5.2), can you change it to "SA15?11*" ? That's my last inquiry for this PR :)

**Comment by kajusK** [comment]
@myfreescalewebpage  Fixed, thanks for your cooperation and patience in this journey :)

**Comment by myfreescalewebpage** [comment]
@kajusK thanks to you for your job ! Merging your contribution :)

**Pull request merged**
