### PR TITLE
Added 74HC1G02 and 74HC164

### PR DESCRIPTION
**Pull request by mpkopec**
Added single 2 input NOR gate.

image

image

Added 8-bit serial in parallel out shift register.
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by mpkopec** [comment]
Off-center in 74HC164 is due to its asymmetry.
Non-standard pins in the gate are used for ensuring the readability of the symbol.

**Comment by mpkopec** [comment]
Closing this pull request since there is this NOR gate in the library. I will move the 74HC164 to a new pull request without any more new components added.

**Comment by evanshultz** [comment]
FYI, single-gate logic symbols should not have separated power pins.

**Comment by mpkopec** [comment]
Just to make sure, I should use the scheme of the hidden supply pins, yes?

**Comment by evanshultz** [comment]
Just match the library for now. Standardizing this is a task that will hopefully (I think must) come for v6 so it will all be sorted out globally later.

If it's helpful, here is a relevant discussion: https://github.com/KiCad/kicad-symbols/issues/190.

**Pull request closed without merging**
