### PR TITLE
This is the symbol for the Raytac's MDBT42Q

### PR DESCRIPTION
**Pull request by prajwaltelkar**
Raytac’s MDBT42Q is a BT 4.0, BT 4.1 and BT 4.2 stack (Bluetooth low energy or BLE) module designed based on Nordic nRF52832 SoC solution, which incorporates: GPIO, SPI, UART, I2C, I2S, PWM and ADC interfaces for connecting peripherals and sensors.

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

URL: https://statics3.seeedstudio.com/assets/file/bazaar/product/MDBT42Q-Version_B.pdf
SCREENSHOT:
SYMBOL1

### CODE REVIEW

**Comment by aewallin** [comment]
some basic questions, based on a quick look:
* this symbol should be placed inside an existing library
* is there a footprint?
* can the GND pins be stacked?

**Comment by prajwaltelkar** [comment]
Yup I shall place this in the symbol library
I have made the footprint and pulled the request

**Comment by poeschlr** [comment]
Do you agree with your submission being published under the KiCad libraries licence? If so please sign the licence agreement.

**Comment by myfreescalewebpage** [comment]
@prajwaltelkar the device should be added in an existing library. A library has 2 files (dcm and lib) and contain multiple symbol. We do not put 1 file = 1 symbol.

Probably the best library for this device is RF_Bluetooth.

**Comment by myfreescalewebpage** [comment]
@prajwaltelkar ping!

**Comment by prajwaltelkar** [comment]
Sorry I was bit busy and couldn't upload the symbol to respective repository.
Could you please guide me to which repository should I pull the request since I am bit new to this.

Thank you.

**Comment by myfreescalewebpage** [comment]
No worries.
This one, https://github.com/KiCad/kicad-symbols.
But the problem is we don't have a library for each device. They are grouped by category. You device should go in the RF_Bluetooth library.
Joel

**Comment by prajwaltelkar** [comment]
Sure ,will do this as soon as I find time..

Thank you.

**Comment by prajwaltelkar** [comment]
I have added the symbol in the RF_Module library.I have modified both lib and dcm files.

This is the screenshot of the symbol

screenshot_mdbt42q


Thank you.

**Comment by myfreescalewebpage** [comment]
This is not done properly, when I open KiCad i have the following error.

Capture

You should not just copy/paste the content of the file you have integrated, the format should be respected, else it does not work ....

Joel

**Comment by prajwaltelkar** [comment]
Could you please guide me how to do..
Sorry,I think so I had to know this but am not getting ..

**Comment by myfreescalewebpage** [comment]
You are probably not working correctly from the beginnings.

1- fork the official kicad repo in your github account
2- clone your fork on your computer
3- configure kicad to use the clone in lib paths parameters
4- edit the library (add you device)
5- push your modification on a new branch on your fork
6- go to your github fork, github propose you to make a pull request to the kicad repo

Hope this helps. If you want to close this PR and open a new one using this steps it's ok of course.
Joel

**Comment by myfreescalewebpage** [comment]
@prajwaltelkar ping

**Pull request closed without merging**
