### PR TITLE
added Infineon BTN8982TA Half-Bridge to Power_Management library

### PR DESCRIPTION
**Pull request by daviid5**
added Infineon BTN8982TA Half-Bridge to Power_Management library ( https://www.infineon.com/dgdl/Infineon-BTN8982TA-DS-v01_00-EN.pdf?fileId=db3a30433fa9412f013fbe32289b7c17 )
added NEXPERIA PSMN5R2-60YL N-Channel Mosfet to Transistor_FET library ( https://assets.nexperia.com/documents/data-sheet/PSMN5R2-60YL.pdf  )

btn8982ta

psmn5r2-60yl

*Replace this line with your commit message! Please provide a description of your pull request*

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@daviid5 
You need to sign the CLA first of all. Can you please do that before we can consider to merge this PR?

**Comment by daviid5** [comment]
@evanshultz I already signed the CLA, but I don't really get if it had worked, because is still says "license/cla — Contributor License Agreement is not signed yet."
Any idea how to solve this?

**Comment by daviid5** [comment]
@evanshultz 
Well where can I check which email was used?

I created this PR out of the GitHub Web Interface, and I have just one GitHub Account.

**Comment by evanshultz** [comment]
Find your icon in the top right of a GH page, then select Settings > Emails. If it's not there, I'm not sure. But that's a good place to start checking.

Did you also click on the `CLA not signed yet` icon above?

**Pull request closed without merging**
