### PR TITLE
Tweak RPi connector

### PR DESCRIPTION
**Pull request by fauxpark**
I'm using the RPi symbol in a project and thought it needed a few small changes.

 - I removed the footprint and added a second filter for the appropriate PinSocket footprints. This is useful when designing a board that simply plugs in over top of the Pi, such as HATs (although they recommend a specific type of dual SMD/THT socket, that I believe is not yet in the libraries, in order to be considered a "HAT")
 - I changed some of the pin names similar to how I did them in the Atmel MCU libraries, with the GPIO number around the inside edge of the symbol and the "alternate functions" towards the middle, separated by a slash. I based the names off of [pinout.xyz](https://pinout.xyz), particularly the graphical pinout on the right.
 - The "datasheet" had gone missing - looks like they implemented or changed the naming convention for their schematics: https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/README.md. Now it points to the 3B+.
 - GPIO0/1 are now at the top right, above GPIO2/3, to keep the numbering in order.

sym

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!
could you do some more changes please?
1. Please stack the power-pins, which can shrink the symbol further
2. Could you make the style closer to other (functional) connector that we have:
2018-04-28 09_37_53-symbol library editor - connector d__kicad_kicad-symbols_connector lib
i.e. add the small rectangles inside the pins, maybe a RPi Logo (if there is one)
3. Having the name INSIDE the connector is unusual in the lib and it is hard to find it between all the pin-labels. Please move outside

thanks,
JAN

**Comment by jkriege2** [comment]
PS: This is for building a "shield", i.e. an add-on board, correct?

**Comment by fauxpark** [comment]
Yes, this symbol is mainly useful for building addon boards (they are called "HATs" instead of shields, when conforming to certain physical dimensions and components). That's also why I think stacking the power pins should not be done here. HATs can be stacked and do not necessarily use all of the power pins.

2 and 3 are done, though I don't know how to add an RPi logo to the symbol.

**Comment by jkriege2** [comment]
Hi!

I used the bitmap-converter of KiCAD ... and here is some code for the logo to paste into your symbol:
```
P 312 0 0 1 11 -180 30 -173 52 -162 74 -149 94 -136 106 -125 111 -120 119 -103 129 -81 138 -58 144 -38 147 -25 146 -23 142 -10 130 8 121 22 117 34 117 37 112 50 102 64 93 76 91 82 96 86 107 94 118 109 126 127 131 145 130 161 124 170 111 176 83 180 55 178 30 170 12 156 1 141 -8 156 -10 158 -26 170 -49 178 -75 181 -100 178 -121 168 -123 167 -129 153 -129 146 -118 146 -116 160 -105 168 -104 169 -85 172 -62 172 -40 170 -25 165 -19 161 -11 149 -7 135 -7 130 12 130 14 143 20 156 30 165 31 166 47 170 69 172 91 172 110 168 113 167 121 157 122 142 117 124 107 106 91 92 78 86 63 82 57 83 42 88 32 97 31 108 32 114 26 114 20 113 14 119 12 130 -7 130 -8 123 -12 115 -21 114 -26 115 -26 108 -25 101 -33 90 -48 84 -69 85 -90 96 -103 109 -114 128 -118 146 -129 146 -127 135 -118 115 -104 96 -84 77 -98 64 -108 51 -112 38 -115 25 -103 25 -102 38 -98 49 -84 65 -60 74 -48 75 -42 71 -46 62 -55 52 -34 52 -33 62 -25 72 -12 79 4 81 20 78 33 69 35 65 47 65 49 71 57 74 70 72 85 65 98 55 106 44 109 31 107 23 102 23 91 28 76 37 62 48 51 58 47 65 35 65 39 57 35 44 24 38 6 36 -12 38 -27 44 -34 52 -55 52 -61 46 -69 39 -86 25 -98 20 -103 25 -115 25 -124 10 -127 6 -140 -15 -143 -33 -141 -41 -130 -41 -130 -24 -125 -6 -117 7 -106 12 -102 11 -98 1 -98 -13 -89 -13 -88 -10 -82 4 -70 19 -56 31 -43 35 -41 35 -23 30 -11 16 -6 -1 -6 -7 12 -7 14 12 22 26 25 28 42 35 59 33 74 24 86 10 93 -7 93 -15 101 -15 102 1 106 9 115 9 124 0 132 -14 135 -29 133 -41 127 -55 125 -58 119 -62 112 -57 108 -49 103 -32 101 -15 93 -15 92 -25 82 -41 74 -47 55 -52 36 -46 19 -30 16 -25 12 -7 -6 -7 -9 -20 -21 -38 -36 -49 -55 -52 -72 -47 -84 -33 -89 -13 -98 -13 -97 -15 -100 -35 -103 -43 -109 -58 -116 -62 -124 -55 -125 -55 -130 -41 -141 -41 -137 -53 -135 -58 -126 -78 -125 -83 -111 -83 -108 -73 -99 -66 -87 -66 -73 -73 -60 -84 -55 -92 -40 -92 -39 -74 -27 -55 -25 -54 -6 -43 13 -43 32 -55 33 -57 45 -75 45 -93 33 -111 23 -117 47 -117 52 -99 65 -79 75 -70 90 -60 103 -61 111 -73 114 -85 110 -106 96 -124 91 -128 73 -137 59 -137 50 -130 47 -117 23 -117 16 -121 -5 -122 -26 -111 -30 -108 -40 -92 -55 -92 -51 -98 -47 -116 -48 -127 -53 -134 -65 -135 -81 -130 -97 -118 -108 -101 -111 -83 -125 -83 -118 -100 -116 -107 -109 -119 -100 -129 -85 -140 -67 -151 -38 -151 -35 -143 -27 -139 -10 -136 10 -135 28 -137 41 -141 45 -145 43 -152 33 -162 14 -174 -6 -175 -26 -164 -32 -159 -38 -151 -67 -151 -62 -154 -54 -159 -31 -171 -11 -179 1 -182 11 -180 F
P 8 0 0 1 -36 120 -36 122 -43 127 -46 129 -45 125 -44 123 -39 118 -36 120 F
P 8 0 0 1 50 124 51 126 50 130 44 124 43 122 43 118 44 118 50 124 F
```

2018-04-28 13_27_55-symbol library editor - connector d__kicad_kicad-symbols_connector lib

**Comment by jkriege2** [comment]
PS: I think the small rectangles should be a bit larger ... compare the USB above

**Comment by fauxpark** [comment]
Ah, I forgot about that tool, whoops. Thank you for the code!

How is this:
sym

**Comment by Ratfink** [comment]
I'm not sure if we're allowed to use that logo here: https://www.raspberrypi.org/trademark-rules/

If it is used, we'd certainly at least need to leave the ® in place.

**Comment by fauxpark** [comment]
Reverted.

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
