### PR TITLE
Add Geiger-Müller symbol

### PR DESCRIPTION
**Pull request by heitorPB**
I asked in the [forums about a Geiger tube symbol](https://forum.kicad.info/t/geiger-tube-symbol/15058), there was none so I decided to make one and contribute to KiCad :)

This is a generic part, without footprint.

gm

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @heitorPB , thanks for contributing,

A few comments I have during my review:

- [ ] Documentation link should be `~` to avoid KLC error
- [ ] I suggest to set pin type to Passive to avoid any ERC errors in the schematics

Else, sounds good, thanks for this nice symbol.

Cheers,
Joel

**Comment by heitorPB** [comment]
Thanks for the review, @myfreescalewebpage! I made the changes you suggested.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by heitorPB** [comment]
Awesome!
Thanks!

**Pull request merged**
