### PR TITLE
Add Mini-Circuits RMK-3-451 frequency multiplier

### PR DESCRIPTION
**Pull request by aewallin**
Mini-Circuits RMK-3-451 frequency multiplier

https://ww2.minicircuits.com/pdfs/RMK-3-451+.pdf

rmk-3-451

no footprint PR yet.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin 

Same comments already fixed at #1200

Cheers,
Joel

**Comment by aewallin** [comment]
after revisions:
rmk-3-451

**Comment by myfreescalewebpage** [comment]
@aewallin footprint and footprint filter to be updated on this one.

Joel

**Comment by aewallin** [comment]
my manual merge seems to have caused a mess - again.

**Comment by aewallin** [comment]
closing and making a new PR.

**Comment by aewallin** [comment]
continued as #1371

**Pull request closed without merging**
