### PR TITLE
add ONET1191PRGT 11.3Gbps limiting amplifier, QFN-16

### PR DESCRIPTION
**Pull request by aewallin**
http://www.ti.com/lit/ds/symlink/onet1191p.pdf

ONET1191P

I suggest using an existing footprint with an EP of 1.7x1.7mm. This part has an EP of 1.68x1.68mm - so the difference is 0.02mm.

suggested footprint dimensions here:
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/qfn-1x.yaml#L115

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Device name should be `ONET1191PRGT` to avoid future conflict with new packages
- [ ] Footprint filter should be `VQFN*1EP*3x3mm*P0.5mm*`
- [ ] We always create the exact footprint following the specification, please submit a footprint for this device with the right EP size, and also VQFN, not QFN
- [ ] Name of pin 11 is `DISABLE`

OK for stacking VCC pins according to application schematic.

Cheers,
Joel

**Comment by aewallin** [comment]
in fact the VQFN footprint seems to already exist!
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/vqfn.yaml#L56

**Comment by aewallin** [comment]
ONET1191PRGT

**Comment by myfreescalewebpage** [comment]
@aewallin thanks for the fixes, no more comment, merging.

**Comment by aewallin** [comment]
great - thanks!

**Pull request merged**
