### PR TITLE
Fix LTC4417 symbol

### PR DESCRIPTION
**Pull request by eclecticc**
Updated to KiCAD 5 nightly and submitting a new PR.

The LTC4417 symbols in Power_Management are the SSOP part numbers (xGN), but use the QFN pinout and footprint (xUF). This PR adds proper LTC4417xGN symbols and moves the existing symbols to the correct LTC4417xUF names.
screen shot 2018-06-17 at 3 56 54 pm

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ x] An example screenshot image is very helpful
- [ x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Flawless, looks good, any objections for merging ?

@eclecticc 
Will you do the QFN variant as well ?

**Comment by eclecticc** [comment]
@Misca1234 , QFN is included in this.  The change was that the QFN symbol was already there, but incorrectly named with the SSOP part number.  This renames the QFN symbol to the correct part number and adds the SSOP symbol for it's correct part number.

**Comment by Misca1234** [comment]
Ok (I was focusing on LTC4417CGN)

**Comment by Ratfink** [comment]
I'd like to see the pins on the left and right shortened to 100 mil while these symbols are being changed.  The symbol will have to be shifted 50 mil to one side to keep all the pins aligned to the 100 mil grid, which is fine.

**Comment by eclecticc** [comment]
Updated with shortened pins.  
ltc4417cuf

**Comment by eclecticc** [comment]
screen shot 2018-06-24 at 3 07 05 pm

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
