### PR TITLE
Add Mini-Circuits LPF-B0R3 low-pass filter

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/LPF-B0R3+.pdf

lpf-b0r3

footprint will follow.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
waiting for footprint: https://github.com/KiCad/kicad-footprints/pull/1132

**Comment by myfreescalewebpage** [comment]
@aewallin conflict and footprint/fp filter to be updated here.

**Comment by aewallin** [comment]
thinner lines, and assign merged footprint
lpf-b0r3

**Comment by myfreescalewebpage** [comment]
@aewallin thanks, great job here ! Merging the PR.

**Pull request merged**
