### PR TITLE
Added new simbol library

### PR DESCRIPTION
**Pull request by hajrudin10**
Added symbol library ( interface_Driver_Receiver_Tranciever) for parts :
ISL3280ExHZ-T
ISL3281ExHZ-T
ISL3282ExRTZ-T
ISL3283ExHZ-T
ISL3284ExHZ-T

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by chschlue** [comment]
Welcome and thanks for your first contribution.

Please do not create a new lib for these symbols, Interface_UART should be a perfect fit. Also, please follow the PR template.

**Comment by hajrudin10** [comment]
All symbols have the same datasheet:
https://www.renesas.com/us/en/www/doc/datasheet/isl3280e-81e-82e-83e-84e-85e.pdf

image
image
image
image
image



https://github.com/jbots/kicad-jb-public/issues/3

**Comment by myfreescalewebpage** [comment]
Hi @hajrudin10 , thanks for contributing,

A few comments I have during my review:

ISL3280ExHZ-T
- [ ] Name should be "ISL3280ExHZ"
- [ ] Description can be enhanced: `RS485, RS422, 20Mbps Transceiver, 3.0V to 5.5V, SOT-23-5` for example
- [ ] Symbol a little bit large and tall, you can easily reduce. Dimensions like ISL3298xxRT symbol for example is good.

ISL3281ExHZ-T
- [ ] Name should be "ISL3281ExHZ"
- [ ] Description can be enhanced: `RS485, RS422, 20Mbps Transceiver, 3.0V to 5.5V, SOT-23-6` for example
- [ ] Symbol a little bit large and tall, you can easily reduce. Dimensions like ISL3298xxRT symbol for example is good.

ISL3282ExRHZ-T
- [ ] Name should be "ISL3282ExRHZ"
- [ ] Description can be enhanced: `RS485, RS422, 20Mbps Transceiver, 3.0V to 5.5V, TDFN-8` for example
- [ ] Symbol a little bit large and tall, you can easily reduce. Dimensions like ISL3298xxRT symbol for example is good.
- [ ] VL should be Power Input at the top of the symbol
- [ ] NC pin should be on the border outline of the symbol
- [ ] Where have you found pin 9 is GND ? If it is GND, it should be stacked with pin 2. If it is not GND, it should be called EP and type Passive

ISL3283ExHZ-T
- [ ] Name should be "ISL3283ExHZ"
- [ ] Description can be enhanced: `RS485, RS422, 20Mbps Transceiver, 3.0V to 5.5V, SOT-23-6` for example
- [ ] Symbol a little bit large and tall, you can easily reduce. Dimensions like ISL3298xxRT symbol for example is good.

ISL3284ExHZ-T
- [ ] Name should be "ISL3284ExHZ"
- [ ] Description can be enhanced: `RS485, RS422, 20Mbps Transceiver, 3.0V to 5.5V, SOT-23-6` for example
- [ ] Symbol a little bit large and tall, you can easily reduce. Dimensions like ISL3298xxRT symbol for example is good.
- [ ] VL should be Power Input at the top of the symbol

Cheers,
Joel

**Comment by hajrudin10** [comment]
I have made the sugested changes. The GND on pin 9 is defined per datasheet.
image

**Comment by myfreescalewebpage** [comment]
Thanks @hajrudin10 great job done.
Two comments:
- For the description, the "Interface - Driver/Receiver/Transceiver" do not give essential information, you can remove this part
- For the size, I was speaking of the global size of the symbol, not specially the drawing inside
Joel

**Comment by hajrudin10** [comment]
Hello,
before I make the changes I allready reduced the height and width of the symbols by 200 mil now it has the same dimensios as the suggested ISL3298xxRT. Should it be reduced more?

**Comment by myfreescalewebpage** [comment]
No reduced by 200mil is very nice !

**Comment by justyn** [comment]
I suggest that on those symbols with an RE pin, this is moved to right side with RO, since these signals connect to the controller, whereas A and B connect to the RS485 bus.
For the same reason I recommend moving VL out from between the A and B pins on ISL3284.

For reference see existing symbol ISL83491 (which is full-duplex, but the top half is a receiver only like these parts).

isl

**Comment by myfreescalewebpage** [comment]
Good proposition !

**Comment by hajrudin10** [comment]
Hello,
I have implemented the changes.

**Comment by myfreescalewebpage** [comment]
Thanks, great job, no more comment, merging.

**Pull request merged**
