### PR TITLE
Adding the 74CBTLV16212 (24bit bus-exchange)

### PR DESCRIPTION
**Pull request by JonathSpirit**
Adding the 74CBTLV16212 (Low-voltage 24-bit FET Bus-exchange switch)

Datasheet : 
https://www.ti.com/lit/ds/symlink/sn74cbtlv16212.pdf

Image : 

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by JonathSpirit** [comment]
ping ?

**Comment by chschlue** [comment]
Sorry for the delay.
Please split by package.

**Comment by JonathSpirit** [comment]
thanks for the review, personally I don't really like multi-unit symbol and for this one i don't think this is necessary.
Do I have to do it anyway ?

**Comment by JonathSpirit** [comment]
image

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
