### PR TITLE
BatteryManagement: BQ27441: fix pin 5 type

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo J <mail@aurabindo.in>

According to the datasheet, Pin 5 is a 1.8v Power output, but not meant to be loaded.
Datasheet: www.ti.com/lit/ds/symlink/bq27441-g1.pdf

bq_27441_fix

Justification:
bq_27441_fix_reason

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
I thnk then you could even move that pin to the right (on top/bottom, we usually have power_input pins).

Could you do that before I mere?

BTW: Thanks for spotting and correcting!

**Comment by aurabindo** [comment]
Sure I'll do that

**Comment by aurabindo** [comment]
bq_27441_fix

**Comment by aurabindo** [comment]
@jkriege2  I hope its ready to be merged !

**Comment by jkriege2** [comment]
Great!

Thanks,
JAN

**Pull request merged**
