### PR TITLE
Add coupled inductors with 1-3-4-2 pinout

### PR DESCRIPTION
**Pull request by evanshultz**
I added Lodestone VTM footprints, like this one:
image

The pinout is great for a single winding because it allows an inductor winding going from pins 1 to 2 to work if the inductor is inserted into the board in either possible orientation.

But this inductor base is also commonly used for common mode chokes, and in that case the coupled inductor symbols didn't match the required pinout. So I've created them:
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Added 1423 and 1243 symbols based on https://github.com/KiCad/kicad-symbols/issues/2455. It's a bit of a shot in the dark since pin numbers and pin functions (namely, which ones are dotted) may not match between different documents, but it at least should give us better coverage with generic symbols matching manufacturer-specific footprints built to the datasheet pinout.

**Comment by cpresser** [comment]
I will give this a closer look soon.

**Comment by cpresser** [comment]
This looks good for me.
Graphics are nice. Footprint-Filters are okay.

Can you rebase/merge to resolve the conflicts?

**Comment by myfreescalewebpage** [comment]
VERY IMPORTANT @evanshultz  and @cpresser the merge lead to an pop up error following this merge. A device is in the dcm but not in the lib file. See screenshot below.

Capture

Joel

**Comment by cpresser** [comment]
Propsed Bugfix is here: https://github.com/KiCad/kicad-symbols/pull/2569

**Comment by evanshultz** [comment]
I got interrupted just after I pushed a commit where I instead meant to do more checking. Thanks all.

**Comment by cpresser** [comment]
> I got interrupted just after I pushed a commit where I instead meant to do more checking. Thanks all.

Actually, I should have checked this more carefully. I just scrolled through the final diff and looked for weird stuff. But not for missing stuff, neither did I check if the branch works on my machine.
This PR should be counted as "Lessons learned" :school:

**Pull request merged**
