### PR TITLE
LT8610 and LT8610AC/LT8610AC-1

### PR DESCRIPTION
**Pull request by daab4848**
**Pull Request for branch_daab** 
-----------------------------------------------------------------
**Branch Name**: branch_daab                                            
**Branch Author**: David Abillar                                           
**Last Modified by**: David Abillar                                   
**Date**: 03-06-2018   
**Current Branch Revision**: 0.01

**Push Details** 
-----------------------------------------------------------------
**Part Name**: LT8610
**Part Manufacturer**: Analog Devices/ Linear Technology
**Datasheet URL**: http://cds.linear.com/docs/en/datasheet/8610fa.pdf
**Current Symbol Library**: Regulator_Switching

**Symbol Screenshot**:
lt8610_symbol

######################################################################  
     
**Part Name**: LT8610AC
**Part Manufacturer**: Analog Devices/ Linear Technology
**Datasheet URL**: http://cds.linear.com/docs/en/datasheet/8610acfa.pdf
**Current Symbol Library**: Regulator_Switching

**Symbol Screenshot**:
lt8610ac_symbol

######################################################################  

**Part Name**: LT8610AC-1
**Part Manufacturer**: Analog Devices/ Linear Technology
**Datasheet URL**: http://cds.linear.com/docs/en/datasheet/8610acfa.pdf
**Current Symbol Library**: Regulator_Switching

**Symbol Screenshot**:
image

**Additional Comments** 
-----------------------------------------------------------------
- Associated footprints can be found in Package_SO library in branch_daab_footprints branch
- Thank you for the thorough review(s)!

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up the integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by daab4848** [comment]
Pull request #415 include the footprints deemed as "missing" from travis script. Once pull request #415 merges, then rerun travis script and it should pass.

**Comment by Ratfink** [comment]
Thanks for the work you've been doing here lately!

I haven't gotten a chance to look at this, I just wanted to point something out.  The "Rev xxx - " part of your commit messages are really just noise to us, as well as everything up to and including the "Push Details" header in the PR message.  We can see who you are, what the branch is called, how many commits there are in the branch, and when they were made elsewhere.  We can't use your revision numbers to refer to the commits within Git, we can only use the commit IDs created by Git itself.  It's not a problem that you wrote that stuff, but unless you really want to keep doing it, you can save yourself the effort in the future. 🙂

**Comment by Ratfink** [comment]
Okay, time for a real review:

### General

* Please remove the file `Regulator_Switching.pro`.
* Please remove the ThermalVias modifier from the footprint filter.  I'd suggest using the non-ThermalVias footprint as the default as well.
* Most of the parts in this library have the component name at the top right of the symbol.  It would be good to move the component name of these symbols to match.
* GND and PGND pins should be electrical type Power Input, not Power Output as they are now.

Again, I'm really not confident with pin electrical types, so there may be more changes that should be made and I didn't see.  @evanshultz would you mind taking a look?

### LT8610AC

* It's not clear what the description text "with Lower Feedback Voltage, Lower Minimum Vin" is comparing the part to.  I'd suggest removing that part of the description, making it "42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, MSOP-16".  Change the keywords accordingly, too.
  * If you'd like, you could add the actual values for feedback voltage and minimum V<sub>IN</sub> as comma-separated fields just before the package name.  For example: "42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, feedback voltage 0.8V, minimum Vin 3.0V, MSOP-16".  If you decide to go that route, please add the same information to the other parts in this PR.

### LT8610AC-1

* Should be an alias of LT8610AC.
* See the description notes for LT8610AC.  Some of the extra information for this part is clear and helpful, but the portion after the datasheet's brief description should be comma-separated.  I'd suggest "42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, Internal Compensation for High Switching Frequencies, Soft-Start at Dropout and Brownout, MSOP-16".

**Comment by evanshultz** [comment]
Sure! I just looked at pins types.
- Yep, Power Output is correct for ground pins. That type is also for voltage supply pins.
- RT and INTVCC should be Passive, since only a resistor or capacitor go to those pins.
- BIAS could be Power Output too since it's connected to low-Z source, but Input is fine. So leave it. I've seen similar pins both ways in our library and since it's not a logic signal is doesn't matter much.
- Pin 17 can be named PGND and stacked since the datasheet says it "must" be connected this way.

**Comment by daab4848** [comment]
> Please remove the file Regulator_Switching.pro.

- Removed.


> Please remove the ThermalVias modifier from the footprint filter. I'd suggest using the non-ThermalVias footprint as the default as well.

- Removed ThermalVias modifier from LT8610, LT8610AC, and LT8610AC-1.
- Updated footprint to non-ThermalVias versions for LT8610, LT8610AC, and LT8610AC-1. 


> Most of the parts in this library have the component name at the top right of the symbol. It would be good to move the component name of these symbols to match.

- Fixed for LT8610, LT8610AC, LT8610AC-1. Component names now reside on top-right corner of the symbol.
- GND pin(s) have been centered on their respective symbols again.


> GND and PGND pins should be electrical type Power Input, not Power Output as they are now.
> Again, I'm really not confident with pin electrical types, so there may be more changes that should be made and I didn't see. @evanshultz would you mind taking a look?

- Changed GND and PGND pins to Power Input for LT8610, LT8610AC, LT8610AC-1 until further notice. 


> LT8610AC
> It's not clear what the description text "with Lower Feedback Voltage, Lower Minimum Vin" is comparing the part to. I'd suggest removing that part of the description, making it "42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, MSOP-16". Change the keywords accordingly, too.
> If you'd like, you could add the actual values for feedback voltage and minimum VIN as comma-separated fields just before the package name. For example: "42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, feedback voltage 0.8V, minimum Vin 3.0V, MSOP-16". If you decide to go that route, please add the same information to the other parts in this PR.

- Updated description to: 
  **42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, Same Feature Set as LT8610AB Plus: 0.8V Feedback Voltage, 3.0V Minimum Vin, MSOP-16**

- Added "0.8V" and "3.0V" to keyword list
  
> LT8610AC-1
> Should be an alias of LT8610AC.
> See the description notes for LT8610AC. Some of the extra information for this part is clear and helpful, but the portion after the datasheet's brief description should be comma-separated. I'd suggest "42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, Internal Compensation for High Switching Frequencies, Soft-Start at Dropout and Brownout, MSOP-16".

- Updated description to: 
  **42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, Same Feature Set as LT8610AC Plus: Internal Compensation for High Switching Frequencies, Soft-Start at Dropout and Brownout, MSOP-16**
  
- Added "0.8V" and "3.0V" to keyword list (since the lower feedback voltage of 0.8V and minimum vin of 3.0V applies to both LT8610AC and LT8610AC-1)

- I'm having problems with making LT8610AC-1 an alias of LT8610AC. It says that it can't add it as an alias because the LT8610AC-1 already exists (see image below)
image


#Additional comments/questions
* If the descriptions above for the LT8610AC and LT8610AC-1 are satisfactory, then may I suggest a semicolon (";") between the "3.0 Minimum Vin" and the "MSOP-16" to clarify to user that it is NOT part of the feature set listing
* Since the LT8610xx use and MSOP-16 package with an exposed die pad, should this also be included in the description? It gives more accurate information.
* The "Same Feature Set as LT8610AC Plus.." wording for the LT8610AC-1 description was not a mistake. The LT8610AC-1 does indeed include the 0.8V Feedback Voltage and 3.0V Minimum Voltage features that the LT8610AC has, 
  but I deemed it as cumbersome to include (i.e. fully writing it out) in the description and I'm afraid it might make the description too long and hard to read. So wording it as "Same Feature Set as LT8610AC Plus..." is 
  intending the user to look to the LT8610AC description for a list of features included.

**Comment by daab4848** [comment]
@evanshultz I just saw your comment after refreshing. Let me make the changes with another commit.

**Comment by Ratfink** [comment]
@daab4848 Looking good, thanks for the improvements!

I think you'll have to remove the LT8610AC-1 from the library before you can add it as an alias for the LT1610AC.  The deal with aliases is they're different names for the same symbol, with the possibility of setting different information in the Description tab of the Properties dialog.  Everything else is the same for those two parts, so turning one into an alias of the other would make it easier to maintain the library.

KLC rule [S6.3](http://kicad-pcb.org/libraries/klc/S6.3/) says that the description should be comma-separated as they are now, not semicolon-separated.  No need to change that.

The footprint name in the description is intentionally simplified (my understanding is that it's primarily there to distinguish when parts are available in several packages, and we ask to always have it for consistency), and shouldn't mention EPs unless it's important to (e.g. if one package has an EP and another doesn't, and they would otherwise have the same short name).  The footprint name and filters have the detailed information anyway.

I think it would be better to make each part's description standalone, not comparing it to other parts.  If you feel that it's getting too long, it would be better to just remove some information and let users check the datasheet for more details.  You might also simplify things to remove a few words, e.g. instead of "Soft-Start at Dropout and Brownout", you might just put "Soft-Start" (not that I'm telling you to change that specifically, just offering suggestions).

I don't think the voltages in the keyword list are necessary if the same voltages are already listed in the description.  They're more helpful in the description too, since they're given names there.

**Comment by evanshultz** [comment]
The EP size should be listed in the FPfilter but it's not needed in the description.

Remove `ThermalVias*` from the end of the FPfilter. It will be the default footprint be the FPfilter is for all compatible footprints even if they're not the default one.

Definitely, definitely shorten the description. It's like a "greatest hits" list for the part.

**Comment by daab4848** [comment]
**Following issues have been fixed with latest commit.**

> Yep, Power Output is correct for ground pins. That type is also for voltage supply pins.

- Fixed. GND pins' electrical type has been set to Power Output.

> RT and INTVCC should be Passive, since only a resistor or capacitor go to those pins.

- Fixed.

> BIAS could be Power Output too since it's connected to low-Z source, but Input is fine. So leave it. I've seen similar pins both ways in our library and since it's not a logic signal is doesn't matter much.

- Noted.

> Pin 17 can be named PGND and stacked since the datasheet says it "must" be connected this way.

- Renamed pins 7, 8 from "PGND" to "GND" and stacked on pin 17. Since the other parts of the LT8610xx family (i.e. LT8610AB, LT8610AC,...)
  only have GND pins, I deemed the PGND pins on the LT8610 has the black sheep, so to speak. 
  Consequently, this maintains consistency of the pin locations so that the user may swap in different
  LT8610xx parts/symbols without disrupting their schematic nets too much.
  
  
> Definitely, definitely shorten the description. It's like a "greatest hits" list for the part.   
 
- Updated LT8610AC description to:
  **42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, 0.8V Feedback Voltage, 3.0V Minimum Vin, MSOP-16**

- I deemed the feedback voltage and minimum voltage as important features to include in the LT8610AC description.
   
- Removed the "0.8V" and "3.0V" from keyword list as they were unnecessary.

**Other important edits**

- Removed LT8610AC-1 symbol from the symbol library and added it as an alias to LT8610AC.

**Comment by Ratfink** [comment]
Aliases have their own separate documentation entries, so please fill out the documentation for LT8610AC-1.  You can copy this information from the symbol it's an alias of with the "Copy Document from Parent" button on the Documentation tab of the Properties window, then make any changes that it might need.

Please move the name of the LT8610AC to the right a bit.  Currently it looks fine for the LT8610AC, but if you view the LT8610AC-1 in the symbol browser, you'll see the name overlaps the VIN pin because the alias' name is longer.

Once you fix those two little problems, I think this will be ready to merge.

**Comment by daab4848** [comment]
> Aliases have their own separate documentation entries, so please fill out the documentation for LT8610AC-1. 
> You can copy this information from the symbol it's an alias of with the "Copy Document from Parent" button on the Documentation tab of the Properties window, then make any changes that it might need.

- LT8610AC-1 Alias documentation entries have been added.
- Description reads:
  **42V, 3.5A Synchronous Step-Down Regulator with 2.5uA Quiescent Current, Internal Compensation at Higher Currents, Soft-Start at Dropout and Brownout, MSOP-16**
- Keyword list same as LT8610AC in addition to "internal", "compensation", and soft-start" 
- Datasheet URL unchanged. Same as LT8610AC.

> Please move the name of the LT8610AC to the right a bit. 
> Currently it looks fine for the LT8610AC, but if you view the LT8610AC-1 in the symbol browser, you'll see the name overlaps the VIN pin because the alias' name is longer.

- Fixed this issue by setting the "Horizontal Justify" to "Align Left". In this way, the "-1" part grows out toward the right side of the symbol.

**Comment by daab4848** [comment]
@Ratfink Just a small reminder, the Travis scripts are still complaining since the associated footprints have not been merged yet (KiCad/kicad-footprints#415). I don't know if this will hinder the merge process.

**Comment by Ratfink** [comment]
Thanks for all the good work!  Since the footprints are being worked on already, I think it's safe to merge this now.

**Comment by daab4848** [comment]
Thank you!

**Pull request merged**
