### PR TITLE
Added INA260

### PR DESCRIPTION
**Pull request by Misca1234**
Re push of 
https://github.com/KiCad/kicad-symbols/pull/470

INA260
http://www.ti.com/lit/ds/symlink/ina260.pdf

It is in the Sensor.lib
GND is not stacked, see page 29

bild

bild

bild

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- IN- should not be Output type. Passive would be OK with me. Perhaps IN+ and VBUS should be too since they all go to a mux.
- I'd be inclined to put the I2C pins and ALERT on the right side since they all interface to a processor and it also keeps the D pins on the "output" side.
- Similarly, I think it would be best if IN- is on the left side below IN+ and VBUS.
- Why can't pins 6 and 11 be stacked? Page 29 only shows separate vias, but that could be getting to a plane quickly for lower inductance. Page 4 indicates those two pins are exactly the same.
- Pin 7 defaults to active low but can be active high. So remove the overbar?

Travis is complaining because the visible pin in the stack is of a different type.

**Comment by Misca1234** [comment]
Some thing like this then

bild

**Comment by evanshultz** [comment]
That looks good to me. Can you shrink the symbol a bit in height and then I'll mege?

**Comment by Misca1234** [comment]
Here we go

bild

**Comment by evanshultz** [comment]
Great. What about moving VBUS back up next to IN+? It seems like they're intended to be connected to the same net.

**Comment by Misca1234** [comment]
Yes, but it looked more symmetric in that way, but it is moved now

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
