### PR TITLE
Mini-Circuits AMK-2-13 2x frequency multiplier

### PR DESCRIPTION
**Pull request by aewallin**
2x frequency multiplier
https://ww2.minicircuits.com/pdfs/AMK-2-13+.pdf

amk-2-13

Footprint: https://github.com/KiCad/kicad-footprints/pull/1127
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening again to update the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Why using bold text ? It's too large, prefer 50mil text (KLC S3.2 http://kicad-pcb.org/libraries/klc/S3.2/)
- [ ] The footprint is not correct, you should update it (and footprint filter will need modification: `Mini?Circuits*PL?052*`)
- [ ] You can center GND pins, but maybe you want consistency with other MiniCircuit symbols ?
- [ ] You should add NC pin 2 (Type Not Connected, not visible) because the pin count is not specified in the footprint (KLC S4.5 http://kicad-pcb.org/libraries/klc/S4.5/)

Cheers,
Joel

**Comment by aewallin** [comment]
NC hidden pin is not on 100mil grid, because the box is not on 100mil grid...
after revision:
amk-2-13

**Comment by myfreescalewebpage** [comment]
@aewallin can you proceed with the conflict branch on this symbol following the merge of the first one ? We will probably need to do like that for each of your RF symbols...

Thanks,
Joel

**Comment by aewallin** [comment]
> @aewallin you are currently violating S4.1 with the NC pin.

would you advise to change the symbol box-size so that the boundary is on a 100mil grid? or could the hidden NC pins be inside the symbol-box? S4.6.1?

**Comment by myfreescalewebpage** [comment]
@aewallin same response, I prefer violating S4.1. Maybe you can move the NC pin 50mil up so only one coordinate violate the rule ?

Joel

**Comment by myfreescalewebpage** [comment]
@aewallin fp filter to be fixed with CD542 instead of PL for this one

Joel

**Comment by aewallin** [comment]
remaining KLC-error is an off-grid NC hidden pin (placed on box boundary)

**Comment by myfreescalewebpage** [comment]
No more comment, merging.

Joel

**Pull request merged**
