### PR TITLE
Transferred xicor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
All into `Potentiometer_Digital.lib`

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

looks good the only thing I stumble upon is X9258 which is present twice: Once as a single-symbol and once with units (one for control&power and four for the pots). Do we want to keep both? I would vote to remove X9258-PART ... as it would be the only digitla pot that is split i this way ...

If you want to keep it, let me know and I will merge.

**Comment by SchrodingersGat** [comment]
Fixed, thanks

**Comment by jkriege2** [comment]
Hi @SchrodingersGat  could you fix the conflict, so I can merge?

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Fixed conflicts

**Pull request merged**
