### PR TITLE
Adding M.2 connectors (A, B, E, M Mechanical Keys)

### PR DESCRIPTION
**Pull request by ki5libs**
Adding M.2 connectors (A, B, E, M Mechanical Keys)
[Datasheet (Socket A)](http://read.pudn.com/downloads794/doc/project/3133918/PCIe_M.2_Electromechanical_Spec_Rev1.0_Final_11012013_RS_Clean.pdf#page=148)
A
[Datasheet (Socket B)](http://read.pudn.com/downloads794/doc/project/3133918/PCIe_M.2_Electromechanical_Spec_Rev1.0_Final_11012013_RS_Clean.pdf#page=154)
B
[Datasheet (Socket E)](http://read.pudn.com/downloads794/doc/project/3133918/PCIe_M.2_Electromechanical_Spec_Rev1.0_Final_11012013_RS_Clean.pdf#page=150)
E
[Datasheet (Socket M)](http://read.pudn.com/downloads794/doc/project/3133918/PCIe_M.2_Electromechanical_Spec_Rev1.0_Final_11012013_RS_Clean.pdf#page=155)
M

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
For reference: https://github.com/KiCad/kicad-symbols/pull/869

**Comment by myfreescalewebpage** [comment]
Hello @ki5libs 
We should work on this for integration in KiCad v6 :)
Can you at the moment group the pins by functions, and stack GND pins together. See for example "Bus_PCI_Express_Mini" in the library on which I have worked in the past.
Then will review your symbols.
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

I've stacked GND and 3.3V pins and make some regrouping. I tried to save pins compatibility between different variants as much as it's possible.

**Comment by myfreescalewebpage** [comment]
@ki5libs I continue the review.

For all symbols:
- [ ] Footprint should be `~` to avoid the travis warning
- [ ] I wonder about the fp filter, maybe `*M*2*A*` for A socket, etc is good. What do you think ? I still try to copy from "Bus_PCI_Express_Mini" I have done
- [ ] For consistency, the names of the symbols should be "Bus_M.2_Socket_X"

Key A:
- [ ] DP AUX and DP ML are Bidirectional
- [ ] LEDx are Open Collector if my understanding is correct

Key B:
No comment

Key E:
- [ ] Name of pin 20 should be `~UART_WAKE` to have the overbar on all the name. Same comment for pins 21 and 23.
- [ ] LEDx are Open Collector if my understanding is correct

Key M:
No comment

Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

I did all according to your notes except of `~` in the footprint field cause it leads to Travis error. I suppose that warning is better :) 

And one more thing about the `MP` pin. Is it something new? I'm not sure that saw it before in the KLC and a little bit confused founding it now. On my opinion symbol should describe the electrical part not mechanical, shouldn't it?

**Comment by myfreescalewebpage** [comment]
> I did all according to your notes except of ~ in the footprint field cause it leads to Travis error. I suppose that warning is better :)

Yes sorry this is for datasheet when it is empty

> And one more thing about the MP pin. Is it something new? I'm not sure that saw it before in the KLC and a little bit confused founding it now. On my opinion symbol should describe the electrical part not mechanical, shouldn't it?

I agree with you, no rule is clearly define. What do you prefer ? I let you the final decision.

**Comment by ki5libs** [comment]
> I agree with you, no rule is clearly define. What do you prefer ? I let you the final decision.

Thanks. Seems to be better without it.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
