### PR TITLE
Add SKY13575-639LF.

### PR DESCRIPTION
**Pull request by matthuszagh**
http://www.skyworksinc.com/uploads/documents/SKY13575_639LF_203270D.pdf

image

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1443

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A comment I have during my review:

- [ ] Footprint filter will be `QFN*1EP*1.6x1.6mm*P0.4mm*`

Else no comment, looks good ! Just need to wait this modification and the integration of the footprint.

Cheers,
Joel

**Comment by matthuszagh** [comment]
hi @myfreescalewebpage i've made the change since the footprint has now been merged. it seems like this made changes to diode too, but i'm confused bc I don't see that in my local git repo....

Also it looks like I need to delete the datasheet?

**Comment by evanshultz** [comment]
@matthuszagh 
Yes, the datasheet should only be in the DCM file and not the LIB file.

@antoniovazquezblanco 
Did you mean to add BAV199DW as a discrete symbol to this PR? Right now BAV199DW is an ALIAS of BAV99S so something seems wrong to me.

**Comment by myfreescalewebpage** [comment]
@matthuszagh yes please, as confirmed by @evanshultz too. Take care, it should be empty in DCM file, not in the LIB file.

@antoniovazquezblanco I don't understand your commits too. Please check.

**Comment by antoniovazquezblanco** [comment]
I did not push anything here. Those commits have been merged in https://github.com/KiCad/kicad-symbols/pull/1575.

It seems that there has been some trouble with this pull request branch but I do not know what has happened.

**Comment by matthuszagh** [comment]
What's the best way to go forward here? Make the changes above and then rebase on the current master?

**Comment by myfreescalewebpage** [comment]
Close and open to refresh Travis result (button not available in Travis, don't know why...)

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh and sorry for the delay.
One error remaining in Travis : Datasheet field should be empty in the lib file.
I don't know if it is possible to fix it in the last version of KiCad.... Else can you do it with a test editor please ? This is "F3" field. You can look at the other devices too.
Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage I've removed the datasheet field. Let me know if this is correct.

**Comment by myfreescalewebpage** [comment]
@matthuszagh you have a modification of BAV199DW (see https://github.com/KiCad/kicad-symbols/pull/1585/files) which is not expected. To be fixed before we can merge.

**Comment by matthuszagh** [comment]
Alright, I've rebased onto master. Sorry for the force push... I'm not really sure how those commits are making it in there. Anyway, hopefully this fixes the issue. Let me know.

**Comment by myfreescalewebpage** [comment]
Thanks, no worries for the force push.
Something is strange, the device is twice in the dcm file. See https://github.com/KiCad/kicad-symbols/pull/1585/files. To be fixed manually I think.

**Comment by matthuszagh** [comment]
How's this?

**Comment by myfreescalewebpage** [comment]
Ok, better to open it.
Can you update the datasheet link ? Seems now "https://www.skyworksinc.com/-/media/SkyWorks/Documents/Products/2201-2300/SKY13575_639LF_203270D.pdf".
No other comment.

**Comment by matthuszagh** [comment]
Updated.

**Comment by myfreescalewebpage** [comment]
Perfect, thanks for the quick fix! Merging.

**Comment by poeschlr** [comment]
Why does this symbol point to the normal qfn package instead of the special manufacturer specific version in the RF.pretty lib? RF.pretty/Skyworks_SKY13575_639LF

**Comment by matthuszagh** [comment]
@poeschlr hm no idea why I didn't use my own footprint I made for this... Anyway thanks for fixing!

**Pull request merged**
