### PR TITLE
Analog_ADC: Add ICL7106/7

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Analog_ADC: Add ICL7106/7

Datasheet: https://www.renesas.com/eu/en/www/doc/datasheet/icl7106-07-07s.pdf

ICL7106CPL

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @piotr-wiszowaty , thanks for contributing,

A few comments I have during my review:

ICL7106CPL
- [ ] Description should ends with the complete package name: `3 1/2 Digit, LCD Display, A/D Converter, DIP-40`
- [ ] Pin length should be 100mil (number of pins < 100)
- [ ] Pin 21 is missing

ICL7107CPL
- [ ] Description should ends with the complete package name: `3 1/2 Digit, LCD Display, A/D Converter, DIP-40`

Cheers,
Joel

**Comment by piotr-wiszowaty** [comment]
Corrected.

**Comment by myfreescalewebpage** [comment]
@piotr-wiszowaty thanks for the quick fixes. You can decrease the height of the symbol by 100mil. Then ready to go. Joel

**Comment by piotr-wiszowaty** [comment]
Decreased.

**Comment by myfreescalewebpage** [comment]
Thanks for the change, no more comment, merging. Joel

**Pull request merged**
