### PR TITLE
add JTOS-50 VCXO with alias JTOS-25

### PR DESCRIPTION
**Pull request by aewallin**
MiniCircuits JTOS series VCXO: JTOS-50 and JTOS-25 (there may be many more with the same pin-numbering and footprint - to do: add more aliases)

Datasheets:
https://ww2.minicircuits.com/pdfs/JTOS-25+.pdf
https://ww2.minicircuits.com/pdfs/JTOS-50+.pdf

oscillator_smd_minicircuits_jtos-50

no footprint PR yet.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
Footprint now merged.

**Comment by aewallin** [comment]
revised symbol with sine-wave:
oscillator_smd_minicircuits_jtos-50

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Part names are very long for no reason. I would suggest "JTOS-25" and "JTOS-50".
- [ ] You can use capital letters for VCC
- [ ] I would like also to suggest centering VCC/GND but it is not mandatory. Let me known. Example below.

capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks. No comments to do, merging.

Joel

**Pull request merged**
