### PR TITLE
MCP23017 and MCP23S17 added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
MCP23017 and MCP12S17 added.

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf

image

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [-] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
There are more changes in the .lib file than just adding the new symbols, how come ?

**Comment by serkanxselcuk** [comment]
> There are more changes in the .lib file than just adding the new symbols, how come ?

I don't know why, footprint editor just reordered some code lines. Actually there are no changes on other parts in library. Codes or designs from other parts are not changed, only reordered by footprint editor automatically.

**Comment by Misca1234** [comment]
The MCP23017 is I2C
The MCPMCP23S17 is SPI

This is not reflected in the meta data meta data for all of the pushed components are the same for all of them)
Change the meta data to reflect SPI/I2C, the specific form factor and remove micochip
for example, for MCP23017_SO
From
16-bit I/O expander, I2C, interrupts, w pull-ups, **(SOIC, SPDIP, SSOP packages)**
**microchip** i2c parallel port expander
http://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf
Into 
16-bit I/O expander, I2C, interrupts, w pull-ups, **SOIC**
**I2C** parallel port expander
http://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf

And for MCP23S17_SO
From
16-bit I/O expander, I2C, interrupts, w pull-ups, **(SOIC, SPDIP, SSOP packages)**
### microchip i2c parallel port expander
http://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf
Into 
16-bit I/O expander, SPI, interrupts, w pull-ups, **SOIC**
**SPI** parallel port expander
http://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf


For the MCP23017 the NC pin is missing, add it like this
bild

That is, make it invisible, NC type and place it on the border


Is there are reason why you did not ad the QFN package as well ?


PS
FYI
you dont need to add the ending ~ in the pin description, for example for " ~CS~" , it would have worked with " ~CS" as well.

**Comment by serkanxselcuk** [comment]
@Misca1234  thank you for helpful tips.

* All descriptions are corrected like:
"16-bit I/O expander, SPI, interrupts, w pull-ups, QFN-28" for MCP23S17_ML.
* All keywords are corrected like:
"SPI parallel port expander" for MCP23S17_xx and "I2C parallel port expander" for MCP23017_xx
* NC pins are added invisible on border of body.

On QFN-28 packages, EP can be connected to VSS or leave unconnected (Datasheet page 11). I made it like NC pins (Invisible, placed on border). Should I make it visible, so that user can decide if they want to connect to VSS or not, or is it OK now?

There was no special reasons to ignore QFN packages, just I did't get time to add them. Now I add them too.

_I am used to put inverting character both sides like `~CS~`, just because I don't want to forget stop over line on devices, which have more functions at a same pin like `RB0/~CS~/INT0/AN0`. Thanks for your tip again :)_

**Comment by Misca1234** [comment]
Nice of you top add the QFN as well, then we have a complete representation of the data sheet.

>  Should I make it visible, so that user can decide if they want to connect to VSS or not, or is it OK now?

Please make it visible and place it next to he VSS pin, then we are ready to merge

**Comment by serkanxselcuk** [comment]
Other changes are just reordered pin lines because old lines were assigned alphabetical
`1 10 11 ... 19 2 20 ...`
and footprint editor reorders automatically numeric
`1 2 ... 9 10 11 ... 19 20 21...` .

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
