### PR TITLE
Add LTC6752 family of comparators

### PR DESCRIPTION
**Pull request by kacper-ka**
This merge adds **LTC6752** family of comparators as separate symbols:
* **LTC6752xS5**,
* **LTC6752xSC6-1**,
* **LTC6752xMS8-2**,
* **LTC6752xUD-3**,
* **LTC6752xSC6-4**.

Previously present ***LTC6752xS5*** symbol (as an *alias* of **MCP6561-OT** is removed, as devices use different packages (see discussion below).

#### Datasheet
https://www.analog.com/media/en/technical-documentation/data-sheets/6752fc.pdf

##### **LTC6752xS5**
LTC6752xS5

##### **LTC6752xSC6-1**
LTC6752xSC6-1

#### **LTC6752xMS8-2**
LTC6752xMS8-2

##### **LTC6752xUD-3**
LTC6752xUD-3

##### **LTC6752xSC6-4**
LTC6752xSC6-4

#### All symbols: S3.2
Pin names text size reduced to fit inside the symbol.

#### All symbols: S3.6
Pin offset reduced to 5 mils:
- prevent pin names overlapping,
- consistent with other comparator symbols.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- ~~If there are matching footprint PRs, provide link(s) as appropriate~~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
@kacper-ka sry, you will have to resolve conflicts again. I just snuck in that SC6 rename (#2718) before 5.1.6 libs are frozen today (after which we couldn't rename it again until v6).

**Comment by kacper-ka** [comment]
@chschlue - done, `master` merged into the branch, all conflicts resolved.

**Comment by kacper-ka** [comment]
Yet I still have doubts about ***LTC6752xS5** and ***LTC6752xUD***:
* ***LTC6752xS5*** is an *alias* of **MCP6561-OT** but there are a few differences:
  - power supply pins' names differ - **MCP6561-OT** uses `V+` and `V-` while ***LTC6752xS5*** datasheet uses `VCC` and `VEE` respectively,
  - packages differ - **MCP6561-OT** uses `SOT-23-5` while ***LTC6752xS5*** datasheet specifies `TSOT-23-5`. The packages differ only in height - nonetheless there are two separate footprints in the library.
* ***LTC6752xUD*** is an *alias* of **LTC6754xUD** but they use different naming of power supply pins:
  | Number | Description | **LTC6752xUD** name | **LTC6754xUD** name |
  | --- | --- | --- | --- |
  | 1 | Positive Supply Voltage for the (LVDS) Output Stage | `VDD` | `VCCO` |
  | 2 | Positive  Supply  Voltage  for  the  Input  Stage | `VCC` | `VCCI` |
  | 3, 9, 13 | Negative power supply, normally tied to ground | `VEE` | `VEE` |

**Comment by evanshultz** [comment]
For simple triangle symbols like opamps and comparators we have commonalized positive and negative power supply pin names to `V+` and `V-` to keep the symbol consistent.

**Comment by kacper-ka** [comment]
Yet **LTC6754xUD** symbol uses `VCCI`, `VCCO` and `VEE` names. And as I can see it is not the only symbol that does not follow the convention.

**Comment by chschlue** [comment]
Yes, we have the occasional stray symbol.
Besides, is there any kind of convention for separate supply triangles @evanshultz?

**Comment by chschlue** [comment]
>   * packages differ - **MCP6561-OT** uses `SOT-23-5` while _**LTC6752xS5**_ datasheet specifies `TSOT-23-5`. The packages differ only in height - nonetheless there are two separate footprints in the library.

MCP6561 datasheet gives 1.45mm max height (matching MO-178) vs LTC6752 1mm max (falling below MO-193), so SOT-23-5 and TSOT-23-5, respectively, is correct (FPs are indeed identical but 3D models differ).

**Comment by kacper-ka** [comment]
Yes, that's right - my point was: shouldn't **LTC6752xS5** be a separate symbol, not an *alias* (due to the package difference)?

The same question applies to **LTC6752xUD** - due to the pin naming differences.

**Comment by chschlue** [comment]
> Yes, that's right - my point was: shouldn't **LTC6752xS5** be a separate symbol, not an _alias_ (due to the package difference)?

Yes.
 
> The same question applies to **LTC6752xUD** - due to the pin naming differences.

Leaning towards yes, for consistency within the 6752 family. Up to you.

**Comment by kacper-ka** [comment]
Ok, I'm going for it, I'll update the symbols.

**Pull request merged**
