### PR TITLE
Added BL0937 - Energy Meter IC

### PR DESCRIPTION
**Pull request by G-Pereira**
[Datasheet](http://www.belling.com.cn/media/file_object/bel_product/BL0937/datasheet/BL0937_V1.02_en.pdf)
image

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @G-Pereira , thanks for contributing,

A few comments I have during my review:

- [ ] Description shoudl ends with package name: `Single Phase Energy Meter IC with Integrated Oscillator, SOP-8`
- [ ] Fp filter: `SOP*3.9x4.9mm*P1.27mm*`
- [ ] IP above IN is better

Cheers,
Joel

**Comment by G-Pereira** [comment]
I have fixed all the point you've listed but the footprint filter has caught my attention. Shouldn't it be: `SOP?8*3.9x4.9mm*P1.27mm*` ?

**Comment by aris-kimi** [comment]
Hi @G-Pereira , well... no. :-) i fall on this allmost every time. Filter must NOT contain pin numbers.
Also, if EP exists in a footprint(and in its name), then the fp filter, keeps the referral `1EP` (for example) following pin number(which is ommited) BUT,
EP's dimmension are ommited (from the end of the fp name).

Example:
This fp: `SOIC-8_3.9x4.9mm_P1.27mm` has this filter: `SOIC*3.9x4.9mm*P1.27mm*`
also fp: `DFN-8-1EP_3x3mm_P0.65mm_EP1.55x2.4mm` has this filter: `DFN*1EP*3x3mm*P0.65mm*`

**Comment by G-Pereira** [comment]
Ok, thank you! All set then

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
