### PR TITLE
Add ublox max series

### PR DESCRIPTION
**Pull request by jneiva08**
ublox MAX 8C, 8Q, M8C, M8Q

Datasheet: https://www.u-blox.com/sites/default/files/MAX-8-M8-FW3_HardwareIntegrationManual_%28UBX-15030059%29.pdf
max_8

ublox MAX M8W

Datasheet: https://www.u-blox.com/sites/default/files/MAX-8-M8-FW3_HardwareIntegrationManual_(UBX-15030059).pdf
max_8w

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08, thanks for contributing,

A few comments I have during my review:

- [ ] Indicate the datasheet in datasheet field, not the hardware reference manual (https://www.u-blox.com/sites/default/files/MAX-8_DataSheet_%28UBX-16000093%29.pdf and https://www.u-blox.com/sites/default/files/MAX-M8-FW3_DataSheet_%28UBX-15031506%29.pdf respectively).
- [ ] Fix part names without manufacturer inside, i.e. "MAX-8C" instead of "ublox_MAX-8C", etc. I know other parts include manufacturer in the name but they should not.
- [ ] SCL is indicated Bidirectional at the beginning of the datasheet, but §1.16.2 indicates DDC interface is slave only, so SCL is an Input only. I would suggest to modify the type to Input.
- [ ] According to the datasheet VCC_RF is a Power Output, not an Output.
- [ ] According to the datasheet RF_IN is an Input, not a Passive pin.
- [ ] According to the datasheet V_ANT is a Power Input, not an Input. KLC S4.2 indicates it should be placed on the top of the symbol. I will suggest to move V_ANT on the top and to switch RF_IN and VCC_RF so it is possible to wire VCC_RF to V_ANT easily (hardware reference manual https://www.u-blox.com/sites/default/files/MAX-8-M8-FW3_HardwareIntegrationManual_%28UBX-15030059%29.pdf page 16).
- [ ] KLC S4.2 also recommend to put Inputs on the left so I will suggest to move EXTINT / SAFEBOOT_N and RESET_N on the left of the symbol.

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage hope i didn't forgot anything

max-m8w:
max_m8w

others:
max_all

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks, this is really great !

An additional comment I have not seen previously, before we can merge:
- [ ] Can you switch RF_IN and LNA_EN pins, so it's easier to wire the LNA_EN when it is used (ref manual https://www.u-blox.com/sites/default/files/MAX-8-M8-FW3_HardwareIntegrationManual_%28UBX-15030059%29.pdf page 17)

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks, no more comment to do, merging.

Thanks for your contribution!

Cheers,
Joel

**Pull request merged**
