### PR TITLE
Added PIC24FJ256DA210-IBG and PIC24FJ256DA210-IPT

### PR DESCRIPTION
**Pull request by Misca1234**
This is a take over of 
https://github.com/KiCad/kicad-symbols/pull/383

PIC24FJ256DA210-IBG  BGA 121
PIC24FJ256DA210-IPT   TQFP 100
http://ww1.microchip.com/downloads/en/DeviceDoc/39969b.pdf

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Strange, travis warned but not checklib.py
```
$ python checklib.py ../../kicad-symbols/MCU_Microchip_PIC24.lib -vv
Checking symbol 'PIC24FJ256DA210-IBG' - No errors
Checking symbol 'PIC24FJ256DA210-IPT' - No errors
Checking symbol 'PIC24FV32KA304-IPT' - No errors
```

It seems this one need a non existing foot print, I look into it

**Comment by Misca1234** [comment]
Awaits
https://github.com/KiCad/kicad-footprints/pull/1170

**Comment by antoniovazquezblanco** [comment]
Thanks @Misca1234 

Couple of things I've seen in the screenshot:

- [ ] VSS pin stacking.
- [ ] The trend would be to include the most basic functionality of each pin if possible and a second functionality if very important. That way syms get smaller.

Also, it is the first time I see the box around some pins, From experience I assume it is to denote 5V compatibility. I like it but I have never included that in my previous microchip syms.

Thanks!

**Comment by Misca1234** [comment]
Naa, it was a little to quick re-push of an older push, 
should we keep the pin markings?

"•   Operating Voltage Range of 2.2V to 3.6V"
"•   5.5V Tolerant Input (digital pins only)"

I can remove those.

**Comment by antoniovazquezblanco** [comment]
> I can remove those.

They do not bother me. Just was curious about them. I do not have a preference. They are useful. Leave them as that is easier :)

**Comment by antoniovazquezblanco** [comment]
Had a quick look. I think everything is ok.

I have seen that you prepended a asterisk in `PIC24FJ256DA210-IPT` fp filter (`*TQFP*12x12mm*Pitch0.4mm*`).

We should come up with a consensus on wether to use it or not. Will merge with the way you prefer to go.

Thanks!

**Comment by evanshultz** [comment]
1. Let's remove the boxes on the pins.
1. Remove the asterisk as mentioned above.
1. The footprint library names have changed since the original PR and need to be updated.
1. Put a hyphen between the package type and pin count in the description.
1. Update the description as mentioned at https://github.com/KiCad/kicad-symbols/pull/875.

@antoniovazquezblanco Do you mean you checked pin names, pin numbers, and pin types?

**Comment by antoniovazquezblanco** [comment]
> @antoniovazquezblanco Do you mean you checked pin names, pin numbers, and pin types?

I guess I just had a quick look over them but did not check them in depth.

More things I can see:
- [ ] Please wildcard the temperature part of the MPN: `PIC24FJ256DA210-xBG`

**Comment by evanshultz** [comment]
OK. Verified pinout and reviewed more in-depth:
1. Should VCAP be on the side since it's for a capacitor and not power in/out? I don't see any indication in the datasheet that this pin can source current for external circuits.
1. Not just the footprint libs, but the footprint names have changed as well. For example Pitch -> P.
1. The BGA footprint doesn't exist, so you could create another one or assign the TFBGA or XBGA footprints we do have that seem OK.
1. As both package have 3 characters in at least one pin number, the pin length should be 150mil.
1. On the right side, why not put port F just above port G?
1. On the BGA symbol, RF2 and RF3 aren't named properly.
1. The BGA symbol appears to be missing all NC pins.
1. To me, the USB (D+/D-/VBUS) and oscillator pins are important enough to mention.
1. The TQFP symbol has pin 39 named wrong.

**Comment by antoniovazquezblanco** [comment]
Footprints have been merged. Re-triggering travis.

**Comment by antoniovazquezblanco** [comment]
Travis is failing. Opened a bug report at https://github.com/KiCad/kicad-library-utils/issues/294

**Comment by antoniovazquezblanco** [comment]
Closing and reopening to force travis to read the new config file.

**Comment by Misca1234** [comment]
@antoniovazquezblanco 
Shall I fix the centring thing as well ?

**Comment by antoniovazquezblanco** [comment]
> Shall I fix the centring thing as well ?

If you are able to do so, please do :)

Thank you!

**Comment by evanshultz** [comment]
Were the items at https://github.com/KiCad/kicad-symbols/pull/1266#issuecomment-478650202 reviewed?

**Comment by Misca1234** [comment]
I have removed the rctangles at the pins
Updated the foot print filter and specified foot print
Centred the symbol

**Comment by evanshultz** [comment]
Thanks!

Are all items I mentioned above addressed? Can you post new screenshots?

**Comment by antoniovazquezblanco** [comment]
Before that, remember my coment at https://github.com/KiCad/kicad-symbols/pull/1266#issuecomment-478474132

Symbol name should wildcard the temperature part of the MPN.

**Comment by Misca1234** [comment]
Now so

bild

bild

bild

bild

**Comment by antoniovazquezblanco** [comment]
Again, The names should be `PIC24FJ256DA210-xBG` and `PIC24FJ256DA210-xPT`.

**Comment by Misca1234** [comment]
Name changed

**Comment by evanshultz** [comment]
@Misca1234 
Thanks! Very close!
1. In the descriptions, put a hyphen before the pin count.
1. The BGA symbol is missing the NC pins.

**Comment by Misca1234** [comment]
NC pin and hyphen added

bild

bild

**Comment by evanshultz** [comment]
@Misca1234 
Thanks! The NC pins can't be stacked, however. See the CI results.

**Comment by Misca1234** [comment]
They are here now

bild

**Comment by evanshultz** [comment]
Thanks! You're missing the NC pins K5 and J9. Then I think this is ready.

**Comment by Misca1234** [comment]
man ...

**Comment by Misca1234** [comment]
Now so

**Comment by evanshultz** [comment]
Thanks! This was a marathon. Looks good, but hope nothing got missed.

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Comment by Misca1234** [comment]
Jee, thanks for holding out guys

**Pull request merged**
