### PR TITLE
Add BM78 Class 2 Bluetooth/BLE module

### PR DESCRIPTION
**Pull request by Kev-J**
Add BM78

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/60001380C.pdf
Associated footprint PR: https://github.com/KiCad/kicad-footprints/pull/2378

bm78

Regarding the commit, it looks like the symbol editor want to move the NRF module description...

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Kev-J , thanks for contributing,

A few comments I have during my review:

- [ ] I see several variants of this device and they have not all the same pinout. The name of your device should be "BM78SPPS5MC2". I suggest to have "BM78SPPS5NC2" and "" as alias. You can submit "BM78SPP05MC2" if you want but it will be a different symbol. See datasheet pages 5 and 40.
- [ ] Footprint and footprint filter to be completed
- [ ] Pin length should be 100mil (symbol < 100pins)
- [ ] PMULDO_O to be set as Passive I think
- [ ] Name of pin 21 should be `~RST`
- [ ] P1xx pin to be grouped
- [ ] Name of pin 13 should be `SCL/P1_2` to have main function on the border of the symbol
- [ ] Name of pin 14 should be `SDA/P1_3` to have main function on the border of the symbol

Cheers,
Joel

**Comment by Kev-J** [comment]
Hi Joel,

It should be better now. There is still one error in Travis due to the missing footprint (see associated footprint PR : https://github.com/KiCad/kicad-footprints/pull/2378).

Cheers,
Kevin

**Comment by myfreescalewebpage** [comment]
It's really better. Two comments:
- [ ] I think the width of the symbol can be reduced
- [ ] Can you arrange P1 pin in the right order (P1_2 first, etc)

Joel

**Comment by Kev-J** [comment]
Hi Joel,

Sorry about that. It should be fixed now.

Kevin

**Comment by myfreescalewebpage** [comment]
Yes. Need to wait the footprint now.
Thanks.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging the symbol now.

**Pull request merged**
