### PR TITLE
Adedd nRF52820

### PR DESCRIPTION
**Pull request by G-Pereira**
Added nRF52820-QDAA
[Datasheet](https://infocenter.nordicsemi.com/pdf/nRF52820_PS_v1.0.pdf)
nrf52820

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @G-Pereira , i have noticed pin26 and pin38 noted in the datasheet to be connected, so i think those need to be stacked. Also not sure if those DECx pins should be passive or power output.

Great job i think, thank you for this. But better wait for a full review from an experienced librarian.

**Comment by G-Pereira** [comment]
Hi @aris-kimi , thanks for reviewing this! 

> i have noticed pin26 and pin38 noted in the datasheet to be connected, so i think those need to be stacked

I have noticed that too but it appears that the symbol for nRF52840 (similar IC) appears to have those pins separate due to optional independent decoupling. I ended up leaving them separate for this IC as well since the same applies here.

> Also not sure if those DECx pins should be passive or power output.

I also went by this one by comparing it with the nRF52840, nRF52810, nRF52811 and nRF52832. They all use "Passive" for this pins and it made sense to me because they are not meant to be used as power supply pins not even for "pin configuration" (set some pins to high level voltage)

**Comment by myfreescalewebpage** [comment]
Hi @G-Pereira , thanks for contributing,

- [ ] Name of the symbol should be "nRF52820-QDxx"

Else, ready to go.

Cheers,
Joel

**Comment by G-Pereira** [comment]
Fixed!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
