### PR TITLE
Symbol for Quectel Bc66

### PR DESCRIPTION
**Pull request by jneiva08**
Added symbol for Quectel BC66

Datasheet: https://www.quectel.com/UploadImage/Downlad/Quectel_BC66_Hardware_Design_V1.1.pdf
**Note:** to access datasheet may need to be register on Quectel website.

Footprint: https://github.com/KiCad/kicad-footprints/pull/1219

Symbol in the editor:
bc66_editor

Symbol on eeschema:
bc66_eeschema

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] I would cross SPI and SIM blocks so that the SIM_GND pin is not so far away from SIM pins
- [ ] ADC0 should be Input
- [ ] Seems according to figure 21 in the datasheet page 32 that SIM_GND is Power Output, isn't it ?
- [ ] I would move NETLIGHT on the right of the symbol

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage , sorry for taking some time to make the modifications.

Have made the modifications you requested.
The SIM_GND Changed to Power_Output, because in Table 11 say SIM_GND is Specified ground for USIM card.

bc66

**Comment by myfreescalewebpage** [comment]
Thanks @jneiva08 for the fixes, looks great, no more comment to do. Merging.

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
