### PR TITLE
Connector: Add JAE Nano SIM Card SF72S006

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add JAE Nano SIM Card SF72S006

Datasheet: https://www.jae.com/direct/topics/topics_file_download/topics_id=68892&ext_no=06&index=0&_lang=en&v=202003111511468456809

Capture

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate

Pending footprint at https://github.com/KiCad/kicad-footprints/pull/2211

- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
Hey @myfreescalewebpage,
about C6: this used to be power in for programming and is now bidir I/O for SWP, so perhaps passive is a better type to support all applications. What do you think?

**Comment by myfreescalewebpage** [comment]
I wasn't aware of this possibility.
Bidirectional type is okay I think for application were the pin is connected to power supply and for applications were the pin is connected to a controller.
Joel

**Comment by myfreescalewebpage** [comment]
Just applied the same modification at my other PR: https://github.com/KiCad/kicad-symbols/pull/2519

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@chschlue you have made the footprint for this one, comments on the symbol ?
Thanks.
Joel

**Comment by chschlue** [comment]
No, thanks.

**Comment by myfreescalewebpage** [comment]
Thanks to you for the review of this part

**Pull request merged**
