### PR TITLE
Add Wolfspeed diodes

### PR DESCRIPTION
**Pull request by evanshultz**
Add all diodes at https://www.wolfspeed.com/power/products/sic-schottky-diodes/table.

Most symbols are copies of an existing symbol, just with a new package. Only the TO-247-3 is new and its symbol looks like this:
image

There are a number of footprints that are missing and I will add them. I've already submitted https://github.com/KiCad/kicad-footprints/pull/461.

The symbol for `C3D02060F` is unique because it is an isolated TO220, which is encapsulated in epoxy and all black. Since that would mean a unique 3D model, I thought it should be a unique footprint. If so, I propose creating `TO-220F-2_Vertical` for this symbol and I will update this PR. Please confirm.

I also updated a coupld ST URLs with short versions.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
If I can get feedback on the correct footprint names, I'll make any adjustments to this and create a PR for the footprints. Some are shown by the Travis output and one more is mentioned above.

**Comment by jkriege2** [comment]
Hi!

I added a footprint(+3D model) PR for the TO-220F: https://github.com/KiCad/kicad-footprints/pull/470 ... also I fixed the TO-220-footprints, as they had slightly wrong measurements and added TO-220 3D models. Does that help?

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Yes! Thank you! I assume you think this footprint name is OK, then.

**Comment by evanshultz** [comment]
For DPAK and D2PAK diodes I only see that the tab should be pin 1. Can anybody find one that needs the tab to be pin 2? If not, the diode footprints don't need to mention the pin of the tab.

**Comment by evanshultz** [comment]
Missing footprints submitted at https://github.com/KiCad/kicad-footprints/pull/485 and also using updated footprints from https://github.com/KiCad/kicad-footprints/pull/470.

**Comment by jkriege2** [comment]
see my comments there: https://github.com/KiCad/kicad-footprints/pull/485

**Comment by evanshultz** [comment]
Thanks Jan! Footprints updated and linked. Looks like Travis is happy!

**Comment by jkriege2** [comment]
Hi!

looks mostly good to me ... the only problem I found is with the double-diodes: Here the labels overlap the symbol:
2018-04-29 07_55_56-symbol library editor - diode d__kicad_review pretty_kicad-symbols_diode lib

Could you correct that? Then I can merge!

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Thanks! I moved them out of the way. Do you prefer a different location?
image

**Comment by jkriege2** [comment]
nice work!

JAN

**Pull request merged**
