### PR TITLE
MCU_Microchip_PIC16: Add PIC16F19195

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
MCU_Microchip_PIC16: Add PIC16F19195

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/PIC16LF19195-6-7-Data-Sheet-40001873D.pdf
PIC16F19195

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@piotr-wiszowaty hello and thanks for this contribution,

Not a full review but starting a with a simple comments:
- [ ] parts should be atomic, this means one symbol for each footprint, aliases only if the symbol is the same and footprint is the same
- [ ] Footprint to be filled for each of them

Joel

**Comment by myfreescalewebpage** [comment]
@piotr-wiszowaty I let you continue on this PR to have the atomic parts has required above.
Ping me when it's ready for review.
Thanks
Joel

**Comment by piotr-wiszowaty** [comment]
All right. I'm going to do the symbols next week.

**Comment by piotr-wiszowaty** [comment]
Ready.

**Comment by myfreescalewebpage** [comment]
@piotr-wiszowaty one comment not addressed regarding the fp filter of QFN variant. Else ok.

**Comment by myfreescalewebpage** [comment]
Thanks for the quick fixes! Merging now

**Pull request merged**
