### PR TITLE
Added OPA551/OPA552 P package

### PR DESCRIPTION
**Pull request by hornang**
Added OPA551/OPA552 P package

* http://www.ti.com/lit/ds/symlink/opa551.pdf
* http://www.ti.com/lit/ds/symlink/opa552.pdf

Difference between OPA551 and OPA552 is what gain it is optimized for.

This symbol is only for the DIP-8 package. The SOIC variant does not have same pin specification (pin 1 and 5 differs).

image

### CODE REVIEW

**Comment by evanshultz** [comment]
- Please base this on the standard triangle opamp symbol in the library. The pin placements differ now. Also copy from the standard symbol the pin name offset. Pin 8 can stay on the bottom where there is room in the standard symbol.
- Add something to the description to differentiate the PNs.

**Comment by evanshultz** [comment]
@hornang 
Will you be fixing up this PR so it can be merged? There is still some work to do and also the branch conflicts are a problem.

**Comment by hornang** [comment]
@evanshultz Sorry, I don't have time these days so for now the answer is no.

**Comment by poeschlr** [comment]
Are you ok with your contribution being published under the KiCad license? If yes then please sign the license agreement (somebody else can later finish your work)
If not then please close the pull request.

**Comment by hornang** [comment]
@poeschlr I'm okay with the license so I have signed CLA, but I don't know if the checks are reflecting it immediately.

**Comment by hornang** [comment]
I see the changes are committed under my previous jobs e-mail. I will change that.

**Comment by poeschlr** [comment]
Thanks. Lets see if somebody would be interested to take this on.

**Comment by JonathSpirit** [comment]
Hi, i can continue this PR, just tell me how can i proceed and if it's ok.

**Comment by evanshultz** [comment]
@JonathSpirit 
Thanks! I made comments above and adding those points to the existing changes would be a good place to start with getting this ready to merge.

**Comment by JonathSpirit** [comment]
ok ! Where do i commit or propose any change ?

**Comment by evanshultz** [comment]
You will have to take the commits here, modify them, and create a new PR based off the latest MASTER.

**Comment by JonathSpirit** [comment]
I created a new pull-request #1827 for this abandoned PR

**Comment by antoniovazquezblanco** [comment]
Closing this in favor of the new PR

**Pull request closed without merging**
