### PR TITLE
add onion omega2+

### PR DESCRIPTION
**Pull request by balcer**
https://docs.onion.io/omega2-docs/omega2p.html

omega

https://github.com/KiCad/kicad-footprints/pull/1311

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
I will add it tomorow 
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by balcer** [comment]
Ok, I fixed all of your comments except one. I don't know what you mean by "GND pins must be stacked". Please provide an example symbol.

**Comment by poeschlr** [comment]
Stacked means they are placed at the same position with all but one set to invisible. The invisible pins must then have the electrical type passive instead of power input to avoid them being global labels.

**Comment by balcer** [comment]
Ok fixed, Onli one travis error is incomprehensible for me. Where should I change metadata?

**Comment by myfreescalewebpage** [comment]
Hi @balcer 

Ignore this error about metadata, this is normal (for your information, metadata are the description, keywords etc).

You have a stacking error remaining when I look at travis result.

Thanks,
Joel

PS : for the next commits, please do not force push, it is difficult for us to review the whole part, it's better if we can check the commits.

**Comment by balcer** [comment]
ok, I hope that my "commit workflow" is ok, and finaly symbol is also ok.

**Comment by myfreescalewebpage** [comment]
@balcer, great job you have done here ! No comment on the modifications. I'm just wondering about a last question: do you know is RST (pin 16) is active low ? I do not found in the documentation, but read here http://community.onion.io/topic/2972/questions-about-pins-in-omega-2 it was.

If you confirm it is active low, the name of the pin 16 should be `~RST`to get the over-bar.

Need to wait the acceptance of the footprint.

Cheers,
Joel

**Comment by balcer** [comment]
Hi @myfreescalewebpage, I made an experiment and technically RST is active low, so I think that you are right, I will change RST to active low. But it doesn't work on Omega2+ version because it resets only CPU and memory stays in 3bit mode so it can't boot. Doh.

**Comment by myfreescalewebpage** [comment]
@balcer thanks, ok for change of RST input. No more comment for me here, just need to wait the footprint.
Joel

**Comment by myfreescalewebpage** [comment]
Merging following integration of the footprint.

**Pull request merged**
