### PR TITLE
Add MSP432E401Y, TLV2371, TLV2372, TLV62568, LM4128, TPS61041, CDNBS0…

### PR DESCRIPTION
**Pull request by Misaka0x2730**
MSP432E401Y - http://www.ti.com/lit/ds/symlink/msp432e401y.pdf
TLV2371, TLV2372 - http://www.ti.com/lit/ds/symlink/tlv2375.pdf
TLV62568 - http://www.ti.com/lit/ds/symlink/tlv62568.pdf
LM4128 - http://www.ti.com/lit/ds/snvs475e/snvs475e.pdf
TPS61041 - http://www.ti.com/lit/ds/symlink/tps61040.pdf
CDNBS08-SLVU2.8-4 - https://www.bourns.com/pdfs/CDNBS08-SLVU28-4.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Misaka0x2730 , thanks for contributing,

For the future, please make separated PR because I think this will be complicated to accept everything in one shot.

Anyway, some comments I have during my review, device by device.

TLV2371D

- [ ] Datasheet field in the Properties should be removed and put in the Documentation field, where you have a wrong Analog Device link (KLC S6.2)
- [ ] Footprint filter is not correct, should be `SOIC*3.9x4.9mm*P1.27mm*`
- [ ] Have you check if an existing symbol can be used to add an alias on it ?
- [ ] You are violating KLC S3.6 (see travis output) that can be easily corrected)

TLV2371DBV

- [ ] Datasheet field in the Properties should be removed and put in the Documentation field, where you have a wrong Analog Device link (KLC S6.2)
- [ ] Footprint filter is not correct, should be `SOT?23*`
- [ ] Have you check if an existing symbol can be used to add an alias on it ?
- [ ] You are violating KLC S3.6 (see travis output) that can be easily corrected)

TLV2371P

- [ ] Datasheet field in the Properties should be removed and put in the Documentation field, where you have a wrong Analog Device link (KLC S6.2)
- [ ] Footprint filter is not correct, should be `DIP*W7.62mm*`
- [ ] Have you check if an existing symbol can be used to add an alias on it ?
- [ ] You are violating KLC S3.6 (see travis output) that can be easily corrected)

MSP432E401Y

- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/msp432e401y.pdf
- [ ] Footprint filter is not set, should be `LQFP*14x14mm*P0.4mm*`
- [ ] Pin PC0 should be renamed "PC0/TCK/SWCLK"
- [ ] Pin PC1 should be renamed "PC1/TMS/SWDIO"
- [ ] Pin PC2 should be renamed "PC2/TDI"
- [ ] Pin PC3 should be renamed "PC3/TDO/SWO"
- [ ] GND pins should be stacked
- [ ] You are violating KLC S4.1 (see travis output) that can be easily corrected)

CDNBS08-SLVU2.8-4

- [ ] Datasheet field in the Properties should be removed and put in the Documentation field, where you have a wrong ST link (KLC S6.2)
- [ ] Footprint filter is not set, should be `SOIC*3.9x4.9mm*P1.27mm*`
- [ ] You are violating KLC S4.1 (see travis output) that can be easily corrected)

LM4128

- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/lm4128.pdf
- [ ] Move reference in top left corner of the symbol and name in top right corner of the symbol
- [ ] You can enlarge vertically the symbol to not get GND closed to other pins
- [ ] Footprint filter is not set, should be `SOT*23*`
- [ ] You are violating KLC S3.1 (see travis output) that can be easily corrected)
- [x] KLC S4.2 accepted for this symbol
- [x] KLC S4.4 do not care for this symbol


TLV62568DBV

- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/tlv62568.pdf
- [ ] Footprint filter is not correct, should be `SOT*23*`
- [ ] SW is Power Output
- [ ] Your symbol is very large, look at other symbol and reduce to get the same size and fix KLC 3.1 at the same time
- [x] KLC S4.2 accepted for this symbol

TLV62568DDC

- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/tlv62568.pdf
- [ ] Footprint filter is not correct, should be `SOT*23*`
- [ ] SW is Power Output
- [ ] PG is Open Collector
- [ ] Your symbol is very large, look at other symbol and reduce to get the same size and fix KLC 3.1 at the same time
- [ ] You are violating KLC S4.1 (see travis output) that can be easily corrected)
- [x] KLC S4.2 accepted for this symbol

TLV62568DRL

- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/tlv62568.pdf
- [ ] Footprint filter is not correct, should be `SOT*23*`
- [ ] SW is Power Output
- [ ] PG does not exists, it is an NC pin see datasheet page 3
- [ ] Your symbol is very large, look at other symbol and reduce to get the same size and fix KLC 3.1 at the same time
- [ ] You are violating KLC S4.1 (see travis output) that can be easily corrected)
- [x] KLC S4.2 accepted for this symbol

TPS61041DBV

- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Footprint filter is not correct, should be `SOT*23*`
- [ ] SW is Power Output
- [ ] Your symbol is very large, look at other symbol and reduce to get the same size and fix KLC 3.1 at the same time

TPS61041DDC

- [ ] Description package name is not correct
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/tps61040.pdf
- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Footprint filter is not correct, should be `SOT*23*`
- [ ] SW is Power Output
- [ ] Your symbol is very large, look at other symbol and reduce to get the same size and fix KLC 3.1 at the same time
- [x] KLC S4.2 accepted for this symbol

TPS61041DRV

- [ ] Description package name is not correct
- [ ] Seems the datasheet link in the Documentation field is not the right one, I propose http://www.ti.com/lit/ds/symlink/tps61040.pdf
- [ ] Datasheet field in the Properties should be removed (KLC S6.2)
- [ ] Footprint filter is not correct, should be `DFN*1EP*2x2mm*P0.65mm*`
- [ ] SW is Power Output
- [ ] Your symbol is very large, look at other symbol and reduce to get the same size and fix KLC 3.1 at the same time
- [x] KLC S4.2 accepted for this symbol

Will require a new complete review after all this changes. please make separated commits to identify the required changes, with a great commit description.

Cheers,
Joel

**Comment by Misaka0x2730** [comment]
About S3.6 and op amp - I just launched checklib.py script and... all op amp violate S3.6

**Comment by myfreescalewebpage** [comment]
@Misaka0x2730 ok, please proceed the other fixes and I will see for this one.

**Comment by myfreescalewebpage** [comment]
@Misaka0x2730 thanks a lot for all the modifications.

MSP432E401Y
- [ ] I would suggest to move GND pins 100mil to the left so the GND/GNDA are symmetrically placed on the symbol

CDNBS08-SLVU2.8-4
- [ ] Description has the wrong package name, should be `, SOIC-8`

TLV62568DBV
- [ ] For consistency with many other device, you can move EN and FB 100mil to the top.

capture

TLV62568DDC
- [ ] For consistency with many other device, you can move EN 100mil to the top.

TLV62568DRL
- [ ] For consistency with many other device, you can move EN and FB 100mil to the top.
- [ ] NC pin should be added, not visible, type not connected as shown below

capture

TPS61041DDC
- [ ] Description package name still not correct, should be ` SOT-23-5`
- [ ] For consistency with many other device, you can move EN and FB 100mil to the top.
- [ ] Footprint is not set, should be `Package_TO_SOT_SMD:SOT-23-5`

TPS61041DRV
- [ ] For consistency with many other device, you can move EN and FB 100mil to the top.
- [ ] NC pin should be added, not visible, type not connected (see TLV62568DRL)
- [ ] Footprint / Footprint Filter seems not correct, probably you should look at the TI SON packages available in the library or provide a new one.

Cheers
Joel

**Comment by Misaka0x2730** [comment]
@myfreescalewebpage Oops, my bad. 
About TPS61041DDC - but DDC package is TSOT-23. DBV - is SOT-23. The only difference - height.

**Comment by evanshultz** [comment]
Indeed, S3.6 is an expected failure on opamp symbols.

NC pins should not stick out of the symbol as shown above. Surely we have some old symbols that do this, though, as seen above.

@Misaka0x2730 
Please include screenshots of all symbols (and footprints) you submit. You can do that now. (This is in the PR template, though we should change "very helpful" to "required".)

**Comment by Misaka0x2730** [comment]
TPS61041DRV package - https://github.com/KiCad/kicad-footprints/pull/1241

**Comment by myfreescalewebpage** [comment]
@Misaka0x2730 can you solve the conflict with the branch ? Thanks
I do not know if this is because of the conflict but I'm unable to checkout your last commits to review, and travis as not checked them...

Joel

**Comment by myfreescalewebpage** [comment]
@Misaka0x2730 thanks.

The last point is TPS61041DDC, description and footprint are not consistent. I have seen your comment about SOT23-5-THIN. Probably the best is to provide a new footprint called "SOT-23-5-Thin".

Other symbols are okay for me.

Joel

**Comment by Misaka0x2730** [comment]
@myfreescalewebpage if I right understand, i can't set different footprint for alias component?

**Comment by myfreescalewebpage** [comment]
@Misaka0x2730 no you can't. Very common devices (i.e. 74xx or 4xxx for example) have no footprint and we define several footprint filter to not have to much large libraries. But for the other, full part name must be defined and device added twice, one for each footprint. This clearly simplify particularly when there is not always the same number of pads, presence or not of exposed pad etc.

**Comment by myfreescalewebpage** [comment]
Hi @Misaka0x2730 

Following acceptance of one footprint linked to this PR, making a full final review of the symbols in this PR.

MSP432E401Y:
- [ ] Pin 59 (RBIAS) type should be Passive

TPS61041DDC:
- [ ] Package name in the description still not correct, should be `SOT-23-5`

TPS61041DRV:
- [ ] Footprint to be updated following merge of PR, should be `Package_SON:WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm`
- [ ] Footprint filter to be updated following merge of PR, should be `WSON*1EP*2x2mm*P0.65mm*`

Also, there is a branch conflict to be solved. It is currently making travis error.

Cheers,
Joel

**Comment by Misaka0x2730** [comment]
@myfreescalewebpage Ok, thanks. 
I'll fix these remarks tonight.

**Comment by Misaka0x2730** [comment]
@myfreescalewebpage Looks completed. Thanks and sorry for I still don't use git well.

**Comment by myfreescalewebpage** [comment]
Closing/opening to get travis result.

**Comment by myfreescalewebpage** [comment]
No worries @Misaka0x2730 seems no completed ! Merging the PR.

Joel

**Pull request merged**
