### PR TITLE
Add AN34092B

### PR DESCRIPTION
**Pull request by evanshultz**
https://industrial.panasonic.com/content/data/SC/ds/ds4/AN34092B_E.pdf
image

Footprint at https://github.com/KiCad/kicad-footprints/pull/652.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
I guess pin 14, FAULT, should have a ~, it is active low


Should pin 9 really be power input ?

bild



PS
When you screen shot the symbol, "switch on" the "show pin type", it is easier and faster to review it
DS

**Comment by evanshultz** [comment]
Made those two changes. Thanks for looking.

My mistake on cutting off the pin types.

**Comment by Misca1234** [comment]
This one is ready to push, what is the process, symbols have to wait for the foot print to be merged first ?

**Comment by evanshultz** [comment]
They can be done in either order, but prefer footprints to be present so we don't have symbols without footprints and also to help catch typos.

**Comment by evanshultz** [comment]
The footprint is merged so this is ready to go.

**Comment by poeschlr** [comment]
I trust the judgment of @Misca1234. Thanks for the contribution.

**Pull request merged**
