### PR TITLE
Add OPA355NA high speed opamp in SOT-23-6

### PR DESCRIPTION
**Pull request by pgrudzinski**
Datasheet: [OPA355](http://www.ti.com/lit/ds/symlink/opa355.pdf)
Screenshot:
image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- Change pin name offset to 5mil.
- Please remove the commas from the description and adhere to the datasheet description.

**Comment by pgrudzinski** [comment]
I will fix the offset, but how does your comment correspond to S6.3 of KLC?
I'm quite sure that I did exactly as it says. It does not say that
description must be 100% in accordance to datasheet, although it makes
sense to use the same terms as manufacturer. It does say it have to be
comma separated, so I took what is used in datasheet and separated terms
with commas. It looks exactly like illustration in KLC. I would leave the
description as is.

**Comment by evanshultz** [comment]
Then please fix the pin name offset and I'll merge.

**Comment by evanshultz** [comment]
Thanks again!

**Pull request merged**
