### PR TITLE
ADM3057E isolated CAN transceiver

### PR DESCRIPTION
**Pull request by rleh**
*Add ADM3057E symbol*

grafik

- [x] Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/ADM3055E-3057E.pdf
- [x] Screenshot
- [x] Footprint already exists
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by rleh** [comment]
> Could you convert this to our "modern" isolated bus transceiver style [...]

Like this?

grafik

**Comment by rleh** [comment]
Or rather like this (with V_ISO_OUT and GND_ISO on the right side):

grafik


---


ab921f0 is shown in the upper picture.

**Comment by chschlue** [comment]
Yes, I was thinking of something along those lines. Choose what's easier to wire up in the schematic.

Also, consider using passive type for the bus side "power" pins, as these aren't actually supposed to drive other power inputs or be driven by external power outputs. Passive avoids having to add power flags if used correctly and triggers ERC warnings if used incorrectly.

**Comment by rleh** [comment]
@chschlue Good point setting the isolated side power pin to passive.

I think I like the variant with V_ISO_OUT and GND_ISO on the right side (see last comit 56d6aa6) better:
grafik

---

Ready to merge from my side.

**Comment by rleh** [comment]
grafik
The `RS` pin belongs to the "isolated" side of the transceiver and thus should be located on the right side.

I will move it closer to the ground pins.

**Comment by rleh** [comment]
grafik

**Comment by rleh** [comment]
Thank you for reviewing!!!

**Pull request merged**
