### PR TITLE
Create TPS22810DRV

### PR DESCRIPTION
**Pull request by eclecticc**
Create http://www.ti.com/lit/ds/symlink/tps22810.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @eclecticc , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name and should not contain special characters, please write `2.7-18V, 79mohms On-Resistance Load Switch With Thermal Protection, WSON-6`
- [ ] Footprint filter should be `WSON*1EP*2x2mm*P0.65mm*` 
- [ ] Keyword can be enhanced, for example `load switch thermal protection`
- [ ] QOD should be "Open Collector"

Cheers,
Joel

**Comment by eclecticc** [comment]
Updated.

**Comment by myfreescalewebpage** [comment]
Thanks @eclecticc just need to fix the description, it's set twice!

**Comment by myfreescalewebpage** [comment]
Thanks. Merging.

**Pull request merged**
