### PR TITLE
Add ADA4940-1ACPZ

### PR DESCRIPTION
**Pull request by matthuszagh**
Add [ADA4940-1ACPZ](https://www.analog.com/media/en/technical-documentation/data-sheets/ada4940-1_4940-2.pdf).

ada4940

power

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/2263).

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] I think the name of the device should be "ADA4940-1xCP" (A is probably the temperature and Z is the ROHS option, both are discard in the lib)
- [ ] You should cross +IN and -IN (it's not always the case in the lib, but I think it's more general)

If you want to fix the ADA4940-2 (if you time), it is welcome and can be merged soon in the lib because we are very closed to v6.

Cheers,
Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage thanks for the review. I've update the name. Can you clarify what you mean by cross +IN and -IN? As in, swap their positions? Isn't it normally the case for differential amplifiers that the orientation of the inputs is opposite to that of the outputs because this permits negative feedback connections without overlapping lines?

**Comment by myfreescalewebpage** [comment]
> As in, swap their positions

That's the purpose yes. But I have seen both situation in the lib, so you decide.

- [ ] Please delete "ADA4940-1ACPZ" and keep only "ADA4940-1xCP" in your pull request.

Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage thanks for catching that, that's now done.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
