### PR TITLE
Valve: Update to latest file format

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
See https://github.com/KiCad/kicad-symbols/pull/1181

### CODE REVIEW

**Comment by evanshultz** [comment]
OK. Looks like all is well and the CI errors aren't affected by this.

**Comment by evanshultz** [comment]
Does this break any outstanding PRs? Do we have a good way to determine that?

**Comment by antoniovazquezblanco** [comment]
I have looked for valve related prs using GH search function and found nothing.

**Comment by evanshultz** [comment]
Alright then. Thanks!

FWIW, doing more than one lib at a time is fine but taking care of libs with no pending PRs, if there's some way to determine that, is a good place to start.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
