### PR TITLE
#957 HLCP-J100 footprint filter

### PR DESCRIPTION
**Pull request by aewallin**
simple fix for #957 
footprints do seem to contain many copies of the same footprint with different names...

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin, thanks for contributing,

Many modifications by the editor but it's okay.
Footprint modified, ok for me.

@antoniovazquezblanco can be merged according to me, and #957 can be closed.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
@aewallin and @myfreescalewebpage  you seem to be contributing a lot lately so I will try to give you my best pointers whenever I can.

In this case, it would be awesome if you were able to split the library update and the changes made into two different commits for reviewing. The way I usually do that is: I open any component in the lib, I open the properties dialog of the component and click OK without making any changes and it will allow me to save the lib with the new format. I will then commit that and proceed to make the changes. I know it is much more tedious but makes it easier later down the review process.

Now, about the changes. You have used `*HLCP?J100*` as the new filter. I don't usually prepend an `*` before the filter. Is there any reason to do that?

Thank you very much!

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco 

> you seem to be contributing a lot lately so I will try to give you my best pointers whenever I can.

Yes I have discussed with other librarians to propose my reviews. Many PRs pending and I think it's good to help when it's possible. I  (but ma,ny I'm try to practice with simple PRs actually.

> In this case, it would be awesome if you were able to split the library update and the changes made into two different commits for reviewing.

I agree with the method, that's always better but we usually see the "bad effects" of the edition after when making the commit so it's too late... If you are not making any change, does it seriously modify the library to the new format ??

> Now, about the changes. You have used *HLCP?J100* as the new filter. I don't usually prepend an * before the filter. Is there any reason to do that?

I have seen with and without in the libraries and I do not know what is the best practice for that, I have not seen any KLC about this.

**Comment by antoniovazquezblanco** [comment]
> If you are not making any change, does it seriously modify the library to the new format ??

Yes. Not a bug, it's a feature :rofl:.

> > Now, about the changes. You have used HLCP?J100 as the new filter. I don't usually prepend an * before the filter. Is there any reason to do that?

> I have seen with and without in the libraries and I do not know what is the best practice for that, I have not seen any KLC about this.

I think this could be related to ancient behaviour when library name was also matched. This is no longer like that but this should be confirmed by more experienced librarians like @evanshultz or @poeschlr .

Thanks

**Comment by myfreescalewebpage** [comment]
> I think this could be related to ancient behaviour when library name was also matched. This is no longer like that but this should be confirmed by more experienced librarians like @evanshultz or @poeschlr .

And conclude with a KLC and a travis test, because this will be redundant question in the future !

**Comment by aewallin** [comment]
Thanks for the guidance.

I agree that ideally the KLC-scripts should check validity of the fp-filter.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco can be merged now following modification of the footprint, and #957 can be closed.

Cheers,
Joel

**Comment by poeschlr** [comment]
Having a * at the beginning can sometimes still be useful. Especially if one might expect fitting footprints to start with a different prefix. 

This was a bit more common in the past especially for things like chip packages. There are for example qfn, vqfn, tqfn and pqfn which are very similar or even equivalent and (seemingly) only named differently because some marketing guy wanted their company to be different. 
Having a * at the beginning allowed us to reuse not quite fitting footprints where we did not have the exactly correct footprint. 
Now that we have scripts for these footprints we can be a bit more strict about that. (We now require the correct footprint to be made and pre assigned.)

**Comment by myfreescalewebpage** [comment]
@poeschlr thanks for clarification

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Comment by evanshultz** [comment]
The leading prefix was also requested by the devs for a time before v5 was released when the footprint filtering behavior was being sorted out. I don't know if these footprints were affected.

VQFN, TQFN, QFN, etc. are often unique in package height. T = thin, V = very thin, etc. So the 3D model is unique even if the footprint is the same. And the 3D models are scripted too, making it easier to be strict, but at the cost of more footprints and 3D models which are very similar.

In this case, why would there be a leading asterisk? Not that I can see it really matters, but the "strictness" would seem to apply here since a display won't have variation like the QFNs I mentioned above. Also, I only recall seeing a question mark used where we know allowing a march against multiple characters will result in non-matching footprints being displayed in CvPcb. For example `SOT*23` will show SOT-23 and SOT-223 so we can use `SOT?23` for a SOT-23 footprint filter but still use `SOT*223` for a SOT-223 package. This is a colloquial rule to be as flexible as possible (so using asterisk wherever possible) but perhaps it's time for a formal rule?

**Comment by aewallin** [comment]
have the travis-scripts print out a list of matched footprints (or the 10 first, if there are more than 10). at least that allows for reasonably fast manual review of the filter results.
then have the KLC dictate wether, and to what extent, false positives and false negatives should be allowed.
too much (manually checked) syntax-rules on the actual filter-string just gives me headache..

**Pull request merged**
