### PR TITLE
Update Switch.lib

### PR DESCRIPTION
**Pull request by kirk-loeten**
MEC 5E

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
https://www.apem.com/de/index.php?controller=attachment&id_attachment=1371
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
Bildschirmfoto 2020-07-08 um 22 15 03
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
it is the same FP like the MEC_5G_LED_BTN
- [x] If there are matching footprint PRs, provide link(s) as appropriate
Buttons_Switches_ThroughHole:SW_MEC_5GTH9
- [x] Check the output of the Travis automated check scripts - fix any errors as required
Bildschirmfoto 2020-07-08 um 22 22 46
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
modification of dcm file expected (see my comment at #2890)
Joel

**Comment by kirk-loeten** [comment]
How can i fix that problem? "Missing all fields on 'Properties > Description' tab"

**Comment by myfreescalewebpage** [comment]
When you have created the symbol you should have pushed the two files modified in the same commit on the same pull request.

To fix on this symbol you can cherry pick the commit, or simply just go on your branch "patch-1" and update the dcm file by hand.

Joel

**Comment by myfreescalewebpage** [comment]
@kirk-loeten thanks for the fix. This is perfect.
Moreover I have no comment on the symbol definition. Merging.
Joel

**Pull request merged**
