### PR TITLE
Add pin names to opamps

### PR DESCRIPTION
**Pull request by evanshultz**
Continuation of https://github.com/KiCad/kicad-symbols/pull/627, adding pin names where missing. In general, the goal is to make pin names visible where possible using pin text size down to 20mil.

Image of a smattering of updated symbols:
image

More detailed breakdown of changes:
Amplifier_Audio:
- General: Change pin name offset to 10mil
- General: Name all unnamed pins
- OPA1622: change inverted pin type to Line type
- STK43x_Sanyo: cannot find a datasheet with pin names so some are left blank
- TDA7496: moved pin 7 to unit B to fit all pins with names

Amplifier_Buffer:
- EL2001: make pin names visible, add CN suffix to indicate DIP package
- LH0002H: fix pin 7 name, move pins 3 and 5 vertical, updated footprint filter

Amplifier_Current:
- INA28x: shift power pins to normal location, move REF* pins to the bottom, make pin names visible

Amplifier_Difference:
- Add AD628 (http://www.analog.com/media/en/technical-documentation/data-sheets/AD628.pdf)

Amplifier_Instrumentation:
- LTC1100*: make pin names visible, align symbols (other than additional pins on xSW symbol)
- INA128/129 moved from Amplifier_Operational

Amplifier_Operational:
- General: Fix up footprint filters throughout
- General: Change pin name offset to 10mil
- ADA4530-1: added package type to description, fixed footprint, reworked symbol a bit
- Add ADA4870 from https://github.com/KiCad/kicad-library/pull/1611 (http://www.analog.com/media/en/technical-documentation/data-sheets/ADA4870.pdf)
- Add MC33172/4 as ALIAS (http://www.onsemi.com/pub/Collateral/MC33171-D.PDF)
- Add OPA1602/4 as ALIAS (http://www.ti.com/lit/ds/symlink/opa1604.pdf)
- ADA4807-1: clarify pin names
- ADA4807-2ACP: clarify pin names, pin name offset to 10mil
- CA3080: name pin 5
- CA3130: name pins, pin name offset to 10mil
- INA128/129: move to Amplifier_Instrumentation
- LM13700: reworked symbol (http://www.ti.com/lit/ds/symlink/lm13700.pdf)
- OPA890: wildcard temp rating

Amplifier_Video:
- AD813: pin name offset, move disable pins and add pin name

Comparator:
- ADCMP35*: name input pin, set pin name offset to 10mil
- LM290*: set pin name offset to 10mil
- LM311: name all unnamed pins, make pin names visible
- MCP6566/MCP6566R/MCP6566U/MCP6569: pin name offset to 10mil
- MIC845H: shrink pin name offset, name or improve name of all pins
- TL3116: move power pins to normal positions, clarify pin names

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Fixed a couple small things I missed in the noise earlier. All remaining issues are regarding pin types which are valid but marked as errors by the check script due to the pin names.

I forgot to mention that I also added the opamp from https://github.com/KiCad/kicad-symbols/pull/741.

**Comment by poeschlr** [comment]
Your first 4 commits are merges. For the future make sure you branch away from the current master branch (git fetch upstream, git checkout upstream/master, git checkout -b new_branch_name, This assumes you have the official repo as a second repo added locally and that it is called upstream.)

Merge commits should really only be required after a contribution commit is made. (Meaning you already made your changes on your branch but some changes got merged to the master of the official lib which conflict with your changes.)

---

Also the diff is quite hard to read as your first real commit is a mix of updating the file version and the adding your fixes. For the future in such cases make a very small change to one symbol (To get the save button. I think you can even revert the change and still be able to save under the new format.).
Save the file and make a separate commit for that first update. (Hopefully this will not be really necessary for many more libs as most should already be saved with v5) This allows the reviewer to look at the diff of the one commit that really does the change. (Avoids further noise.)

---

Now for the review (visually checked all parts in the files you touched as i can not tell from the diff what changes where intended)

In general i think parts with +/- pins on the left could use a bit reduced pin name offset. Especially if the first slot on top/bottom is used. (The + and - collide with the text of that.)
There is also a slight inconsistency as not all op amps have the +/- visible.

Amplifier Audio lib:
- LM4950TA and LM4950TS is missing the pin names for the power pins (unit c)
- Sanyo parts have a few pins without names
- TDA2030 V+ and V- overlap (smaller fontsize would help)
- TDA7266M PG pin looks a bit odd with this large font next to the mute pin (they also nearly overlap)
   - On other parts the PG pin is part of the last unit. They will suffer from the same issue if one overlays that unit with any other unit.
- TDA7266M Is pin 1 or pin 9 the stby pin (make the font smaller. The other pin has no name right now.)

Amplifier buffer: everything ok

Amplifier Current:
- INA193 and INA282: I would suggest to slightly reduce the font size for V+ and GND

Amplifier Difference looks ok

Amplifier Instrumentation:
- The ref pin is sometimes short and sometimes long. (even thought it is at the same "slot" in all symbols)

Amplifier oerational:
- ADA4807-2ACP pin 11 has no name
- OPA2333xxDRB pin 9 without a name
- OPA2691-14 Dis_A is longer than Dis_B (at the same position)

Amplifier Video looks good

Comperator:
- parts with a single IN pin might benefit from reducing the font size of the IN pin (overlap with power pins)

**I am prepared to merge this as is, as long as the stuff i found above is documented in an issue.**

**Comment by evanshultz** [comment]
I will review this closely within the next 2 days and update. Thanks for the workflow comments and review.

**Comment by poeschlr** [comment]
I assume this is the one replaced by #767?

**Comment by evanshultz** [comment]
Yes.

**Pull request closed without merging**
