### PR TITLE
Added haptic driver from TI - DRV2510-Q1.

### PR DESCRIPTION
**Pull request by mpkopec**
Added haptic driver for solenoids and voice coils from TI. Checked the library with utils, however rules 5.1 and 5.2 seem to be for some reason violated - I don't know why. Please suggest any changes if necessary. Below a screenshot of the component.

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@mpkopec thanks for this contribution,

I would first of all suggest that this device should go to "Driver_Motor" library.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Just seen your question at https://github.com/KiCad/kicad-symbols/issues/1450, added Librarians and Question on this to wait returns.

**Comment by mpkopec** [comment]
Hello,
I think driver motor is a bad idea, especially, that there are a lot of haptics drivers, which are not as "motory" as this one. I mean, e.g. LRA drivers from TI. For them I see no reason to put them into Driver_Motor. What is more, the only motor-alike feature is that it drives inductive loads, but I don't think it should be decisive.

**Comment by myfreescalewebpage** [comment]
Yes, that's what you have ask in the issue I have seen after, and you're probably right but I prefer to have the position of more experienced librarians. Any way, until a response is given, here is my review:

- [ ] Description should separate footprint package with a comma, not a dot: `Haptic driver for solenoids and voice coils, up to 3A output, TSSOP-16`
- [ ] Footprint filter should be `HTSSOP*1EP*4.4x5mm*P0.65mm*`
- [ ] Pins length should be 100mil (symbol < 100 pins)
- [ ] GND pins need to be stacked
- [ ] Expose Pad should be renamed GND and stacked with GND pins
- [ ] Name of pin 8 is `STDBY`
- [ ] Type of pins 10/13 (BSTN/BSTP) should be Passive to avoid ERC errors
- [ ] Type of pin 3 (REG) should be Passive to avoid ERC errors
- [ ] Type of pins 11/12 (OUT-/OUT+) should be Power Output

Cheers,
Joel

**Comment by mpkopec** [comment]
Joel,
First of all, thanks for all the insight, I followed all your suggestions except for the footprint, since the one I made a filter for is reccomended by Texas Instruments. If you insist I'll change it, but I wanted to point it out. Below, new screenshot.

image

**Comment by myfreescalewebpage** [comment]
> I followed all your suggestions except for the footprint, since the one I made a filter for is reccomended by Texas Instruments

Keep the footprint of course, I'm only speaking about the footprint filter ! Rules of footprint filters available at http://kicad-pcb.org/libraries/klc/S5.2/

**Comment by mpkopec** [comment]
Thanks Joel, didn't see the part about the mask and EP size. I haven't been around for some time and have to learn KLC once again. Thanks for the review!

**Comment by myfreescalewebpage** [comment]
Thanks for the modifications, no more comment on the symbol. Just wants to wait a response from an experienced librarians at https://github.com/KiCad/kicad-symbols/issues/1450 to decide about the library.

**Comment by myfreescalewebpage** [comment]
Merging according to #1450

**Pull request merged**
