### PR TITLE
add Mini-Circuits attenuator LAT-3

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/LAT-3+.pdf

lat-3

Footprint PL-225 https://github.com/KiCad/kicad-footprints/pull/1150

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Does the Attenuator symbol (zig zak line) need to be oriented in up-down direction ?
if you rotate it and make it smaller you can place GND in the middle ?

**Comment by aewallin** [comment]
@Misca1234 I don't know if there is a standard for RF block-diagrams that we could follow.
some links I found:
rf: http://www.rfcafe.com/business/software/visio-stencils/visio-stencils.htm
attenuators: https://www.electrical-symbols.com/electric-electronic-symbols/electrical-attenuator-symbols.htm
filters: https://www.microwaves101.com/encyclopedias/filter-schematic-symbols 

The mini-circ parts I have worked on are in the image below (most submitted as PRs). For mixers and phase-detectors etc. it is nice to leave the bottom-center position free for a functional pin, not just GND.
See also passive filters #605 - some of my symbols could be merged with that work, if there was a generic symbol-generation script for lpf, hpf, bfp passive filters.
rf_parts

**Comment by Misca1234** [comment]
Ok, was just wondering

**Comment by Misca1234** [comment]
@antoniovazquezblanco 
Not sure if I am the right one to evaluate this

**Comment by antoniovazquezblanco** [comment]
Sorry, I've assigned you to another PR you seemed very involved with but I had many tabs opened and was distracted multiple times this morning which may lead to me assigning you here also.

As always, don't feel pressured by me doing that. I will only do that if I see you have carried out most of the reviewing and you are near to finishing it; just to keep track of things.

I am sorry. That was a mistake.

**Comment by antoniovazquezblanco** [comment]
Footprint merged

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
@Misca1234 @aewallin I agree with the vertical symbol, already seen several times.

@aewallin can you proceed according to the other Mini-Circuit PR for this one (impedance, etc) ?

Thanks,
Joel

**Comment by aewallin** [comment]
Now looks like so:
lat-3

**Comment by Misca1234** [comment]
PS
Do not wait for any comments from my side in this thread, I do not really have any knowledge about these symbols or how to best handle them
DS

**Comment by myfreescalewebpage** [comment]
No worries @Misca1234 I'm currently working with @aewallin on the Mini-Circuits symbols to get them merged soon since the footprint are quite all accepted.

This one is now okay for me too, merging.

Joel

**Pull request merged**
