### PR TITLE
Add TI BQ24072 and BQ24074

### PR DESCRIPTION
**Pull request by mjeanson**
Datasheet: http://www.ti.com/lit/ds/symlink/bq24074.pdf

### BQ24072
[](https://imgur.com/lohfYLL.png)

### BQ24074
[](https://imgur.com/h5paPjC.png)

### BQ24075
[](https://imgur.com/q5yy9jw.png)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jneiva08** [comment]
If I'm now wrong, in the footprint filter you shouldn't put the number of pins.
You can see as example in TAS5825MRHB

**Comment by myfreescalewebpage** [comment]
Hi @mjeanson , thanks for contributing,

A few comments I have during my review:

BQ24072:
- [ ] Name of the device should be `BQ24072RGT` to avoid conflict if the manufacturer add packages options
- [ ] Description should ends with the package name, add `, VQFN-16` at the end
- [ ] Footprint should be `Package_DFN_QFN:VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm`
- [ ] Footprint filter should be `VQFN*1EP*3x3mm*P0.5mm*`
- [ ] BAT pins should be stacked
- [ ] OUT pins should be stacked
- [ ] Expose pad (pin 17) should be stacked with VSS

BQ24073:
- [ ] Name of the device should be `BQ24073RGT` to avoid conflict if the manufacturer add packages options
- [ ] Description should ends with the package name, add `, VQFN-16` at the end

BQ24074:
- [ ] Name of the device should be `BQ24074RGT` to avoid conflict if the manufacturer add packages options
- [ ] Description should ends with the package name, add `, VQFN-16` at the end
- [ ] Footprint should be `Package_DFN_QFN:VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm`
- [ ] Footprint filter should be `VQFN*1EP*3x3mm*P0.5mm*`
- [ ] BAT pins should be stacked
- [ ] OUT pins should be stacked
- [ ] Expose pad (pin 17) should be stacked with VSS

BQ24075:
- [ ] Name of the device should be `BQ24075RGT` to avoid conflict if the manufacturer add packages options
- [ ] Description should ends with the package name, add `, VQFN-16` at the end
- [ ] Footprint should be `Package_DFN_QFN:VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm`
- [ ] Footprint filter should be `VQFN*1EP*3x3mm*P0.5mm*`
- [ ] BAT pins should be stacked
- [ ] OUT pins should be stacked
- [ ] Expose pad (pin 17) should be stacked with VSS

BQ24079:
- [ ] Name of the device should be `BQ24079RGT` to avoid conflict if the manufacturer add packages options
- [ ] Description should ends with the package name, add `, VQFN-16` at the end

Because the PR modify an existing device with major modification, this will need to wait for KiCad V6.

Cheers,
Joel

**Comment by mjeanson** [comment]
Would you prefer this to be split in 2 PRs? One with the new parts and a second one with the updates to BQ24075 for V6?

**Comment by mjeanson** [comment]
The missing footprint is in https://github.com/KiCad/kicad-footprints/pull/1605

**Comment by myfreescalewebpage** [comment]
The footprint has been merged.
The width of the symbols can be reduced a bit (200mil less I think).
If you wish to get BQ24072 to 74 merged soon, yes you can separate modification of BA24075/BQ24079 in another PR that we will merge in V6 only.
Cheers,
Joel

**Comment by mjeanson** [comment]
Resized as requested and remove the updated BQ24075

**Comment by myfreescalewebpage** [comment]
@mjeanson thanks for separating the symbols. No more comment here, merging.

**Pull request merged**
