### PR TITLE
add LMH6702MF+LMH6609MF as variant of existing symbol

### PR DESCRIPTION
**Pull request by aewallin**
http://www.ti.com/lit/ds/symlink/lmh6702.pdf
http://www.ti.com/lit/ds/symlink/lmh6609.pdf

LMH6702 in SOT-23-5 package.
LMH6609 in SOT-23-5 package.
No changes to symbol, just a new variant.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by diegoherranz** [comment]
As mentioned on https://github.com/KiCad/kicad-symbols/pull/1238, could you add "single opamp" to the keywords?

Thanks!

**Comment by aewallin** [comment]
keywords added.

**Comment by aewallin** [comment]
manually resolved merge-conflict (git was confused about the dcm file due to #1233)

**Comment by myfreescalewebpage** [comment]
Hi @aewallin

No more comment on this PR.

Thansk @diegoherranz for the review !

Cheers,
Joel

**Pull request merged**
