### PR TITLE
[RF] Add Semtech SX1276/7/8/9 and fix datasheet links for SX1272/3

### PR DESCRIPTION
**Pull request by maximeborges**
Add symbols for Semtech SX1276/7/8/9 and fix datasheet links for SX1272/3

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi, It looks like it is your first PR in KiCad libraries. Thank you for your contribution and welcome!

For future contributions it would be nice to provide the datasheet link and some screenshots of your symbols in the PR message content. This facilitates and speeds up the review process.

This is my firsts thoughts about your contribution:

- [ ] In SX1272/73 move pins 7 and 8 (Not Connected) onto symbol outline box. This is recommended by KLC, which states: "The end of the pin should lie on the symbols outline box to prevent unwanted connections to the invisible pin..." See further at (http://kicad-pcb.org/libraries/klc/S4.6/). I know you didn't make this symbol, but it is a good time to fix it.

image

- [ ] In SX1272/73 the type of RF (pin 24) and RFI (pin 25) are wrong. Again, I know you didn't make this symbol, but it is a good time to fix it.

- [ ] In SX1276 it would be nice to rename pin 20 to RXTX/RF_MOD (with the underscore) to match datasheet pin name. What do think about that?

- [ ] In SX1276 you've set the type of the pin 21 (RFI_HF) as output, but the datasheet defines it as "RF **input** for band 1 (Ground)"

- [ ] In SX1276 you've set the type of the pin 22 (RFO_HF) as input, but the datasheet defines it as "RF **output** for band 1 (Ground)"

- [ ] In SX1276 you've set the type of the pin 1 (RFI_LF) as output, but the datasheet claims which it is input type
- [ ] In SX1276  you've set the type of the pin 28 RFO_LF as input, but the datasheet says which it is  an output.

- [ ] Description OK
- [ ] Default footprint OK
- [ ] Footprint filter OK
- [ ] Datasheet links OK

I'm in doubt about the pin 29 in SX1272/76. Datasheet says that the exposed pad is connected to GND. Can the pin 29 be stacked? If affirmative, then this can't be merged now, because it will break current designs. @poeschlr, can you give me a hint about this?

image

**Comment by maximeborges** [comment]
I don't have time tonight to do everything, but about the exposed pad, it should effectively be connected to GND.
This is the reference design by Smetech, where it's clearly connected:
image

Anyway, thanks for the review, I will fix the other points.

**Comment by calebreister** [comment]
Just a quick note: it's *Samtec* not Samtech. Not sure if this needs to be corrected in the symbols.

**Comment by gmsotavio** [comment]
@calebreister Are you not confusing Samtec (Connectors manufacturer) with Semtech (RF manufacturer)?

**Comment by maximeborges** [comment]
@calebreister you could have done a quick Google search to see that it's we are talking about Semtech, the RF chip manufacturer.

**Comment by maximeborges** [comment]
This modification will break current design since it's now fixing the "Origin is centered on the middle of the symbol" S3.1 warning.
I also stacked the EP with other GND pins since there is no reason at all to do someting else than connecting it directly to GND.

SX1272
SX1276
SX1278
Sorry for the french text, I can't switch the UI to english for an unknown reason.

**Comment by myfreescalewebpage** [comment]
@gmsotavio what is the status here ? V6 is in preparation and breaking changes can be done now

**Comment by myfreescalewebpage** [comment]
@maximeborges I try to continue/restart the review from this point:

SX1272
- [ ] Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/440000001NCE/v_VBhk1IolDgxwwnOpcS_vTFxPfSEPQbuneK3mWsXlU`
- [ ] I suggest to have all RF related pins on the right (PA_BOOST, VR_PA, RFO, RFI, TXRX) and all the digital pins on the left (SPI port, DIx pins, RESET) to simplify the schematics wiring for RF and MCU parts.
- [ ] Pin 21 name "RF_MOD" only is enough

SX1273
- [ ] Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/440000001NCE/v_VBhk1IolDgxwwnOpcS_vTFxPfSEPQbuneK3mWsXlU`

SX1276
- [ ] Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`
- [ ] I suggest to have all RF related pins on the right (PA_BOOST, VR_PA, RFOxx, RFIxx, TXRX) and all the digital pins on the left (SPI port, DIx pins, RESET) to simplify the schematics wiring for RF and MCU parts. Keeping pin compatibility with SX1272 is very nice.

SX1277
- [ ] Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`

SX1278
- [ ] Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`
- [ ] I suggest to have all RF related pins on the right (PA_BOOST, VR_PA, RFOxx, RFIxx, TXRX) and all the digital pins on the left (SPI port, DIx pins, RESET) to simplify the schematics wiring for RF and MCU parts. Keeping pin compatibility with SX1272/6 is very nice.
- [ ] Name of pin 19 is "NSS"

SX1279
- [ ] Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`

Thanks

Joel

**Comment by myfreescalewebpage** [comment]
@maximeborges ping, just tell me if you are still working on this subject :) this is cool devices plenty of people will love !

**Comment by maximeborges** [comment]
I haven't worked on this thing for quite some months now, so if you want to apply the modification you proposed it will be gladly welcomed. Otherwise I can do it in a few days I think.

**Comment by myfreescalewebpage** [comment]
I cannot do it myself because I'm the reviewer of this PR, I cannot be the author and the reviewer at the same time. No problem, you can do it in the coming days.

PS : remember the repo will be totally locked and transferred to GitLab the 2020-10-01.

**Comment by maximeborges** [comment]
Here we go, i hope it's not too late for the review.

> SX1272
> 
> * [X]  Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/440000001NCE/v_VBhk1IolDgxwwnOpcS_vTFxPfSEPQbuneK3mWsXlU`
> * [X]  I suggest to have all RF related pins on the right (PA_BOOST, VR_PA, RFO, RFI, TXRX) and all the digital pins on the left (SPI port, DIx pins, RESET) to simplify the schematics wiring for RF and MCU parts.
> * [X]  Pin 21 name "RF_MOD" only is enough
> 
> SX1273
> 
> * [X]  Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/440000001NCE/v_VBhk1IolDgxwwnOpcS_vTFxPfSEPQbuneK3mWsXlU`
> 
> SX1276
> 
> * [X]  Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`
> * [X]  I suggest to have all RF related pins on the right (PA_BOOST, VR_PA, RFOxx, RFIxx, TXRX) and all the digital pins on the left (SPI port, DIx pins, RESET) to simplify the schematics wiring for RF and MCU parts. Keeping pin compatibility with SX1272 is very nice.
> 
> SX1277
> 
> * [X]  Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`
> 
> SX1278
> 
> * [X]  Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`
> * [X]  I suggest to have all RF related pins on the right (PA_BOOST, VR_PA, RFOxx, RFIxx, TXRX) and all the digital pins on the left (SPI port, DIx pins, RESET) to simplify the schematics wiring for RF and MCU parts. Keeping pin compatibility with SX1272/6 is very nice.
> * [X]  Name of pin 19 is "NSS"
> 
> SX1279
> 
> * [X]  Datasheet link has changed, please use `https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE`

**Comment by myfreescalewebpage** [comment]
@maximeborges we are closed to move on GitLab but it is still ready !
Datasheet for the aliases have not been updated, else seems it's good.
Joel

**Comment by maximeborges** [comment]
Woops, a bug in KiCAD ?
Well, here it is

**Comment by myfreescalewebpage** [comment]
@maximeborges there is an issue with the CLA, please check. Maybe you have change your mail address? Sign again in this case with the new mail address please, this is mandatory to accept your contribution.
Else no comment on the symbols.
Joel

**Comment by maximeborges** [comment]
It seems that I can't validate the CLA since I changed my main email address on Github, I don't really know what to do to fix this...

**Comment by myfreescalewebpage** [comment]
Can you add the missing email as secondary address in GitHub, maybe it will be ok for CLA

**Comment by maximeborges** [comment]
The missing address is set as my primary; so I don't really understand what's happening

**Comment by maximeborges** [comment]
Looks like changing the author of the commits did it...

**Comment by myfreescalewebpage** [comment]
Thanks, great job! Merging now these very nice symbol that will be very useful in the library :)

**Pull request merged**
