### PR TITLE
Intel

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR pulls across all the Intel symbols

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

there are several symbols in `MCU_Intel`that are not actually MCUs and should be moved:
- 8237 --> MCUSupportIC.lib (new) or Interface.lib???
- 8259 --> MCUSupportIC.lib (new) or Interface.lib???
- 8284 --> Timer.lib
- 8288 --> MCUSupportIC.lib (new) or Interface.lib???

Best,
JAN

**Comment by SchrodingersGat** [comment]
Moved as suggested

**Comment by jkriege2** [comment]
Hi!

could you fix soem of the KLC-errors (at least the ones that are easy) and add an issue for the remaining:
1. replace `Sockets:PLCC44` by `Package_LCC:PLCC-44` in Interface.lib (82C55A_PLCC)
1. replace `Sockets:PLCC28` by `Package_LCC:PLCC-28` in Timer.lib (82C54_PLCC)
1. replace `DIP-40` by `Package_DIP:Package_DIP:DIP-40_W15.24mm` in several libs
1. replace `DIP-28` by `Package_DIP:Package_DIP:DIP-28_W15.24mm` in several libs
1. get rid of all the double-inversions (I think a regexp-replacement replace `(X ~.*I) I` by `\1` should do the trick)

Maybe I can see to fixing the metadata-stuff at a later time.

Best,
JAN

**Comment by SchrodingersGat** [comment]
I have fixed the first two but please merge and we'll address the other multi-library stuff later.

**Comment by jkriege2** [comment]
OK!

Please open an Issue for the remaining things ;-)

Thanks,
JAN

**Pull request merged**
