### PR TITLE
Meanwell IRM-30/45/60 AC/DC converters

### PR DESCRIPTION
**Pull request by Sthing**
Symbols for Meanwell IRM-30/45/60 AC/DC converters.

Footprints: https://github.com/KiCad/kicad-footprints/pull/858

Datasheets:
 - http://www.meanwell.com/Upload/PDF/IRM-30/IRM-30-SPEC.PDF
 - https://www.meanwell-web.com/content/files/pdfs/productPdfs/MW/IRM-45/IRM-45-spec.pdf
 - https://www.meanwell-web.com/content/files/pdfs/productPdfs/MW/IRM-60/IRM-60-spec.pdf

image

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
@Sthing 
You got a merge conflict in the push
Also, new rules applies to isolated ACDC and DCDC converters, the "dotted" line in the middle of the symbol should be one, that is, remove one of the two you have in the symbol

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @Sthing thanks for this contribution

Can you solve the branch conflict for this PR, it prevents checkout and thus it is not possible to make the complete review ? Thanks.

As already indicated by @Misca1234, isolation barrier convention is now to draw only a single dot line, please remove one.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@Sthing ping! :)

**Comment by Sthing** [comment]
Hi @myfreescalewebpage.
Sorry for being absent - been too busy at work.
I'll try and take a look at it tonight.

**Comment by myfreescalewebpage** [comment]
@Sthing no worries, thanks for your message :)

**Comment by myfreescalewebpage** [comment]
@Sthing making a full review from this point.

IRM-30-5:
- [ ] Footprint filter should be `Converter*ACDC*MeanWell*IRM*30*THT*`
- [ ] I suggest to modify output pins according to IRM-20 series: name of pins `+Vo` and `-Vo` and positive pin above negative pin
- [ ] Datasheet link is `https://www.meanwell.com/Upload/PDF/IRM-30/IRM-30-SPEC.PDF` for this symbol and all aliases (missing "s" to http, Meanwell currently redirects)

IRM-45-5:
- [ ] Footprint filter should be `Converter*ACDC*MeanWell*IRM*45*THT*`
- [ ] I suggest to modify output pins according to IRM-20 series: name of pins `+Vo` and `-Vo` and positive pin above negative pin

IRM-60-5:
- [ ] Footprint filter should be `Converter*ACDC*MeanWell*IRM*60*THT*`
- [ ] I suggest to modify output pins according to IRM-20 series: name of pins `+Vo` and `-Vo` and positive pin above negative pin

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@Sthing ping :)

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this PR is abandoned.

**Comment by myfreescalewebpage** [comment]
Repushed, closing.

**Pull request closed without merging**
