### PR TITLE
Sensor_Optical: Kingbright KPS-3227 ambient light sensor.

### PR DESCRIPTION
**Pull request by mgottschlag**
Symbol for the Kingbright KPS-3227 ambient light sensor.

The center of the sensor was copied from the other phototransistors, but the KPS-3227 is a 4-pin package (actually, would fit a 2-pin LED footprint as well, but I thought the symbol should better match the datasheet).

The device uses a standard 1210 RGB LED footprint, so I selected that generic footprint.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
http://www.kingbright.com/attachments/file/psearch/000/00/watermark00/KPS-3227SP1C(Ver.9).pdf
- [X] An example screenshot image is very helpful
2019-01-11-220054_671x656_scrot
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
- if the pins 1-3 and 2-4 are always used together then they can be stacked pins in the symbol?

**Comment by mgottschlag** [comment]
Yeah, that would work... I guess the pin numbers need to be invisible then?

**Comment by aewallin** [comment]
yes, one pin visible, the other stacked pin passive/invisible, with the same pin-name as the visible pin (here the pin names are empty I guess).

**Comment by mgottschlag** [comment]
2019-01-12-143852_515x413_scrot

**Comment by myfreescalewebpage** [comment]
Hi @mgottschlag 

Thanks for your contribution, no comment to do following the update.

@aewallin thanks for your review, good catch.

Cheers,
Joel

**Pull request merged**
