### PR TITLE
Standardize testpoint-like power symbols

### PR DESCRIPTION
**Pull request by evanshultz**
Most of our power symbols look like this:
image

However, some (LINE/NEUT/PRI*/V*) looked like the testpoint symbol:
image

I see two problems with the VDD and VSS symbols above:
1. The power symbols aren't consistent and look like a testpoint. If I see a power symbol in the schematic, it should be clear what it is.
1. Positive and negative voltages are not differentiated.

This PR updates the testpoint-like symbols to look like the first screenshot.

Note that there is other clean up to be done here, like simplifying the symbols and standardizing text sizes, but I'll do that in another PR.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@evanshultz totaly agree with you. No comment on the symbols you have modified, but I suggest also to standardize +3.3VADC / +3.3VDAC / +3.3VP / +VDC / -VDC / HT / VDC. What do you think ?

**Comment by evanshultz** [comment]
Thanks for looking, Joel.

+VDC,  -VDC, and HT are bigger and I'm a little hesitant to make changes right now to them. Even if they are going to be smaller and don't affect the pins. Maybe @poeschlr would like to comment?

I'm happy to update the others but I don't know why they're different. Do you (or anybody else) have any idea if the uniqueness of these symbols has a special meaning that should be retained?

**Comment by myfreescalewebpage** [comment]
> +VDC, -VDC, and HT are bigger and I'm a little hesitant to make changes right now to them

Yep, sure. The update you have done is almost very nice, it's still possible to decide later for the other.

> Do you (or anybody else) have any idea if the uniqueness of these symbols has a special meaning that should be retained?

No I don't, I never use these specific symbols.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
No comments in a couple days so let's go. I standardized the ones that were only slightly different than the common symbol, and left alone the three big symbols we discussed above. OK?

**Comment by myfreescalewebpage** [comment]
@evanshultz current status is convenient I think. Merging.

**Pull request merged**
