### PR TITLE
Add Texas Instruments TPD12S520DBT HDMI Receiver Port Protection and …

### PR DESCRIPTION
**Pull request by twam**
…Interface

Datasheet: http://www.ti.com/lit/ds/symlink/tpd12s520.pdf
Screenshot: screenshot 2019-03-03 at 16 28 48

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @twam thanks for this contribution !
Before we can make the review, can you update the file "sym-lib-table" to add your library in it ?
Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @twam , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name: `, TSSOP-38`
- [ ] Name of pin 16 is `CE_REMOTE_IN`
- [ ] Name of pin 19 is `HOTPLUG_DET_IN`
- [ ] Name of pin 20 is `HOTPLUG_DET_OUT`
- [ ] Name of pin 23 is `CE_REMOTE_OUT `
- [ ] NC pin should be moved to the border outline of the symbol
- [ ] It seems according to the datasheet that pins 16 to 23 are Bidirectional, isn't it ? IN and OUT only refer to the position of the HDMI connector.

Cheers,
Joel

**Comment by twam** [comment]
screenshot 2019-03-05 at 19 47 32

Concerning your last point: From where do you infer that all are bidirectional? From my understanding only the CEC and I²C SDA line bidirectional where as Hotplug and the I²C SCL are only voltage translated from IN to OUT.

**Comment by myfreescalewebpage** [comment]
Great job.
Regarding to the last comment, my references are table on page 3 and schematic on page 7 that only shows bidirectional level translators for the 4 signals.
Joel

**Comment by twam** [comment]
I'm convinced. Updated them all to be bidirectional.

**Comment by myfreescalewebpage** [comment]
Thanks @twam no comment here, merging.

**Pull request merged**
