### PR TITLE
Add a WIFI module  : AI-Thinker ESP-07S

### PR DESCRIPTION
**Pull request by dongly**
Add a WIFI module  : AI-Thinker ESP-07S
[https://wiki.ai-thinker.com/_media/esp8266/a018ps00.pdf](https://wiki.ai-thinker.com/_media/esp8266/a018ps00.pdf)
QQ五笔截图未命名2

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by nerdyscout** [comment]
ESP-07 is already part of kicad-symbols.
image
what is the point about your pull request?
is there a english datasheet to clearify?

**Comment by dongly** [comment]
ESP-07S is not exactly the same as ESP-07. It has a pad on the bottom.
English Version Datasheet: [https://wiki.ai-thinker.com/_media/esp8266/a018ps01.pdf](https://wiki.ai-thinker.com/_media/esp8266/a018ps01.pdf)

now I add a pad on the botom
QQ五笔截图未命名

QQ五笔截图未命名111

QQ五笔截图未命名2

**Comment by gmsotavio** [comment]
@nerdyscout As discussed in https://github.com/KiCad/kicad-footprints/pull/1780, ESP-07S has an extra GND pad, in such way an alias isn't enough.

@dongly, there are two remaining changes to be done before merging:

- [ ] Pin 17 must be set to invisible and passive type (Rules for pin stacking : http://kicad-pcb.org/libraries/klc/S4.3/)

- [ ] It's better to get the body of this symbol centered around the origin (0, 0) in the symbol editor (http://kicad-pcb.org/libraries/klc/S3.1/). I know this will break the backward compatibility with ESP-07, but another PR can be opened to enhance ESP-07. I think this symbol is too big and can be optimized. My personal suggestion is depicted bellow, and you optionally can adhere to it.

image

Checklist: 
- [ ] Symbol name OK
- [ ] Description OK
- [ ] Tags OK
- [ ] Pin numbering/names OK
- [ ] Default footprint OK
- [ ] Footprint filter OK

**Comment by gmsotavio** [comment]
@dongly are you still alive on this?

**Comment by gmsotavio** [comment]
@dongly  Please, reopen whether you are still alive on this.

**Comment by gmsotavio** [comment]
@dongly please, reopen if you are still on this.

**Pull request closed without merging**
