### PR TITLE
Added BSD235C Complementary P+N MOSFET.

### PR DESCRIPTION
**Pull request by cederom**
Infineon's OptiMOS Complementary P+N Small Signal Transistor Enhanced Super Logic 2.5V Avalanche Rated.

Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>

PICTURE: https://pasteboard.co/Jom8zxh.png

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @cederom , thank you for your contribution.

I want to suggest a few changes before a review,

Datasheet link i think it is better to change to https://www.infineon.com/dgdl/Infineon-BSD235C-DS-v02_04-EN.pdf?fileId=db3a30433580b371013585a2d0d53326 in order to open *.pdf file directly

Description should be something like `-0.53/+0.95A Id, -20/+20V Vds, P/N-Channel MOSFET, SOT-363`

**Comment by aris-kimi** [comment]
@cpresser , i please ask also for some input here.
Datasheet:
εικόνα
Current `SOT-363-SC_70-6` from lib:
εικόνα

What should be applied here?
(My conclution is we also need a new scripted SOT-363 (with variations) from below link. Am i right?)

MO-203-AB : https://www.jedec.org/sites/default/files/docs/MO-203C.pdf

**Comment by cederom** [comment]
Hello and thank you @aris-kimi / @cpresser :-) I have only worked with `Package_TO_SOT_SMD:SOT-363_SC-70-6_Handsoldering` on several boards and this works fine. I did not try the "non handsoldering" narrow variant.

**Comment by myfreescalewebpage** [comment]
Hi @cederom , thanks for contributing, and thanks to @aris-kimi for the comments !!!

A few comments I have:

- [ ] Footprint: `Package_TO_SOT_SMD:SOT-363_SC-70-6` 
- [ ] Fp filter: `SOT?363*`
- [ ] Position offset: 20mil
- [ ] I propose to make a two units symbol instead of the current design. It's always more convenient on the schematics and more inline with the lib. See for example: IRF6802SD

@aris-kimi 

> What should be applied here? (My conclution is we also need a new scripted SOT-363 (with variations) from below link. Am i right?)

What do you mean ?

Cheers,
Joel

**Comment by aris-kimi** [comment]
Hi @myfreescalewebpage , i do not think current library's SOT-363 fits datasheets's drawing's dimmensions. Not sure though..

**Comment by myfreescalewebpage** [comment]
There is a very small difference and it's usual with this kind of packages. We can accept SOT-363 (also because the datasheet indicates SOT-363 so we can consider this fit with the standard package dimensions).

**Comment by cederom** [comment]
Will update soon and let you know. Thank you all for your hints and feedback. I have recently bought some other MOSFET N, P, and Complementary from Infineon. Very similar situation. Will also create symbols for them :-)

**Comment by cederom** [comment]
Updates pushed :-)

**Comment by myfreescalewebpage** [comment]
Thanks for the update. However:

- [ ] The orientation of the symbol is not correct, see IRF6802SD, you have top rotate by 90 degrees (all pair of transistor are like that)
- [ ] You have to set the pin offset to 20mil, and you have to uncheck "Show pin name" to hide pin names.

Joel

**Comment by cederom** [comment]
Why did travis fail this time? Can you fix stuff so its ready do merge please? :-)

**Comment by myfreescalewebpage** [comment]
This is due to another pull request, not because of your symbol.
No more to do for this PR, merging.

**Pull request merged**
