### PR TITLE
Add Analog ADN4652

### PR DESCRIPTION
**Pull request by cronJ**
Add Analog ADN4652

Created from [https://www.analog.com/media/en/technical-documentation/data-sheets/adn4650-4651-4652.pdf](https://www.analog.com/media/en/technical-documentation/data-sheets/adn4650-4651-4652.pdf)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cronJ , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name, please add `, SSOP-20` at the end
- [ ] Footprint filter should be `SSOP*5.3x7.2mm*P0.65mm*`
- [ ] The isolation barrier should be indicate with a dash line. For example you can look at `ISO1050DUB` device in the library
- [ ] Pin 9 is missing (VDD1, not to be stacked with pin 3)
- [ ] Pin 12 is missing (VDD2, not to be stacked with pin 3)

Maybe a symbol more tall than large is better, I'm not sure yet.

If you wish to submit ADN4650 and ADN4651 too, it's a pleasure to review them too!

Cheers,
Joel

**Comment by cronJ** [comment]
Hi,

I implemented the requested changes.

Here is the PR for [ADN4650](https://github.com/KiCad/kicad-symbols/pull/1888)
Here is the PR for [ADN4651](https://github.com/KiCad/kicad-symbols/pull/1889)

Best regards.

**Comment by myfreescalewebpage** [comment]
@cronJ that's great, thanks. As indicated above, pin 9 and pin 12 should NOT be stacked. The datasheet indicate two capacitorS are required on the pins, we do not stack positive power pin in this case in the library.
Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Is this PR ready to be merged?

**Comment by myfreescalewebpage** [comment]
Yes it is, sorry, I was not here this week !
Merging.

**Pull request merged**
