### PR TITLE
Corrected footpring name

### PR DESCRIPTION
**Pull request by thomasonw**
Corrected footpring name to reflect final name used in KiCAD-Footprints

This pull request is a follow on to #607 - where the footprint name has been corrected.
Please also refer to companion footprint pull request located at: [https://github.com/KiCad/kicad-footprints/pull/611](https://github.com/KiCad/kicad-footprints/pull/611)

### CODE REVIEW

**Comment by thomasonw** [comment]
I believe the Travis fails are related to the footprint being renamed and not yet accepted?

**Comment by evanshultz** [comment]
Footprints are merged so the check scripts aren't complaining now. Please make the footprint filter more robust with `Texas*HTSOP*1EP*3.9x4.9mm*P1.27mm*EP2.95x4.9mm*Mask2.4x3.1mm*` and then I can merge this.

**Comment by thomasonw** [comment]
Changed footprint filters, and Travis is still happy!

**Comment by evanshultz** [comment]
Thanks again!

**Pull request merged**
