### PR TITLE
Adding SN74AUP1T34DCK

### PR DESCRIPTION
**Pull request by ki5libs**
Adding SN74AUP1T34DCK Logic Level Translator.
[Datasheet](http://www.ti.com/lit/ds/symlink/sn74aup1t34.pdf)
sn74aup1t34dck

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for contributing to KiCad! It's because of a willing community like you that the library can grow and improve.

You will find a list of rules and guidelines for the KiCad library at http://kicad-pcb.org/libraries/klc/. Please see that webpage for more information about the review items below.

- Add package type `SC-70` to the end of the description.
- Keywords are typically mutually exclusive with the description, so you can simplify them.
- Set pin name offset to 20mil.
- Remove the text "LLT" from the symbol.
- Place the VCC* pins at the top, probably moving the A and B pins towards the middle of the sides.
- Part number should be on the top right.

Thanks!

**Comment by antonlysak** [comment]
It's fixed now:
- [x] Add package type SC-70 to the end of the description.
- [x] Keywords are typically mutually exclusive with the description, so you can simplify them.
- [x] Set pin name offset to 20mil.
- [x] Remove the text "LLT" from the symbol.
- [x] Place the VCC* pins at the top, probably moving the A and B pins towards the middle of the sides.
- [x] Part number should be on the top right.
sn74aup1t34dck

Thanks for your explanations!

**Comment by antoniovazquezblanco** [comment]
@evanshultz you started reviewing this. Would you get back to it?

From what I've seen you do a ton of reviewing! It is awesome! I may be making your life miserable with so much asignment, I am sorry!

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
It's nice to have more help now! And I appreciate the pings when I get distracted or forgetful.

@ki5libs 
Sorry that I missed this. Thanks for making fixes. There are two more things to do:
1. Change the footprint filter to `SOT*353*`.
1. Make the B pin Output type. Only when it's powered down is it high-impedance, but that's not a controllable state (for instance with an enable pin) so we won't consider it here.

Thanks!

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
