### PR TITLE
add analog switch MAX14759

### PR DESCRIPTION
**Pull request by penoud**
add analog switch MAX14759

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
https://datasheets.maximintegrated.com/en/ds/MAX14759-MAX14763.pdf
- [X] An example screenshot image is very helpful
image
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
EP must be available for connection:

image

**Comment by penoud** [comment]
Thank, I correct the EP pin to visible.
image

**Comment by evanshultz** [comment]
The URL for ADG633 is being removed! I don't know why, but please fix that. You may have started this branch when it wasn't up to date with the master here.

- Place the EP on the bottom of the symbol. This is rather cramped so you can make it bigger.
- You need the NC pin, set to No Connect type and invisible. Place the end of the pin on the symbol body so it's not easy to accidentally connect.
- Please fix the description as in the first PR.

There are no branch conflicts because of the first PR I merged. It's often best to make one PR for all similar symbols or footprints if they're related. Like here, 3 parts on the same datasheet can go together.

**Comment by evanshultz** [comment]
Oops. Stack pin 11 on VN. See https://github.com/KiCad/kicad-symbols/pull/991#issuecomment-423851359.

**Comment by penoud** [comment]
Update screenshoots
Unit A:
image
Unit B:
image

**Comment by evanshultz** [comment]
The ref des and value are floating above the symbol.

As with the other open switch in this family, let's get some feedback on EP pin placement. I now think placing it next to VN is best, but let's see if I'm alone.

**Comment by penoud** [comment]
Corrected but I'm not able to set ref and des for unit a closer to the component body:
Unit A:
image
Unit B:
image

**Comment by evanshultz** [comment]
The ref des and value placement look OK to me. Thanks!

About the EP, I've been dumb. We figured it out at https://github.com/KiCad/kicad-symbols/pull/991#issuecomment-423851359. If you can do that I can merge.

Thanks!

**Comment by penoud** [comment]
Updated unit b:
image

**Comment by penoud** [comment]
This violate rule 4.3
How can we stack without the same name? We can't, then I have to revert to previous version?

**Comment by penoud** [comment]
Ok I corrected it

**Comment by evanshultz** [comment]
Nice. Thanks! You can update the other switch symbol similarly and I can merge it.

**Pull request merged**
