### PR TITLE
Added UCCx895

### PR DESCRIPTION
**Pull request by LJJS**
Added the UCCx895 family.
http://www.ti.com/lit/ds/symlink/ucc3895.pdf

UCCx895

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cp-aquila** [comment]
It seems you have done commits using different users. Thus the CLA complains.
Since no one has started a review yet, you can rewrite the history to fix this and force push.

**Comment by LJJS** [comment]
> It seems you have done commits using different users. Thus the CLA complains.
> Since no one has started a review yet, you can rewrite the history to fix this and force push.

Thanks,
It should be fixed now.

**Comment by myfreescalewebpage** [comment]
@LJJS you should create one symbol per footprint, we now try to not make so much generic symbol. Please also review #2582 some comments apply also here. Joel

**Comment by LJJS** [comment]
> @LJJS you should create one symbol per footprint, we now try to not make so much generic symbol. Please also review #2582 some comments apply also here. Joel

@myfreescalewebpage I made the changes as you proposed

**Comment by myfreescalewebpage** [comment]
I see several soic and several dip. Are they alias ? In this case make alias. I was only pointing we create separated symbol when the footprint and pinout is not the same only.

**Comment by LJJS** [comment]
> I see several soic and several dip. Are they alias ? In this case make alias. I was only pointing we create separated symbol when the footprint and pinout is not the same only.

Ah okay I see.
I changed it according to that

**Comment by myfreescalewebpage** [comment]
Hi @LJJS , thanks for contributing,

A few comments I have during my review:

UCC3895DW
- [ ] The footprint filter should be `SOIC*7.5x12.8mm*P1.27mm*`

For all:
- [ ] SS/DISB, CT, RT, DELAB and DELCD should be Passive to avoid ERC errors

Else, great job !!

Cheers,
Joel

**Comment by LJJS** [comment]
> Hi @LJJS , thanks for contributing,
> 
> A few comments I have during my review:
> 
> UCC3895DW
> 
>     * [ ]  The footprint filter should be `SOIC*7.5x12.8mm*P1.27mm*`
> 
> 
> For all:
> 
>     * [ ]  SS/DISB, CT, RT, DELAB and DELCD should be Passive to avoid ERC errors
> 
> 
> Else, great job !!
> 
> Cheers,
> Joel

Hi @myfreescalewebpage,
thanks for your quick review!

I made the changes as you suggested.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
