### PR TITLE
ir

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Moved `ir` library (International Rectifier)

### CODE REVIEW

**Comment by poeschlr** [comment]
According to https://github.com/KiCad/kicad-library/issues/1402:
- The audio amplifiers should go into amplifier_audio, the rest of the audio stuff into audio_misc
- driver_fet should be called driver_gate (Both names are equally valid. But we might want to fix the table in the issue or use the name we used there.)
- smart fets in power_distribution lib see issue: https://github.com/KiCad/kicad-symbols/issues/56
- maybe we should use Power_FactorController (or Correction) instead of Power_PFC

**Comment by evanshultz** [comment]
> maybe we should use Power_FactorController (or Correction) instead of Power_PFC

I think this breaks the paradigm. It's a controller for a PFC supply, so I suggest `Regulator_Controller_PFC`. That sticks closely to the existing lib naming and is clear. A PFC controller and non-PFC controller are not to be confused and would not be confused by someone designing a SMPS using one.

**Comment by SchrodingersGat** [comment]
* Amplifier_Audio - Fixed
* Driver_FET - I think Driver_FET is a better name, but happy to change if the consensus is otherwise.
* I put these into `Power_Distritbution` so that we can easily rename this lib if we come up with a better name. At least they are in the one place.
* Would `Regulator_PFC` be an acceptable compromise?

**Comment by poeschlr** [comment]
Merge required.

About PFC lib: I suggest to use less appreciations. (I think i will not be the only person who has no clue what PFC stands for. Took me some trips to google to find this out.)

**Comment by SchrodingersGat** [comment]
I think that people who are using a PFC device would know what it stands for, though.. 

I have inquired about adding library descriptions here - https://lists.launchpad.net/kicad-developers/msg32497.html

We also have other abbreviations in the library names, FET, BJT, CMOS, etc. There is at some level always going to be required knowledge.

(I had to Google PFC at some point, too).

**Comment by SchrodingersGat** [comment]
I will have to restart this PR as the merge conflicts are very complicated. I will have to only transfer one lib at a time now that they are all meshing together.

Once we arrive at a consensus for the PFC lib I'll close this PR and start again.

**Comment by SchrodingersGat** [comment]
Given that there are not enough PFC devices to really warrant their own lib, I'll put these under `Regulator_Controller`. If that library ever balloons to hundreds of items we can reclassify at that stage.

**Comment by SchrodingersGat** [comment]
Once #71 and #73 are merged I shall resubmit this one.

**Comment by SchrodingersGat** [comment]
Closing, replaced by https://github.com/KiCad/kicad-symbols/pull/78

**Pull request closed without merging**
