### PR TITLE
Adding IS25WP256D

### PR DESCRIPTION
**Pull request by ki5libs**
Adding IS25WP256D
[Datasheet](http://www.ti.com/lit/ds/symlink/tlv62080.pdf)
is25wp256d

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Could you put the NC pin on the edge, like the recommendation of KLC S4.6

**Comment by antonlysak** [comment]
I think it's done now

**Comment by ki5libs** [comment]
I've fixed errors caused autotest's fails in different symbols, but I think that most of them needs serious reworking (but it should not be part of this PR)

**Comment by ki5libs** [comment]
I've resolved conflicts taking the version from master repository. But it causes autotest's fails again. @jneiva08 please make some decision regarding that and tell me what should I do in this situation. I hope IS25WP256D could be merged some way...

**Comment by poeschlr** [comment]
It is ok to ignore travis messages in symbols not changed by you. (Travis tries to only show errors in things made by you. If part of your contribution requires manual merges then it will include all changes by these merges.)

**Pull request closed without merging**
