### PR TITLE
Added new mosfet. FDN340P

### PR DESCRIPTION
**Pull request by TheSillyMouse**
Manufacturer: ON Semiconductor
Part Number: FDN340P
Description: 2A Id, 20V Vds, P-Channel MOSFET, 70mOhm Ron, SOT-23

Datasheet:
https://www.onsemi.com/pub/Collateral/FDN340P-D.PDF
image

Screenshot:
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @TheSillyMouse , thanks for this addition.

This symbol, since it already has a lot of simillars, it is better to be declared as an alias of TP0610T, wich is the parent symbol of some SOT-23 P-ch MOSFETs.

Logic behind this is:
if a new part has already an existing symbol, AND, with the same footprint (also same pin connections), it is declared as an alias.

aaa

**Comment by TheSillyMouse** [comment]
> Hi @TheSillyMouse , thanks for this addition.
> 
> This symbol, since it already has a lot of simillars, it is better to be declared as an alias of TP0610T, wich is the parent symbol of some SOT-23 P-ch MOSFETs.
> 
> Logic behind this is:
> if a new part has already an existing symbol, AND, with the same footprint (also same pin connections), it is declared as an alias.
> 
> aaa

@aris-kimi 
Alias added.

**Comment by aris-kimi** [comment]
Hi @TheSillyMouse i think you should change the datasheet URL once again, aliases update their fields from parent's info, and then this PR will be ready.

**Comment by TheSillyMouse** [comment]
> Hi @TheSillyMouse i think you should change the datasheet URL once again, aliases update their fields from parent's info, and then this PR will be ready.

Done.

**Comment by cpresser** [comment]
> Hi @TheSillyMouse i think you should change the datasheet URL once again, aliases update their fields from parent's info, and then this PR will be ready.

Hi @aris-kimi. I did see you made some useful comments and reviews recently. How do you feel about joining the librarian-team? We could use some help.

**Comment by aris-kimi** [comment]
@cpresser ,I would love to. I still have a lot to learn, i do need some info in order to be able to help you appropriately. But yes that sounds great. Thank you for this.

**Comment by evanshultz** [comment]
@TheSillyMouse 
All looks good now. Thank you!

@aris-kimi 
Thank you for the great review and for accepting the invitation!

**Pull request merged**
