### PR TITLE
add PAM8403DR, 3w stereo class d amp

### PR DESCRIPTION
**Pull request by lukh**
Adding a 3W Stereo Class D amp in a SOP-16 package
[PAM8403](https://www.diodes.com/assets/Datasheets/PAM8403.pdf)
Screenshot from 2020-05-07 10-08-11

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lukh , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "PAM8403D"
- [ ] Footprint is not correct, should be `Package_SO:SOP-16_3.9x9.9mm_P1.27mm` (to be submitted)
- [ ] Fp filter: `SOP*3.9x9.9mm*P1.27mm*`
- [ ] NC pin should be on the border outline of the symbol
- [ ] You should align PVDD with PGND
- [ ] The width of the symbol can be reduced

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Important note: the repository will be locked for new PR the 2020-09-01 in preparation of v6. If you want to submit the footprint you can do it before the end of August.

**Comment by lukh** [comment]
- [ ] Name of the symbol should be "PAM8403D"
- [ ] Footprint is not correct, should be Package_SO:SOP-16_3.9x9.9mm_P1.27mm (to be submitted)
- [ ] Fp filter: SOP*3.9x9.9mm*P1.27mm*
- [ ] NC pin should be on the border outline of the symbol
- [ ] You should align PVDD with PGND
- [ ] The width of the symbol can be reduced

**Comment by lukh** [comment]
Here the link of the footprint PR: https://github.com/KiCad/kicad-footprints/pull/2426

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint.

**Comment by chschlue** [comment]
FP merged.

**Comment by lukh** [comment]
Thank you all ! :)

**Pull request merged**
