### PR TITLE
Added Adesto AT25SL321-UUE-T 32-Mbit FLASH memory

### PR DESCRIPTION
**Pull request by aectaan**
Added Adesto AT25SL321-UUE-T FLASH memory.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
https://www.adestotech.com/wp-content/uploads/AT25SL321_112.pdf
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
image
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
https://github.com/KiCad/kicad-footprints/pull/2307
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aectaan , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "AT25SL321-U"
- [ ] Fp filter: `WLCSP*1.55x2.28x0.52mm*Layout2x4*P0.5mm*`
- [ ] Name of pin B2 should be `IO1/SO` to have main function near to the border
- [ ] Pin length 100mil for this symbol

Cheers,
Joel

**Comment by aectaan** [comment]
Hi Joel, thank you for review. I fixed all, that you pointed.

**Comment by myfreescalewebpage** [comment]
Thanks looks great.
I think you can decrease the height of the symbol, 100mil at the top and 100mil at the bottom.
Else just need to wait the fooprint

**Comment by aectaan** [comment]
I reduced height, as you said. Footprint is [here](https://github.com/KiCad/kicad-footprints/pull/2307)

**Comment by myfreescalewebpage** [comment]
Thanks. Just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
@aectaan footprint name to be updated here please

**Comment by myfreescalewebpage** [comment]
@aectaan ping we are closed to the merge on this symbol, thanks!

**Comment by aectaan** [comment]
@myfreescalewebpage I'm on vacation right now, can I do it at this Sunday?

**Comment by myfreescalewebpage** [comment]
Sure sure !! No problem, this was just to have news from you :-)
Remember the repo will be totally locked and transferred to GitLab the 2020-10-01.

**Comment by aectaan** [comment]
now it looks ok:)

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
