### PR TITLE
Clear STM8 library

### PR DESCRIPTION
**Pull request by aris-kimi**
Some aliases removed, some alliases added, a few descriptions corrected.
stm8s

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aris-kimi , thanks for this enhancement. This is breaking the current library and will be merged at the next major release only (KiCad V6).
I see one travis warning about STM8S003F3U: can you also fix the footprint filter: `ST?UFQFPN*3x3mm*P0.5mm*`
Joel

**Comment by aris-kimi** [comment]
Hi @myfreescalewebpage , i made it *UFQFPN*3x3mm*P0.5mm* , should i change it like you mentioned? or leave it so it might fit in at any possible footprint name change?

**Comment by myfreescalewebpage** [comment]
We usually include the manufacturer in this kind of case, yes.

**Comment by myfreescalewebpage** [comment]
Thanks. Ready to go when V6 will be here.

**Pull request merged**
