### PR TITLE
ublox Sara U2xx Symbol

### PR DESCRIPTION
**Pull request by jneiva08**
Added symbol of ublox Sara U2xxx

Datasheet: https://www.u-blox.com/sites/default/files/SARA-U2_DataSheet_(UBX-13005287).pdf
Integration Manual: https://www.u-blox.com/sites/default/files/SARA-G3-U2_SysIntegrManual_%28UBX-13000995%29.pdf

sara

Footprint: [#1099](https://github.com/KiCad/kicad-footprints/pull/1099)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I am not sure that power out is the correct electrical type for sim_det

Otherwise this looks good

**Comment by jneiva08** [comment]
you are right, in the datasheet says input. thanks for catch

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08, thanks for contributing,

A few comments additionally to @poeschlr :

- [ ] Indicate the datasheet in datasheet field, not the integration manual
- [ ] According to the datasheet, RESET should be named RESET_N
- [ ] According to the datasheet ANT is Bidirectional, not Passive

Cheers,
Joel

**Comment by poeschlr** [comment]
@myfreescalewebpage the footprint is found under https://github.com/KiCad/kicad-footprints/pull/1099. And yes this link was missing from this pull request.

**Comment by antoniovazquezblanco** [comment]
I am sorry another merge caused a conflict in this PR due to KiCad updating the file version.

@myfreescalewebpage about:
> According to the datasheet, RESET should be named RESET_N

I think that the `_N` is to indicate that the logic of the pin is inverted and we can do that with the upper line.

**Comment by antoniovazquezblanco** [comment]
I resolved the conflict for you @jneiva08 

Please make a pull before commiting any other changes!

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco 

> I think that the _N is to indicate that the logic of the pin is inverted and we can do that with the upper line.

I agree. In the past someone ask me to add _N on a symbol to be consistent with the datasheet. I think he was right because when many pins have a similar name, this is a source of troubles. I think we should keep symbol closed to the datasheet.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco and @jneiva08 just read KLC S4.7 (http://kicad-pcb.org/libraries/klc/S4.7/) and removed my previous comment about _N. Also make a second review of all the other PR I have commented these days, still some modification to do to conform with this KLC.

**Comment by jneiva08** [comment]
@antoniovazquezblanco Thanks for resolved the conflict.
Now i'm getting error when try to open the RF library
Later will make the clone again to confirm if it is giving the same error

**Comment by antoniovazquezblanco** [comment]
>  Did find already the problem why didn't open and have already fixed.

Sorry, I resolved the conflict through Github interface and missed those two lines! :man_facepalming:

**Comment by antoniovazquezblanco** [comment]
Is there anything missing in this PR?

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco there is question about the ANT pin, also on other PR. Librarians haven't status actually.

**Comment by poeschlr** [comment]
Looks good now.

**Comment by jneiva08** [comment]
thanks for all your time

**Pull request merged**
