### PR TITLE
Added DC4759J5020AHF.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://cdn.anaren.com/product-documents/Xinger/DirectionalCouplers/DC4759J5020AHF/DC4759J5020AHF_DataSheet(Rev_E).pdf

image

image

Footprint pr: https://github.com/KiCad/kicad-footprints/pull/1281

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by matthuszagh** [comment]
What's the correct way to accommodate multiple configurations that use the same footprint? I don't think I did it the right way here...

**Comment by aewallin** [comment]
Unit A/B is e.g. for dual op-amps where the same package contains two amps and we want to place two symbol-units on the schematic that belong to the same footprint.

I don't think you can do anything else than two separate symbols (with identical copied graphic+box) for the two pin-configurations here.

for a mini-circ directional coupler I came up with #1224, but your graphic looks better :)

**Comment by matthuszagh** [comment]
@aewallin, thoughts on how I should name them?

**Comment by myfreescalewebpage** [comment]
@matthuszagh no comment on these symbols, thanks to @aewallin for the review. Merging.

**Pull request merged**
