### PR TITLE
MP45DT02 symbol changes

### PR DESCRIPTION
**Pull request by Resaj**
MP45DT02 symbol changes for adapt it to KLC convention.

Datasheet: http://www.st.com/content/ccc/resource/technical/document/datasheet/group3/27/62/48/98/44/54/4d/36/DM00303211/files/DM00303211.pdf/jcr:content/translations/en.DM00303211.pdf

PR footprint: https://github.com/KiCad/kicad-footprints/pull/303

imagen

### CODE REVIEW

**Comment by Resaj** [comment]
I supose that the footprint link is wrong until the PR #303 of footprints library has been acepted.

**Comment by jkriege2** [comment]
2018-01-28 21_10_38-symbol library editor - sensor_temperature d__kicad_review pretty_kicad-symbols
2018-01-28 21_10_10-symbol library editor - sensor_pressure d__kicad_review pretty_kicad-symbols_se

**Comment by poeschlr** [comment]
@jkriege2 did you mean to just add two screenshots without comment here or where they meant for somewhere else?

**Comment by jkriege2** [comment]
Oh no .... there was text with those ;-)

@Resaj Please remodel your symbol after the other sensors in the lib. It makes sense to have all I/O on the right (especially I wouldn't split the bus-pins CLK and DOUT onto two sides) and a small drawing of a microphone symbol (see device.lib for reference) inside to indicate this is a microphone++.

See the two screenshots above for reference on the symbol-shapes.

**Comment by Resaj** [comment]
I've just made the changes.
This is the new image of the symbol:
imagen

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
