### PR TITLE
add STGP7NC60HD

### PR DESCRIPTION
**Pull request by BAHOO08**
I added new symbol to Transistor_IGBT.lib.

---
datasheet http://www.farnell.com/datasheets/2309889.pdf
изображение

after symbol checking  i got  this message
"Checking symbol 'STGP7NC60HD':
  Violating S3.1"

But i think this symbol set symmetrical.

### CODE REVIEW

**Comment by cp-aquila** [comment]
TBH, I think this looks rather ugly with the big circle. The body-diode is also way bigger than the other diode-arrows in the symbol.

How about something like this?
grafik
I did start from `Q_NIGBT_GCE` to create that.

**Comment by BAHOO08** [comment]
изображение
Made the circle smaller

**Comment by chschlue** [comment]
It would be great if we could stick with all the other transistor symbols' pin positions for interchangeability, like @cpresser's mockup.

**Comment by BAHOO08** [comment]
@chschlue, I dont understand, what do you mean?

**Comment by chschlue** [comment]
Transistor pins in the lib are usually at -200/0, 100/200, 100/-200 while yours are at -300/0, 50/200, 50/-200.

**Comment by myfreescalewebpage** [comment]
Hi @BAHOO08 , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with package name: `25A, 600V, N-Channel IGBT, TO-220`
- [ ] Can you follow @chschlue recommandation at https://github.com/KiCad/kicad-symbols/pull/2861#issuecomment-675596301 please ? The design of @cpresser at https://github.com/KiCad/kicad-symbols/pull/2861#issuecomment-669077271 correspond to these constraints, please carefully check the position of the pins

Cheers,
Joel

**Comment by BAHOO08** [comment]
I changed position pins into -200/0, 100/200, 100/-200 and add TO-220 to discription.
P.S. Sorry for taking so long to edit. There was no way to go to the laptop on vacation.

**Comment by myfreescalewebpage** [comment]
No worries :) Thanks for the update. Merging.

**Pull request merged**
