### PR TITLE
Add ublox NEO M8 series

### PR DESCRIPTION
**Pull request by jneiva08**
ublox NEO-M8M

Datasheet: https://www.u-blox.com/sites/default/files/NEO-8Q-NEO-M8-FW3_HardwareIntegrationManual_%28UBX-15029985%29_0.pdf
neo_m8m

ublox NEO-M8N, M8Q, 8Q

Datasheet: https://www.u-blox.com/sites/default/files/NEO-8Q-NEO-M8-FW3_HardwareIntegrationManual_%28UBX-15029985%29_0.pdf
neo_m8n

ublox NEO-M8T

Datasheet: https://www.u-blox.com/sites/default/files/NEO-8Q-NEO-M8-FW3_HardwareIntegrationManual_%28UBX-15029985%29_0.pdf
neo_m8t

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

Please can you also proceed these symbols following my comments for https://github.com/KiCad/kicad-symbols/pull/1097 and https://github.com/KiCad/kicad-symbols/pull/1096 ?

Cheers,
Joel

**Comment by jneiva08** [comment]
The symbols looks like this:

NEO-8Q/M8Q/M8N
8q

NEO-M8M
m8m

NEO-M8T
m8t

**Comment by jneiva08** [comment]
@myfreescalewebpage I think it looks better now. Hope i didn't forgot anything.

m8t

**Comment by myfreescalewebpage** [comment]
Hello @jneiva08 

Sorry for the long delay. Thanks for all these modifications, great job !!

Some few comments on this PR given below.

NEO-M8T:
- [ ] Name of pin 3 is "TIMEPULSE", not "TIMEPULSE_1"

NEO-M8M:
- [ ] Type of pin 1 "SAFEBOOT" is "Input", not "Bidirectionnal"

NEO-M8N / NEO-M8Q / NEO-8Q:
- [ ] Type of pin 1 "SAFEBOOT" is "Input", not "Bidirectionnal"

All:
- [ ] For consistency with MAX / LEO families, description can start with only "GNSS Module NEO M8" for M8N/M8M/M8Q/M8T and "GNSS Module NEO 8" for NEO-8Q without the full part name which is redundant

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks. Just restarted travis test after merging the footprint.

No more comment to do, merging this PR.

Cheers,
Joel

**Comment by jneiva08** [comment]
thanks for your time

**Pull request merged**
