### PR TITLE
XC6220B331MR - 1A LDO Voltage Regulator

### PR DESCRIPTION
**Pull request by nerdyscout**
Hi,
added just another LDO.

https://media.digikey.com/pdf/Data%20Sheets/Torex/XC6220.pdf

grafik

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@nerdyscout thansk for the fixes.

However, I do not agree to add SOT-89. First, this is not the same part name (XC6220B331MR  is only SOT-23) and moreover, the pins number are not consistent (same number of pins but not the same allocation).

- [ ] Remove SOT-89 from the footprint filter

KLC S4.2 accepted for this symbol.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@nerdyscout thanks.

- [ ] You are still violating S5.1 (need to add footprint - to not make the confusion with footprint filter, it's not the same field) -> http://kicad-pcb.org/libraries/klc/S5.1/

Joel

**Comment by nerdyscout** [comment]
thank you for clarification!

**Comment by myfreescalewebpage** [comment]
@nerdyscout No worries. The last comment before it is possible to merge:

- [ ] The footprint is at a strange position, you can put is closer to the device, or at position 0, 0 for example. This will permit people who make the footprint visible in a schematic to not be lost.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@nerdyscout thanks, looks great, merging the PR

**Pull request merged**
