### PR TITLE
MPL115A1: Change footprint

### PR DESCRIPTION
**Pull request by jneiva08**
Update default footprint and filter.

Footprint: https://github.com/KiCad/kicad-footprints/pull/1570

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 thanks for this contribution,

Just one comment, footprint should be `NXP*LGA*3x5mm*P1.25mm*` here.

Joel

**Comment by jneiva08** [comment]
Hi @myfreescalewebpage , have done the change

**Comment by evanshultz** [comment]
Since height is specific for this part and different from other related NXP sensors, perhaps height should be in the footprint filter also?

Note that this is potentially capricious to do during 5.1 since it affects and existing symbol but I'll take the responsibility, Joel.

**Comment by myfreescalewebpage** [comment]
@evanshultz I have clearly wondered if it was to be included, but removing the height permit more user possibilities as we do for the EP size.
Footprint and symbol specific to this part only and changed at the same time, I don't think this is a problem.
Joel

**Comment by evanshultz** [comment]
I don't agree with you.

We leave off the EP size on QFNs because the footprint fits the package perfectly and also because the EP size doesn't affect the 3D model (varying EP sizes or via/no-via footprints can share a 3D model).

In this case, the height of the package is known and this footprint filter allows footprints with a 3D model of an incorrect height to be selected. The footprint filter (because of the 3D model association) allows more than just footprints with varying copper and a correct 3D model.

Does that make sense? Have I overlooked something?

Now, is this a big issue? No. But I'm sharing what should be thought through before deciding interchangeability and from there what possible footprints (and 3D models) CvPcb should show to the users when the footprint filter, err, filter is enabled.

**Comment by myfreescalewebpage** [comment]
I have forgotten about the 3D model, you are right, height is probably better in this case, sorry. @jneiva08 if you wish to fix the EP filter back with height, can you make a PR please ? Sorry for the annoyance.

**Pull request merged**
