### PR TITLE
Remove part name from description in power ports

### PR DESCRIPTION
**Pull request by JacobEFO**
Remove part name from description

---
Description: Several power ports contained part name in the description violating http://kicad-pcb.org/libraries/klc/S6.3/

Fixed that issue on several power ports. The filtering function remains unchanged.

Output from Travis check:

Checking symbol '+10V' - No errors
Checking symbol '+12C' - No errors
Checking symbol '+12L' - No errors
Checking symbol '+12LF' - No errors
Checking symbol '+12P' - No errors
Checking symbol '+12V' - No errors
Checking symbol '+12VA' - No errors
Checking symbol '+15V' - No errors
Checking symbol '+1V0' - No errors
Checking symbol '+1V1' - No errors
Checking symbol '+1V2' - No errors
Checking symbol '+1V35' - No errors
Checking symbol '+1V5' - No errors
Checking symbol '+1V8' - No errors
Checking symbol '+24V' - No errors
Checking symbol '+28V' - No errors
Checking symbol '+2V5' - No errors
Checking symbol '+2V8' - No errors
Checking symbol '+3.3VA' - No errors
Checking symbol '+3.3VADC' - No errors
Checking symbol '+3.3VDAC' - No errors
Checking symbol '+3.3VP' - No errors
Checking symbol '+36V' - No errors
Checking symbol '+3V3' - No errors
Checking symbol '+3V8' - No errors
Checking symbol '+48V' - No errors
Checking symbol '+4V' - No errors
Checking symbol '+5C' - No errors
Checking symbol '+5F' - No errors
Checking symbol '+5P' - No errors
Checking symbol '+5V' - No errors
Checking symbol '+5VA' - No errors
Checking symbol '+5VD' - No errors
Checking symbol '+5VL' - No errors
Checking symbol '+5VP' - No errors
Checking symbol '+6V' - No errors
Checking symbol '+7.5V' - No errors
Checking symbol '+8V' - No errors
Checking symbol '+9V' - No errors
Checking symbol '+9VA' - No errors
Checking symbol '+BATT' - No errors
Checking symbol '+VDC' - No errors
Checking symbol '+VSW' - No errors
Checking symbol '-10V' - No errors
Checking symbol '-12V' - No errors
Checking symbol '-12VA' - No errors
Checking symbol '-15V' - No errors
Checking symbol '-24V' - No errors
Checking symbol '-2V5' - No errors
Checking symbol '-36V' - No errors
Checking symbol '-3V3' - No errors
Checking symbol '-48V' - No errors
Checking symbol '-5V' - No errors
Checking symbol '-5VA' - No errors
Checking symbol '-6V' - No errors
Checking symbol '-8V' - No errors
Checking symbol '-9V' - No errors
Checking symbol '-9VA' - No errors
Checking symbol '-BATT' - No errors
Checking symbol '-VDC' - No errors
Checking symbol '-VSW' - No errors
Checking symbol 'AC' - No errors
Checking symbol '~Earth' - No errors
Checking symbol '~Earth_Clean' - No errors
Checking symbol '~Earth_Protective' - No errors
Checking symbol 'GND' - No errors
Checking symbol 'GNDA' - No errors
Checking symbol 'GNDD' - No errors
Checking symbol 'GNDPWR' - No errors
Checking symbol 'GNDREF' - No errors
Checking symbol 'GNDS' - No errors
Checking symbol 'HT' - No errors
Checking symbol 'LINE' - No errors
Checking symbol 'NEUT' - No errors
Checking symbol 'PRI_HI' - No errors
Checking symbol 'PRI_LO' - No errors
Checking symbol 'PRI_MID' - No errors
Checking symbol 'PWR_FLAG':
  Violating S5.2
  Violating S6.2
Checking symbol 'VAA' - No errors
Checking symbol 'VAC' - No errors
Checking symbol 'VBUS' - No errors
Checking symbol 'VCC' - No errors
Checking symbol 'VCCQ' - No errors
Checking symbol 'VCOM' - No errors
Checking symbol 'VD' - No errors
Checking symbol 'VDC' - No errors
Checking symbol 'VDD' - No errors
Checking symbol 'VDDA' - No errors
Checking symbol 'VDDF' - No errors
Checking symbol 'VEE' - No errors
Checking symbol 'VMEM' - No errors
Checking symbol 'VPP' - No errors
Checking symbol 'VS' - No errors
Checking symbol 'VSS' - No errors
Checking symbol 'VSSA' - No errors
Checking symbol 'Vdrive' - No errors

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @JacobEFO , thanks for contributing,

A single comment I have during my review:

- [ ] Parts +1V0, +1V1, +1V1, +1V35, +1V5, +1V8, +2V5, +2V8, +3V8, -2V5, -3V3, VAA description should be changed to "Power flag" for consistency

Agree with the other changes.

Cheers,
Joel

**Comment by evanshultz** [comment]
What does ", direct current" mean? We can't know how the user will utilize this plumbing signal so if this is to indicate DC (not alternating current) I don't get it. And these are also voltages symbols so I'm not seeing why current should be mentioned.

**Comment by myfreescalewebpage** [comment]
@evanshultz an option can be to remove any of these descriptions... DC is for direct current in this case, +/-BATT have also battery in the description for example.

Do you think we should remove all descriptions to simply have "Power flag" for all of them ? I think this is nice on Earth* or GND* symbols to keep them because this explain the initial expected difference between the symbols.

**Comment by evanshultz** [comment]
Since there really is nothing more than the symbol name to differentiate them, and the symbol name is inclusive of the symbol purpose, I'm fine with a common description for all power flags.

For grounds I think a little more description can be kept since the symbol shape is different, the symbol name isn't always obvious, and we can point out the common usage of that symbol in the description. So yes, I think we're in agreement.

Even if there's more we'd like to do I'm OK to merge this since the purpose of the PR is fulfilled.

**Comment by myfreescalewebpage** [comment]
I agree with you.

@JacobEFO can you apply the above comment to complete the PR ? Thanks.

Joel

**Comment by JacobEFO** [comment]
> I agree with you.
> 
> @JacobEFO can you apply the above comment to complete the PR ? Thanks.
> 
> Joel

Absolutely. I'll set 'Power flag' as the only description for all power port symbols except for GND/EARTH.

**Comment by myfreescalewebpage** [comment]
Thanks @JacobEFO no more comment to do on this PR, merging.

**Pull request merged**
