### PR TITLE
add MAX16050/MAX16051 voltage monitors/sequencer

### PR DESCRIPTION
**Pull request by hvraven**
This adds [MAX16050 and MAX16051](https://datasheets.maximintegrated.com/en/ds/MAX16050-MAX16051.pdf) voltage monitors and sequencers. I put them in `Power_Supervisor`, please correct me if it should go in another power sublibrary.

It requires another QFN-28 variant found in https://github.com/KiCad/kicad-footprints/pull/1759 and https://github.com/pointhi/kicad-footprint-generator/pull/406.

Some questions about the pin layout: I've separated the pins for the individual control (SET, OUT and DISC) based on input and output. For layouting I think it would make more sense to keep them together as they usually all go towards the same power supply circuit. Is that ok in this application? Then I would like to redesign them before they get merged.

Screenshot_20190731_215132
Screenshot_20190731_215325

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by lorem-ipsum** [comment]
Also I did just realise that many of the outputs should be changed to open collectors. Will do this once I know how to position the pins.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

MAX16050
- [ ] Name of the device should be "MAX16050xTI"

MAX16051
- [ ] Name of the device should be "MAX16051xTI"

For both devices:
- [ ] Footprint filter should be `QFN*1EP*4x4mm*P0.4mm*`
- [ ] OUTx, REM, OV_OUT and RESET should be Open Collector
- [ ] DELAY, TIMEOUT and ABP should be Passive

I'm surprised the footprint has been accepted, it should be TQFP it is clearly indicated in the Maxim spec, not QFP... @evanshultz ?

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

thanks for the review. I've integrated your feedback and rebased against the current master.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
There is a missing `$` on line 69 of the dcm file and thus the library can't be opened.
Joel

Capture

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum ping!

**Comment by myfreescalewebpage** [comment]
@hvraven ping!

**Comment by myfreescalewebpage** [comment]
@hvraven ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by hvraven** [comment]
Hi @myfreescalewebpage ,

sorry for the long time off, is fixed now.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
