### PR TITLE
Add shield pin to Wuerth_7499010121A

### PR DESCRIPTION
**Pull request by cp-aquila**
Add shield pin to Wuerth_7499010121A

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

grafik

* Related https://github.com/KiCad/kicad-footprints/pull/1390
* https://katalog.we-online.de/pbs/datasheet/7499010121A.pdf
* I checked with the multimeter if Pin8 is connected to shield pins, it is not

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@DanSGiesbrecht have you still time to review this PR ? Thanks, Joel

**Comment by evanshultz** [comment]
There is still a problem: the footprint has no corresponding SH pin(s)!

Footprint:
image

The pads inline with the body are NPTHs. So even if this pin is added it won't have anything on the footprint to connect to.

From the [datasheet](https://katalog.we-online.de/pbs/datasheet/7499010121A.pdf), I can see pin 8 looks like it might be a ground. Does anyone know if pin 8 is connected to the metal body or if it is a separate pin (which is added here)?
image

Contrast with this one:
image

That uses this symbol:
image

**Comment by cp-aquila** [comment]
Hi,
there is a PR for the footprint pending: https://github.com/KiCad/kicad-footprints/pull/1390 which adds the pins.
This how it looks when soldered: 
grafik

Those two pins are part of the metal enclosure, so according to S3.7 they are shield-pads.
However, they are **not** connected to anything else.
So Pin8 is electrically not the same as those pins.

**Comment by cp-aquila** [comment]
Here is another picture of the connector. The metal enclosure has some tabs that connect the sides of the RJ45 plug
grafik

**Comment by evanshultz** [comment]
@cp-aquila 
Thanks! I didn't notice there was already a FP correction.

I merged that so this should be good to go. However, could you move the SH pin to the bottom? Since it will likely connect to ground that gives the SH pin a straight shot to a ground symbol.

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
