### PR TITLE
Add Fiber Optic Rx/Tx AFBR-1624Z AFBR-2624Z

### PR DESCRIPTION
**Pull request by vk6677**
Add Fiber Optic Rx/Tx AFBR-1624Z AFBR-2624Z

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

please provide screenshots and sign the license agreement for your contribution. Also please have a look at the output of our automatic (continuous integration) check scripts. They check several aspects of the KiCAD library conventions that we require any contribution to adhere to. You can find the current KLC version there: http://kicad-pcb.org/libraries/klc/

Best,
JAN

**Comment by Misca1234** [comment]
The footprint specified does not exists and I can not find a pull request for 
OptoDevice:Broadcom_AFBR-1624Z
or
OptoDevice:Broadcom_AFBR-2624Z

The datasheet link should be
AFBR-1624Z: https://docs.broadcom.com/docs/AV02-4369EN
AFBR-2624Z https://docs.broadcom.com/docs/AV02-4369EN

**Comment by Misca1234** [comment]
If you replace your FP filter with 
Broadcom?AFBR?16xxZ*

The footprints are in this push
https://github.com/KiCad/kicad-footprints/pull/406

**Comment by antoniovazquezblanco** [comment]
Ping @vk6677!

**Comment by Misca1234** [comment]
@antoniovazquezblanco 
If he is not interested any more I will take over the push

**Comment by Misca1234** [comment]
Over taken
https://github.com/KiCad/kicad-symbols/pull/1264

**Pull request closed without merging**
