### PR TITLE
Transferred memory.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR splits the `memory.lib` library into:

- EEPROM
- Flash
- NVRAM (FRAM / MRAM)
- RAM

There libraries need a lot of work. If there is nothing critical that anyone can see, please merge and we can raise an issue to fix.

### CODE REVIEW

**Comment by poeschlr** [comment]
Do we have a script that can at least change the Housings_xxx lib name to Package_xxx and Pitch -> P?
This should repair most footprint associations.

**Comment by SchrodingersGat** [comment]
Yep, I'll run that later on. Probably not until Monday, I'm away all weekend

**Comment by SchrodingersGat** [comment]
@poeschlr the incorrect footprint library names have been fixed. Ok to merge?

**Comment by poeschlr** [comment]
I think this is ok for now. Any further fixes can be made later on.

**Pull request merged**
