### PR TITLE
Added TUSB4020BI

### PR DESCRIPTION
**Pull request by jstjst**
Added symbol for TUSB4020BI USB Hub
http://www.ti.com/lit/ds/symlink/tusb4020bi.pdf
Used the TUSB4041I symbol as a template
grafik

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jstjst** [comment]
I will create the footprint soon

**Comment by poeschlr** [comment]
If you create the footprint i would suggest to use our scripts: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_DFN_QFN

**Comment by poeschlr** [comment]
For the future please use a dedicated branch for each of your contributions and base that branch on the current git master of the official repo.
to do that you would need to add this repo as a second online repo:
`git remote add upstream git@github.com:KiCad/kicad-symbols.git`

after you have done that you can create a new synced up branch with the following commands:
```
git fetch upstream
git checkout upstream/master
git checkout -b new_branch_name
git push --set-upstream origin new_branch_name
```

after that you can do your changes normally. just base your pull request on that branch instead of your master branch (should be already the suggested branch if you start the web application)

**Comment by poeschlr** [comment]
@jstjst did you create the footprint? If so could you link to its pull request from here?

**Comment by myfreescalewebpage** [comment]
Hi @jstjst , thanks for contributing,

A few comments I have during my review:

- [ ] Pin name position offset should be 20mil (see travis output)
- [ ] Captial letters is good for the description, suggested `Two-Port USB 2.0 Hub`
- [ ] Pins length should be 100mil (symbol<100pins)
- [ ] Pin 24 (USB_R1) type should be Passive
- [ ] Pin 9 (USB_VBUS) should be grouped with pins 26/27
- [ ] RSVD pins must be moved on the outline box of the symbol, as shown below

capture

- [ ] RSVD pins type should be "Not Connected"
- [ ] I don't think the position of the pins is really good to get an easy wiring on the schematic. i want to propose crystal in bottom left corner with control input pins, upstream USB in top left corner, and moving downstream port 2 down so there is more room between downstream ports. What do you think ?

As required by Rene, have you got a look to submit the footprint ?

Can you also fix the branch conflict ? Thanks.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @jstjst are you still alive on this subject ? Thanks.

**Comment by jstjst** [comment]
Hi @myfreescalewebpage ,
sorry for the late response, the project got delayed by other things, but I'm back on it.
I will look over the symbol and also create the footprint in near future.
Cheers,
Jonas

**Comment by jstjst** [comment]
>     * I don't think the position of the pins is really good to get an easy wiring on the schematic. i want to propose crystal in bottom left corner with control input pins, upstream USB in top left corner, and moving downstream port 2 down so there is more room between downstream ports. What do you think ?

I agree with that, but when I move the downstream port 2 down, where should I put the RVSD pins?

**Comment by myfreescalewebpage** [comment]
Thanks for your response. RSVD pin are not visible and you can place them where you want, this is not very important.

**Comment by myfreescalewebpage** [comment]
@jstjst I see you are working on this but something is not correct with your git, the diff only show a modification of one fp filter now and we have no more your addition, please look at https://github.com/KiCad/kicad-symbols/pull/801/files.

Joel

**Comment by jstjst** [comment]
Yes something went wrong with my git, so I resubmitted the PR.

**Pull request closed without merging**
