### PR TITLE
Add UCC256301

### PR DESCRIPTION
**Pull request by phamhuuhuyhoang**
Added schematic symbol for the UCC256301 Hybrid hysteretic LLC resonant controller. Temporarily using the SOIC 16 footpint. The actual package has pin 2 and 13 missing for creepage and clearance when used at high voltages.
[Datasheet](https://www.ti.com/lit/ds/symlink/ucc256301.pdf)
UCC256301symbol

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks and welcome!

I'm thinking a few pin placement adjustments will help:
- Move RVCC to the top.
- Maybe move pins 6 and 7 to the left side.
- Space out the high-side pins to all a the bootstrap cap to fit there.

Do you have a schematic section you can share showing how you've wired up this symbol? If it's buried in the power circuitry or the power and controller circuitry are different would affect which pins locations might be best.

You will need to make the correct footprint for this part. It can be generated using the script at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO. Or you may modify an existing footprint. Instructions on library requirements are at https://kicad-pcb.org/libraries/klc/ and for skipped pins specifically see https://kicad-pcb.org/libraries/klc/F2.4/.

**Comment by phamhuuhuyhoang** [comment]
pin placements have been updated
image

I have started a pull request to add the footprint to the kicad-footprint library: 
https://github.com/KiCad/kicad-footprints/pull/2298

**Comment by evanshultz** [comment]
These changes all looks OK to me, unless you can share part of a schematic using this symbol so we can see it in context. Once the footprint is merged, this can be merged as well if you update the symbol to use that footprint.

**Comment by evanshultz** [comment]
@phamhuuhuyhoang 
Can you please update this symbol to use the footprint you made? I apologize for losing track of the footprint PR but it's not merged.

**Comment by phamhuuhuyhoang** [comment]
symbol updated to use the correct footprint

**Comment by evanshultz** [comment]
@phamhuuhuyhoang 
This all looks good. Sorry for the long delay. We all appreciate you taking the time to contribute to the KiCad library, and even with the slow response I'm happy you were able to come back to this and hopefully you will contribute more in the future.

**Pull request merged**
