### PR TITLE
Transfer dc-dc

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Moved dc-dc library across

### CODE REVIEW

**Comment by poeschlr** [comment]
Isn't @antoniovazquezblanco working on this in PR https://github.com/KiCad/kicad-symbols/pull/17?

**Comment by antoniovazquezblanco** [comment]
I will get back to it in a couple of weeks. I will pick on wherever you leave it.

**Comment by SchrodingersGat** [comment]
I believe he was working on the Converter_DCDC lib which is standalone converter modules. The existing dc-dc lib is for switchmode regulators. However the dc-dc lib did also contain some which should be moved into Converter_DC-DC

**Comment by antoniovazquezblanco** [comment]
I see two different libs in your comment: `Converter_DCDC` and `Converter_DC-DC`. Shouldn't we avoid this?

**Comment by SchrodingersGat** [comment]
Yes, we should. Thanks for pointing that out. I have update my comment.

**Comment by antoniovazquezblanco** [comment]
Given your preferred name is `Converter_DC-DC` should I open issues to rename footprint libraries to that from the current `Converter_DCDC` and `Converter_ACDC` names?

**Comment by SchrodingersGat** [comment]
@antoniovazquezblanco given that they are already in place, I will rename the file in my PR here. My preference is not that strong. We will need to rename the 3D models though - https://github.com/KiCad/kicad-packages3D/tree/master/Converters_DCDC_ACDC.3dshapes

**Comment by antoniovazquezblanco** [comment]
My preference would be to regenerate the files with the script. I am also supposed to do that but again, not until I meet my work deadline.

**Comment by poeschlr** [comment]
@SchrodingersGat could you merge the sym lib table? This merge is a bit much for the web interface.

**Comment by SchrodingersGat** [comment]
Finally had a chance to fix conflicts

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
