### PR TITLE
Various symbol fixes

### PR DESCRIPTION
**Pull request by evanshultz**
Addresses most, but not all, of the issues noted at https://github.com/KiCad/kicad-symbols/issues/272. The remaining ones are for MCUs and memory, which I understand will be fixed by Bob's scripts.

The only datasheets possible necessary would seem to be for the dual FETs:
- https://www.infineon.com/dgdl/irf7343pbf.pdf?fileId=5546d462533600a4015355f68c1a1b73
- http://www.irf.com/product-info/datasheets/data/irf7309ipbf.pdf
- http://www.onsemi.com/pub/Collateral/FDS9934C-D.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Oh. And here's the symbol for ADS128D818: 
image

**Comment by poeschlr** [comment]
This seems to have some conflicts. I assume it conflicts with the stuff by @bobc.

Also why does CLA say you did not sign? (I am sure you already signed it.)

**Comment by evanshultz** [comment]
@poeschlr 
Branch conflicts fixed. I also realized that one symbol (ADC128D818, formerly ADC128D818) had the wrong name, wrong pin names, wrong description (according to the linked datasheet) and my fixes for it didn't get committed so I corrected that. Here is the symbol image:
image

Not sure about CLA... I did sign it and it shows as signed for me above.

**Comment by evanshultz** [comment]
@poeschlr 
Are you able to review this now? I think there's a good number of fixes here which would improve the v5 library.

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 
Branch conflicts fixed. Again. I think there are good fixes in here that I'd like to see in v5. Can I get a review, please?

Note that Analog_ADC.lib and Transistor_FET.lib are giving me issues because this PR is too old. I'll make a new PR for the fixes to them.

**Comment by jkriege2** [comment]
Please fix the merge conflict!

Thanks,
JAN

**Comment by jkriege2** [comment]
Also I don't really understand the "Files changed" result: That contains several fixes done by bobc already (e.g. creation of Memory_EPROM.lib), i.e. already present in the master, still they are shown ad changes compared to the master??? Maybe that will be fixed after the merge conflict is fixed ... let's see.

I checked out this branch and fixed the one merge conflict ... to me it seems good and I found only a few minor things:

1. The HV9961NG-G datasheet link does not work (I think Supertex was bought by microchip and the PDF-links changed). The working link would be http://ww1.microchip.com/downloads/en/DeviceDoc/20005588A.pdf
2. I think http://ww1.microchip.com/downloads/en/DeviceDoc/20005588A.pdf is a candidate for having pin-count in FPFIlter and no NC-pins in the symbol (there seem to be more NCs than actual pins). Also could you move the power-pin to the top?
3. Please have a look at PCF8563 ... The FPFilters are a bit messy. From the datasheet they should be `SOIC*3.9x4.9mm*P1.27mm*` and `MSOP*3x3mm*P0.65mm*`. Also there should be a second symbol for  the HVSON10-package from the datasheet (but that could be for a later PR). the package could be `VSON-10-1EP_3x3mm_P0.5mm_EP1.65x2.4mm`
4. DS1602/DS1302 are missing FPFilters `SOIC*3.9x4.9mm*P1.27mm*` and `DIP*W7.62mm*`
5. DS1307+ has misformed FPFilters. they should be `SOIC*3.9x4.9mm*P1.27mm*` and `DIP*W7.62mm*`

As said, the rest looks good. If you could fix these, I will merge!

Thanks,
JAN

**Comment by poeschlr** [comment]
The files changed thing tells you what changed relative to when this branch was created, not relative to what is in master.

**Comment by jkriege2** [comment]
Hmmm  ... when there are no conflicts it should show the changes to the CURRENt master (at least that's how I understodd it so far) ... am I wrong, or is it really a problem with the conflicts??? ... We'll see when the conflicts are fixed anyways ;-)

**Comment by bobc** [comment]
I think @poeschlr  is correct. Only if you rebase the PR will the other changes from master not appear as changes.

In fact, if you remove other changes after resolving conflict to try to "clean" the diff it will revert those other changes on master. We have had this happen a few times already, changes have been lost because a PR did not include other changes from master.

**Comment by evanshultz** [comment]
How incredibly annoying... Branch conflicts are fixed now. Again.

I also made the changes you suggested, @jkriege2. Thanks for reviewing! Changes:
1. Fixed all HVxxxx Supertex datasheet URLs to Microchip except HV9972. I can only find a Mouser datasheet and it's not listed on Microchip's website.
1. For HV9961LG the NC and "useful" pins are equal in quantity and I left it alone. Updated all HVxxx symbols to put power pins on top and use 20mil pin text offset. HV9967 says the various ground pins are to be connected together, even the thermal pad, so I stacked them.
1. Split the existing symbol by package, and left the SON symbol out.
1. Fixed. This was missing a DCM entry and I added it.
1. Also fixed and simplified since both packages were shown. And also added a DCM entry.

While I don't mind fixing up a few things we find now, I'd prefer to merge this quickly. My intent was to fix the issues turned up in another PR's Travis output and not overhaul new things. If there are other small things I will be glad to do them, but I want to make the cut for v5 with this PR.

**Comment by evanshultz** [comment]
And added MC1455 (https://www.onsemi.com/pub/Collateral/MC1455-D.PDF) as ALIAS of NE555 (which was already an ALIAS) which I think is not controversial and won't cause any addition re-review.

I'm done here. Please review and merge. Thanks!

**Comment by jkriege2** [comment]
OK!

thanks for the work you put in ... I don't see anything else ;-) ...

JAN

**Pull request merged**
