### PR TITLE
Adding 5P49V6965

### PR DESCRIPTION
**Pull request by ki5libs**
Adding 5P49V6965
[Datasheet](https://www.idt.com/document/dst/5p49v6965-datasheet)

5P49V6965_new

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cp-aquila** [comment]
Hi, 
just two points from a quick look:
- Pin24 (OUT0_SEL_I2CB) is an output and strapping pin. I would rather place it on the right side.
- SCL should be a input pin
- The symbol is quite large, how about putting the VDD pins next to each other?

**Comment by ki5libs** [comment]
Hi @cp-aquila 
- pin 24 moved to the right side. I leave `Bidirectional` type according to datasheet (input/output);
- SCL type changed to `Input`, SDA type changed to `Bidirectional` respectively;
- symbol is squeezed in horizontal plane.

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs , thanks for contributing,

A few comments I have during my review:

- [ ] Pin offset should be 20mil (see travis error)
- [ ] Footprint should be `Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm`
- [ ] Pin length should be 100mil

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage

thanks for review. I've fixed all of your remarks

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment, merging.

**Pull request merged**
