### PR TITLE
Added FPF2006

### PR DESCRIPTION
**Pull request by Misaka0x2730**
Added FPF2006 - 100mA Current Limited Load Switch.
Datasheet: https://www.onsemi.com/pub/Collateral/FPF2001-D.pdf
image
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @Misaka0x2730 , it is better to use a white theme for the screenshots, this makes things more clear..

A good way to do, is to edit the first message and reupload a new picture..

**Comment by Misaka0x2730** [comment]
@aris-kimi Thank for a tip, but I think it doesn't really matter))
And white theme literally burns my eyes.

**Comment by myfreescalewebpage** [comment]
Hi @Misaka0x2730 , thanks for contributing,

A few comments I have during my review:

- [ ] I suggest to create FPF2000 and to have the following references as aliases
- [ ] Description should be enhanced with current limit for example, to make the differences between the symbol of the family. It should also be terminated by the package name "SOT-353"
- [ ] Pin length must be 100mil for this symbol (<100pins)
- [ ] Name of pin 1 is VOUT
- [ ] Name of pin 5 is VIN
- [ ] I suggest to have FLAG on the right has shown in the datasheet, and to make a symbol more compact. Proposition below.

Capture

Cheers,
Joel

**Comment by Misaka0x2730** [comment]
@myfreescalewebpage Thank you! 
I completed changes in accordance with your comments, but your last comment violating S4.2, can I just ignore this rule?

**Comment by myfreescalewebpage** [comment]
Hello @Misaka0x2730 
Thanks for the fixes.
Yes for regulators S4.2 is normal.
Why keeping FLAGB on the left ? We usually put as shown on the datasheet, this is preferable because most user will do it.
Joel

**Comment by Misaka0x2730** [comment]
@myfreescalewebpage Oops, sorry, my fault, fixed.

**Comment by myfreescalewebpage** [comment]
No worries, thanks.

**Pull request merged**
