### PR TITLE
BQ78350

### PR DESCRIPTION
**Pull request by jneiva08**
Did the following changes:
* Added alias for BQ78350-R1
* Updated description
* Fix KLC S3.6 and S4.1
* Symbol is a little smaller

Datasheets BQ78350: http://www.ti.com/lit/ds/symlink/bq78350.pdf
Datasheets BQ78350-R1: http://www.ti.com/lit/ds/symlink/bq78350-r1.pdf

Symbol:
bq78

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
Hi @jneiva08 

### Changes that can be merged:

I do have one suggestion: Consider adding more keywords than just `BMS` (e.g. `battery`, `management`, `Li-Ion`, `Gauge`, `controller`).

Moving the RefDes, part name and package label looks good, as does changing the pin name offset from 40 to the recommended 20.

---

### Changes that can't be merged right now:
Unfortunately, changing the symbol pin positions breaks existing design compatibility. This improvement - while valid - cannot be merged at this time. It will likely have to wait until the release of **KiCad 5.1**.

---

If you would like to have the acceptable improvements merged, you can revert the pin positions. Otherwise, this PR can wait until such time that it's deemed acceptable to merge. @poeschlr , what do you think?

**Comment by antoniovazquezblanco** [comment]
Offtopic: I use the 'In review' label to filter issues. The intended use is to tag the issue as long as it is assigned to someone. Given that you already started the review I would not remove the tag unless you abandon the review and mark it as pending review. Sorry for the interruption :)

**Comment by DanSGiesbrecht** [comment]
@antoniovazquezblanco thanks for the information! What's the difference between assigning and using the `in review` label?

**Comment by evanshultz** [comment]
A couple notes about pin names:
1. VEN should be Open Collector.
1. This appears to be an I2C master device so should SCL be Output type? I vote yes.

**Comment by antoniovazquezblanco** [comment]
All the comments seem to have been addressed here.

I would like to ask @poeschlr to address if this would be acceptable enough to be merged in 5.1.0 or if should be postponed to 6.0.0 due to compatibility changes (pin positions have been changed due to symbol downsizing).

**Comment by poeschlr** [comment]
I would prefer the symbols to stay as stable as possible (with regards to pin positions)

But if somebody can give a good reason as to why this change is necessary then we can include it.
A good first step would be to add a screenshot of the old symbol such that we can discuss the benefits of the new one more easily.

**Comment by jneiva08** [comment]
This is the actual symbol:
bq78350_actual

This is the new symbol:
bq78350_pr
Also adds the following:
* Added alias for BQ78350-R1
* Updated description
* Fix KLC S3.6 and S4.1

**Comment by DanSGiesbrecht** [comment]
Closed/reopened to re-initiate CLA-Assistant.

**Comment by DanSGiesbrecht** [comment]
I think this is a good improvement. Users of the libraries would notice the change, unlike something like a pin-swap, for example.

**Comment by poeschlr** [comment]
My decision stands. There are not enough benefits from this change to allow it in. So please revert the pin positions to what they where before. (or we need to leave this for after 5.1)

**Comment by DanSGiesbrecht** [comment]
Sounds good. I'll modify the milestone to `6.0.0` for now. @jneiva08 , if you'd like to break this into two PRs, feel free.

**Comment by myfreescalewebpage** [comment]
@DanSGiesbrecht what is the status here ? I can continue the review if you want

**Comment by myfreescalewebpage** [comment]
@jneiva08 I try to continue the review:

- [ ] Name should be BQ78350DBT and alias "BQ78350DBT-R1"
- [ ] Descriptions of the symbol and the alias should be terminated by the package name, please add `, TSSOP-30` at the end
- [ ] Pins 11 and 13 should be Bidirectional

Else looks good
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage, have made the changes requested

**Comment by myfreescalewebpage** [comment]
Thanks for this quick fix on a so old pull request !! Just want to merge it now :)

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
