### PR TITLE
Interface/AD9910: split AVDD_1V8 by datasheet

### PR DESCRIPTION
**Pull request by lorem-ipsum**
the [datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/AD9910.pdf) recommends different regulators for the different analog 1.8V power supplies (see page 46 of the datasheet). Split the stacked power supply pins as suggested by the datasheet.

Sorry for not spotting while creating yesterdays PR.
ad9910

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Good catch! What about moving pin 6 to the right so it's closer to the digital supply pins?

**Comment by lorem-ipsum** [comment]
Makes sense, I moved the analog pins around, now the 1V8 are in the centre and 3V3 on the left. Pin 6 is now next to digital 1V8.

**Comment by evanshultz** [comment]
Thanks! Can you post a new screenshot for historical reasons?

**Comment by lorem-ipsum** [comment]
screenshot_20180517_231608

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
