### PR TITLE
Pressure sensor MS5607

### PR DESCRIPTION
**Pull request by kajusK**
Added pressure sensor

http://www.farnell.com/datasheets/1756127.pdf (couldn't find datasheed directly on manufacturer website...)

2019-02-07-204648_1920x1080_scrot

### CODE REVIEW

**Comment by kajusK** [comment]
Hi @myfreescalewebpage,

Updated as requested, originally I thought separating the PS pin from others could make the schematic using this part a bit better looking, but your suggestions looks better.

**Comment by myfreescalewebpage** [comment]
Hi @kajusK thanks for the fixes. I'm sorry I have made a small error in the previous comment during my review, pin 7 is Bidirectional, not pin 8 (this one is an Input). Can four fix this, then this is ready to be merged. Thanks, Joel

**Comment by kajusK** [comment]
I should have checked that before changing, error on both sides :) Fixed.

**Comment by myfreescalewebpage** [comment]
No worries, thanks for this correction, merging your PR !

**Pull request merged**
