### PR TITLE
Add Schaffner RN102 series common mode chokes

### PR DESCRIPTION
**Pull request by yankee14**
Add Schaffner RN102 series common mode chokes.

Datasheet: https://www.schaffner.com/products/download/product/datasheet/rn-series-common-mode-chokes-new/

I was pleasantly surprised to find that the footprint already exists for this series. Maybe this PR should be denied, in favor of the generic common mode chokes under Device?

RN102-0

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by cpresser** [comment]
Making a full specified symbol is a perfectly fine addition.

I am not quite sure about the name. I am thinking about adding a prefix perhaps like `Choke_RN102-0.3-02-12M`. Currently nothing is prefixed in that library. 
Contents so far in `Filter.lib` are SAW and AC-line-filters, nothing like this (common-mode-choke). But on the other hand I could not find a library that is a better fit for this addition.
What do you think?

**Comment by yankee14** [comment]
@cpresser that sounds good to me! I went ahead and made the naming change as you suggested.

**Comment by myfreescalewebpage** [comment]
Hello @yankee14 

I propose to follow naming used on footprint, starting the part name with "Choke_Schaffner_RN102...".

Else no comment to do. Please tell me what you think.

Joel

**Comment by cpresser** [comment]
Perhaps even `Choke_CommonMode_Schaffner_RN102...`. Chokes that are not common mode do exist.
On the other hand, that information is already in the description and the keywords.
But more prefix makes it simpler to split the library in the future assuming there are more common-mode-choke additions.

**Comment by myfreescalewebpage** [comment]
There is already RN102 which seems to be the part name so I suppose not common mode will have a different one.

**Comment by yankee14** [comment]
Hi @cpresser and @myfreescalewebpage , would you like `Choke_Schaffner_RN102` or `Choke_CommonMode_Schaffner_RN102`?

**Comment by myfreescalewebpage** [comment]
Footprint has "Choke_Schaffner_RN102" so I prefer having the same logic.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
