### PR TITLE
added NCP551

### PR DESCRIPTION
**Pull request by Knochi**
ON-Semi NCP551 series low dropout regulator
added common voltage versions 1.5, 1.8, 3.3 and 5.0V

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)

Regulator_Linear_NCP551SN50T1G

### CODE REVIEW

**Review by chschlue — CHANGES_REQUESTED** [review]
Please remove T1G packaging suffix and move NC pin onto the symbol's outline.

**Comment by Knochi** [comment]
> 
> 
> Please remove T1G packaging suffix and move NC pin onto the symbol's outline.

What do you mean by "onto the symbols outline" it is on the outline.

**Comment by chschlue** [comment]
No, it's not. It's 100 mils below.

If you were to draw a wire from GND to the right, you'd connect it. That's why NC pins have to be within the body.

Also, please remove automotive variants. Missed those before.

**Comment by Knochi** [comment]
oh ok.. didn't get that the have to be within the body.. never saw that before
Am 14. März 2020, 19:32 +0100 schrieb Christian Schlüter <notifications@github.com>:

**Comment by koenraad-voltza** [comment]
> Also, please remove automotive variants. Missed those before.

Why? I don't see anything in the KLC against automotive MPNs, and the base part number is different. Maybe I missed something?

**Comment by chschlue** [comment]
That's to avoid bloat as per [S2.2](https://kicad-pcb.org/libraries/klc/S2.2/).
In this case we cannot reasonably use wildcards (who would search for `NCx551`?)
We don't have `SNx4*` symbols for `SN54*` and `SN74*` parts for that reason.

**Pull request closed without merging**
