### PR TITLE
TLC5957 & TLC5951

### PR DESCRIPTION
**Pull request by s-light**
adding 
- [TLC5951](http://www.ti.com/lit/ds/symlink/tlc5951.pdf) (24-Channel, 12-Bit PWM LED Driver)
- [TLC5957](http://www.ti.com/lit/ds/symlink/tlc5957.pdf) (48-Channel, 16-Bit ES-PWM LED Driver)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
  - [TLC5951](http://www.ti.com/lit/ds/symlink/tlc5951.pdf)
  - [TLC5957](http://www.ti.com/lit/ds/symlink/tlc5957.pdf)
- [x] An example screenshot image is very helpful
image
image
image
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
  - HTSSOP-38-1EP* https://github.com/KiCad/kicad-footprints/pull/1029
  - *QFP*40 → blocked by https://github.com/KiCad/kicad-footprints/issues/606#issuecomment-431347500
  -  QFN*56 EP5.6 → https://github.com/KiCad/kicad-footprints/pull/1031
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @s-light, thanks for contributing,

A few comments I have during my review:

TLC5951DAP:
- [ ] The device is HTSSOP, please remove "QFN-40" at the end of the description
- [ ] Footprint filter should be `HTSSOP*1EP*6.1x12.5mm*P0.65mm*`
- [ ] CLK pins (2/37/5/4/6) should have default Graphic Style (Line)
- [ ] IREF is not really a Power pin, should be moved to the left of the symbol

TLC5951RHA:
- [ ] The device is Texas VQFN, please remove "HTSSOP-38" at the end of the description and replace QFN-40 with "Texas S-PVQFN-N40"
- [ ] Footprint filter should be `Texas*S*PVQFN*` (only one filter)
- [ ] CLK pins (27/24/30/29/31) should have default Graphic Style (Line)
- [ ] IREF is not really a Power pin, should be moved to the left of the symbol.

TLC5951RTA:
- [ ] The device is Texas VQFN, please remove "HTSSOP-38" at the end of the description and replace QFN-40 with "Texas S-PVQFN-N40"
- [ ] Footprint filter should be `Texas*S*PVQFN*` (only one filter)

TLC5957RTQ:
- [ ] Footprint filter should be `QFN*1EP*8x8mm*P0.5mm*`
- [ ] CLK pins (28/29) should have default Graphic Style (Line)
- [ ] IREF is not really a Power pin, should be moved to the left of the symbol.

Can you also fix the branch conflict ? I think this is the reason why Travis fails...

Cheers,
Joel

**Comment by s-light** [comment]
thanks Joel for reviewing.
i will fix this the next days! :-)

**Comment by s-light** [comment]
should be all fine now ?! :-)

**Comment by myfreescalewebpage** [comment]
Hi @s-light looks really great, good job!

For the TLC5957RTQ symbol, please keep IREFGND on the bottom of the symbol. I was only asking IREF on the left. Also,  I like how you have placed it on the other symbols, not in the corner, but not to much high, so it's possible to add resistor to the ground easily. For this device I propose the following modification:

capture

No comment on the other devices.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
> Why did i move it then?

lol

> so i thought 'makes sens to keep them together...

Yes but we recommend GND Power pin at the bottom. It is also consistent with the proposed schematic on the first page of the datasheet :)

Anyway, great job from you on this PR, no more comments to do and merging your contribution.

Thanks
Joel

**Pull request merged**
