### PR TITLE
Add Infineon Merus audio amplifier symbols

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.infineon.com/dgdl/Infineon-MA12040-DS-v01_00-EN.pdf?fileId=5546d46264a8de7e0164b7467a3d617c
https://www.infineon.com/dgdl/Infineon-MA12070-DS-v01_00-EN.pdf?fileId=5546d46264a8de7e0164b750002861a5
image

https://www.infineon.com/dgdl/Infineon-MA12040P-DS-v01_00-EN.pdf?fileId=5546d46264a8de7e0164b74ff0e561a2
 https://www.infineon.com/dgdl/Infineon-MA12070P-DS-v01_00-EN.pdf?fileId=5546d46264a8de7e0164b761f2f261e4
image

Only difference in the symbols are the pin names on pins 21-24.

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1666

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
CI errors: The NC pins are noted as going to DVDD, so I made them actual pins in case they're connected external (for copper coverage?). And the CLK pin (also called CLKIO in the pin table) is a bidirectional pin.

**Comment by evanshultz** [comment]
Geesh... Any help here? When master is changed adjacent to my changes, GH barfs. I can merge master into this branch cleanly but that didn't fix it. Then I tried manually adding the missing part entry and still issues. Sigh.

**Comment by chschlue** [comment]
Done.

Git supports different merge algorithms. Has anyone ever experimented if there's a better one for the textual databases we're dealing with here as opposed to actual code?

**Comment by evanshultz** [comment]
@chschlue 
Thanks! I use GitHub Desktop and I don't know what algorithm it uses. I assume you used a command line; can you help me out with the command that you used that works?

**Comment by chschlue** [comment]
I actually used the "resolve conflicts" function of GH's web UI, removed the conflict markers (there was no actual conflict after all), moved LME49600 up to restore alphabetical order and committed.
That's the same as `git merge master` followed by resolving conflicts manually (by text editor) followed by `git commit` on the command line.
I know of no fully automated way of doing that, but it's curious that GH desktop lets you merge master into your PR branch cleanly while GH web doesn't let you merge your branch into master cleanly.
I've never used GH desktop but I guess GH web uses a more cautious [strategy](https://git-scm.com/docs/merge-strategies) for merging PRs than GH desktop (or plain git) uses to merge branches by default.

This is usually fine. For code, if one branch adds lines somewhere in the middle of a function while another one removes adjacent lines, for example, it's probably an actual conflict requiring human intervention.
Here, that kind of change is usually benign but git simply can't tell the difference.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz some comments for this PR:

MA12040
- [ ] PVDD should be separated in two stacked blocks
- [ ] Name of pin 32 is "CLKIO"
- [ ] OUTxx pins should be Output

MA12040P
- [ ] PVDD should be separated in two stacked blocks
- [ ] CLK is Input only
- [ ] OUTxx pins should be Output

Joel

**Comment by evanshultz** [comment]
Thanks for looking!

- PVDD are not shown as needing unique decoupling, so I guess you mean since the pairs of pins are separated on the IC isn't nice to make separate pin stacks. Done.
- Interestingly, the pinout on page 4 show CLK for MA12040. I changed it.

**Comment by evanshultz** [comment]
Also, the NC pins are now set to Passive type. I don't know what I was thinking. They're discrete pins on the symbol so that the user can connect one or both of them to the DVDD supply if they so desire, or use an NC pin instead of the actual DVDD pin (though this has it's own issue as the DVDD pin is Power Input type), but the NC pins can also be left floating as well. Flexibility.

**Comment by myfreescalewebpage** [comment]
Yes not bad, even if travis is not happy because of the NC pins which in reality connected on this device...

**Pull request merged**
