### PR TITLE
add ADR420-series voltage references in MSOP-8

### PR DESCRIPTION
**Pull request by aewallin**
https://www.analog.com/media/en/technical-documentation/data-sheets/adr420_421_423_425.pdf

Voltage reference with 4 different variants for 2.048, 2.5, 3.0 and 5.0 V.
MSOP-8 package (also available in SOIC-8)
adr42xarmz

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
revised symbol:
adr42xarmz

**Comment by aewallin** [comment]
Thanks for the review. Changes made as suggested.
adr420armz

**Comment by myfreescalewebpage** [comment]
Hi @aewallin, thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter should be `MSOP*3x3mm*P0.65mm*`
- [ ] Use capital letters for VIN
- [ ] Pins 3 and 7 should be added, Type Not Connected, Not Visible
- [ ] ADR421ARMZ, you can indicate "2.50V" to be more accurate

Cheers,
Joel

**Comment by aewallin** [comment]
adr420armz

**Comment by myfreescalewebpage** [comment]
Thanks. Merging.

**Pull request merged**
