### PR TITLE
Cleanup Power_Protection

### LINKED ISSUE #22: Issues with Power Protection lib
- [ ] Some symbols have off grid pins
- [ ] Footprints are linked that do no longer exist under that name

For more details see: https://travis-ci.org/KiCad/kicad-symbols/builds/311840123?utm_source=github_status&utm_medium=notification

### PR DESCRIPTION
**Pull request by gauravjuvekar**
Partially fixes #22

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work, thanks.

Is there a reason why you removed the internal drawing in TPD8F003
2017-12-26 23_00_37-symbol library editor - power_protection d__kicad_kicad-symbols_power_protectio
 ... I think that was really useful + we have internal schematics in several symbols and you even added some.

**Comment by gauravjuvekar** [comment]
@jkriege2 A few parts of the drawing were off-grid and I thought that the drawing increased the size of the symbol a lot. I'll redo it and update the PR. 

Also, is there any agreed on convention for internal drawings (beyond the draw it if it's simple and helps)? Can I replace the resistor box with the "triangle-wave" notation of a resistor?

**Comment by jkriege2** [comment]
Hmmm ... I think the drawing should follow the usual (i.e. IEC) conventions in this lib, so I would rather use a standard box-resistor ...

**Comment by gauravjuvekar** [comment]
@jkriege2 Have a look again

**Comment by gauravjuvekar** [comment]
selection_422

**Comment by jkriege2** [comment]
Hi!

the diodes should be unfilled (as per IEC standard). Could you change that?

Thanks,
JAN

**Comment by gauravjuvekar** [comment]
@jkriege2 
Should it have a line through it in its axial direction? Is there any document freely available online with symbol drawings according to IEC specifications?

**Comment by poeschlr** [comment]
A good guide is the device lib.

**Comment by gauravjuvekar** [comment]
@jkriege2 See pushed changes.

**Comment by jkriege2** [comment]
Hi!

yes there should be a line ... I found this one online: http://pcad-libs.embedders.org/rules/ref_617.pdf

Best,
JAN

**Comment by jkriege2** [comment]
Great work!

Thanks,
JAN

**Pull request merged**
