### PR TITLE
Added CHT11 as an alias to DHT11

### PR DESCRIPTION
**Pull request by Misca1234**
Added CTH11 to DHT11 as an alias
http://aosong.com/en/products-21.html

Apparently it is the same component as DHT11 as indicated on the backside of the component 
on the images on 
http://aosong.com/en/products-21.html

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @Misca1234 

I'm wondering about something: have you found the CHT11 anywhere except on the page you have indicated above ?

Is it possible that it is a mistake of the website on the reference ?

Even https://octopart.com do not know the CHT11 device...

Joel

**Comment by Misca1234** [comment]
When the first attempt to get the DHT11in (you merged the third attempt) 
I have a faint memory of the following happen, one of us sent an email to the company and asked stuff , then Aosong came back and said that the DHT11 is for the Chinese market and the CHT11 is for the non-Chinese market.
This was the start signal that fucked everything up, people found some 2+ different data sheet that could not agree on one or more measurements, one guy measured the component in real life, which of course did not match at least one of the data sheets and then it spiralled out of control.

However, every resellers, distributes, "kit makers" seems to use the designation DHT11, it is hard to find any CHT11. The only reason CHT11 is pushed to KiCad is because of the email sent to Aosong and their answer.

The confusion is immense about this one
I just stumbled on a fourth variant of the data sheet for this component
https://cdn-shop.adafruit.com/datasheets/DHT11-chinese.pdf
This one seems to agree more with the English data sheet but it is in Chinese.

I would guess the following happen.
Aosong made the DHT11 where the original Chinese data sheet was correct
The DHT11 was a seller hit
They put development resources on the DHT11 => made it smaller, but kept DHT11 as identification, no variants
Released new data sheet in English and Chinese with new measurements 
Tried to differentiate the market in an attempt to charge different in different markets by launching the DHT11 rebranded as CHT11, but no one care about the CHT11

**Comment by myfreescalewebpage** [comment]
If the manufacturer confirmed by mail this is an existing device, that's enough for me to say it's not a typo error.

No comment on the PR itself, merging.

Joel

**Comment by Misca1234** [comment]
just note, the manufactured told "us" that DHT11 is for Chinese domestic market and CTH11 for the international market, they did not confirm any measurement or so

**Pull request merged**
