### PR TITLE
Bc95

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.quectel.com/UploadImage/Downlad/Quectel_BC95_Hardware_Design_V1.3.pdf#page16

Footprint: https://github.com/KiCad/kicad-footprints/pull/1943

Screenshot:
bc95

Note: only added NC pis from 1 to 49, the other don't fit in the symbol square

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jneiva08** [comment]
Hi @gmsotavio , need to make any modifications?

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08

A few comments I have during my review:

- [ ] Footprint should be `RF_GSM:Quectel_BC95`
- [ ] Fp filter: `Quectel?BC95*`
- [ ] I have see your question about NC pin on the footprint PR. I suggest to remove all the NC pins for this symbol.
- [ ] Name of pin 15 should be uppercase ("RESET")
- [ ] Pin 38 should be Power Output
- [ ] Pin 42 should be Power Input I think because it will be connected to board GND probably in most case
- [ ] Pin 32 is duplicated, you have an unwanted "VRTC" pin on the top to be removed
- [ ] You can move a little bit USIM pin to the bottom so there is more room for RF part

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage, have made the changes requested, hope i didn't miss anything

bc95

**Comment by myfreescalewebpage** [comment]
This looks very nice, great job. Merging.

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
