### PR TITLE
Adding XUx5x and XUx7x IDT oscillators

### PR DESCRIPTION
**Pull request by ki5libs**
Adding XUx5x and XUx7x IDT oscillators
Symbol is based on Si570 symbol.
[Datasheet](https://www.idt.com/document/dst/xu-family-datasheet)

XUx5x

[Footprint PR for XUx5x](https://github.com/KiCad/kicad-footprints/pull/1919)
[Footprint PR for XUx7x](https://github.com/KiCad/kicad-footprints/pull/1918)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by ki5libs** [comment]
Hi @cpresser, both footprint PRs are merged now. Could you remove `Pending footprint` label? And, by the way, is it possible somehow for me to rerun Travis checking in such situations?

**Comment by chschlue** [comment]
You can close and reopen the PR.

**Comment by ki5libs** [comment]
Thanks

**Comment by cpresser** [comment]
I took another look at this.
The symbol looks rather big to me. Here is a comparison to another oscillator from the same lib:
image
- [ ] Is there a reason why its so big? If no, can you please shrink it?
- [x] Footprint and filter are good
- [x] Pinout and names
- [x] Aliases and Keywords
- [ ] The description should have more commas in it, its supposed to be a comma separated list

**Comment by ki5libs** [comment]
Hi, @cpresser,

thanks for you opinion. Description fixed (commas added). 
As I've written this symbol is based on Si570. So I made it the same size. But I agree, it could be shrinked. Please find this example screenshot and let me know if you think it's still not OK:
XUX_NEW

**Comment by cpresser** [comment]
Yep, the size is way better. Thanks!
Comparison-Image: image
If you would move pins 1,4 and 5 down by one grid-size I would like it even better. Then its the same as the other oscillators that have their input and output centered. The square-wave-symbol is also smaller on the reference oscillators. But thats not mandatory as its a purely stylistic choice.
- [ ] PinNamePositionOffset should be 20mil. Unsure why travis does not complain here.

**Comment by ki5libs** [comment]
@cpresser,

all changes asked by you are done. Example screenshot:
XUX_NEW2

**Comment by cpresser** [comment]
thanks!

**Pull request merged**
