### PR TITLE
add SN74LVC2T45YZP

### PR DESCRIPTION
**Pull request by dsilwa**
Signed-off-by: Dominik Sliwa <dominik@e-plum.pl>

SN74LVC2T45YZP symbol based on the symbol for SN74LVC2T45DCUR
datasheet: http://www.ti.com/lit/ds/symlink/sn74lvc2t45.pdf
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
The part is called SN74LVC2T45YZP, the R is just for T&R packaging.

**Comment by chschlue** [comment]
And the voltage regulator probably deserves its own PR.

**Comment by dsilwa** [comment]
I've removed the "R"(I've added it because the SN74LVC2T45DCUR had it) and created another PR for the LDO.

**Comment by myfreescalewebpage** [comment]
No comment to add here, merging.

**Pull request merged**
