### PR TITLE
Adding the C8051F380/1/2/3/4/5/6/7/C family (QFN32)

### PR DESCRIPTION
**Pull request by JonathSpirit**
Adding the silicon-labs "Full Speed USB Flash MCU Family" (C8051F380/1/2/3/4/5/6/7/C) in QFN32

(not sure about the footprint :/ )

https://www.silabs.com/documents/public/data-sheets/C8051F38x.pdf

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @JonathSpirit , thanks for contributing,

A few comments I have during my review:

- [ ] Package at the end of the description has not the right format. Should be "QFN-32"
- [ ] Footprint is to be completed
- [ ] Footprint filter is not correct (see other devices in the lib with the same footprint and also travis output)
- [ ] Pin length should be 100mil (pin name have only 2 chars)

Else no comment to do.

Cheers,
Joel

**Comment by JonathSpirit** [comment]
Hi thanks for the review,
I applied all the changes :
image

image

image

**Comment by myfreescalewebpage** [comment]
Thanks.
- [ ] The packages at the ends of aliases description are still not correct
- [ ] Footprint filter should be `QFN*1EP*5x5mm*P0.5mm*`

**Comment by JonathSpirit** [comment]
oups didn't see the alias description, and should i put : 

> QFN\*1EP\*5x5mm\*P0.5mm\*3.3x3.3mm\*

for the filter ?

**Comment by myfreescalewebpage** [comment]
No it's `QFN*1EP*5x5mm*P0.5mm*`, we never indicate the EP size in the footprint filter. If you found some devices where this rules is not correct this is because they are old and should be updated.

**Comment by JonathSpirit** [comment]
Thanks for the answer, I applied the change

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
