### PR TITLE
add AD7949 family of 8 channel ADC

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the [AD7949](https://www.analog.com/media/en/technical-documentation/data-sheets/AD7949.pdf), [AD7689](https://www.analog.com/media/en/technical-documentation/data-sheets/AD7682_7689.pdf) and [AD7699](https://www.analog.com/media/en/technical-documentation/data-sheets/AD7699.pdf) 8 channel ADC. They share the same package and symbol, only the resolution and speed differ.

The reference pins are set to passive as they can either be used to supply a reference or need bypass capacitors attached.

AD7949

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Thanks for shrinking.
1. Let's also separate pin 21 here since it's not connected internally.
1. 7689 and 7699 come in two packages, so they need to be named like `AD7689xCP` to note the symbol only applies to the LFCSP package. The last one can be named this way but doesn't have to be.

Would you please post a new screenshot?

**Comment by lorem-ipsum** [comment]
AD7949

**Comment by evanshultz** [comment]
The suffix for the package should be `xCP`, not `xxPZ`. The `Z` is for RoHS, which we don't capture, and there is only one character for the A or B grade. `CP` is the package's short name.

Actually, 7949 and 7699 only come in B grade so you can use `AD7949BCP` and `AD7699BCP` if you like. 7689 comes in both grades so we need either both or a wildcard.

**Comment by lorem-ipsum** [comment]
changed them, and only kept the wildcard for the 7689

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
