### PR TITLE
Add MMZ09332BT1 symbol

### PR DESCRIPTION
**Pull request by drid**
Add MMZ09332BT1 RF power amplifier
https://www.nxp.com/docs/en/data-sheet/MMZ09332B.pdf

image

Footprint: https://github.com/KiCad/kicad-footprints/pull/1692  

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @drid , thanks for contributing,

A few comments I have during my review:

- [ ] The description is too much long and should be terminated with the package name, I propose: `High efficiency linearity amplifier, QFN-12`
- [ ] Use Capital Letters for RFIN pin and POWER_DOWN
- [ ] NC pins 4 and 5 should be on the symbol, invisible, on the border outline
- [ ] VCC2/RFOUT pins should be stacked and should be Output

Can look like:

Capture

Cheers,
Joel

**Comment by drid** [comment]
> VCC2/RFOUT pins should be stacked and should be Output
As it can be seen in datasheet and gerber files, although these pins are internally connected, usually on pin is VCC and the other two RF out. If all three pins are connected, a different matching network is needed.

**Comment by myfreescalewebpage** [comment]
Thanks for the tip.
About NC pin, they should be located on the border outline of the symbol.
Joel

**Comment by drid** [comment]
You mean like this?
image

**Comment by myfreescalewebpage** [comment]
Can be at the bottom, but on the 100mil grid.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Just need to wait the footprint now. Joel

**Comment by drid** [comment]
There is a PR for the footprint but it's halted

**Comment by myfreescalewebpage** [comment]
@drid can you solve the branch conflict here to permit the merge of the symbol ? Thanks Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
