### PR TITLE
Add E73-2G4M04S-52832 BLE5 module

### PR DESCRIPTION
**Pull request by isundaylee**
Add symbol for E73-2G4M04S-52832 BLE5 module based on nRF52832 chip. 

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/555

Datasheet: http://www.cdebyte.com/en/downpdf.aspx?id=243 (page 5)
Screenshot:

screen shot 2018-05-04 at 2 01 20 pm

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Would you mind making this symbol look more like our other Nordic Semi symbols? See https://github.com/KiCad/kicad-symbols/pull/75, https://github.com/KiCad/kicad-symbols/pull/247, and https://github.com/KiCad/kicad-symbols/pull/379. Even though this is a module, it seems to have the same functionality and pinout at a glance.

**Comment by isundaylee** [comment]
Thanks for the review! Sure, to make sure I don't miss anything, it seems that: 

- I should move all GPIO pins except RESET to the right.
- Use VDD/VSS instead of VCC/GND. 
- Move DEC pins to the left of VCC.
- Maybe also label the NFC/AIN functions on the corresponding GPIO pins? Not sure if I should do this since the module data sheet didn't. 

Anything else I should do besides theses?

**Comment by isundaylee** [comment]
I've changed the symbol to match the other nRF symbols' style. Updated screenshot: 

screen shot 2018-05-06 at 4 46 55 pm

**Comment by evanshultz** [comment]
Sorry that I missed your questions above.
- I'm prefer VCC/GND pin names since the module datasheet uses it, but you've matched the position of the MCU symbol and that looks good.
- You can omit the NFC/AIN pin names if you prefer. Again, the pin position is good.
- Compared to the MCU symbol, you rectangle is a bit bigger. Can you shrink it to match?
- Please add the default footprint and footprint filter to match your footprint submission.
- Since this symbol works for both 52832 and 52810 modules, would you mind adding an 52810 ALIAS?

**Comment by isundaylee** [comment]
@evanshultz Made changes as requested. On second thought I feel like keeping the AIN and NFC markings might be handy. Let me know if you'd prefer them removed instead. 

Updated screenshot: 

screen shot 2018-05-18 at 12 46 32 pm

Thanks!

**Comment by isundaylee** [comment]
@evanshultz Thanks! Done. Just to confirm, did you mean `E73*2G4M04S*` or `E73-2G4M04S*` as the footprint filter?

**Comment by evanshultz** [comment]
Either way will be OK with the current filtering method, actually. This should be fine.

**Pull request merged**
