### PR TITLE
Add some aliases for the generic power LED 1w / 3w

### PR DESCRIPTION
**Pull request by Franck78**
Add some aliases  for the power LED

From Gitian manufacturer:
* white leds: GT-P02W2 GT-P02W3 GT-P02W4 GT-P02W5 GT-P02W6
* color leds: GT-P02B5 GT-P02B3 GT-P02G5 GT-P02G6 GT-P02Y2 GT-P02A1 GT-P02R1 GT-P02R6

From Polywa:
* white/1w: KLHP331WW KLHP331NW KLHP331W
* color/1w: KLHP331B KLHP331G KLHP331A KLHP331R
* white/3w: KLHP3433WW KLHP3433NW KLHP3433W K
* color/3w: LHP3433B KLHP3433G KLHP3433A KLHP3433R

https://github.com/KiCad/kicad-footprints/pull/2433
https://github.com/KiCad/kicad-packages3D/pull/721

(note: my Lib editor introduces a reorder between 2 components.
No change here but bigger diff
LED_RGCB LED_RGB_EP)

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
* https://www.getiangroup.com/data/upload/ueditor/20190909/5d75f9d95ad18.pdf (white)
* https://www.getiangroup.com/data/upload/20190902/5d6cc52e92386.pdf (colors and rgb variant package)
* http://www.kwalityphotonics.com/images/pdfdocs/ds_47.1_klsl331we.pdf
* http://www.kwalityphotonics.com/images/pdfdocs/ds_47_klhp3433xe.pdf

- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
no change here
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
https://github.com/KiCad/kicad-footprints/pull/2433
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@Franck78 thanks for this contribution.
The "Device" library goal is to have only generic devices, no aliases are made.
You should add your LEDs in the "LED" library. Each of them linked to the right footprint.
Joel

**Comment by Franck78** [comment]
ah,
Hello Joel,

let's do it in the correct sequence then !

1. move this device to LED
2. I will do a new PR

Or if my 'change' is correct, merge it, do the move to LED, case closed ;)

I don't know how to move things, sorry.

**Comment by myfreescalewebpage** [comment]
You should not move, but copy. The generic LED should remain the Device library and should remain unchanged.
Don't do a new PR, the repo is now locked, we do not accept new PR because KiCad v6 is in preparation. Instead, make the modifications on this PR.
Joel

**Comment by Franck78** [comment]
I think the description will stay as it is with a more than enough semi Chineese description ;)

**Pull request closed without merging**
