### PR TITLE
add AAT4616IGV

### PR DESCRIPTION
**Pull request by balcer**
aa6

http://www.skyworksinc.com/uploads/documents/AAT4616_201940E.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @balcer, thanks for contributing,

A single comment I have during my review:

- [ ] You added the package name to the keyword instead of the description. Also do not forget the comma: `Adjustable Current Limited Load Switch, SOT-23-5`

Cheers,
Joel

**Comment by balcer** [comment]
Done

**Comment by myfreescalewebpage** [comment]
@balcer the library can't be properly opened, some missing lines before "$CMP AAT4616IGV-1-T1" in the DCM file... Thanks.

**Comment by balcer** [comment]
@myfreescalewebpage fixed

**Comment by myfreescalewebpage** [comment]
@balcer due to merging of the other PR, this one has now conflict, can you solve it please ? Thanks, Joel

**Comment by balcer** [comment]
@myfreescalewebpage I made rebase on the new master. Sorry for force push.

**Comment by myfreescalewebpage** [comment]
No worries. No more comment to do here, merging.

**Pull request merged**
