### PR TITLE
Adding MT48 256Mb SDRAM. Changing some old SDRAMs

### PR DESCRIPTION
**Pull request by ki5libs**
Adding MT48 256Mb SDRAM (TSOP-II-54 package)
[Datasheet](https://www.micron.com/-/media/client/global/documents/products/data-sheet/dram/256mb_sdr.pdf)
x16:
MT48x16
x8:
MT48x8
x4:
MT48x4
AS4C4M16SA changed to the same form (also Travis errors fixed):
AS4C
IS42S16400J-xC(with IS42S16400J-xT alias) changed to the same form (also Travis errors fixed):
IS42S

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @ki5libs thanks for this

Two comments right now:
- [ ] Can you rebase to the master to permit the review easily ?
- [ ] Packages in the description should be "TSOP-II-54"

Will do a full review after that

Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

I've been in the trip. Give me couple of days to figure it out.

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks for your message, no problem

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

I hope it's ready for review now.

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs, thanks

Full review now.

AS4C4M16SA
- [ ] Name of pin 22 should be "A10/AP"
- [ ] Style of pin 38 should be Line

IS42S16400J-xC
- [ ] Style of pin 38 should be Line

MT48LC16M16A2TG
- [ ] Style of pin 38 should be Line

MT48LC16M16A2P
- [ ] Package in the description should be "TSOP-II-54"

MT48LC32M8A2TG
- [ ] Style of pin 38 should be Line

MT48LC32M8A2P
- [ ] Package in the description should be "TSOP-II-54"

MT48LC64M4A2TG
- [ ] Style of pin 38 should be Line

MT48LC64M4A2P
- [ ] Package in the description should be "TSOP-II-54"

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

thanks for review. I've fixed all of your notes. 

By the way I've noticed strange thing. May be it's a KiCAD bug. In the description of MT48LC16M16A2P, MT48LC32M8A2P and MT48LC64M4A2P (aliases) I was seeing  "TSOP-II-54" package though it was incorrect in Memory_RAM.dcm.

**Comment by myfreescalewebpage** [comment]
Strange, maybe it's a bug, not experienced by myself.
Merging.

**Pull request merged**
