### PR TITLE
modifed the Raspberry Pi symbol and added the Run header

### PR DESCRIPTION
**Pull request by jstjst**
modifed the Raspberry Pi symbol and added the Run header

Also the symbol name of the Raspberry Pi models may should be changed to `Raspberry_Pi` or `Raspberry_Pi_40-Pin`, because today all models have the 40 Pin header (there is a new version of the version 1, that had original 26 pins and now has also 40 pins). But I think just `Raspberry_Pi` is the way to go, since there is no symbol in the library with 26 pins

grafik

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@jstjst I do not understood this symbol, I see you added RUN and GND pins 41/42, but they are not on the RPi isn't it ? The expansion header has only 40 pins....
Additionally, you haven't provided a footprint for this symbol...
Joel

**Comment by jstjst** [comment]
@myfreescalewebpage They are not on the GPIO header, but access able from a separate header and can be use to reset the Raspberry Pi
https://raw.githubusercontent.com/raspberrypisig/raspberrypisig.github.io/master/assets/images/rpi3runheader.jpg
https://i.stack.imgur.com/UR12g.jpg

I have a footprint for the Raspberry Pi Zero ready, just need to push is

**Comment by myfreescalewebpage** [comment]
> @myfreescalewebpage They are not on the GPIO header, but access able from a separate header and can be use to reset the Raspberry Pi

Well, so what is your symbol stand for ? It can't be used on a PCB....
You should simply use the existing symbol and add a 2 pins connectors if you wants to wire them, isn't it ?

**Comment by jstjst** [comment]
If your are mounting a RPi Zero as a daughter board on a PCB, you would need this symbol:
grafik

**Comment by myfreescalewebpage** [comment]
@jstjst agree with you. But I'm speaking of the RPi 2/3 symbol of this PR at the moment. Why speaking about the RPi zero ?

**Comment by jstjst** [comment]
I would suggest to rename the RPi 2/3 symbol to Raspberry Pi. There is no real difference.
And I wouldn't add Zero to the withRun symbol, because it might be useful when someone want to use a normal Raspberry Pi as a daughterboard (I've seen that before).

**Comment by myfreescalewebpage** [comment]
@jstjst still do not understood the purpose of this pull request.... Sorry.

If you want to add support or RPi zero, you can submit a new pull request. I recommend you to start looking at PRi CM1 and CM3 module recently merged, fully compliant with KLC at the moment.

Renaming the symbol is not possible until we are near to v6 release, because it will break existing schematics.

**Comment by jstjst** [comment]
Ok, I think I will submit symbols for the Raspberry Pi Zero.

i don't know if it is a Option, to rename the symbols like that (I think this is much cleaner, if possible):
Raspberry_Pi
 - Raspberry_Pi_2_3 (alias for compatibility)
Raspberry_Pi_withRun

**Comment by myfreescalewebpage** [comment]
Raspberry_Pi only I think is not possible because it will refer to Raspberry Pi 1.

About the run option, I have previously understood it was a separated connector not available in the 40 pins connector so I do not understood the way to wire it. What the footprint can look like ? I have checked at some images of the board on Google Image but I do not understood where this connector is and what it looks like. If you have a photo and you can indicate on it where it is, that's will help to take a decision.

Thanks,
Joel

**Comment by jstjst** [comment]
I made a list with all the commonly used pin headers of the Raspberry Pi models:

- 26 GPIO pin header ("old")
  - Raspberry Pi 1 A (discontinued) (plus 2 pin header `RUN, GND`)
  - Raspberry Pi 1 B (discontinued) (plus 2 pin header `RUN, GND`)
- 40 GPIO pin header
  - Raspberry Pi 1 A+ (plus 2 pin header `RUN, GND`)
  - Raspberry Pi 1 B+ (plus 2 pin header `RUN, GND`)
  - Raspberry Pi 2 B (plus 2 pin header `RUN, GND`)
  - Raspberry Pi 3 B (plus 2 pin header `RUN, GND`)
  - Raspberry Pi 3 A+ (plus 2 pin header `PEN, RUN`)
  - Raspberry Pi 3 B+ (plus 2 pin header `PEN, RUN`)  (plus 4 pin header POE)
  - Raspberry Pi Zero (plus 2 pin header `RUN, GND`) (plus 2 pin header `TV, GND`)
  - Raspberry Pi Zero W (plus 2 pin header `RUN, GND`) (plus 2 pin header `TV, GND`)

The pin headers (2.54mm pitch) in brackets are not factory populated, but can be soldered in and than accessed from a expansion board (HAT) or when the Pi is used as a daughter board.

RUN -> holds the processor in Reset state
REN -> disables the power supply
TV -> Composite video
POE -> PoE Taps from Ethernet connector

As it turns out there are much more variants as I had in mind. So I thought over my suggestion to just name the symbol `Raspberry_Pi` and I now think we should create a symbol (alias) for every RPi model. This will be also more future proof.

This symbols would be needed:
- 26 GPIO
  - Raspberry Pi 1 A
  - Raspberry Pi 1 B
- 26 GPIO with `RUN, GND`
  - Raspberry Pi 1 A
  - Raspberry Pi 1 B
- 40 GPIO
  - Raspberry Pi 1 A+
  - Raspberry Pi 1 B+
  - Raspberry Pi 2 B
  - Raspberry Pi 3 B
  - Raspberry Pi 3 A+
  - Raspberry Pi 3 B+
  - Raspberry Pi Zero
  - Raspberry Pi Zero W
- 40 GPIO with `RUN, GND`
  - Raspberry Pi 1 A+
  - Raspberry Pi 1 B+
  - Raspberry Pi 2 B
  - Raspberry Pi 3 B
  - Raspberry Pi Zero
  - Raspberry Pi Zero W
- 40 GPIO with `PEN, RUN`
  - Raspberry Pi 3 A+
  - Raspberry Pi 3 B+
- 40 GPIO with `PEN, RUN` and POE
  - Raspberry Pi 3 B+
- 40 GPIO with `RUN, GND` and `TV, GND`
  - Raspberry Pi Zero
  - Raspberry Pi Zero W

I don't know if it makes sense to create all these symbols now with the new library format coming some time in future. But I would create at least most of the symbols when needed.

**Comment by myfreescalewebpage** [comment]
@jstjst thanks for this complete list of all the raspberry pi boards ! Yes I totally agree with this approach, a symbol should be defined for each board. We have to think to the names for each of them. I will review them with pleasure if you submit some of them :)

**Comment by jstjst** [comment]
Since a lot of symbols need to be created, I reviewed the existing RPi symbols, to avoid double work.
I noticed following things:
 - Power Pins are not stacked, but I would leave it like that. Because it gives the Option to leave some of them unconnected since there are connected on the Pi. It is sometimes a bit tricky to layout all of them, because they are scattered on the connector.
 - GPIO Pin grouping looks fine to me.
 - Pin offset need to be set to 20
 - Description may be improved (with a look to the CM)
 - Symbols should be in `MCU_Module`
 - Symbol name scheme like the CMs
 - Footprint filter need to be changed
 - Footprint need to be defined
 - Designator should be `A`
 - Rectangles at the pins should be removed

@myfreescalewebpage Could you please take a look at the list.
Since we might put the new symbols in `MCU_Module` anyway, it might be the best option to leave to RPi symbol in `Connector` and remove it with v6

**Comment by myfreescalewebpage** [comment]
@jstjst I totaly agree with you on all the points. Also, yes keeping the existing symbol in Connector is the best choice today, to be removed in v6 only.
PS : I have personally reviewed all the CM modules recently (https://github.com/KiCad/kicad-symbols/pull/1675), for me they are good examples to follow and they match with KLC guidelines ;-)

**Comment by myfreescalewebpage** [comment]
Proposition of names:

- 26 GPIO
  - Raspberry Pi 1 A => RaspberryPi-1A
  - Raspberry Pi 1 B => RaspberryPi-1B
- 26 GPIO with `RUN, GND`
  - Raspberry Pi 1 A => RaspberryPi-1A_Run
  - Raspberry Pi 1 B => RaspberryPi-1B_Run
- 40 GPIO
  - Raspberry Pi 1 A+ => RaspberryPi-1A+
  - Raspberry Pi 1 B+ => RaspberryPi-1B+
  - Raspberry Pi 2 B => RaspberryPi-2B
  - Raspberry Pi 3 B => RaspberryPi-3B
  - Raspberry Pi 3 A+ => RaspberryPi-3A+
  - Raspberry Pi 3 B+ => RaspberryPi-3B+
  - Raspberry Pi Zero => RaspberryPi-Zero
  - Raspberry Pi Zero W => RaspberryPi-ZeroW
- 40 GPIO with `RUN, GND`
  - Raspberry Pi 1 A+ => RaspberryPi-1A+_Run
  - Raspberry Pi 1 B+ => RaspberryPi-1B+_Run
  - Raspberry Pi 2 B => RaspberryPi-2B_Run
  - Raspberry Pi 3 B => RaspberryPi-3B_Run
  - Raspberry Pi Zero => RaspberryPi-Zero_Run
  - Raspberry Pi Zero W => RaspberryPi-ZeroW_Run
- 40 GPIO with `PEN, RUN`
  - Raspberry Pi 3 A+ => RaspberryPi-3A+_Pen_Run
  - Raspberry Pi 3 B+ => RaspberryPi-3B+_Pen_Run
- 40 GPIO with `PEN, RUN` and POE
  - Raspberry Pi 3 B+ => RaspberryPi-3B+_Pen_Run_PoE
- 40 GPIO with `RUN, GND` and `TV, GND`
  - Raspberry Pi Zero => RaspberryPi-Zero_Run_Tv
  - Raspberry Pi Zero W => RaspberryPi-ZeroW_Run_Tv

**Comment by jstjst** [comment]
Another list with the symbol naming:
- [ ] RaspberryPi-1A
  - [ ] RaspberryPi-1B
- [ ] RaspberryPi-1A_Run
  - [ ] RaspberryPi-1B_Run
- [ ] RaspberryPi-1A+
  - [ ] RaspberryPi-1B+
  - [ ] RaspberryPi-2B
  - [ ] RaspberryPi-3B
  - [ ] RaspberryPi-3A+
  - [ ] RaspberryPi-3B+
  - [ ] RaspberryPi-Zero
  - [ ] RaspberryPi-Zero-W
- [ ] RaspberryPi-1A+_Run
  - [ ] RaspberryPi-1B+_Run
  - [ ] RaspberryPi-2B_Run
  - [ ] RaspberryPi-3B_Run
  - [ ] RaspberryPi-Zero_Run
  - [ ] RaspberryPi-Zero-W_Run
- [ ] RaspberryPi-3A+_Run_PEN
  - [ ] RaspberryPi-3B+_Run_PEN
- [ ] RaspberryPi-3B+_Run_PEN_PoE
- [ ] RaspberryPi-3B+_PoE
- [ ] RaspberryPi-Zero_Run_TV
  - [ ] RaspberryPi-Zero-W_Run_TV
- [ ] RaspberryPi-Zero_TV
  - [ ] RaspberryPi-Zero-W_TV

@myfreescalewebpage Can you take a look if the naming should be changed somewhere?
I'm not totally happy about the names for the symbols with PEN, since it leaves the impression PEN is an extra functionality to Run. But in reality the Run connectors were changed so that GND was replaced with PEN.

**Comment by jstjst** [comment]
I did not see your comment

**Comment by myfreescalewebpage** [comment]
> I did not see your comment

But we have made quite the same proposition so looks great :)
Just some differences on:
- ZeroW and Zero-W, to be honest I have not checked how RPi is described officially, but we should follow th official naming
- Case of Pen or PEN, I haven't preference

**Comment by jstjst** [comment]
>     ZeroW and Zero-W, to be honest I have not checked how RPi is described officially, but we should follow th official naming

Changed that already
> Case of Pen or PEN, I haven't preference
I would choose PEN, since it stands for Power ENable.

**Comment by jstjst** [comment]
I made a symbol with all the possible connections in it, so we have one master and just delete pins for the other symbols. That will make it also easy to change out symbols in the schematic.
grafik

**Comment by myfreescalewebpage** [comment]
@jstjst this looks a very good template. Just one comment: GND pins must be stacked. In any case it is a good practice to connect all of them.

**Comment by jstjst** [comment]
@myfreescalewebpage Ok, than I will stack all Power Pins (also 5V and 3V3).

**Comment by jstjst** [comment]
Can we also make a decision about the Designator (A or U)?
With in MCU_Module, both are present.

**Comment by jstjst** [comment]
Continue in PR #1771

**Pull request closed without merging**
