### PR TITLE
TMC5160-TA added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
Based on PR from G-Pereira:TMC5160-TA (#1070)
(I didn't know how to actualize an existing PR)

Datasheet: https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5160_Datasheet_Rev1.06.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by G-Pereira** [comment]
Nice to see my work being useful! Sadly I've stopped working for this but if you want I would be happy to help. How is this going?

**Comment by serkanxselcuk** [comment]
Hi @G-Pereira, 
it was a nice helpful to go on an already prepared symbol. Thank you for your contribution. I started a design with TMC5130-TA, later I will develop a stronger version with TMC5160-TA. But it works slowly because I do it after work.

**Comment by myfreescalewebpage** [comment]
Hi @serkanxselcuk , thanks for contributing,

A few comments I have during my review:

- [ ] Description format is wrong, should be `20A Driver for two-phase bipolar stepper motor, SPI, UART, TQFP-48`
- [ ] Footprint filter should be `TQFP*1EP*7x7mm*P0.5mm*`
- [ ] Name of pin 13 should be `~CS~/CFG3`
- [ ] Name of pin 28 should be `~DRV_EN`
- [ ] Pin 49 is missing and should be stacked with GNDD pins
- [ ] Pin 16 should be Bidirectional
- [ ] Pin 25 should be Bidirectional
- [ ] Pins CA1, CA2, CB1, CB2 should be Passive
- [ ] The position of the pins should be arrange. I think control on the left and power on the right can be very nice. Here is my proposition (this reduce a bit the height of the symbol):

Capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk any news here ? Thanks!

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage,

thanks for your review.
I made most changes at #1797 for tmc5130. I would prefer to get it merged before this one, because tmc5130 and tmc5160 are mostly similar.

**Comment by myfreescalewebpage** [comment]
No worries @serkanxselcuk , thanks for your message.

**Comment by serkanxselcuk** [comment]
image
TMC5160-TA
 
I prefer to merge #1797 TMC5130A-TA first to ensure pin compatibility.

**Comment by serkanxselcuk** [comment]
image

image

- [ ] Description format is wrong, should be 20A Driver for two-phase bipolar stepper motor, SPI, UART, TQFP-48
- [ ] Footprint filter should be TQFP*1EP*7x7mm*P0.5mm*
- [ ] Name of pin 13 should be ~CS~/CFG3
- [ ] Name of pin 28 should be ~DRV_EN
- [ ] Pin 49 is missing and should be stacked with GNDD pins
- [ ] Pin 16 should be Bidirectional
- [ ] Pin 25 should be Bidirectional
- [ ] Pins CA1, CA2, CB1, CB2 should be Passive
- [ ] The position of the pins should be arrange.

**Comment by serkanxselcuk** [comment]
@myfreescalewebpage 
Hi Joel,
changes are made. I believe merging TMC5130 will take more than I thought. I hope it should be ready to merge.

*This is not a review, only feedback to label `Pending changes`*

**Comment by myfreescalewebpage** [comment]
Hi @serkanxselcuk 

Thanks.

- [ ] The datasheet link is broken, should now be: https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5160A_Datasheet_Rev1.13.pdf
- [ ] EP size should not be in the FP filter, we never do that.
- [ ] OK for the EP. Should be Power Input and closed to GND pins
- [ ] I still think the position of the pin is not very nice, can you provide schematic sample to look at the result ?

Joel

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk ping

**Comment by serkanxselcuk** [comment]
Hi Joel,

I am back after a long pause.  Thank you for your review. I will fix that points.

Greetings.

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage ,

hier is an example schematic for TMC5160  based on Datasheet Page 5 Figure 1.1.

https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5160A_Datasheet_Rev1.14.pdf

image

Labels are SPI and Enable signals to master MCU, Limit sensors/switches and clock input.

**Comment by G-Pereira** [comment]
It's probably a good idea to add an alias for the newer revision, the TMC5160A

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk you have addressed all my points. About he design, why not, I let you first merge #1797 and then we can finalize here.

@G-Pereira do you know what is the differences between TMC5160 and TMC5160A ? I'm not able to identify this.

**Comment by G-Pereira** [comment]
It's an hardware revision, the non A version is no longer in production since the A version fixes hardware bugs. The same happened with TMC2160/A, they probably share some most of the IP since the TMC2160 is the same as the TMC5160 except for the built-in controller.
According to the datasheet:
"The A-version compatibly replaces the non-A-version."

**Comment by serkanxselcuk** [comment]
image

image
( see #1797 )

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk will check every thing after integration of #1797

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk I have seen the other PR is merged, please ping me when this one is ready too.

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage ,
yes, it is ready now.

**Comment by myfreescalewebpage** [comment]
Made a complete review, no comment. Merging, thanks @serkanxselcuk for this great job

**Pull request merged**
