### PR TITLE
Add Microchip ATSAMA5D21, 196-pin BGA Linux-capable MPU

### PR DESCRIPTION
**Pull request by yankee14**
This is a Microchip ATSAMA5D21--one of the cheapest Linux-capable microprocessor units on the market!

I tried to make this symbol adhere to the KiCad Library Convention (KLC), however, I am not happy with how it looks. In my opinion, the complexity justifies diverging from the KLC, and the symbol should be split into logical blocks based on functionality.

[Datashort](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-45165-Atmel-SMART-SAMA5D2_Flyer.pdf)
[Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAMA5D2-Series-Data-Sheet-DS60001476C.pdf)

ATSAMA5D21

[Associated footprint PR](https://github.com/KiCad/kicad-footprints/pull/1604)
[Associated kicad-footprint-generator PR](https://github.com/pointhi/kicad-footprint-generator/pull/364)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 thanks for this great symbol !

I have not yet performed a full review, if you which to split the device in several units, it's a good idea ! You can separate the DDR, the power supplies, the crystal... Please let me known.

Notes:
- you can stack ground pins which have the same name.
- I'm not sure on the screenshot, but pins have 3 digits => pin length should be 150mil
- You have to update the "sym_lib_table" file when creating a new library

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@yankee14 seems you have worked on this, but you have at least not updated the "sym_lib_table" file yet. Please indicate when it's ready for review.
Joel

**Comment by yankee14** [comment]
I finally have some more time to work on this @myfreescalewebpage . I made some more progress but am not yet finished.

**Comment by yankee14** [comment]
@myfreescalewebpage I think it is ready for review

**Comment by myfreescalewebpage** [comment]
Make a full review now:

- [ ] Description should be `ARM Cortex-A5 MPU, 500 MHz max, 1x SDIO/SD-CARD/eMMC/QSPI memory, 128 kB SRAM, 16-bit bus DDR2/DDR3 RAM, 1.1-1.32 V, 72 GPIO, TFBGA-196` (just changed the package type format at the end)
- [ ] Unit A : Will be better if all pins are on the same side, on the right for example, starting from PA18 at the top, to PA31. The same applies to units B, C and D. This is what we have done for some FPGA for example in the lib.
- [ ] Unit F : Name of pin D13 should be `~DDR_RESET` to get the overbar
- [ ] Unit J : Probably XIN and XOUT are to connect a crystal, right ? In this case having them on the same side is better, else OK.
- [ ] Unit H : Name of pin N3 shoud be `~RST` to get the overbar
- [ ] Unit H : PIOBUx pin on the same side is better I think
- [ ] Unit H : XIN32 and XOUT32 on the same time to simplify wiring the crystal
- [ ] Unit H : COMPP and COMPN are Input according to the datasheet

Joel

**Comment by yankee14** [comment]
@myfreescalewebpage I think I covered all your items. Please let me know if there are more corrections to be made!

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 and sorry for the delay. No more comment for me on this PR, just need to wait for the footprint before merging (https://github.com/KiCad/kicad-footprints/pull/1604).
Joel

**Comment by yankee14** [comment]
@myfreescalewebpage no worries. @evanshultz gave the okay on the footprint

**Comment by myfreescalewebpage** [comment]
@yankee14 fottprint has been merged, need to rename in the symbol: `Package_BGA:Microchip_TFBGA-196_11x11mm_Layout14x14_P0.75mm_SMD`

**Comment by evanshultz** [comment]
@yankee14 
Because splitting symbols is relatively new, could you post screenshots of all units? This will make referencing what you've done here easier in the future.

**Comment by yankee14** [comment]
@evanshultz of course

@myfreescalewebpage I'm on it

**Comment by yankee14** [comment]
Units A through J
a
b
c
d
e
f
g
h
i
j

**Comment by myfreescalewebpage** [comment]
@yankee14 thanks.
Last comment : footprint filter should be "Microchip*TFBGA*11x11mm*P0.75mm*"

**Comment by chschlue** [comment]
@edp-d6labs I think @myfreescalewebpage meant to say "Microchip\*TFBGA\*11x11mm\*P0.75mm\*" but forgot to escape the asterisks :)

**Comment by yankee14** [comment]
@chschlue oops, of course lol

**Comment by myfreescalewebpage** [comment]
Yes markdown langage !
No more comments to do here, merging. Tanks for this great job !
Joel

**Pull request merged**
