### PR TITLE
Fix multiple greedy FP filters

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Fixes https://github.com/KiCad/kicad-symbols/issues/697

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
This looks good to me and I'm prepared to merge now, but will this break enough other PRs to be done in chunks? IMO it's fine to do at any time, but I didn't want to merge without soliciting other's thoughts.

**Comment by antoniovazquezblanco** [comment]
Perfect. I took the liberty to assing you Evan. Thanks!

**Comment by evanshultz** [comment]
No problem. No comments in a day and since I expect there to be little to no impact I'll merge. Thanks!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
