### PR TITLE
ADD LM5050-1 And LM5050-2

### PR DESCRIPTION
**Pull request by jneiva08**
Add symbols fot LM5050-1 and LM5050-2

LM5050-1
Datasheet: http://www.ti.com/lit/ds/symlink/lm5050-1-q1.pdf

lm5050-1

LM5050-2
Datasheet: http://www.ti.com/lit/ds/symlink/lm5050-2.pdf

lm5050-2

The symbols was made based of LM5051 already on symbol library.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jneiva08** [comment]
@myfreescalewebpage hope the footprint name is like you recommended, and the footprint filter is wright
Tomorrow will make footprint PR, the old footprit will need little of work to be to the recent KLC format

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

LM5050-1
- [ ] Capital letter at the beginning of the description: `High side OR-ing FET controller, 5V to 75V operation, SOT-23-6`
- [ ] Footprint not found, is it different of SOT-23-6 ? Do you have submitted a pull request ?
- [ ] Pin number of pin GATE is 5

LM5050-1-Q1
- [ ] Capital letter at the beginning of the description and fix of package name at the end required: `High side OR-ing FET controller, 1V to 75V operation, SOT-23-6`

LM5050-2
- [ ] Capital letter at the beginning of the description: `High side OR-ing FET controller, 6V to 75V operation, SOT-23-6`
- [ ] Missing one `*` at the end of the footprint filter
- [ ] Footprint not found, is it different of SOT-23-6 ? Do you have submitted a pull request ?
- [ ] Datasheet link should be `http://www.ti.com/lit/ds/symlink/lm5050-2.pdf`
- [ ] I suggest that FGD pin should be moved to the right, at the place of VS pin
- [ ] Pin number of pin GATE is 5

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage 
Aside from the modifications you requested, i was thinking to change the symbol to be identical to https://github.com/KiCad/kicad-symbols/pull/1706 , it is more compact. what is your opinion?

**Comment by myfreescalewebpage** [comment]
It's not bad, and getting something consistent with #1706 is great, you can go in this direction too. Thanks to point that.

**Comment by jneiva08** [comment]
@myfreescalewebpage Have made the changes you requested, in the same style of TPS2419

LM5050-1
lm5050-1

LM5050-2
lm050-2

how it looks LM5050-1 in schematic
sch

In regads of footprint, need to finish the modifications requested. The PR is https://github.com/KiCad/kicad-footprints/pull/1489 and for the script is https://github.com/pointhi/kicad-footprint-generator/pull/331

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks. Ok for the footprints.
For the LM5050-2 you have changed the input voltage range but you should not, it is 6-75V not 5-75V, please revert this.
Will do a new review when the footprint will be merged.
Joel

**Comment by jneiva08** [comment]
Noticed the footprint is no centred in the top misses 2.54mm

**Comment by myfreescalewebpage** [comment]
> Noticed the footprint is no centred in the top misses 2.54mm

Not understood...

**Comment by jneiva08** [comment]
Travis i giving the following error:
+ Violating S3.1

**Comment by evanshultz** [comment]
We don't accept automotive-grade parts. They fall under http://kicad-pcb.org/libraries/klc/S2.2/.

**Comment by myfreescalewebpage** [comment]
@evanshultz I'm not sure this is an inconvenient here but if it is strict that mean @jneiva08 should simply remove the Q1 alias ?

@jneiva08 S3.1 travis log is only a info not an error here. It's enough centered to get happy with this.

**Comment by evanshultz** [comment]
Yes. Just remove that ALIAS.

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks. Description should ends with the correct package name, for me it is "Texas R-PDSO-G6" here. Else, no more comment, just need to wait integration of the footprint.

**Comment by evanshultz** [comment]
My recollection is that the description uses a more generic footprint name, such as `SOT-23-6` in this case. Maybe there are manufacturer-specific packages in the description so feel free to verify.

**Comment by myfreescalewebpage** [comment]
@evanshultz it is, the footprint is specific here ...

**Comment by evanshultz** [comment]
Just because TI has their own name doesn't mean it's not a generic package. JEDEC MO-193AA is referenced in the datasheet.

**Comment by myfreescalewebpage** [comment]
Right, I do not know if it correspond to standard SOT-23-6...

**Comment by evanshultz** [comment]
It does. It's the thinner version. See page 20 of http://www.ti.com/lit/ds/symlink/lm5050-2.pdf or search for the JEDEC spec:
image

So you can use `TSOT-23-6` if you like.

**Comment by myfreescalewebpage** [comment]
Right, "TSOT-23-6" not "SOT-23-6" :)

@jneiva08 package name at the end of the description should be "TSOT-23-6"

Thanks,
Joel

**Comment by evanshultz** [comment]
I recall simplifying "WQFN" to "QFN" and "VBGA" to "BGA" (for two examples). So not sure how detailed it should be. Probably a very minor grey area of KLC.

**Comment by poeschlr** [comment]
If we want to drop the first character for xQFN then we definetly need to include the height parameter. (the first character for the most part correlates to different package heights. How well that correlation is depends a bit on the manufacturer and how they use these names.)

**Comment by evanshultz** [comment]
@poeschlr 
The above conversation is exclusively about the text in the description of a symbol. Not a footprint. And not the footprint assigned to a symbol.

This has been variable and ambiguous in the past. I take from the above you want to be more specific so what Joel is asking in his last comment would be correct then.

**Comment by jneiva08** [comment]
@myfreescalewebpage @evanshultz 
Sorry for taking long, have changed footprint and filter to TSOT-23-6

**Comment by evanshultz** [comment]
I think description should also say `TSOT-23-6`, and it's missing the leading `T`.

**Comment by jneiva08** [comment]
Forgot to change the description.

**Comment by myfreescalewebpage** [comment]
@jneiva08 after a complete review:

LM5050-1:
- [ ] OUT pin should be Input

LM5050-2:
- [ ] OUT pin should be Input
- [ ] Name of pin 1 should be `~FGD`

Else, no more comment.

Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage have made the changes.
In the datasheet says OUT is an output.

**Comment by myfreescalewebpage** [comment]
@jneiva08 I have seen that but also check on the internal schematic and description of pins "Voltage sense connection to the external MOSFET Drain pin." This indicate it's an input, even if "O" if written in output type.

**Comment by myfreescalewebpage** [comment]
Merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
