### PR TITLE
Regulator_Linear: Rename variants of MCP1754 to follow naming convention

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
This PR renames son MCP1754 symbols to follow KLC.

See https://github.com/KiCad/kicad-symbols/pull/1731

### CODE REVIEW

**Comment by evanshultz** [comment]
It looks like this is adding the SOT23 versions, but that's already done. Maybe it's GH not figuring out the changes properly with other interim changes since this was submitted?

This should just correct the SOT89 symbol name, and I tagged this as for v6.

**Comment by myfreescalewebpage** [comment]
Nothing to add to the review, just need to wait V6.

**Comment by antoniovazquezblanco** [comment]
I cannot see 5.1.7 tagged yet in the repo. Has that been done?

Thanks!

**Comment by chschlue** [comment]
No, the v5 branches will be tagged 5.1.7 on 2020-09-23.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco  the branch "v5" is the branch on which we have to push for v5.1.7, but yes it will be tagged later

**Comment by antoniovazquezblanco** [comment]
Perfect! Glad to see things pushing fordward. I think I will find some time again to start helping back. 😄

**Pull request merged**
