### PR TITLE
Isolator: Add ADuM26xN devices

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://www.analog.com/media/en/technical-documentation/data-sheets/adum260n-261n-262n-263n.pdf

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A few comments I have during my review:

For all devices:
- [ ] Package in the description should be "SOIC-16"
- [ ] You can simply indicate keywords "digital isolator galvanic isopower" for these devices (consistent with other similar devices)
- [ ] We use now a single dash line on the device to indicate the isolation, please remove one

Else, sounds good !

Cheers,
Joel

**Comment by evanshultz** [comment]
Just for the heck of it, no requirement: Is the internal drawing overly complex?

**Comment by myfreescalewebpage** [comment]
@evanshultz it is, that's in line with the datasheet.

**Comment by antoniovazquezblanco** [comment]
Will address all comments above. I can change device internal drawings but I prefer not to if possible. Let me know what do you want me to do with them.

Thanks!

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks @antoniovazquezblanco  no more comment, merging.

**Pull request merged**
