### PR TITLE
Add PD4859J5050S2HF

### PR DESCRIPTION
**Pull request by matthuszagh**
https://cdn.anaren.com/product-documents/Xinger/PowerDividers/PD4859J5050S2HF/PD4859J5050S2HF_DataSheet(Rev_D).pdf

image

footprint pr: https://github.com/KiCad/kicad-footprints/pull/1281

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] Can you solve the branch conflict on this PR, please ?
- [ ] You are currently violating KLC S3.2, please increse size of the pad name to 50mil. You can achieve this by moving GND to the left, this is better to not violate KLC. Proposition below.

capture

Cheers,
Joel

**Comment by matthuszagh** [comment]
I've made the changes and fixed the branch conflict. The text for input and gnd look a bit close now, but let me know what you think.

image

**Comment by myfreescalewebpage** [comment]
@matthuszagh sorry for the text size and position of GND, I have first ask you to modify it but then edited my comment and you probably haven't seen this (see above). Can you revert back text size and position of GND pins please ? I prefer having consistency with #1398 

Thanks,
Joel

**Comment by matthuszagh** [comment]
Ah ok, no worries. It's reverted now and the merge conflict is fixed. Let me know if anything else.

**Comment by myfreescalewebpage** [comment]
@matthuszagh Thanks to be very reactive, can you add package name at the end of the description : `, Anaren 0805`. Then will be able to merge, that's the last comment to do here.

**Comment by matthuszagh** [comment]
Done.

**Comment by myfreescalewebpage** [comment]
Thanks, great job ! Merging.

**Pull request merged**
