### PR TITLE
Add Nexperia PMEG*E[HJT] {SOD-[13]23F,SOT-23} Schottky diodes

### PR DESCRIPTION
**Pull request by chschlue**
PMEG2005EH
PMEG2005EJ
PMEG2010AET

https://assets.nexperia.com/documents/data-sheet/PMEGXX05EH_EJ_SER.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG1020EH_EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG1030EH_EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2010AEH_PMEG2010AET.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2010AEJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2010EH_EJ_ET.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2015EH_EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG2020EH_EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3002EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3010CEH_PMEG3010CEJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3010EH_EJ_ET.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3015EH_EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG3020EH_EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4002EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4005CEJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4010CEH_PMEG4010CEJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG4010EH_EJ_ET.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6002EJ.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG6010CEH_PMEG6010CEJ.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
why did you mark this as bug?

**Comment by chschlue** [comment]
I moved PMEG6010CEJ from an SOD-323 symbol.
Forgot to mention.

**Comment by poeschlr** [comment]
please always separate bug fixes from additions. Fixes can typically be merged much faster than additions.

**Comment by chschlue** [comment]
There were no SOD-123F / -323F Schottky symbols before, so the fix depends on the addition anyway.

**Comment by myfreescalewebpage** [comment]
@chschlue can you rebase your branches so it will be possible to review this PR ? Thanks, Joel

**Comment by chschlue** [comment]
Done.

**Comment by myfreescalewebpage** [comment]
Hi @chschlue , starting the review of this pull request. Will do several steps.

First, you added "PMEGxx05EH" and "PMEGxx05EJ" but it seems they do not exist really. Instead, on the aliases should be used to device the symbol.

For PMEG2010AET PMEG2010ET PMEG3010ET PMEG4010ET aliases, you added them to a zener diode and the symbol is not the same...

Joel

**Comment by chschlue** [comment]
> First, you added "PMEGxx05EH" and "PMEGxx05EJ" but it seems they do not exist really. Instead, on the aliases should be used to device the symbol.

I think I just started out with wildcarded symbols per footprint and forgot to remove them before actually opening this PR. Will fix.

> For PMEG2010AET PMEG2010ET PMEG3010ET PMEG4010ET aliases, you added them to a zener diode and the symbol is not the same...

That's nonsense, of course. Don't know what I was thinking. Will fix.

**Comment by myfreescalewebpage** [comment]
:) no worries

**Comment by chschlue** [comment]
@myfreescalewebpage Hope I got it right this time.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
