### PR TITLE
Added IR2x3x & IR2x3xS Drivers

### PR DESCRIPTION
**Pull request by aris-kimi**
IR2133 & alias IR2135, IR2233, IR2235 (PDIP28)
IR2133S & alias IR2135S, IR2233S, IR2235S (SOIC-28)
Datasheet: https://www.infineon.com/dgdl/Infineon-IR2x33-IR2x35-DataSheet-v01_00-EN.pdf?fileId=5546d462533600a4015355c890ba169f

ir2x3x

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aris-kimi , thanks for contributing,

A few comments I have during my review:

Both symbols:
- [ ] Pin 9 is LO3
- [ ] Pin 11 is LO1
- [ ] I'm troubled by the position of the pins. Something like schematic page 5 of the datasheet seems better. Tell me, r maybe you can provide a sample schema ?

Cheers,
Joel

**Comment by aris-kimi** [comment]
Thank you for your review, i added them as a variation from 1st page.
I will commit pin names changes after your reply.

In a schematic i am working i have used it like this:
εικόνα

But still changes expected.. If you think this should change as page 5 inform me to work on it.

**Comment by myfreescalewebpage** [comment]
I think yes, I will follow the diagram of the manufacturer. PLease.

**Comment by aris-kimi** [comment]
εικόνα
Only as a proposal.
Next `review fixes` commit will be as proposed previously by you. If you think this area is good to stay as shown here, inform me to commit again.
In the next commit height is also reduced by 400mils

**Comment by myfreescalewebpage** [comment]
I think it's nice.

**Comment by aris-kimi** [comment]
Fixed as proposed.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
