### PR TITLE
Added symbol for the Infineon BTS7004-1EPP Smart High-Side Power Switch

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Another Infineon Smart High Side Switch, the BTS7004-1EPP

I have a Pull request for the associated footprint for this symbol: https://github.com/KiCad/kicad-footprints/pull/553

Datasheet - https://www.infineon.com/dgdl/Infineon-BTS7004-1EPP-DS-v01_00-EN.pdf?fileId=5546d4626102d35a016147550a725555

screenshot from 2018-05-04 21-26-32

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
screenshot from 2018-05-04 21-35-21

**Comment by johnfwhitmore** [comment]
screenshot from 2018-05-04 21-38-51

**Comment by johnfwhitmore** [comment]
Single Travis error remaining is the footprint which is included in pull request:
https://github.com/KiCad/kicad-footprints/pull/553

**Comment by evanshultz** [comment]
Please make similar changes as I've requested at https://github.com/KiCad/kicad-symbols/pull/572.

**Comment by johnfwhitmore** [comment]
screenshot from 2018-05-24 21-21-32

**Comment by johnfwhitmore** [comment]
screenshot from 2018-05-24 21-30-08

**Comment by johnfwhitmore** [comment]
I tried stacking those "Not Connected" pins but Travis wasn't happy with that. As you've said I'll spread them about. 
Yes there are a number of PROFET switches in a number of families and most seem to follow this four pin arrangement but some seem not to have the DEN pin. The problem, in my head, is there are a lot of pin numberings and footprints used. That means that even though they share common pins they'll be numbered differently. I've just been looking at the High Side Switches thus far but now have to start looking at the low side so it might get worse before it gets better.

Can I still use this branch for changes?

**Comment by evanshultz** [comment]
I didn't ask you to stack NC pins; I asked you to place them around the other pins to maintain a consistent symbol body size. Thank you for doing that.

Switching from a high-side to a low-side switch involves a circuit change, so consistent symbols only apply for switches with the same "polarity". Missing a DEN pin is no problem if the other pins are consistent so the symbols are still generally interchangeable. The low-side switches would logically have a different pin arrangement that should be consistent for low-side pins.

Yes, please go ahead and keep using this branch.

**Comment by johnfwhitmore** [comment]
Miscommunication there. My fault, I wasn't suggesting that you'd asked me to stack the NC pins :-( I was just trying to state that I realised that the symbol as it stands ain't the best, given the placement of those NC pins. My previous attempt to make it better didn't work out but that was not at your suggestion. That was my own misguided attempt.

I've spaced the pins out and reduced the size of the symbol as a result. I'm not 100% sure the distinction or requirements for "Description" and "Keyword" fields so I should check the guidelines on that.

I've not rebased this repo but assume I'll be the only one changing those specific files.
screenshot from 2018-06-05 18-01-03

**Comment by evanshultz** [comment]
Looking nice now. Thanks!

Please place the NC pins so their end is along the part body and they're unlikely to be accidentally connected. As they are now, running a wire outside the part body could connect to the NC pins.

Description vs keywords probably aren't well described. Description usually starts with the datasheet description/title, then adds and information very important to the user or to distinguish symbols, and finishes with the package. Keywords are other common search terms to help guide users to the symbol.

Would you please show this symbol and other similar symbols in this family together so we could get an idea if they look like a proper "family" of symbols?

**Comment by johnfwhitmore** [comment]
There's a lot of differences in all these symbols. I've only included the single channel devices in the screen captures. Opps got them wrong have to redo those give me a minute...

**Comment by johnfwhitmore** [comment]
screenshot from 2018-06-09 17-35-58
screenshot from 2018-06-09 17-36-46
screenshot from 2018-06-09 17-37-14

**Comment by johnfwhitmore** [comment]
Can't send the schematic file for you to look at yourself so just the screen capture. There's a bit of variation in the PROFET symbols, so where to start. 

Let me know what you think. I guess I could go through them one at a time and straighten them out.

A lot don't stack Output pins. They share pins, apart from DEN, but their pin numbering is all different so I'm not sure that they can all share a symbol, even if they share pins and functionality. But thankfully I'm not an expert so perhaps there is a way around that.

**Comment by evanshultz** [comment]
The screenshot is great. Thanks for doing that.

They can't share a symbol, correct, but it looks like they could share a symbol design. Just modify the pin numbers and footprint info to fit each different package. And use ALIASes where possible. Stacking pins is a relatively newer convention for KiCad symbols so it's no wonder many of them aren't stacking.

We can just stick to your new symbols in this PR. No need to burden this with touching other things when we can get your new part merged faster. If you do want to make updates in a later PR that's great.

For the description, can you include the Rds(on), voltage, and current? I see some have that and I'd like the new parts to have it too. Also, add a comma between each section in the description (including before the package type). Then if you can rotate the NC pins so the pin body is inside the symbol outline I will merge this one. Thanks again!

**Comment by johnfwhitmore** [comment]
screenshot from 2018-06-15 22-05-18
screenshot from 2018-06-15 22-05-33

Sorry been busy for a few days. I will open a new PR and have a look at those other parts, tweeking them a little. One other question is that there is a Low Side Switch in the Infineon series. Should that go into Power Management as well?

I'm not sure that this symbol is fully correct but I'm getting there, I hope ;-)

**Comment by evanshultz** [comment]
Whoa. Sorry that I missed this update.

In the description please change `15Amps` to just `15A`, then I will merge this. Your newer PR to align the symbols can deal with any remaining cosmetic adjustment to this symbol as well as the others.

**Comment by johnfwhitmore** [comment]
No Worries ;)
Yeah I'll start a new PR to look at all those components, but I'm trying to clear up a few I've already out there. Started playing with a SMPS with chips not in the libs so I'm astray in the head. 

Thanks for all your help on this one. I'll start looking at the other Profets ASAP.

**Comment by evanshultz** [comment]
Thanks! I appreciate your effort to this get done.

In addition to aligning them graphically, aligning descriptions would be good too. :)

I also find I'm compiled a number of symbols in my personal lib from time to time and then take a bit to clean them out before more clutter appears. :)

**Comment by johnfwhitmore** [comment]
Thanks a million for that I'll start next step over the weekend, if I get time.

**Pull request merged**
