### PR TITLE
ISO1211 + ISO1212

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Create Digital Input Receiver Texas ISO1211 and ISO1212

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing

http://www.ti.com/lit/ds/symlink/iso1211.pdf

- [x] An example screenshot image is very helpful

iso1211

iso1212

- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by HubertD** [comment]
checked pin names, numbers and functions. looks good to me.

**Comment by evanshultz** [comment]
1. Please add the channel count to the description to better differentiate these symbols.
1. Output pins should to Tri-state type.
1. Let's make the SUB pins visible. They're not to be used in production, but they have a functional connection and could be used in testing or some other use. If they're hidden on the schematic, this symbol couldn't be used for developing a test fixture (for example) for these symbols.
1. What about putting EN at the bottom so you can align the IN and OUT pins across the symbol?
1. Flip the whole thing around so input is on the left and output on the right.

**Comment by myfreescalewebpage** [comment]
@evanshultz I realize my design it ugly now ! Will do a new one, agree with your comments :)

**Comment by myfreescalewebpage** [comment]
@evanshultz done! You can have a new review now :)

**Comment by evanshultz** [comment]
I feel like I won the lottery!

Now they look like:
image
image

Thanks!

**Comment by myfreescalewebpage** [comment]
loool thanks! Sorry to not have updated the screenshots myself :)

**Pull request merged**
