### PR TITLE
Added STM8S208CB with aliases

### PR DESCRIPTION
**Pull request by aris-kimi**
Aliases are:
STM8S208C8
STM8S208C6
STM8S207CB
STM8S207C8
STM8S207C6
Datasheet: https://www.st.com/resource/en/datasheet/stm8s208cb.pdf
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aris-kimi** [comment]
stm8s

**Comment by aris-kimi** [comment]
Hi there @myfreescalewebpage. Since i kept the engine running... Have a look please... Thank you for the patience!!

**Comment by myfreescalewebpage** [comment]
@aris-kimi  only one comment:

- [ ] You can decrease the height of the symbol by 100mil at the bottom, so you will have the VCAP at 100mil of the corner, as done with the previous PR.

Else, perfect, no comment to do!

Joel

**Comment by aris-kimi** [comment]
@myfreescalewebpage will it be ok to decrease the height by 200mill and transfer both vcap and reset to the right side in order to have symmetry in the body?

**Comment by aris-kimi** [comment]
stm8s

**Comment by myfreescalewebpage** [comment]
@aris-kimi it's also ok for me

**Comment by aris-kimi** [comment]
@myfreescalewebpage i think we are done. Thank you for the assistance.

**Comment by myfreescalewebpage** [comment]
Thanks for the quick fixes. Maybe the fastest pull request of the KiCad history !

**Pull request merged**
