### PR TITLE
Added LTC4370

### PR DESCRIPTION
**Pull request by 0xdec**
Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/4370f.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@0xdec thanks for this contribution

I do not agree at all with the design of the symbol, you should follow the KLC rules: positive power pins to the top, negative power pins at the bottom, other pins to the left and right.

Please update this, then will do the review.

Cheers,
Joel

**Comment by 0xdec** [comment]
@myfreescalewebpage sorry about that, I used the layout from the datasheet which is really nice for logical component placement. I will rework it with the symbol guidelines in mind.

**Comment by myfreescalewebpage** [comment]
Thanks, this is something important to get something clear across the library :)

**Comment by myfreescalewebpage** [comment]
@0xdec any news here ? Thanks :)

**Comment by 0xdec** [comment]
@myfreescalewebpage finally got around to fixing this

**Comment by myfreescalewebpage** [comment]
Hi @0xdec , thanks for contributing,

A few comments I have during my review:

LTC4370CDE:
- [ ] Alias not require, should just use a wildcare, please rename device to "LTC4370xDE"
- [ ] Description should ends with the package name: `OR Controller Current Sharing Controller N-Channel 2:1, DFN-16`
- [ ] EP pin should be Passive
- [ ] CPOx should be Passive to avoid ERC errors
- [ ] RANGE should be Passive to avoid ERC errors

LTC4370CMS:
- [ ] Alias not require, should just use a wildcare, please rename device to "LTC4370xMS"
- [ ] Description should ends with the package name: `OR Controller Current Sharing Controller N-Channel 2:1, MSOP-16`
- [ ] EP pin should be Passive
- [ ] CPOx should be Passive to avoid ERC errors
- [ ] RANGE should be Passive to avoid ERC errors

Cheers,
Joel

**Comment by 0xdec** [comment]
LTC4370xDE:
- [x]  Alias not required, should just use a wildcard, please rename device to "LTC4370xDE"
- [x]  Description should ends with the package name: `OR Controller Current Sharing Controller N-Channel 2:1, DFN-16`
- [x]  You are violating S3.3, see Travis log
- [x]  EP pin should be Passive
- [x]  CPOx should be Passive to avoid ERC errors
- [x]  RANGE should be Passive to avoid ERC errors

LTC4370xMS:
- [x]  Alias not required, should just use a wildcard, please rename device to "LTC4370xMS"
- [x]  Description should ends with the package name: `OR Controller Current Sharing Controller N-Channel 2:1, MSOP-16`
- [x]  You are violating S3.3, see Travis log
- [x]  EP doesn't exist on MS package
- [x]  CPOx should be Passive to avoid ERC errors
- [x]  RANGE should be Passive to avoid ERC errors

**Comment by myfreescalewebpage** [comment]
@0xdec thanks for all those fixes.
On LTC4370xDE EP pin has not been set to Passive, please fix it before we can merge.

**Comment by 0xdec** [comment]
@myfreescalewebpage good catch, fixed

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
