### PR TITLE
Add PS8802-x

### PR DESCRIPTION
**Pull request by strombom**
PS8802-1
PS8802-2
http://www.cel.com/pdf/datasheets/ps8802.pdf

image
image

image
image

Footprint: https://github.com/KiCad/kicad-footprints/pull/333

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by strombom** [comment]
All other optoisolators have all pins of passive type.

Should I remove the names of the pins so that travis allows them to be of passive type instead of power pins (which travis wants on top/bottom but which does not fit those components)?

**Comment by jkriege2** [comment]
Hmmm .. I would leave the pin-names, but make types to PASSIVE, we can then accept this exception to KLC. I think passive makes sense here, as people might want to use this OC in another way than connecting the emitter diectly to a power-source/GND and keeping the names makes sense for reference to the datasheet.

**Comment by strombom** [comment]
Ok now they are passive again.

image

image

**Comment by jkriege2** [comment]
Please fix the footprint library names and add a strike-through-line through the photodiodes in PS8802-2

Thanks,
JAN

**Comment by strombom** [comment]
Updated library and strike-through lines.

image

image

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
