### PR TITLE
added TPS2500/2501

### PR DESCRIPTION
**Pull request by jstjst**
added TPS2500/2501 Integrated USB power Switch with Boost Converter
http://www.ti.com/lit/ds/symlink/tps2500.pdf
grafik

### CODE REVIEW

**Comment by jstjst** [comment]
Footprint might be affected by https://github.com/KiCad/kicad-footprints/issues/1551

**Comment by myfreescalewebpage** [comment]
Hi @jstjst , thanks for contributing,

A few comments I have during my review:

TPS2500:
- [ ] Name of the symbol should be `TPS2500DRC` to avoid future conflict if the manufacturer add package options
- [ ] Description should ends with the package name and can be enhanced: `Integrated USB power Switch with Boost Converter, Light-Load, High-Efficiency Eco-mode, Control Scheme, Texas S-PVSON-10`
- [ ] You can reduce a bit the with of the symbol. 600mil is enough.
- [ ] Footprint filter should be `Texas*S*PVSON*N10*`
- [ ] I suggest ENUSB should be on the left near to EN
- [ ] GND and PGND must be on the bottom of the symbol
- [ ] Pin 11 should be stacked with GND
- [ ] ILIM should be Passive to avoid ERC errors
- [ ] SW is Power Input, you can move it above IN

TPS2501:
- [ ] Name of the symbol should be `TPS2501DRC` to avoid future conflict if the manufacturer add package options
- [ ] Description should ends with the package name and can be enhanced: `Integrated USB power Switch with Boost Converter, Light-Load, High-Efficiency Eco-mode, Constant Frequency, Texas S-PVSON-10`

Cheers,
Joel

**Comment by jstjst** [comment]
TPS2500:
* [ ]  Name of the symbol should be `TPS2500DRC` to avoid future conflict if the manufacturer add package options
 * [ ]  Description should ends with the package name and can be enhanced: `Integrated USB power Switch with Boost Converter, Light-Load, High-Efficiency Eco-mode, Control Scheme, Texas S-PVSON-10`
 * [ ]  You can reduce a bit the with of the symbol. 600mil is enough.
 * [ ]  Footprint filter should be `Texas*S*PVSON*N10*`
 * [ ]  I suggest ENUSB should be on the left near to EN
 * [ ]  GND and PGND must be on the bottom of the symbol
 * [ ]  Pin 11 should be stacked with GND
 * [ ]  ILIM should be Passive to avoid ERC errors
 * [ ]  SW is Power Input, you can move it above IN

TPS2501:
 * [ ]  Name of the symbol should be `TPS2501DRC` to avoid future conflict if the manufacturer add package options
 * [ ]  Description should ends with the package name and can be enhanced: `Integrated USB power Switch with Boost Converter, Light-Load, High-Efficiency Eco-mode, Constant Frequency, Texas S-PVSON-10`

**Comment by jstjst** [comment]
- Stacked Pins 2/5/11 since they must be connected together
- Changed ILIM to Passive
- Moved SW and ENUSB
- Changed Footprint filter
- Renamed Symbol and changed description

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes.

Agree to stack pins 2/5/11, but you have an error on this. All pins must be named GND in this case (see also travis error).

ILIM and SW types not changed yet.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Merging.

**Pull request merged**
