### PR TITLE
Add Symbol for ESP32-WROOM-32 RF module

### PR DESCRIPTION
**Pull request by HubertD**
Cannot believe this is not already part of the library :-)

Datasheet: https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/722

sym-esp32-wroom-32

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by HubertD** [comment]
esp32-wroom-32

**Comment by diegoherranz** [comment]
I've checked the pinout and it looks correct.
A minor comment: I would expect SENSOR_VP on top of SENSOR_VN, positive one first (and lower pin number too).

Thanks for submitting this.

**Comment by diegoherranz** [comment]
Thanks for the update. It looks good to me.

**Comment by diegoherranz** [comment]
While reviewing https://github.com/KiCad/kicad-footprints/pull/767, I've noticed that ESP32-WROOM-32D is the same as ESP32-WROOM-32 symbol-wise.
Could you make the ESP32-WROOM-32D an alias of ESP32-WROOM-32?

Thanks!

**Comment by diegoherranz** [comment]
Hi, @HubertD 

Thanks for creating the alias.
The ESP32-WROOM-32U, however, despite having the same symbol, needs a different footprint so I believe that it requires an independent symbol so that it can be associated with RF_Module:ESP32-WROOM-32U.

So, can you either add another symbol for the 32U or simply remove it keeping the 32 and the 32D?
If it's the latter I can create a PR to add the 32U.

Many thanks!

**Comment by HubertD** [comment]
i removed the ESP32-WROOM-32U alias again because it needs a different footprint (no keep-out zone necessary).
@diegoherranz  would be glad if you took the job to add a new symbol for ESP32-WROOM-32U since I don't have much time to spare in the next two weeks

**Comment by diegoherranz** [comment]
Looks good to me. As soon as this gets merged, I'll submit a pull request with the ESP32-WROOM-32U.
Many thanks!

**Comment by diegoherranz** [comment]
Is everyone happy with this one? When it gets merged I will submit the ESP32-WROOM-32U (different footprint). Thanks!

**Comment by HubertD** [comment]
any news?

**Comment by chertov** [comment]
Merge please! I'm waiting ESP32-WROOM in library
Thanks for the symbol!

**Comment by DanSGiesbrecht** [comment]
I will revive this review ASAP. Thank you for your patience.

**Comment by DanSGiesbrecht** [comment]
@HubertD looks great! Thank you again for contributing, and for your patience.

**Pull request merged**
