### PR TITLE
Add RClamp0502B, RClamp0502BA and RClamp0582B

### PR DESCRIPTION
**Pull request by kacper-ka**
This merge adds **RClamp0502B**, **RClamp0502BA** and **RClamp0582B** unidirectional ESD protections diodes, manufactured by **Semtech**.

**RClamp0502BA** and **RClamp0582B** are added as *aliases* of **RClamp0502B**.

## Datasheets
- **RClamp0502B**: https://www.semtech.com/products/circuit-protection/low-capacitance/rclamp0502b
- **RClamp0502BA**: https://www.semtech.com/products/circuit-protection/low-capacitance/rclamp0502ba
- **RClamp0582B**: https://www.semtech.com/products/circuit-protection/low-capacitance/rclamp0582b

## Screenshots
Screenshot from 2020-09-24 10-56-33

## KLC violations
None.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- ~~If there are matching footprint PRs, provide link(s) as appropriate~~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- ~~Give a reason behind any intentional library convention rule violation.~~

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @kacper-ka , thanks for contributing,

Not a full review but some comments

- [ ] The two diodes are not independent so I suggest to have a design as done for "D_Zener_x2_ACom_AKK" for example.
- [ ] Can you indicate datasheet link to the PDF itself ?
- [ ] You can simplify the end of the description (remove "(SOT-416, SOT-523)")

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@kacper-ka ping

**Comment by myfreescalewebpage** [comment]
Thanks for the answer.
1. Yes please
2. ok
3. ok thanks

**Comment by myfreescalewebpage** [comment]
@kacper-ka any news here ?

**Comment by kacper-ka** [comment]
@myfreescalewebpage yeah, sorry for the delay.

**Comment by myfreescalewebpage** [comment]
No problem. Looks great. Two final comments:

- [ ] The zener I was speaking about as reference above has changed. The name is now "D_Zener_Dual_CommonAnode_AKK_Parallel" and it's rotated. Can you have a look and rotate +move your symbol to have the same compared to "D_Zener_Dual_CommonAnode_AKK_Parallel" please ?
- [ ] You have forgotten to update the package name in the description of the aliases (you are not the first and you will not be the last one to make this mistake !)

Joel

**Comment by kacper-ka** [comment]
Ok, the second one was straightforward but I have problem with locating the symbol you mentioned: `D_Zener_Dual_CommonAnode_AKK_Parallel`. I cannot find it on `master` branch, I have fetched and pulled changes from the upstream. Has it been already published?

**Comment by myfreescalewebpage** [comment]
Thanks. My last comment:
- [ ] The small line on the cathode should be on the other side

Capture

**Comment by myfreescalewebpage** [comment]
Please check my previous screenshot, this not what I expected, look also  "D_Zener_Dual_CommonAnode_AKK_Parallel" please

**Comment by myfreescalewebpage** [comment]
To be moved by 50mil on the left

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
