### PR TITLE
Add Kemet EC2-*NU Relays

### PR DESCRIPTION
**Pull request by gcormier**
The Kemet EC2-NU series have the same pinout and footprint as Omron G6S-2 series.

Datasheet : https://content.kemet.com/datasheets/KEM_R7002_EC2_EE2.pdf

**Kemet Pinout**
image

**Kemet Footprint**
image

**Omron Pinout and Footprint**
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)

### CODE REVIEW

**Comment by gcormier** [comment]
Sorry about that revert madness.

**Comment by myfreescalewebpage** [comment]
Hi @gcormier , thanks for contributing,

A few comments I have during my review:

- [ ] Can you add the coil voltage in the descriptions ? Example at https://github.com/KiCad/kicad-symbols/pull/2557
- [ ] EC2-3NU has not the right datasheet link 

Cheers,
Joel

**Comment by gcormier** [comment]
Sure - this is pretty old, so why don't I open a new PR with these changes and the additions you requested so I don't have to deal with re-basing which I failed at last week :)

**Comment by myfreescalewebpage** [comment]
Actually git is happy with merging this branch without rebasing :) No need to create a new one.

Capture

**Comment by gcormier** [comment]
Sweet, sorry I missed that comment some how - this should be good to go.

**Comment by myfreescalewebpage** [comment]
I just realized I'm reviewing this PR https://github.com/KiCad/kicad-symbols/pull/2631 which propose the same part + some other references of the same manufacturer.

I check few things and realize also the Kemet are bigger than the Omron. I conclude the packages are not compatible, which give an advantage to the other PR.

We keep yours opened for the moment, but will probably be rejected.

**Comment by yankee14** [comment]
@gcormier sorry about that, I should have checked whether this was already an open PR

**Comment by gcormier** [comment]
@yankee14 No problem, yours looks much more comprehensive!

**Comment by myfreescalewebpage** [comment]
Thanks @gcormier  and @yankee14 :) nice to work with you !

**Comment by myfreescalewebpage** [comment]
The other PR has been merged now.
Thanks for your understanding @gcormier 
Joel

**Pull request closed without merging**
