### PR TITLE
Add DMC2053UVT

### PR DESCRIPTION
**Pull request by gcormier**
New symbol. Paired mosfets for high side switching.

- [x] Need description feedback
- [x] Need keyword feedback
- [x] Check passive pins 2/5 - should they be power?

Submitted
image

Example usage to control power to a sub-circuit/load.
image

Datasheet
https://www.diodes.com/assets/Datasheets/DMC2053UVT.pdf

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@gcormier the device should be added separated in two units, see for example FDG1024NZ in Transistor_FET library.
Joel

**Comment by gcormier** [comment]
Even though one is a P-channel and one is an N-channel?

**Comment by myfreescalewebpage** [comment]
Yes.

**Comment by gcormier** [comment]
Updated. 

image


I've messed up git though somehow.

**Comment by myfreescalewebpage** [comment]
@gcormier the library can't opened, something is wrong in the DCM file, see the git diff, ENDCMP and # are missing.
Joel

**Comment by gcormier** [comment]
I think it's fixed up now.

**Comment by myfreescalewebpage** [comment]
@gcormier here is my complete review:

- [ ] Description should be `4.6A/3.2A Id, 20V Vds, Complementary pair enhancement mode P-Channel and N-Channel MOSFET, TSOT-23-6`
- [ ] Keywords can be `complementary mosfet`
- [ ] The diode on unit B is not in the right direction
- [ ] Footprint filter should be `TSOT?23*`
- [ ] All pins should be Passive
- [ ] Pins 2 and 4 are crossed

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the tests.

**Comment by myfreescalewebpage** [comment]
Do not know why travis tests are not more launched for this pull request. Doubled checked with local scripts, every think seems ok for me on this symbol. Merging.

**Pull request merged**
