### PR TITLE
Ltm4637

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.analog.com/media/en/technical-documentation/data-sheets/4637fc.pdf

image

Uses footprints merged at https://github.com/KiCad/kicad-footprints/pull/1027. I just realized I didn't put `mm` after the body size on the footprints: **should I change the footprints now and update the FP filters here?** It's such a specialized footprint that the problems it could cause will be limited.

Used the 'Duplicate' function in libedit to make the 'V' symbol; just renamed and changed the footprint and FP filter.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz , thanks for contributing,

A few comments I have during my review:

LTM4637V
- [ ] I think the symbol should be "LTM4637xV"
- [ ] I would suggest to fix the footprint name right now and the footprint / fp filter here. I can review the footprint change too if it's just the name.
- [ ] TEMP should be Open Collector
- [ ] TRACK/SS should be Passive
- [ ] DIFF_OUT is Output
- [ ] VFB should be Passive I think (not sure)

LTM4637Y
- [ ] I think the symbol should be "LTM4637xY"
- [ ] I would suggest to fix the footprint name right now and the footprint / fp filter here. I can review the footprint change too if it's just the name.
- [ ] TEMP should be Open Collector
- [ ] TRACK/SS should be Passive
- [ ] DIFF_OUT is Output
- [ ] VFB should be Passive I think (not sure)

Cheers,
Joel

**Comment by evanshultz** [comment]
Thanks for looking!

Where I still wanted to share something:
- TEMP is not Open Collector since that wold imply an output. I chose Passive since it's intended to have just a resistor from a positive voltage for temp monitoring.
- TRACK/SS in also an input for connecting modules together, but I changed to Passive.
- Chose VFB to be Input since it's essentially going to an opamp/OTA input and we use Input for opamp +/- pins.

Let me know if all the above looks OK or if you'd like more changes.

Footprint names fixed in https://github.com/KiCad/kicad-footprints/pull/2173. I assigned you to that PR.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks for the quick fixes

- TEMP : ok it's understood, I now see it's only to sense the IC temperature. Passive is great.
- VFB : ok with the detail you have given.

I have no more comment, merging right now too.

Joel

**Pull request merged**
