### PR TITLE
Driver_Motor: DRV8662

### PR DESCRIPTION
**Pull request by stephf0716**
Piezo Haptic Driver with Integrated Boost Converter
http://www.ti.com/lit/ds/symlink/drv8662.pdf

drv8662

### CODE REVIEW

**Comment by jkriege2** [comment]
Please fix the issues reported by out Travis check scripts (see link at the bottom of the PR-discussion):

```
Checking symbol 'DRV8662':
  Violating S3.3
    Symbol outline and fill requirements
    Component line is thickness 0mil, recommended is 10mil
  Violating S4.1
    Pin requirements
    Pins not located on 100mil grid:
     - Pin FB (3), @ (600, 350)
     - Pin REXT (15), @ (600, 150)
  Violating S4.2
    Pins should be arranged by function
    Positive power pins should be placed at top of symbol
     - Pin VDD (2) @ (-600,600)
  Violating S4.4
    Pin electrical type should match pin function
    Power pins should be of type POWER INPUT or POWER OUTPUT
     - Pin GND (6) @ (100,-900) is of type INPUT
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Specified footprint library does not exist
     - Footprint library 'Housings_DFN_QFN' was not found
    Footprint filter 'TSSOP-16*4.4x5mm*P0.65mm*' does not match the footprint 'Housings_DFN_QFN:QFN-20-1EP_4x4mm_Pitch0.5mm' set for this symbol.
  Violating S5.2
    Footprint filters should match all appropriate footprints
    Footprint filter 'TSSOP-16*4.4x5mm*P0.65mm*' seems to contain pin-number, but should not!
    Minuses and underscores in footprint filter 'TSSOP-16*4.4x5mm*P0.65mm*' should be escaped with '?' or '*'.
```

**Comment by jkriege2** [comment]
Hi!

the symbol looks good now, but I think you picked the wrong footprint: the QFN-20 has a slightly different EP, different pin-pads and no thermal vias ... could you make a matching footprint, based on the already existing `Texas_S-PVQFN-N...`-footprint? That would be great ... 

best,
JAN

**Comment by stephf0716** [comment]
I can definitely do that. This is my first time contributing to an open source project and I am very excited!

**Comment by stephf0716** [comment]
Sorry, I am obviously a newbie, I didn't realize "Close and comment" meant to close the PR. I guess this is really a hands-on learning experience.

**Comment by jkriege2** [comment]
Hi!

since the footprint is merged, please use it in the symbol, so we can merge this!

cu
JAN

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
