### PR TITLE
Adding the C8051F380/1/2/3/4/5/6/7/C family (LQFP32)

### PR DESCRIPTION
**Pull request by JonathSpirit**
Adding the silicon-labs "Full Speed USB Flash MCU Family" (C8051F380/1/2/3/4/5/6/7/C) in LQFP32

https://www.silabs.com/documents/public/data-sheets/C8051F38x.pdf

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
See first my comment at #2390. Then will do a full review of this symbol too.

**Comment by JonathSpirit** [comment]
image

image

image

**Comment by myfreescalewebpage** [comment]
Following the other merge, can you rebase here please ?

**Comment by myfreescalewebpage** [comment]
Thanks, no comment, merging.

**Pull request merged**
