### PR TITLE
Add DIN rail adapter

### PR DESCRIPTION
**Pull request by ferdymercury**
image

Matching footprint PR: https://github.com/KiCad/kicad-footprints/pull/1041

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ferdymercury** [comment]
Datasheet is https://www.phoenixcontact.com/online/portal/us?uri=pxc-oc-itemdetail:pid=1201578&library=usen&tab=1

**Comment by myfreescalewebpage** [comment]
Hi @ferdymercury , thanks for contributing,

Librarians, is it really a "device" that is to be added in the lib ? If  going this was we will add many screws, nuts, etc etc and I'm not sure Kicad aimed to replace Solidworks !!!!

Cheers,
Joel

**Comment by ferdymercury** [comment]
Well, I can remove the screws. But this has the same character than a "Mounting Hole". It is just an alias for three mounting holes. The point is that its footprint will tell you where not to put components based on the courtyard etc.

**Comment by poeschlr** [comment]
I would allow this in the lib.

The question is if all din rail connectors come with 3 mounting holes. Maybe a better symbol would be to show a simplified part outline as viewed from the side instead of showing one from the top. (The side view might be a lot more generic)

**Comment by myfreescalewebpage** [comment]
@poeschlr @ferdymercury I do not agree, it's not a mounting hole ! A mounting hole is important to add a hole in the PCB. In this PR we are taking about a piece of plastic on a DIN rail ! Do you really fix your PCB on it directly with no other enclosure ?! This kind of part is made to be fixed on the back of an enclosure to be mounted on a DIN rail....

I agree with @poeschlr that if the part need to be added to the library, a symbol representing the form of the clip is better.

> The question is if all din rail connectors come with 3 mounting holes.

No, some have two holes only, others are just some clips.

Cheers
Joel

**Comment by ferdymercury** [comment]
I really fix my PCB directly to this adapter. Did it last month.

**Comment by ferdymercury** [comment]
See for example https://eckstein-shop.de/Adafruit-DIN-Rail-RJ-45-To-Terminal-Block-Adapter-Vertical-Jack?curr=EUR&gclid=CjwKCAiA9efgBRAYEiwAUT-jtFRlM3fOtaPwg4uSzSYQx-1dPlB9dj0kyxGrYXxToUJik9T1SRVthhoCqnQQAvD_BwE

**Comment by myfreescalewebpage** [comment]
Okay... never seen this in the industry but why not.

Can you rework the design of the symbol, for example something looking like the profile of the part ?

**Comment by ferdymercury** [comment]
Reworked.
image

**Comment by myfreescalewebpage** [comment]
@ferdymercury thanks.

Additional comment:
- [ ] You should swap reference and name, see MountingHole part for example.

Cheers,
Joel

**Comment by ferdymercury** [comment]
Thanks Joel. Fixed.

**Comment by myfreescalewebpage** [comment]
@ferdymercury thanks, no other comment to do.

If other librarians are okay, this is ready to be merged when the footprint will be accepted (https://github.com/KiCad/kicad-footprints/pull/1041).

Joel

**Comment by myfreescalewebpage** [comment]
@ferdymercury I think this is ready to be merged. Thanks for the job !

Cheers,
Joel

**Pull request merged**
