### PR TITLE
Add ATtiny406/806/1606 and 416/816/1616/3216

### PR DESCRIPTION
**Pull request by fauxpark**
Previously added in #848 (not merged), this PR also includes the x06 series, so those symbols can be made aliases instead.

Datasheets:
406: http://ww1.microchip.com/downloads/en/DeviceDoc/Microchip%208bit%20mcu%20AVR%20ATtiny406%20data%20sheet%2040001976A.pdf
806/1606: http://ww1.microchip.com/downloads/en/DeviceDoc/ATtiny806_1606_Data_Sheet_40002029A.pdf

416/816: http://ww1.microchip.com/downloads/en/DeviceDoc/40001913A.pdf
1616/3216: http://ww1.microchip.com/downloads/en/DeviceDoc/ATtiny3216_ATtiny1616-data-sheet-40001997B.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by fauxpark** [comment]
It seems there is a missing VQFN footprint. [Here](http://ww1.microchip.com/downloads/en/DeviceDoc/20%20Lead%20VQFN%203x3x0_9mm_1_7EP%20U2B%20C04-21496a.pdf) is the Microchip packaging spec, it should be easy to add it to the script.

**Comment by evanshultz** [comment]
Of course the PR I just merged broke this one. Can you please fix the branch conflict?

These symbols have power pins named VCC but the datasheet shows VDD. Maybe it's not a big issue now, but is this something to add to #387 and address across all symbols at some point?

When you submit multiple symbols, would you mind to include screenshots of all symbols? That makes it faster and easier to review.

**Comment by evanshultz** [comment]
Oh, and should the description say "VQFN" instead of "QFN"? I understand https://github.com/KiCad/kicad-symbols/pull/1043#issuecomment-428743384 to mean the actual work of any footprint manipulation will come later, but should the descriptions be done now?

**Comment by fauxpark** [comment]
I was expecting the conflict :P I've been juggling these symbols around through all of these PRs.

The power pin naming is annoyingly inconsistent with the majority of these AVRs. I wasn't sure what to do with that so I just stuck with VCC for now. I think it's still fairly obvious what is meant, but if you'd prefer to use the exact naming from the datasheet I can change it.

I didn't think it was necessary to show the SOIC package symbol since it's essentially the same, but I realise you might need to quickly check the pin numbering etc. since it is different. I'll remember that next time. Here it is just in case:

406s

As for the package description, it can be done now, but I prefer to do mass changes like that in one go to avoid fragmentation of work. In this case the footprint is not yet in the libs so I will change it to VQFN.

**Comment by evanshultz** [comment]
This is all good.

On Monday I'll make the footprint if it hasn't been done already and add the two items to #387 if they aren't there. Thanks!

**Comment by evanshultz** [comment]
If the footprint filter gets a leading "V" this should be green and can be merged.

**Comment by fauxpark** [comment]
Whoops, sorry.

**Pull request merged**
