### PR TITLE
Add TI SN74LVC1T45{DBV,DCK,DRL}

### PR DESCRIPTION
**Pull request by whitequark**
This PR adds the symbols for [TI SN74LVC1T45](http://www.ti.com/lit/ds/symlink/sn74lvc1t45.pdf) Single-Bit Dual-Supply Bus Transceiver With Configurable Voltage Translation and 3-State Outputs, for SOT and SC packages. All three variants are identical other than for footprint selector/filter.

Screenshot:
screenshot_20180514_035739
Footprint PR(s):
  - [ ] https://github.com/KiCad/kicad-footprints/pull/581

Datasheet information:
screenshot_20180514_042123
screenshot_20180514_042129
screenshot_20180514_042140
screenshot_20180514_042148

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Please add package types to the end of the description. For DBV, that is `SOT-23-6`. Then I can merge!

You used filled triangles, and the existing symbols have both hollow (most) and filled (a few). Plus I can see pin name offset isn't 20mil on many symbols in the lib. Add them to the list of inconsistencies...

**Comment by whitequark** [comment]
Package names added.

**Comment by evanshultz** [comment]
The footprint name isn't going to change so I'll merge.

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
