### PR TITLE
Added LED_Dual_CACA to Device.lib

### PR DESCRIPTION
**Pull request by kcozens**
Added missing LED_Dual_CACA to Device.lib (counterpart to LED_Dual_ACAC)
------------
led_dual_caca

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @kcozens , thanks for contributing,

A few comments I have during my review:

- [ ] You have badly copy/paste the description from the ACAC version, it should be `Dual LED, anodes on pins 2 and 4` for this one :)

Travis warnings accepted for consistency with the others LEDs.

Cheers,
Joel

**Comment by fauxpark** [comment]
> it should be `Dual LED, anodes on pins 2 and 4` for this one

Actually, it should be `Dual LED, cathodes on pins 1 and 3` to match the rest of the dual LED descriptions (except for the two common anode ones, of course).

**Comment by kcozens** [comment]
Joel, thanks for catching the error in the description. I copied another part and modified it. I didn't realize there was a description field. I haven't used it with any of the parts I have created for myself. As to Travis errors, I don't know anything that. I will look for, and read, information about contributing to the libraries before I make any future contributions to them.

**Comment by myfreescalewebpage** [comment]
@fauxpark 

> Actually, it should be Dual LED, cathodes on pins 1 and 3 to match the other two.

That's totally the same and depends if you prefer keeping pin type or pin number from one device to another one...

@kcozens 

Thanks, this is the only things to modify for this contribution, then I can merge the PR.

Joel

**Comment by fauxpark** [comment]
> That's totally the same and depends if you prefer keeping pin type or pin number from one device to another one...

It's arbitrary, yes, but it's about consistency. Look at any of the RGB LED, diode or transistor symbols in this lib - their descriptions all have a specific structure between them which users should expect not to be deviated from (unless absolutely necessary).

IMO it's little details like this that make the libs seem more polished and professional.

**Comment by myfreescalewebpage** [comment]
There is only two other LED_Dual* device, but I agree they both speak about the cathodes in the description. However, LED RGB to not have the same description format at all...

@kcozens modify the way you want I don't think this kind of detail is so much important. That's only the description field, the name you have chosen is good.

Joel

**Comment by fauxpark** [comment]
> LED RGB to not have the same description format at all...

They absolutely do. I made sure of this (I cleaned up the Device lib a while back):

```
LED_ARGB: RGB LED, anode/red/green/blue
LED_BARG: RGB LED, blue/anode/red/green
LED_BGRA: RGB LED, blue/green/red/anode
LED_CRGB: RGB LED, cathode/red/green/blue
LED_RABG: RGB LED, red/anode/blue/green
LED_RAGB: RGB LED, red/anode/green/blue
LED_RCBG: RGB LED, red/cathode/blue/green
LED_RCGB: RGB LED, red/cathode/green/blue
```

**Comment by myfreescalewebpage** [comment]
@fauxpark compared to led dual of course !

LED_Dual_AACC: Dual LED, cathodes on pins 3 and 4
Led_Dual_ACAC : Dual LED, cathodes on pins 2 and 4

So proposing "Dual LED, cathodes on pins 1 and 3" or "Dual LED, anodes on pins 2 and 4" for LED_Dual_CACA is absolutely identical

**Comment by fauxpark** [comment]
It is "identical", yes. But it's not consistent with the existing two symbols.

**Comment by myfreescalewebpage** [comment]
Probably, ok for "Dual LED, cathodes on pins 1 and 3"

**Comment by myfreescalewebpage** [comment]
Hi @kcozens are you still alive on this subject ? Thanks.

**Comment by kcozens** [comment]
I've pushed the change to the description.

**Comment by evanshultz** [comment]
I support questioning the ways things are done to hopefully improve the library, but if a scheme is already in place and it works well then we should be consistent. Thanks all for making this symbol align before merging.

**Comment by myfreescalewebpage** [comment]
Thanks @kcozens for this fix, can be merged now !

**Pull request merged**
