### PR TITLE
Added Recom RPM-family of DC/DC converters to symbol lib (1A, 2A, 3A and 6A, non-isolating)

### PR DESCRIPTION
**Pull request by fhw72**
Added RECOM RPM-family of DC/DC converters to symbol lib (3Amp, 6Amp, non-isolating)

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
https://www.recom-power.com/pdf/Innoline/RPM-1.0.pdf
https://www.recom-power.com/pdf/Innoline/RPM-2.0.pdf
https://www.recom-power.com/pdf/Innoline/RPM-3.0.pdf
https://www.recom-power.com/pdf/Innoline/RPM-6.0.pdf

- [x] An example screenshot image is very helpful
screenshot 2019-02-06 14 28 38

Added footprint with PR#1382 in footprint-lib.

screenshot 2019-02-06 14 30 02

- [x] Deviation from KLC rules for pins C5+ E5.
    They are used to control the output voltage and are strongly coupled to the output voltage pin.
    (Please see datasheet and screenshot).

screenshot 2019-02-06 15 32 02

### CODE REVIEW

**Comment by fhw72** [comment]
I've created a footprint for it... but I'm really not sure where to place it.
Maybe a mod can import it to the correct library?!


[Converter_DCDC_Recom_RPMx.x-x.0.kicad_mod.txt](https://github.com/KiCad/kicad-symbols/files/2837229/Converter_DCDC_Recom_RPMx.x-x.0.kicad_mod.txt)

**Comment by myfreescalewebpage** [comment]
@fhw72 you should submit a pull request on the footprint repository for the kicad_mod file: https://github.com/KiCad/kicad-footprints

**Comment by fhw72** [comment]
yes...I filed a pull request PR#1382 in footprint-lib.

**Comment by poeschlr** [comment]
Footprint has been merged

**Comment by myfreescalewebpage** [comment]
Hi @fhw72 , thanks for contributing,

A few comments I have during my review:

- [ ] The symbol should not have a dash line, this is reserved for isolated converters
- [ ] Datasheet of RPM5.0-6.0 seems not correct, should be `https://www.recom-power.com/pdf/Innoline/RPM-6.0.pdf`
- [ ] SEQ pin should be Passive to avoid ERC errors
- [ ] NC pin should be moved on the border outline of the symbol
- [ ] The symbol is very large, I propose the following design:

capture

Cheers,
Joel

**Comment by fhw72** [comment]
Hi Joel,
I changed the symbol according to your suggestion and I also pushed the correct files to the branch now. Sorry about the confustion.
BR, Frank

**Comment by myfreescalewebpage** [comment]
Hi @fhw72 looks great, no more comment to do on this PR, merging.

**Pull request merged**
