### PR TITLE
Add ATAES132ASH

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Crypto EEPROM in SOIC-8 package

image

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/ATAES132A-Data-Sheet-40002023A.pdf

---

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @SchrodingersGat , thanks for contributing,

A few comments I have during my review:

- [ ] The name of the part should be "ATAES132A-SH"
- [ ] I think we can make it similar to some 25LCxx eeprom already in the library, what do you think of the following proposition:

Capture

Cheers,
Joel

**Comment by SchrodingersGat** [comment]
Ok, changes as requested!

**Comment by SchrodingersGat** [comment]
image

**Comment by myfreescalewebpage** [comment]
Thanks, merging!

**Pull request merged**
