### PR TITLE
Fix naming convention for Device.lib

### LINKED ISSUE #861: More consistent naming for symbols in Device.lib
An offshoot of https://github.com/KiCad/kicad-symbols/pull/831#issuecomment-414030052.

I see some issues are being prebooked for v6, so I thought I should add this list of naming tweaks:

|Old Name                     |New Name                           |
|-----------------------------|-----------------------------------|
|`Amperemeter_AC`             |`Ammeter_AC`                       |
|`Amperemeter_DC`             |`Ammeter_DC`                       |
|`CP1`                        |`CP_US`                            |
|`CP1_Small`                  |`CP_Small_US`                      |
|`CTRIM`                      |`C_Trim`                           |
|`CTRIM_DIF`                  |`C_Trim_Diff`                      |
|`DIAC_ALT`                   |`DIAC_Alt`                         |
|`D_ALT`                      |`D_Alt`                            |
|`D_Capacitance_ALT`          |`D_Capacitance_Alt`                |
|`D_Photo_ALT`                |`D_Photo_Alt`                      |
|`D_Radiation_ALT`            |`D_Radiation_Alt`                  |
|`D_Schottky_Small_ALT`       |`D_Schottky_Small_Alt`             |
|`D_Schottky_x2_ACom_AKK`     |`D_Schottky_Dual_CommonAnode_AKK`  |
|`D_Schottky_x2_ACom_KAK`     |`D_Schottky_Dual_CommonAnode_KAK`  |
|`D_Schottky_x2_ACom_KKA`     |`D_Schottky_Dual_CommonAnode_KKA`  |
|`D_Schottky_x2_KCom_AAK`     |`D_Schottky_Dual_CommonCathode_AAK`|
|`D_Schottky_x2_KCom_AKA`     |`D_Schottky_Dual_CommonCathode_AKA`|
|`D_Schottky_x2_KCom_KAA`     |`D_Schottky_Dual_CommonCathode_KAA`|
|`D_Schottky_x2_Serial_ACK`   |`D_Schottky_Dual_Serial_ACK`       |
|`D_Schottky_x2_Serial_AKC`   |`D_Schottky_Dual_Serial_AKC`       |
|`D_Schottky_x2_Serial_CAK`   |`D_Schottky_Dual_Serial_CAK`       |
|`D_Schottky_x2_Serial_CKA`   |`D_Schottky_Dual_Serial_CKA`       |
|`D_Schottky_x2_Serial_KAC`   |`D_Schottky_Dual_Serial_KAC`       |
|`D_Schottky_x2_Serial_KCA`   |`D_Schottky_Dual_Serial_KCA`       |
|`D_Small_ALT`                |`D_Small_Alt`                      |
|`D_TVS_ALT`                  |`D_TVS_Alt`                        |
|`D_TVS_x2_AAC`               |`D_TVS_Dual_AAC`                   |
|`D_TVS_x2_ACA`               |`D_TVS_Dual_ACA`                   |
|`D_TVS_x2_CAA`               |`D_TVS_Dual_CAA`                   |
|`D_Temperature_Dependent_ALT`|`D_TemperatureDependent_Alt`       |
|`D_Tunnel_ALT`               |`D_Tunnel_Alt`                     |
|`D_Unitunnel_ALT`            |`D_Unitunnel_Alt`                  |
|`D_Zener_ALT`                |`D_Zener_Alt`                      |
|`D_Zener_Small_ALT`          |`D_Zener_Small_Alt`                |
|`D_Zener_x2_ACom_AKK`        |`D_Zener_Dual_CommonAnode_AKK`     |
|`D_Zener_x2_ACom_KAK`        |`D_Zener_Dual_CommonAnode_KAK`     |
|`D_Zener_x2_ACom_KKA`        |`D_Zener_Dual_CommonAnode_KKA`     |
|`D_Zener_x2_KCom_AAK`        |`D_Zener_Dual_CommonCathode_AAK`   |
|`D_Zener_x2_KCom_AKA`        |`D_Zener_Dual_CommonCathode_AKA`   |
|`D_Zener_x2_KCom_KAA`        |`D_Zener_Dual_CommonCathode_KAA`   |
|`D_x2_ACom_AKK`              |`D_Dual_CommonAnode_AKK`           |
|`D_x2_ACom_KAK`              |`D_Dual_CommonAnode_KAK`           |
|`D_x2_ACom_KKA`              |`D_Dual_CommonAnode_KKA`           |
|`D_x2_KCom_AAK`              |`D_Dual_CommonCathode_AAK`         |
|`D_x2_KCom_AKA`              |`D_Dual_CommonCathode_AKA`         |
|`D_x2_KCom_KAA`              |`D_Dual_CommonCathode_KAA`         |
|`D_x2_Serial_ACK`            |`D_Dual_Serial_ACK`                |
|`D_x2_Serial_AKC`            |`D_Dual_Serial_AKC`                |
|`D_x2_Serial_CAK`            |`D_Dual_Serial_CAK`                |
|`D_x2_Serial_CKA`            |`D_Dual_Serial_CKA`                |
|`D_x2_Serial_KAC`            |`D_Dual_Serial_KAC`                |
|`D_x2_Serial_KCA`            |`D_Dual_Serial_KCA`                |
|`Delay_Line`                 |`DelayLine`                        |
|`Electromagnetic_Actor`      |`ElectromagneticActor`             |
|`Ferrite_Bead`               |`FerriteBead`                      |
|`Ferrite_Bead_Small`         |`FerriteBead_Small`                |
|`Frequency_Counter`          |`FrequencyCounter`                 |
|`Hall_Generator`             |`HallGenerator`                    |
|`LED_ALT`                    |`LED_Alt`                          |
|`LED_CRGB`                   |`LED_KRGB`                         |
|`LED_Dual_2pin`              |`LED_Dual_Bidirectional`           |
|`LED_Dual_AAC`               |`LED_Dual_AAK`                     |
|`LED_Dual_AACC`              |`LED_Dual_AAKK`                    |
|`LED_Dual_ACA`               |`LED_Dual_AKA`                     |
|`LED_Dual_ACAC`              |`LED_Dual_AKAK`                    |
|`LED_Dual_CAC`               |`LED_Dual_KAK`                     |
|`LED_Dual_CCA`               |`LED_Dual_KKA`                     |
|`LED_PAD`                    |`LED_Pad`                          |
|`LED_RCBG`                   |`LED_RKBG`                         |
|`LED_RCGB`                   |`LED_RKGB`                         |
|`LED_Series_PAD`             |`LED_Series_Pad`                   |
|`LED_Small_ALT`              |`LED_Small_Alt`                    |
|`LTRIM`                      |`L_Trim`                           |
|`Laserdiode_1A3C`            |`Laserdiode_1A3K`                  |
|`Laserdiode_1C2A`            |`Laserdiode_1K2A`                  |
|`Laserdiode_M_TYPE`          |`Laserdiode_MType`                 |
|`Laserdiode_N_TYPE`          |`Laserdiode_NType`                 |
|`Laserdiode_P_TYPE`          |`Laserdiode_PType`                 |
|`MEMRISTOR`                  |`Memristor`                        |
|`Net-Tie_2`                  |`NetTie_2`                         |
|`Net-Tie_3`                  |`NetTie_3`                         |
|`Net-Tie_3_Tee`              |`NetTie_3_Tee`                     |
|`Net-Tie_4`                  |`NetTie_4`                         |
|`Net-Tie_4_Cross`            |`NetTie_4_Cross`                   |
|`Peltier_Element`            |`PeltierElement`                   |
|`Q_DUAL_NMOS_G1S2G2D2S1D1`   |`Q_Dual_NMOS_G1S2G2D2S1D1`         |
|`Q_DUAL_NPN_C2C1E1E2`        |`Q_Dual_NPN_C2C1E1E2`              |
|`Q_DUAL_NPN_NPN_E1B1C2E2B2C1`|`Q_Dual_NPN_NPN_E1B1C2E2B2C1`      |
|`Q_DUAL_NPN_PNP_E1B1C2E2B2C1`|`Q_Dual_NPN_PNP_E1B1C2E2B2C1`      |
|`Q_DUAL_PMOS_G1S2G2D2S1D1`   |`Q_Dual_PMOS_G1S2G2D2S1D1`         |
|`Q_DUAL_PNP_C2C1E1E2`        |`Q_Dual_PNP_C2C1E1E2`              |
|`Q_DUAL_PNP_PNP_C1B1B2C2E2E1`|`Q_Dual_PNP_PNP_C1B1B2C2E2E1`      |
|`Q_DUAL_PNP_PNP_E1B1C2E2B2C1`|`Q_Dual_PNP_PNP_E1B1C2E2B2C1`      |
|`RF_Shield_One_Piece`        |`RF_Shield_OnePiece`               |
|`RF_Shield_Two_Pieces`       |`RF_Shield_TwoPieces`              |
|`RTRIM`                      |`R_Trim`                           |
|`R_PHOTO`                    |`R_Photo`                          |
|`R_POT`                      |`R_Potentiometer`                  |
|`R_POT_Dual`                 |`R_Potentiometer_Dual`             |
|`R_POT_Dual_Separate`        |`R_Potentiometer_Dual_Separate`    |
|`R_POT_TRIM`                 |`R_Potentiometer_Trim`             |
|`R_POT_TRIM_US`              |`R_Potentiometer_Trim_US`          |
|`R_POT_US`                   |`R_Potentiometer_US`               |
|`Rotary_Encoder`             |`RotaryEncoder`                    |
|`Rotary_Encoder_Switch`      |`RotaryEncoder_Switch`             |
|`SPARK_GAP`                  |`SparkGap`                         |
|`Thermocouple_ALT`           |`Thermocouple_Alt`                 |
|`Transformer_AUDIO`          |`Transformer_Audio`                |
|`Voltage_Divider`            |`VoltageDivider`                   |
|`Voltage_Divider_CenterPin1` |`VoltageDivider_CenterPin1`        |
|`Voltage_Divider_CenterPin3` |`VoltageDivider_CenterPin3`        |

 - Words that are in all caps but not an acronym eg. `MEMRISTOR`, are changed to be Capitalized
 - I interpret the underscore in symbol names to delimit the different properties of the symbol (NPN vs PNP transistors for example), so things like "Rotary_Encoder" and "Voltage_Divider" should be concatenated with no underscore
 - ~`CP1` (polarized capacitor with curved cathode) should conform to the defacto standard suffix of `_ALT` to denote an alternate symbol (perhaps it should be `CP_CurvedCathode` instead?)~ Per https://github.com/KiCad/kicad-symbols/pull/831#issuecomment-419721166 it should be named CP_US instead
 - Dual diodes are changed from `x2` to `Dual` for clarity
 - The `C` in dual/RGB LED symbol names is changed to `K` in keeping with other diode symbols and to prevent confusion with some dual diodes which use `C` to mean the "center" pin

### PR DESCRIPTION
**Pull request by fauxpark**
Fixes #861.

For v6, here we have a whole bunch of symbol renames for Device.lib for consistency and readability. I've broken it down into smaller commits so it's easier to digest.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
A couple thoughts for discussion by all. I've seen this before but may have not thought about it:
1. I somewhat like having the polarized cap symbols be `CP*` since that makes it easy to find with just two keys. Since `polarized` is in the description I think we don't lose anything. But is avoiding any kind of brevity best except when it's a true acronym?
2. Perhaps the jumper here should be removed since we have an entire Jumper library?

**Comment by fauxpark** [comment]
That's a good point, I can see how that naming would be useful. A lot of the other symbols in this lib are prefixed with the refdes, and since both polarized and unpolarized caps use `C` I figured it would be best to keep it in line with convention here. As a smaller thing, I also think `C_Polarized` is a... nicer name for the symbol.

The Jumper library looks a little more complete than these symbols, so I agree they could probably be removed.

**Comment by poeschlr** [comment]
I worry that this will be more work than necessary if we do things like this too early. I do not expect to open the lib up for v6 development in the near future and with the old lib format we always will run into merge conflicts. (Unless you are prepared to keep this pull request up to date with current master for the next year or so.)

I understand why things like this are done but pleas understand that we simply do not have the manpower to have parallel development for v6 and v5 so we really need to keep working on v5 with the restrictions that apply to that for at least the near future. I plan to split the libs as soon as the new file format is there. Then we will need to have a separate branch for fixing only critical bugs in v5. I might be persuaded to do this a bit earlier but i feel we should really focus on getting the lib for v5 as good as we can get it before doing so.

**Comment by fauxpark** [comment]
I was under the impression that there would be [no more releases in the v5 series after 5.1](http://kicad-pcb.org/blog/2019/03/KiCad-5.1.0-Release/), thus I waited until it was out to file this and #1651. I've seen other issues being added to the 6.0.0 milestone so I assumed it was safe to get these in.

**Comment by poeschlr** [comment]
No there will be no 5.2.x but there will definetly be more bugfix releases (5.1.1, 5.1.2, ...) between now and version 6 (version 6 is at least two years from now. KiCad typically gets a bugfix release every half year or so.)

**Comment by fauxpark** [comment]
I knew v6 would be some time away but I guess I misinterpreted the blog post (and I am not well versed in the development cycle). I'm happy to come back to these periodically to watch for conflicts. The AVR symbols probably won't see much activity but there are some KLC issues in Device.lib that someone else might decide to fix.

**Comment by fauxpark** [comment]
Oh, in addition, I also saw the "prebooked for v6" label being removed from many issues. If development on the v6 libraries hasn't started yet I'm not sure why that was done.

**Comment by fauxpark** [comment]
@evanshultz would you mind deleting the CLA comment above? Thanks.

**Comment by chschlue** [comment]
@fauxpark I deleted the first version, I think that was the problematic one.

**Comment by myfreescalewebpage** [comment]
@fauxpark can you solve the branch conflict here please ?
@evanshultz I think then this will be ready for merging. Can take the newt steps of the review if you want.

**Comment by fauxpark** [comment]
@myfreescalewebpage @evanshultz done :)

**Comment by myfreescalewebpage** [comment]
Looks great, no more comment. merging.
Thanks @fauxpark for this  great job!!!

**Comment by evanshultz** [comment]
I didn't get a chance to get to this before it was merged, and I have a couple comments. Maybe it doesn't matter, but I'll write them down:
1. Jumpers didn't get removed, unless I've overlooked something.
1. Underscores seem to be the normal delimiter, but Voltage_Divider went to VoltageDivider. Similarly, SPARK_GAP went to SparkGap and not Spark_Gap. Is there a consistent rationale in when to use underscore and when to smash words together with CamelCase?
1. Some instances of Serial still exist that should be Series. For example, D_Dual_Serial_ACK.
1. The suffix _Alt isn't very descriptive. Maybe we can find something better? _Filled if it's for a filled/solid diode symbol?

@chschlue 
FYI, since this may break a lot of schematics so I want you to be aware. And it will probably pop up on the forum. I like the changes and this is great to do for v6 when we have an opportunity, but I don't want to overlook the user experience.

**Comment by fauxpark** [comment]
@evanshultz

> Underscores seem to be the normal delimiter, but Voltage_Divider went to VoltageDivider. Similarly, SPARK_GAP went to SparkGap and not Spark_Gap. Is there a consistent rationale in when to use underscore and when to smash words together with CamelCase?

"Spark Gap" and "Voltage Divider" are the "base" names of the symbol (see second bullet point in #861), so for example if someone wanted to add a smaller spark gap symbol, they would call it `SparkGap_Small`. This is actually already done with the voltage divider symbols, there are two variants denoting the center pin as pins 1 and 3 (the `VoltageDivider` symbol itself has center on pin 2 and I would argue needs no `_CenterPin2` as the pins are in order here).

> Some instances of Serial still exist that should be Series. For example, D_Dual_Serial_ACK.

I did not change anything regarding Serial/Series. When I opened this PR, there was only Serial. If they were meant to be consistent, it should have been done in the PR adding the Parallel/Split dual diodes.

> The suffix _Alt isn't very descriptive. Maybe we can find something better? _Filled if it's for a filled/solid diode symbol?

I vaguely recall there being some concern over symbol name length (but I could be mistaken), so I didn't touch the Alt suffix besides un-all-capsing it.

I can make a followup PR removing the jumper symbols and changing `Alt` to `Filled`, can that still be done on GitHub?

**Comment by chschlue** [comment]
If you think you can wrap it up by the end of September, feel free to do it on GitHub.
(Note that the PR will be auto-closed. Just wait for someone to reopen and label it.)

**Comment by fauxpark** [comment]
@chschlue got it, done.

**Pull request merged**
