### PR TITLE
Relay and Relay_SolidState symbol cleanup

### LINKED ISSUE #1956: Verbose relay symbols
There are extraneous polylines and possibly other elements which overlap and are ultimately non-visible. I believe some relay symbols weren't drawn as elegantly as possible and then copied which is the root of the problem. While not a big issue, it inflates the size of the file for no benefit.

### PR DESCRIPTION
**Pull request by evanshultz**
Fixes #1956.

No pins changed position at all! Little to no changes to the actual symbols; this is about making things more elegant. However, there were some small changes to the solid state symbols so here are are a couple reference images:
image
image
image
image

Relay:
-Pin name offset to 20mil
-Use as few lines as possible
-Diodes are unfilled with a middle line
-Shrack relays to diagonal line coil style
-Convert polylines of characters to text
-Make text upright when viewed in libedit
-Move NC pins to symbol outline

Relay_SolidState:
-Use as few lines as possible
-Diodes are unfilled with a middle line
-Move NC pins to symbol outline
-Set TLP148G as ALIAS of TLP141G

To avoid maintenance issues and make this the standard symbols from which users can take if they contribute new symbols, I'd really like to see this merged quickly. Thanks!

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Ping! Any chance to get this merged before branch conflicts?

**Comment by evanshultz** [comment]
@diegoherranz 
You assigned this PR to yourself. I fixed one branch conflict so it's able to merge now. Were there any changes you wanted or any other issues?

**Comment by diegoherranz** [comment]
I haven't reviewed it yet, but I had interest in seeing this one merged, that's why I took it.
I'll review this weekednd.
Thanks!

**Comment by diegoherranz** [comment]
I've added the bug label too since it also fixes a few NC pins which were outside of the symbol outline. Namely: MOC3010M, MOC3031M and FOD420.
I've checked them and they look OK now.

**Comment by diegoherranz** [comment]
Some checks done:

- TLP148G made an ALIAS of TLP141G: checked datasheets and it's safe to do

- Lib files in this PR compared to those in master using https://github.com/KiCad/kicad-library-utils/blob/master/schlib/comparelibs.py with the `--design-breaking-changes` option.
No difference in pin naming or placement except for the NC pins mentioned above.

- I've randomly checked a few symbols and the graphical cleanup done looked OK.

Given the `--design-breaking-changes` check done above is OK, which is the most important thing, I'm happy to merge this even if I haven't individually checked every symbol. It is low risk and we can benefit from unified, tidy symbols in master before getting new submissions in these libraries.

Thanks, @evanshultz

**Pull request merged**
