### PR TITLE
Add 3-Port Gigabit Ethernet Switch KSZ9893RNX

### PR DESCRIPTION
**Pull request by tpambor**
Add 3-Port Gigabit Ethernet Switch KSZ9893RNX by Microchip with RGMII/MII/RMII Interface

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/KSZ9893R-Data-Sheet-DS00002420C.pdf

ksz9893

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @tpambor , thanks for contributing,

A few comments I have during my review:

- [ ] Pins length should be 100mil (symbol<100pins)
- [ ] TXRX* pins name are not consistent with the datasheet
- [ ] You can cross LED2_0 and LED2_1 to get 0 above 1 like LED1 pins
- [ ] NC pins should be moved on the border outline of the symbol
- [ ] XO is output, XI is input
- [ ] Pin 49 should be named `~SCS`

Will do a full review again after those changes.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @tpambor are you still alive on this subject ? Thanks !

**Comment by tpambor** [comment]
Sorry for the delay. @myfreescalewebpage I intentionally changed the TXRX* pin names such that they end with _N/_P. This suffix is used by the differential pair router to identify them as a differential pair. If the symbol should rather match the datasheet I will change the names. I incorporated your other points. Thanks for the review.

**Comment by myfreescalewebpage** [comment]
> If the symbol should rather match the datasheet I will change the names.

Yes please, when an other user will use this symbol this will be confused, we always try to match the datasheet the best as possible.

**Comment by tpambor** [comment]
> > If the symbol should rather match the datasheet I will change the names.
> 
> Yes please, when an other user will use this symbol this will be confused, we always try to match the datasheet the best as possible.

Ok, done.

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes @tpambor . Only a remaining issue for me: positive power supply pins should not be stacked. This will enlarge a lot the size of the symbol, or the other possibility is to create a second unit in the symbol to separate the power supply pin (positive + GND/EP). I let you decide what is the best.
Thanks,
Joel

**Comment by tpambor** [comment]
@myfreescalewebpage I think this would violate the kicad library convention.
[KLC S4.3](http://kicad-pcb.org/libraries/klc/S4.3/):
>2. Power supply pins must be stacked unless the datasheet specifies the need for decoupling capacitors on every pin.

There exist also a lot of other symbols that stack power supply pins e.g. LAN951x (#651). I personally would prefer leaving them stacked.

**Comment by myfreescalewebpage** [comment]
@tpambor when the datasheet explicitly indicate a single capacitor only is required, we allow stacking,  but when there is no indication we require to not stack. That's a rule, not my personal desire.

We know other symbols are not correct, and if you want to fix some of them, that's welcome. The PR you have quoted is one of the examples, KLC have been improved to detail these guidelines but sometime still need to be improved to avoid confusion.

**Comment by tpambor** [comment]
@myfreescalewebpage Ok I unstacked them.

**Comment by myfreescalewebpage** [comment]
Thanks. Ok for me on this PR, merging. Thanks for the great job done here @tpambor !

**Pull request merged**
