### PR TITLE
Added Microchip/Micrel MIC5365/6-3.3Volt LDO

### PR DESCRIPTION
**Pull request by fhw72**
Added Micrel MIC5365/6-3.3Volt LDO with two footprints:
SOT23-5 and SOT353-5 (aka SC-70).

Standard footprints were reused; no new footprints were created.

Datasheet link:
http://ww1.microchip.com/downloads/en/DeviceDoc/mic5365.pdf

### CODE REVIEW

**Comment by fhw72** [comment]
2nd attempt; I'm sorry about the confusion.

**Comment by myfreescalewebpage** [comment]
Hi @fhw72, thanks for contributing,

A few comments I have during my review:

MIC5365-3.3YC5:
- [ ] Description should end with the full package name "SC-70-5"
- [ ] You are violating KLC S3.6 which is easy to fix, see travis output
- [ ] I would say footprint filter should be `SOT*353*SC*70*`, in any case, no leading star

MIC5366-3.3YC5:
- [ ] Description should end with the full package name "SC-70-5"
- [ ] You can add the output auto discharge capability to the description, for example `150mA Low-dropout Voltage Regulator, Output discharge circuit, Vout 3.3V, Vin up to 5.5V, SC-70-5`

MIC5365-3.3YD5:
- [ ] Description should end with the full package name "SOT-23-5"
- [ ] Footprint filter should be `SOT*23*`

Cheers,
Joel

**Comment by poeschlr** [comment]
The pin offset is set in the general symbol settings dialog. Set it to 20 and it should be ok. See: http://kicad-pcb.org/libraries/klc/S3.6/

**Comment by poeschlr** [comment]
For the future please add screenshots to the pull request description.

**Comment by fhw72** [comment]
I've fixed the KLC S3.6 violation. Thanks for taking the time to review the part. :-)


screenshot 2019-01-02 12 01 14
screenshot 2019-01-02 12 01 25

**Comment by myfreescalewebpage** [comment]
Hi @fhw72 

Thanks for the fixes. No comment to do. Merging your PR.

Cheers,
Joel

**Pull request merged**
