### PR TITLE
Added AudioPlugs

### PR DESCRIPTION
**Pull request by cnieves1**
Added audio plugs generic symbol (mono, stereo/TRS and stereo/TRRS)
  https://en.wikipedia.org/wiki/Phone_connector_(audio)

Captura de pantalla de 2020-04-08 12-56-04
Captura de pantalla de 2020-04-08 12-56-14
Captura de pantalla de 2020-04-08 12-56-24

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Captura de pantalla de 2020-04-08 13-14-26
Captura de pantalla de 2020-04-08 13-14-34
Captura de pantalla de 2020-04-08 13-14-43

**Comment by cpresser** [comment]
Hi,

can you elaborate why you choose those pin names?
Which footprints will those symbols be used with?

**Comment by cnieves1** [comment]
Those pin names are standard: (T)ip, (R)ing1, (R)ing2, (S)leeve.
Mating audio jack connectors are already in the library (see Connector:AudioJack*) and have the same pin names.
One of the footprints to be used with that symbol will be:
  https://github.com/KiCad/kicad-footprints/pull/2203

**Comment by cpresser** [comment]
I really like the graphics. Well done :heart: 
Names are good, they fit well into the existing library.

The description needs some work. This also applies to keywords. Perhaps add 6.25, 3.5mm 2.5mm and so on to the keywords. At least for me that is the first thing that comes to mind when thinking of those connectors. Not sure if every variant exists for each diameter though.

image

**Comment by cnieves1** [comment]
Added to the keywords. I'm not aware of any TRRS 6.35mm, so I didn't add it to AudioPlug4.
What changes are required in the description? Descriptions follow those of the AudioJack* symbols already in the library...

**Comment by cpresser** [comment]
They all say `4 Poles`which does not seem right.

**Comment by cnieves1** [comment]
Ups! Didn't  noticed that! sorry!. Fixed now.

**Pull request merged**
