### PR TITLE
Add WIZnet W5500

### PR DESCRIPTION
**Pull request by robinolejnik**
This PR adds the WIZnet W5500 ethernet controller
http://wizwiki.net/wiki/lib/exe/fetch.php/products:w5500:w5500_ds_v109e.pdf
https://www.wiznet.io/product-item/w5500/
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
Thank you for contributing to the KiCad libraries. While I don't have time to conduct a full review (other librarians, go for it), I have the following suggestions:

- Please name all `NC` pins.
- Consider stacking power pins (`AGND` and `AVDD` respectively), in accordance with [S4.3](https://kicad-pcb.org/libraries/klc/S4.3/).

**Comment by robinolejnik** [comment]
Thanks for the suggestions. I added and pushed the changes. Here is the new screenshot:
image

**Comment by aewallin** [comment]
Are all the RSVD pins connected together - and then pulled down to GND with an external resistor?
should they all be stacked and only one RSVD pin shown?

**Comment by robinolejnik** [comment]
I'm not really sure about these pins.
The datasheet says that RVSD pin 23 must be tied to GND, all other RVSD pins are specified as NC.
While the reference schematic don't connect any of them, several boards I saw have an external pull down resistor on each one for some reason. According to the datasheet all of them should have an internal pull down.
What do you think on this?

**Comment by myfreescalewebpage** [comment]
Hi @robinolejnik , thanks for contributing,

A few comments I have during my review:

- [ ] The datasheet link should be a link to the datasheet itself. I propose `http://wizwiki.net/wiki/lib/exe/fetch.php/products:w5500:w5500_ds_v109e.pdf`
- [ ] EXRES1 should be Passive
- [ ] VBG should be Passive
- [ ] TOCAP should be Passive

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@robinolejnik ping, this is a cool device that should be appreciated in KiCad :)

**Comment by robinolejnik** [comment]
image
I finally had some time to work on this again...

@myfreescalewebpage I fixed the points you mentioned.
What do you think about the RSVD pins?

I asked WIZnet, that's their answer:
>>>
>>>I mean all RSVD pins.
>>
>> Do you mean to connect all RSVD pins to GND or only pin 23?
>
> We recommend connecting the W5500 RSVD pin to the GND.
> EMI characteristics may be better.

regards
Robin

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes.
I think the current symbol is great for the RSVD pins, we can do what we want, connect them or not to the ground. It's nice to let the user decide.
Joel

**Comment by robinolejnik** [comment]
Thanks Joel!

**Pull request merged**
