### PR TITLE
OPA818 op-amp in 3x3mm WSON-8

### PR DESCRIPTION
**Pull request by aewallin**
https://www.ti.com/lit/ds/symlink/opa818.pdf

OPA818IDRGx

some open questions:
- pin1 ~PD has an internal pull-down, so maybe it should be passive type? (datasheet suggests it can be left floating)
- not sure about the convention for exact part-number e.g. OPA818IDRGx (some other parts seem to replace "I" by "x" - but the datasheet only shows this part-number.)
- I reduced size of PD and EP names, so they fit the symbol.

footprint PR https://github.com/KiCad/kicad-footprints/pull/2223

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "OPA818xDRG"

Else just need to wait the footprint

Cheers,
Joel

**Comment by aewallin** [comment]
footprint now merged!

**Comment by chschlue** [comment]
Indeed.
@cpresser was that an oversight?

**Comment by cpresser** [comment]
We are talking about https://github.com/KiCad/kicad-footprints/pull/2223 right?
And https://github.com/pointhi/kicad-footprint-generator/pull/633

TBH, I did not put to much thought into that. On the generator PR it was already prefixed Texas. Most likely since its a copy-paste variant of `Texas_S-PWSON-N8`, just with the EP added. That seems plausible, I did not question that since it was consistent with the existing variant.

What do you suggest we do about that? Since all those footprints are build according to ipc spec and not texas-spec, I think removing the manufacturer prefix for them is the way to go.
The only other use of the existing `Texas_S-PWSON-N8_EP1.2x2mm` is  `LP2951-3.0_WSON`

**Comment by chschlue** [comment]
Yes, I think we best fix both.

**Comment by cpresser** [comment]
That should do the trick:
https://github.com/pointhi/kicad-footprint-generator/pull/642
https://github.com/KiCad/kicad-footprints/pull/2494
https://github.com/KiCad/kicad-symbols/pull/3094

**Comment by aewallin** [comment]
footprint now changed back to the generic name.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
