### PR TITLE
TPS7B69xx

### PR DESCRIPTION
**Pull request by Knochi**
Texas Instruments Wide Input Range (40V), Low Dropout Regulator Series TPS7B6
added 3.3V Version TPS7B6933 (SOT223)
added 5.0V Version TPS7B6950 (SOT-23-5)
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)

Regulator_Linear_TPS7B6950
Regulator_Linear_TPS7B6933

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Knochi , thanks for contributing,

A few comments I have during my review:

TPS7B6933:
- [ ] Name of the device should be "TPS7B6933DCY"
- [ ] Can you format the description as done for many other regulators : "150mA, Ultralow-Quiescent-Current Low Drop-out Voltage Regulator, Fixed Output 3.3V, SOT-223"
- [ ] Footprint filter should be "SOT?223*" (see travis error)
- [ ] Pin offset should be 20 mils (see travis error)
- [ ] GND pins should be stacked
- [ ] Dimensions of the symbol are not like many other regulators and should be fixed. See for example LM317 or L7805 common devices.

TPS7B6950:
- [ ] Name of the device should be "TPS7B6950DBV"
- [ ] Can you format the description as done for many other regulators : "150mA, Ultralow-Quiescent-Current Low Drop-out Voltage Regulator, Fixed Output 5.0V, SOT-23-5"
- [ ] Pin offset should be 20 mils (see travis error)
- [ ] GND pins should be stacked
- [ ] NC pin should be moved to the border outline of the symbol
- [ ] Dimensions of the symbol are not like many other regulators and should be fixed. See for example LM317 or L7805 common devices.

Cheers,
Joel

**Comment by Knochi** [comment]
> TPS7B6933:
> 
>     * [ ]  Name of the device should be "TPS7B6933DCY"


> TPS7B6950:
> 
>     * [ ]  Name of the device should be "TPS7B6950DBV"

At another part a reviewer wanted me to remove the package suffix. Is there a rule when to have the suffix?

**Comment by Knochi** [comment]
Hi Joel,

> Name of the device should be "TPS7B6933DCY"
At another part it was suggested to remove the package suffix. Is there any rule for that?


> TPS7B6933:

* [x]  Can you format the description as done for many other regulators : "150mA, Ultralow-Quiescent-Current Low Drop-out Voltage Regulator, Fixed Output 3.3V, SOT-223"
* [x]  Footprint filter should be "SOT?223*" (see travis error)
*  [x]  Pin offset should be 20 mils (see travis error)
*  [x]  GND pins should be stacked
 * [x]  Dimensions of the symbol are not like many other regulators and should be fixed. See for example LM317 or L7805 common devices.

> TPS7B6950:

>     * [ ]  Name of the device should be "TPS7B6950DBV"
See above 
* [x]  Can you format the description as done for many other regulators : "150mA, Ultralow-Quiescent-Current Low Drop-out Voltage Regulator, Fixed Output 5.0V, SOT-23-5"
* [x]  Pin offset should be 20 mils (see travis error)
* [x]  GND pins should be stacked
* [x]  NC pin should be moved to the border outline of the symbol
This is not done at several other symbols (e.g. LM317 SO-8) is that a new rule?
* [x]  Dimensions of the symbol are not like many other regulators and should be fixed. See for example LM317 or L7805 common devices.

CU
David

**Comment by myfreescalewebpage** [comment]
Hello @Knochi 

The name of the device should be the more detailed it is possible. Actually this part has only one package option, but if the manufacturer add new options, we will have a conflict. So you have to name the device properly right now. Note that we always discard temperature and the packaging (tube / real). Rules at chapter S2 at https://kicad-pcb.org/libraries/klc/

Missing '*' at the end of footprint filter.
Pin offset still wrong (see travis error log).
GND pin stacking rule is : First pin visible power input, other pin invisible and set to Passive (to be fixed).

NC pin on the border outline is an old rule but plenty of very old symbols have not been updated. If you want to submit this kind of enhancement it's possible with a pull request :)

Joel

**Comment by myfreescalewebpage** [comment]
@Knochi ping

**Pull request closed without merging**
