### PR TITLE
HT12D

### PR DESCRIPTION
**Pull request by G-Pereira**
A Serial Decoder with a comparator.
image

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
https://www.farnell.com/datasheets/1525377.pdf
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @G-Pereira , thanks for contributing,

A few comments I have during my review:

- [ ] The footprint should be SOP, not SOIC
- [ ] The description should ends with the package name. I propose: `2^12 serial decoder, SOP-20`
- [ ] The datasheet should be from the manufacturer website, do you have one ? Else OK.
- [ ] The Dx pin should be Output
- [ ] The symbol is very thin and can be arranged to make easy connection in a schematic. I propose based on the datasheet:

Capture

Cheers,
Joel

**Comment by G-Pereira** [comment]
Which footprint specifically? I have confirmed all the dimensions and while searching on the internet I found out that SOIC is the same. I have found this weird but in fact I have used this footprint and it fits perfectly.

**Comment by G-Pereira** [comment]
There is no SOP-20 in the libraries

**Comment by G-Pereira** [comment]
This force push was to revert the last commit

**Comment by G-Pereira** [comment]
Ok, I got confused with Travis output, sorry the mess. It should be ok now, the force push changes nothing because I've used it to go back to the "Set Dx pins to output" commit and then I've pushed again the "Center Symbol" commit

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes.
We always ask to create the exact footprint, even if the dimensions are the same. This is to avoid future confusion by the users of your symbol. You can create the footprint with the generator (https://github.com/pointhi/kicad-footprint-generator) and submit it.

**Comment by G-Pereira** [comment]
What about creating a copy of the SOIC footprint? It is exactly the same.

**Comment by myfreescalewebpage** [comment]
The generator should be updated anyway. But yes it's simple to do it because then you just have to use a compare tool to check both generated footprints are the same :)

**Comment by myfreescalewebpage** [comment]
Thanks. Will need to wait the integration of the footprint before continue here.

**Comment by chschlue** [comment]
FP merged

**Comment by G-Pereira** [comment]
There was an issue with the footprint dimensions. This is not ready to merge

**Comment by G-Pereira** [comment]
Check https://github.com/KiCad/kicad-footprints/pull/2440

**Comment by G-Pereira** [comment]
Ready to merge!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
