### PR TITLE
Add AC/DC converter series: Recom RAC20-xxSK

### PR DESCRIPTION
**Pull request by Werni2A**
Adds a few AC/DC converters.

[https://recom-power.com/pdf/Powerline_AC-DC/RAC20-K.pdf](https://recom-power.com/pdf/Powerline_AC-DC/RAC20-K.pdf)
[Pin table](https://recom-power.com/pdf/Powerline_AC-DC/RAC20-K.pdf#page=6)

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/2265)

I copied the symbol from RAC01-xxSGB

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Werni2A , thanks for contributing,

A few comments I have during my review:

- [ ] "RAC20-xxSK" should not exist. Instead you should use one of the symbol as the main symbol (5V version for example) and then make the other as alias.
- [ ] Pin 3 is missing, should be called "NC", invisible, Not connected and placed on the border outline of the symbol

Cheers,
Joel

**Comment by Werni2A** [comment]
Hi Joel, thank you or the review.

I removed the generic part "RAC20-xxSK" and also changed the footprint filter to be more precise. Maybe you can take a look at that again.

Concerning your second point. The missing pin 3 is just I would say a naming convention for this kind of parts. The pin is physically missing therefore NC would be in my opinion inappropriate because there is no pin to connect to. Please take a look at the [footprint](https://github.com/KiCad/kicad-footprints/pull/2265). What do you think about that?

**Comment by myfreescalewebpage** [comment]
Thanks. Yes sorry for pin 3 , thanks to point that. In this case we do not add it.
For the fp filter I prefer `Converter*ACDC*RECOM*RAC20*SK*THT*`
Joel

**Comment by Werni2A** [comment]
@myfreescalewebpage I reset the footprint filter to the original one :)

**Comment by myfreescalewebpage** [comment]
Thanks!
Just need to wait the footprint now.
Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@Werni2A there is a case issue here on the footprint and footprint filter. "RECOM"->"Recom". Then ready to be merged.
Joel

**Comment by Werni2A** [comment]
@myfreescalewebpage I adjusted both fields. The CI should now succeed. Thanks for you effort.

**Comment by myfreescalewebpage** [comment]
Thanks for the fix, merging now

**Pull request merged**
