### PR TITLE
Added BQ51051B/BQ51051B/BQ51052B with package DSBGA

### PR DESCRIPTION
**Pull request by jneiva08**
Since was already meged VQFN packaged, modifyed to fit DSBGA package.
It was in on a closed PR: https://github.com/KiCad/kicad-symbols/pull/822
PR for the footprint made by cyber-murmel: https://github.com/KiCad/kicad-footprints/pull/826

Datasheet:
http://www.ti.com/lit/ds/symlink/bq51050b.pdf

Screenshot:
bq_bga

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Travis is giving a error on stacked pins, have put the second as passive, should be the same type?

**Comment by myfreescalewebpage** [comment]
Closing/opening the PR to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hello @jneiva08 thanks for contributing

Few comments I have during my review :

- [ ] In this case, because the pins are Input, yes they need to have the same type. So turn B2 and B4 pins to Input and travis should be happy with you
- [ ] You have made a mistake in the footprint, it should be `Package_BGA:Texas_DSBGA-28_1.9x3.0mm_Layout4x7_P0.4mm`
- [ ] Footprint filter should not contains number of pads, I propose something like `Texas?DSBGA*1.9x3.0mm*P0.4mm*`

Cheers,
Joel

**Comment by jneiva08** [comment]
hi @myfreescalewebpage, did the modifications requested.

**Comment by myfreescalewebpage** [comment]
Thanks @jneiva08 , no more comment to do. Merging the PR.

Joel

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
