### PR TITLE
3W and 5W AC/DC converters from Hi-Link.

### PR DESCRIPTION
**Pull request by Sthing**
Footprints in https://github.com/KiCad/kicad-footprints/pull/860

## 3W modules
HLK-PM03, HLK-PM01, HLK-PM12

http://www.hlktech.net/product_detail.php?ProId=60

image

## 5W modules
HLK-5M03, HLK-5M05, HLK-5M12

http://www.hlktech.net/product_detail.php?ProId=54

image

------------
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Sthing, thanks for contributing,

A few comments I have during my review:

- [ ] I have not found datasheets in PDF format, not sure they are available on the manufacturer website, but it's better if you have a link ?
- [ ] HLK-PM12 datasheet is in PDF format but it is better if you redirect to the manufacturer website because link can be break at any time by this site
- [ ] You should cross -Vin and +Vin to get positive pin on the top right and negative pin at the bottom right
- [ ] Outputs pins are named "+VO", "-VO", not "+Vin" and "-Vin". To be consistent, I will call inputs "AC1" and "AC2" according to the manufacturer names "AC" and "AC" (we can't put the same name for this)
- [ ] Can you make the symbol horizontally symmetrical regarding to the "isolation dashes"  in the box ?
- [ ] You are violating KLC S3.6 and S5.2 that are easy to solve, please check at the travis output.
- [ ] For consistency with the other devices in the library, remove current in the description, for example look at "HS-40003" : "3.3V, 3W, AC-DC module power supply, Hahn"
- [ ] For consistency with the other devices in the library, remove current in the keywords, for example look at "HS-40003" : "3.3V 3W AC-DC module power supply"

Cheers,
Joel

**Comment by evanshultz** [comment]
- Change pin name offset to 20mil.
- Pins 1 and 2 may be correctly named just `AC` as it may not matter which is connected to Line and which to Neutral. It would depend on the circuit design inside the module.
- At https://github.com/KiCad/kicad-symbols/issues/429 we decided to use a single dashed line to separate Primary and Secondary pins in this type of symbol.
- If some of the PNs are `PMxx` and some are `5Mxx` the footprint naming should indicate that, so please consider that in the footprint name and, once the footprint is merged, update this PR to match.

**Comment by myfreescalewebpage** [comment]
@Sthing up ?

**Comment by Encrypt** [comment]
Hello everyone!

I've just noticed that these symbols were added to the library in #1147 
I guess you can close this issue :)

**Comment by myfreescalewebpage** [comment]
Hello @Encrypt thanks for pointing this to our attention! I was wondering also if original author as stop working on this subject. I label with Abandoned and Duplicated tags and close the PR now.
Also closing the footprint PR https://github.com/KiCad/kicad-footprints/pull/860 for the same reason.
Joel

**Pull request closed without merging**
