### PR TITLE
Add symbol for CUI PD-30S.

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet](https://www.cui.com/product/resource/digikeypdf/pd-30s.pdf).

This symbol goes with the footprint in KiCad/kicad-footprints#592.

cui_pd-30s-symbol

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ppelleti 
No comment on the symbol, just need to wait the footprint.
Joel

**Comment by myfreescalewebpage** [comment]
@ppelleti can you solve the branch conflict here please ?

**Comment by myfreescalewebpage** [comment]
@ppelleti ping

**Comment by ppelleti** [comment]
The conflict should be solved now.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
