### PR TITLE
Remove lead finish suffixes from Microchip AVR MCUs

### PR DESCRIPTION
**Pull request by fauxpark**
#387, ticks off item number 14.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks!!

Since this will be disruptive, what about holding off until v6 is near that way schematics don't get disrupted until then. Would you be OK with that, and the minor branch divergence that may happen in the meantime? I will be happy to try and catch all new submissions and follow this paradigm in the interim.

**Comment by fauxpark** [comment]
Fine by me. I haven't seen any new additions to these libs in a while, I think I got em all ;)

**Comment by myfreescalewebpage** [comment]
@evanshultz I think this PR can now be merged, what do you think ?

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Yes!

@fauxpark 
I quickly scanned things and it looks good. Thanks for all of your dedication and expertise over quite some time!

**Pull request merged**
