### PR TITLE
Tps6303x

### PR DESCRIPTION
**Pull request by cnieves1**
Added TPS63030 and TPS63031.
Footprint depends on: https://github.com/pointhi/kicad-footprint-generator/pull/453.
Datasheet: http://www.ti.com/lit/ds/symlink/tps63030.pdf
imagen

imagen

### CODE REVIEW

**Comment by cnieves1** [comment]
Travis CI failed with invalid footprint (pending PR, see first message), and:
```
 Violating S4.2
    Pins should be arranged by function
    Positive power pins should be placed at top of symbol
     - Pin VIN (5) @ (-400,200)
```
This PR uses the same symbol as TPS63000 (alreday in the library) with different footprint. 
I hope the required change is not needed.

**Comment by chschlue** [comment]
VIN on the left is fine.
But power input for VINA doesn't make sense to me, given how it's supposed to be used. Should be output or passive.

**Comment by cnieves1** [comment]
Why? In the datasheet (page 4) it is specified as power input:

imagen

**Comment by chschlue** [comment]
tps1
tps2

**Comment by cnieves1** [comment]
Agreed. Changed VINA to passive.

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
