### PR TITLE
Added SC35VB80S-G with one alias

### PR DESCRIPTION
**Pull request by aris-kimi**
Datasheet: https://www.comchiptech.com/admin/files/product/SC35VB80S-G%20Thru506369.%20SC35VB160S-G%20RevB.pdf

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2383

scvb_3phase_diode

```
  Violating S3.1

    Origin is centered on the middle of the symbol

    > Symbol unit 1 slightly off-center

    >   Center calculated @ (-50.0, 0.0)

  Violating S5.1

    For components with a single default footprint, footprint field is filled with valid footprint

    filename

    Specified footprint does not exist

     - Footprint file Diode_THT:Diode_Bridge_Comchip_SCVB-L was not found
```

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@aris-kimi no comment to do here, just need to have the footprint.
Joel

**Comment by aris-kimi** [comment]
Conflict fixed.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
No comment here, merging.

**Pull request merged**
