### PR TITLE
Add new gate drivers

### PR DESCRIPTION
**Pull request by evanshultz**
Si8241 / Si8244
https://www.silabs.com/documents/public/data-sheets/Si824x.pdf
Since this is an audio-specific part I put it in this library like IRS20957
image

1EDN7550 / 1EDN8550
https://www.infineon.com/dgdl/Infineon-1EDN7550B-DS-v02_00-EN.pdf?fileId=5546d46262b31d2e01635d9799ef264f
image

NCD5702
https://www.onsemi.com/pub/Collateral/NCD5702-D.PDF
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz 

A few comments I have during my review:

- [ ] There is an error in the Amplifier Audio library, line 1341 there is missing ENDDRAW / ENDDEF
- [ ] 1EDN7550: name should be 1EDN7550B for the SOT-23-6 version same comment for the alias
- [ ] NCD5702: Pin 4 is Open Collector
- [ ] NCD5702: Pin 12 is Open Collector
- [ ] NCD5702: Pin 11 is Open emitter
- [ ] NCD5702: Pin 16 is Open emitter

Cheers,
Joel

**Comment by evanshultz** [comment]
NCD5702 pin 16 should actually be open collector, but otherwise I addressed all of the items above and a couple other things I noticed.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
This should be ready to merge now.

@chschlue 
I think I see what you meant at https://github.com/KiCad/kicad-symbols/pull/2203#issuecomment-623263256. I can directly remove the conflict markers on GH after clicking on the Resolve Conflicts button once the actual conflict is addressed. Seems ugly... there must be a better way. But it works.

**Comment by chschlue** [comment]
@evanshultz see https://github.com/KiCad/kicad-symbols/pull/2203#issuecomment-626442811

**Comment by myfreescalewebpage** [comment]
Correct. Merging.

**Pull request merged**
