### PR TITLE
Add LMP8640

### PR DESCRIPTION
**Pull request by cejpmart**
DS: http://www.ti.com/lit/ds/symlink/lmp8640.pdf

The symbol is based on INA138, although IMO it may mislead somebody into thinking it is a standard op amp.

Imgur

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cejpmart , thanks for contributing,

Warning about KLC S3.6 accepted (consistent with other op amp symbols).

Just one thing to modify according to me, please can you change the keywords to "current monitor shunt sensor" for consistency with the other devices.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Offtopic:

@myfreescalewebpage you can use the ``` ` ``` character to produce inline "code" sections that allow the use of other characters such as `*`. Github has a button with a "insert code" tooltip you can use or you could just wrap your code in the mentioned character. That would produce `SOT*23*6*`. 

Also, I am not sure if this applies to this case but please beware of https://github.com/KiCad/kicad-symbols/issues/697

Thank you for your time!

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco thanks for the markdown lesson, fixed ! Also fix my comment regarding to #697.

**Comment by myfreescalewebpage** [comment]
@cejpmart up ?

**Comment by cejpmart** [comment]
the placement of the labels was correct from the start, I must have attached an outdated screenshot

**Comment by myfreescalewebpage** [comment]
@cejpmart that's great for me, no other comment to do. Thanks for your contribution !

Cheers,
Joel

**Pull request merged**
