### PR TITLE
74x gxx series power pin cleanup

### PR DESCRIPTION
**Pull request by yankee14**
I'm working on fixing the power pin issues, broken datasheet hyperlinks, etc. with the 74xGxx library. I need advice on which KLC rules I'd be allowed to break, because I can't follow it and have the symbol look reasonable in all cases.

See https://www.kicad-pcb.org/libraries/klc/S3.8/

"Power pins in this case must be drawn on the same symbol as the logic pins."

That is very difficult to do while also keeping the symbol reasonably small. I would have to make the pin name font very small, or offset the power/ground pins to the left or right. Even if I move the pins to the left and right, there are cases where it still won't fit unless I make the symbol quite large.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by chschlue** [comment]
`74LVC1G00/02` look good to me like that.
For multi-unit symbols, it looks like the screenshot in S3.8 is obsolete. I suggest using floating pins (like multi-unit opamps and such).

Generally, working logic symbols are going to be a brand new addition to v6, a black void where no man has gone before.
Because of that, I think the right way is making the symbols work and adapting KLC accordingly, not the other way round.

**Comment by yankee14** [comment]
This PR after https://github.com/KiCad/kicad-symbols/issues/2705#issuecomment-629807359 :

c88f710347aed645fd9b42f4e937b5df

**Comment by evanshultz** [comment]
Please don't misunderstand my comment. It's my opinion, as just one of the librarians, that having a consistently 'bad' library is best for users as they're used to the symbols and have implemented them in schematics now. This is a great improvement, but it's incremental and breeds entropy which may not be the best choice for the interim time left until v6 is released.

I'll own the scripts and make the new logic libraries which will allow us to address all symbols in one fell swoop in a maintainable way.

**Comment by yankee14** [comment]
@evanshultz The scripts sound really good! I'm personally in no hurry, and I get what you mean by introducing entropy. In the meantime, I just edit the symbols individually in my own branch as I need them for work and such https://github.com/yankee14/kicad-symbols/tree/ed_devel.

I'm going to close this. Thanks.

**Pull request closed without merging**
