### PR TITLE
Add AS179-92LF

### PR DESCRIPTION
**Pull request by lorenz**
Adds the Skyworks AS179-92LF SPDT RF switch. [Datasheet](http://www.skyworksinc.com/uploads/documents/AS179_92LF_200176H.pdf)
Symbol is adapted from another RF switch.
AS179-92LF

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Of course you will need to fix the branch conflicts.
1. You may have noticed this PR accidentally included `Si446x`.
1. Pins 4 and 6 are flipped.
1. Footprint filter can be just `SOT*363*`.

**Comment by lorenz** [comment]
Should be all good now, good catch with the flipped pins :)

**Comment by evanshultz** [comment]
Thanks! Looks good now.

Please don't force push commits since that makes review harder. We will squash merge to keep the commit history clean.

**Comment by lorenz** [comment]
That was the rebase, the changes were pushed in a separate commit.

**Pull request merged**
