### PR TITLE
Added symbol for BAV99S

### PR DESCRIPTION
**Pull request by Duckle29**
Added an atomic symbol for the BAV99S dual series diode package
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

[Datasheet](https://assets.nexperia.com/documents/data-sheet/BAV99_SER.pdf)

- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Check the output of the Travis automated check scripts - fix any errors as required

image
image
image
image

### CODE REVIEW

**Comment by Duckle29** [comment]
I went with SC-88 in the description, as this is what the datasheet says. (while the footprint is SOT-363_SC-70-6)

**Comment by evanshultz** [comment]
- Change the description to `High-speed switching diodes, dual series, SOT-363`. The datasheet also shows that package and it reconciles with the KiCad footprint better.
- Change pin name offset to 1mil.

You have done something bad with the documentation file. Do you know what happened? I think things ended up OK but there is a lot of useless noise in this PR. @Ratfink Would you be able to check this out and confirm it's OK to merge?

**Comment by evanshultz** [comment]
Also:
- Remove underscore in pin names.

**Comment by Duckle29** [comment]
I keep copying the .dcm file manually from master branch and then manually insterting the bav99s section, but kicad keeps changing it a lot to what you see in my last commit.

**Comment by Ratfink** [comment]
@evanshultz I looked closely through the DCM file, and it indeed looks like nothing more than a lot of entries being shuffled around.  So this PR looks safe to merge, but because of the noise I'd suggest a squash merge!

**Comment by evanshultz** [comment]
@Duckle29 
Alright. Thank you.

Can you change the pin names to be unique and match the datasheet? Like A1, K2, K3A4, A3, K4, K1A2? Then I can merge.

@Ratfink 
Thanks!

**Comment by evanshultz** [comment]
Also, by sharing graphical elements between the units the lines of graphics can be halved (!):
```
# BAV99S
#
DEF BAV99S D 0 1 Y N 2 F N
F0 "D" 0 100 50 H V C CNN
F1 "BAV99S" 0 200 50 H V C CNN
F2 "Package_TO_SOT_SMD:SOT-363_SC-70-6" 0 -500 50 H I C CNN
F3 "" -750 -400 50 H I C CNN
$FPLIST
 SOT?363*
$ENDFPLIST
DRAW
C 0 0 10 0 1 0 F
P 2 0 1 0 0 -100 0 0 N
P 2 0 1 0 200 0 -200 0 N
P 3 0 1 8 -50 -50 -50 50 -50 50 N
P 3 0 1 8 150 50 150 -50 150 -50 N
P 6 0 1 8 -150 50 -50 0 -150 -50 -150 50 -150 50 -150 50 N
P 6 0 1 8 50 50 150 0 50 -50 50 50 50 50 50 50 N
X A1 1 -300 0 100 R 50 50 1 1 P
X K2 2 300 0 100 L 50 50 1 1 P
X K3A4 3 0 -200 100 U 50 50 2 1 P
X A3 4 -300 0 100 R 50 50 2 1 P
X K4 5 300 0 100 L 50 50 2 1 P
X K1A2 6 0 -200 100 U 50 50 1 1 P
ENDDRAW
ENDDEF
```

**Comment by Duckle29** [comment]
@evanshultz That should do it. I don't know what you mean with sharing lines between units, as both units are identical, and a change to one unit is mirrored in the other.

The reason for the previous pin-naming was that I figured the two units were interchangeable, and if you don't check "All units are not interchangeable" then you can't have different pin names between units.

**Comment by Duckle29** [comment]
Example of junction dot

**Comment by evanshultz** [comment]
This option lets you make an element (line, circle, etc.) on all units instead of of having a unique element on each unit:
image

I can uncheck the box (so units are interchangeable) and have different pin numbers. Unfortunately I'm only able to use 4.0.7 at the moment. What version of KiCad are you using?

**Comment by Duckle29** [comment]
@evanshultz Hey there, I'm using the nightly on windows, a few weeks old. I'll give it ago in an hour on my laptop, that's using the ppa

**Comment by evanshultz** [comment]
Great! Unless somebody finds out this doesn't work, I'll assume making symbols this way is OK. Thank you!

**Pull request merged**
