### PR TITLE
Adding AP3211 asynchronous DC-DC buck (step-down) converter.

### PR DESCRIPTION
**Pull request by persus**
Adding AP3211 asynchronous DC-DC buck (step-down) converter.

image

---

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
Don't claim you provided a DS URL when you didn't.

**Comment by persus** [comment]
Sorry.
https://www.olimex.com/Products/Breadboarding/BB-PWR-3608/resources/MT3608.pdf

**Comment by chschlue** [comment]
- [ ] Use manufacturer DS URL
- [ ] Enlarge symbol so that ?_Small fit between BS/SW/FB pins

**Comment by persus** [comment]
> * [X]  Use manufacturer DS URL

https://www.diodes.com/assets/Datasheets/AP3211.pdf
> * [ ]  Enlarge symbol so that ?_Small fit between BS/SW/FB pins

What is "?_small"? Which library convention rule do you mean?
> * [X]  Rename to AP3211K

OK

**Comment by chschlue** [comment]
R_Small, C_Small and so on.
There is no KLC rule but having enough room for these allows for cleaner schematics.

**Comment by persus** [comment]
Like this?

image

**Comment by chschlue** [comment]
Almost, except BS cannot be on top.

**Comment by persus** [comment]
Like this?

image

**Comment by chschlue** [comment]
We're getting there. But GND has to be on the bottom side.

**Pull request closed without merging**
