### PR TITLE
added symbol - Memory_RAM/IDT7006PF dual 16k x 8 dual port ram

### PR DESCRIPTION
**Pull request by bwack**
Datasheet url: https://www.idt.com/document/dst/7006-data-sheet

bilde

Using TQFP64 14x14 footprint from the official footprint library:
https://github.com/KiCad/kicad-footprints/blob/master/Package_QFP.pretty/TQFP-64_14x14mm_P0.8mm.kicad_mod

### CODE REVIEW

**Comment by bwack** [comment]
bilde

**Comment by myfreescalewebpage** [comment]
@bwack positive power pins should not be stacked on this symbol.
The rule (to apply on GND pins here) is: First pin Power Input, visible, other pins Passive, invisible.
Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @bwack , just made a complete review:

- [ ] Description should not contain so much capital letters and must ends with package name, you can change to: `16K x 8 Dual-Port SRAM, TQFP-64`
- [ ] Footprint filter should be `TQFP*14x14mm*P0.8mm*`
- [ ] Pin length should be 100mil for all pins (symbol < 100pins)
- [ ] You can reduce a bit the width of the symbol
- [ ] Name of pin 19 should be `~OE~R`
- [ ] Name of pin 21 should be `~SEM~R`
- [ ] Name of pin 22 should be `~CE~R`
- [ ] Name of pin 38 should be `~INT~R`
- [ ] Name of pin 39 should be `~BUSY~R`
- [ ] Name of pin 40 should be `M/~S~`
- [ ] Name of pin 42 should be `~BUSY~L`
- [ ] Name of pin 43 should be `~INT~L`
- [ ] Name of pin 59 should be `~CE~L`
- [ ] Name of pin 60 should be `~SEM~L`
- [ ] Name of pin 62 should be `~OE~L`
- [ ] VCC pins should not be stacked
- [ ] GND pins stacking to be fixed (see my previous message)

Cheers,
Joel

**Comment by bwack** [comment]
Thanks Joel. After applying suggestions it looks like this:

bilde

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes, no more comment, merging :)

**Pull request merged**
