### PR TITLE
Fix PMEG6010 Schottky diode FPs

### PR DESCRIPTION
**Pull request by chschlue**
Move aliases from SOD-123/-323 to SOD-123F/-323F symbols.

https://assets.nexperia.com/documents/data-sheet/PMEG6010CEH_PMEG6010CEJ.pdf

**Depends on https://github.com/KiCad/kicad-symbols/pull/2211**

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue can you rebase your branches so it will be possible to review this PR ? Thanks, Joel

**Comment by chschlue** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks.
Just checked PMEG2010AET and PMEG2010ET. Package is SOT-23 but the pins used on the symbol are 1-2 whereas the pin used in the datasheet are 1-3.
You just review you pull request.
Joel

**Comment by chschlue** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Same comment here with "PMEGxx05EH" and "PMEGxx05EJ" generic names

**Comment by chschlue** [comment]
@myfreescalewebpage This branch is based on https://github.com/KiCad/kicad-symbols/pull/2211, not master. All commits shown here but https://github.com/KiCad/kicad-symbols/pull/2237/commits/7f15d7b1c75bcba1394150c06d56da97535fe458 are spooks.

**Comment by chschlue** [comment]
In a sudden OCD fit, I also changed SOD-128 descriptions to match all the others.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Following the merge of #2211 it's clearly simpler here to understand the modifications.
No comment do do, merging.

**Pull request merged**
