### PR TITLE
Add ADAU145x SigmaDSPs

### PR DESCRIPTION
**Pull request by evanshultz**
http://www.analog.com/media/en/technical-documentation/data-sheets/ADAU1452_1451_1450.pdf

image

Sorry for the 2.3->2.4 noise in the library...

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Fixed a couple things caught by Travis.

@poeschlr 
Would your script be able to pop out a footprint for this part? It's not called a DFN by Analog Devices but I think the package is compatible with your script except, perhaps, the bevel on the corners.

**Comment by evanshultz** [comment]
@poeschlr 
I believe a suitable footprint is created by adding the following to `https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_DFN_QFN/size_definitions/qfn-other.yaml`. Would you please take a look and perhaps add this to your script so these symbols could be merged?

Maybe this footprint should be manufacturer-specific? And it doesn't have beveled corners as the script doesn't (yet?) support that.

```
LFCSP-72-1EP_10x10mm_Pitch0.5mm_EP5.3x5.3mm_ThermalVias:
  device_type: 'LFCSP'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://www.analog.com/media/en/technical-documentation/data-sheets/ADAU1452_1451_1450.pdf'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  # custom_name_format:
  body_size_x_min: 9.9
  body_size_x: 10.0
  body_size_x_max: 10.1
  body_size_y_min: 9.9
  body_size_y: 10.0
  body_size_y_max: 10.1
  lead_width_min: 0.18
  lead_width_max: 0.3
  lead_len_min: 0.3
  lead_len_max: 0.5

  EP_size_x_min: 5.15
  EP_size_x: 5.3
  EP_size_x_max: 5.45
  EP_size_y_min: 5.15
  EP_size_y: 5.3
  EP_size_y_max: 5.45
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [3, 3]
  #heel_reduction: 0.1 #for relatively large EP pads (increase clearance)

  thermal_vias:
    count: [4, 4]
    drill: 0.3
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    # EP_num_paste_pads: [2, 2]
    #paste_between_vias: 1
    #paste_rings_outside: 1
    EP_paste_coverage: 0.65
    #grid: [1, 1]
    # bottom_pad_size:
    # paste_avoid_via: False

  pitch: 0.5
  num_pins_x: 18
  num_pins_y: 18
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

Images:
image
image

**Comment by poeschlr** [comment]
A lot of qfn packages have a small chamfer on the 4 corners. We do not show it for most of them in the library.
(Showing the chamfer on all 4 corners would make it quite hard to add a pin 1 mark.)

**Comment by evanshultz** [comment]
Footprint PR is at https://github.com/KiCad/kicad-footprints/pull/852.

**Comment by evanshultz** [comment]
Footprints have been merged. This PR is, I believe, also ready to merge.

**Comment by evanshultz** [comment]
Is somebody able to review and merge this?

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz 

No comment to do on this PR. Modification of file format reviewed and ok. Merging.

Joel

**Pull request merged**
