### PR TITLE
Comparator: Add LM397 and TL331

### PR DESCRIPTION
**Pull request by henryhallam**
Add TI's [LM397](http://www.ti.com/lit/ds/symlink/lm397.pdf) single voltage comparator and its pin-compatible cousin [TL331](http://www.ti.com/lit/ds/symlink/tl331.pdf)

lm397

These couldn't be aliases of existing SOT-23-5 comparators since the pinout doesn't match any that are in the library already.

------------

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] If there are matching footprint PRs, provide link(s) as appropriate - **n/a**
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for this nice contribution!

Please remove the duplicate "open drain" and/or "open collector" keywords since those are found in the description and then I will merge!

**Comment by henryhallam** [comment]
Updated - I removed the keywords altogether since all relevant words were in the description. Let me know if that wasn't correct.
Thanks.

**Comment by evanshultz** [comment]
Some keywords are required. Just "single comparator" or something simple is acceptable.

**Comment by antoniovazquezblanco** [comment]
@henryhallam ping! :)

**Comment by evanshultz** [comment]
@henryhallam 
Can you please fix the branch conflicts?

Also, we ask that you use incremental commits instead of force pushes (sounds like it should be from Star Wars!) so that's it's easier to keep track of what happens in a PR between starting and merging it.

**Comment by evanshultz** [comment]
I fixed the branch conflict and apparently I felt things were OK in the past. Nothing jumped out at me just now, so I'll merge.

**Pull request merged**
