### PR TITLE
REF02: add aliases for Analog REF01/REF02/REF03

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds new aliases to the existing REF02 symbol. So far only the TI variants were added, this adds the versions from Analog which use DIP or SOIC packages. [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/REF01_02_03.pdf)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

REF02AP
- [ ] Can you fix the name of pin 2 and 6 at the same time: should be in capital letters. VIN and VOUT
- [ ] Can you fix pin offset at the same time, should be 20mil (see travis error)

REF02HS and REF02EZ
- [ ] Datasheet link problem to be fixed

Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

thanks for the review. I've integrated your feedback.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum the datasheets links of the two devices are still not correct. I see some part is a link to TI and some part is a link to Analog...

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

sorry for this. Now they are really fixed.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, particularly for fixing existing KLC errors on the device.
No more comment, merging.

**Pull request merged**
