### PR TITLE
add LED1642GW

### PR DESCRIPTION
**Pull request by dudelectric**
Push of LED1642GW
Datasheet: https://www.st.com/resource/en/datasheet/led1642gw.pdf
**LED1642GWPTR**
**LED1642GWQTR**
**LED1642GWTTR**
**LED1642GWXTTR**

**LED1642GWXTTR - has Pull Request for the Footprint: https://github.com/KiCad/kicad-footprints/pull/2442**
**LED1642GWQTR - has Pull Request for the Footprint: https://github.com/KiCad/kicad-footprints/pull/2451**

**Change has made to all parts:**
**LED1642GWPTR**
- [x] Fp filter: QSOP*3.9x8.7mm*P0.635mm*
- [x] Pin length:100mil
- [x] Group SDO with SDI
- [x] Decrease the height of the symbol by 100mil

**LED1642GWQTR**
- [x] Fp filter: QFN*1EP*4x4mm*P0.5mm*
- [x] Footprint has new lib: https://github.com/KiCad/kicad-footprints/pull/2451
- [x] Pin length:100mil
- [x] Group SDO with SDI
- [x] Decrease the height of the symbol by 100mil
- [x] EP pin number 25, at the bottom of the symbol, Passive

**LED1642GWTTR**
- [x] Description:"TSSOP-24"
- [x] Pin length:100mil
- [x] Group SDO with SDI
- [x] Decrease the height of the symbol by 100mil

**LED1642GWXTTR**
- [x] Description:"TSSOP-24"
- [x] Fp filter: TSSOP*1EP*4.4x7.8mm*P0.65mm*
- [x] Pin length:100mil
- [x] Group SDO with SDI
- [x] Decrease the height of the symbol by 100mil
- [x] EP pin number 25, at the bottom of the symbol, Passive

image

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @dudelectric , thanks for contributing,

A few comments I have during my review:

LED1642GWPTR
- [ ] Fp filter: `QSOP*3.9x8.7mm*P0.635mm*`
- [ ] Pin length should be 100mil
- [ ] You should group SDO with SDI
- [ ] You can decrease the height of the symbol by 100mil

LED1642GWQTR
- [ ] Fp filter: `QFN*1EP*4x4mm*P0.5mm*`
- [ ] The selected footprint has too large EP, you should submit it if not found in the library
- [ ] Pin length should be 100mil
- [ ] You should group SDO with SDI
- [ ] You can decrease the height of the symbol by 100mil
- [ ] EP pin should be added, pin number 25, at the bottom of the symbol, Passive

LED1642GWTTR
- [ ] Package in the description should be "TSSOP-24"
- [ ] Pin length should be 100mil
- [ ] You should group SDO with SDI
- [ ] You can decrease the height of the symbol by 100mil

LED1642GWXTTR
- [ ] Package in the description should be "TSSOP-24"
- [ ] Fp filter: `TSSOP*1EP*4.4x7.8mm*P0.65mm*`
- [ ] Pin length should be 100mil
- [ ] You should group SDO with SDI
- [ ] You can decrease the height of the symbol by 100mil

Cheers,
Joel

**Comment by dudelectric** [comment]
> 
> 
> Hi @dudelectric , thanks for contributing,
> 
> A few comments I have during my review:
> 
> LED1642GWPTR
> 
>     * [ ]  Fp filter: `QSOP*3.9x8.7mm*P0.635mm*`
> 
>     * [ ]  Pin length should be 100mil
> 
>     * [ ]  You should group SDO with SDI
> 
>     * [ ]  You can decrease the height of the symbol by 100mil
> 
> 
> LED1642GWQTR
> 
>     * [ ]  Fp filter: `QFN*1EP*4x4mm*P0.5mm*`
> 
>     * [ ]  The selected footprint has too large EP, you should submit it if not found in the library
> 
>     * [ ]  Pin length should be 100mil
> 
>     * [ ]  You should group SDO with SDI
> 
>     * [ ]  You can decrease the height of the symbol by 100mil
> 
>     * [ ]  EP pin should be added, pin number 25, at the bottom of the symbol, Passive
> 
> 
> LED1642GWTTR
> 
>     * [ ]  Package in the description should be "TSSOP-24"
> 
>     * [ ]  Pin length should be 100mil
> 
>     * [ ]  You should group SDO with SDI
> 
>     * [ ]  You can decrease the height of the symbol by 100mil
> 
> 
> LED1642GWXTTR
> 
>     * [ ]  Package in the description should be "TSSOP-24"
> 
>     * [ ]  Fp filter: `TSSOP*1EP*4.4x7.8mm*P0.65mm*`
> 
>     * [ ]  Pin length should be 100mil
> 
>     * [ ]  You should group SDO with SDI
> 
>     * [ ]  You can decrease the height of the symbol by 100mil
> 
> 
> Cheers,
> Joel

Hi @myfreescalewebpage  Thanks for your review

**LED1642GWPTR**
- [x]  Fp filter: `QSOP*3.9x8.7mm*P0.635mm*`
- [x] Pin length should be 100mil
- [x]  You should group SDO with SDI
- [x]  You can decrease the height of the symbol by 100mil
image

**Comment by myfreescalewebpage** [comment]
Hello @dudelectric thanks for the update, great job.

For the LED1642GWXTTR, the description should ends with the package name, without "exposed pad": `16-channel LED driver with error detection, current gain control and 12/16 bit PWM brightness control, TSSOP-24` is great

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now

**Comment by chschlue** [comment]
FPs merged.

**Comment by chschlue** [comment]
BTW, I believe TR means tape & reel while package suffixes are P, Q, T and XT, respectively.

**Comment by dudelectric** [comment]
> 
> 
> BTW, I believe TR means tape & reel while package suffixes are P, Q, T and XT, respectively.

Should I change all names to this?

**Comment by myfreescalewebpage** [comment]
I had a doubt but looking as the main vendors I know (mouser, ...) it seems the TR is always present.
So at the moment part name seems correct. Merging.

**Pull request merged**
