### PR TITLE
Add TI 722xx series Voltage Regulators

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo J <mail@aurabindo.in>

Adds TI 722xx series of fixed and adjustable LDOs

kicad_72201

tps722_0
tps72201_1
tps72201_2

kicad_72218
kicad_72216

kicad_72215
tps72218_2
tps72218_1
tps72218_0

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you move the NC pin to the left such that its contact point (the end where a wire can attach) coincides with the symbol outline. (or is within the symbol outline)

This does reduce the chances of accidentally connecting it.

**Comment by jkriege2** [comment]
@poeschlr Can this be merged, or should the version be reset to 2.3 (see https://github.com/KiCad/kicad-symbols/issues/191) ... the symbols look good (IMHO)

JAN

**Comment by jkriege2** [comment]
Please resolve conflicts!

**Comment by aurabindo** [comment]
tps722xx
tps722xx_0
tps722xx_1
tps72218
tps72218_0
tps72218_1

**Comment by aurabindo** [comment]
@jkriege2 conflicts resolved.

**Pull request merged**
