### PR TITLE
Microchip MCU SAME

### PR DESCRIPTION
**Pull request by DerekGn**
This is a replacement PR for PR #50 its related to the work in PR #95 

http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-11296-32-bit-Cortex-M7-Microcontroller-SAM-E70Q-SAM-E70N-SAM-E70J_Datasheet.pdf

ATSAME70Q21A-AN
ATSAME70Q20A-AN
ATSAME70Q19A-AN

image

ATSAME70N21A-AN
ATSAME70N20A-AN
ATSAME70N19A-AN

image

ATSAME70J21A-AN
ATSAME70J20A-AN
ATSAME70J19A-AN

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
could you change the description and keywords a bit? Currently they are:
```
D SAM E70 Microchip SMART ARM-based Flash MCU
K 32-bit ARM Cortex-M7 2048K Flash 384K SRAM LQFP144
```

I think it would be better to have (at least that's the strategy we follow for regulators, transistors, ... i.e. most info in description, especially what sets the parts apart + more general keywords in keywords):
```
SAM E70 Microchip SMART ARM Cortex-M7-based MCU, 2048K Flash, 384K SRAM, LQFP144
+K 32-bit ARM Cortex-M7 MCU microcontroller
```
Especially the footprint should be part of description (see http://kicad-pcb.org/libraries/klc/S6.3/).

Also you could think aout stacking the power-pins to further cleanup the symbols, see http://kicad-pcb.org/libraries/klc/S4.3/ (and https://github.com/KiCad/kicad-symbols/blob/master/Regulator_Linear.lib for several examples). We allow this now with sepcific rules (+checks in the Travis-scripts).

Best,
JAN

**Comment by DerekGn** [comment]
Yes stacking the power would be much cleaner and better for using the part. I will take a look.

Thanks

**Comment by jkriege2** [comment]
please fix the conflict for sym-lib-table, then I can merge!

Thanks ... and if you celebrate: Merry christmas!

JAN

**Comment by DerekGn** [comment]
Hi,
Fixed the conflict.
Merry Christmas to you too :)

**Comment by DerekGn** [comment]
@jkriege2 Somehow I closed this PR before it was merged.

**Comment by jkriege2** [comment]
Hi!

I just checked this again ... it seems that the GND-stack on the `ATSAME70N21A-AN` went wrong: All pins are POWER-INPUT, but only the visible should be POWER_INPUT and the others PASSIVE.

Please fix before I merge!

Thanks,
JAN

**Comment by DerekGn** [comment]
Seems I missed that when i checked over the symbols. fixed now

**Comment by jkriege2** [comment]
Thanks,
JAN

**Comment by poeschlr** [comment]
@DerekGn You might not have missed it. If you open the properties dialog for any pin in a pin stack kicad does change all other pins to have the same pin name and electrical type.
For this reason you need to finish all pins before you stack them. And if you want to change something, you first need to move them apart.

**Pull request merged**
