### PR TITLE
Added symbol TPSM53602RDAR and aliases

### PR DESCRIPTION
**Pull request by hajrudin10**
*Replace this line with your commit message! Please provide a description of your pull request*

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

-Datasheets:
***TPSM53602RDAR** --> https://www.ti.com/lit/ds/symlink/tpsm53602.pdf
***TPSM53603RDAR** --> https://www.ti.com/lit/ds/symlink/tpsm53603.pdf
***TPSM53603RDAR** --> https://www.ti.com/lit/ds/symlink/tpsm53604.pdf

image

-Link to the footprint PR: https://github.com/KiCad/kicad-footprints/pull/2434

-Violations:
*VIN is on the left side and VOUT on the right side: by looking at other symbols this is pretty standard for DCDC converters and voltage regulators
*NC pins are visible and on the bottom position: according to datasheet it is recommended to tie the NC pins to PGND, the "real" not connected pins in this part are called according to datasheet DNC and they are not visible.

### CODE REVIEW

**Comment by Werni2A** [comment]
Hi @hajrudin10 thank you for you contribution. I'm not a official reviewer, so just a hint from my side :)

Your datasheet links in the PR as well as the footprints themselves are pretty long but the part after ".pdf" is not required to identify the document.

This means that you can shorten e.g. 
[https://www.ti.com/lit/ds/symlink/tpsm53602.pdf?ts=1598540493042&ref_url=https%253A%252F%252Fwww.ti.com%252Fstore%252Fti%252Fen%252Fp%252Fproduct%252F%253Fp%253DTPSM53602RDAR%2526utm_source%253Dgoogle%2526utm_medium%253Dcpc%2526utm_campaign%253Dapp-null-null-OPN_EN-cpc-store-google-wwe%2526utm_content%253DDevice%2526ds_k%253DTPSM53602RDAR%2526DCM%253Dyes%2526gclid%253DCj0KCQjws536BRDTARIsANeUZ5_vJ8t9GtFSZ1ZydJHyffGJ-2RDdkveDmfCJBsLhdJH01hKdff-JCIaAoiAEALw_wcB%2526gclsrc%253Daw.ds](https://www.ti.com/lit/ds/symlink/tpsm53602.pdf?ts=1598540493042&ref_url=https%253A%252F%252Fwww.ti.com%252Fstore%252Fti%252Fen%252Fp%252Fproduct%252F%253Fp%253DTPSM53602RDAR%2526utm_source%253Dgoogle%2526utm_medium%253Dcpc%2526utm_campaign%253Dapp-null-null-OPN_EN-cpc-store-google-wwe%2526utm_content%253DDevice%2526ds_k%253DTPSM53602RDAR%2526DCM%253Dyes%2526gclid%253DCj0KCQjws536BRDTARIsANeUZ5_vJ8t9GtFSZ1ZydJHyffGJ-2RDdkveDmfCJBsLhdJH01hKdff-JCIaAoiAEALw_wcB%2526gclsrc%253Daw.ds)
to
[https://www.ti.com/lit/ds/symlink/tpsm53602.pdf](https://www.ti.com/lit/ds/symlink/tpsm53602.pdf)

**Comment by myfreescalewebpage** [comment]
Hi @hajrudin10 , thanks for contributing,

A few comments I have during my review:

TPSM53602RDAR
- [ ] Name should be "TPSM53602RDA"
- [ ] Description should ends with package name: `36V, 2A input, stepdown, DC/DC converter, Texas B3QFN-14`
- [ ] Fp filter: `Texas*B3QFN*1EP*5x5.5mm*P0.65mm*`
- [ ] You should stack pins 3, 10 and 11 with PGND
- [ ] FB above PGOOD will be better for the wiring and it more consistent with other devices in the lib
- [ ] The height of the symbol can be reduced

TPSM53603RDAR
- [ ] Name should be "TPSM53603RDA"
- [ ] Description should ends with package name: `36V, 3A input, stepdown, DC/DC converter, Texas B3QFN-14`

TPSM53604RDAR
- [ ] Name should be "TPSM53604RDA"
- [ ] Description should ends with package name: `36V, 4A input, stepdown, DC/DC converter, Texas B3QFN-14`

Cheers,
Joel

**Comment by hajrudin10** [comment]
Changes implemented.

**Comment by myfreescalewebpage** [comment]
You have stacking error, pins 3, 10 and 11 should be called PGND

**Comment by hajrudin10** [comment]
> You have stacking error, pins 3, 10 and 11 should be called PGND

Hello,
the pins are called NC per datasheet. The connection to PGND is a recommendation not a must. Should I still rename the pins to PGND?

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
> Hello,
the pins are called NC per datasheet. The connection to PGND is a recommendation not a must. Should I still rename the pins to PGND?

Yes because they are stacked with PGND

**Comment by hajrudin10** [comment]
Hello,
I have implemented the changes.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
