### PR TITLE
Adding H5AN8G8NAFR-UHC

### PR DESCRIPTION
**Pull request by ki5libs**
Adding H5AN8G8NAFR-UHC
[Datasheet](https://www.skhynix.com/product/filedata/fileDownload.do?seq=7687)
h5an8g8nafr-uhc
[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/760)
[The old one PR](https://github.com/KiCad/kicad-symbols/pull/772)
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Is it the X8 version (I guess so because you have DQ4-DQ7) ?

If so
A7 should be DM/DBI/TDQS_t
A3 TDQS_c

**Comment by Misca1234** [comment]
Great thx, all looks good

Just a question, would you mind to change the pin length from 150 to 100?
So it looks like most other symbols, you can open the file in a text editor and do a search replace.

**Comment by ki5libs** [comment]
@Misca1234 done

h5_new

**Comment by Misca1234** [comment]
thx

**Comment by evanshultz** [comment]
A few things stick out to me:
- Package type (`FBGA-78`) is not in the description.
- Configuration (`1G x 8`) and default speed (`DDR4-2400`) would be nice to have in the description.
- Ref des and value are floating a bit above the symbol.
- There is no need for the "DDR4" text on top of the symbol.
- The Q and non-Q power pins are a bit offset from each other on top and bottom.
- N7 should be just NC (page 6 and 9) and Not Connected type and invisible. Same with F2, G2, and G8.
- VREFCA and ZQ are supply pins; should they be Power Input type and on the top?
- Where is it mentioned that ALERT is open drain? And it can be an input in test mode.

@ki5libs 
Would you be willing to respond to the above items, if necessary, and then create another PR to make any updates above?

**Pull request merged**
