### PR TITLE
Added BZV55xxxx Zener Diode full list

### PR DESCRIPTION
**Pull request by aris-kimi**
As a `ZMDxx` aliases.
It is the full list of zener diodes expanded.
If this is not acceptable inform me to change to one alias addition in the form of `BZV55xxxx`
Also not sure about `, MiniMELF(SOD-80C)` description ending.

Datasheet: https://assets.nexperia.com/documents/data-sheet/BZV55_SER.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by cpresser** [comment]
> It is the full list of zener diodes expanded.
> If this is not acceptable inform me to change to one alias addition in the form of `BZV55xxxx`

It is acceptable, there is already a series as individual aliases in the lib (`DZ2S030X0L`). Other rather recent commits also added whole series (https://github.com/KiCad/kicad-symbols/pull/2357).

On the other hand, we also merged wildcard style series: https://github.com/KiCad/kicad-symbols/pull/2137
This PR is actually pretty similar to the existing `BZM55xxx` series.

I would rather include the wildcard version. It adds less clutter. I don't see the big benefit for the user of having each voltage as own variant.
Any additional thoughts or input @evanshultz ?

> Also not sure about `, MiniMELF(SOD-80C)` description ending.

I suggest to take `, MiniMELF` to be consistent with other parts already in the lib. Also, the `SOD-80C` string is nowhere to be found in the official libraries.

**Comment by aris-kimi** [comment]
@cpresser , thank you for your answer, i included `SOD-80C` found in the datasheet because it could have saved me some search before i found the correlation to `MiniMELF`. I do like the consistency in libraries, so i will remove it and commit again.

**Comment by evanshultz** [comment]
https://kicad-pcb.org/libraries/klc/G2.1/ is clear that new contributions should use individual parts as ALIASes and not wildcards. So this then looks good. This is relatively new and I believe the rationale is that it's more helpful since users don't have to guess and try where wildcards might be. At the cost of bigger files. There's always a tradeoff but that's KLC as of today.

I would think having both package names in the description, or a keyword, is helpful too. If it's in the description please use parenthesis since we use a forward slash to denote available packages on symbols which aren't fully-specified.

**Comment by aris-kimi** [comment]
Thank you @evanshultz , if i understood correct 
`10V, 500mW, 2%,  Zener diode, MiniMELF(SOD-80C)`
is the acceptable description?
If yes then @cpresser , can you choose to merge only two previous commits? In which i think (beside some mess i've fixed) description fits?

I do want to thank you once again for making me feel welcomed here!!

**Comment by myfreescalewebpage** [comment]
@aris-kimi I have checked this PR too, I think the current description is good.
Just one comment: there is a double space before "Zener" in the description for all the aliases, can you remove one space please ?
Then ready to merge.
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
