### PR TITLE
Add ADS786x series of ADCs

### PR DESCRIPTION
**Pull request by byronhopps**
Added new symbol ADS7866 with aliases ADS7867 and ADS7868

http://www.ti.com/lit/ds/symlink/ads7866.pdf

screen shot 2018-02-14 at 4 49 27 pm

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by byronhopps** [comment]
Looking at the Travis output, it appears that the new symbol I added passes all checks, but when saving the library in the new file format the line order of existing symbols was changed. Since those symbols are not KLC compliant yet, they cause the travis script to fail.

**Comment by poeschlr** [comment]
Yes this is the downside of the fact that different kicad versions use different line ordering in the lib files. (Even different stable versions with the same file format behave differently.)

You can ignore errors for symbols you did not touch.

Note: I did not look at this contribution in any other way. The reason for my comment is to inform the contributor that this (expected) behavior is not a problem.

**Comment by jkriege2** [comment]
The symbol looks good to me ... there's only two things to change:
- please make the SDO-pin tri-state (it's in high-z, when the IC is not selected)
- please change the description to a more standardized format that contains the package at the end, e.g. `Single miniature 12-bit ADC, 100-200ksps, SPI, micro-power, SOT-23-6`

**Comment by byronhopps** [comment]
The requested changes have been made

**Comment by jkriege2** [comment]
Thanks!

JAN

**Pull request merged**
