### PR TITLE
add Mini-Circuits SXBP-series bandpass filter

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/SXBP-140+.pdf
https://ww2.minicircuits.com/pdfs/SXBP-27R5+.pdf
https://ww2.minicircuits.com/pdfs/SXBP-100+.pdf
(there are maybe 20 aliases of this, to be added eventually..)

sxbp-140

Footprint: https://github.com/KiCad/kicad-footprints/pull/1134
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Lines are very large compared to the text (KLC S3.2 http://kicad-pcb.org/libraries/klc/S3.2/). Probably 10mil width is enough
- [ ] The footprint is not correct, you should update it (but footprint filter will no need modification)
- [ ] You can center GND pins, but maybe you want consistency with other MiniCircuit symbols ?

Cheers,
Joel

**Comment by aewallin** [comment]
IMO centered GND pins will obstruct the filter-symbol.
after revision:
sxbp-140

**Comment by myfreescalewebpage** [comment]
> IMO centered GND pins will obstruct the filter-symbol.

Agreed with you.

No more comment, merging.

Joel

**Comment by aewallin** [comment]
This one must wait for the footprint PR to be merged: https://github.com/KiCad/kicad-footprints/pull/1151

**Comment by myfreescalewebpage** [comment]
@aewallin you probably made a mistake, the footprint of this symbol is already merged: https://github.com/KiCad/kicad-footprints/pull/1134 ?

**Pull request merged**
