### PR TITLE
Adding PIC24FJ256DA210 Family Microcontroller

### PR DESCRIPTION
**Pull request by ajmv**
http://ww1.microchip.com/downloads/en/DeviceDoc/39969b.pdf

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for contributing to KiCad!

Similar to what I mentioned at https://github.com/KiCad/kicad-footprints/pull/432, there are a number of items we request to review a new symbol. That part of the default new PR message has been deleted above.

Please post an image of your symbols. And also fix the errors the check scripts caught. I'll stop here to let you get to work on that and please let us know if you have any questions.

**Comment by antoniovazquezblanco** [comment]
@ajmv can you please address the comment above?

**Comment by ajmv** [comment]
@antoniovazquezblanco sorry the delay, I'll try, let me see...

**Comment by antoniovazquezblanco** [comment]
@ajmv no worries. It was just to know if you wanted to keep collaborating. Thank you for comming back :)

**Comment by ajmv** [comment]
Well, the library is very functional for me, I just wanna to contribute but I'm not familiar with github repository, I need some instructions "for dummies" to repair that and give this library to the community. Sorry, my English is very poorly.

**Comment by antoniovazquezblanco** [comment]
I see you are from Venezuela. Here you have what @evanshultz said:

Gracias por contribuir a Kicad!

Igual que comenté en KiCad/kicad-footprints#432, hay una serie de elementos que pedimos como requisito para revisar un símbolo nuevo. Esos elementos son parte del mensaje por defecto cuando se crea un "pull request" y han sido eliminados más arriba.

Por favor, publica aquí una imagen de tus símbolos. Soluciona también los errores que muestra Travis. Pararé aquí antes de revisar el símbolo. Para cualquier otra duda estamos a tu disposición.

Un saludo!

**Comment by antoniovazquezblanco** [comment]
@ajmv Will you be finishing this? Do you need anything else?

**Comment by Misca1234** [comment]
mmmm Venezuela, in 1993 I tried to find a company there where I could do my master thesis, sadly no response therefore I never learned Spanish ;)

I have over taken this push
https://github.com/KiCad/kicad-symbols/pull/1266

**Pull request closed without merging**
