### PR TITLE
Add Cromatek D168K 7-segment display

### PR DESCRIPTION
**Pull request by RockyTV**
The datasheet from Cromatek's website is this: http://www.cromatek.com.br/site/components/com_jshopping/files/demo_products/D1X6_A_rev01.pdf

Although it doesn't list the D168K component in the datasheet, there's [another datasheet in here](http://ead.ime.eb.br/pluginfile.php/21295/mod_folder/content/0/Displays%20LED%20e%20LCD/Cromatek%20D168K.pdf?forcedownload=1) and, comparing both, all that changes is part number - the component dimensions and specifications are the same.

I've made the footprint as well, but I don't know if I should submit a PR or use the existing `7SegmentLED_LTS6760_LTS6780`. The pad hole in the specified footprint is 0.8mm (the D168K uses 0.5mm holes) and it uses oval pads.

### CODE REVIEW

**Comment by RockyTV** [comment]
Cromatek: 


Liteon:


The existing footprint is the Liteon one. I think it's compatible.

**Comment by myfreescalewebpage** [comment]
Hi @RockyTV , thanks for contributing,

First, can you sign the CLA, which is a mandatory condition to accept your contribution? Thanks.

A few comments I have during my review:

- [ ] You have not selected the right part to add an alias. You have selected a Common Cathode part but your device is Common Anode. Please add your alias to the KCSA02-107 device instead.
- [ ] The name of your part contain the manufacturer name, it is not correct. The real name is "D168K", to be fixed
- [ ] Seems the datasheet is not correct or maybe the device name is not. The datasheets speaks about D146A, D196A, D166A and D1X6AB -80B2.

Cheers,
Joel

**Comment by RockyTV** [comment]
> You have not selected the right part to add an alias. You have selected a Common Cathode part but your device is Common Anode. Please add your alias to the KCSA02-107 device instead.

> Seems the datasheet is not correct or maybe the device name is not. The datasheets speaks about D146A, D196A, D166A and D1X6AB -80B2.

There are 2 datasheets attached. I haven't noticed that the datasheet from the manufacturer was for a common anode display, but the specs/dimensions are exactly the same from the other datasheet I linked. I have contacted them to ask if they have the datasheet for D168K or a similar common cathode one, still waiting for a reply. In case you haven't noticed, this is the actual component datasheet: http://ead.ime.eb.br/pluginfile.php/21295/mod_folder/content/0/Displays%20LED%20e%20LCD/Cromatek%20D168K.pdf?forcedownload=1


> The name of your part contain the manufacturer name, it is not correct. The real name is "D168K", to be fixed

I'll fix it.

**Comment by myfreescalewebpage** [comment]
@RockyTV I'm speaking about the datasheet in the library itself, I don't care of the ones on the PR. So in any case there is something not coherent in the symbol definition you made and need to be corrected...

**Comment by RockyTV** [comment]
I've updated the device listing. The server that hosted the datasheet got back up so I downloaded it and uploaded to archive.org. Should be good to go now.

**Comment by myfreescalewebpage** [comment]
@RockyTV  thanks for the clarifications. Checked the datasheet. Symbol is ok but not the footprint, thus it is not possible to make an alias of the KCSC02-105.

You should create a new part (copy the KCSC02-105 for example), and create the correct footprint (it seems it does not exist in the lib but you can double check too). Proposed name: `Display_7segment:Cromatek_Dxxxx` because it seems the package can be used for several devices.

Cheers,
Joel

**Comment by RockyTV** [comment]
What's wrong with the footprint? The only difference I've found is that the
drill holes are bigger. The rest of the dimensions are fine, no?

**Comment by RockyTV** [comment]
I think there's no need to create a new footprint. As stated in OP:

> I've made the footprint as well, but I don't know if I should submit a PR or use the existing `7SegmentLED_LTS6760_LTS6780`. The pad hole in the specified footprint is 0.8mm (the D168K uses 0.5mm holes) and it uses oval pads.

**Comment by myfreescalewebpage** [comment]
The footprint `7SegmentLED_LTS6760_LTS6780` is 18x12.5mm, whereas D168K is 19.05x12.6mm so a new footprint is required, we do not tolerate approximations, we use precised footprint dimensions.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@RockyTV any news here ? Have you created a new footprint ? If so, can you indicate a link to the footprint pull request here ? Thanks, Joel

**Comment by RockyTV** [comment]
I'm sorry, I've formatted my PC and forgot to update this PR. Will try to get it done this week!

**Comment by myfreescalewebpage** [comment]
@RockyTV no worries, that was just to get some news from you :)

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this is abandoned.

**Comment by RockyTV** [comment]
@myfreescalewebpage I am sorry for forgetting about this, I've submitted the footprint PR and I'll fix this PR as well.

Thanks for reminding me (I got notified by email).

**Comment by myfreescalewebpage** [comment]
Thanks @RockyTV , just removed the Abandoned tag.
Joel

**Comment by myfreescalewebpage** [comment]
No news of the original author, indicate the PR is abandoned.

**Comment by RockyTV** [comment]
Why mark it as abandoned? I fixed what you asked, was just waiting for a review.

**Comment by myfreescalewebpage** [comment]
Sorry, have been a little to much fast on this... waiting the footprint

**Comment by myfreescalewebpage** [comment]
@RockyTV back on symbol review now.

- [ ] The name of the main symbol should be "D168K", not "Cromatech...."
- [ ] Then you can add aliases for the other variants with a different color
- [ ] Footprint to be updated: `Display_7Segment:D1X8K`
- [ ] Fp filter to be updated: `D1X8K*`
- [ ] Datasheet to be updated: `https://ia800903.us.archive.org/24/items/CTKD1x8K/Cromatek%20D168K.pdf`
- [ ] Pin name position offset should be 20mil

Joel

**Comment by RockyTV** [comment]
> Pin name position offset should be 20mil

How do I achieve this? Shouldn't pin name be aligned to a 50mils grid?

**Comment by RockyTV** [comment]
There you go.

**Comment by myfreescalewebpage** [comment]
Perfect ! No comment, merging, thanks for all the work you have done on this part.
Joel

**Pull request merged**
