### PR TITLE
SMPS controller/converter: Add, move, and fix symbols

### PR DESCRIPTION
**Pull request by evanshultz**
When adding some new SMPS controller ICs, I noticed the TOPxxx symbols in Regulator_Controller should be in Regulator_Switching. I moved them in addition to adding the new parts. And also a few fixes to existing symbols.

I think we have enough PFC SMPS controller to warrant their own library. Maybe not right now with the imminent release of v5, but I think we've hit the threshold. We have more than 30. Perhaps Regulator_ControllerPFC.lib?

There is a missing SSOP-10 footprint. Please merge now and I'll add the footprint shortly.

General:
- Replaced all footprint "Pitch" with "P"
- Fixed FPfilter for TOP209P

LM25119:
- Add default footprint
- Made pins 100mil length

NCP1200*:
- split into MPNs for various frequencies
- improve description
- fix pin 3 name to "CS" (was "CS1")
- add NC pin 7
- place power pins on top and bottom

Add to Regulator_Switching:
- FSBH0F70A/0170/0170A/0270/0270A/0370: https://www.fairchildsemi.com/datasheets/FS/FSBH0370.pdf
- FSBH0F70WA/0170W/0270W: http://www.onsemi.com/pub/Collateral/FSBH0270W-D.pdf
- NCP107x: http://www.onsemi.com/pub/Collateral/NCP1070-D.PDF

Add to Switching_Controller:
- ICE1PCS01: https://www.infineon.com/dgdl/Infineon-ICE1PCS01-DS-v01_03-en.pdf?fileId=db3a304412b407950112b427c6f13cc7
- ICE1PCS02: https://www.infineon.com/dgdl/Infineon-ICE1PCS02-DS-v01_02-en.pdf?fileId=db3a304412b407950112b427c9283ccb
- ICE2PCS01: https://www.infineon.com/dgdl/Infineon-ICE2PCS01-DS-v02_03-en.pdf?fileId=db3a304412b407950112b427caa43ccf
- ICE2PCS02: https://www.infineon.com/dgdl/Infineon-ICE2PCS02-DS-v02_04-en.pdf?fileId=db3a304412b407950112b427cc3c3cdc
- ICE2PCS03: https://www.infineon.com/dgdl/Infineon-ICE2PCS03-DS-v02_01-en.pdf?fileId=db3a30431936bc4b01193b45457e52a1
- ICE2PCS04: https://www.infineon.com/dgdl/Infineon-ICE2PCS04-DS-v02_01-en.pdf?fileId=db3a30431936bc4b01193b4e467952a9
- ICE2PCS05: https://www.infineon.com/dgdl/Infineon-ICE2PCS05-DS-v01_02-en.pdf?fileId=db3a30431c69a49d011cdfb46a834373
- ICE2PCS06: https://www.infineon.com/dgdl/Infineon-ICE2PCS06-DS-v01_01-en.pdf?fileId=db3a3043327f13e3013285ff4ecb2e77
- ICE3PCS01: https://www.infineon.com/dgdl/Infineon-ICE3PCS01-DS-v03_00-EN.pdf?fileId=db3a304329a0f6ee0129a67ae8c02b46
- ICE3PCS02: https://www.infineon.com/dgdl/Infineon-ICE3PCS02G-DS-v03_00-EN.pdf?fileId=db3a304329a0f6ee0129a67fab472b4b
- ICE3PCS03: https://www.infineon.com/dgdl/Infineon-ICE3PCS03G-DS-v03_00-EN.pdf?fileId=db3a304329a0f6ee0129a683c9c92b50
- ISL6551: https://www.intersil.com/content/dam/Intersil/documents/isl6/isl6551.pdf
- L4981A/B: http://www.st.com/resource/en/datasheet/l4981.pdf
- L4984: http://www.st.com/resource/en/datasheet/l4984d.pdf
- L6561: http://www.st.com/resource/en/datasheet/l6561.pdf
- L6262: http://www.st.com/resource/en/datasheet/l6562.pdf
- L6562A: http://www.st.com/resource/en/datasheet/l6562a.pdf
- L6562AT: http://www.st.com/resource/en/datasheet/l6562at.pdf
- L6563/A: http://www.st.com/resource/en/datasheet/l6563.pdf
- L6563H: http://www.st.com/resource/en/datasheet/l6563h.pdf
- L6563S: http://www.st.com/resource/en/datasheet/l6563s.pdf
- L6564: http://www.st.com/resource/en/datasheet/l6564.pdf
- L6564H: http://www.st.com/resource/en/datasheet/l6564h.pdf
- L6564T: http://www.st.com/resource/en/datasheet/l6564t.pdf
- L6598: www.st.com/resource/en/datasheet/l6598.pdf
- L6727: http://www.st.com/resource/en/datasheet/l6727.pdf
- NCP1207A/B: http://www.onsemi.com/pub/Collateral/NCP1207B.PDF
- NCP1280: https://www.onsemi.com/pub/Collateral/NCP1280-D.PDF
- NCP1380A/B/C/D: https://www.onsemi.com/pub/Collateral/NCP1380-D.PDF
- NCP1653/A: https://www.onsemi.com/pub/Collateral/NCP1653-D.PDF
- TDA4862: https://www.infineon.com/dgdl/Infineon-PFC_DCMICTDA4862G-DS-v02_00-en.pdf?fileId=db3a304412b407950112b417ffae24a3
- TDA4863: https://www.infineon.com/dgdl/Infineon-TDA4863-DS-v02_00-en.pdf?fileId=db3a304412b407950112b427d2d23ce8
- TDA4863-2: https://www.infineon.com/dgdl/Infineon-TDA4863_2-DS-v02_01-en.pdf?fileId=db3a304412b407950112b41802de24ab
- UC3854: http://www.ti.com/lit/ds/symlink/uc3854.pdf
- UCC25600: http://www.ti.com/lit/ds/symlink/ucc25600.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Since there are so many new symbols, here is a sample:
image

**Comment by evanshultz** [comment]
NCP1070 uses a DIP-8 with pin 7 missing. See http://www.onsemi.com/pub/Collateral/NCP1070-D.PDF. How should we call this footprint? I selected `DIP-8-7_W7.62mm`, which follows our "missing pins" nomenclature. In many cases, especially vendor-specific footprints, this works. But in this case, how to know if the missing pin is pin 1, pin 2, pin 8, etc.? We also want our FPfilter to catch the footprint and not allow the trailing wildcard to allow any 8 pin footprints. This is ugly, but perhaps `DIP-8-NoPin6_W7.62mm`?

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 
Any input on the footprint naming question above? How to name a footprint with a random pin missing? I don't see that IPC-7251/7351 covers this case. They have a scheme for missing pins, but not a way to indicate which pin is missing.

And... any chance to get this reviewed?

**Comment by poeschlr** [comment]
About footprint naming. I am not really sure how we should handle this. If only one pin is missing your suggestion isn't too bad. If there are multiple missing pins it might get a bit messy.

---

One option here would be to have true atomic parts iff such a package is not really used by anything else. (Name the package after the component.)

---

The screenshot of the symbols looks good.

For the future could you please separate fixing old stuff from adding new things? New symbols need to be checked a lot more thorough than changing existing symbols. (For new symbols i like to check if they have the correct pin number, pin name and electrical triple for all pins.)

**Comment by evanshultz** [comment]
@poeschlr 
Yeah, it's just that if we have multiple footprints that are identical but have different names, it's annoying and a maintenance problem. But right now I don't have an elegant way to name these footprints either.

I started adding new parts, but then found a few things to touch with the existing symbols. I understand what you mean about it getting messy.

Is this able to be merged? I didn't see any request for changes.

**Comment by evanshultz** [comment]
@poeschlr 
OK. I'm fine to go with this footprint naming for now but I think we'll need something better eventually.

I don't see any requested changes above so I assume you answered one question but haven't had time to review yet?

**Comment by poeschlr** [comment]
@evanshultz wrote:
> I don't see any requested changes above so I assume you answered one question but haven't had time to review yet?

Yup sadly i am currently a bit short on time. (That's why it would be better to split fixes from new contributions. Reviewing a fix takes a lot less time as i only need to ensure that you did not make anything worse.)

**Comment by evanshultz** [comment]
@jkriege2 @Ratfink 
Are you guys able to review this?

**Comment by daab4848** [comment]
@evanshultz @poeschlr 

> NCP1070 uses a DIP-8 with pin 7 missing. See http://www.onsemi.com/pub/Collateral/NCP1070-D.PDF. How should we call this footprint? I selected `DIP-8-7_W7.62mm`, which follows our "missing pins" nomenclature. In many cases, especially vendor-specific footprints, this works. But in this case, how to know if the missing pin is pin 1, pin 2, pin 8, etc.? We also want our FPfilter to catch the footprint and not allow the trailing wildcard to allow any 8 pin footprints. This is ugly, but perhaps DIP-8-NoPin6_W7.62mm?

- Could an abbreviated prefix be used to specifically denote the missing pin? Perhaps "N" for No-pin, "M" for Missing-pin, or "O" for Omitted-pin. 

-In any case, using an abbreviated prefix makes the footprint name more concise and easier to implement in the FPfilter.

- For the NCP1070 and using "N" as the abbreviated prefix for No-pin, the `DIP-8-7_W7.62mm` could be renamed as `DIP-8-N6_W7.62mm`.

- If there are a few more pins, such as LT3638, then the missing pins can be appended with a "-". and listed in ascending order. Example: `MSOP-12-16` could be renamed as `MSOP-12-N2-4-13-15' or maybe even `MSOP-12-N2-N4-N13-N15' (the latter seems to be more FPfilter friendly)

- While there exists the possibility of encountering package(s) with more than 4 missing pins, I think it's relatively safe to say that such packages are the exception rather than the norm. Even though the LT3638 had 4 missing pins, it was done in a rather symmetrical way and was done mainly for voltage isolation, so it narrows down the possible number of packages with 4 or more missing pins. And therefore, footprint naming can be expected to be less ugly and less cumbersome (one hopes).

- Also according to KLC F2.4, the naming scheme for packages for missing pins were `PKG-<xx>-<yy>`, where <xx> = number of remaining pins and <yy> = number of remaining pins + number of removed pins. @evanschultz's footprint name for the NCP1070 seems to violate this (i.e. shouldn't it be `DIP-7-8_W7.62mm` ?).

-Any additional thoughts and comments?

**Comment by evanshultz** [comment]
@daab4848 
A concise place to look at for this issue is http://www.onsemi.com/pub/Collateral/NCP1076A-D.PDF, which has two packages available, both like an 8 pin DIP, but with either pin 3 or pin 6 removed.

We default to IPC standards for footprint naming in the official library. The conventions in IPC 7351 does not cover this specific case, unless I'm mis-reading it. What you mention above may work, similar to what I mentioned above but more concise. It's still pretty verbose and, to me, looks ugly; then again, there aren't many footprints like this.

IPC 7351 is where we took the hidden pins and deleted pins footprint naming from. And after reading it again, I'm using pin number 8, I think you are correct.

**Comment by evanshultz** [comment]
@Ratfink 
Would you perhaps be able to review these symbols? The footprint naming is an open issue, but if the symbols are OK then we're most of the way there.

**Comment by Ratfink** [comment]
Sure, I'll have a look.

**Comment by Ratfink** [comment]
Here are the rest of my notes.  With these and the one note above fixed, I think the symbols (excepting the ongoing footprint naming discussion) will be okay.

* L4981A/B: Pin 20 should be "GDRV".
* L6598: Pins 6 and 7 should be "OPIN-" and "OPIN+", respectively (datasheet does say OPON in one place, but since the pins are op-amp inputs, OPIN makes more sense).
* NCP1207A/B: I think it would make sense to make these symbols drop-in compatible with one another.  Also, I believe the pin numbering on the B variant is wrong (HV should be 8 since KLC says that missing pin numbers are skipped).
* NCP1380A/B/C/D: Pin 8 (CT) is just connected to a capacitor, so should it be electrical type Passive?
* TDA4862: Pin 8 (VCC) should be electrical type Power Input, I believe.
* UC3854: First FPFilter should be "SOIC*7.5x10.3mm*P1.27mm".  I believe Pin 5 (MULTOUT) should be Bidirectional.

**Comment by evanshultz** [comment]
Good catches all around! Thank you! Everything should be OK except for pin 7/8 numbering on NCP1207B, since that's the open issue that also affects the footprint.

I changed the pin type on UC3854 to Passive, since it's only connected to passive parts and doesn't generate or receive any signals that are passed to any other parts (it's only an input and output to other internal circuitry). I also created an issue at https://github.com/KiCad/kicad-symbols/issues/381 to seek consensus and specify in KLC what pin type should be used for non-logic (analog) pins.

**Comment by evanshultz** [comment]
@Ratfink 
If I select a normal DIP8 package would you merge this PR? I promise to create a case to capture the discussion about the 7-pin version of the package, create the footprint once we've settled on the naming, and then update the symbols that need that footprint in another PR. In the interim, a normal 8-pin footprint will still work. I'm pushing because there are a lot of symbols without any controversy here and I'd like to avoid a branch conflict.

**Comment by Ratfink** [comment]
As I understand it, the reason for omitting a pin on a device like this is for high voltage isolation.  Using a regular DIP-8 footprint would put a piece of copper between the pads that should be isolated, somewhat defeating the purpose.

Maybe remove the missing-pin symbols from this PR instead, and submit them in a new PR later once the naming discussion is resolved?  When the time comes, you could link the new PR to this one to remind us that they've already been reviewed for everything other than the footprint association and filters.

**Comment by evanshultz** [comment]
I would use the word "creepage" (across the package body) or "clearance" (through air) rather than "isolation", but the idea is the same. That's the major reason I'm aware of. That being said, I think we're still OK.

Check out the [NCP1207B datasheet](http://www.onsemi.com/pub/Collateral/NCP1207B.PDF). If VCC has a 10uF cap, HV can go up to 500V. UL 60950-1 Table 2Q says that across a PCB surface with soldermask for non-reinforced insulation, 1.0mm supports 570V. Looking at our SOIC-8 footprint, the spacing between a pair of pads is 0.67mm or 1.34mm total adding the distance from pad 6 to 7 to 8. So considerably more than the minimum requirement I referenced, but of course there are many caveats and more distance is always better.

But instead of trying to ram this through I'll wait a couple days to see if we can relatively quickly settle on a naming convention for footprints with a single pin missing. The footprint naming issue is at https://github.com/KiCad/kicad-footprints/issues/436.

**Comment by evanshultz** [comment]
Missing footprints submitted at https://github.com/KiCad/kicad-footprints/pull/441. Updated affected symbols. Once ST gives me the info for the SSOP10 footprint I'll add it. I think this should be ready for merge.

**Comment by poeschlr** [comment]
Sorry for missing this. Here my answers regarding the footprint naming. (Man i wish one could split parts of discussions in github like i can over at the forum.)

> Could an abbreviated prefix be used to specifically denote the missing pin? Perhaps "N" for No-pin, "M" for Missing-pin, or "O" for Omitted-pin.

Seems like a good approach. I feel we are already a bit away from easily human readable footprint names so adding more single letter prefixes is ok to me. (As long as they are documented in the KLC)

I am not sure which of these would be the best idea. (I have a slight preference for "N" or "M" over "O") Does IPC say something about that?
(Or is your suggestion to add all 3. If so then i might need a bit more explanation of the different meanings as i don't see it right now.)

> If there are a few more pins, such as LT3638, then the missing pins can be appended with a "-". and listed in ascending order. Example: MSOP-12-16 could be renamed as 'MSOP-12-N2-4-13-15' or maybe even 'MSOP-12-N2-N4-N13-N15' (the latter seems to be more FPfilter friendly)

Again an interesting question. I don't think the later is more fp filter friendly but i think it is easier to read.

**Comment by evanshultz** [comment]
I already started a new discussion for this topic at https://github.com/KiCad/kicad-footprints/issues/436. It's linked above and even commented on that dedicated naming issue.

**Comment by evanshultz** [comment]
@Ratfink 
I have a few outstanding footprints for this symbol PR, which are linked above and you can merge if you like (hehehe...), but I've adopted the naming style discussed already. If there's nothing else, is this ready to merge?

**Comment by Ratfink** [comment]
Okay, now that all the relevant footprints are merged, I'll merge this as well.  Thanks for adding these chips!

**Pull request merged**
