### PR TITLE
Adding MXM3.0 connector

### PR DESCRIPTION
**Pull request by ki5libs**
[MXM3.0 Specification](https://wenku.baidu.com/view/ecf588fbf705cc175527092d.html)

MXM_new

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/1508)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks for this contribution!
We have previously decided in an other pull request that this kind of symbol should group pin by functions, not depending of the position on the conenctor. See https://github.com/KiCad/kicad-symbols/pull/1196 for example.

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

I've reworked this symbol. It's single unit now. I've grouped pins according to specification.

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks, not bad! Starting the review right now, some comments:

- [ ] Pin length should be 150mil for this symbol (>=100pins and <1000pins)
- [ ] I wonder if KEY pins should be in the symbol and the footprint ? Are they really present ?
- [ ] What are the OEM and RSVD pins ?
- [ ] The provided datasheet is clearly not enough, do you have a better reference to make the review ?
- [ ] The footprint filter should be simply `*MM70*` for this symbol to allow several sources

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage , sorry for some delay in answering.
>Pin length should be 150mil for this symbol (>=100pins and <1000pins)

Done,  made symbol a little bit smaller
>I wonder if KEY pins should be in the symbol and the footprint ? Are they really present ?

They are not actually present on the footprint. It was my mistake to show them on the symbol. I've removed them now.
>What are the OEM and RSVD pins ?

According to the specification (page 34):

> OEM (8 pins). OEM reserved pins. System may connect these pins to extend the MXM functionality or to obtain cost reduction. Compliant MXM modules must not connect to any of the OEM pins.
RSVD (24 pins). Reserved pins for future use. System must not connect any of these pins to ensure compatibility with future MXM versions. MXM version 3.0 modules must not connect to these pins.

>The provided datasheet is clearly not enough, do you have a better reference to make the review ?

It's official specification and I thought that it's better variant to refer than any custom MXM module datasheets. I'm sorry for the link, maybe it's not very comfortable but I couldn't find any more places of this specification. Some references lead to [this site](http://www.mxm-sig.org/), but it looks unavailable now.
>The footprint filter should be simply *MM70* for this symbol to allow several sources

Done

**Comment by myfreescalewebpage** [comment]
@ki5libs about the datasheet, it's plenty of Chinese I do not understood at all where to get the complete document and I'm not able to review the pin numbers for example. Can you attached it to the pull request in PDF format ?

**Comment by ki5libs** [comment]
@myfreescalewebpage sorry, but I can't. I spent couple of hours trying to pay for downloading from Baidu, but it was unsuccessful. I'm also not very convenient with Chinese, but figured out how to see complete specification. Hope you could do it too.
Show1
Pressing on upper marked area shows first 40 pages, pressing on lower marked area - the rest of document.
Sorry again, but I couldn't found this document anywhere else.

**Comment by myfreescalewebpage** [comment]
Thanks for this, I will continue like that :)

**Comment by myfreescalewebpage** [comment]
@ki5libs make a full review from this point. Here are my comments:

- [ ] We prefer in this kind of case to remove the datasheet link, please
- [ ] Name of pin 24 is `TH_PWM`
- [ ] Name of pin 27 is `PNL_BL_PWM`
- [ ] You can cross the position of OEM pins 41 and 42 to get all OEM pins in the right order
- [ ] You can organize the position of the pins RSVD to get them ordered by pin number like OEM pins

Else, good symbol!

Cheers,
Joel

**Comment by ki5libs** [comment]
@myfreescalewebpage 

I've done everything you listed. Removing datasheet link led to Travis error. Do you think it's OK?

**Comment by myfreescalewebpage** [comment]
Oh yes sorry, please just enter `~`in the datasheet link to make travis happy :)
Else no more comment.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
