### PR TITLE
add Mini-Circuits PHA-13HLN as alias

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the [PHA-13HLN](https://www.minicircuits.com/pdfs/PHA-13HLN+.pdf) RF amplifier from Mini-Circuits. As it uses a standard SOT-89 it is simply an alias to a similar, existing amplifier.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by lorem-ipsum** [comment]
As I started to need more of the amplifiers I "scripted" all the SOT-89 amplifiers of Mini-Circuits. I did not check all of them, but checked samples from every series (GALI, GVA, PVA, PHA).

**Comment by aewallin** [comment]
none of the "ww2" URLs are working for me today - is the generic url supposed to start with "www" and then there is a load-balancer (or whatever) on the server-side that directs to "ww2".

this probably applies to many other mini-circ parts.

**Comment by lorem-ipsum** [comment]
This is new, bit still the case. I will fix this one in the next days and also post a PR to fix the existing links in the library.

**Comment by lorem-ipsum** [comment]
rebased against master (to get the other symbol links fixed) and fixed the links

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum can you rebase again so it's possible to review the PR properly ? Thanks. Joel

**Comment by lorem-ipsum** [comment]
Rebased

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
