### PR TITLE
Add PAT1220.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://www.susumu.co.jp/common/pdf/n_catalog_partition16_en.pdf

image

footprint: https://github.com/KiCad/kicad-footprints/pull/1288

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] I disagree with the name of the devices and their description. You indicate 50ohm impedance in the description, so you have to put the complete name of the devices with the correct spelling from the manufacturer: `PAT1220-C-0dB`, `PAT1220-C-1dB`, ..., `PAT1220-C-10dB`
- [ ] I would suggest that pin 3 should be renamed `~` and type set to Passive because some users will maybe not connect this to GND depending of their application

Else sounds good.

Cheers,
Joel

**Comment by matthuszagh** [comment]
Made the changes.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
