### PR TITLE
Add Tps6300x

### PR DESCRIPTION
**Pull request by jneiva08**
Add Buck-Boost Converter  TPS6300x

symbol based in TPS63060

Datasheet: http://www.ti.com/lit/ds/symlink/tps63000.pdf

Footprint: [PR #1212](https://github.com/KiCad/kicad-footprints/pull/1212)

tps63000

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08, thanks for contributing,

A few comments I have during my review:

- [ ] Description should end with full package name `, VSON-10`
- [ ] There is a double space in the keywords of the TPS63001 between "3.3V" and "converter"

Else, need to wait for the footprint.

Cheers,
Joel

**Comment by jneiva08** [comment]
Hi @myfreescalewebpage, have made the alterations you requested.

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 thanks, no more comment, just need to wait for the footprint before we can merge.

**Comment by myfreescalewebpage** [comment]
Merging following integration of the footprint.

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
