### PR TITLE
- Created library MCU_Renesas_Synergy_S1

### PR DESCRIPTION
**Pull request by rdmeneze**
-- added R7FS128783A01Cxx LQFP48
-- 32-bit ARM ® Cortex ® -M0+ Microcontroller
-- Ultra low power 32-MHz ARM ® Cortex ® -M0+ microcontroller, up to 256-KB code flash memory, 24-KB SRAM, Digital Addressable Lighting Interface, Capacitive Touch Sensing Unit, 14-bit A/D Converter, 8-bit D/A Converter, security and safety features.
-- https://www.renesas.com/us/en/doc/products/renesas-synergy/doc/r01ds0309eu0100-synergy-s128.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Sorry for the late feedback.

The symbol name should wildcard the temperature range. But it should not wildcard the package. Meaning the correct name would be `R7FS12878xA01CFL` (for the lqfp-48 version)

Stack ground pins (moves responsibility for correct schematic from the circuit designer to the library team)

VREFH0 and VREFL0 are exchanged

**Comment by myfreescalewebpage** [comment]
@rdmeneze ping! :)

**Comment by rdmeneze** [comment]
@myfreescalewebpage , @poeschlr ping ;)

**Comment by rdmeneze** [comment]
> 
> 
> @rdmeneze ping! :)

I did a mistake  :(

I'm using a new computer and after I performed the commit I noticed that my github wasn't configured and the git performed the commit using a random user name. Do you know how I can fix it?

**Comment by myfreescalewebpage** [comment]
Taking next steps of the review. Here are my comments:

- [ ] I would suggest to update description format as already done on other similar devices. What do you think of `ARM Cortex-M0+ MCU, 32MHz, 256KB Flash, 24KB RAM, 1.65-3.6V, 37 GPIO, LQFP-48` ?
- [ ] Keywords can be the same of other similar devices, you can update to `32-bit ARM Cortex-M0+ MCU Microcontroller`
- [ ] Name of pin 44 is `P011/VREFL0`
- [ ] Name of pin 45 is `P010/VREFH0`
- [ ] VCL should be Passive and at the bottom of the left or right side to simplify wiring (capacitor to GND)
- [ ] RES should be next to SWDIO and SWCLK to simplify wiring
- [ ] You should stack VSS pins
- [ ] VSS_USB is Power Input
- [ ] Can you align VCC_USB with VSS_USB, AVCC0 with AVSS0 etc ?
- [ ] Can you detail how you have group pins ? With not grouping P0xx, P1xx, etc ?
- [ ] Can you put pins in the right order, i.e. P009 above P010, above P011 etc ?

Cheers,
Joel

**Comment by rdmeneze** [comment]
> 
> 
> Taking next steps of the review. Here are my comments:
> 
>     * [ ]  I would suggest to update description format as already done on other similar devices. What do you think of `ARM Cortex-M0+ MCU, 32MHz, 256KB Flash, 24KB RAM, 1.65-3.6V, 37 GPIO, LQFP-48` ?
> 
>     * [ ]  Keywords can be the same of other similar devices, you can update to `32-bit ARM Cortex-M0+ MCU Microcontroller`
> 
>     * [ ]  Name of pin 44 is `P011/VREFL0`
> 
>     * [ ]  Name of pin 45 is `P010/VREFH0`
> 
>     * [ ]  VCL should be Passive and at the bottom of the left or right side to simplify wiring (capacitor to GND)
> 
>     * [ ]  RES should be next to SWDIO and SWCLK to simplify wiring
> 
>     * [ ]  You should stack VSS pins
> 
>     * [ ]  VSS_USB is Power Input
> 
>     * [ ]  Can you align VCC_USB with VSS_USB, AVCC0 with AVSS0 etc ?
> 
>     * [ ]  Can you detail how you have group pins ? With not grouping P0xx, P1xx, etc ?
> 
>     * [ ]  Can you put pins in the right order, i.e. P009 above P010, above P011 etc ?
> 
> 
> Cheers,
> Joel

Hi Joel!
Thank for your comments. 

I'm new at KiCAD and I'd like to know how to do this: 
> You should stack VSS pins

**Comment by myfreescalewebpage** [comment]
Hi @rdmeneze thanks for the fixes you already done.

> I'm new at KiCAD and I'd like to know how to do this:
You should stack VSS pins

Sure. Every VSS pins at the same place, first pin is Power Input and visible, the other pins are Passive and invisible.

Thanks for pin grouping modification. I still need to have P2xx and P1xx in the right order. Why grouping P2xx with P3xx ?

A last comment about pin names: we arrange pin name to always have the primary pin function near to the border of the symbol. For example you should rename pin 14 to `USB_DP/P914` to achieve this (to be done on all concerned pins).

Joel

**Comment by rdmeneze** [comment]
thank you @myfreescalewebpage for your comments.
> Thanks for pin grouping modification. I still need to have P2xx and P1xx in the right order. 
> Why grouping P2xx with P3xx ?
ok. Now I saw what are you was talking about. My mistake!
-----

> A last comment about pin names: we arrange pin name to always have the primary pin function near 
> to the border of the symbol. For example you should rename pin 14 to USB_DP/P914 to achieve 
> this (to be done on all concerned pins).
ok. I copied the pin names from the datasheet figure 1.4.   
I changed the pins names following your recommendations and I have one question: at the datasheet item 1.7, we can found the associations between  the port names and the port functions. I'd like to know if I have to put at the symbol all pin names? For example, the port P400 can be associated to 5 different peripherals. Have I to add all peripherals at the gpio name?

**Comment by myfreescalewebpage** [comment]
There is still some few enhancements to do about pin name and place, I propose you to follow this proposition:

Capture

> I'd like to know if I have to put at the symbol all pin names

No, we have stopped doing this, still make two large symbol for no reason. The actual names are enough.

Joel

**Comment by rdmeneze** [comment]
ping @myfreescalewebpage

**Comment by myfreescalewebpage** [comment]
Still not at the right place for no reason, see the screenshot below:

Capture

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
