### PR TITLE
update TMLM series and add missing symbols

### PR DESCRIPTION
**Pull request by lorem-ipsum**
- remove redundant aliases in favour of TMLM041xx
- add missing symbols with higher output power
- add dual output variants TMLM042xx
- slightly update description

[datasheet](https://www.tracopower.com/products/tmlm.pdf), footprints are already exsting
* TMLM041xx (unchanged)
tmlm041xx
* Dual output variant
tmlm042xx
* Higher power variants (AC connections are not distinguished)
tmlm051xx

### CODE REVIEW

**Comment by lorem-ipsum** [comment]
This fixes issues #154 and #155

**Comment by Misca1234** [comment]
If these are galvanic isolated they should perhaps have a division line to mark that ?
(like some of the others ACDC, DCDC)

**Comment by lorem-ipsum** [comment]
so far none of the ACDC converters have that line. I am not really sure if it helps adding it. If it should be added then it should most likely be added to all other ACDC converts as well (would need to check the datasheets for that).

**Comment by Misca1234** [comment]
It is not stated in the guidelines so I guess it is more of a matter of taste among the heavyweighters within the library admin team.

**Comment by lorem-ipsum** [comment]
As there seems to be some agreement by now I reworked the footprints. I also increased the height of the boxes a bit as I found them a bit to crowded.

tmlm042xx
tmlm041xx

**Comment by Misca1234** [comment]
@lorem-ipsum 
You got a branch conflict in this push, it needs to be solved

**Comment by lorem-ipsum** [comment]
I did the rebase and I think I didn't break anything

**Comment by Misca1234** [comment]
I have to dissagree a little with you about your clean up


Device TMLM041xx should be renamed into TMLM 04103
with all the other TMLM 041XX as aliases.
With aliases you also specify the output voltage seperatly

Same goes for TMLM042xx, TMLM051xx , TMLM101xx and TMLM201xx

What do you think about that ?

**Comment by lorem-ipsum** [comment]
I don't really mind. It seems to be not really consistent throughout the library.

**Comment by Misca1234** [comment]
I guess people have different view on this, mine is from a documentation point of view.

You can see on the schematic directly what component it is and it makes the BOM generation more "automatic". Now, the BOM list generation could be better in kicad, but in the best of all worlds you would only need the schematic after 10 years when the PCB need a make over.

**Comment by lorem-ipsum** [comment]
Makes sense. Is it fine as is? I have changed the description from `xW` to `yV zzzmA` to make it more explicit. The power rating is still in the keywords.

**Comment by Misca1234** [comment]
Looks good, thx

**Pull request merged**
