### PR TITLE
CP2102N: Fix double-negated pins, add QFN20 symbol

### PR DESCRIPTION
**Pull request by 0xdec**
[Datasheet](https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf)

- Tweaked existing CP2102N symbols to be drop-in compatible with each other
- Fixed double-negated pins on existing symbols
- Stack power pins on existing symbols
- Match existing pin names with datasheet
- ~~Added QFN20 symbol (and associated footprint: kicad/kicad-footprints#1989)~~

CP2102N-Axx-xQFN20
CP2102N-Axx-xQFN24
CP2102N-Axx-xQFN28

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi,

I like that the symbols are made drop-in-compatible. Good choice.
But that also means that the changes do break existing designs. So we can't merge this now. i added the 6.0 milestone.

I did not do a full review yet since we can't merge it anyway.
- [x] Name & Wildcarding looks good
- [ ] ... todo more review

**Comment by 0xdec** [comment]
Changed footprint for `CP2102N-Axx-xQFN20` to `SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm`, which is already in [kicad-footprints](https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm.kicad_mod).

**Comment by cpresser** [comment]
We can merge this now since the v6 branch was opened. I will finish my review in the next few days.

**Comment by cpresser** [comment]
Allright, I did some more checking:
* [x] Pin-Names, Numbers and positions on all parts are good
* [x] Footprints
  * [x] `QFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm` The EP is slightly to big (recommended: 2.55mm vs 2.6mm). I think making a new footprint for 0.05mm difference in EP-size is not needed here. 2.6mm is good enough.
  * [x] `QFN-28-1EP_5x5mm_P0.5mm_EP3.35x3.35mm` is an exact match.
  * [x] `SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm' is an exact match
* [x] Names, Keywords, Description is good!

**Comment by cpresser** [comment]
I wanted to also bring the CP2104 in line with this PR. But the repo-lockdown bot got my own PR^^
But this can wait until we move to gitlab.

**Pull request merged**
