### PR TITLE
Added AP65111

### PR DESCRIPTION
**Pull request by DecadoPL**
I've been working on https://github.com/KiCad/kicad-symbols/pull/1897 . I'm learning Git and Kicad so I've deleted old repo and did it from the very begining. And now I have no idea how to pull it into the same topic, so I create new one. BTW even if i signed CLAassistant it is still pending. Hope it will work this time.

https://www.diodes.com/assets/Datasheets/AP65111A.pdf

image

Instead of naming it AP65111WU i named it AP65111AWU, this name exist in manufacturer database and shops database. Correct me if I'm wrong

### CODE REVIEW

**Comment by DecadoPL** [comment]
I signed CLA license multiple times and it is still shows that it has been not signed 

image

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Since you reviewed the original PR I'm assigning you.

**Comment by myfreescalewebpage** [comment]
Hi @DecadoPL thanks to continue this work. Some comments here:

- [ ] SW should be Power Output
- [ ] Just notice "KHZ" should be "KHz" in the description

Else, no other comment to do, great job !
Joel

**Comment by evanshultz** [comment]
Should SW be Power Output? It does not supply power directly to other ICs because there is a series element (inductor) between the SW pin and the actual converter output. For that reason, maybe Output or Passive is better? I recall this being discussed before but a quick search didn't turn it up. And it may not make any real difference anyway.

**Comment by myfreescalewebpage** [comment]
Well @evanshultz I agree the classical usage of this is to have an inductor on SW output, but that's only a typical application. In the real life, it's an output and it is able to drive power so... I don't remember of this discussion except for another device but it was a different converter topology.

**Comment by DecadoPL** [comment]
@myfreescalewebpage 
So what is the final decision? How should i modify it?

**Comment by evanshultz** [comment]
@DecadoPL 
It definitely should not be Power Input. Assuming the inductor is there it probably won't matter since you'll need the PWR_FLAG symbol after the inductor. And the library isn't consistent about this already. You can change it as requested above.

**Comment by myfreescalewebpage** [comment]
@DecadoPL let say you can keep Output only. That something will need to be more consistent in the lib, one day!

**Comment by DecadoPL** [comment]
@myfreescalewebpage Done!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
