### PR TITLE
Add SHTC1, SHTC3

### PR DESCRIPTION
**Pull request by DanSGiesbrecht**
## Add SHTC1/SHTC3 Humidity and Temperature Sensors

- SHTC1 [datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Humidity/Sensirion_Humidity_Sensors_SHTC1_Datasheet.pdf)
- SHTC3 [datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Humidity/Sensirion_Humidity_Sensors_SHTC3_Datasheet.pdf)
- Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1946

Travis error: will be resolved by Footprint PR merge.

---

symbol

---

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
- Pin names, types, position are all good. 
- Description + alias also checks out.

As soon as the FP is done I am ready to merge this.

**Comment by DanSGiesbrecht** [comment]
Close/reopen to force Travis check.

**Comment by DanSGiesbrecht** [comment]
@cpresser this is good-to-go! :)

**Comment by cpresser** [comment]
Thanks, merged!

> Close/reopen to force Travis check.

Slightly related comment:
Travis has a 'Restart Build' button. See https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit
Login with the github-account does work for that usecase.

**Pull request merged**
