### PR TITLE
LAN951x - USB To 2/3/4 USB ports and Ethernet Interface

### PR DESCRIPTION
**Pull request by jneiva08**
Added all LAN951x USB HUB and Ethernet NIC. Can find this IC on the raspberry pi 2.

lan9512 - http://ww1.microchip.com/downloads/en/DeviceDoc/00002304A.pdf
lan9513 - http://ww1.microchip.com/downloads/en/DeviceDoc/00002305A.pdf
lan9514 - http://ww1.microchip.com/downloads/en/DeviceDoc/00002306A.pdf

The symbol is divided in 2 parts. Part A is equal for the 3 (power supply, i/o, etc), the Part B have Ethernet port and the number of USB ports each hub have

Part A

lan9512_a

lan9512 Part B

lan9512_b

lan9513 Part B

lan9513_b

lan9514 Part B

lan9514_b

The PR for footprint is 

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Add the package to the description, that is, change 
Two USB 2.0 hub with an integrated 10/100 Ethernet controller (0°C to +70°C)
into
Two USB 2.0 hub with an integrated 10/100 Ethernet controller (0°C to +70°C), QFN-48

Pin nRESET should have a ~ in front of nRESET so you get a line above text.
Pin nTRST should have a ~ in front of nTRST so you get a line above text.

Pin nFDX_LED text should look like this '~nFDX_LED~/GPIO0'
Pin nLNKA_LED/GPIO1 text should look like this '~nLNKA_LED~/GPIO1'
Pin nSPD_LED/GPIO2 text should look like this '~nSPD_LED~/GPIO2'



LAN9512
Pin 1..5, 58 and 59 is missing
Pin 45 should be of the type output
pin 13, 34 and 40, make them NC
The 6 pins 6 .. 9, 17 and 18, NC is missing, you should add them like this
Type: NC
Invisible
Placed on the symbol outline
bild

LAN9513
Pin 1..5, 58 and 59 is missing
Pin 45 should be of the type output
pin 13, 34, 40 and 47, TEST[1..4], make them NC and invisible
The 3 pins 8, 9 and 18 and 18, NC
pin 6, 7 and 17 is missing

LAN9514
Pin 1..5, 58 and 59 is missing
Pin 45 should be of the type output
pin 13, 34 and 40, make them NC
pin 6 .. 9, 17 and 18 is missing

Could you look into this and I can remake the review?

**Comment by Misca1234** [comment]
Add the package to the description, that is, change 
Two USB 2.0 hub with an integrated 10/100 Ethernet controller (0°C to +70°C)
into
Two USB 2.0 hub with an integrated 10/100 Ethernet controller (0°C to +70°C), QFN-48

Pin nRESET should have a ~ in front of nRESET so you get a line above text.
Pin nTRST should have a ~ in front of nTRST so you get a line above text.

Pin nFDX_LED text should look like this '~nFDX_LED~/GPIO0'
Pin nLNKA_LED/GPIO1 text should look like this '~nLNKA_LED~/GPIO1'
Pin nSPD_LED/GPIO2 text should look like this '~nSPD_LED~/GPIO2'



LAN9512
Pin 45 should be of the type output

LAN9513
Pin 45 should be of the type output

LAN9514
Pin 45 should be of the type output

PS
Missed it was splittered in last comment
DS

**Comment by jneiva08** [comment]
Modified the default footprint to have same name in [#698](https://github.com/KiCad/kicad-footprints/pull/698)

**Comment by diegoherranz** [comment]
The keywords for the LAN9514 incorrectly say "Three" instead of "Four".
Anyway, I think the keywords should be changed to remove the comma and possibly removing the numbers (not sure they make much sense on the keywords"). E.g. "USB HUB Ethernet 10/100".

Thanks!

**Comment by diegoherranz** [comment]
Thanks, @jneiva08, for updating the keywords.
Honest question (for maintainers probably): regarding active low inputs, a tilde was added to get a a bar above. However, the name still contains a "n" prefix, e.g. ~nTRST. That means we are negating twice (the n and the bar) which I think it is incorrect.
What is the convention on this case in the KLC? I guess we could remove the "n"? Or leave the "n" and not having the bar? I think I prefer the former, but I'd like to hear from maintainers.
Thanks!

**Comment by Misca1234** [comment]
Without having any statistical data to back it up but removing the 'n' is most common

**Comment by diegoherranz** [comment]
Thanks, @Misca1234. I think that makes sense.

Could you then, @jneiva08, remove the "n" prefixes?

Thanks,
Diego

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
