### PR TITLE
Add INA3221 shunt and bus voltage monitor

### PR DESCRIPTION
**Pull request by nivekg**
I created a symbol for the INA3221 and it passed all KLC checks.

Datasheet: http://www.ti.com/lit/ds/symlink/ina3221.pdf

ina3221

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by nivekg** [comment]
Just realised that pins 11 and 12 are in the wrong order. Now fixed.

ina3221

**Comment by aewallin** [comment]
- 6 of the outputs are open-drain, som maybe they should be of type open-collector? see e.g. https://forum.kicad.info/t/electrical-type-of-schematic-symbol-pins/9439
- package (and footprint) has an exposed pad, so add pin 17 "EP" so that user can connect it to a heatsink-plane. (p45/46 of datasheet) - the datasheet is a bit thin on info about the EP-pin othwerwise...

**Comment by nivekg** [comment]
* Changed the electrical type of pins 8,9,10,13 to open collector. 
* I left pins 6(SCL), 7(SDA) as is. While they are open collector electrical type, it seems better to leave them input and bidirectional, since they are slave I2C.
* Changed pin 16 to input, I set it incorrectly before.
* Added pin 17 EP as passive.

ina3221

**Comment by myfreescalewebpage** [comment]
Hi @nivekg, thanks for contributing,

A few comments I have during my review:

- [ ] Description has a bug, I think you can remove the "-" just after "I2C"
- [ ] Package seems to be VQFN-16 with P0.65mm, isn't it ? Seems this package is not yet available in the library but in this case it should be added, you can submit a PR. @poeschlr maybe VQFN are scripted ? If so, can you indicate how, I'm not enough experimented on this subject...
- [ ] I would say VPU is a Power Input and should be placed in top of the symbol
- [ ] The positions of the pins seems globally very strange. I would : 1- put the IN+ inputs above the IN- inputs ; 2- Move I2C interface in the bottom right corner and open collector outputs in the top right corner, so it's easier to wire the PU resistors. A proposition is given below (KLC not checked on this proposition, to be verified):

capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@nivekg thanks for the fixes !

Yes, the exact full name of the footprint should be "Texas_S-PVQFN-N16_EP2.1x2.1mm" alternatively "Texas_S-PVQFN-N16_EP2.1x2.1mm_ThermalVias". I'm not experienced with the scripting and that's why I need a more experienced librarian to check it and I think @poeschlr has the answer.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@nivekg any news here about the footprint ? Thanks, Joel

**Comment by nivekg** [comment]
Not really. I got crazy busy and kind of neglected it.

**Comment by myfreescalewebpage** [comment]
@nivekg no worries, we keep your submission pending, my message was just to get news from you :)

**Comment by nivekg** [comment]
@myfreescalewebpage I finally created the Texas_S-PVQFN-N16_EP2.1x2.1mm and Texas_S-PVQFN-N16_EP2.1x2.1mm_ThermalVias footprints. I used the kicad-footprint-generator. I tried running the ./check_kicad_mod.py script to see if it conformed to the rules, but kept getting python errors. So. I'm not sure if its ok. Pull request: https://github.com/KiCad/kicad-footprints/pull/1641

**Comment by myfreescalewebpage** [comment]
@nivekg ok no worries, let start waiting what the reviewer will say on the footprint PR before finishing the symbol !

**Comment by evanshultz** [comment]
@nivekg 
Footprint is merged. If you can fix the branch conflicts this check should be good when CI runs again.

**Comment by myfreescalewebpage** [comment]
@nivekg ping :)

**Comment by nivekg** [comment]
Should be good now. Thanks for the ping.

**Comment by myfreescalewebpage** [comment]
Thanks.
The PR currently removes UCC39002D which is not correct.
Please fix, then this is ready to merge.
Joel

**Comment by nivekg** [comment]
maybe now?

**Comment by myfreescalewebpage** [comment]
There is still an issue with MAX8586 symbol.
Check at https://github.com/KiCad/kicad-symbols/pull/1343/files
Joel

**Comment by nivekg** [comment]
Cool, I removed the duplicate MAX8586 in Power_Management.dcm

**Comment by myfreescalewebpage** [comment]
@nivekg thanks, it's great now, merging !
Joel

**Pull request merged**
