### PR TITLE
Add FxB2227A NPN & PNP amplifiers

### PR DESCRIPTION
**Pull request by dsa-t**
Datasheet: http://www.onsemi.com/pub/Collateral/FMB2227A-D.PDF

FMB2227A:
Unit A:
image
Unit B:
image

FFB2227A is an alias of BC846BPN:
Unit A:
image
Unit B:
image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- The FFB package is SC-70-6, not SuperSOT-6. Please fix the description.
- For the FMB symbol, you copied an existing symbol then changed the pinout and package, right?
- Lastly, would you mind fixing the BC846BPN footprint filter by removing all but `SOT*363*`? If not, that's OK.

**Comment by dsa-t** [comment]
Done. Also added FMB3946. Yes, the symbol was copied.

**Comment by evanshultz** [comment]
OK. Looks good.

Just one thing. Please use http://www.onsemi.com/pub/Collateral/FMB3946-D.pdf for the FMB3946 link since Fairchild was acquired.

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
