### PR TITLE
Fix pins for BD139 and BD140

### PR DESCRIPTION
**Pull request by RavenFire**
Swap the Base and Emitter pin numbers to align with the datasheet.

Datasheet:
http://www.st.com/internet/com/TECHNICAL_RESOURCES/TECHNICAL_LITERATURE/DATASHEET/CD00001225.pdf

Original symbols:
bd139_old

New symbols:
bd139_new

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
This fix won't do.
These symbols each several aliases for which the old pinout was correct, see https://www.onsemi.com/pub/Collateral/BD238-D.pdf

I also suggest using ST's speaking DS URLs like https://www.st.com/resource/en/datasheet/bd140.pdf

**Comment by jkriege2** [comment]
Please cross-check against our footprint ... I have the feeling that in the DS they number 1-2-3 right to left, while the KiCAD footprint number 1-2-3 left to right!

**Comment by jkriege2** [comment]
see e.g. https://www.onsemi.com/pub/Collateral/BD139-D.PDF

**Comment by chschlue** [comment]
True, ST has it the wrong way round, missed that.
In that case the symbols are correct but the DS links should be updated.

**Comment by evanshultz** [comment]
@RavenFire 
Please see and check the above conversation. Would you instead transform this PR into a doc update and revert the pin number changes?

**Comment by chschlue** [comment]
@evanshultz 
The pin swap is fine but we probably shouldn't link to datasheets from the only manufacturer that numbers pins RTL to avoid confusion.

**Comment by chschlue** [comment]
Please use MF DS links if possible, i.e.
https://www.onsemi.com/pub/Collateral/BD135-D.PDF
https://www.onsemi.com/pub/Collateral/BD136-D.PDF

**Comment by chschlue** [comment]
@RavenFire reopen if you are still on this.

**Pull request closed without merging**
