### PR TITLE
Added ADC081C021CIMM 8-bit ADC from TI

### PR DESCRIPTION
**Pull request by awygle**
Added ADC081C021CIMM 8-bit ADC from TI. Only added the MSOP-8 variant.

Datasheet: http://www.ti.com/lit/ds/symlink/adc081c021.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by awygle** [comment]
Fixed the offset. VIN isn't a power pin, it's the analog input for the ADC.

**Comment by evanshultz** [comment]
Thanks!

It seems the '021 version only comes in VSSOP8. :)

Yes, that "error" is bogus in this case and can be ignored.

Changes requested:
- Set pin name offset to 20mil.
- I'd like to see VIN and ADR* on the left, with the I2C and ALERT pins on the right.
- SCL should be Input type.
- Can you slightly change you description to match the datasheet with `I2C-Compatible, 8-Bit Analog-to-Digital Converter with Alert Function`?

**Comment by awygle** [comment]
The above changes have been made.

**Comment by evanshultz** [comment]
@awygle 
Thanks!

It's easier to track changes if you make updates to an older commit rather than wipe everything out. I'm not sure how you're pushing changes to GH but there are ways which allow the online interface to show incremental changes.

- Add the package name to the end of the description with a comma separator.
- Can you post a new screenshot? This is helpful whenever any significant visual change is made.

**Comment by whitequark** [comment]
> Can you post a new screenshot? This is helpful whenever any significant visual change is made.

The screenshot is updated, no? It has these changes:
 * I'd like to see VIN and ADR* on the left, with the I2C and ALERT pins on the right.
 *SCL should be Input type.

**Comment by Ratfink** [comment]
@evanshultz I believe he's amending the one commit in his local branch and force-pushing to overwrite the remote branch.  I agree that's not generally a good practice, for numerous reasons (it becomes more important in less centralized projects, where other people might have based other branches on the commits that are being amended).  For us maintainers, being able to see a diff since the last review is wonderful.

**Comment by awygle** [comment]
> I believe he's amending the one commit in his local branch and force-pushing to overwrite the remote branch.

That's correct. I usually do this so that one commit remains one functional change, however if you're planning to squash the branch in or something I'll just push "bugfix" commits from now on.

**Comment by evanshultz** [comment]
@Ratfink 
Ah! Thank you.

@awygle 
For me, seeing a diff is very nice. I would appreciate if you can push bugfixes. Thanks!

I didn't look back to the first comment. I see the updated screenshot now. Thank you.

The symbol now looks rather tall. Can you smash it a bit vertically? Then it looks ready to merge.

**Comment by awygle** [comment]
Made the change requested:

image

**Comment by evanshultz** [comment]
Thanks for getting this symbol ready to merge!

**Pull request merged**
