### PR TITLE
add LTC1562 quad active RC-filter in SSOP-20

### PR DESCRIPTION
**Pull request by aewallin**
LTC1562 active filter (four op-amps) in SSOP-20 package
https://www.analog.com/media/en/technical-documentation/data-sheets/1562fa.pdf
LTC1562-2 alias: https://www.analog.com/media/en/technical-documentation/data-sheets/15622fa.pdf

LTC1562xxG

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi and thanks for you contribution.
A few thoughts - no full review yet.
- [ ] Shutdown should be on the left since it is an input pin
- [ ] I would like to see AGND to the right of GND, thats what we do for other chips.
- [ ] Can you please rebase this so its a trivial merge? The current branch has conflicts.


Do you have an example screenshot that shows the symbol in use? I am wondering if having all outputs on the left and inputs on the right works for this symbol. Currently it looks similar to the datasheet which is not bad per se, but does not conform to KLC.

**Comment by aewallin** [comment]
thanks for the comments.

- AGND to bottom right
- SHDN to lower left
- should now merge
- I would prefer the datasheet layout as most users will use one of the example circuits presented in the datasheet (for e.g. low-pass, band-pass, high-pass application)

**Comment by chschlue** [comment]
The alternative is a multi-unit symbol, one unit per filter section and a fifth for power and SHDN.

**Comment by aewallin** [comment]
> 
> 
> The alternative is a multi-unit symbol, one unit per filter section and a fifth for power and SHDN.

Are you suggesting that the "DeMorgan"-mechanism can/should be used here?

For practical reasons I think following the datasheet makes sense. I agree that if you are teaching active filters in a course or a textbook you would draw explicitly op-amps.

**Comment by chschlue** [comment]
No, I'm suggesting the "Number of Units: 5" and "All units are not interchangeable" mechanisms can be used ;)
Example: First part in the lib (alphabetically), the non-IEEE 4001.

**Comment by aewallin** [comment]
@cpresser ping! anything further I can do to help this get merged? many months now since the last comment. thanks.

**Comment by cpresser** [comment]
> @cpresser ping! anything further I can do to help this get merged? many months now since the last comment. thanks.

Basically you can do nothing but join the reviewers team :) But asking after that much time is okay.

I did some more checks:
- [x] I think the current layout is plausible, at least from my experience I would rather copy stuff from the datasheet. So having individual symbols is not a real advantage.
- [ ] Keywords are space separated, please remove the `,`
- [ ] Footprint-filter should also contain the pitch (`SSOP*20*5.3x7.2mm*P0.65mm*`)
- [x] Pin-numbers, names and electrical type are good.

**Comment by cpresser** [comment]
Thanks!

**Pull request merged**
