### PR TITLE
Add HMC431.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://www.analog.com/media/en/technical-documentation/data-sheets/hmc431.pdf

with no connect pins:
image

without (only for visual clarity):
image

Footprint pr: https://github.com/KiCad/kicad-footprints/pull/1283

I wasn't able to fit all NC pins on the border without making the symbol larger so placed some on the interior. It's ugly in the editor, but I think it's better than making the symbol unnecessarily large. Is it ok to place the NC pins on the inside instead of on the border for a few of them?

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh 

No comment to do on this symbol. Just need to wait the footprint before we can merge.

Joel

**Comment by aewallin** [comment]
- I would name pin25 "EP"
- most oscillators have a square or sine-wave graphic in the box, to show it's and oscillator.. a matter of style if it's wanted here or not I guess..

**Comment by matthuszagh** [comment]
The datasheet requires connecting the EP to ground. Do you want me to expose that pin? (Same issue as [this comment](https://github.com/KiCad/kicad-symbols/pull/1405#issuecomment-453251070)).

I'll add the graphic, I think you're right that would look nicer

**Comment by matthuszagh** [comment]
image

Added the graphic. Let me know what you want to do with EP.

**Comment by myfreescalewebpage** [comment]
Ok for the wave, but pin 25 need to be stacked with GND according to the datasheet ("ALL GROUND LEADS AND GROUND PADDLE MUST BE SOLDERED TO PCB RF GROUND"), so keeping the expose pad stacked to GND.

**Comment by myfreescalewebpage** [comment]
@matthuszagh footprint accepted for this device, can you fix branch conflict here so we will be able to merge the PR ?

Thanks

**Comment by matthuszagh** [comment]
Conflicts fixed.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
