### PR TITLE
Add Microchip MCP6V67 as alias of LM2904

### PR DESCRIPTION
**Pull request by yankee14**
Add Microchip MCP6V67 opamp as alias of LM2904

* "Zero Drift"
* Low input offset voltage

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/MCP6V66-Family-Data-Sheet-DS20006266A.pdf

Screencaps:
LM2904_UnitA

LM2904_UnitB

LM2904_UnitC

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by yankee14** [comment]
There is also a TDFN version of this part (with larger quantities available at Digi-Key), but I'm not sure how to handle that.

TDFN: MCP6V67T-E/MNY
MSOP-8: MCP6V67-E/MS

**Comment by myfreescalewebpage** [comment]
Hello @yankee14 , thanks for contributing,

The policy is now generally to create one symbol for each package version. For MCP6V67 you should do it.

Joel

**Comment by myfreescalewebpage** [comment]
Hello @yankee14 

Why MCP6V67EMS is not an alias of the same device too ?

Joel

**Comment by yankee14** [comment]
@myfreescalewebpage I think EMS (the MSOP) is the one I did make an alias? I did not do the other one (the TDFN) because the footprint does not seem to exist in the library yet.

**Comment by myfreescalewebpage** [comment]
It is in the git diff https://github.com/KiCad/kicad-symbols/pull/2778/files

**Comment by yankee14** [comment]
@myfreescalewebpage yeah, that's definitely a bug with KiCad. It's happened to me several times, but I couldn't figure out how to recreate it. I didn't do anything in KiCad that should cause it to create a unique symbol out of the alias I added to LM2904.

The unique symbol is removed and only the alias to LM2904 is left, MCP6V67EMS.

**Comment by myfreescalewebpage** [comment]
Yes I think I have already seen this 'behavior' of KiCad. I personally always verify the git diff just to ensure that's the wanted modification.

**Comment by yankee14** [comment]
@myfreescalewebpage I found an issue with this PR during layout. The MSOP package for MCP6V67EMS exposed pad (would be pin 9) does not have a pin representation in the symbol, thus cannot be connected to a net.

**Pull request merged**
