### PR TITLE
Add LT4295 and LT4320/1

### PR DESCRIPTION
**Pull request by evanshultz**
Some parts used in LTPoE++.
Footprints will be submitted pending the merge of https://github.com/pointhi/kicad-footprint-generator/pull/422.

LT4320
https://www.analog.com/media/en/technical-documentation/data-sheets/4320fb.pdf
image

LT4321
https://www.analog.com/media/en/technical-documentation/data-sheets/4321f.pdf
image

LT4295
https://www.analog.com/media/en/technical-documentation/data-sheets/LT4295.pdf
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz 

LT4231xUF
- [ ] Footprint filter should be `QFN*1EP*4x4mm*P0.65mm*`
- [ ] The footprint is missing

LT4295
- [ ] Name should be "LT4295xUFD"
- [ ] Should use capital letters for VCC and VIN

Joel

**Comment by evanshultz** [comment]
I'm not sure why Travis is complaining as the footprint is at https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.15x2.15mm.kicad_mod. Maybe you can see a typo that I'm missing?

Other items are fixed. Thanks for looking!

**Comment by myfreescalewebpage** [comment]
Yes sorry, my previous comment was not correct, just fixed it. I also notice the footprint filter is to be fixed for LT4230xDD device. Do you have a PR reference for the DFN package missing ?

**Comment by evanshultz** [comment]
I corrected the FP filter. Thank you.

I was waiting for a script PR to be merged but had forgotten to make the footprint since it was merged. I have submitted https://github.com/KiCad/kicad-footprints/pull/2226 to add the missing footprint to the library.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment here, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
The missing footprint has been merged.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
