### PR TITLE
TE Miniature PCB Relay PCH

### PR DESCRIPTION
**Pull request by daviid5**
added TE Miniature PCB Relay PCH

http://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FPCH_series_relay_data_sheet_E%7F1215%7Fpdf%7FEnglish%7FENG_DS_PCH_series_relay_data_sheet_E_1215.pdf

te_pch_a

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @daviid5 , thanks for contributing,

A few comments I have during my review:

- [ ] I think it will be better to call it "TE_PCH-A" for consistency with other symbols
- [ ] You are violating KLC S3.6, can be easily fixed
- [ ] You are violating KLC S5.2, footprint filter should be `Relay*SPST*TE*PCH*A*`

I have seen footprint is still pending (https://github.com/KiCad/kicad-footprints/pull/884) so it's okay for the last travis error.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@daviid5 up ?

**Comment by myfreescalewebpage** [comment]
@daviid5 thanks, I see you have pushed some commits, but it seems you have a merging issue, your PR is currently removing two symbols... Thanks.

**Comment by daviid5** [comment]
@myfreescalewebpage Yes I know, but at the moment I don't really know how to fix it.
I messed up by working in my master-branch ...
Do you have an Idea for fixing this in an easy way?

**Comment by myfreescalewebpage** [comment]
If you are working with Microsoft Windows I recommend you GitHub for Windows, that's trivial with it.

Else, you will be interested by https://github.com/KiCad/kicad-symbols/pull/145#issuecomment-356436694

**Pull request closed without merging**
