### PR TITLE
[DEVICES-ADDITION] : Add Q_DUAL_ MOSFETS

### PR DESCRIPTION
**Pull request by suzizecat**
Add DUAL N/PMOS in 6-pin package

Hello !  

I wish to add some generic dual-mosfet components corresponding to [BSL306N](https://www.infineon.com/dgdl/Infineon-BSL306N-DS-v02_04-en.pdf?fileId=db3a30431add1d95011afc80323d04f0) (NMOS) and [BSL308PE](https://www.infineon.com/dgdl/Infineon-BSL308PE-DS-v02_03-en.pdf?fileId=db3a30431d8a6b3c011d8ff3592c03d0) (PMOS) based on the dual NPN/PNP symbols. 

I added the TSOP* footprint filter since it's the one I need to use, but don't hesitate to tell me if I may add some other filters.

image

image

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi @suzizecat!
Thanks! A few things:
- Please add more FPfilters. It seems like `SC?70*`, `SC?88*`, `SOT?363*` would be good.
- Please fix the text size. You can see this is the CI checks above by clicking on the Details link.

**Comment by evanshultz** [comment]
Oh, and please put the ref des above the symbol name. The PMOS is flipped.

**Comment by suzizecat** [comment]
Thanks for the review !
That should be fixed

**Comment by evanshultz** [comment]
Could you please make the pin names invisible to align with our other MOS symbols?
image

**Comment by suzizecat** [comment]
Done.

**Comment by evanshultz** [comment]
Thank you!!

**Pull request merged**
