### PR TITLE
Add AD8561ARZ comparator

### PR DESCRIPTION
**Pull request by ferdymercury**
https://www.analog.com/media/en/technical-documentation/data-sheets/ad8561.pdf

Use with Package_DIP:DIP-8_W7.62mm_LongPads

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the official footprint library
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ferdymercury** [comment]
image

**Comment by evanshultz** [comment]
I see you've added screenshots. Thank you.

Rather than repeat myself many times, please see my comments at your other PR and do them for all of your PRs, such as using background fill for symbols. Also, you need to do some work on the footprint section of the symbol. And for opamps and comparators use a triangle symbol as is standard in our library.

**Comment by ferdymercury** [comment]
I know, thanks. I will work on this next month.

**Comment by ferdymercury** [comment]
I noticed that this symbol is already available as TL3116. So no more work needed, just adding as alias.

**Comment by evanshultz** [comment]
OK. This basically works (I'll fix the packages later as I mentioned).

But there are two small things:
1. Remove the comma from the keywords.
1. Add the packages to the end of the description (`DIP-8/SOIC-8/TSSOP-8`).

**Comment by ferdymercury** [comment]
Done, thanks.

**Comment by evanshultz** [comment]
Looks good. Thank you!

**Pull request merged**
