### PR TITLE
Create VTX-214-010 family

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Fixes https://github.com/KiCad/kicad-symbols/issues/153

Create VTX-214-010 family following issue at https://github.com/KiCad/kicad-symbols/issues/153.
The symbol is based on VTX-214-015 already in the library

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing

http://www.vigortronix.com/10WattACDCPCBPowerModule.aspx

- [x] An example screenshot image is very helpful

Capture

- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

GND pin at the right, warning from travis check, followed convention for this kind of symbol.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Datasheet page 2 shows pin names of `L`, `N`, DC+` and `DC-`. Should we adhere to that? It seems more clear than either set of pin names shown on page 3. This goes for the existing VTX symbol too.
1. The -107 version is 7.5V output.
1. Can the `xxx*` be removed from the FP filter? Possibly swap it to `THT*`?

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks for the answer.

1- Yes and page 3 shows other names too. I have made some screenshot below.



So I just decided to keep the same name than VTX-214-015 family. Let me known what is the best, the datasheet has no clear table of the pins names...
2- fixed.
3- Keep consistency of the format with VTX-214-015 family too.

Joel

**Comment by evanshultz** [comment]
1. The table on page 2 was the only place that was clear about the two AC pins, so that's one reason why I favored it. Both VTX symbols could use this naming?
3. Right now, this part of the FP filter does nothing. If there was an SMD later then possibly adding "THT" could help. But likely there will only be the THT version so the footprint and the symbol don't need to capture that. We don't specify SMD or THT for most footprints if there's only one version.

Neither are blocking to merge this, but thinking that having v5.1 released gives us more latitude to change I looked at it with fresh eyes. :)

**Comment by myfreescalewebpage** [comment]
1- Yes they can, I will fix both symbols right now
2- My intention was to help the issue #153 which is only about the missing symbol but if it is more consistent we can also review the footprints names, let me know

**Comment by myfreescalewebpage** [comment]
Changing the output names also solve one travis warning :)

**Comment by myfreescalewebpage** [comment]
@evanshultz any new comments ? Thanks.

**Comment by evanshultz** [comment]
Nope. Looks OK.

**Comment by antoniovazquezblanco** [comment]
Thank you both!

**Pull request merged**
