### PR TITLE
Add RTL8211EG-VB-CG

### PR DESCRIPTION
**Pull request by joshtyler**
Add RTL8211EG-VB-CG Ethernet Phy

Datasheet is [here](https://datasheet.lcsc.com/szlcsc/Realtek-Semicon-RTL8211EG-VB-CG_C69264.pdf).

Matching footprint PR is [here](https://github.com/KiCad/kicad-footprints/pull/1858)

I haven't grouped the power/ground pins, because one DVDD33 pin is used differently to the other pins (one DVDD33 pin always needs to be 3.3V, the others can be 2.5V if 2.5V is desired as an I/O voltage. See Datasheet Section 6.10 (p.12).

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by joshtyler** [comment]
Footprint PR has now been merged

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @joshtyler , thanks for contributing,

A few comments I have during my review:

- [ ] The datasheet is not from the manufacturer website. Do you have another link?
- [ ] The description should ends with the package name: `10/100/1000Mbps Ethernet Transceiver with RGMII/GMII/MII/RMII Interface, QFN-64`
- [ ] The footprint filter should be `QFN*1EP*9x9mm*P0.5mm*`
- [ ] MDIO should be Bidirectionnal
- [ ] RSET should be Passive
- [ ] LEDx pins should be Bidirectionnal
- [ ] ANx pins should be Bidirectionnal
- [ ] COL/MODE pin should be Bidirectionnal
- [ ] PHY_ADx pins should be Bidirectionnal
- [ ] SELRGV pins should be Bidirectionnal
- [ ] GND pins and EP should all be stacked

Cheers,
Joel

**Comment by joshtyler** [comment]
Hi @myfreescalewebpage thanks for the review.

I've addressed all of the review comments. Unfortunately I don't have another source for the datasheet.  Realtek don't list it on their website for public download. 

When changing pin directions I also set TXDLY and RXDLY to Bidirectional following the same logic.

The CI build wasn't happy with the EP_GND pin in the GND stack, so I had to rename it to GND.

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes.
"The CI build wasn't happy with the EP_GND pin in the GND stack, so I had to rename it to GND." => This is normal.

However, the GND pin stacking rule is still not respected. The rule is : First GND pin Power Input, visible, other GND pins Passive, Invisible (see travis error output).

Something I haven't notice before: NC pin should be on the border outline of the symbol:

Capture

**Comment by joshtyler** [comment]
Oops, sorry about forgetting to change the type of those stacked pins. All fixed in that latest commit.

Regarding the NC pins, [KLC S4.6](https://www.kicad-pcb.org/libraries/klc/S4.6/) does permit NC pins lying within the symbol body. I placed them there deliberately to remove any possibility of inadvertent connection (e.g. by having a wire touching a symbol outline in that place). Is there a consensus that having the pins on the symbol outline is the preferred style?

**Comment by myfreescalewebpage** [comment]
Thanks for the fix.
There is no real rule for the NC pin position. Usually I ask to put them on the border outline of the symbol to not have too much crazy results...
Let me known if you want to keep like that or if you want to move them.
Joel

**Comment by joshtyler** [comment]
Cool, thanks :+1: I've moved the NC pins:

image

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment, merging.

**Pull request merged**
