### PR TITLE
Add MAX17261 symbol

### PR DESCRIPTION
**Pull request by drid**
Add MAX17261 symbol

* Versions for TDFN and WLP packages

Datasheet: https://datasheets.maximintegrated.com/en/ds/MAX17261.pdf

image

Footprints:
https://github.com/KiCad/kicad-footprints/pull/1685
https://github.com/KiCad/kicad-footprints/pull/1686
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @drid , thanks for contributing,

A few comments I have during my review:

General:
- [ ] We discard the packaging options and the ROHS, temperature etc. The devices you submitted should only be "MAX17261xxTD" and "MAX17261xxWL", no alias

TDFN version:
- [ ] Description should be "5.1μA Multi-Cell Fuel Gauge with ModelGauge m5 EZ, TDFN-14"
- [ ] Footprint should be `Package_DFN_QFN:TDFN-14_1EP_3x3mm_P0.4mm_EP2.35x1.78mm`
- [ ] Footprint filter should be `TDFN*1EP*3x3mm*P0.4mm*` 
- [ ] NC pins should be on the border outline of the symbol
- [ ] Style of ALRT and SCL should be Line
- [ ] You should group ALRT with SDA/SCL
- [ ] CELLX is input
- [ ] TH is Passive
- [ ] EP pin 9 should be added on stacked on GND
- [ ] The size of the symbol should be reduce a lot, too much place lost
- [ ] REG can be moved on the right bottom to easily wire the capacitor

WLP version:
- [ ] Description should be `5.1μA Multi-Cell Fuel Gauge with ModelGauge m5 EZ, WLP-9`
- [ ] I disagree with package size
- [ ] Style of ALRT and SCL should be Line
- [ ] You should group ALRT with SDA/SCL
- [ ] CELLX is input
- [ ] TH is Passive
- [ ] The size of the symbol should be reduce a lot, too much place lost
- [ ] REG can be moved on the right bottom to easily wire the capacitor

Cheers,
Joel

**Comment by drid** [comment]
Made most changes, reduced symbol size but kept it same between the two version so it can be replaced easily in schematic.
Working on WLP-9 footprint

**Comment by myfreescalewebpage** [comment]
Great job done here !

- [ ] The WLP footprint filter should be `WLP*1.468x1.468mm*Layout3x3*P0.4mm*`

Else no more comment, good idea to have the possibility to cross the two symbol, and the size is nice.

Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@drid seems the footprint should be updated here following the merge of the footprint PR.

**Comment by myfreescalewebpage** [comment]
Thanks.

For the WL version:
- [ ] Footprint filter should be `Maxim*WLP*1.595x1.415*Layout3x3*P0.4mm*` (never put the pin number in fp filter

Joel

**Comment by myfreescalewebpage** [comment]
@drid ping, we are close to merge this PR

**Comment by myfreescalewebpage** [comment]
Thanks, great effort done here! No more comment.

**Pull request merged**
