### PR TITLE
Sn74 lv1 t34

### PR DESCRIPTION
**Pull request by fragraider**
Added both package version of Texas Instruments SN74LV1T34 Single buffer and level translator.

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
   ->https://www.ti.com/lit/ds/symlink/sn74lv1t34.pdf
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
   -> See below.
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
  -> Fitting footprints where available.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
  -> Fitting footprints where available.
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.
  -> No rule violation intended.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

billede
billede

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @fragraider , thanks for contributing,

A few comments I have during my review:

SN74LV1T34DBV
- [ ] Fp filter: `SOT?23*`
- [ ] Capital letters for VCC

SN74LV1T34DCK
- [ ] Package in the description: "SOT-353"
- [ ] Fp filter: `SOT?353*`
- [ ] Capital letters for VCC

Cheers,
Joel

**Comment by fragraider** [comment]
Hello Joel

Thanks for the review! Should all be fixed now.

**Comment by myfreescalewebpage** [comment]
Perfect. Merging.

**Comment by fragraider** [comment]
Thanks!

**Pull request merged**
