### PR TITLE
add ISO1050 in SO-8

### PR DESCRIPTION
**Pull request by balcer**
Hi, this is my first kicad-symbol pr. Hope it will match all KLC requirements.  

http://www.ti.com/lit/ds/symlink/iso1050.pdf
 
symbol

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @balcer, thanks for contributing,

A few comments I have during my review:

- [ ] There si two package versions of the ISO1050, please rename yours to ISO1050DUB (8 pins version), according to the datasheet page 5
- [ ] Isolation barrier is now no more indicated twice, remove one dash line and center the other one on the symbol. For example you can look at ISO1540 in the Isolator library.
- [ ] GND1 / GND2 should be at the bottom of the symbol. For example you can look at ISO1540 in the Isolator library.
- [ ] Reference should be in the top left corner, name in the top right corner.
- [ ] Type of pin 2 RXD should be Output
- [ ] Type of pin 3 TXD should be Input
- [ ] I don't agree with the footprint selected, it is not SOIC, it is SOP, but not sure it is available in Kicad (?), in this case need to create it. Also the footprint filter violates KLC S5.2.

Cheers,
Joel

**Comment by balcer** [comment]
> There si two package versions of the ISO1050, please rename yours to ISO1050DUB (8 pins version), according to the datasheet page 

You are right, corrected 

> Isolation barrier is now no more indicated twice, remove one dash line and center the other one on the symbol. For example you can look at ISO1540 in the Isolator library.

Ok, that's reasonable but I can't find this rule in KLC, maybe it should added to KLC rules?

>GND1 / GND2 should be at the bottom of the symbol. For example you can look at ISO1540 in the Isolator library.

Done

>Reference should be in the top left corner, name in the top right corner.

Done

>Type of pin 2 RXD should be Output

Done

>Type of pin 3 TXD should be Input

 Done, my mistake

>I don't agree with the footprint selected, it is not SOIC, it is SOP, but not sure it is available in Kicad (?), in this case need to create it. Also the footprint filter violates KLC S5.2.

Footprint: https://github.com/KiCad/kicad-footprints/pull/1273

**Comment by poeschlr** [comment]
We can not put every detail into the KLC. So there is the rule make your symbol fit similar symbols.

**Comment by balcer** [comment]
I was trying to make ISO1050 symbol exactly like ISO1540 but I do not understand why ISO1540 is not centered? Should I move my symbol up? Is ISO1540 correct?

**Comment by poeschlr** [comment]
Being centered has a lower priority when compared to aligning to 100 mil grid. Meaning if your symbol has an even number of pins on one side then it might not be possible to get it exactly centered.

Travis will sadly complain about that. (There is no easy way to get travis fixed in this regard.)

**Comment by myfreescalewebpage** [comment]
Hi @balcer 

Thanks for the modifications. A few new comments:

- [ ] The footprint format is not correct (travis output), should be with ":" `Package_SO.pretty:SOP-8_6.62x9.15mm_P2.54mm`
- [ ] The associated footprint filter is `SOP*6.62x9.15mm*P2.54mm*`
- [ ] Description should ends with the package name `, SOP-8`

Otherwise, looks good. Need to wait the footprint review too.

Cheers,
Joel

**Comment by balcer** [comment]
Hi, myfreescalewebpage,

thanks for review, a want to be sure:
SOP*6.62x9.15mm*P2.54mm* - will this filter suggest other SOP packages. For example 10 pin?

Best regards

**Comment by balcer** [comment]
Ok, I made corrections. I hope my next PR will be less difficult. Thank all for help. Last question - 3D model. Texas provides a 3D model but I now that this is against the license. Should I prepare my own 3d model and brake M1.2 KLC rule?

**Comment by myfreescalewebpage** [comment]
Just a remaining error on the footprint. Sorry I have edited my above comment, ".pretty" should not be in the field.

> Last question - 3D model. Texas provides a 3D model but I now that this is against the license. Should I prepare my own 3d model and brake M1.2 KLC rule?

M1.1 says: "Users should only submit models they have created themselves, either manually designed or via parametric scripting tools. Contributing model data designed by a third party complicates licensing issues and should be avoided."

You will have to draw it yourself if you want to submit the model. Maybe it is possible to start from an existing one in the KiCad 3D source repo: https://github.com/KiCad/kicad-packages3D-source

Joel

**Comment by balcer** [comment]
Fixed

**Comment by myfreescalewebpage** [comment]
Looks great for me, just need to wait for the footprint https://github.com/KiCad/kicad-footprints/pull/1273

Joel

PS : in the future please do not force pus, only push to your branch. This clearly simplify the reviews when you are making fixes.

**Comment by myfreescalewebpage** [comment]
Footprint merged, now merging the symbol.

**Pull request merged**
