### PR TITLE
added TPS54061

### PR DESCRIPTION
**Pull request by rs-development**
http://www.ti.com/lit/ds/symlink/tps54061.pdf

image

Reused Symbols from TPS54360, only shifted GND Pins to fit VSENSE instead of FB.

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @rs-development , thanks for contributing,

A few comments I have during my review:

- [ ] The name of the device should be "TPS54061DRB"
- [ ] The footprint filter should be `Texas*S*PVSON*`
- [ ] The pin offset should be 20mil
- [ ] Pin 9 should be stacked with GND
- [ ] BOOT should be Passive
- [ ] Pin 4 should be Passive
- [ ] PH should be Power Output
- [ ] I'm not sure the position of the pin is the best according to the schematic reference in the datasheet page 16, I propose the following:

Capture

Cheers,
Joel

**Comment by rs-development** [comment]
@myfreescalewebpage done as you have said.

image

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes. One travis error remaining about the stacking rule: pin 9 name must be "GND".

**Comment by myfreescalewebpage** [comment]
Pin 9 Passive to respect stacking rule :)

**Comment by myfreescalewebpage** [comment]
Thanks. Merging.

**Pull request merged**
