### PR TITLE
Makeover of Sensor_Magnetic and add AH1806

### PR DESCRIPTION
**Pull request by jneiva08**
Hi,

This PR will be the biggestes done by me up to now.
Tried put Sensor_Magnetic to respect KLC, the changes are:
* Pin name position offset to 20mil,
* Centered  symbols to be symmetrical,
* Moved the NC ot the edge,
* Updated the datasheet link was broken,
* Updated some footprint filters,
* Added A110x  P/N for SIP-3 package and updated description,
* Added AH1806.

Need you help to try understand why A1101ELHL, A1101EUA, A1301KLH and A1301KUA-T still getting error on S4.4, It looks how to should be.
On checklib-py -v gives this message:
"    Pin electrical type should match pin function
     Pin types should match pin function"

Need you option about should proceed the footprint for AH1806. For SOT23W need be other pin order and SOT553 need to have other measures.

Now the symbols looks:

a110x_sot

a110x_sip

a130x_sip

a130x_sot

ah1806_sot553

ah1806_sot_sip

as5045a

as5045b

as5048b

as5055a

mmc5883ma

sm35xlt

tlv493d

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Updated TLV493D symbol:

symbol

* Changed missing datasheet link of forgotten alias,
* The A1101*, A1301* still gives error on S4.4, Should change from Vout (is what is on datasheet) to Output?
* What is your opinion how  should proceed the footprint for AH1806. For SOT23W need be other pin order and SOT553 need to have other measures. Should create with name of Diodes on the beginning?

**Comment by Misca1234** [comment]
Allow me to come back to you tomorrow evening

**Comment by antoniovazquezblanco** [comment]
@jneiva08 could you please resolve the conflict?

@Misca1234 will you assign this to yourself as you already started the review?

Thank you both!

**Comment by Misca1234** [comment]
@antoniovazquezblanco Mja, I am not that big believer in assigning pushes to specific persons

@jneiva08 
> What is your opinion how should proceed the footprint for AH1806. For SOT23W need be other pin
> order and SOT553 need to have other measures. Should create with name of Diodes on the beginning?

If they have made a special version and named it SOT553, we need a new foot print with prefix Diodes, 
will you make a new one or should I make it?

**Comment by jneiva08** [comment]
Sorry for asking, it's my first time to have conflicts.
Can explain how should proceed? I don't mind making the change.

Thanks

**Comment by Misca1234** [comment]
What have have happen is that your push and another push (that have been merged) is "trying to" change on the same places in a file.
This means that git does not know which change it should choose, yours or the other.

You solve it in two ways
1. Click on the "Resolve conflicts" button above and then you are showed where the conflict is and you can solve it on-line in the browser. This also mean you can no longer push from your local git branch unless you make same changes locally

2.
On your local computer, 
Download and update the master.
Update your branch (which this push comes from), 
Git wont be able to solve the merge from master (you get the same conflict as in this push)
Solve the conflict and then re push your branch

3. 
Close and delete this push
On your local computer, 
Download and update the master.
Create a new branch
Add the changes you have done in this push
Push the new branch

Click on the "Resolve conflict" button and see how large the conflict is and then you can decide what method you want.

PS
A tip
It is kinda risky to make large changes on the same time, because the reviewers thinks, "gosh that was big, I will check it next Saturday, when I have time" so the push will start to slip in time and the chance is big that conflicts occur because other much smaller pushes is merged to the same .dcm or .lib
My recommendation is to make several smaller pushes instead of one big
DS

**Comment by Misca1234** [comment]
Do you want me to make the Diode_SOT-553

**Comment by jneiva08** [comment]
Added [Diodes_SOT-553](https://github.com/KiCad/kicad-footprints/pull/997)

**Comment by jneiva08** [comment]
@Misca1234, soon will close this PR, then break in few new PR's to be ease to merge :)

**Pull request closed without merging**
