### PR TITLE
rfcom

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR pulls across all symbols from the old `rfcom` library

### CODE REVIEW

**Comment by pointhi** [comment]
there are some bluetooth modules in RF as well as Lora/Sigfox and GSM which could be moved

**Comment by SchrodingersGat** [comment]
@pointhi can you point out which ones, exactly?

**Comment by pointhi** [comment]
For bluetooth for example ```SPBTLE-RF```

**Comment by SchrodingersGat** [comment]
Ok, these have now been moved. Thanks for spotting

**Comment by SchrodingersGat** [comment]
I have opened an issue here - https://github.com/KiCad/kicad-symbols/issues/149

**Pull request merged**
