### PR TITLE
Added TI TCA980x I2C buffer / translators

### PR DESCRIPTION
**Pull request by luca-della-vedova**
Hi!

I added the TCA980x family for Texas Instruments I2C level translators, it has the same pins (although in different positions) of the existing TCA9406DC so I took that symbol, changed the pinout and updated the description, as well as adding aliases for parts with different current rating.

Screenshot here
image

And datasheet here
https://www.ti.com/lit/ds/scps264a/scps264a.pdf

Overall a quite simple addition, the symbol could be made a bit smaller by removing the underscore but it would be less readable so I didn't do it.

Cheers!
/Luca
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @luca-della-vedova , thanks for contributing,

A few comments I have during my review:

- [ ] Names of pins SCL* and SDA* are without the underscore in the datasheet
- [ ] I think it's better to have EN below SCLA/SDAA group, as shown on the application example first page of the datasheet

Else, sounds good.

Cheers,
Joel

**Comment by luca-della-vedova** [comment]
Hi Joel,

Done, here is the latest version:
image

Cheers!
/Luca

**Comment by myfreescalewebpage** [comment]
Hi @luca-della-vedova 

- [ ] The left pins are on the symbol outline border ! To be fixed.

Also just realized a missing comment:
- [ ] The descriptions should end with the package name, please add `, VSSOP-8`at the end ofeach description

Thanks,
Joel

**Comment by luca-della-vedova** [comment]
> Hi @luca-della-vedova
> 
> * [ ]  The left pins are on the symbol outline border ! To be fixed.
> 

Wow I have no idea how I didn't notice that, fixed.

> Also just realized a missing comment:
> 
> * [ ]  The descriptions should end with the package name, please add `, VSSOP-8`at the end ofeach description
> 

Done
> Thanks,
> Joel

/Luca

**Comment by myfreescalewebpage** [comment]
Thanks ! No more comment, merging.

**Pull request merged**
