### PR TITLE
Change D & LED line thickness to 10mil

### PR DESCRIPTION
**Pull request by evanshultz**
A lot of stuff changed but it's mostly innocuous line thickness changes. If you want a specific symbol comparison let me know.

Here is a list of changes that aren't just line thicknesses:
- Simplified DIAC symbols to two polylines which results in the same visual representation
- D_Schottky_Small symbol adjustment to 'tips' by 5mil to avoid line overlapping
- Unfill triangles on ASMT-YTC2-0AA02
- Add missing junction dots on LED_Cree_XHP50_12V and LED_Cree_XHP70_12V
- Unfill single LED symbols and add 0mil thickness center line
- Change HDSP/HLCP LED symbols to standard one (50mil grid corners of triangle)
- Remove leading asterisk from HLCP-J100_2's FP filter

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Unfortunately that's a lot of stuff to review at once. I think I will give it a closer look soon (perhaps do some scripting to filter out all the thickness changes).
I would prefer this to be in separate commits, at least for the non-thickness changes, but I guess that's to late now.

**Comment by evanshultz** [comment]
Fair point. Sorry to glom it all together. I started on the line thicknesses but then got too excited and forgot to split things up as I found other issues.

**Comment by cpresser** [comment]
So I tried to partially script this, removing the changes that are not just line-thickness changes. Resulting in 170 diff lines.
Those are the symbols that have 'other' changes (count = 49):
```
5KPxxCA
BAV70W
BAV99S
C3D16060D
CLS6B-FKW
DB3
D_Bridge_-AA+
DIAC_ALT
D_Photo
D_Photo_ALT
D_Radiation
D_Radiation_ALT
D_Schottky_ALT
D_Schottky_x2_ACom_KKA
D_Schottky_x2_KCom_KAA
D_Schottky_x2_Serial_KCA
D_Shockley
D_TVS
D_TVS_ALT
D_TVS_x2_AAC
D_TVS_x2_ACA
D_TVS_x2_CAA
D_x2_ACom_KKA
D_Zener_Small
D_Zener_Small_ALT
D_Zener_x2_ACom_AKK
D_Zener_x2_ACom_KKA
D_Zener_x2_KCom_AKA
D_Zener_x2_KCom_KAA
HDSP-4830
HLCP-J100
HLCP-J100_2
LD271
LED_ABRG
LED_ALT
LED_Cree_XHP50_12V
LED_Cree_XHP50_6V
LED_Cree_XHP70_12V
LED_Dual_2pin
LED_Dual_CACA
LED_Dual_CCA
LED_Small
LED_Small_ALT
QLS6A-FKW
SD103ATW
SFH4356P
SFH482
SMLVN6RGB
ZPYxx
```

I am not sure how I will continue from here on. Probably manually look at each symbol.
Do we have tools to render a symbol? Then I could script this even more.

**Comment by evanshultz** [comment]
@cpresser 
Thanks for looking again! There was some rendering stuff going on in https://github.com/KiCad/kicad-symbols/pull/1976 but I didn't personally try it.

**Comment by cpresser** [comment]
I did build a shitty renderer. It makes `.svg` files from the graphic primitives inside the symbol. With `rsvg-convert` I can generate `.png` files.
It is pretty crude, the bounding-box stuff does not work properly yet. But its good enough to finally finish this PR.

Left row is #2301, right row is master:
foo

**Comment by cpresser** [comment]
Can somebody else please look over the pictures? I did not find any issues, but a second pair of eyes to check would be nice.

**Comment by cpresser** [comment]
For reference, the shittyDraw code is here: https://github.com/cpresser/kicad-library-utils/tree/shittyDraw

**Comment by buzztiaan** [comment]
This looks a bit odd? 
image

**Comment by cpresser** [comment]
> This looks a bit odd?
> image
Rendering error, the script is not aware of multi-units yet.

**Comment by evanshultz** [comment]
Thanks! This is still very valuable for doing these kinds of quick comparisons. The new and old symbols all look like they match to me, but I'm not an impartial third party.

**Comment by cpresser** [comment]
updated comparison with slightly better rendering 
* bounding boxes, 
* arcs
* text position
comp

**Pull request merged**
