### PR TITLE
add LT3045 voltage regulator, MSOP-12

### PR DESCRIPTION
**Pull request by aewallin**
https://www.analog.com/media/en/technical-documentation/data-sheets/3045fa.pdf

very similar to the lower current one #1812 - but this one is in MSOP-12

LT3045xMSE

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Let's replicate the comments I made at https://github.com/KiCad/kicad-symbols/pull/1812 and then I'll review further.

For the future, you're welcome to submit these two together since they're so similar and in the same library.

**Comment by aewallin** [comment]
edited symbol:
LT3045xMSE

**Comment by evanshultz** [comment]
Thanks!

Merging the other PR caused this branch conflict. If you fix that and change pin 3 to Input type I will merge.

**Comment by aewallin** [comment]
I interpreted your "3" above as "4 EN/UV"

**Comment by evanshultz** [comment]
You read my mind correctly. Thanks!

**Pull request merged**
