### PR TITLE
Add SN74CBT3253

### PR DESCRIPTION
**Pull request by einball**
Add SN74CBT3253 Dual 1:4 Analog Multiplexer

The datasheet can be found here: [SN74CBT3253](http://www.ti.com/lit/gpn/sn74cbt3253)

- Adds SN74CBT3253 with the SOP16 (*D*) and the TSSOP (*PW*) variant. 
- __KLC violation:__ I did not draw separate symbols but set multiple possible footprints in the footprint filter since all variants have the same pinout, only differ in device suffix and package variant.

bildschirmfoto vom 2019-03-04 11-29-19

---
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by einball** [comment]
Pin 9 now corrected to __2A__ instead of __1B__ as seen in the provided image above!

**Comment by myfreescalewebpage** [comment]
Hi @einball , thanks for contributing,

A single comment I have during my review:

- [ ] You can add one footprint filter to cover SSOP footprint: `SSOP*5.3x10.2mm*P0.65mm*`

Else, it's good to merge.

Cheers,
Joel

**Comment by einball** [comment]
I added `SSOP*5.3x6.2mm*P0.65mm*` to the footprint filter, since this has 16 pins, not 28.

Thanks for the review!

Jan

**Comment by myfreescalewebpage** [comment]
You are right !
Thanks for the addition, merging.
Joel

**Pull request merged**
