### PR TITLE
Commonalize Transistor_FET

### PR DESCRIPTION
**Pull request by evanshultz**
From https://github.com/KiCad/kicad-symbols/issues/1975.

Changes:
-Use a common symbol design
-Set various parameters per KLC
-Align FP filters

Here are examples of the unified style:
image
image

There are a lot of lines changed, so I'm not sure the best way to review this.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Ping!

I'd like to submit some new FET symbols, but didn't want to mix an entire library update with additions.

**Comment by evanshultz** [comment]
Ping again! Is this able to be merged so I can submit new FET symbols and so it's not a headache with future merges to this file?

**Comment by evanshultz** [comment]
I would be happy to fix https://github.com/KiCad/kicad-symbols/issues/2041 in this PR if nobody minds. I can submit another PR to fix it as well. But I'd really be happy to see this merged one way or another.

**Comment by frantony** [comment]
@evanshultz

Can we create scripts for regenerating entire Transistor_FET library (as [R_Network.py](https://github.com/KiCad/kicad-library-utils/blob/master/schlib/autogen/R_Network/R_Network.py) does)?

**Comment by evanshultz** [comment]
Could it be done? Yes.

**Comment by frantony** [comment]
@evanshultz

I have made a script for counting uniq drawings in kicad symbol library, please see [count-uniq-kicad-sym-draw-sh](https://gist.github.com/frantony/bffd4c2713df5fda72cbef1dd4c7b3c1#file-count-uniq-kicad-sym-draw-sh).

The script uses [kicad-library-utils](https://github.com/KiCad/kicad-library-utils) for extracting all component from symbol library. Next script extracts drawing for every component (without pins!) and finds identical drawing by hash summing.

The script reports that

  * there are 22 uniq drawings (total 67) in [KiCad master Transistor_FET.lib]( https://github.com/KiCad/kicad-symbols/blob/master/Transistor_FET.lib)
  * there are 9 uniq drawings (total 67) in [evanshultz:transistors/Transistor_FET.lib](https://github.com/evanshultz/kicad-symbols/blob/transistors/Transistor_FET.lib)

Great work!

Is there a simple method to render one kicad symbol in a batch mode?
I want to make a script for visual comparison.

**Comment by evanshultz** [comment]
Thanks for your effort here!

I understand this means only 9 unique symbols are required and this PR is correct in simplifying as much as possible.

I do not know about a mode to render just a single symbol as you mention. Asking on the developer mailing list is probably the best way to find out if this is possible.

**Comment by evanshultz** [comment]
Ping again! Again. Any chance to get this merged before branch conflicts?

**Comment by frantony** [comment]
@evanshultz 

I have generated Transistor_FET library symbols in batch mode with eeshow (see below).
My render script can be found here: [draw-uniq-kicad-lib-sym.sh](https://gist.github.com/frantony/7d146ebcc5db1fc5a8f2df1c99f80b38)
The script renders only first unit for multi-unit symbols (e.g. IRF7309).


Transistor_FET lib

**Comment by evanshultz** [comment]
@frantony 
This is very cool! Thanks!

FYI, our existing symbol generator is written in Python and can be found at https://github.com/KiCad/kicad-library-utils/tree/master/schlib/autogen.

**Comment by evanshultz** [comment]
@poeschlr @cpresser @diegoherranz @chschlue 
Is anybody above to review and merge this? I note https://github.com/KiCad/kicad-symbols/pull/2066 and https://github.com/KiCad/kicad-symbols/pull/2095 affect the same files and avoiding branch conflicts is nice. If this could get merged and then the depletion mode symbols added it might clean everything up.

**Comment by chschlue** [comment]
Breaking:
- [x] No symbol names changed
- [x] No pins moved

Non-breaking:
- [x] FP changes OK

Not sure what else I definitely need to look out for so this doesn't break existing schematics.

**Comment by chschlue** [comment]
https://github.com/KiCad/kicad-footprints/pull/1803
https://github.com/KiCad/kicad-footprints/pull/1804
https://github.com/KiCad/kicad-footprints/pull/1805

**Comment by evanshultz** [comment]
Thanks! See https://github.com/KiCad/kicad-symbols/issues/520 and https://github.com/KiCad/kicad-footprints/issues/608.

Since nothing is getting worse, it should be OK to merge this if you don't find problems. Since initially realizing we had symbols without footprints, we've been strict about requiring footprints and merging them before symbols (and adding CI tests to verify any default footprint is present in the lib). That being said, I'm happy to update the Fairchild datasheet links (will have to be on Monday) before you merge. Just let me know.

I wanted to do the footprints with a script and have been discussing off and on with Infineon since the above issues were posted (well more than a year ago!) for complete DirectFET dimensions without success. Primarily the corners are undefined (not even a max dimension) but I can't recall off the top of my head if there were other missing parameters too. We can merge the footprints you made, and thanks for making them (!), but it would be nice if the vendor told us all info. At any rate, I'll review your footprints, hopefully on Monday, and merge them. Thanks for doing that! I was on vacation for several weeks, largely without internet, and then catching up at work but I should be able to be more involved here again now.

**Comment by chschlue** [comment]
I was somehow too stupid to find https://github.com/KiCad/kicad-footprints/issues/608.
Whatever, I'm almost done drawing all remaining DirectFET variants.

I think this PR is heavy enough already and other PRs are depending on it, so I'd rather merge this now. DS links can wait a day or two, I guess.

**Pull request merged**
