### PR TITLE
Sensor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added sensor symbol libraries

### CODE REVIEW

**Comment by evanshultz** [comment]
If you want to add a bit of polish, here is low-hanging fruit.

Sensor_Gas.dcm:
- URL is http://ams.com/eng/Products/Environmental-Sensors/Air-Quality-Sensors/CCS811
- "i2c" should be "I2C"

Sensor_Humidity.dcm:
- ENS210 URL should be http://ams.com/eng/Products/Environmental-Sensors/Relative-Humidity-and-Temperature-Sensors/ENS210

Sensor_Motion.dcm:
- Many ST URLs can be shorted, for example LSM9DS1 is www.st.com/resource/en/datasheet/lsm9ds1.pdf

Sensor_Multifunction.dcm:
- DHT11 cxan remove the leading `- ` from description
- SHT1x URL is https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Sensirion_Humidity_Sensors_SHT1x_Datasheet_V5.pdf

Sensor_Optical.dcm:
- Flir_LEPTON (is that even a good name?) URL should be http://www.flir.com/uploadedFiles/OEM/Products/LWIR-Cameras/Lepton/Lepton%20Engineering%20Datasheet%20-%20without%20Radiometry.pdf

Sensor_Pressure.dcm:
- LPS25HB URL could be www.st.com/resource/en/datasheet/lps25hb.pdf
- MPL115A1 has vendor names and URL as keywords

Sensor_Temperature.dcm:
- Many parts in SOT23 and SC70-5 have the word "package" (could be just `SOT-23` or `SC-70-5`)

**Comment by evanshultz** [comment]
@SchrodingersGat 
Great work! This is much better than before. I still see some footprint stuff that could be cleaned up, such as `MPL115A1` showing an FPfilter of `*LGA*8*`, but I think it's fine to merge. Did you want to do anything else?

**Comment by SchrodingersGat** [comment]
Please merge as is, we will raise an issue to fix. Stable release is just around the corner :)

**Comment by SchrodingersGat** [comment]
As long as this is "as good" as the v4 repo then I'm happy for now

**Comment by SchrodingersGat** [comment]
@evanshultz @poeschlr ok to merge?

**Pull request merged**
