### PR TITLE
muRata OKI-78SR serie added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
* OKI-78SR-3.3/1.5-W36H-C
* OKI-78SR-5/1.5-W36H-C 
* OKI-78SR-12/1.0-W36H-C 
* OKI-78SR-3.3/1.5-W36-C
* OKI-78SR-5/1.5-W36-C
* OKI-78SR-12/1.0-W36-C

Datasheet: https://power.murata.com/data/power/oki-78sr.pdf

image
image

image
image
 
footprint PR: https://github.com/KiCad/kicad-footprints/pull/960

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [-] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by serkanxselcuk** [comment]
CI errors are only footprint, they are on PR process.

**Comment by poeschlr** [comment]
Sorry it took so long. Thanks for this nice contribution.

**Comment by poeschlr** [comment]
Ok i have written too early. I just noticed this is placed into the switching regulator library. That library is meant for ICs that still need external components attached to function. This contribution would fit better into Converter_DCDC as it is a ready made module.

**Comment by nonninz** [comment]
Hi.

I'm also using this part in one of my boards and I'd like to see this merged. I have addressed @poeschlr latest comment in my fork, however I'm not sure how to proceed from here.

I thought the proper way would be to make a PR from my fork towards @serkanxselcuk repository, so that he can merge it if he wants and this PR would be conseguentely updated, but GitHub won't allow me to do so.

Could you suggest a way for this to go on? [Here is a link to the commit where I fix the issue](https://github.com/nonninz/kicad-symbols/commit/7f24e083d8e55ae5371664234b9260b45c98ffaf).

Thank you all for your hard work <3

**Comment by poeschlr** [comment]
The correct way to take over a pull request is by creating a new pull request here on the official library based on the original pull request.
If you do that make sure you reference the original pull request such that whoever reviews it can look at the original to know what was requested.

**Comment by nonninz** [comment]
Thank you. New PR: #1695

**Comment by myfreescalewebpage** [comment]
New PR has been created for this one, closing.

**Pull request closed without merging**
