### PR TITLE
Add PAC193x QFN

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/PAC1931-Family-Data-Sheet-DS20005850E.pdf

Screenshot:

PAC1931
PAC1931

PAC1932
PAC1932

PAC1933
PAC1933

PAC1934
PAC1934

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

PAC1931x-xJQ
- [ ] Missing a comma in description before the package name

All devices:
- [ ] Footprint filter should be `UQFN*1EP*4x4mm*P0.65mm*`
- [ ] Name of pin 4 is SM_CLK
- [ ] Name of pin 5 is SM_DATA
- [ ] EP pin number 17 should be added at the bottom of the symbols. It is NOT stacked with GND.

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage, have made the changes requested.

screenshot:
PAC1934

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
