### PR TITLE
Add HT9170D

### PR DESCRIPTION
**Pull request by fvollmer**
Add the HT91070D DTMF receiver (http://www.holtek.com/documents/10179/116711/9170v111.pdf).

ht91070d

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by fvollmer** [comment]
There is a warning:

>   Violating S4.4
>     Pin electrical type should match pin function
>     Pin types should match pin function
>      - Pin VREF (4) @ (-500,100) is type POWER OUTPUT : suggested INPUT

I think this warning can be ignored, since VREF is generated internally.

**Comment by myfreescalewebpage** [comment]
Hi @fvollmer , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name, `, SOIC-18`
- [ ] Comma is not required in the keywords, to be removed
- [ ] Pin length should be 100mil (symbol < 100pins)
- [ ] We usually put reference in the top left corner and name in the top right corner. Actually the name override the VDD pin which is not very convenient.

Travis warning about VREF accepted.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@fvollmer modifications ok. Many changes due to newer version of KiCad, accepted. Following the modification of pins length, you have new KLC error (see travis output). You have to enlarge a little bit the symbol to fit the 100mil grid.

**Comment by fvollmer** [comment]
Thanks for your review! I think I implemented all changes.

ht9170d

**Comment by myfreescalewebpage** [comment]
VDD and VSS pin still too long, otherwise seems okay. Reduce pin length, and increase a little bit the outline box of the symbol.
Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
Great. No more comment to do, merging.

Joel

**Pull request merged**
