### PR TITLE
added NCP662

### PR DESCRIPTION
**Pull request by Knochi**
added ON-Semi Low Dropout Regulator NCP662 Series in common fixed voltages 1.5V, 1.8V, 3.3V and 5.0V.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)

Regulator_Linear_NCP662SQ15T1G

### CODE REVIEW

**Comment by cpresser** [comment]
Hi and thanks for you contribution!
This looks like its the first symbol to use the `SC-82AB` package. 

There are a few things that should be addressed before I can merge this:
- [x] Description and keywords are good
- [x] Package is good
- [ ] Footprint-Filter should not start with an `*`
- [ ] I would like to wait for travis-ci to generate a result. Unsure why it fails. I did restart the build, but it still fails. I will investigate this, but are open to suggestions as well.
- [ ] The pin-names are not correct, they should be VIN and VOUT.
- [ ] The `T1G` suffix should be removed. It is non-functional.
image

**Comment by myfreescalewebpage** [comment]
@Knochi ping, are you still alive on this subject ?

**Comment by Knochi** [comment]
> 
> 
> @Knochi ping, are you still alive on this subject ?

Ah yes.. sorry
will have a look

**Comment by Knochi** [comment]
- [x] Footprint-Filter should not start with an *
- [ ] I would like to wait for travis-ci to generate a result. Unsure why it fails. I did restart the build, but it still fails. I will investigate this, but are open to suggestions as well.
- [x] The pin-names are not correct, they should be VIN and VOUT.
- [x] The T1G suffix should be removed. It is non-functional.

**Comment by myfreescalewebpage** [comment]
Did you manage to get it working ? Just inform us so the ongoing status of this PR is clear for us

**Comment by myfreescalewebpage** [comment]
Just seen the new PR you have done, for the future you should keep your branch until the PR is merged, and you can simply push to your branch to update the PR. Continue the review on the other PR.

**Pull request closed without merging**
