### PR TITLE
Tmc2041 la

### PR DESCRIPTION
**Pull request by Misca1234**
Push for 

TMC2041-LA
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2041_datasheet.pdf

TMC2100-LA 36 pin
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2100_datasheet_Rev1.08.pdf

TMC2100-LA 48 pin
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2100_datasheet_Rev1.08.pdf

TMC2041-LA
bild

bild

TMC2100-LA 36 pin
bild

bild

TMC2100-LA 48 pin
bild

bild

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
#### TMC2041-LA
- I think that the current rating in the description should be 2.2A, instead of 2.0A.
Fixed
- Please change the maximum voltage rating in the description from 46V to 26V.
Fixed
- I'd recommend adding `UART` to the description.
Fixed
- I couldn't find a mention of `/RX` in the datasheet for the `SDO` pin. Can you please point me to where you found the `RX` usage?
Page 8, Pin 8, "mode configuration input in UART mode"
- I would recommend adding space between DIR2, CSN pins, and between BR2B, CPI pins, but this one's just personal preference.
Fixed
- Please remove GNDA from the stacked pins and place it off to the side.
Fixed
- This one's knit-picky (sorry): Can you please change QFNxx to QFN-xx in the descriptions?
Fixed
-I'd recommend removing Step/Direction from the keyword lists.
- Please consider changing the footprint filter format for all symbols to: QFN?48*1EP*7x7*P0.5mm*EP5.3x5.3mm*
Changed it to QFN*1EP*7x7*P0.5mm*EP5.3x5.3mm*, pin number should be included


#### TCM2100-LA_TQFP-EP48

- Please remove GNDA from the stacked pins and place it off to the side.
Fixed
- This one's knit-picky (sorry): Can you please change QFNxx to QFN-xx in the descriptions?
Fixed
    I'd recommend removing Step/Direction from the keyword lists.
Fixed   
- VCP powers the charge pump, so I think that it would be beneficial on the top of the symbol, rather than the right.
Fixed
- I'd suggest moving TST_MODE to the bottom-left of the symbol, underneath SWSEL to make it easier to connect to GND.
Fixed
- Please change the name of this symbol to TCM2100-TA (-TA for TQFP indication)
Fixed
-Please consider changing the footprint filter format for all symbols to: QFN?48*1EP*7x7*P0.5mm*EP5.3x5.3mm*
-This symbol lists the incorrect footprint. Please fix:
This push needs an additional foot print to be pushed

- The filter
Fixed
- The description
Fixed
- The footprint field
Fixed

**Comment by Misca1234** [comment]
-Please consider changing the footprint filter format for all symbols to: QFN?48*1EP*7x7*P0.5mm*EP5.3x5.3mm*
-This symbol lists the incorrect footprint. Please fix:
This push needs an additional foot print to be pushed

Dont merged before needed foot print is merged

**Comment by Misca1234** [comment]
TMC2100-TA  do now have the correct foot print

> Please consider changing the footprint filter format for all symbols to:

I keept _ThermalVias in the FP filter, these symbols do have an extra pin for the therminal vias pad and if a user choose a non thermal foot print there will be an unconnected pin

**Comment by evanshultz** [comment]
The footprint filter should not include the EP size nor the vias. This allows the user to pick a non-default footprint from all the options that are likely to fit the package (unless they disable all CvPcb filtering, at which point they can really do some silly things).

Leave the `mm` after the body size in the footprint filter. This will make sure things don't break now. If height is added, which is a good idea and probably should have been done from the beginning and if even in the IPC footprint naming doc, at least all of our footprints and filters are consistent so even though we'll have a huge pile of clean-up work at least one set of rules will apply everywhere.

Note that asterisks are a Markdown character and so please enclose footprints (and filters) in the grave accent character (https://en.wikipedia.org/wiki/Grave_accent, I had to look up what the heck that thing is actually called), used in Markdown to enclose code and eliminate formatting, so that rendering the footprint [filters] doesn't get messed up. This is especially helpful for users that may comment via email and can't see the Markdown formatting.

**Comment by DanSGiesbrecht** [comment]
@Misca1234 sorry for the delay. Reviewing your latest commits, I've added a checklist for pending changes:

#### Common to all
- [ ] I noticed that you separated out `GNDA` on TMC2041-LA and TMC2100-TA - Thanks! TMC 2100-LA still requires the `GNDA` pin to be separated from the stack.
- [ ] I wasn't clear with this one, sorry. Please also change the descriptions for the other packages:
    - TMC2100-LA: `QFN-36`
    - TMC2100-TA: `TQFP-48` (this one is currently listed as `QFN-48` in the description)
- [ ] Thanks for removing this from some of the symbols. `Step/Direction` is still present in TMC2100-LA.
- [ ] I think I understand where the miscommunication lies with regards to thermal vias. From @Misca1234:
> I keept _ThermalVias in the FP filter, these symbols do have an extra pin for the therminal vias pad and if a user choose a non thermal foot print there will be an unconnected pin
  - Removing the `ThermalVias` portion of the filter means that the designer can select a footprint that doesn't have vias. There will still be a thermal **pad** (because the filter still contains `EP`), but it means that they can place their own vias during layout.
  - Aligning with @evanshultz 's feedback, please change the footprints to the following:
    - TMC2041-LA: `QFN*1EP*7x7mm*P0.5mm*`
    - TMC2100-LA: `QFN*1EP*5x6mm*P0.5mm*`
    - TMC2100-TA: `TQFP*1EP*7x7mm*P0.5mm*`
- [x] I'd suggest moving `TST_MODE` to the bottom-left of the symbol, underneath `SWSEL` to make it easier to connect to `GND`.
  - **Comment**: Thanks! :+1:

#### TMC2041-LA
- [x] Please change maximum current in the description to 2.2A, instead of 2.0A.
  - **Comment**: Thanks! :+1:
- [x] Please change the maximum voltage rating in the description to 26V, instead of 46V.
  - **Comment**: Thanks! :+1:
- [x] I'd recommend adding `UART` to the description.
  - **Comment**: Thanks! :+1:
- [ ] With regards to pin 8 `SDO`: I did some extra digging. Pin 8 isn't actually the `RX` line of the UART peripheral.
  - From page 20 of the datasheet:
UART-signals
  - The `SDO` pin is used for configuration selection in UART mode, and doesn't carry data. `SWIOP` and `SWION` are used for communication. Please change the name to just `SDO`, rather than `SDO/RX`.

- [x] I would recommend adding space between DIR2, CSN pins, and between BR2B, CPI pins, but this one's just personal preference.
  - **Comment**: Thanks! :+1:

#### TCM2100-LA_TQFP-EP48
- [x] Please change the name of this symbol to `TCM2100-TA` (-TA for TQFP indication)
  - **Comment**: Thanks! :+1:
- [ ] This symbol lists the incorrect footprint. Please fix:
  - [ ] The filter (Please see footprint filter note above)
  - [ ] The description (Noted above - still lists QFN)
  - [x] The footprint field
- ~~As with GNDA, I would recommend separating out GNDD on this package. This will allow the designer to separate motor power from GNDD and GNDA.~~
  - The datasheet recommends using the thermal lug as a star-GND point, so I think that what you've done by separating out analog GND is good enough.
- [ ] To match TMC2041-LA, please change `BRA`, `BRB` to passive types.

#### TCM2100-LA
- ~~As with GNDA, I would recommend separating out GNDD on this package. This will allow the designer to separate motor power from GNDD and GNDA.~~
- [ ] Please separate out the GNDA signal as with other symbols.
- [ ] To match TMC2041-LA, please change `BRA`, `BRB` to passive types.

**Comment by DanSGiesbrecht** [comment]
@Misca1234 
Great, thanks! Please push the changes. I can check them now, or later today.

**Comment by Misca1234** [comment]
Pushed now, apparently it was to late for me yeasterday

**Comment by DanSGiesbrecht** [comment]
All good, I'm still awake :laughing: 

All the changes look good, thanks! There's one thing that's still there (sorry): The description of TCM2100-TA has `TQFN-48`, which should be `TQFP-48`. Otherwise, all the other changes look good!

**Comment by Misca1234** [comment]
It have been changed

**Comment by DanSGiesbrecht** [comment]
I just noticed that the Travis check was failing, my bad. Please also change TMC2100-LA:
- pin 11 to `GNDD`, and
- pin 35 to `GNDP`.

**Comment by Misca1234** [comment]
They are now changed, the travis error concern the SDO pin

**Comment by DanSGiesbrecht** [comment]
Thanks for all the work on this one!

**Pull request merged**
