### PR TITLE
Add KT2520.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://global.kyocera.com/prdct/electro/product/pdf/kt2520_e.pdf

image

footprint pr: https://github.com/KiCad/kicad-footprints/pull/1284

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name, `, Kyocera 2520` based on the footprint name
- [ ] The footprint filter never contains the number of pins, I propose `Oscillator*SMD*Kyocera*2.5x2.0mm*`

Need to wait for the footprint review.

Cheers,
Joel

**Comment by matthuszagh** [comment]
Thanks for the comments Joel, I made the changes.

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment on the symbol. Waiting for the footprint now before merging.

**Comment by aewallin** [comment]
should you specify TCXO here (with pin1 to GND), to make it separate from the VCTCXO variant, where pin1 is the input control voltage?

**Comment by matthuszagh** [comment]
Yeah you're right, good catch. What's the best way to specify that? Name the component "KT2520_TCXO"?

**Comment by myfreescalewebpage** [comment]
Good catch @aewallin I haven't realized there were two versions.

Ordering information indicate there is a "T" at the end for TCXO version, so I suggest to rename the part "KT2520K-T" (because KT2520K-xxxxx-x-x-x-xx-x-T" is too long).

We don't know the Spec Codes for the other version, but this will be possible to add them with another letter at the end later when they will be available.

Let me known about this proposition.

Joel

**Comment by myfreescalewebpage** [comment]
Found an exmaple of the other version on Mouser: https://www.mouser.fr/ProductDetail/Kyocera-Electronic-Components/KT2520K26000DCW28QAS?qs=BybUIy1AcUaoD%252bX5%2FJuT8g%3D%3D

There is also a KT2520Y series: https://global.kyocera.com/prdct/electro/pdf/KT2520Y_e_2007.pdf

So I think the choice is nice. Waiting for the footprint.

Joel

**Comment by myfreescalewebpage** [comment]
Footprint integrated, merging the symbol now.

**Pull request merged**
