### PR TITLE
Added the NXP PCF8525T I2C Real Time Clock

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Sorry been a while and I've lost track of things. This is the addition of the 'T' device.

I have to check the footprint for the other two, as a cursory glance didn't find them. Creating pull request to check Travis.

Datasheet - https://www.nxp.com/docs/en/data-sheet/PCF8523.pdf

Screenshot from 2019-04-02 19-36-06

### CODE REVIEW

**Comment by swedishhat** [comment]
Hi @johnfwhitmore, I cloned your repo and ran the SchLib helper script on your modified library. It threw the following error: 
image

Your pin position offset is set to 40mil (1.016mm), which is still technically compliant to the KLC since it's less than the 50mil max:
image

However, I'd still probably recommend changing it to 20mil (0.508mm) to avoid this collision between the VSS pin and the INT1/CLK0 pin -- changing the pin position offset fixes it:
image

Also, please rename pin 7 from "INT1/CLKO" to "~INT1~/CLKO". This will place a bar over the "INT1" part showing that it is an active low signal.
image

Otherwise, looks good! :+1:

**Comment by johnfwhitmore** [comment]
Thanks for your comments. It's still a bit cramped down there but might be better then increasing the size of the symbol.

Screenshot from 2019-04-06 15-42-13

**Comment by johnfwhitmore** [comment]
Thanks for your comments. It's still a bit cramped down there but might be better then increasing the size of the symbol.

**Comment by swedishhat** [comment]
Looks good to me. I'm new to this and don't have merge rights or anything but hopefully we can get an admin to weigh in and move it along

**Comment by myfreescalewebpage** [comment]
Hi @johnfwhitmore , thanks for contributing,

First thanks to @swedishhat for the first step review :)

A few comments I have during my review:

- [ ] Name of pin 7 should be `~INT1~/CLKOUT`
- [ ] The design of the symbol is a little bit different than the other RTC in the library. Maybe you can arrange the pin looking at DS1307Z+ example. Proposition below.

Capture

Cheers,
Joel

**Comment by swedishhat** [comment]
Hi @myfreescalewebpage, not a problem. It looks like "Name of pin 7 should be ~INT1~/CLKOUT" is already fulfilled since it has the bar over the top. His commit also says "X ~INT1~/CLKO 7 400 -200 100 L 50 50 1 1 O"

**Comment by johnfwhitmore** [comment]
Can I respond from email.

Going to look at that this evening so if there are comments I'll address
them later, but I think the negative logic pin is sorted.

**Comment by myfreescalewebpage** [comment]
I'm not pointing the negative logic but the name itself, CLKOUT vs CLKO. The datasheet indicate CLKOUT, so you should follow this name for better understanding.

**Comment by johnfwhitmore** [comment]
Oops, sorry don't know where I pulled that from. I'll change it.

**Comment by myfreescalewebpage** [comment]
No worries :)

**Comment by evanshultz** [comment]
Note that clock output and interrupt pins on this IC are all open drain.

**Comment by myfreescalewebpage** [comment]
Good catch @evanshultz I have forgotten this point ! @johnfwhitmore can you fix INT/CLKOUT pin type too ?
Thanks,
Joel

**Comment by johnfwhitmore** [comment]
Screenshot from 2019-04-10 06-47-01

**Comment by johnfwhitmore** [comment]
Sorry for the delay over the last few days. Normal laptop had to go in for repair so fighting with an old 32bit device.

**Comment by myfreescalewebpage** [comment]
@johnfwhitmore that's great except the symbol is not vertically centered (see travis warning). Can you fix it ? Then ready to be merged :)

**Comment by johnfwhitmore** [comment]
I actually looked for that when I did it but didn't see the axis in the symbol editor. Must not have been awake.


Screenshot from 2019-04-10 23-28-37

**Comment by myfreescalewebpage** [comment]
No worries, thanks this looks great! Merging :)

**Comment by johnfwhitmore** [comment]
Thanks a million for your help!

**Comment by myfreescalewebpage** [comment]
You're welcome :)

**Pull request merged**
