### PR TITLE
add Lis3dh

### PR DESCRIPTION
**Pull request by penoud**
Add the accelerometer LIS3DH 
---
- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
https://www.st.com/resource/en/datasheet/cd00274221.pdf
- [X] An example screenshot image is very helpful
image
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @penoud thanks for this contribution,

I see you have many travis errors that are not expected, please have a look to the results.
Also, two immediate comments I have: GND pins must be stacked, pin length should be 100mil (symbol < 100pins)

Cheers,
Joel

**Comment by penoud** [comment]
@myfreescalewebpage  Yes way too much Travis errors. Should be fine now.

**Comment by myfreescalewebpage** [comment]
Hi @penoud , thanks for contributing,

A few comments I have during my review:

- [ ] Description can be enhanced to be more consistent with other symbols, for example I think to `3-Axis Accelerometer, 2/4/8/16g range, I2C/SPI interface, LGA-16`
- [ ] Keywords too for the same reason: `3-axis accelerometer i2c spi mems`
- [ ] Footprint filter should be `LGA*3x3mm*P0.5mm*LayoutBorder3x5y*` 
- [ ] Pin 10 should be stacked with GND
- [ ] Type of ADCx pins should be Input
- [ ] Type of INTx pins should be Output
- [ ] GND pins are not stacked correctly, invisible GND pins should be Passive
- [ ] The pins can be arranged better to get symmetrical symbol horizontally and more symmetrical vertically too
- [ ] For consistency with other LIS* symbols, SPI pins to be moved on the left, ADCx can be on the right

Cheers,
Joel

**Comment by penoud** [comment]
Update screenshot:
image

**Comment by myfreescalewebpage** [comment]
RES pin to be stacked on GND not fixed (datasheet page 9 indicate "Connect to GND")
Not realized before, NC pin should be moved on the border outline of the symbol.

Proposition for the position of the pins:

capture

Let me known what do you think of this.
I have keep INT pins with SPI/I2C interface because it is intended to be connected to a MCU.

**Comment by penoud** [comment]
I corrected the symbol according your comment. Thanks

**Comment by myfreescalewebpage** [comment]
Thanks. For pin stacking, you should rename pin 10 to GND (see also travis error).

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
