### PR TITLE
add RF switch MASWSS0178

### PR DESCRIPTION
**Pull request by hvraven**
This adds the RF switch [MASWSS0178](https://cdn.macom.com/datasheets/MASWSS0178.pdf).

Screenshot_20190817_210058

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

- [ ] The footprint filter should be `MSOP*3x3mm*P0.65mm*`
- [ ] I suggest to have the same design than the "MSW-2-20" in the lib (except the drawing inside of course)

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

thanks for the review. I fixed the footprint filter. I have a question about adjusting the symbol. I do like the idea of having them interchangable, but the MSW-2-20 symbol is rather large due to the long pin names used by Mini-Circuits. When using the same outline the symbol will be unnecessarily large. Should I use the same vertical positions, but compressed in the horizontal direction?

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Good comment. "Should I use the same vertical positions, but compressed in the horizontal direction?" I think yes, it is a good idea.
Joel

**Comment by lorem-ipsum** [comment]
I changed the drawing and pin layout as suggested. I kept the combination of closed and open switch from the MSW series. There is no documentation on the switch state if both CTL pins are low, so there is no correct layout for it.

MASWSS0178

**Comment by myfreescalewebpage** [comment]
I disagree with the drawing inside the symbol.
With my previous comment I was thinking to have the same pin position to have something consistent across this kind of symbols. However, the switches were great before and are no more as shown in the datasheet now....

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum ping ?

**Comment by myfreescalewebpage** [comment]
@hvraven ping

**Comment by myfreescalewebpage** [comment]
@hvraven ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by hvraven** [comment]
Hi @myfreescalewebpage ,

I just understood what your issue with the drawing was, of course you're totally right. What do you think of this version? It is not exactly pin compatible with the other switches (RFC is one position down), but it allows it to keep the style of the original drawing.
Screenshot_20200826_103805

**Comment by myfreescalewebpage** [comment]
It's not bad, ok for me. Merging.

**Comment by myfreescalewebpage** [comment]
Thanks for the update of this PR :)

**Pull request merged**
