### PR TITLE
Adding TLV755xxPDRV, TLV757xxPDRV

### PR DESCRIPTION
**Pull request by ki5libs**
Adding TLV755xxPDRV, TLV757xxPDRV
[Datasheet TLV755](http://www.ti.com/lit/ds/symlink/tlv755p.pdf)
[Datasheet TLV757](https://www.ti.com/lit/ds/symlink/tlv757p.pdf)

TLV755-757xxPDRV_new

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@ki5libs 
Please fix the branch conflict due to me merging your other PR in this library.

**Comment by ki5libs** [comment]
@evanshultz 
Done

**Comment by cpresser** [comment]
- [ ] FP-Filter should be `WSON*1EP*2x2mm*P0.65mm*`
- [ ] The description says `SOT-23-5`, but the package is `WSON-6`
- [ ] Pinput does not match the datasheet

**Comment by evanshultz** [comment]
ALIASes for `TLV70012_SOT23-5` are now on two lines. I'm not sure why this happened but we know one line is safe. @ki5libs What version of KiCad are you running? @cpresser Please be sure to open this branch in 5.1.4 to be sure it doesn't break anything before merging.

**Comment by cpresser** [comment]
Thanks @evanshultz, i was debugging it and had not yet found it.
I am running KiCad 5.1.4 from debian backports. 

image

**Comment by ki5libs** [comment]
@cpresser 
My apologies for the inconvenience. Looks like I made some mistakes during manual conflict resolving. It should  be OK now.
@evanshultz 
I'm still running 5.0.0-rc3-6a2723a. May it cause problems?

**Comment by cpresser** [comment]
@ki5libs no problem, that's what reviews are for.
I suggest you update to the latest stable version. Running a `-rc` version in production seems weird.

**Pull request merged**
