### PR TITLE
added AD7794/AD7795 ADC

### PR DESCRIPTION
**Pull request by jstjst**
Added Symbol forAD7794/AD7795 ADC
https://www.analog.com/media/en/technical-documentation/data-sheets/AD7794_7795.pdf

grafik

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jstjst** [comment]
> Violating S3.3
    Symbol outline and fill requirements
    Component outline is thickness 0mil, recommended is 10mil
fixed
>  Violating S4.4
    Pin electrical type should match pin function
    Pin types should match pin function
     - Pin CLK (2) @ (700,300) is type BIDI : suggested INPUT
CLK can be Clock in or out (see datasheet p.11)
>  Violating S6.2
    Component fields contain the correct information
    Datasheet field must be EMPTY
fixed

**Comment by jstjst** [comment]
- [ ] Descriptions have a spelling error: "Channel", not "Channal"
- [ ] Descriptions should be terminated with the package name, please add , TSSOP-28 at the end
- [ ] You should group the serial interface pins SCLK, DOUT, DIN and CS together
- [ ] NC pin 4 should be moved on the border outline of the symbol
- [ ] I think PSW should be Passive to avoid ERC errors (Power Output of the left side not allowed in the KLC)
- [ ] The symbol is very large and very tall for no reason, have a look to ADS8688 symbol for example that has been merged recently to enhance yours

**Comment by jstjst** [comment]
Should be fine now - for whatever reason the check don't update

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the checks.

**Comment by myfreescalewebpage** [comment]
Thanks @jstjst no more comment to do, merging.

**Pull request merged**
