### PR TITLE
OCXO OH300

### PR DESCRIPTION
**Pull request by aewallin**
Datasheet: http://www.conwin.com/datasheets/cx/cx282.pdf

Screenshot:
ocxo_connorwinfield_oh300

Footprint-PR: to-do

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1112

**Comment by aewallin** [comment]
I changed the symbol to show sine-wave output:
ocxo_connorwinfield_oh300

**Comment by aewallin** [comment]
Footprint merged. https://github.com/KiCad/kicad-footprints/pull/1112

**Comment by myfreescalewebpage** [comment]
Hi @aewallin, thanks for contributing,

A few comments I have during my review (basically the same as https://github.com/KiCad/kicad-symbols/pull/1199):


- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to get travis execution.

**Comment by myfreescalewebpage** [comment]
Good to see the description enhanced too!
No more comment on this symbol. Merging.

Joel

**Pull request merged**
