### PR TITLE
Add AS1115

### PR DESCRIPTION
**Pull request by evanshultz**
https://ams.com/documents/20143/36005/AS1115_DS000206_1-00.pdf/3d3e6d35-b184-1329-adf9-2d769eb2404f

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Footprint PR at https://github.com/KiCad/kicad-footprints/pull/853.

**Comment by evanshultz** [comment]
Forgot to easily show pin types:
image
image

**Comment by evanshultz** [comment]
Footprints have been merged so this is all green and ready to merge, I think.

**Comment by Misca1234** [comment]
Looks Good

**Pull request merged**
