### PR TITLE
Adding Si7336ADP

### PR DESCRIPTION
**Pull request by ki5libs**
Adding Si7336ADP
[Datasheet](www.vishay.com/docs/73152/si7336adp.pdf)
si7336adp
[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/935)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ki5libs** [comment]
Pins 6-8 are removed corresponding to footprint [PR#935](https://github.com/KiCad/kicad-footprints/pull/935)
si7336adp

**Comment by evanshultz** [comment]
- Change the package in the description from "SO-8" to "PowerPAK-8".
- There is now no default footprints. Use `Package_SO:Vishay_PowerPAK_SO-8`.
- The footprint filter should then be `Vishay*PowerPAK*SO*`.

**Comment by evanshultz** [comment]
Thanks! The footprint filter is missing the `Vishay` part but otherwise it's ready to merge.

**Comment by ki5libs** [comment]
@evanshultz I found `Package_SO:PowerPAK_SO-8_Single` and `Package_SO:PowerPAK_SO-8_Dual` in footprint library. Looks like `Package_SO:Vishay_PowerPAK_SO-8` created by me duplicates `Package_SO:PowerPAK_SO-8_Single`... I didn't see it when I created this [PR](https://github.com/KiCad/kicad-footprints/pull/935). What do you think, maybe the right way is change default footprint of Si7336ADP to `Package_SO:PowerPAK_SO-8_Single`, leave footprint filter as it is and then create PR for removing `Package_SO:Vishay_PowerPAK_SO-8`?

**Comment by evanshultz** [comment]
Yes, go ahead and do that. Thanks for checking!

**Comment by ki5libs** [comment]
@evanshultz sorry for some delay.

I've changed it now. This is [PR#1037](https://github.com/KiCad/kicad-footprints/pull/1037) for removing `Package_SO:Vishay_PowerPAK_SO-8`

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
