### PR TITLE
Cleaned up issues for MCU_NXP_LPC.lib

### PR DESCRIPTION
**Pull request by DerekGn**
Cleaned up build issues for MCU_NXP_LPC.lib from https://github.com/KiCad/kicad-symbols/issues/25

image

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

THanks for the contribution. I had a quick look at it ... is there a reason why you removed the footpritn fields? Are these devices meant for different footprints each? If there is only one footprint per device, set the footprint field (see http://kicad-pcb.org/libraries/klc/S5.1/ and http://kicad-pcb.org/libraries/klc/S5.2/) to point to that footprint AND the footprint filter (FPFilter) to match that footprint (+possible variants, like _HandSoldering ...). An example:
LPC1102UK pointed to `Package_CSP:WLCSP-16_4x4_2.17x2.32mm_P0.5mm`, which was renamed to `Package_CSP:WLCSP-16_4x4_B2.17x2.32mm_P0.5mm`, so the footprint field should be set for the second (newer) version. 
The FPFilter then does not have to contain the package lib. In the case above it should be simply `WLCSP*4x4*B2.17x2.32mm*P0.5mm*`.

Could you modify your PR accordingly?

Thanks,
JAN

**Comment by DerekGn** [comment]
Ok I missed the fact that the FP should be set with the FP filter. I will fix and update PR.

**Comment by jkriege2** [comment]
Hi!

nice work, thanks!
One last thing: Could you remove the pin-count 16 from the WLSCP-package FPFilter?

Thanks,
JAN

PS: Could you also take a second look at your older work there: https://github.com/KiCad/kicad-symbols/pull/83

**Comment by DerekGn** [comment]
I am working on #83 at the moment
Part 1 here https://github.com/KiCad/kicad-symbols/pull/97

you mean change this WLCSP*16*4x4*B2.17x2.32mm*P0.5mm* to this WLCSP*4x4*B2.17x2.32mm*P0.5mm*?

**Comment by jkriege2** [comment]
yes, that's what I meant. 

Pin count is not a "problem" ... we distinguish two cases here:
1. Symbols that have all pins (also NC pins) have the same number of pins in the symbol as are found in the package. Therefore KiCADs own pin-count filter is used to match out the correct footprint (e.g. for `DIP*W7.62mm*` will match all naroow DIPs, but the pin-count filter will narrow it down to say a DIP-8). Tehrefore pin-count is not necessary
2. In contrast there may be symbols where you don't place all pins (e.g. a reference diode in DIP-8, as you really cannot place all those 6 NC pins ...). Then we need the pin-count in the filter as the pin-count filter in KiCAD does not work for such cases!

**Comment by jkriege2** [comment]
PS: The KLC is not that specific about this, it just states to include all "dimensional information" ...
PPS: Bear in mind: This is one of the less important rules in KLC ;-)

**Comment by DerekGn** [comment]
Right that all makes sense I had forgotten about KiCADs own pin-count filter. So there is no need set the pin count explicitly in the Fpfilter. I will fix.

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
