### PR TITLE
Added PIC18F25K83-SP microcontroller

### PR DESCRIPTION
**Pull request by zettawatt**
Added the PIC18(L)F2[5|6]K83-SP microcontroller symbol
Datasheet: 
http://ww1.microchip.com/downloads/en/DeviceDoc/40001943A.pdf

image

### CODE REVIEW

**Comment by poeschlr** [comment]
Sorry for the late answer.

Please accept the license agreement (or close the pull request if you do not want your work to be published under the kicad library license.)

---

It might be possible to reduce the size of this symbol.
Please stack the VSS pins (this moves responsibility from the circuit designer to the symbol designer)
Note to self: pin numbers vs pin names is ok.

**Comment by myfreescalewebpage** [comment]
@zettawatt are you still alive on this subject ? As @poeschlr indicated above, you should first sign the CLA before we start the review of your contribution. This is a mandatory condition to get your contribution accepted. Thanks for the update, Joel

**Comment by myfreescalewebpage** [comment]
@zettawatt ping! :)

**Comment by myfreescalewebpage** [comment]
No response for 3 months on this PR, tagged Abandoned.

**Comment by RICCIARDI-Adrien** [comment]
Hi,
This microcontroller has been added to library with pull request #1120, so this pull request may be closed.

**Comment by myfreescalewebpage** [comment]
Thanks @RICCIARDI-Adrien for this remark, closing this PR, indicate it's duplicated.

**Pull request closed without merging**
