### PR TITLE
Added L80 gps receiver

### PR DESCRIPTION
**Pull request by kajusK**
Added L80 GPS receiver
Datasheet: https://www.quectel.com/UploadImage/Downlad/L80_Hardware_Design_V1.1.pdf
Footprint: https://github.com/KiCad/kicad-footprints/pull/2498

2020-09-28-131636_1920x1080_scrot

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@kajusK this is rejected because the repo is locked. Moreover, the PR is currently in progress for this symbol: https://github.com/KiCad/kicad-symbols/pull/2657

**Comment by kajusK** [comment]
@myfreescalewebpage
Ah, I missed that PR, will check it, thank you.

I was expecting a reject partially due to the message shown, but I was not able to find any footprint/symbols repo on the gitlab the message was mentioning. Is there any page where I could follow the progress of the repos porting and see when the new repos are ready for PRs?

**Comment by myfreescalewebpage** [comment]
There will be moved to GitLab the 2020-10-01, it's very soon. Our timeline is at https://github.com/orgs/KiCad/teams/librarians/discussions/49?

**Comment by myfreescalewebpage** [comment]
@kajusK L80-R just merged in the lib. But I notice your module is L80, not L80-R, can you check and tell me ? Seems the footprint is the same, isn't it ?

Anyway, it is good if the two symbol can be interchangeable, I let you check this point and maybe you can  push when we will be on GitLab.

**Pull request closed without merging**
