### PR TITLE
adds the THAT1512 chip to the audio amp library

### PR DESCRIPTION
**Pull request by krinkleneck**
Adding the THAT Corp. THAT1512 Audio Amplifier Package.  Default assignment is DIP-8, but it comes in multiple package types.

---

Thanks for reading a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- http://www.thatcorp.com/datashts/THAT_1510-1512_Datasheet.pdf
THAT1512

- Packages DIP & SOIC

- [?] Is the lack of color a violation of conventions?

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@krinkleneck about "Is the lack of color a violation of conventions?", yes, please update. Thanks, Joel

**Comment by krinkleneck** [comment]
How do you fill the background?  I am not finding an option in the symbol editor.

**Comment by krinkleneck** [comment]
Nevermind

**Comment by myfreescalewebpage** [comment]
@krinkleneck I have not made a full review, but:

- [ ] Documentation link should be field with datasheet link
- [ ] One symbol should be submitted for each package, footprint and footprint filter should be set
- [ ] Pin name position offset is usually 5mil for this kind of symbol (triangle)
- [ ] Description can be enhanced and should ends with the package name
- [ ] The triangle and the position of the pins are not consistent with other devices, look at THAT1580 for an example

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@krinkleneck any news here ? Thanks :)

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this PR is abandoned.

**Pull request closed without merging**
