### PR TITLE
add SFP/SFP+ connector

### PR DESCRIPTION
**Pull request by aewallin**
SFP+ defined in SFF-8431 https://www.snia.org/technology-communities/sff/specifications
SFP defined in INF-8074i , from e.g. http://www.10gtek.com/templates/wzten/pdf/INF-8074.pdf

20-pin connector + Cage, for SFP/SFP+ optical transciever.
Most pins are shared between SFP (1Gbit) and SFP+ (10Gbit) standards.
There are a few pins that differ in name/function, these are separated by a slash "/" in the symbol.
- an option is to instead have two separate symbols, one for SFP and one for SFP+

Footprint: https://github.com/KiCad/kicad-footprints/pull/1214

sfp_sfp _connector

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
fp-filter is remaining travis error - will fix when footprint is merged.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

SFP_CONNECTOR
- [ ] I suggest to rename simply to `SFP`
- [ ] The symbol is generic, you should remove the footprint and I suggest to just have footprint filter `*SFP*` to allow several footprint in the lib
- [ ] "SFP" text in the symbol is not useful
- [ ] CAGE should be Passive
- [ ] All MOD_DEF should be Input or Passive ? Do you know what is the purpose of these pins ?
- [ ] Reference should be J, not P

SFP+_CONNECTOR
- [ ] I suggest to rename simply to `SFP+`
- [ ] The symbol is generic, you should remove the footprint and I suggest to just have footprint filter `*SFP*` to allow several footprint in the lib
- [ ] "SFP+" text in the symbol is not useful
- [ ] CAGE should be Passive
- [ ] SCL should be Input
- [ ] Reference should be J, not P

Cheers,
Joel

**Comment by aewallin** [comment]
- SFP+ datasheet is SFF-8432 https://members.snia.org/document/dl/25892
- SFP datasheet is INF-8074, from e.g. http://www.10gtek.com/templates/wzten/pdf/INF-8074.pdf (not sure what would be the most generic/official link)
- MOD_DEF pins listed in INF-8074 page 21-22 (essentially the same as for SFP+) 2-wire serial interface and a mod_abs that is grounded by the SFP-module when present.
- maybe description should be "connector for SFP module" as this symbol is not the SFP module itself?

**Comment by myfreescalewebpage** [comment]
Yes you can add "Connector for" in front of both descriptions I think this will be ok.
One more comment: for symbols, do not add any extra information in the document link, just simply indicate the link. Else, it is not possible to open the documentation with the PDF icon !

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Merging.

**Pull request merged**
