### PR TITLE
Added PN512 RFID module

### PR DESCRIPTION
**Pull request by Kev-J**
Hi,

I just created the symbol for the PN512 RFID module.
Associated footprint: https://github.com/KiCad/kicad-footprints/pull/2439
Datasheet: https://www.nxp.com/docs/en/data-sheet/PN512.pdf
Sans titre

Cheers,
Kevin

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Kev-J , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with package name and should not have specific symbols: `NFC frontend, ISO/IEC 14443A&B, MIFARE, FeliCa and NFC Forum tag types, HVQFN-32` is great
- [ ] Footprint should be HVQFN, not QFN. If it does not exists you should submit it.
- [ ] Fp filter will be `HVQFN*1EP*5x5mm*P0.5mm*`
- [ ] You should align DVDD with DVSS, PVDD with PVSS etc
- [ ] Name of pin 6 should be `~NRSTPD`
- [ ] I don't see where pin 33 is connected to PVSS in the datasheet. Should be called "EP", Passive, and not stacked with PVSS
- [ ] You should stack TVSS pins
- [ ] The global dimensions of the symbol can be reduced a lot, please

Cheers,
Joel

**Comment by Kev-J** [comment]
Hi Joel,

It should be better now. I updated the PR's first message to link with the footprint's PR.
I still have one error (except the missing footprint) about the TVSS pin stack. Do you want me to turn one pin into invisible and passive?

cheers,
Kevin

**Comment by myfreescalewebpage** [comment]
Thanks for the update.

> Do you want me to turn one pin into invisible and passive?

Yes one of the two should be Passive Invisible to respect stacking rule.

One comment also:

- [ ] EP is no more stacked, so it should be visible now

Joel

**Comment by Kev-J** [comment]
Done 👍 

Thanks a lot,
Kevin

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint.

**Comment by cpresser** [comment]
This is yet another instance where the footprint is just a copy of an existing one.
See https://github.com/pointhi/kicad-footprint-generator/pull/629#issuecomment-692875089

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging the symbol following the footprint

**Pull request merged**
