### PR TITLE
Add Y14 Relay

### PR DESCRIPTION
**Pull request by asukiaaa**
Add Y14 relay.

http://www.hsinda.com.cn/en/ProductShow.asp?ID=208

screenshot from 2018-04-25 20-18-40

Foorprint: https://github.com/KiCad/kicad-footprints/pull/519

Thanks.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for you contribution. please fix these errors reported by Travis:
```
Checking symbol 'Y14':
  Violating S3.6
    Pin name position offset
    Pin offset not preferred value
     - Pin offset (40) should be 20mils unless required by symbol geometry
  Violating S5.2
    Footprint filters should match all appropriate footprints
    No footprint filters defined
  Violating S6.3
    Part meta-data is filled in as appropriate
    Component Y14 has metadata errors:
     - Symbol name should not be included in description
```

In addition, please change you symbol, so it follows the style of the other relays in this lib:
2018-04-26 21_26_17-symbol library editor - relay d__kicad_kicad-symbols_relay lib

Finally, please directly link a PDF (datasheet) rather than the webpage of the product and please make your description and keywords close to other relays, e.g. 
```
D: Hsin Da Y14-series relay, Single Pole Dual Throw
K: Relay SPDT
```

Also please rename the symbol to `Y14x-1C-xxDS`, as this is the full MPN with voltage/sensitivity wildcards.

Best & thanks,
JAN

**Comment by asukiaaa** [comment]
Dear JAN

Thanks for reviewing and comments.
I updated symbol like this.
https://github.com/KiCad/kicad-symbols/pull/539/commits/4b638f6c0301804032959057498570ee6065b01b
screenshot from 2018-04-27 23-29-31

Thanks,
Asuki

Footprint: https://github.com/KiCad/kicad-footprints/pull/519
3D model: https://github.com/KiCad/kicad-packages3D/pull/302
Source of 3D model: https://github.com/KiCad/kicad-packages3D-source/pull/123

**Comment by jkriege2** [comment]
Please stack pins 5&6 as in the screenshot I put above. Also: Is there a reason why you deviated from the style above still (pin-placement, symbol-size)? If you use the exact same design, it is very easy to exchange one relay for another!

**Comment by asukiaaa** [comment]
> If you use the exact same design, it is very easy to exchange one relay for another!

Exactly,.
I updated with using same design.
screenshot from 2018-04-28 00-14-03

**Comment by jkriege2** [comment]
Looks good, I will merge, as soon as the footprint has been renamed and the link corrected, as requested over at https://github.com/KiCad/kicad-footprints/pull/519

**Comment by asukiaaa** [comment]
I corrected link for footprint.

**Comment by jkriege2** [comment]
Thanks,
JAN

**Comment by asukiaaa** [comment]
Thank you very much.

**Pull request merged**
