### PR TITLE
Add ADG884 analog switch

### PR DESCRIPTION
**Pull request by gszy**
This PR adds two variants of the ADG884 analog switch: the LFCSP
ADG884BCPZ and the MSOP ADG884BRMZ. There also exists another variant:
the WLCSP ADG884BCBZ, but it seems its footprint is not yet available in
KiCad footprints repository.

## The datasheet

<https://www.analog.com/media/en/technical-documentation/data-sheets/ADG884.pdf>

### The symbol

ADG884xCP

### The pin table

ADG884xCP_KiCad_Pin_Table

### The symbol

ADG884xRM

### The pin table

ADG884BRM pins

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @gszy , thanks for contributing,

A few comments I have during my review:

ADG884BCP
- [ ] The name of the symbol should be "ADG884xCP"
- [ ] Description should ends with the package name: `0.5Ω CMOS, Dual 2:1 MUX/SPDT Audio Switch, LFCSP-WD-10`
- [ ] Fp filter should be `LFCSP*1EP*3x3mm*P0.5mm*` (never EP size in fp filter)
- [ ] Pin 11 should be stacked with GND

ADG884BRM
- [ ] The name of the symbol should be "ADG884xRM"
- [ ] Description should ends with the package name: `0.5Ω CMOS, Dual 2:1 MUX/SPDT Audio Switch, MSOP-10`

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@gszy ping
KiCad V6 is coming soon and the repo will be lock. It is good if we can arrange the integration of your PR before.
Thanks
Joel

**Comment by gszy** [comment]
@myfreescalewebpage, thanks for the review. I will try to push an updated version tomorrow.

**Comment by myfreescalewebpage** [comment]
@gszy please indicate when it's ready to review again.

**Comment by gszy** [comment]
In a few minutes, I hope…

**Comment by gszy** [comment]
It’s ready now. I have updated the pictures (except the last one) in the first comment as well.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
