### PR TITLE
Add ARJP11A-MASA-B-A-EMU2 RJ45 connector

### PR DESCRIPTION
**Pull request by ppielorz**
Added ARJP11A-MASA-B-A-EMU2 symbol
Datasheet: https://abracon.com/Magnetics/lan/ARJP11A.PDF
Screenshot: 
image

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1940

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @ppielorz,

Thanks for your contribution. One remark:

- [ ] I think your symbol is placed in the wrong library. In my understanding, the correct library is `Connectors` and not `Transformers`. It is a symbol for an RJ45 jack connector with a buit-in magnetic module.

**Comment by ppielorz** [comment]
You are perfectly right about library, I don't know why I left it in Transformers...

**Comment by gmsotavio** [comment]
Closing and reopening to force travis-ci

**Comment by gmsotavio** [comment]
- [ ] It seems that specified footprint is wrong. Specified footprint does not exist. Replace `Connector_RJ:RJ45_Abracon_ARJP11A-MA` by `Connector_RJ:RJ45_Abracon_ARJP11A-MA_Horizontal`
- [ ] In footprint filter, replace `RJ45*Abracon*ARJP11A-MA*` by  `RJ45*Abracon*ARJP11A?MA*` i

**Comment by ppielorz** [comment]
Done.

**Comment by gmsotavio** [comment]
Thanks

**Comment by cp-aquila** [comment]
Hi,

my OCD triggered slightly because the two halves of the transformer are not perfectly symmetrical.
So I took a closer look and found some more issues. They are all not really critical, its just cosmetic:
- [ ] Symmetry of transformers
- [ ] Duplicate lines 
grafik
- [ ] Of the the center-tap connections is missing (to the lower bridge rectifier)
- [ ] The LEDs should have arrows, otherwise they are just diodes
- [ ] Marker-Dot for the transformers is missing
- [ ] scaling of resistors/capactitors/diodes seems off. Here is a screenshot of the symbol with `R` and `C` symbols from the lib on top: 
grafik


It seems like travis does not catch the duplicate lines thing. I will investigate that.

**Comment by gmsotavio** [comment]
Hi @cp-aquila 
Unfortunately, I don't usually be as rigorous with the revision of symbols as I usually do with the revision of footprints. For future reviews of symbols I will try to be more rigid. What do you suppose I do here? Revert the PR and ask the author to make the modifications?

**Comment by cp-aquila** [comment]
Hi @gmsotavio 
No worries, my whole post is pretty much nitpicking. All those are cosmetic.
I would not revert the PR. Instead lets make a bugfix commit on top of that. The Pin-Positions and types do not need to change, so it won't be a breaking change.

@ppielorz Is that something that you want to do? If not, I will take care of it instead.

**Comment by ppielorz** [comment]
@cp-aquila I can do it. Should I make changes and commit to the same branch as before?

**Comment by cp-aquila** [comment]
I think its best if you make a new branch and a new PR. In that new PR, put a link to this one.

**Pull request merged**
