### PR TITLE
Temp sensor

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://www.silabs.com/documents/public/data-sheets/Si7050-1-3-4-5-A20.pdf

imagen

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
Thanks for the contribution!  There are a few changes I'd like to see before I can merge this.

* My comments from #491 about fixing Travis errors and removing the generic name apply here as well.
* Please make the symbol less wide.  It could certainly be made at least 200 mil narrower without any ill effects.
* The footprint name you've set isn't quite right, as it should also list the EP size.  I believe it should be called `DFN-6-1EP_3x3mm_P1mm_EP1.6x2.5mm`.  Are you planning on creating the footprint as well?
* Please move the reference text to the top left of the symbol, and the symbol name to the top right.

**Comment by Ratfink** [comment]
Thanks for making these changes!  I see a few more things that I'd like changed:

* The symbol is less wide than it was before, but now it's taller than it has to be.  If you could give it the height it had before, and the width it has now, that would be perfect.
* The new footprint name is still incorrect, as the EP size should be of the pad on the landing pattern, not on the chip itself.
* The old footprint filter (without the number of pins or EP size) was correct.  The number of pins gets filtered automatically, and we decided in #473 to leave the EP size out of footprint filters (but keep the number of EPs).

Given the current flurry of activity from #520, I will have to ask that a proper footprint be created for this before the symbol can be merged.

**Comment by carlosromorgar** [comment]
Hi
Thanks for your feedback. I have just pushed the footprint. It is #552 of footprint repository.
Regards

**Comment by Ratfink** [comment]
Sorry to keep telling you conflicting things about this, but since @poeschlr already made a script-generated footprint for this part in https://github.com/KiCad/kicad-footprints/pull/539, it would be best if you could just make this symbol use that footprint (and a matching filter) instead.  I'm really sorry that I wasted your time in creating a redundant footprint.

**Comment by carlosromorgar** [comment]
Upps. Sorry. It is my first time submitting symbols and I did not understand what you told me.

I have seen in KiCad/kicad-footprints#539 that it is not already merged. Should I add  DFN-6-1EP_3x3mm_P1mm_EP1.65x2.55mm reference to my symbol? Or it is necessary to wait until it was merged? Thank you in advance.
BR

**Comment by Ratfink** [comment]
Thanks for making that change, this symbol looks just perfect now.  After the footprint is merged, I'll merge this as well.  Thanks for the contribution!

**Pull request merged**
