### PR TITLE
Add RB1-125B8G1A RJ45 jack

### PR DESCRIPTION
**Pull request by joshtyler**
Add RB1-125B8G1A RJ45 jack with integrated 1000BASE-T magnetics.

[Datasheet](https://datasheet.lcsc.com/szlcsc/1901091107_UDE-Corp-RB1-125B8G1A_C363353.pdf)

image

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/1884)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by joshtyler** [comment]
Travis will pass once footprint is merged.

**Comment by joshtyler** [comment]
I got the LED polarities incorrect when originally creating the symbol. This is fixed in the latest commit

image

image

**Comment by myfreescalewebpage** [comment]
Hi @joshtyler , thanks for contributing,

This PR is quite old but finally will be reviewed. A few comments I have:

- [ ] Pin offset should be 20mil
- [ ] The description inside the symbol is wrong, "C4", "C5" and "C6" to be fixed. See schematic page 8.
- [ ] L1 and L2 are crossed (the anode is L1)
- [ ] L3 and L4 are crossed (the anode is L3)

Cheers,
Joel

**Comment by joshtyler** [comment]
Thanks for the review @myfreescalewebpage, I've rebased and addressed your review comments. The symbol now looks like this:
image

(There are two force commits because it took me a couple of goes to get the rebase right. I'm more used to conflict resolution using subversion rather than git!)

**Comment by myfreescalewebpage** [comment]
Thanks. Last comment I have not see on the previous review

- [ ] SH should be Passive.

Else just need to wait the footprint.
Joel

**Comment by joshtyler** [comment]
Thanks Joel, I've made that change.

**Comment by aris-kimi** [comment]
@myfreescalewebpage footprint PR merged.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
