### PR TITLE
Add Quectel M95 GSM modem

### PR DESCRIPTION
**Pull request by Schlumpf**
grafik
**Datasheet:** https://www.quectel.com/UploadImage/Downlad/M95_Hardware_Design_V1.3.pdf
**Footprint-PR:** https://github.com/KiCad/kicad-footprints/pull/2299
**KLC violation:** I stacked the two VBAT pins, because they are next to each other. The reason for two pins instead of one seems to be the high power bursts on connecting to the network.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] ~~Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)~~
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @AUTHOR, thanks for contributing,

A few comments I have during my review:

- [ ] RF_ANT should be Passive

Else just need to wait the footprint

Cheers,
Joel

**Comment by Schlumpf** [comment]
Done :)

**Comment by myfreescalewebpage** [comment]
@Schlumpf solved branch conflict for you here

**Comment by myfreescalewebpage** [comment]
Merging

**Comment by Schlumpf** [comment]
Thanks ;)

**Pull request merged**
