### PR TITLE
Added LMR33610

### PR DESCRIPTION
**Pull request by nivekg**
Added the LMR33610ADDAR and LMR33610BDDAR. Its the same as the LMR33640, the footprint and symbol are the same, so I just added it as an alias. Just changed the description to match the fact its can supply 1A and has a frequency of 400KHz and 1400KHz. 

Datasheet: http://www.ti.com/lit/ds/symlink/lmr33610.pdf 
LMR33910

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @nivekg no comment to do, can you fix the branch conflict due to #2776, thanks.

**Comment by nivekg** [comment]
@myfreescalewebpage Should be fixed now, thanks.

**Comment by myfreescalewebpage** [comment]
Issue in the dcm file.

Capture

**Comment by nivekg** [comment]
Sorry about that. I need to learn how to fixed merge conflicts better. Fixed the error and works fine now.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
