### PR TITLE
Added MUN3211DW Dual NPN BRT

### PR DESCRIPTION
**Pull request by Duckle29**
I've added the on-semi Dual NPN Bias Resistor Transistors or dual NPN BRT.
------------

[Datasheet](http://www.onsemi.com/pub/Collateral/DTC114ED-D.PDF)

Unit A Unit B

Options
Description
Aliases
Footprint Filter
Description for both of the aliases is the same
Alias description
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Duckle29** [comment]
The pins are not on a 100 mil grid. I'm not sure if they should be, or if the transistor should be centered. I copied the symbol from a different transistor.

Also, what do you think of the internal graphic of the resistor network? Yay or nay?

**Comment by evanshultz** [comment]
On simple symbols like this the pins can be on a 50mil grid.

Personally I dislike the way the resistors look here. Do you have any other ideas? I'm not sure what to suggest.

- Do not include the two automotive PNs.
- They are 100mA Ic.
- Remove "Small Signal" from the description.
- Footprint filter can be just `SOT*363*`.

**Comment by Duckle29** [comment]
@evanshultz I don't really like the look either. This with squiggly resistors might be marginally better?

**Comment by Duckle29** [comment]
I also don't know why it says I haven't signed the CLA, I have.

**Comment by evanshultz** [comment]
Does the email you used to submit the PR and the email you use for GitHub match? I believe that is the typical cause of issues with the CLA.

**Comment by Duckle29** [comment]
@evanshultz Email is the same as it's always been. Odd.

**Comment by evanshultz** [comment]
Seeing if close and reopen also fixes the hung up CLA on this PR...

**Comment by Duckle29** [comment]
Nice :)

**Comment by antoniovazquezblanco** [comment]
I like the box resistor design over the squiggly one. Have you tried to add the resistors out of the transistor circle?

**Comment by evanshultz** [comment]
Yes. By "general symbol design" I was trying to include "make it bigger" but that's not too clear above. I don't think it looks bad with resistors outside the circle, but it is quite big.

Here is what I came up with:
image

```
# MUN5211DW1
#
DEF MUN5211DW1 Q 0 20 Y N 2 F N
F0 "Q" 150 50 50 H V L CNN
F1 "MUN5211DW1" 150 -50 50 H V L CNN
F2 "Package_TO_SOT_SMD:SOT-363_SC-70-6" 5 -440 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 SOT*363*
$ENDFPLIST
DRAW
C -150 0 10 0 1 0 F
C 50 -120 10 0 1 0 F
C 0 0 111 1 1 10 N
C 0 0 111 2 1 10 N
S -250 20 -190 -20 0 1 0 N
S -170 -90 -130 -30 0 1 0 N
P 2 0 1 0 -150 -30 -150 0 N
P 2 0 1 0 -30 0 -190 0 N
P 2 0 1 20 -25 60 -25 -60 N
P 3 0 1 0 -150 -90 -150 -120 50 -120 N
P 2 1 1 0 -25 25 50 100 N
P 3 1 1 0 -25 -25 50 -100 50 -100 N
P 5 1 1 0 0 -70 20 -50 40 -90 0 -70 0 -70 F
P 2 2 1 0 -25 25 50 100 N
P 3 2 1 0 -25 -25 50 -100 50 -100 N
P 5 2 1 0 0 -70 20 -50 40 -90 0 -70 0 -70 F
X C1 3 50 200 100 D 50 50 1 1 P
X E1 4 50 -200 100 U 50 50 1 1 P
X B1 5 -350 0 100 R 50 50 1 1 I
X E1 1 50 -200 100 U 50 50 2 1 P
X B1 2 -350 0 100 R 50 50 2 1 I
X C1 6 50 200 100 D 50 50 2 1 P
ENDDRAW
ENDDEF
```

@Duckle29 
If you have any other ideas please submit them. If not, and you like this, you can push this style or some other variation. If we don't get any feedback in a few days we can accept this or an improved version.

**Comment by evanshultz** [comment]
No other comments in a few days and apparently this is OK with you, @Duckle29 . I'll merge this in a few hours if there is no new feedback.

**Comment by Duckle29** [comment]
I thought I commented, but aparrently I didn't.

I prefer the external version, even if it's a bit bigger. It's not perfect, but it's the best of the options :)

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
