### PR TITLE
Add MCP1802x-1202xOT

### PR DESCRIPTION
**Pull request by ikuo**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/22053C.pdf

image

## Checklist

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
Thanks for your submission.

- [ ] I think this symbol could be an alias of TC1017-xCT instead of a new symbol. That reduces the number of symbols in the library and makes the maintenance easier. Could you turn it into an alias?
- [ ] Optional: could you make aliases for the other voltages to have the complete series?

Thanks!

**Comment by ikuo** [comment]
@diegoherranz Thank you for the suggestion.

I've updated with alias with wildcard names `xx0xxOT` on voltage alternatives.
I hope it makes sense. But let me know, if I need to make a separate alias for each voltage alternative.

image

**Comment by diegoherranz** [comment]
Thanks for the changes.
Wilcarding the voltages looks good to me.
Just a couple of small comments:
- [ ] The file permissions have been changed from 644 to 755. Could you revert that?
- [ ] Could you add the tolerance to the name? That is MCP1802x-xx02xOT.

Thanks!

**Comment by ikuo** [comment]
@diegoherranz I've update on the two points.
Could you review again please?
Thank you,

**Comment by diegoherranz** [comment]
Looks good to me. Merging.
Thanks for your contribution. I hope it's the first of many.

**Comment by ikuo** [comment]
thank you!

**Pull request merged**
