### PR TITLE
Raspberry Pi Compute Modue 3 Plus

### PR DESCRIPTION
**Pull request by jneiva08**
Symbol for Raspberry Pi Compute Module 3 Plus and Lite

Datasheet: https://github.com/raspberrypi/documentation/raw/master/hardware/computemodule/datasheets/rpi_DATA_CM3plus_1p0.pdf

Scrennshot:
CM3+
cm3p

CM3+ Lite
cm3p_lite

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for these symbols, I'm currently making the review but it will take a little bit of time. Joel

**Comment by jneiva08** [comment]
Hi @myfreescalewebpage , have made minor changes.

Now all pins is in 2.54mm grid. but the lengt is 1.27mm
Removed duplicated GND pin.

**Comment by myfreescalewebpage** [comment]
@jneiva08 I wille make the review step by step, here are my first comments:

Module CM3:
- [ ] The name of the symbol is a little bit special, I think something like "RaspberryPi-CM3" and "RaspberryPi-CM3+" is better
- [ ] The descriptions can be enhanced, and "Module" is not correctly spelled. For example: `BCM2837 Broadcom 1.2GHZ single core industrial SoM computer` is great and consistent with other SOM in the library
- [ ] Same comment for keywords, `raspberry pi compute module` is great

**Comment by jneiva08** [comment]
Forgot to update how the symbols looks now

CM3+
CM3+

CM3+L
CM3+L

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks for this great modification! Some few items are not fixed yet, please checkout my previous comment.
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage , sorry if i did missed. Have made the changes requested, did the same for HDMI as DSIx/CAMx

**Comment by jneiva08** [comment]
@myfreescalewebpage , the CM3 can be an alias of CM3+ and the same for lite version. 

For CM1 need its own symbol because of SDX pins and GND are not connected and pin GPIO46/47 have different name.

**Comment by jneiva08** [comment]
CM3 is identical of CM3+, so made an alias.
Added in description the size of flash (if it have) and ram
Added symbol of CM1

**Comment by myfreescalewebpage** [comment]
@jneiva08 really great job !
Just one comment about the description modification: can you spell frequencies `MHz`and `GHz`to indicate the cpu clock speed.
Also, number and unit should be seprataed by a space: 700 MHz, 1.2 GHz, 1 GB RAM, etc
Thanks,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage , have already update the description.

the CM1 is not compatible with CM3/CM3L, for the IO pin compatible needs to grow a little.

**Comment by myfreescalewebpage** [comment]
Thanks @jneiva08 , great job here ! Merging :)

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
