### PR TITLE
Move IQRF (DC)TRs into RF_Module library

### PR DESCRIPTION
**Pull request by Roman3349**
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/452

Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

Move IQRF (DC)TRs into RF_Module library

 - IQRF (data controlled) transceiver are moved to RF_Module library
 - Datasheet for TR-72DA(T) is updated.

Datasheet: https://iqrf.org/weben/downloads.php?id=337

Screenshot:
tr-52da

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Roman3349** [comment]
@Misca1234 

1. I'll fix it.
2. 
Whole RF module is inserted in "SIM card" connectors. The manufacturer recommends these ones:
- KON-SIM-01 (https://www.iqrf.org/products/accessories/connectors/kon-sim-01) - current footprint,
- KON-SIM-02 (https://www.iqrf.org/products/accessories/connectors/kon-sim-02).

**Comment by Misca1234** [comment]
Then Pin 9 is sort of very dubious, becaouse, as you point out, the second pin holder, KON-SIM-02, don't have "pin 9", perhaps you you should make it passive, or even NC, not visible ?

Then the user will not be suprised to see pin 9 and it will connect to "pin 9" on the foot print

**Comment by evanshultz** [comment]
@Roman3349 
Are you able to finish off this PR? I haven't looked at anything yet, but v5 is coming and this is one of the items that @Ratfink listed at https://github.com/KiCad/kicad-symbols/issues/520.

**Comment by Roman3349** [comment]
@evanshultz I hopefully fixed the footprint and the symbol 3 weeks ago.

And there is screenshot of the symbol:
tr-52da

**Comment by evanshultz** [comment]
@Misca1234 @Ratfink 
Would one of you be able to review this, making sure it's fixing #520, in the next couple days?

**Comment by evanshultz** [comment]
@Roman3349 
Thank you!

**Comment by Ratfink** [comment]
For this to improve the #520 situation, it needs to be merged along with https://github.com/KiCad/kicad-footprints/pull/452.  I'll try to review both before the end of this weekend.

**Comment by Ratfink** [comment]
Looks good, thanks for fixing up this old symbol (and creating the footprint for it)!

**Pull request merged**
