### PR TITLE
Fixed documentations URLs and pins type of the CP2102, CP2104, CP2112…

### PR DESCRIPTION
**Pull request by vlunyov**
Fixed documentations URLs to actual state.
Fixed incorrect pins type (Input, Output, Power etc) to correct type according the docs.
Were touched the CP2102, CP2104, CP2112, FT232RL, FT232BM and ADUM4160.
The geometry of the components did not changed.

### CODE REVIEW

**Comment by poeschlr** [comment]
A screenshot with "show pin types" enabled would help a lot here. Or make a list of what you changed.

**Comment by vlunyov** [comment]
adum4160
http://www.analog.com/media/en/technical-documentation/data-sheets/ADuM4160.pdf

ft232bm
http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232BM.pdf

ft232rl
http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf

ft245bm
http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT245BM.pdf

cp2102n
https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf

**Comment by vlunyov** [comment]
Also fixed the footprint mask of the FT245BM (error S5.1):
LQFP*7x7mm*P**0.5**mm -> LQFP*7x7mm*P**0.8**mm (it was checked in the datasheet).

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
