### PR TITLE
BAV99 fixes

### PR DESCRIPTION
**Pull request by evanshultz**
https://assets.nexperia.com/documents/data-sheet/BAV99_SER.pdf

BAV99 was a two-unit symbol with a duplicated pin 3. This is dangerous, and we fixed this with opamps having duplicated power pins, because it can allow an unintentional net short.

It's now a single-unit symbol like our other dual-unit diodes:
image

I also make the dot at the internal wire intersection for BAV99S be on both units (it was missing on the second unit):
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
BAV99 does not have the package-name in the description.
Besides that I found no other problems.

**Comment by evanshultz** [comment]
@cpresser 
I didn't even notice that was always missing. Added now. Thanks!

**Comment by cpresser** [comment]
Thanks! 
Out of curiosity, why is there a 2nd commit which is empty (e811612)?

**Comment by evanshultz** [comment]
Thanks!

Because that's what I had at the time, I used the web interface to make this change. When the page didn't save I hit the 'commit' button again.

**Pull request merged**
