### PR TITLE
Add SOIC and TSSOP AT25SF081 NOR Flash

### PR DESCRIPTION
**Pull request by awygle**
This adds the SOIC and TSSOP (but not DFN) packages of the AT25SF081 NOR Flash.

My main question mark here is how to deal with the QSPI mode for the pins...

Datasheet is https://www.mouser.com/datasheet/2/590/DS-AT25SF081_045-1385733.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by awygle** [comment]
The new symbols pass all Travis scripts, but the rest of this library is a mess.... maybe if I feel ambitious I'll try and clean them up but it'll be in a separate PR.

**Comment by DanSGiesbrecht** [comment]
@awygle  I recently pushed to the Flash Memory library file. It definitely is a mess, but as @poeschlr has mentioned, it can't be fixed until the v6 library release, to avoid breaking existing designs.

Some things can be cleaned up, such as descriptions, footprint references, and datasheet links. Pin positions, symbol location, and pin lengths are all things that currently cause the Travis check to fail, but can't be resolved right now without breaking library compatibility.

This was discussed a bit in #849

**Comment by awygle** [comment]
Ah I see, thank you for the additional context. I wasn't aware that there was a release process with stability guarantees for the libraries.

I will be happy to just get this merged, for now :) when it does become possible to make such changes, please let me know and I'll be glad to help out at that time.

**Comment by Misca1234** [comment]
@awygle 
Please us the manufactures link and not the distributer, that is, change from
https://www.mouser.com/datasheet/2/590/DS-AT25SF081_045-1385733.pdf
to
https://www.adestotech.com/wp-content/uploads/DS-AT25SF081_045.pdf

**Comment by Misca1234** [comment]
All looks good except one minor detail
in the description, add the capsule at the end, that is for AT25SF081-SSHD-X, change from 
8-Mbit, 2.5V Minimum SPI Serial Flash Memory with Dual-I/O and Quad-I/O Support
to
8-Mbit, 2.5V Minimum SPI Serial Flash Memory with Dual-I/O and Quad-I/O Support**, SOIC**

**Comment by awygle** [comment]
@Misca1234 done!

**Comment by Misca1234** [comment]
I am sorry, I was not clear enough, you need to do for the alias as well

AT25SF081-SSHD-X
8-Mbit, 2.5V Minimum SPI Serial Flash Memory with Dual-I/O and Quad-I/O Support, SOIC**-8**

AT25SF081-SSHF-X
8-Mbit, 2.3V Minimum SPI Serial Flash Memory with Dual-I/O and Quad-I/O Support**, SOIC-8**

AT25SF081-XMHD-X
8-Mbit, 2.5V Minimum SPI Serial Flash Memory with Dual-I/O and Quad-I/O Support, TSSOP**-8**

AT25SF081-XMHF-X
8-Mbit, 2.3V Minimum SPI Serial Flash Memory with Dual-I/O and Quad-I/O Support**, TSSOP-8**


Sorry for the pickynes

**Comment by awygle** [comment]
@Misca1234 fixed! That was my fault, I have a hard time remembering what is and isn't shared between the alias and the main symbol.

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
