### PR TITLE
added TLV9004xRUCR

### PR DESCRIPTION
**Pull request by Shackmeister**
Datasheet: http://www.ti.com/lit/ds/symlink/tlv9004.pdf
Based on one of the other quad opamps

@myfreescalewebpage All your suggested changes have been made
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@Shackmeister  thaks for this PR.
Just comment about the name of the device because I don't know what is the last "R" in the name. The package name is "RUC". I wonder if the last R is not the packaging option... That's why I suggest to rename the device to `TLV9004xRUC`
Joel

**Comment by myfreescalewebpage** [comment]
@Shackmeister any news here ? Thanks!

**Comment by Shackmeister** [comment]
hi @myfreescalewebpage 

I went over the datasheet again. I could probably change the "x" to "I" since it doesn't come in other versions with identical pinout and FP.

Regarding the last R, I can't find the partnumber anywhere without the R, so I'm not sure if it would be appropriate to remove it.

**Comment by myfreescalewebpage** [comment]
hello @Shackmeister 

> I went over the datasheet again. I could probably change the "x" to "I" since it doesn't come in other versions with identical pinout and FP.

No, "I" is the temperature that we always discard

> Regarding the last R, I can't find the partnumber anywhere without the R, so I'm not sure if it would be appropriate to remove it.

Yes I agree. Let say at the moemnt it's not a problem to keep it.

Merging :)

Joel

**Pull request merged**
