### PR TITLE
add Micro-Chip SY58031U clock buffer

### PR DESCRIPTION
**Pull request by hvraven**
[Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/sy58031u.pdf)
screenshot_20190124_092728

### CODE REVIEW

**Comment by aewallin** [comment]
VCC pins could be stacked?

**Comment by poeschlr** [comment]
The datasheet specifically asks for bypass caps at the VCC pins. Meaning they can not really be stacked. (My assumption would be that an ideal pcb design would have a separate cap for every VCC pin. To communicate this between the schematic designer and the layout guy you need every VCC pin separately in the symbol.)

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A single comment I have during my review:

- [ ] I sugegst to have pins VT and VREF-AC type set to Passive to avoid ERC error in all possible configuration (datasheet page 9).

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage,
sounds useful, I changed them to passive. I also added two aliases which are the same chip, but with different output signaling standards.

**Comment by lorem-ipsum** [comment]
i've just realised that the two aliases should not be aliases, but new components as the signaling standard is PECL which uses open emitters for output. So the output pins have a different function. I will make the changes later this day.

**Comment by myfreescalewebpage** [comment]
> i've just realised that the two aliases should not be aliases, but new components as the signaling standard is PECL which uses open emitters for output. So the output pins have a different function. I will make the changes later this day.

Yes exactly. Waiting for the change back then I will review the PR.

Joel

**Comment by lorem-ipsum** [comment]
I split the aliases into separate components, should be good now.

**Pull request merged**
