### PR TITLE
This PR transfers the symbols in maxim.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Moved to the following repos:

* Amplifier_Video
* Analog_ADC
* Driver_FET
* Interface_Expansion
* Potentiometer_Digital
* Power_Supervisor
* Sensor_Temperature
* Timer_RTC

There are a small handful still to be allocated in legacy/maxim.lib

### CODE REVIEW

**Comment by poeschlr** [comment]
Is it on purpose that you changed the descriptions for stuff that is already in the sensor temperature lib? (Mostly you removed the package information from it.)

For the unique id stuff we will again need an issue to get an idea where to put them.

**Comment by SchrodingersGat** [comment]
It appears that there were many duplications of symbols between `Sensor_Temperature.lib` and `maxim.lib` and they have been squashed together. I have manually added footprint descriptors back in for some of these symbols.

With issue #65 now raised, is this OK to merge?

**Comment by poeschlr** [comment]
You changed DS1822Z from soic-8 to msop-8 (in the description) the fp filter for it is for a soic footprint (The datasheet simply calls it 8 pin SO. There is no dimensioned drawing in the datasheet.)

**Comment by SchrodingersGat** [comment]
Changed it back manually. There must have been a discrepancy between the two existing symbols. Thanks for spotting that.

**Comment by SchrodingersGat** [comment]
@poeschlr any other changes? I'm waiting on this merge to complete some other libs :)

**Comment by poeschlr** [comment]
Looks good now. Thanks

**Pull request merged**
