### PR TITLE
Power_Management: Add MAX8586

### PR DESCRIPTION
**Pull request by dogtopus**
Datasheet: https://datasheets.maximintegrated.com/en/ds/MAX8586.pdf

Preview:

max8586

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] \(N/A) If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
@dogtopus 
It would be nice if you shortened the pin length to 100


@KiCad/librarians 
Should this be in Power_Management.lib as now or be in Regulator_Current.lib ?

**Comment by dogtopus** [comment]
@Misca1234 Done.

**Comment by DanSGiesbrecht** [comment]
I thin that Power_Management.lib is acceptable. The symbol in Regulator_Current.lib only provides current protection, whereas the part in this PR has multiple fault protections: over-current, over-temperature, and reverse-current.

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
