### PR TITLE
Add Allegro A4954 H-Bridge

### PR DESCRIPTION
**Pull request by einball**
This commit adds the Allegro A4954 Fullbridge stepper motor driver. You can find the link to the datasheet [here](https://www.allegromicro.com/-/media/Files/Datasheets/A4954-Datasheet.ashx). It uses a TSSOP16 package for which a matching package in kicad-footprints was found.

Bildschirmfoto vom 2019-12-22 14-36-15

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
pin1 and pin8, both GND, should be stacked? 
(unless there is some strange use-case where they are not connected both to GND??)

same for pin9 and pin16 - if they are internally connected together in the device, then they can be stacked in the symbol.

**Comment by einball** [comment]
Thanks for reviewing! GND and VBB do, of course, have to be stacked.

**Comment by myfreescalewebpage** [comment]
Hi @einball , thanks for contributing,

A few comments I have during my review:

- [ ] Description should be terminated by the package name: `Fullbridge PWM Motor Driver, UVLO, OCP, Current Limit, Short Circuit Protection, TSSOP-16`
- [ ] The package should be TSSOP, not HTSSOP.
- [ ] Footprint filter will be `TSSOP*1EP*4.4x5mm*P0.65mm*`
- [ ] Name of pin 14 is LSS34
- [ ] Expose Pad should be stack with GND for this device

Cheers,
Joel

**Comment by einball** [comment]
Hi @myfreescalewebpage , thanks for the review!

The recent commit includes all changes you requested, except for stacking PAD with GND since those are two different names (which makes them non-stackable by [KLC](https://kicad-pcb.org/libraries/klc/S4.3/). 

Should I rename PAD to GND, leave as-is or just stack the pins with different names?

**Comment by myfreescalewebpage** [comment]
"Should I rename PAD to GND" => yes please, this is the usual way to do in Kicad library

**Comment by einball** [comment]
Thanks for the clarification :+1:

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes.
I just realized the package has an EP but the footprint is not correct. It should have the EP size in the name. Moreover the selected footprint has not the right EP size.
You should submit the correct footprint using the footprint generator (https://github.com/pointhi/kicad-footprint-generator).
Joel

**Comment by myfreescalewebpage** [comment]
@PatrickBaus  ping! Any news of the footprint for this device ?

**Comment by PatrickBaus** [comment]
Did you mean to ping @einball?

**Comment by einball** [comment]
Sorry I abandoned the PR for the last months. I am working on my graduation thesis until end of August and won't be able to finish the PR until then. 

I will complete this as the first thing in September. If you deem that is too long, please close and I will reopen it as soon as I get to it.

**Comment by myfreescalewebpage** [comment]
@PatrickBaus yes sorry
@einball no worries, we keep the PR ongoing, this was just to have news from you :)

**Comment by einball** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2461
Generator PR: https://github.com/pointhi/kicad-footprint-generator/pull/615

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging

**Comment by einball** [comment]
Aww yiss! See you on Gitlab :heart_eyes:

**Pull request merged**
