### PR TITLE
Adds A3214ELHLT-T Hall effect sensor to Sensor_Magnetic

### PR DESCRIPTION
**Pull request by gvandewaetere**
Adds A3214ELHLT-T Hall effect sensor to Sensor_Magnetic
Datasheet: http://www.allegromicro.com/~/media/Files/Datasheets/A3213-4-Datasheet.ashx

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @gvandewaetere , thanks for contributing,

A few comments I have during my review:

- [ ] The new symbol should be an alias of `A1301KLHLT-T`, isn't it ?

It has several defects if you want to fix them:
- [ ] Footprint filter should be `SOT?23W*`
- [ ] VOUT should be written with capital letters

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@gvandewaetere any news here ? Thanks

**Comment by gvandewaetere** [comment]
Hi Joel,

You were absolutely right.
I have made the changes you proposed.

Kind regards,
Giovanni.

**Comment by myfreescalewebpage** [comment]
@gvandewaetere thanks, perfect fix, no more comment to do. Merging.

**Pull request merged**
