### PR TITLE
Added OPA196, OPA2196 and OPA4196

### PR DESCRIPTION
**Pull request by JeppeSRC**
Added the OPAx196 line of OpAmps.

[Datasheet](http://www.ti.com/lit/ds/symlink/opa4196.pdf)

img1
img2
img3

Violation S3.6: Pin name position offset is set to 0,127 because it's like that on every other OpAmp symbol.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Most of them can be an alias of an existing symbol. I checked pin-numbering and footprints.
(you can search for them with `grep -B2 "Package" libfile.lib`
* `OPA196IDBV` can be an alias of `NCS325`
* `OPA196ID` can be an alias of `OPA333xxD`
* `OPA196IDGK` can be an alias of `OPA197xDGK`
* `OPA2196` is slightly more difficult. There is `NCS2325D` which has the same symbol and shares the SOIC FP. But it does not have a fp-filter for VSSOP.
* `OPA4196` can be an alias of `OPA4197` (i have not checked the pins here, but assume they are the same)

**Regarding the `OPA2196`**
This could almost be fixed by adding the filter `SOP*3x3mm*P0.65*`, the `NCS2325D`  comes in `MSOP-8`, so this is fine. The only issue here is that the filter to match the VSOP needs to be `SOP*3.0x3.0mm*P0.65*`. The difference is the `.0` in the dimension.
A filter that catches both is `SOP*3*x3*mm*P0.65*`. Not sure if this is as intended.
Does KLC specify if `3mm` or `3.0mm` is correct?

**Comment by chschlue** [comment]
How about essentially copying https://github.com/KiCad/kicad-symbols/pull/2188?
All these problems have already been resolved over there.

**Comment by cpresser** [comment]
> How about essentially copying #2188?
> All these problems have already been resolved over there.
> 
> Edit: @cpresser do you mind me taking this one?
> Edit: Referencing #164 here as well won't hurt.

Yes please take it over, you already have the info needed for this.

**Comment by chschlue** [comment]
@JeppeSRC 
It's pretty simple

1. Re-branch from current master
2. Add OPA196xD to OPA333xxD
3. Add OPA196xDBV to MCP6L91T-EOT
4. Add OPA196xDGK to OPA197xDGK
5. Add OPA2196xD to NCS2325D
6. Add OPA2196xDGK to OPA2197xDGK
7. Add OPA4196xD to OPA4197xD
8. Add OPA4196xPW to OPA4197xPW
9. Force-push
10. Profit! Seven new op-amps.

**Comment by JeppeSRC** [comment]
shit

**Comment by JeppeSRC** [comment]
I did not mean to do that

**Comment by JeppeSRC** [comment]
Is there a way to revive it or do I need to open a new PR?

**Comment by evanshultz** [comment]
In the GitHub UI I believe you can restore your branch.

**Comment by chschlue** [comment]
In case you're still trying to recover the branch: Don't bother, just open a new PR. The necessary changes require a new branch anyway.

**Pull request closed without merging**
