### PR TITLE
Driver_LED: Add DIO5661x

### PR DESCRIPTION
**Pull request by m-laniakea**
Driver_LED: Add DIO5661x

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

https://www.mouser.com/datasheet/2/802/dioo_06292016_DIO5661V0%204-1217651.pdf

### CODE REVIEW

**Comment by m-laniakea** [comment]
symbol screenshot

**Comment by myfreescalewebpage** [comment]
Hi @m-laniakea , thanks for contributing,

I have not made a full review but right now:

- [ ] This device should be atomic, meaning you should define one symbol for each footprint option. Take care, SOT and DFN options have not the same pinout !!!
- [ ] Pin length should be 100mil (symbol < 100pins)
- [ ] NC pins should be added to the symbol, type Not Connected, invisible, and placed on the border outline of the symbol
- [ ] DFN option has pin 7 stacked GND
- [ ] FB will be better on the right
- [ ] LX should be Open Collector

Cheers,
Joel

**Comment by m-laniakea** [comment]
@myfreescalewebpage
Joel, thank you for your feedback.

FB may be better on the right, but would that not violate S4.2?
Also should there be a separate symbol for SOT and TSOT?

Good catch on the DFN pins. Thanks again.

**Comment by myfreescalewebpage** [comment]
> FB may be better on the right, but would that not violate S4.2?

This is accepted for this kind of symbol. Some parts of the KLC are simply guidelines but not strict.

> Also should there be a separate symbol for SOT and TSOT?

Yes

**Comment by myfreescalewebpage** [comment]
@m-laniakea thanks, making a full detailed review from this point:

All:
- [ ] Footprint is missing in field properties
- [ ] Datasheet should be from the manufacturer, not mouser !

DIO5661CD6:
- [ ] Footprint filter will be `DFN*1EP*2x2mm*P0.65mm*`
- [ ] Description should end with package name, add `, DFN-6` at the end

DIO5661ST6:
- [ ] Footprint filter will be `SOT?23*`
- [ ] Description should end with package name, add `, SOT23-6` at the end

DIO5661TST6:
- [ ] Footprint filter will be `TSOT?23*`
- [ ] Description should end with package name, add `, TSOT23-6` at the end

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
I have an error when opening the datasheet, and you ?

Capture

**Comment by m-laniakea** [comment]
@myfreescalewebpage 
Yes, same error. That is why the mouser datasheet was used.

There's [another page](http://www.dioo.com/uploads/product/20190311/e6c7f30c0fbe92fbfa6965c8ef1c5b19.pdf) which currently works.
Going to update a few hours from now.

**Comment by myfreescalewebpage** [comment]
@m-laniakea thanks for the update, it's better ! No more comment on this pull request, merging.

**Pull request merged**
