### PR TITLE
add Mini-Circuits low pass filter RLP-30

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/RLP-30+.pdf

rlp-30

Footprint: https://github.com/KiCad/kicad-footprints/pull/1136

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
@aewallin 
I guess you are aware of the merge conflict, it occur when you add several symbols at the same "point" in the file, when the first of your symbols is merged it causes a merge conflict in all you other pushes.
So you have either go over all your pushes and resolve the merge or choose in which order they should be merged (that is ignore all of them but one at the time)

**Comment by myfreescalewebpage** [comment]
Closing/opening again to update the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

The branch conflict prevent to checkout your contribution. Can you solve the conflict so I will be able to make the review ? Thanks.

Obviously, you can proceed with comments from https://github.com/KiCad/kicad-symbols/pull/1215 at the same time.
 
Cheers,
Joel

**Comment by aewallin** [comment]
Now:
rlp-30

**Comment by aewallin** [comment]
Note that here the recommended land-pattern is used by two different packages. The footprint is named with package GP731, but in fact this symbol uses another package (in description) GP1212.
https://ww2.minicircuits.com/case_style/GP731.pdf
the two packages differ in height and weight.

So the description here has GP1212, but the footprint-assignment(and fp-filter) is to GP731.
Not sure if there is a better solution.

**Comment by aewallin** [comment]
git-mess.
continued at #1373

**Pull request closed without merging**
