### PR TITLE
AD8015 transimpedance amplifier, in SOIC-8

### PR DESCRIPTION
**Pull request by aewallin**
https://www.analog.com/media/en/technical-documentation/data-sheets/AD8015.pdf

this is a transimpedance amplifier, not a pure op-amp. not sure if there is a better library where this can be placed?

AD8015

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] Your symbol is very tall, triangle symbols are usually a little bit smaller and with pin offset of 5, not 10. Moreover, I wonder if Vbyp should be on the left or on the bottom? An example to follow can be symbol THAT2181 in the library. Let me known about Vbyp position.

Maybe @evanshultz can also give his opinion on this design, he is used to review the triangle symbols :)

Cheers,
Joel

**Comment by evanshultz** [comment]
I would also support having the input on the middle left side an Vbyp on the top or bottom.

**Comment by myfreescalewebpage** [comment]
Yes @evanshultz probably it's better :)

**Comment by aewallin** [comment]
updated symbol:
AD8015

**Comment by evanshultz** [comment]
Here is an example with differential outputs in the library. It would be nice to commonalize.
image

Also, calling the power pins `+V` and `-V` has been done on all triangle symbols. It may be slightly different than the datasheet but it's still understandable and helps out with this small symbol size.

**Comment by myfreescalewebpage** [comment]
@aewallin your proposition is not yet aligned with the above exampel shown by @evanshultz (which is great I think)
Take care at the outputs dimensions and positions, and Vbyp should ne just on the right of -V
Joel

**Comment by aewallin** [comment]
the example-triangle mentioned above, THAT2181, had corners on a 200-mil grid, but that is too small for the pin-placements shown in LTC6362 - so now the triangle size is larger again following LTC6362.
AD8015

**Comment by myfreescalewebpage** [comment]
@aewallin thanks, according to me it's great now. @evanshultz your opinion is important for me here, what do you think of the above proposition ?

**Comment by evanshultz** [comment]
Looks good to me as well. Thanks all!

**Comment by myfreescalewebpage** [comment]
Thanks @aewallin for this symbol and @evanshultz for your confirmation, merging :)

**Pull request merged**
