### PR TITLE
Add Mini-Circuits RF switches KSW(A)-2-46 and KSWHA-1-20

### PR DESCRIPTION
**Pull request by lorem-ipsum**
Added the symbols for the RF switches. They all use the same package which can be found in [this PR](https://github.com/KiCad/kicad-footprints/pull/1062).
* [KSW-2-46](https://ww2.minicircuits.com/pdfs/KSW-2-46+.pdf)
ksw-2-46
* [KSWA-2-46](https://ww2.minicircuits.com/pdfs/KSWA-2-46+.pdf)
kswa-2-46
* [KSWHA-1-20](https://ww2.minicircuits.com/pdfs/KSWHA-1-20+.pdf)
kswha-1-20

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

KSW-2-46:
- [ ] Footprint is missing, should be `Package_SO:Mini-Circuits_XX112_LandPatternPL-217`
- [ ] Why SOP footprint filter ? Only XX112 one is required for me, see also my comment at https://github.com/KiCad/kicad-footprints/pull/1062#issuecomment-455994527

KSWA-2-46:
- [ ] Footprint is missing, should be `Package_SO:Mini-Circuits_XX112_LandPatternPL-217`
- [ ] Why SOP footprint filter ? Only XX112 one is required for me, see also my comment at https://github.com/KiCad/kicad-footprints/pull/1062#issuecomment-455994527

KSWHA-1-20:
- [ ] Footprint is missing, should be `Package_SO:Mini-Circuits_XX112_LandPatternPL-218`
- [ ] Why SOP footprint filter ? Only XX112 one is required for me, see also my comment at https://github.com/KiCad/kicad-footprints/pull/1062#issuecomment-455994527

Else no comment to do on the symbols.
Waiting for footprints to be merged to accept this contribution.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum any news on this subject ? Thanks, Joel

**Comment by lorem-ipsum** [comment]
I've rebased the branch and removed the SOP footprint filter. I have no interest in building the land pattern, as they  are only recommendations on how to use the footprint. If anyone wants to add them the footprint filter will catch them.

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum thanks for the update here. If you have only one remaining footprint filter, then the footprint should be set... I think you should add XX112 footprint here for the three symbols...

**Comment by lorem-ipsum** [comment]
based on the discussion in KiCad/kicad-footprints/pull/1062 I re-added the SOP footprint filter and set it to be the default. I've kept the filter for Mini-Circuits XX112 in case the LandPattern is added later on.

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum great. However, the format of the footprint is not correct, "pretty" and "/" should not be here.
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage, sorry for that, should have run the script on this. Hopefully its good now.

**Comment by myfreescalewebpage** [comment]
Now there is an issue opening the editor:

Capture

("$ENDCMP" is missing in the previous device, HMC7992, probably due to merge issue)

Joel

**Comment by lorem-ipsum** [comment]
Hi Joel,
sorry for that, you're probably right about the merge. Should be fixed now.
Hendrik

**Comment by myfreescalewebpage** [comment]
Hello Hendrik,
Thanks, yes it's common when merging.
Travis complains about the footprint, you should:
- Remove the footprint
- Or remove the XX112 footprint filter.

Joel

**Comment by lorem-ipsum** [comment]
I've removed the pre-selected footprint. Assigning it is easy and this way one can select the land pattern if it is created.

**Comment by myfreescalewebpage** [comment]
No more comment, merging.

**Pull request merged**
