### PR TITLE
Add ltc6804 1

### PR DESCRIPTION
**Pull request by phamhuuhuyhoang**
Added a schematic symbol for the LTC6804-1 (daisy chain version) 12 cell battery management IC

[Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/680412fc.pdf)
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @phamhuuhuyhoang , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with package name: `Multicell Battery Stack Monitor, 12-cell max, multi-chemistry, integrated balancing, stackable, serial interface, SSOP-48`
- [ ] Footprint should be SSOP-48, not TSSOP. If it does not exist you can submit it in footprint repo. Fp filter to be modified accordingly.
- [ ] V- pins to be stacked and centered
- [ ] V+ to be centered
- [ ] VREF1 is Output
- [ ] ICMP and IBIAS should be Passive

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@phamhuuhuyhoang ping

**Comment by phamhuuhuyhoang** [comment]
Updated with changes per feedback

- [x]  Description should ends with package name: `Multicell Battery Stack Monitor, 12-cell max, multi-chemistry, integrated balancing, stackable, serial interface, SSOP-48`
- [x]  Footprint should be SSOP-48, not TSSOP. If it does not exist you can submit it in footprint repo. Fp filter to be modified accordingly.
* [x]  V- pins to be stacked and centered
* [x]  V+ to be centered
* [x]  VREF1 is Output
* [x]  ICMP and IBIAS should be Passive

**Comment by myfreescalewebpage** [comment]
Thanks. The footprint does not exist, you have to submit it in https://github.com/KiCad/kicad-footprints/pulls using the generator https://github.com/pointhi/kicad-footprint-generator

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@phamhuuhuyhoang just notice a small error:

- [ ] the leading `*` in the fp filter is not required. `SSOP*5.3x12.8mm*P0.5mm*` is great

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
