### PR TITLE
Add SAM DA1 family

### PR DESCRIPTION
**Pull request by 0xdec**
Add Microchip SAM DA1 family (everything except the chip-scale packages). Aliases of SAM D21 family from #2336, see screenshots/discussion from there.

[Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAM_D21_DA1_Family_Data%20Sheet_DS40001882E.pdf)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi and sorry for the huge delay.

I see you did add new symbols and not just aliases. That I don't understand (yet).
For example it seems to me that `ATSAMDA1J14B-A` and `ATSAMD21J15A-A` are identical and could use the alias feature.

**Comment by 0xdec** [comment]
@cpresser good question, I don't remember why I decided to do that. I think just aliases should be fine. I'll try to change that now.

**Comment by 0xdec** [comment]
@cpresser changed to be aliases

**Comment by cpresser** [comment]
Looks good. Thanks!

**Pull request merged**
