### PR TITLE
Add Motorola MC6802 symbol, with aliases for the MC68A02 and MC68B02

### PR DESCRIPTION
**Pull request by nealcrook**
speed variants. Symbol is derived from MC6800 symbol because only a
small number of pins differ.

Cleanest datasheet is here:  https://www.jameco.com/Jameco/Products/ProdDS/43502.pdf
Alternative datasheet is here: pdf.datasheetcatalog.com/datasheets/700/499617_DS.pdf
(the Jameco one is better because it is a clean scan of a stand-alone datasheet that includes the speed variants. The one on pdf.datasheetcatalog.com is an extract from a large Motorola databook and only covers 1 speed variant)

image

This matches an existing 40pin DIL footprint.

I know of no library convention rule violations. I have made this as similar as possible to the existing MC6800 symbol.

Thanks for reviewing and (hopefully) accepting this symbol.

Neal.

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by nealcrook** [comment]
Whew. My first contribution to Kicad.

**Comment by myfreescalewebpage** [comment]
Hi @nealcrook , thanks for contributing and for this first PR!

A few comments I have during my review:

- [ ] You can stack VSS pins
- [ ] XTAL and EXTAL should be Passive

Cheers,
Joel

**Comment by nealcrook** [comment]
Hi Joel,
Thanks for your rapid review and feedback. I have made the changes you requested. However, this creates inconsistencies in this library because:
* MC6800 has non-stacked power pins
* MC6809 has XTAL and EXTAL pads marked as INPUT rather than PASSIVE
Should I change these two symbols (which I did not create) to be consistent with the rules applied to MC6802? It will be an easy/quick fix.

thanks,
Neal.

**Comment by myfreescalewebpage** [comment]
Hello neal,

Thanks for the fix. Please can you center VSS, you have probably aligned with VCC but when there is only one pin at the bottom I usually ask to center it.

Regarding the other symbols you mentioned, they are very old in the library and do not follow the last recommendations. If you want to upgrade them (in a new pull request) it's welcome ! It will be a breaking change so can be merged at the next major KiCad release, which is currently in preparation. Important note : in preparation of the next KiCad release the library repositories will be locked and no new pull requests will be accepted until we migrate the libraries. This will be done very soon, the 2020-09-01 so if you want to make the enhancements, you can do it now, 2 days left to make new pull requests only!

Joel

**Comment by nealcrook** [comment]
Joel.
I had agonised about whether to centre VSS!! It's done. I will do the other changes in a new branch/pull request after this is merged, provided there is time before the lock.

Thanks for guiding me through this process.

Neal.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
