### PR TITLE
add EMI filter Schaffner FN406

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the EMI filter series [FN406](https://www.schaffner.com/products/download/product/datasheet/fn-406-ultra-compact-emc-filter/) from Schaffner. Footprint can be found in this PR https://github.com/KiCad/kicad-footprints/pull/1783.

Screenshot_20190817_220222

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
[G1.1](http://kicad-pcb.org/libraries/klc/G1.1/) doesn't mention pin names but I'm not sure if ' is a good idea.

**Comment by poeschlr** [comment]
@chschlue Pin names are only used to communicate to the reader of a schematic. So they can use any character supported by kicad. And it is a good idea to have them agree with the datasheet.

The reason asset names are restricted is because different operating systems have different restrictions for file names and it is not yet clear if the symbols will eventually end up as one symbol per file like the footprints.

---

@lorem-ipsum looks good, thanks

**Comment by chschlue** [comment]
@poeschlr If file name restrictions are the only reason then arbitrary characters in the description field should also be ok, right?

**Comment by poeschlr** [comment]
Maybe @evanshultz can say more about it as i am not really experienced on the symbol side (I practically worked only on footprints the last few years.)
I at least am not aware of any rule restricting characters for description fields. (I am however not sure if kicad supports the full utf character set. But it should be quite obvious if we encounter one that does not work.)

**Comment by evanshultz** [comment]
As @poeschlr said, we should stick with the minimal characters in KLC for best compatibility. We know other characters render fine in some OSes but KiCad runs on a lot of systems and can change. And regression testing of character set may not be done. In addition, changing character handling "under the hood" was actually being discussed recently so you never know...

That all being said, I think we have some Greek letters and probably some other stuff in symbol descriptions throughout the library. I pinged the dev mailing list to ask if they have any official guidance on the allowable character set to see if G1.1 can be expanded.

**Comment by chschlue** [comment]
@poeschlr @evanshultz https://github.com/KiCad/kicad-website/issues/431

**Pull request merged**
