### PR TITLE
Add TI LM25085MM and LM25085MY Buck controllers

### PR DESCRIPTION
**Pull request by strombom**
2V Constant On-Time PFET Buck Switching Controller
http://www.ti.com/lit/ds/symlink/lm25085.pdf

image

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by strombom** [comment]
I think the tests failed because the EESchema-LIBRARY Version 2.3 was increased to 2.4 and many changes was made to the lib file so that all symbols were reevaluated. Should I try to revert to version 2.3 and paste my changes there or is there any other way to pass the tests?

**Comment by poeschlr** [comment]
Did you close this because you did not get a reaction fast enough or was there a different problem?

Regarding the many reported errors when saving the lib in a different kicad version: This is a known problem. Sadly different versions of kicad use different line ordering in their lib output. (Even if the lib file version is the same.)
It is allowed to contribute to the lib in any file format version as long as the contribution does not contain invalid files (and follows KLC)
The danger is by going form 2.4 back to 2.3. (If done by kicad this results in an empty dcm file. This is another known problem.)

If you really only want your component checked by travis you can use a text editor to insert it into the files. (But this is kind of dangerous.)

**Comment by strombom** [comment]
Yes I'm just learning git. I think I'll create a new branch for each component. And use 2.3 file format this time so that there is only a minimal difference in the commit.

**Comment by strombom** [comment]
Many regulators in the library have the power in and out pins on left/right instead of on the top as stated in KLC.

Example:
image

I tried to follow KLC and put them on top:
image

What is preferable?

On all datasheets the power pins are on left/right...

**Comment by poeschlr** [comment]
The KLC is not written to encompass all parts. (We also do not list all known exceptions in there as it will make the KLC unreadable)

I think sometime in the past it was decided that regulators do not need to follow the "power pins only on top/bottom" rule.
Maybe @jkriege2 does remember more.

**Comment by jkriege2** [comment]
For regulators we often accept power-pins on the left/right as it is often the "natural"/commonly used pin-layout (especially for e.g. 3-pin linear regulators) ... in the end they can be thought of as power-converters as compared to usual components that are more like power-sinks.

Keep in mind that exceptions to KLC can be allowed if there is a good reason for them! + our check scripts are naturally not always right

**Pull request closed without merging**
