### PR TITLE
Add TWELITE SMD/DIP IEEE802.15.4 breakout module

### PR DESCRIPTION
**Pull request by true-nature**
Added TWELITE SMD/DIP (NXP JN5164/5169 IEEE802.15.4 breakout module)

TWELITE 
Datasheet: [https://www.mono-wireless.com/jp/products/TWE-LITE/MW-PDS-TWELITE-JP.pdf](https://www.mono-wireless.com/jp/products/TWE-LITE/MW-PDS-TWELITE-JP.pdf) (Japanese only)
Pin assign table is page 9.
2nd column is IO name of JN516x, the last column is IO name of std. application.

pin assign figure of std. application: [https://www.mono-wireless.com/jp/products/TWE-LITE/TWE-Lite-standard-pin.png](https://www.mono-wireless.com/jp/products/TWE-LITE/TWE-Lite-standard-pin.png)
[Footprint PR(448)](https://github.com/KiCad/kicad-footprints/pull/448), [merged ](https://github.com/KiCad/kicad-footprints/commit/a3e6b5f5ac4e78fc90e13b3bcfbee27384d5c9cf)

Screenshot:
twelite
twelite-desc
twelite-filter

TWELITE_DIP
Datasheet: [https://www.mono-wireless.com/jp/products/TWE-Lite-DIP/MW-PDS-TWELITEDIP-JP.pdf](https://www.mono-wireless.com/jp/products/TWE-Lite-DIP/MW-PDS-TWELITEDIP-JP.pdf) (Japanese only)
Pin assign table is page 8.
2nd column is IO name of JN516x, the last column is IO name of std. application.

Screenshot:
twelite_dip
twelite_dip-desc
twelite_dip-filter

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
My Japanese is sort of little rusty but I can say at least this

Try shorten the pins a little, they are little to long.

On symbol TWELITE, place the NC pin in such way that the pin end (the little x) is on the symbols outline.

I also guess that people want you to stack the GND pins, unless there is a specific reason for them to be separated, such as that each pin should have one capacitor connected to them.

You could change the description for the module from 
NXP JN5164/JN5169 breakout module
NXP JN5164/JN5169 breakout module
to
NXP JN5164/JN5169 breakout module, SMD
NXP JN5164/JN5169 breakout module, DIP

**Comment by true-nature** [comment]
@Misca1234 
Thank you for advice.
- Changed descriptions
- Shortened all pins
- Fixed position of the NC pin
- Stacked the GND pins and changed visibility
twelite

JN516x on TWELITE is a Wireless Microcontroller and it can be an I2C master or slave.
[Data Sheet: JN516x](https://www.nxp.com/docs/en/data-sheet/JN516X.pdf)
TWELITE is shipped from manufacturer([MONO-WIRELESS](https://mono-wireless.com/j)) including their standard application firmware in the flash memory. MONO-WIRELESS's standard application acts as an I2C master and read the values from sensor devices connected to I2C bus.
MONO-WIRELESS is providing SDK and source codes from web site. We can change the firmware for purpose by ourselves.

**Comment by Misca1234** [comment]
@true-nature 
Hi
Are you sure that TWE-L-DP-W is using a standard DIP-28_W15.24mm?
If you look at page 6 in https://www.mono-wireless.com/jp/products/TWE-Lite-DIP/MW-PDS-TWELITEDIP-JP.pdf

it seems that there is extra pins VCC, GND, RXT, RST, PRG, TXT?
(they are not visible from the side)

**Comment by true-nature** [comment]
These five contacts are located on the module only for the dedicated ISP writer (TWELITE R). 
Since they do not appear in the circuit diagram, they are not included in the symbol.

[TWELITE R user's manual](https://mono-wireless.com/jp/products/TWE-LITE-R/TWE-Lite-R_manual_v004.pdf) (Japanese only)
[usage example of the ISP contacts](https://mono-wireless.com/jp/products/TWE-LITE-R/exampleC.png)

**Comment by Misca1234** [comment]
All looks good

**Comment by true-nature** [comment]
Thank you for checking and advices.

**Pull request merged**
