### PR TITLE
Add MS5525DSO Pressure-Sensor

### PR DESCRIPTION
**Pull request by cp-aquila**
Add MS5525DSO Pressure-Sensor

Datasheet: https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=MS5525DSO&DocType=DS&DocLang=English
Footprint-PR: https://github.com/KiCad/kicad-footprints/pull/1743
grafik

This device has lots of different styles on how to connect tubes, I added all of them as footprint-filters, even though so far only one style exists as footprint.

I am not sure if I should stack the SOUT+ SOUT- and SGND pins. They need to be connected externally, its a two die device, they are not bonded internally:
grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @cp-aquila,

Your symbol looks good. I have a note about it and a question:

- Why have you named -SIN pins as SGND? I would call them as -SIN to match the name of the datasheet, but I think you have a reason for not doing so.

> I am not sure if I should stack the SOUT+ SOUT- and SGND pins.

I would keep all pins under the control of the designer so that both devices can be used separately (although unlikely). I believe that would make sense do not stack any pins here, including SUPPLY+. This is just a suggestion, I'm ready to merge anyway.

**Comment by cp-aquila** [comment]
> 
> I would keep all pins under the control of the designer so that both devices can be used separately (although unlikely). I believe that would make sense do not stack any pins here, including SUPPLY+. This is just a suggestion, and I'm ready to get this merged anyway.

That is a good thought.
I did unstack the `Supply+` pins. The names of `SGND` were just wrong, I did rename them to `SOUT-`.

While thinking about this the idea of making this into two units, one for the sensor and one for the controller came up. That would solve the pin-stacking problem and also clearly show that its two chips in one package.
But I think that is overkill and no added value to the designer. WDYT?

**Comment by cp-aquila** [comment]
@gmsotavio Friendly ping. Do you have time to give this and the footprint another look?

**Comment by myfreescalewebpage** [comment]
@cp-aquila I will do the review now:

- [ ] Name of pin 1 and 3 is "SIN-" and I suggest to stack them
- [ ] I suggest to stack pin 2 and 4
- [ ] Name of pin 7 should be "SCLK/SCL"
- [ ] Chip Select pin is usually below the other SPI pins. I suggest the following top to bottom order: SDO, SDI, SCLK and CSB
- [ ] You can stack pin 11 and 13
- [ ] You can stack pin 12 and 14

Joel

**Comment by myfreescalewebpage** [comment]
- [ ] You can move the SOUT/SIN pin block by 100mil to they are vertically centered

**Comment by cp-aquila** [comment]
Done. Sorry, that was a stupid mistake.

**Comment by myfreescalewebpage** [comment]
No problem.
I prefer waiting the footprint before merging the symbol for this part.
Joel

**Comment by myfreescalewebpage** [comment]
Merging the symbol too. Thanks @cp-aquila

**Pull request merged**
