### PR TITLE
Adding JK0654219NL

### PR DESCRIPTION
**Pull request by ki5libs**
Adding JK0654219NL
[Datasheet](https://media.digikey.com/pdf/Data%20Sheets/Pulse%20PDFs/JK%20Series.pdf#page=4)

JK0654219NL

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/1886)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @ki5libs,

Some notes about your symbol.

- [ ] Symbol body must have a line width of 10mil (0.254mm), as per KLC S3.3 (http://kicad-pcb.org/libraries/klc/S3.3/).
- [ ] It is not required, but preferred value for pin name position offset is 20mil, as per KLC S3.6 (http://kicad-pcb.org/libraries/klc/S3.6/). You have used 40 mil.
- [ ] According with KLC S4.1 (http://kicad-pcb.org/libraries/klc/S4.1/) the number of characters in the pin number determine a pin’s length. When there are two characters in the pin number then 100mil (2.54mm) long pins should be used. Please, change your pins length to 100 mil. You have used 200mil.

**Comment by ki5libs** [comment]
Hi @gmsotavio,

thanks for review. All changes you asked are done. This is changed symbol screenshot

JK0654219NL_new

**Comment by gmsotavio** [comment]
Great! Thank you very much. No m

**Comment by gmsotavio** [comment]
Closing and reopening to force Travis CI to run again.

**Comment by gmsotavio** [comment]
Great. Thank you for your contribution to KiCad libraries and for addressing my suggestions.

Regards,

**Pull request merged**
