### PR TITLE
Mpl3115a2

### PR DESCRIPTION
**Pull request by jneiva08**
Add NXP MPL3115A2

Datasheet:https://www.nxp.com/docs/en/data-sheet/MPL3115A2.pdf

Symbol:
mpl3115

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
- The description and keywords look like they may not have been updated (?).
- Please add the package to the end of the description.
- Oh! I hate that footprint name because it mentions a MPN but the package is generic. Would you be willing to do any renaming required to fix that? If not, it's OK and I will merge anyway.
- Pin 7 should be Bidirectional type.
- Section 13.6 of the datasheet shows that the INT* pins have a configurable output type. Should they be Open Collector to give the broadest compatibility since that would allow parallel pins if this is desired without triggering an ERC error? Output is certainly a valid type so my point is to ask you to think it though so we can decide that best choice. Thanks!

**Comment by jneiva08** [comment]
@evanshultz , all modification requested is already made.
The only doubt is about the name of the footprint, the used appears to be a little wider

**Comment by evanshultz** [comment]
Thanks!

The footprints in MPL3115A2 and MPL115A1 datasheets appear to be identical. Only the top cover is slightly different between them. So I would propose to keep it an NXP-specific footprint and remove the MPN (so `NXP_LGA-8_3x5mm_P1.25mm`). Then this symbol and MPL115A1 can get updated to the new footprint. That means the height difference wouldn't be reflected in the 3D model but there isn't one for the old footprint at https://github.com/KiCad/kicad-packages3D/tree/master/Package_LGA.3dshapes so this probably isn't a big deal (at least now). If you want to include height in the footprint (add `_H1.1mm`) that would be OK with me too. Or I'll merge it as is but I wanted to capture this for future consideration at least. Let me know.

**Comment by jneiva08** [comment]
The measurement in both footprints are the same, except in height the difference is 0.1mm.
The footprint was made by script., have moved mpn from the script and added _H1.2mm
Have added 1.2mm because the script as created for MPL115A1 it is 1.2mm.
Later will create both PR for the change and fix footprint for MPL115A1.

**Comment by jneiva08** [comment]
@evanshultz , have made all the changes, hope didn't miss anything.

PR of other changes:
Script: https://github.com/pointhi/kicad-footprint-generator/pull/347
Footprint: https://github.com/KiCad/kicad-footprints/pull/1570
MPL115A1 symbol: https://github.com/KiCad/kicad-symbols/pull/1806

**Comment by evanshultz** [comment]
Doesn't this need a 1.1mm tall footprint?

**Comment by evanshultz** [comment]
And thank you!

**Comment by jneiva08** [comment]
@evanshultz , did wrong to remove height from the filter and in MPL115A1?

**Comment by evanshultz** [comment]
It's not a big problem, but height will ensure the 3D model (through the footprint) is correct. Please add it here and then I can merge.

Please add height here and if you want to correct the MPL115A1 to put height in it's footprint filter to that would be great. Sorry for the hassle no matter what you decide.

**Comment by jneiva08** [comment]
@evanshultz @myfreescalewebpage 
Sorry to only make the changes now.

Did open new PR to change footprint filter to MPL115A1.
Link: https://github.com/KiCad/kicad-symbols/pull/1865

**Comment by evanshultz** [comment]
Unless I've misread the datasheet, this one should be 1.1mm tall.

**Comment by jneiva08** [comment]
The MPL115A1 is 1.2mm, and MPL3115A2 is 1.1mm
Since the footprint was for MPL115A1 renamed to have 1.2mm

**Comment by evanshultz** [comment]
Then should there be a 1.1mm tall version for this symbol? I may have misunderstood something. Did you have another plan?

**Comment by jneiva08** [comment]
well ... probably the right move should be add new PR for footprint with "_H1.1mm"
I think the script isn't merge, so can easily add the new footprint.

**Comment by evanshultz** [comment]
OK. That sounds good to me. Thank you for cleaning this all up!

**Comment by jneiva08** [comment]
@evanshultz Have done all modifications necessary. Hope it is all fine.

**Comment by jneiva08** [comment]
hi @evanshultz still need to make any modification?

**Comment by jneiva08** [comment]
hi @evanshultz still need to make any modification to close this PR?

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 I respond in place of @evanshultz, I have made another review for you and for me it's OK since the footprint has been merged. Merging the symbol. Joel

**Comment by jneiva08** [comment]
Thanks for having time to make second review

**Comment by myfreescalewebpage** [comment]
No worries!

**Pull request merged**
