### PR TITLE
Added MAX4820 and MAX4821 relay drivers from Maxim Integrated

### PR DESCRIPTION
**Pull request by amil109**
Added MAX4820 and MAX4821 relay drivers from Maxim Integrated. Based on DRV8860 symbol. SPICE model not updated.

https://datasheets.maximintegrated.com/en/ds/MAX4820-MAX4821.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ x] An example screenshot image is very helpful

MAX4821
MAX4820

- [ x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ NA] If there are matching footprint PRs, provide link(s) as appropriate
- [ ??] Check the output of the Travis automated check scripts - fix any errors as required
- [ NA] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @amil109 , thanks for contributing,

A few comments I have during my review:

MAX4820
- [ ] The name of the device should be "MAX4820xUP" for the TSSOP package version
- [ ] The description should ends with the package name: `8-Channel Serial Interface Low-Side Driver, TSSOP-20`
- [ ] The footprint is not correct, it has an expose pad
- [ ] The pin offset should be 20mil (see travis log)
- [ ] The style of pin RESET, SET and CS should be Line
- [ ] Name of pin 3 is `~RESET`
- [ ] Name of pin 4 is `~CS`
- [ ] Pin 8 should be invisible and move on the border outline of the symbol (see travis log)
- [ ] PGND pins should be stacked on GND according to the datasheet
- [ ] All OUTx pins are Open Collector
- [ ] COM should be Passive
- [ ] Name of pin 2 is `~SET`
- [ ] Expose pad (pin 21) should be added, stacked on GND
- [ ] The height of the symbol  can be reduced by 100mil

MAX4821
- [ ] The name of the device should be "MAX4821xUP" for the TSSOP package version
- [ ] The description should ends with the package name: `8-Channel Serial Interface Low-Side Driver, TSSOP-20`
- [ ] The footprint is not correct, it has an expose pad
- [ ] The pin offset should be 20mil (see travis log)
- [ ] The style of pin RESET, SET and CS should be Line
- [ ] Name of pin 3 is `~RESET`
- [ ] Name of pin 4 is `~CS`
- [ ] PGND pins should be stacked on GND according to the datasheet
- [ ] All OUTx pins are Open Collector
- [ ] COM should be Passive
- [ ] Name of pin 2 is `~SET`
- [ ] Expose pad (pin 21) should be added, stacked on GND
- [ ] The height of the symbol  can be reduced by 100mil

Cheers,
Joel

**Comment by amil109** [comment]
Hi Joel,

Thanks for the fast review!

I've made the changes requested, except I wasn't quite sure how to 'stack' the pins - do you mean just put them on top of one another on the symbol? Is there a convention for where I should put the names / numbers (please point me to an example and I'll copy it).

I left the PGNDs separate from GND as the functional diagram suggests they are separate, but indeed, in practice I can't imagine them being separate!

Cheers,

Andrew

**Comment by myfreescalewebpage** [comment]
I disagree with the selected footprint, the EP size is not correct I think (my reference is https://pdfserv.maximintegrated.com/package_dwgs/21-0108.PDF). If the right footprint does not exist in the library, you can submit it.

> I've made the changes requested, except I wasn't quite sure how to 'stack' the pins - do you mean just put them on top of one another on the symbol?

Yes. First pin Power Input, visible. The following are Passive, invisible. All with the same name (GND in this case).

> I left the PGNDs separate from GND as the functional diagram suggests they are separate, but indeed, in practice I can't imagine them being separate!

The datasheet explicitly indicates the EP / GND and PGND have to be connected together so it's why we ask to stack all of them.

Joel

**Comment by amil109** [comment]
Hi Joel,

Thank you for the info and your help! I've made those changes, and have a pull request for the updated footprint here: https://github.com/KiCad/kicad-footprints/pull/2227

The Travis script fails now because the footprint doesn't exist, which makes sense in this case.

Cheers,

Andrew

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Thanks @chschlue , closing and opening to refresh travis test

**Comment by myfreescalewebpage** [comment]
@amil109 thanks for the fixes. 3 comments not fixed at this moment.

For NC pin, this is the solution:

Capture

The visible GND pin should be Power Input. See travis log and my previous comment.

And for the description, just need to copy paste :)

**Comment by myfreescalewebpage** [comment]
@amil109 ping

**Comment by amil109** [comment]
Sorry for the delay - hopefully these updates cover the fixes needed.

Note that I changed _all_ the GND pins to power input, I hope that was correct? If not, I apologise - let me know which ones need to be passive, and I will change them right away. Travis checks pass now in any case.

Thanks!

**Comment by myfreescalewebpage** [comment]
Hello @amil109 
Thanks.
For GND pins it was correct before. You have now a travis error. Invisible GND pins should be Passive.
Joel

**Comment by amil109** [comment]
Hi @myfreescalewebpage , sorry... re-submitted now! Thank you for your patience and help with these!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
