### PR TITLE
Add Recom RAC20-xxDK Dual Output Parts

### PR DESCRIPTION
**Pull request by Werni2A**
[Datasheet](https://recom-power.com/pdf/Powerline_AC-DC/RAC20-K.pdf#page=6)

image

---

## :warning: Deprecation warning
In preparation for the KiCad v6 release this repository will be locked down on Sept 1, 2020. No new pull requests will be accepted. Existing pull requests can be worked on until Oct 1, 2020. Changes breaking v5.1 compatibility can be merged starting Sept 1, 2020.

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-symbols/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

We plan to convert the library to the new v6 S-expr format after it is imported to GitLab. That also means that old pull requests will need to be redone with the v6 format if they are not merged before then.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by Werni2A** [comment]
@myfreescalewebpage you merged the RAC-20 single output parts, this PR adds the remaining dual output parts of the series. Maybe you also want to take a look at this one. No pressure :)

**Comment by myfreescalewebpage** [comment]
I will take this, this is a great ddition

**Comment by myfreescalewebpage** [comment]
Can you solve the branch conflict now, the PR is opened

**Comment by Werni2A** [comment]
@myfreescalewebpage Not sure why it was closed but now the conflict should be fixed.

**Comment by myfreescalewebpage** [comment]
The repo is locked and all new PR are automatically closed.

**Comment by myfreescalewebpage** [comment]
About your symbol, only one comment:

- [ ] It's too large, please make the symbol the same width than the single output version

Joel

**Comment by Werni2A** [comment]
Is there some guideline according to the naming of the symbol pins in AC/DCs? E.g. should all symbols in the lib have the same name for output pins or should be exactly as in the datasheet? One of the symbols should be adjusted.

Btw. I reduced the symbol size.

image

**Comment by myfreescalewebpage** [comment]
> Is there some guideline according to the naming of the symbol pins in AC/DCs? E.g. should all symbols in the lib have the same name for output pins or should be exactly as in the datasheet?

Not related to converter only, all symbol should carefully follow the datasheet. Else this is a nice mess !!! We just ask people to copy/paste the names.

> One of the symbols should be adjusted.

Which one ?

**Comment by Werni2A** [comment]
Then I need to fix https://github.com/KiCad/kicad-symbols/pull/2692 you merged earlier and this PR. 

I will address this tomorrow afternoon.

Notes for myself:
- [ ] Change `AC(L)` to `VAC in (L)` and also for N wire
- [ ] Create another PR to fix single output naming of `+Vout` and `+Vout`

image

**Comment by myfreescalewebpage** [comment]
Ohhh good point.

For the first subject, we also do not create pin name too much long so here it is accepted to keep AC(L) and AC(N).
For the second subject, you're right, and I notice RAC01 series in the lib has the same problem. If you create a pull request ping me and I will review it. Else, this is not an important trouble.

Joel

Merging this PR now.

**Pull request merged**
