### PR TITLE
8devices carambola2

### PR DESCRIPTION
**Pull request by EpeR1**
I have create a Carambola2 symbol, documentation is here:
https://www.8devices.com/media/products/carambola2/downloads/carambola2-datasheet.pdf

## NOTE
* The GPIO 2/3/4/5 are in brackets, because they share lines with SPI, and SPI is connected with internal FLASH memory, so using them for GPIO applications, at runtime, is very difficult. 

* The official dataset is a bit tricky, because there is an inconsistency between page2 and page3. The list on page3 is wrong, ETH1 and ETH0 leds are swapped, the correct pinout is on page2.   
(I have piece of a board, and I tested.)

* The Carambola2's footprint is submitted here:
https://github.com/KiCad/kicad-footprints/pull/1739

* I wrote USB_D+, USB_D- instead of USB+, USB-, because they are USB data lines instead of USB Power lines.

*  UARTs are on left side, because  they are the control UARTs.

The module info from doc:
car2

The symbol, what I have created:

cara

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by EpeR1** [comment]
The footprint is provided in an additional pull-request:
https://github.com/KiCad/kicad-footprints/pull/1739

**Comment by EpeR1** [comment]
The footprint is provided via additional pull request:
https://github.com/KiCad/kicad-footprints/pull/1739

**Comment by myfreescalewebpage** [comment]
Hi @EpeR1 , thanks for contributing,

Nice device :)

A few comments I have during my review:

- [ ] Double space before "industrial" in the description, remove one.
- [ ] Footprint filter should be `Carambola2*` (no start at the beginning)
- [ ] For pin name, can you use only capital letters please. Also we usually do not indicate all functions because it makes very large symbol, for example you should remove "bootstrap" and parenthesis. The primary function is always near the border outline of the symbol.
- [ ] Name of pin 50 and 51 : "+3VD" is enought
- [ ] Name of pin 52 : "+2VD" is enought
- [ ] You should center positive power pins, Powr inputs on the left, power outputs on the right.
- [ ] You have to stack GND pins
- [ ] ANTENNA pins should be Passive

Will make a complete review after those changes.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@EpeR1 any news here ?

**Comment by EpeR1** [comment]
Updated - What do you think?
cr8

**Comment by myfreescalewebpage** [comment]
Thanks, great job !
Few remaining comments:

- [ ] Name of pin 2 should be `I2S_MICIN/SLIC_DATA_IN/GPIO_22`
- [ ] Ethernet Rx pin should be Input and Ethernet Tx pins should be Output
- [ ] Name of pin 16 should be `GPIO_4/SPI_MOSI`
- [ ] Name of pin 17 should be `GPIO_3/SPI_CLK`
- [ ] Name of pin 18 should be `GPIO_5/SPI_MISO`
- [ ] Name of pin 19 should be `GPIO_2/SPI_CS0`
- [ ] Name of pin 23 should be `GPIO_11/UART_RTS/I2S_MCK/JS/~SOFT_RESET~`
- [ ] You should group pins 23, 24, 43, 44
- [ ] Pin 23 is Output
- [ ] Name of pin 36 should be `LED5/GPIO_16`
- [ ] Name of pin 40 should be `LED1/GPIO_1`
- [ ] Pins 35 to 41 are all Bidirectional
- [ ] Name of pin 43 should be `GPIO_9/UART_RX/SPI_CS_1`
- [ ] Name of pin 44 should be `GPIO_10/UART_TX/SPI_CS_2`
- [ ] The width of the symbol is great but the height can be reduce again (200mil between each group of pins is great)

Joel

**Comment by EpeR1** [comment]
Updated.

About pin 16,17,18,19:
They are connected to internal FLASH memory, by factory. 
(Datasheet page 5.) 
Using them for gpio is difficult, the primary function is SPI, so I let the "SPI_"  names near  the symbol border.
Or should exchange them ?

aaa

**Comment by myfreescalewebpage** [comment]
Good point about the SPI pins. I agree to keep this version.
No more comment to do on the symbol, I think the design is great. Don't know why travis complains, I have double checked and this is correct.
Just need now to wait the footprint before merging.
Joel

**Comment by EpeR1** [comment]
OK, thank you!
Travis complained, because I did a little mistake:  I forgot to set Invisible, stacked pins to passive. It is correct now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging following integration of fp, travis fully happy now

**Pull request merged**
