### PR TITLE
Adding ADuM1400, ADuM1401 and ADuM1402

### PR DESCRIPTION
**Pull request by cedricboudinet**
Hello

I added some components for ADuM140x (I duplicated the symbol from ADuM141x and added some corrections).

Regards

### CODE REVIEW

**Comment by chschlue** [comment]
Hello and welcome.
Thanks for your first contribution, but please do what the PR template says instead of just overwriting it, it really makes reviews easier.

--- 

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

**Comment by cedricboudinet** [comment]
Hello,
Here are more informations:

Datasheet : https://www.analog.com/media/en/technical-documentation/data-sheet/ADUM1400_1401_1402.pdf

Example screenshot:

ADUM140x


All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)
 
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:
   * [x]  Provide a URL to a datasheet for the symbol(s) you are contributing
   * [x]  An example screenshot image is very helpful

   * [x]  Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
       
      * A new fitting footprint must be submitted if the library does not yet contain one. 
   * [ ]  If there are matching footprint PRs, provide link(s) as appropriate 
   * [x]  Check the output of the Travis automated check scripts - fix any errors as required
   * [ ]  Give a reason behind any intentional library convention rule violation.

**Comment by myfreescalewebpage** [comment]
Hi @cedricboudinet , thanks for contributing,

A few comments I have during my review:

For all symbols:
- [ ] The name of the symbols should be "ADuM1400xRW" "ADuM1401xRW" and "ADuM1402xRW"
- [ ] Add a space after commas in the descriptions
- [ ] Package in the description should be SOIC-16 not SO-16
- [ ] You should stack GND1 pins
- [ ] You should stack GND2 pins
- [ ] The height of the symbol can be reduce a bit following pin stacking
- [ ] We represent the isolation barrier with a single dash line now

ADuM1400xRW
- [ ] NC pin should be on the border outline of the symbol

Cheers,
Joel

**Comment by cedricboudinet** [comment]
Dear Joel,

I am not sure to understand what you mean by "You should stack GND1 pins". Do you mean that I should move them up so that they are closer to the VE1 pin or shoud I move pin 2 between pin 1 and pin 3?

Bests
Cedric

**Comment by myfreescalewebpage** [comment]
No.
They should be at the same place. They are all connected together. See for example GND pins of the "VisionSOM-6UL" symbol in the lib.
Joel

**Comment by cedricboudinet** [comment]
Hi @myfreescalewebpage 
I just pushed the modifications you asked. Do you want me to add a new screenshot?
Bests

**Comment by myfreescalewebpage** [comment]
No need of new screenshot, this is useful before starting the review at the beginning. Then it's usually ok, except if important modifications are done.

You are not totally correct for the pin stacking, see travis result. To fix it: the pins which are not visible should be Passive.

**Comment by myfreescalewebpage** [comment]
Thanks, travis and myself are happy now !
Merging.

**Pull request merged**
