### PR TITLE
Add NB3N551MN.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://www.onsemi.com/pub/Collateral/NB3N551-D.PDF

image

footprint pr: https://github.com/KiCad/kicad-footprints/pull/1286

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A comment I have during my review:

- [ ] Description should ends with package name, add `, DFN-8` at the end

Else, just need to wait for the footprint.

Cheers,
Joel

**Comment by matthuszagh** [comment]
@myfreescalewebpage done.

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment on the symbol. Waiting for the footprint now before merging.

**Comment by matthuszagh** [comment]
Conflicts fixed here too.

**Comment by myfreescalewebpage** [comment]
Thanks @matthuszagh however, need to update the footprint here !

Cheers,
Joel

**Comment by matthuszagh** [comment]
Should now be fixed. Let me know if any further issues.

**Comment by myfreescalewebpage** [comment]
@matthuszagh ok for me here, merging !
Thanks
Joel

**Pull request merged**
