### PR TITLE
Coilcraft CST symbols

### PR DESCRIPTION
**Pull request by evanshultz**
Symbols that match with https://github.com/KiCad/kicad-footprints/pull/588.

Datasheets:
- https://www.coilcraft.com/pdfs/cst.pdf
- https://www.coilcraft.com/pdfs/cst2010.pdf

I prefer split symbols because it allows placing the halves of the transformer in different places on the schematic. But some may not prefer that and KiCad doesn't check that all units are placed so I included single-unit symbols as well. Previous discussion at https://github.com/KiCad/kicad-library/pull/837. Any feedback of thoughts about how these symbols should look or be built?

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
By the risk of hijacking this thread, of curiosity, why do you prefer splitting the symbols, instead of using labels (https://github.com/KiCad/kicad-library/pull/837 was closed for comments), labels is your friend to get ride of "stray lines" that clutter the scheme (like the example you gave of page 27 of the [UCC2893 datasheet](http://www.ti.com/lit/ds/symlink/ucc2893.pdf) ) ?

**Comment by evanshultz** [comment]
So... leave this in limbo or merge it and then update later if/when we ever find a better name?

`MultiUnit` doesn't communicate any better than `Split` to me and it's longer. That's why I chose these names. And it got a good response at https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-396073808. @Ratfink

**Comment by poeschlr** [comment]
If we use Split then it should at least be capitalized normally not all caps.

**Comment by evanshultz** [comment]
All are done.

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
