### PR TITLE
Add Infineon GaN FET symbols

### PR DESCRIPTION
**Pull request by evanshultz**
All parts are at https://www.infineon.com/cms/en/product/power/wide-band-gap-semiconductors-sic-gan/gallium-nitride-gan/:
- [IGO60R070D1](https://www.infineon.com/dgdl/Infineon-IGO60R070D1-DataSheet-v02_01-EN.pdf?fileId=5546d46265f064ff016685f053216514)
- [IGOT60R070D1](https://www.infineon.com/dgdl/Infineon-IGOT60R070D1-DataSheet-v02_11-EN.pdf?fileId=5546d46265f064ff016685fa65066523)
- [IGT60R070D1](https://www.infineon.com/dgdl/Infineon-IGT60R070D1-DataSheet-v02_01-EN.pdf?fileId=5546d46265f064ff016686028dd56526)
- [IGT60R190D1S](https://www.infineon.com/dgdl/Infineon-IGT60R190D1S-DataSheet-v03_01-EN.pdf?fileId=5546d46265f064ff016685fa29796520)
- [IGT40R070D1 E8220](https://www.infineon.com/dgdl/Infineon-IGT40R070D1%20E8220-DataSheet-v02_00-EN.pdf?fileId=5546d4626afcd350016b269dd8f34ec4)
- [IGLD60R070D1](https://www.infineon.com/dgdl/Infineon-IGLD60R070D1-DataSheet-v02_00-EN.pdf?fileId=5546d46265f064ff016685f03f056511)
- [IGLD60R190D1](https://www.infineon.com/dgdl/Infineon-IGLD60R190D1-DataSheet-v02_00-EN.pdf?fileId=5546d46269e1c019016a6d78ff5e2aba)

And they all share the same symbol:
image

I've used pin names instead of numbers as has been agreed upon for symbols with standardized pin names. This makes it much easier to copy the symbol and make it work since the pin numbers can always stay the same. You can see what a bigger pain it would be to figure out the pin numbers for all the packages used by these symbols otherwise.

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1680

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Since there is nobody assigned and no review, I added a new part just released.

**Comment by myfreescalewebpage** [comment]
Hello @evanshultz 

For all devices of this PRs, I disagree with the drawing of the symbol. You selected a mosfet with a diode, why ?

Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Because I copied the existing FET symbol and missed that. Thanks for noting this error. Here is one updated symbol that I will propagate to all symbols in this PR if you agree:
image

I also changed the pin names to numbers and added the pins that are now needed as requested at https://github.com/KiCad/kicad-footprints/pull/1680.

**Comment by myfreescalewebpage** [comment]
Thanks, yes clearly it's better symbol for these devices. You can make the other modifications.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Thanks! That should take care of the symbols so I think we will just be waiting on footprints.

**Comment by myfreescalewebpage** [comment]
Yes exactly, just need to wait the footprint now.

**Comment by poeschlr** [comment]
The footprints have been merged but this requires a rebase (or merge whatever you prefer)

**Comment by evanshultz** [comment]
@myfreescalewebpage 
I think this is ready now.

**Comment by myfreescalewebpage** [comment]
@evanshultz sorry for the delay, yes this can be merge now :)

**Pull request merged**
