### PR TITLE
Pwr management

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR brings across all the symbols from the old **Power_Management** library.

No new libs created, symbols fit into existing ones.

### CODE REVIEW

**Comment by jkriege2** [comment]
Please replace the word Pitch in the FPFilters and footprints ...

cu
JAN

**Comment by SchrodingersGat** [comment]
Done!

**Comment by jkriege2** [comment]
could you also fix the other footprint issues:
- LTC4357DCB, LTC4359-DCB, LTC4365TS8, RT9701, PM8834* have only 1 fpfilter, but no footprint set
- fix LTC4007 footprint+fiilter
- fix LM5051, LT1641-1, MIC2026-1BN fpfilter

**Comment by poeschlr** [comment]
I merge this for now. The suggestions by jan will be documented in an issue.

**Pull request merged**
