### PR TITLE
Transistor_FET: Add Diodes Inc. N-Channel SOT-23 MOSFETs

### PR DESCRIPTION
**Pull request by diegoherranz**
Semi-scripted

By filtering https://www.diodes.com/products/discrete/mosfets/mosfet-master-table/export/mosfet-master-table.xlsx and processing it with a quick and dirty script. All of them added as aliases.

Selected:
 - N-channel
 - SOT23 (I manually checked that they're all same pinout)
 - Without ESD gate protection so that they can be aliases of BSS138
 - Automotive qualified variants (with a Q suffix) excluded (even if there's a separate datasheet). I guess this is somewhat similar to temperature variants which we don't alias?
- Excluded parts already in the library (obviously)

After filtering the spreadsheet (`diodes_nfets_sot23.ods`), datasheet column replaced by a plain text URL (was a hyperlink) and saved as CSV.

The CSV gets processed by `fet_aliases_gen.py` which prints the CMPs to be added to the `.dcm` file and the list of part numbers to add to the `.lib`.

I pasted the aliases on the `.lib` and reordered manually (alphabetically).

I pasted the CMPs at the end of the .dcm and opened and saved from within KiCad so that they get ordered properly.

Note: Some existant components were not in the right order and have been reordered too.

Datasheets and script used: [fets_spreadsheets_script.zip](https://github.com/KiCad/kicad-symbols/files/2659589/fets_spreadsheets_script.zip)

Thanks!

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful (Not applicable)
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @diegoherranz, thanks for this great contribution

Just to summarize, following symbols added by this PR, with my comment when issue detected:
- 2N7002E
- 2N7002H
- BS170F
- BS870
- BSN20
- BSS123
- BSS127S
- DMG2302U
- DMG3402L
- DMG3404L
- DMG3406L
- DMG3414U
- DMG3418L
- DMN10H220L
- DMN10H700S
- DMN13H750S
- DMN2041L: datasheet link broken, have you got another one ?
- DMN2050L
- DMN2056U
- DMN2058U
- DMN2075U
- DMN2230U
- DMN24H11DS
- DMN24H3D5L
- DMN3042L
- DMN3051L
- DMN30H4D0L
- DMN3110S: wrong current value, should be 3.3A
- DMN3150L: wrong datasheet link (should be https://www.diodes.com/assets/Datasheets/ds31126.pdf), wrong current value, should be 3.8A
- DMN3300U
- DMN3404L: wrong current value, should be 5.8A
- DMN6075S: wrong current value, should be 2.5A
- DMN6140L
- DMN67D7L
- DMN67D8L
- VN10LF
- ZVN3306F
- ZVN3310F
- ZVN3320F
- ZVN4106F
- ZXM61N02F
- ZXM61N03F
- ZXMN10A07F: wrong current value, should be 0.76A
- ZXMN2A01F: wrong current value, should be 2.2A
- ZXMN2A14F: no current value, should be 4.1A
- ZXMN2B01F: wrong current value, should be 2.4A
- ZXMN2B14FH: wrong current value, should be 4.3A
- ZXMN2F30FH: wrong current value, should be 4.9A
- ZXMN2F34FH: wrong current value, should be 4.0A
- ZXMN3A01F
- ZXMN3A14F: wrong current value, should be 3.2A
- ZXMN3B01F
- ZXMN3B14F
- ZXMN3F30FH
- ZXMN6A07F

Symbols re-ordered in the lib:
- IPD50R380CE
- IPD50R3K0CE
- PGA26E07BA
- PGA26E19BA
- Si7336ADP

Cheers,
Joel

**Comment by diegoherranz** [comment]
Thanks for the review.
Have you checked the specs manually? That's a big effort!
I trusted the spreadsheet provided by Diodes Inc., but it seems incorrect??
For example:
> DMN3110S: wrong current value, should be 3.3A

The spreadsheet incorrectly says 5.5A!

I'll fix them manually. And possibly report all this to Diodes Inc. for them to fix the spreadsheet.

**Comment by myfreescalewebpage** [comment]
> Have you checked the specs manually? That's a big effort!

Yes of course! Checked each part added/moved in the git diff, opened each new part in kicad, open doc from kicad interface (to check link are not broken) and check datasheet for each of them. Finally checked moved parts in the lib have not been modified accidentally.

Joel

**Comment by diegoherranz** [comment]
Thanks for the deep review. I wrongly assumed that the spreadsheet provided by Diodes Inc. would be correct!

It should all be fixed. See the commits messages for more info.

Regarding the following comment, I think that the datasheet link was correct already?
> DMN3150L: wrong datasheet link (should be https://www.diodes.com/assets/Datasheets/ds31126.pdf), wrong current value, should be 3.8A

Thanks!

**Comment by myfreescalewebpage** [comment]
>  I wrongly assumed that the spreadsheet provided by Diodes Inc. would be correct!

:)

> It should all be fixed. See the commits messages for more info. Regarding the following comment, I think that the datasheet link was correct already?

Checked your last commits, okay for me, no more comment. Probably I have not looked correctly the datasheet at this moment, verified again, it's okay for me too.

Merging, thanks a lot for all these devices !

Joel

**Pull request merged**
