### PR TITLE
add Mini-Circuits SYPD-2 phase detector

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/SYPD-2.pdf
https://ww2.minicircuits.com/pdfs/SYPD-1+.pdf
https://ww2.minicircuits.com/pdfs/SYPD-52+.pdf

sypd-2

Footprint: https://github.com/KiCad/kicad-footprints/pull/1133

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin 

Same comments already fixed at #1208 

Waiting for the footprint.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@aewallin following the integration of the footprint, footprint and footprint filter to be updated here.
No other comment on the PR.

**Comment by aewallin** [comment]
I'm suggesting the case-name in the fp-filter, the issue with the fp-filter in the ones already merged and the plain-footprints is described here: https://github.com/KiCad/kicad-footprints/issues/1308

**Comment by myfreescalewebpage** [comment]
No more comment here, merging.

**Pull request merged**
