### PR TITLE
Multiple Converter_ACDC fixes

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
- Fixed pin offsets
- Add IRM-02-xxS for SMD devices
- Filter fix

imagen

Related to:
https://github.com/KiCad/kicad-footprints/issues/749

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @antoniovazquezblanco  can you fix the conflicts here? Thanks

**Comment by antoniovazquezblanco** [comment]
I will soon. Just getting back from holidays. After work planning gets finished I will get back to KiCad ;)

**Comment by antoniovazquezblanco** [comment]
@SchrodingersGat Done!

**Comment by SchrodingersGat** [comment]
Thanks @antoniovazquezblanco

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
