### PR TITLE
Added LTC6909 timer IC

### PR DESCRIPTION
**Pull request by SchrodingersGat**
www.analog.com/media/en/technical-documentation/data-sheets/6909fa.pdf

image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Bump @evanshultz

**Comment by evanshultz** [comment]
- Pins 1 and 3 have names close together. Can you move left side pins down a bit?
- SET connects to V+A through a resistor while all other left side pins are V+D. Perhaps move SET to the top so that  can be "inside" the pins that connect to V+D.
- All OUT* pins are tri-state.

**Comment by SchrodingersGat** [comment]
image

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
