### PR TITLE
Add LP38512 series

### PR DESCRIPTION
**Pull request by evanshultz**
http://www.ti.com/lit/ds/symlink/lp38512.pdf
image
image

http://www.ti.com/lit/ds/symlink/lp38512-adj.pdf
image
image

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1996

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aewallin** [comment]
TAB/DAP internally connected to pin3 (GND) - so should be stacked with pin3?

**Comment by myfreescalewebpage** [comment]
@evanshultz can you update this to solve the conflict, I can review the symbol then.
Joel

**Comment by myfreescalewebpage** [comment]
@evanshultz ping

**Comment by myfreescalewebpage** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
@myfreescalewebpage 
My apologies. I've missed this. I'll take care of it today.

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Fixed. Sorry for the churn as I did some clean-up of my own mistakes after fixing the major part of the branch conflict.

**Comment by myfreescalewebpage** [comment]
@evanshultz no worries. Several comments:

LP38512MR-ADJ
- [ ] Position offset should be 20mil
- [ ] Package in the description should be "Texas HTSOP-8"

LP38512TJ-1.8
- [ ] Position offset should be 20mil
- [ ] On this package the DAP is physically connected to GND and datasheet ask the user to connect the DAP to GND. I sugegst to stack pin 6 with GND

LP38512TJ-ADJ
- [ ] Position offset should be 20mil
- [ ] On this package the DAP is physically connected to GND and datasheet ask the user to connect the DAP to GND. I sugegst to stack pin 6 with GND

LP38512TS-1.8
- [ ] Position offset should be 20mil
- [ ] I think "TO-263" is enough in the description
- [ ] On this package the DAP is physically connected to GND and datasheet ask the user to connect the DAP to GND. I sugegst to stack pin 6 with GND

Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Done. Thanks for looking!

To give a bit more room for text, our 'standard' linear regulator symbol used a 10mil pin name offset. I thought @jkriege2 reworked the linear regulators and we found that this fit better, but I can't find a PR for that. Anyway, I see ~150 symbols with 10mil in this lib and about half as many with 20mil. This is similar to using 5mil on triangle opamps so the text doesn't crash and gives more room around it. Since this may not be documented anywhere I can change it, but 10mil with input on L and output on R seems the de facto style for these simple linear regulator symbols.

For the TS-1.8 symbol I moved those other package names to the keywords. I think they are common names for this package and it may be helpful if a user can find regulators matching their preferred package by searching for all common names for this package. If you don't like this I can make other changes.

**Comment by myfreescalewebpage** [comment]
Thanks for the update and also for the comments, agree with all of them. Will try to remember the offset rule for linear regulators too :)

**Pull request merged**
