### PR TITLE
Add RAK Wireless RAK4200 LoRa module schematic symbol

### PR DESCRIPTION
**Pull request by alnunez**
RAK Wireless RAK4200 LoRa module: 

Datasheet: [https://downloads.rakwireless.com/LoRa/RAK4200/Hardware-Specification
/RAK4200_Module_Specifications_V1.4.pdf](https://downloads.rakwireless.com/LoRa/RAK4200/Hardware-Specification/RAK4200_Module_Specifications_V1.4.pdf)

Footprint PR# [2356](https://github.com/KiCad/kicad-footprints/pull/2356)
RAK4200-SCH

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @alnunez , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint should be `RF_Module:RAK4200`
- [ ] Footprint filter should be `RAK4200*` only, remove the other one
- [ ] Main function of the GPIo pin should be near to the border. The name of pin 9 should be `I2C_SCL/PB6`. The name of pin 10 should be `I2C_SDA/PB7`
- [ ] RF should be Passive
- [ ] Name of pin 20 should be `VDD`
- [ ] Name of pin 18 should be `~MCU_NRESET`
- [ ] You should stack GND pins. This will permit to reduce a little bit the width of the symbol.

Cheers,
Joel

**Comment by alnunez** [comment]
> Hi @alnunez , thanks for contributing,
> 
> A few comments I have during my review:
> 
> * [ ]  Footprint should be `RF_Module:RAK4200`
> * [ ]  Footprint filter should be `RAK4200*` only, remove the other one
> * [ ]  Main function of the GPIo pin should be near to the border. The name of pin 9 should be `I2C_SCL/PB6`. The name of pin 10 should be `I2C_SDA/PB7`
> * [ ]  RF should be Passive
> * [ ]  Name of pin 20 should be `VDD`
> * [ ]  Name of pin 18 should be `~MCU_NRESET`
> * [ ]  You should stack GND pins. This will permit to reduce a little bit the width of the symbol.
> 
> Cheers,
> Joel

Done all changes. Travis failed after adding the footprint field

**Comment by myfreescalewebpage** [comment]
@alnunez thanks for the changes. No more comment to do, the travis error is normal at this time, just need to wait the footprint now.

Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Fp merged, merging the symbol.

**Pull request merged**
