### PR TITLE
Added RCLAMP3328P

### PR DESCRIPTION
**Pull request by SchrodingersGat**
8-way ESD clamping diode in UDFN-9 package

Datasheet: https://media.digikey.com/pdf/Data%20Sheets/Semtech%20PDFs/RCLAMP3328P.pdf

image

image

Footprint: https://github.com/KiCad/kicad-footprints/pull/1572

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Added some other aliases based on compatible parts available on DigiKey

**Comment by SchrodingersGat** [comment]
Note the only KLC error is because the footprint has not yet been merged

**Comment by evanshultz** [comment]
- Remove "package" from the end of the description.
- Should the upper pins be named K1, K2, etc.?

**Comment by SchrodingersGat** [comment]
Changes made as requested

**Comment by evanshultz** [comment]
Thanks!

`RCLAMP3328P` lost the package name in addition to the word `package`.

**Comment by evanshultz** [comment]
Looks good. Thanks!

**Pull request merged**
