### PR TITLE
Fix #41: Sensor_MultiFunction should be merged into Sensor

### LINKED ISSUE #41: Sensor_MultiFunction should be merged into Sensor
The symbols in Symbol_MultiFunction should be merged into Sensor.lib

### PR DESCRIPTION
**Pull request by stephf0716**
Fix #41: Sensor_MultiFunction should be merged into Sensor

### CODE REVIEW

**Comment by jkriege2** [comment]
It seems like you delete several symbol descriptions from Sensors.dcm. Maybe this is due to you using a v4-KiCAD, but the lib is already in the v5/nightly-format. Please regenerate the missing info.

Also you should delete Sensor_MultiFunction from https://github.com/KiCad/kicad-symbols/blob/master/sym-lib-table

**Comment by jkriege2** [comment]
Could you please fix the merge conficts?

**Comment by stephf0716** [comment]
ok, should be fine to merge now

**Comment by jkriege2** [comment]
THanks,
JAN

**Pull request merged**
