### PR TITLE
Added MPR121QR2

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://resurgentsemi.com/wp-content/uploads/2018/09/MPR121_rev5-Resurgent.pdf?d453f8&d453f8
Footprint: https://github.com/KiCad/kicad-footprints/pull/2185
Captura de pantalla de 2020-03-30 14-53-39

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)
Captura de pantalla de 2020-03-30 14-54-15

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] It's probably better to move IRQ near SDA/SCL and it will permit to reduce the height of the symbol
- [ ] I suggest to cross description of pin 12 to 19 to have "ELEx" near to the border (to have all "ELEx" near to the border)
- [ ] IRQ should be Open Collector
- [ ] Probably it's better to make more space between ADDR and REXT (no reason to group them)

Cheers,
Joel

**Comment by cnieves1** [comment]
Done:
Captura de pantalla de 2020-04-05 17-35-10

**Comment by myfreescalewebpage** [comment]
It's better to align VSS with VDD and it is possible without other modifications:

Capture2

**Comment by cnieves1** [comment]
Done:
Captura de pantalla de 2020-04-06 00-09-18

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Merging following integration of the fp

**Pull request merged**
