### PR TITLE
Added Diodes SD103ATW 3xSchottky array SOT-363 SMD.

### PR DESCRIPTION
**Pull request by cederom**
Here goes the new symbol of "SURFACE MOUNT SCHOTTKY BARRIER DIODE ARRAY".

Datasheet: https://www.diodes.com/assets/Datasheets/ds30374.pdf

Symbol Screenshots (a copy-pase drawing from `1N5820` symbol x3):
image
image
image

Using existing PCB Footprint `SOT-363*` from `TO_SOT_Packages_SMD` library:
image
image

### CODE REVIEW

**Comment by evanshultz** [comment]
- Description should be `Schottky Barrier Diode Array, SOT-363`
- Pin name offset should be 20mil.
- Add a default footprint.
- The footprint filter should be `SOT?363`.

Note that this is one case (basically this whole library) where we allow off grid pins.

**Comment by cederom** [comment]
Okay! I copy-pasted symbol from existing 1N5820.. will update next week, thanks for feedback @evanshultz! :-)

**Comment by antoniovazquezblanco** [comment]
@cederom please, don't forget about this PR! Thanks!

**Comment by cederom** [comment]
Thanks for the reminder! I will come back to this project next week, will
do! :-)

--
CeDeROM, SQ7MHZ, http://www.tomek.cedro.info

**Comment by poeschlr** [comment]
I took over and finished this in https://github.com/KiCad/kicad-symbols/pull/1351.

I hope nobody is mad at me.

**Comment by cederom** [comment]
Thank you @poeschlr @antoniovazquezblanco ans sorry for the delay I could not get under the amount of late tasks :-(

ALL THE BEST IN 2019 FOLKS!!! (AND BETTER ORGANIZATION FOR ME HE HE)

**Pull request closed without merging**
