### PR TITLE
Add EL817 optocoupler

### PR DESCRIPTION
**Pull request by gggfred**
[Datasheet](http://www.everlight.com/file/ProductFile/EL817.pdf)
imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. This can be an ALIAS of one of the existing *817 symbols.
1. The description should only mention `DIP-4` (add the comma) based on the footprint you've assigned. Depending on the symbol you choose in the first item that could vary.

**Comment by gggfred** [comment]
> 
> 
>     1. This can be an ALIAS of one of the existing *817 symbols.
> 
>     2. The description should only mention `DIP-4` (add the comma) based on the footprint you've assigned. Depending on the symbol you choose in the first item that could vary.

@evanshultz it's done

**Comment by evanshultz** [comment]
Thanks! Two things remain regarding the description:
1. With no suffix, CTR is 50-600%.
1. Add the hyphen in the package name.

**Comment by gggfred** [comment]
> 
> 
> Thanks! Two things remain regarding the description:
> 
>     1. With no suffix, CTR is 50-600%.
> 
>     2. Add the hyphen in the package name.

ready

**Comment by evanshultz** [comment]
Thanks! It's not required to add the CTR to the description but were you planning to add it?

**Comment by gggfred** [comment]
actually not. I copied the PC817 description

**Comment by evanshultz** [comment]
PC817 does have CTR in the description. But as I said, it's not required.

Thanks!

**Pull request merged**
