### PR TITLE
Add IS31FL3218

### PR DESCRIPTION
**Pull request by fauxpark**
Another LED matrix driver by ISSI.

sym

Datsheet: http://www.issi.com/WW/pdf/31FL3218.pdf
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1640
Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/374

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Should the body size and pinout be compatible with the existing 3216 symbol? I've not used either part so I don't know if that's something to consider or not. If not, can the symbol be a bit smaller? It looks like empty space at the bottom. If not, then everything looks good and I'll merge.

FYI, review is a bit easier if all symbols are in screenshots and not just one. :)

**Comment by evanshultz** [comment]
Can you capitalize words in the description? That seems to be the convention.

**Comment by fauxpark** [comment]
> Should the body size and pinout be compatible with the existing 3216 symbol? I've not used either part so I don't know if that's something to consider or not.

The pinouts of all these ISSI drivers seem wildly different between them. This part has two extra OUT pins, does not have the GPIO capability on OUT9-OUT16, nor does it have the audio input pin, so I'd say it is not at all compatible.

> If not, can the symbol be a bit smaller? It looks like empty space at the bottom. If not, then everything looks good and I'll merge.

Done.

> FYI, review is a bit easier if all symbols are in screenshots and not just one. :)

I figured it would imply the only difference between them is the extra pin on the QFN symbol for the EP, but fair enough. Sorry.

**Comment by evanshultz** [comment]
All good. Thanks!

**Pull request merged**
