### PR TITLE
ADD INA219 SOIC and SOT-23

### PR DESCRIPTION
**Pull request by jneiva08**
Add INA219

Datasheet: http://www.ti.com/lit/ds/symlink/ina219.pdf

SOIC-8:
ina219_soic

SOT-23-8:
ina219_sot23

I don't know if it is the right place to add.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] "I" in the name indicate industrial temperature, but should be omitted in KiCad. The devices should be called `INA219AxD` and `INA219AxDCN`
- [ ] If you can add aliases `INA219BxD` and `INA219BxDCN` this can be very nice :) This is an high accuracy version (you can complete the description)
- [ ] Can you remove special characters in the description ? => "Zero"
- [ ] Can you use only capital letters for Vs => "VS"
- [ ] A0 and A1 should be Input

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage, have made the changes you requested

The symbol looks this now:
ina219

**Comment by myfreescalewebpage** [comment]
Hello @jneiva08 great job here, no more comment to do, merging.

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
