### PR TITLE
Add LP3869x linear regulators

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.ti.com/lit/ds/symlink/lp38691.pdf
https://www.ti.com/lit/ds/symlink/lp38693.pdf

image
image
image
image

Two notes:
- Page 20 of the datasheet talks about the thermal pad of the WSON. It's unconnected electrically but strongly recommended to be grounded.
- The WSON footprint oddly doesn't mention the thermal pad size, but it's correct and used by two symbols (`LMR10510YSD` and `LMR62421XSD`) so I went with it.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz !

A few comments I have during my review:

- [ ] The aliases of "LP38691SD-1.8" have datasheet link "https://www.ti.com/lit/ds/symlink/lp38693.pdf"
- [ ] The "LP38693DT-1.8" has datasheet "https://www.ti.com/lit/ds/symlink/lp38691.pdf"
- [ ] LP38691SD-1.8 the expose pad is usually called "EP" in the lib, I was almost sure we do this even if the datasheet called it something else, isn't it ?

Else no comment on the symbols

Cheers,
Joel

**Comment by evanshultz** [comment]
Fixed the first two. How did I do that?

For the last one, I think EP is standard for footprints (see https://kicad-pcb.org/libraries/klc/S5.2/) but I'm not aware of any standard for symbols. It does vary. Check out `TLC5947DAP` and `TLC5940PWP` as a couples examples I found quickly. But if you want I can change it. Probably this should be standardized, but there's a lot of cleanup to get it tidy.

**Comment by myfreescalewebpage** [comment]
Yes I know there is plenty of things to cleanup like that. I personally always ask the expose pad to be called "EP", except if it is stacked with GND of course!

**Comment by evanshultz** [comment]
Alright. I can change it, but did you notice on page 4 it's explicitly called 'DAP'?

**Comment by myfreescalewebpage** [comment]
Yes I notice that. I think "EP" naming should really be standardized to symbol as well.

**Comment by evanshultz** [comment]
OK. Done.

**Comment by myfreescalewebpage** [comment]
Thanks. I have just notice in the travis log that the pin offset is 10 mil instead of 20. Is it intentional?

**Comment by evanshultz** [comment]
Yes. To give a bit more clearance for the 'standard' regulator symbol pin text, going down to 10mil was used. I didn't find the PR about this but I recall seeing this when Jan standardized these symbols a few years ago. And right now I see about double the number of symbols using 10mil in the library. So clearly it's still mixed, but 10mil is intentional.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
