### PR TITLE
Add TLV755P*DBV LDO aliases

### PR DESCRIPTION
**Pull request by awygle**
This adds the TLV755P LDO series SOT23-5/DBV parts from TI as a set of aliases to the TLV71209_SOT23-5 symbol.

Datasheet is http://www.ti.com/lit/ds/symlink/tlv755p.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by awygle** [comment]
I don't understand why the Travis script is calculating the center the way it is - based on my other experiences I would expect this to say the component is centered. If someone can offer advice on how to convince Travis I'll make those changes, otherwise I should probably revert the movement (but keep the pin offset change).

**Comment by evanshultz** [comment]
In general, the centering algorithm is rather weak (I seem to recall only pin locations are checked) and we often allow violations of this rule. Here is the existing symbol:
image

It's fine as it was. You can revert any movement changes.

And while you're at it: For completeness, can you add `Low IQ, Small Size,` to the description as in the datasheet title?

**Comment by awygle** [comment]
Done!

**Comment by evanshultz** [comment]
Thanks once again! Please keep the PRs coming!

**Pull request merged**
