### PR TITLE
Added Silicon Labs BGM12x Bluetooth SiP modules.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.silabs.com/documents/public/data-sheets/bgm12x-datasheet.pdf
Footprint depends on PR: https://github.com/KiCad/kicad-footprints/pull/2042

imagen

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

BGM121A256V2
- [ ] The footprint is missing
- [ ] Pin 4 and 5 should be Passive
- [ ] Pin 6, 27, 51, 52 are missing
- [ ] Name of pin 26 is V_BATT
- [ ] Name of pin 28 is V_1V8
- [ ] Name of pin 31 is V_IOVDD
- [ ] GND stacking is not correct. Invisible pin should be Passive (see travis output)

BGM121N256V2
- [ ] I don't see any differences on the pinout, is the package different ? If yes, the same comment done above apply also on this symbol. Else, this should be an alias.

Cheers,
Joel

**Comment by cnieves1** [comment]
Sorry, something was screwed up while rebasing... Closing this PR and reopening a new one:
  https://github.com/KiCad/kicad-symbols/pull/2674
Is there any howto about rebasing? I always end up including master commits into my branch...

**Comment by chschlue** [comment]
Basically `git rebase master` while on the PR branch. How do you do it?

**Comment by cnieves1** [comment]
I did a:
  - git checkout master
  - git fetch upstream
  - git merge upstream/master
  - git push
  - git checkout PR_branch
  - git rebase master
  - git push
I checked before pushing that there were only my commits, then pushed, and then realized there were a lot of other commits (merged into master) at the PR...

**Comment by chschlue** [comment]
Upstream is KiCad/kicad-symbols, I assume?

Im a little confused. https://github.com/KiCad/kicad-symbols/compare/master...cnieves1:bgm121 shows that your branch has only on commit on top of master, but with a different hash than https://github.com/KiCad/kicad-symbols/pull/2432/commits/aaf2c67542837a681831df15e26eb6de5cb7817a. Then, there's https://github.com/KiCad/kicad-symbols/pull/2432/commits/74943bd1aa064173b65691f20c10390e991b4a2c which says you merged your PR branch into itself.

**Comment by cnieves1** [comment]
Yes, upstream is kicad/kicad-symbols.

Please don't try to understand it... I delete the whole branch both locally and in github. Then I created a new one (with the same name) with the changes done...
So https://github.com/KiCad/kicad-symbols/compare/master...cnieves1:bgm121 is clean.

Yes, I realize that there is no chance now to see what was wrong. Sorry!

If you look above at this page you will see how other commits are mixed with this PR...
This is not the first time this happens to me. It seems there is something I don't understand yet...

**Pull request closed without merging**
