### PR TITLE
Added NUF4401MN.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.onsemi.com/pub/Collateral/NUF4401MN-D.PDF
Footprint depends on PR: https://github.com/pointhi/kicad-footprint-generator/pull/452
imagen

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

- [ ] The description should ends with the package name: `4 channel EMI filters with integrated ESD protection, DFN-8`
- [ ] The footprint filter should be `DFN*1EP*2x2mm*P0.5mm*`
- [ ] Use only capital letters for pin names
- [ ] You can reduce the height of the symbol by 100mil

Cheers,
Joel

**Comment by cnieves1** [comment]
Keep in mind that there are symbols similar to this one:
Captura de pantalla de 2020-04-06 08-46-24
Captura de pantalla de 2020-04-06 08-46-34

Changes done.
Captura de pantalla de 2020-04-06 08-53-13

Now that symbol is shrinked, the symbol border is no longer centered...

**Comment by myfreescalewebpage** [comment]
Yes the other symbol should be updated too.
It is accepted to have center shifted according to symbol geometry.
Joel

**Pull request merged**
