### PR TITLE
fix for issue #466: fp filter DIP* -> *:DIP*

### PR DESCRIPTION
**Pull request by poeschlr**
This gets the kicad 4 behavior back for `DIP*` filters.
More details about it see https://github.com/KiCad/kicad-symbols/issues/466 and launchpad bug report https://bugs.launchpad.net/kicad/+bug/1751565.

---

Filter result for MCP7940N.
screenshot from 2018-04-18 11-11-06

For reference the original result as reported by @evanshultz:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
I see Wayne comment on the launchpad bug since this was posted. Has that discussion finished, or at least reached a point where this can/should begin?

**Comment by poeschlr** [comment]
I still have some hope that there will be a better solution than this PR.

**Comment by stambaughw** [comment]
I'm still looking at this.  There seems to be something amiss with the
CvPcb filtering code.  I will reply as soon as I figure out what is
going on.

**Comment by poeschlr** [comment]
This PR is no longer necessary as the underlying problem has now been fixed on the software side.
(Commit that fixed it: https://github.com/KiCad/kicad-source-mirror/commit/62522ee45015642d2440bf8103e6cf879de57c06)

With today's nightly build (on ubuntu) i already get the correct result without this being merged.

**Pull request closed without merging**
