### PR TITLE
Add MAX941

### PR DESCRIPTION
**Pull request by rleh**
Add MAX941

- [x] Datasheet: https://datasheets.maximintegrated.com/en/ds/MAX941-MAX944.pdf
- [x] Screenshot below
- [x] Footprints exist & match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Travis automated check scripts

MAX941

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
Hi @rleh! Thank you for contributing to the KiCad libraries! I have a few notes, just from looking at your screenshot:

- Please align your `NC` pin on the symbol body outline. From [S4.6](http://www.kicad-pcb.org/libraries/klc/S4.6/):
> Pins that are not intended to be connected must be set to invisible. In this case the electrical type must be Not Connected. **The end of the pin should lie within or on the symbols outline to prevent unwanted connections to the invisible pin**.
- Please make the pin length of 2,3 100mils.
- Consider adopting 20mils text for `nLATCH` and `nSHUTDOWN` (shown below). This is permitted under [S3.2](http://www.kicad-pcb.org/libraries/klc/S3.2/):
image

**Comment by rleh** [comment]
Thanks for reviewing!

I took care of your comments and adapted the symbol accordingly:
grafik

**Comment by rleh** [comment]
@DanSGiesbrecht I rebased my commits to resolve the conflicts.

Merge?

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@rleh I try to continue/restart the review from this point

- [ ] The part should be atomic, i.e. one symbol per footprint, with the footprint at the end of the description, footprint set and fp filter according to the wanted part. Name "MAX941xPA" for PDIP, "MAX941xSA" for SOIC etc.
- [ ] keyword "single comparator" is better has done for other similar symbols
- [ ] Name of pin 6 should be "V-" for single supply compactors

Will do a full review after those changes

Joel

**Comment by rleh** [comment]
@myfreescalewebpage Thanks for reviewing!

I made the requested changes and therefore split the component into 3 parts (for PDIP, SOIC and µMAX/MSOP packages).

**Comment by myfreescalewebpage** [comment]
@rleh thanks, I continue the review:

MAX941xPA:
- [ ] Package at the end of the description "PDIP-8"

MAX941xSA:
- [ ] Package at the end of the description "SOIC-8"

MAX941xUA-T:
- [ ] Name should be MAX941xUA, I thin the "T" refer to the packaging (tube reel)
- [ ] Package at the end of the description "MSOP-8"
- [ ] Fp filter `MSOP*3x3mm*P0.65mm*`

Then ready to go !

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging. Good job done here and quick fixes!

**Comment by rleh** [comment]
Thanks!

**Pull request merged**
