### PR TITLE
Correct pin types for DWM1000 and fix a few for DWM1001

### LINKED ISSUE #2856: Electrical type of DWM1000 VSS pins should be Power input, not Power output
The schematic symbol for DWM1000 in RF_Module has all of the VSS pins set to the electrical type Power output. This causes ERC to fail, as these pins all need to be tied together.

The correct setting for all of the VSS pins is Power input.

### PR DESCRIPTION
**Pull request by gavanfantom**
* All ground pins on DWM1000 are now power inputs
* I/O signals corrected on DWM1000
* One or two signals corrected on the DWM1001, but the GND stack left wrong to appease the automated checker.

Fixes #2856

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @gavanfantom 

Thanks for the enhancement.

For DWM1001 I wonder if pin 26, 27 type are correct.
For pin 30 and 31 type seems to be Output.
If you want to fix also the pin position offset this is welcome.

Again thanks for this job.
Joel

**Comment by myfreescalewebpage** [comment]
@gavanfantom ping. If you have time to check my previous comment. Thanks

**Comment by gavanfantom** [comment]
It's probably best to pull this and deal with the dwm1001 separately, as that's not a module I've used.

**Comment by myfreescalewebpage** [comment]
Thanks for your answer, in this case merging now the job already done.
Joel

**Pull request merged**
