### PR TITLE
Moved SIM900 from RF to RF_GSM.

### PR DESCRIPTION
**Pull request by jneiva08**
Moved SIM900 from RF to RF_GSM.
Updated Electrical Type of some pins and datasheet.

sim900

datasheet:
http://simcom.ee/documents/SIM900/SIM900_Hardware%20Design_V2.05.pdf

footprint:
[#583](https://github.com/KiCad/kicad-footprints/pull/583)
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Hi,

I moved because, intend to add more 2 GSM modems.
Already added the footprint.

What KLC rules should be updated?

**Comment by evanshultz** [comment]
Then I'll list the items I see. Thanks for helping to improve the library!
- All pin lengths should be 100mil.
- Pins should only be of type Line.
- Stack power and ground pins.
- Once pins are stacked, the symbol may be able to be shrunk a bit.
- I think VRTC should also be Power Input type, but this one is a gray area. Bidirectional would normally be only for logic pins.
- The LCD interface pins do not match the datasheet names.
- I'm inclined to put mic input pins on the left and PWM output pins on the right.
- Put the NC pin ends on the symbol border so those pins can't be easily connected.

**Comment by evanshultz** [comment]
Thanks for making these changes!
- Could you please post a new screenshot since there are notable visual changes?
- Just to be sure we're limiting the footprints properly in case a potentially conflicting footprint from another vendor is ever added, the footprint filter should be `SIMCom*SIM900*`.

**Comment by jneiva08** [comment]
This is how to looks now the symbol of SIM900.

simcom900v2

**Comment by evanshultz** [comment]
Thanks! Two more comments:
- Can the MIC and SPK pins be across from each other?
- The NC pins will not be shown, so they can pack inbetween other pins and the symbol can be a bit shorter.

I'll wait to merge this until after the footprint is merged.

**Comment by jneiva08** [comment]
I'm sorry for my 2 earlier commits. Still getting used with git.

The NC pins were distributed among the others and the symbol shrank slightly.

The modifications on the symbol is:

sim900_symbol


Thanks for your patience with me.

**Comment by evanshultz** [comment]
Thank you! The symbol looks very nice now!

Unfortunately, this is introducing a new lib (`RF_GSM`) and with KiCad v5 shipping soon we aren't changing libraries at this time. Could you move this symbol back to `RF` (I think that is the best library to use) and then I can merge?

**Comment by Ratfink** [comment]
Actually, Rene specifically said in https://github.com/KiCad/kicad-symbols/issues/451#issuecomment-390485782 that creating new libraries is okay during the freeze.  Unless there are some other symbols that are planned to go into this new library though, I'm not sure creating it with one symbol is a good idea.

**Comment by jneiva08** [comment]
I moved sim900 to new library because i'm planning to add more GSM modules.
I'm waiting for the commit to add sim800c, will need no marketing some fix first (some sugestions given um this PR).
This was my time to use git exept clone 😀.

**Comment by evanshultz** [comment]
Thanks! I appreciate all your efforts to fix up this symbol and I'm looking forward to the new ones! We really appreciate the community like you building up the official KiCad library!

**Pull request merged**
