### PR TITLE
Add BUK9M53-60EX

### PR DESCRIPTION
**Pull request by strombom**
BUK9M53-60EX

https://assets.nexperia.com/documents/data-sheet/BUK9M53-60E.pdf

image

image

Footprint pull request: https://github.com/KiCad/kicad-footprints/pull/313

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
since you removed all whitespace before the A and V-unit-sybols, could you please do the same for mOhm?

**Comment by strombom** [comment]
Ok removed whitespace

**Comment by evanshultz** [comment]
The footprint name change at https://github.com/KiCad/kicad-footprints/pull/313 will cause this PR to need a corresponding change.

**Comment by evanshultz** [comment]
Thanks again! I really appreciate your hard work to want to improve the library and follow through to get it done!

@poeschlr 
Can you check out the CI output here? It's complaining about the pin text offset being 1mil on this symbol. But many other symbols are the same. Is our script not correctly catchinging all these warnings?

**Comment by jkriege2** [comment]
no, the scripts work fine. I noticed that several "small" symbols (also in device.lib) have the wrong pin-offset set. It's not a visible problem, as they don't have pin-labels ... bt still the scripts check that and complain. We should do a cleanup for that at some point.

**Comment by jkriege2** [comment]
I opened an issue for taht: https://github.com/KiCad/kicad-symbols/issues/260

**Comment by strombom** [comment]
Is it this value?

image

I'm unable to change the value, it's not saved...

**Comment by evanshultz** [comment]
@strombom 
That's fine. Jan's PR will clean up the whole lib anyway. Thank you!

**Pull request merged**
