### PR TITLE
Adding ICE40HX1K-TQ144

### PR DESCRIPTION
**Pull request by ki5libs**
Adding ICE40HX1K-TQ144 Lattice FPGA
[Datasheet](https://www.latticesemi.com/view_document?document_id=49312)
[Pinout](https://www.latticesemi.com/view_document?document_id=49383)
Unit A
ice40_ba
Unit B
ice40_bb
Unit C
ice40_bc
Unit D
ice40_bd
Unit E
ice40_be

Symbol based on ICE40HX8K-BG121 structure and pins allocations.
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ki5libs thanks for this contribution,

I have not made a full review, but seen:
- [ ] Pin length should be 150mil (because pin numbers are with 3 characters only)
- [ ] On unit E, Power Input should be on top and bottom
- [ ] The symbol is not centered (travis error), not sure which unit it is...

Cheers,
Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage , please, find some comments above:

>Pin length should be 150mil (because pin numbers are with 3 characters only)

I couldn't do this because using of pin length 50 mil or 150 mil in case of NC pins which should lay on rectangle border lead to Travis error. Maybe I just don't know how to do this. Please correct me if I'm wrong.
>On unit E, Power Input should be on top and bottom

Done.
>The symbol is not centered (travis error), not sure which unit it is...

Tried to fix it, but it still have small offset (0, 150). It's actually not an error and KLC S3.1 tells that it's acceptable in case of not symmetrical symbol.
>Footprint filter should be TQFP*20x20mm*P0.5mm*

Done.

**Comment by myfreescalewebpage** [comment]
> I couldn't do this because using of pin length 50 mil or 150 mil in case of NC pins which should lay on rectangle border lead to Travis error. Maybe I just don't know how to do this. Please correct me if I'm wrong.

You can move the NC pins inside the symbol to solve this issue. You can also enlarge a little bit the units, and get the positive power pins centered for most of them.

Joel

**Comment by ki5libs** [comment]
@myfreescalewebpage thanks for advice, I've done it such way. I couldn't fix center. Please let me know if you have some offering about that. 
Part A:
ICE40_PA
Part B:
ICE40_PB
Part C:
ICE40_PC
Part D:
ICE_PD
Part E:
ICE40_PE

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks, now making a full review from this point. Here are my comments:

- [ ] Number of pin GNDPLL is 35 and pin VCCPLL is 36 (you have cross them)
- [ ] Why grouping pins 67/68/70/71 on unit E and not on unit C with the other IOB pins ?
- [ ] Why grouping pins 66 and 65 on unit C ?
- [ ] Unit C is larger than units A/B/D for no reason. Maybe it's better if you can have the same width.

Cheers,
Joel

**Comment by ki5libs** [comment]
@myfreescalewebpage 

thanks for finding my mistake with pins 35 and 36. It's fixed now. I've also changed the width of unit C.
Another two questions have the same answer - I've making this symbol using ICE40HX8K-BG121 as an example. So pin placement is very close to that symbol. Pins 67, 68, 70, 71 in most cases used for SPI memory connection so it's one more reason to place them separately. And I can move pins 65 and 66 if you tell me how would you prefer to allocate them.

**Comment by myfreescalewebpage** [comment]
Thanks for the fixes.
I'm not familiar with this kind of device, how the CRESET_B and CDONE pins are used ? What do they stand for ?
Joel

**Comment by ki5libs** [comment]
@myfreescalewebpage 

`CRESET_B` and `CDONE` are configuration control pins. `CRESET_B` is an input, which resets the FPGA when driven low. When it returns high, the FPGA restarts the configuration process from its power-on conditions. At the end of the configuration process device turning off the internal pull-down transistor on the `CDONE` output pin. That's it.

**Comment by myfreescalewebpage** [comment]
So it's not really linked to pins on unit C. I suggest to group them with power pins if you agree ?

**Comment by myfreescalewebpage** [comment]
Ok for me, thanks. Merging.

**Pull request merged**
