### PR TITLE
Add three new transistors as ALIASes

### PR DESCRIPTION
**Pull request by evanshultz**
- https://assets.nexperia.com/documents/data-sheet/PUMX1.pdf
- https://assets.nexperia.com/documents/data-sheet/PUMT1.pdf
- https://toshiba.semicon-storage.com/info/docget.jsp?did=19305&prodName=2SC4213 (warning -download!)

Also correct description to BC817W to mention the correct package

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
It all looks basically good.

The aliases are correct and the fix to the description of the BC817W is correct too.
I've checked the descriptions and they look OK too.

Just one thing. Are the keywords for the PUMx1 parts a typo?

Thanks!

**Comment by evanshultz** [comment]
I thought the keywords looked a little weird too but that was the root part's keywords. And I can still understand what's meant. Since the description and keywords are rather a mess in all the transistor libs, and there's an issue to track straightening it up, I just left things for now. Do you want a change?

**Comment by diegoherranz** [comment]
I don't understand why the "Transistor/PNP" and "Transistor/NPN".
If you don't mind I would just leave them as "NPN Transistor" and "PNP Transistor".
Thanks!

**Comment by evanshultz** [comment]
Alrighty then. I've updated this part of the keywords for all dual BJT symbols.

**Comment by diegoherranz** [comment]
Thanks. I didn't expect you to fix them all, but this looks much better now :)
Merging.

**Pull request merged**
