### PR TITLE
Traco TDN

### PR DESCRIPTION
**Pull request by ryback08**
ADD Traco DC/DC TDN dual output SMD & DIP reference
Change name of TDN_5-0910 to TDN_x-xx1x, compatible with most range

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

For TDN version 1W, 3W 5W
[1W DIP ](https://www.tracopower.com/sites/default/files/products/datasheets/tdn1wi_datasheet.pdf)
[1W SMD](https://www.tracopower.com/sites/default/files/products/datasheets/tdn1wism_datasheet.pdf)
[5W DIP](https://www.tracopower.com/sites/default/files/products/datasheets/tdn5wi_datasheet.pdf)
[5W SMD](https://www.tracopower.com/sites/default/files/products/datasheets/tdn5wism_datasheet.pdf)

tdninfo

[](url)
Screenshoot :
SMD version - Single output

DIP version - Single output
1DIP
SMD version - DUAL output

DIP version DUAL output
2DIP

### CODE REVIEW

**Comment by ryback08** [comment]
Hi aris-kimi, I made change.
I begin with git-hub..... complicated to understand the right way.

I deleted TDN_x-xx2xWISM and add all version of TDN 5.

**Comment by aris-kimi** [comment]
Hi @ryback08 , thanks.
I know how complicated looks for those first steps, but i feel it worths it :-)

There are some conflicts with *.dcm file, can you please fix this in order to proceed with the review?

**Comment by ryback08** [comment]
I finally copy original Regulator_Switching.dcm on kicad github and add all componed from my file.
Add TDN, see line 4317 to 4532.
.... Conflicts
What is the good way to solve it.

**Comment by aris-kimi** [comment]
I am not sure, i really need assistance in this one @myfreescalewebpage if you spare some time.

I would suggest to copy KiCAD's libraries without any addition in order to clear differences, but both *.dcm and *.lib files.
After confirmation that nothing has been affected, add your changes in both files, and upload again.

**Comment by myfreescalewebpage** [comment]
About the branch conflict ? You have to rebase on top of the master https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by ryback08** [comment]
I delete the fork, I start the work again.

**Pull request closed without merging**
