### PR TITLE
Change alias LM358Z-2.5 to LM385Z-2.5

### PR DESCRIPTION
**Pull request by davidsrsb**
Typo in part number, the LM358 is a dual opamp

Correcting alias part number error in Reference_Voltage symbol library to intended LM385Z-2.5

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @davidsrsb 

Not checked, but is DCM file already correct ?

Thanks
Joel

**Comment by davidsrsb** [comment]
The DCM also had "358"

**Comment by davidsrsb** [comment]
I am trying to understand the travis fail, asking for metadata, was the original library compliant?

**Comment by myfreescalewebpage** [comment]
@davidsrsb that's because you have modified only the lib file, not the dcm. Kicad currently gives an error when opening the library editor, saying the alias LM358Z-2.5 is not found. Travis also do no found the alias definition in dcm file, and complains.

=> dcm file, line 81, change 358 to 385.

Joel

**Comment by davidsrsb** [comment]
I see, my local updated copy of the DCM did not commit to my GitHub fork. The Git GUI is not that intuitive to use for the first time

**Comment by davidsrsb** [comment]
Please close this, it is replaced by #1383

**Pull request closed without merging**
