### PR TITLE
add MSW(A)-2 RF switches

### PR DESCRIPTION
**Pull request by lorem-ipsum**
add a series of RF switches from Mini-Circuits. Absorbative and reflective versions share the same symbol, so I only added a screenshot of one each (pin numbers are different though). Footprint PRs will be created soon, I will reference them here.

[MSW-2-20](https://ww2.minicircuits.com/pdfs/MSW-2-20+.pdf) [MSW2-50](https://ww2.minicircuits.com/pdfs/MSW2-50+.pdf)
msw-2-20

[MSWA-2-20](https://ww2.minicircuits.com/pdfs/MSWA-2-20+.pdf) [MSWA2-50](https://ww2.minicircuits.com/pdfs/MSWA2-50+.pdf)
mswa2-50

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A few comments I have during my review:

MSW-2-20
- [ ] Waiting for the footprint

MSW2-50
- [ ] Bad datasheet link, should be `https://ww2.minicircuits.com/pdfs/MSW2-50+.pdf`
- [ ] NC pin 2 should be added, type Not Connected, not visible
- [ ] Waiting for the footprint

MSWA-2-20
- [ ] RF Output pins number are crossed
- [ ] Waiting for the footprint

MSWA2-50+
- [ ] NC pin 2 should be added, type Not Connected, not visible
- [ ] Waiting for the footprint

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
> About the NC pins: Is it really necessary to add them?

Yes please. If the user wants to change the footprint (selecting hand soldering version for example), then he is able to use the pad number filter.

Comments about your previous commits: MSW2-50 datasheet not correctly fixed.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks @lorem-ipsum 
Last change not yet fixed : waiting pin 2 (NC) on two devices.
Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage,
did not have the time to fix it yesterday, now its hopefully good to go.
Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
@lorem-ipsum thanks, ok for me now, merging.
Joel

**Pull request merged**
