### PR TITLE
Add MP171

### PR DESCRIPTION
**Pull request by SebastianRumohr**
Added MP171 to Regulator_Switching:

- MP171GJ with TSOT23-5
- MP171GS with SOIC-8

Reasons behind violations:
- S4.2: VCC pin is not on top of symbol. This is because it is the control circuit power supply and not the power supply of the IC. You'll put a capacitor between source and VCC. Refer to schematic [example](https://user-images.githubusercontent.com/46223600/53476699-47194800-3a73-11e9-9341-a451cae07b95.PNG)

MP171GJ:  
mp171gj

MP171GS:  
mp171gs

Example:  
example

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @SebastianRumohr , thanks for contributing,

A few comments I have during my review:

MP171GJ:
- [ ] The description format is not correct, should be `60mA Non-Isolated Off-Line Regulator, 700V Input Voltage, Adjustable Output Voltage, TSOT-23-5`
- [ ] Keywords should no contain the part name itself, `regulator switching adjustable` is great
- [ ] Footprint filter should be `TSOT?23*`
- [ ] Pins 3 and 4 should be stacked
- [ ] Use capital letters for pin names
- [ ] VCC should be on the top of the symbol
- [ ] SOURCE should be in front os DRAIN
- [ ] FB below SOURCE

MP171GS:
- [ ] The description format is not correct, should be `60mA Non-Isolated Off-Line Regulator, 700V Input Voltage, Adjustable Output Voltage, SOIC-8`
- [ ] Keywords should no contain the part name itself, `regulator switching adjustable` is great
- [ ] Footprint filter should be `SOIC*3.9x4.9mm*P1.27mm*`
- [ ] Pins 3 and 4 should be stacked
- [ ] Use capital letters for pin names
- [ ] VCC should be on the top of the symbol
- [ ] SOURCE should be in front os DRAIN
- [ ] FB below SOURCE
- [ ] NC pins should be added, type Not Connected, invisible, placed on the border outline of the symbol

Cheers,
Joel

**Comment by SebastianRumohr** [comment]
Hi @myfreescalewebpage , thanks for your review. 

I fixed your comments.
MP171GJ:
* [X]  The description format is not correct, should be `60mA Non-Isolated Off-Line Regulator, 700V Input Voltage, Adjustable Output Voltage, TSOT-23-5`
* [X]  Keywords should no contain the part name itself, `regulator switching adjustable` is great
* [x]  Footprint filter should be `TSOT?23*`
* [x]  Pins 3 and 4 should be stacked
* [x]  Use capital letters for pin names
* [x]  VCC should be on the top of the symbol
* [x]  SOURCE should be in front os DRAIN
* [x]  FB below SOURCE

MP171GS:
* [x]  The description format is not correct, should be `60mA Non-Isolated Off-Line Regulator, 700V Input Voltage, Adjustable Output Voltage, SOIC-8`
* [x]  Keywords should no contain the part name itself, `regulator switching adjustable` is great
* [x]  Footprint filter should be `SOIC*3.9x4.9mm*P1.27mm*`
* [x]  Pins 3 and 4 should be stacked
* [x]  Use capital letters for pin names
* [x]  VCC should be on the top of the symbol
* [x]  SOURCE should be in front os DRAIN
* [x]  FB below SOURCE
* [x]  NC pins should be added, type Not Connected, invisible, placed on the border outline of the symbol

**Comment by myfreescalewebpage** [comment]
Thanks @SebastianRumohr great job done here. I think you can keep the height a little bit more important by adding 100mil extra space between SOURCE and FB, and this will fix the travis warning you have on both symbols. Proposition below, tell me what you think of this:

capture

**Comment by SebastianRumohr** [comment]
Thanks @myfreescalewebpage for the review. 
I thought about adding extra space between SOURCE and FB too. But I was not sure whether it is okay with the KLC or not. I added the extra space now.
mp171gj
mp171gs

I hope everything is okay now.

**Comment by myfreescalewebpage** [comment]
Very nice job done here, this remove the last travis warning so it's good to have. No more comment, merging.

**Comment by SebastianRumohr** [comment]
Thanks a lot.

**Pull request merged**
