### PR TITLE
Add LM329

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.analog.com/media/en/technical-documentation/data-sheets/129329fd.pdf
image

The FP filter will make Travis unhappy but due to the naming of the footprints and the validity of them to fit this part, I think using an underscore and antagonizing the CI system is best.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz 

A single comment I have during my review:

- [ ] The footprint filter should be "TO?92*" (travis error)

Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
I already thought about this. Please see my comment above and review the footprints in the lib that could potentially fit.

**Comment by myfreescalewebpage** [comment]
@evanshultz but this prevent using "TO-92.kicad_mod".... Why blocking this possibility ?

**Comment by evanshultz** [comment]
Oh. I hadn't realized that was at the top of the list. Thanks for pointing that out. I was trying to block `TO-92L*` and `TO-92S*` which aren't the right package. Oh well. Updated. The other TO-92 parts in this library are messy and inconsistent as I look through them.

**Pull request merged**
