### PR TITLE
Add LT1634 Voltage Reference

### PR DESCRIPTION
**Pull request by nivekg**
Hi, I created a symbol for the LT1634 voltage reference (all part numbers). No rule violations, but maybe someone can suggest a better keyword description. Let me know what you think.

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/1634ff.pdf

LT1634BCMS8-1.25:
LT1634BCMS8-1 25
LT1634BCMS8-2.5:
LT1634BCMS8-2 5
LT1634CCZ-1.25:
LT1634CCZ-1 25
LT1634CCZ-2.5:
LT1634CCZ-2 5
LT1634CCZ-4.096:
LT1634CCZ-4 096
LT1634CCZ-5:
LT1634CCZ-5
LT1634xxS8-1.25:
LT1634xxS8-1 25
LT1634xxS8-2.5:
LT1634xxS8-2 5
LT1634xxS8-4.096:
LT1634xxS8-4 096
LT1634xxS8-5:
LT1634xxS8-5

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Wildcard the temperate rating, which would change `LT1634BCMS8-1.25` to `LT1634BxMS8-1.25` as one example.
1. Use the ALIAS feature so only three symbols are needed.
1. the TO-92 symbol has the A pin wrong: it should be pin 3.
1. The TEST pin should be visible since it can be grounded.
1. All package pins must be included use the pin count filter in CvPcb, so add the TEST and DNC pins and make them hidden. Alternately, in a case like where there are more non-functional pins than commonly-usable ones, you could add the pin count to the footprint filter for the 8-pin symbols.

**Comment by nivekg** [comment]
Sorry for the long wait:

1. For the MSOP-8 package, there is only one temperature rating for the part which is LT1634BCMS8 so I think that's fine. Similarly for the T0-92 package which is LT1634CCZ. The SO-8 package has multiple temperature ratings and temperature coefficients so it has the name LT1634xxS8.
2. I changed the symbols to use the alias feature. Now there are only three symbols LT1634BCMS8-1.25, LT1634CCZ-1.25 and LT1634xxS8-1.25
3. The T0-92 pins looks right, unless I'm missing something. In the datasheet the symbol orientation is inverted compared to the kicad-footprint. 
4. Made the test pin visible, I'm not sure what type the pin should be so made it an input.
5. Added the pin count to the footprint filter for the 8-pin symbols.

Screenshots:
LT1634BCMS8
LT1634bcms8_updated

LT1634CCZ 
LT1634ccz_updated

LT1634xxS8
LT163

**Comment by nivekg** [comment]
@evanshultz Is anyone still checking this PR? (Not being pushy, just checking)

**Comment by evanshultz** [comment]
@nivekg 
I've been lazy but I'm trying to wrap things up. Let me know if you will be able to get to this in the next few days.

3. Maybe I'm the one cross-eyed. The datasheet shows the bottom view of the TO92, so the pins need to be changed. Swap pin numbers 1 and 3. Please elaborate if I'm mistaken since this is what I see.
image
4. I probably would have gone with Passive, but Input should be safe.

**Comment by nivekg** [comment]
Yup, your right. I was looking at the orientation wrong. All fixed now.

**Comment by evanshultz** [comment]
Thanks!

Just one more thing that I only noticed now: remove the `Inline*` from the TO-92 package's footprint filter. There are other footprints which could be used if the user is doing their own prep and I don't want to filter them out.

Once you do that, if my former self reviewed this well, we are ready to merge!

**Comment by nivekg** [comment]
I fixed it.

**Comment by evanshultz** [comment]
Thanks for coming back to this PR and putting in the effort to get it merged!

**Pull request merged**
