### PR TITLE
 add MSP430F2618-EP

### PR DESCRIPTION
**Pull request by penoud**
add MSP430F2618-EP

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
http://www.ti.com/lit/ds/symlink/msp430f2618-ep.pdf
- [X] An example screenshot image is very helpful
image
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @penoud , thanks for contributing,

A few comments I have during my review:

- [ ] Rename DVCC1 and DVCC2 to DVCC only
- [ ] Rename DVSS1 and DVSS2 to DVSS only and stack them
- [ ] Pin B3 is missing, you should add it, with name AVSS, and stack it with pin B2
- [ ] Pins C2 and C3 are connected together inernally and should be stacked
- [ ] RST pin is active low, the name of the pin B5 should be `~RST~/NMI` to get the overbar
- [ ] Pins A5 and A6 (TCK and TDI/TCLK) are Input, not Power Input
- [ ] Pin B6 (TMS) is Input, not Bidirectional
- [ ] Pin E2 (VREF+) is Power Input, not Bidirectional and should be placed on the top of the symbol
- [ ] The name of pin G1 should be `VREF-/VeREF-`
- [ ] Pin G1 (VREF-/VeREF-) is Power Input, not Bidirectional and should be placed on the bottom of the symbol
- [ ] Pin E1 (XIN) is Input and pin F1 (XOUT) is Output
- [ ] I would also suggest, as it is recommended by the datasheet page 7, that all reserved pins should be added, called DVSS, and stacked with the other DVSS pins

Cheers,
Joel

**Comment by penoud** [comment]
Updated screenshoot:
image

**Comment by myfreescalewebpage** [comment]
Thanks @penoud , few remaining comments:

- [ ] P6.5 pins (C2 and C3) name not crossed
- [ ] Pin E2 (VREF+) should be placed on the top of the symbol
- [ ] Pin G1 (VREF-/VeREF-) should be placed on the bottom of the symbol
- [ ] For consistency between top and bottom of the symbol, you can cross the position of the DVSS and AVSS pins (Digital on the left, analog on the right)

Joel

**Comment by penoud** [comment]
updated symbol:
image

**Comment by myfreescalewebpage** [comment]
For the same logic, VREF+ to be moved to the right of AVCC.

Also just realized that following stacking of P6.5, the ports on the left are no more aligned with the ports on the right. Maybe moving ports on the left up of 100mil is great. Proposition below.

capture

Let me known.

Joel

**Comment by penoud** [comment]
Looks fine for me. Did I need to do something?

**Comment by myfreescalewebpage** [comment]
Yes please, I have only attached a screenshot to illustrate the modification suggested to you, I haven't made any modifications of the previous message :)

Joel

**Comment by penoud** [comment]
Updated pin placement screenshoot:
image

**Comment by myfreescalewebpage** [comment]
@penoud ok for me, no more comment. Merging.
Thanks for your work on this PR !
Joel

**Pull request merged**
