### PR TITLE
Add EMI2121MTTAG

### PR DESCRIPTION
**Pull request by cp-aquila**
Add EMI2121MTTAG

------------
Datasheet: https://www.onsemi.com/pub/Collateral/511BN.PDF
Screenshot
Matches the footprint from this [pull-request](https://github.com/KiCad/kicad-footprints/pull/951)

* [x]  Provide a URL to a datasheet for the symbol(s) you are contributing
* [x]  An example screenshot image is very helpful
* [x]  Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
* [x]  If there are matching footprint PRs, provide link(s) as appropriate
* [ ]  Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by cp-aquila** [comment]
Travis does fail since the footprint is not merged yet.
(https://github.com/KiCad/kicad-footprints/pull/951)
Should I remove the footprint field?

**Comment by cp-aquila** [comment]
- Use shorter Pins
- Remove names, add numbers
- Swap Pins so they route easier to a Micro-USB connector
- Update footprint name


I did push new commits to my branch, but somehow this PR is not getting updated. Unsure what my mistake is :/

**Comment by cp-aquila** [comment]
- Use shorter Pins
- Remove names, add numbers
- Swap Pins so they route easier to a Micro-USB connector
- Update footprint name


I did push new commits to my branch, but somehow this PR is not getting updated. Unsure what my mistake is :/

**Comment by cp-aquila** [comment]
- Use shorter Pins
- Remove names, add numbers
- Swap Pins so they route easier to a Micro-USB connector
- Update footprint name


I did push new commits to my branch, but somehow this PR is not getting updated. Unsure what my mistake is :/

**Comment by cp-aquila** [comment]
- Use shorter Pins
- Remove names, add numbers
- Swap Pins so they route easier to a Micro-USB connector
- Update footprint name


I did push new commits to my branch, but somehow this PR is not getting updated. Unsure what my mistake is :/

**Comment by cp-aquila** [comment]
- Use shorter Pins
- Remove names, add numbers
- Swap Pins so they route easier to a Micro-USB connector
- Update footprint name


I did push new commits to my branch, but somehow this PR is not getting updated. Unsure what my mistake is :/

**Comment by myfreescalewebpage** [comment]
Hi @cp-aquila , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name, `, WDFN-8`
- [ ] The drawing makes the pin number to be displayed below the pins. I would suggest to modify the options of the symbol according to the following screenshot. This makes the pin number back above the pins, like all other symbols.

capture

Cheers,
Joel

**Comment by cp-aquila** [comment]
Hi Joel,

thanks for the review!
I made changes related to your comments.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Merging.

Joel

**Pull request merged**
