### PR TITLE
PIC32MX795F512L added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
PIC32MX795F512L-80V/PF, 80I/PF, 80V/PT and 80I/PT added.

Packages:
TQFP-100 12x12mm
TQFP-100 14x14mm

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/60001156J.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [-] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by serkanxselcuk** [comment]
Other changes are reordered lines, footprint editor made it automatically.

**Comment by seselcuk** [comment]
image

image

I signed CLA with both of users. I cannot understand why it is shown as not signed.

**Comment by serkanxselcuk** [comment]
Hi @antoniovazquezblanco ,
can you review this symbol?
Thank you.

**Comment by antoniovazquezblanco** [comment]
I do not have much time but I can guide you a little bit:

- Stack VSS pins.
- Pin naming should only contain the primary function and a secondary function in case it is very important (Port name + programming interfaces at most).
- Reorganize pins by function please.

Thank you!

**Comment by serkanxselcuk** [comment]
image

**Comment by serkanxselcuk** [comment]
image

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @serkanxselcuk , thanks for contributing,

A few comments I have during my review:

About symbol names, do you know what means 80I and 80V ? I think 80 is maybe 80MHz and the letter is the industrial grade but I'm not sure... If I'm right, this not a relevant information in the library and should be discarded, in this case it's good to remove the aliases, and chose part names "PIC32MX795F512L-PF" and "PIC32MX795F512L-PT" for the two package variants. Let me known if you have more information.

For both devices:
- [ ] Pins length should be 150mil (3 digits pin numbers)
- [ ] VSS pins are badly stacked. The first must be visible, power input while the other must be invisible, passive (see also travis error)
- [ ] Pin on the left should have their names beginning with pin number, not the function. For example pin 57 name should be `RG2/D+`, etc.
- [ ] Pin VBUS should be moved to the left of the symbol, see for example PIC32MX210F016D-IPT for example just above RG port.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @serkanxselcuk are you still alive on this subject ? Thanks.

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage , i will make those updates. Just I have some private problems now to be active here.

**Comment by myfreescalewebpage** [comment]
No worries @serkanxselcuk that was only to get news from you :) we keep the thread open here ! Thanks for your message.
Joel

**Comment by serkanxselcuk** [comment]
image
@myfreescalewebpage , your requested changes are done. thank you for your helpful notices.

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk thanks for making this old PR alive :) Two more comments:

- [ ] Just look at the PRODUCT IDENTIFICATION SYSTEM of the datasheet (page 438), I think the devices should be named `PIC32MX795F512L-80-xPF` and `PIC32MX795F512L-80-xPT`.
- [ ] Can you update the description and keywords to the new format ? For these devices: description `MIPS MCU, 80MHz, 512KB Flash, 12KB Boot Flash, 128KB RAM, 2.3-3.6V, USB, CAN, Ethernet, TQFP-80` and keywords `32-bit MPIS MCU Microcontroller`

Cheers,
Joel

**Comment by serkanxselcuk** [comment]
@myfreescalewebpage thank you for your review,

MCUs renamed in PIC32MX795F512L-80x-PF and PIC32MX795F512L-80x-PT. Descriptions and keywords changed as like suggestion.

Regards
Serkan

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk you have used "_" instead of "-" in the names. Else, this is great.

**Comment by serkanxselcuk** [comment]
@myfreescalewebpage sorry, my type error. fixed.
Thanks again.
Serkan

**Comment by myfreescalewebpage** [comment]
Thanks ! Merging :)

**Pull request merged**
