### PR TITLE
7 seg symbol

### PR DESCRIPTION
**Pull request by Solartraveler**
Add symbols for SA39-11, SC39-11, SA39-12, SC39-12 10x13mm Kingbright 7 segment LED displays

---

There are four colours available, with some suffix. I always added the datasheet link to the red ones. I successfully manufactured a PCB with three SC39-11YWA. I added the other variants for sake of completeness. The symbol is actually taken from one of the other 7segment display from the kicad lib - just the pin layout has been adjusted.

The pullrequest for the footprint is: https://github.com/KiCad/kicad-footprints/pull/1618

7segment-symbol

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Solartraveler , thanks for contributing,

A few comments I have during my review:

- [ ] First of all can you sign the CLA, which is a mandatory condition to accept your contribution ? Thanks.
- [ ] The design should be consistent with other 7 segment display in the library: one alias for each color, footprint name, footprint filter, etc. Look at other device from the same manufacturer in the library, for example `SA15-11SRWA` 

Then will do a full review.

Cheers,
Joel

**Comment by Solartraveler** [comment]
Okay, I hope, I have changed everything as requested. But I guess I missed something ;)

**Comment by myfreescalewebpage** [comment]
Great job done here !
I have just done a full review, no comment to do, perfect job!
Just need to wait the footprint before merging.
Thanks.
Joel

**Comment by Solartraveler** [comment]
Okay, the footprint is now merged with https://github.com/KiCad/kicad-footprints/pull/1866
And I have resolved conflicts with the current master branch.
As stated in https://github.com/KiCad/kicad-footprints/pull/1618#issuecomment-531628088
I have added the first used Email to my Git account - hope this helps, so I dont need a new pull request here.

**Comment by myfreescalewebpage** [comment]
Hi @Solartraveler and sorry for the delay. Seems everything is ok, no more comment to do, merging.

**Pull request merged**
