### PR TITLE
Added connector 41612 A-C

### PR DESCRIPTION
**Pull request by AndreaQ77**
New symbol, sorry I'am a beginner, first time.

*Replace this line with your commit message! Please provide a description of your pull request*

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
> New symbol, sorry I'am a beginner, first time.

Welcome and thanks for the contribution. Things around here sometimes go slow so don't expect us to answer your questions inmediatelly, but we will also not forget about your PR.

In order to help us, please look at the instructions in your first post and try to follow them (share a link to the datasheet, post an screen capture of the symbol...).

Thanks!

**Comment by AndreaQ77** [comment]
Component data sheet:
https://www.mouser.com/datasheet/2/418/NG_CD_5650951_O1-668739.pdf

I have split it in two parts, one per row.
image
image

**Comment by AndreaQ77** [comment]
Footprint PR:
https://github.com/KiCad/kicad-footprints/pull/1193

**Comment by evanshultz** [comment]
Unless I'm mistaken, we already have scripted connector symbols that are suitable:
image

As mentioned at https://github.com/KiCad/kicad-symbols/issues/1157, we need to ensure capitalization matches the footprints (expected to come in https://github.com/KiCad/kicad-footprints/pull/1076) but I think on the symbol side we're good either way.

**Comment by lorem-ipsum** [comment]
Great that you create these symbols, I did some work on the footprints (not quite finished yet, but already usable). As there are so many they definitely should be scripted, but having some is already a start.

The currently existing symbols are not suitable as they don't match the notation used by the DIN41612 connectors. The examples you showed use `a` and `b`, but the connector uses `a` and `c`. This becomes more problematic with skipped pins if only even numbered rows are populated.

I prefer the approach of splitting the rows into different components as this scales to more rows. There are connectors with three and up to five columns. For those splitting them is the only solution and then it would make sense to use the splitted approach for all of them as it would allow to "upgrade" from a 2 column version to a fully populated 3 column version.

**Comment by poeschlr** [comment]
As already written in the issue about this:

- We might want to create a separate symbol library holding only symbols for din connectors
- specialized symbols are required for many of them so i might suggest to include specialized symbols for all of them (will get confusing for users otherwise)
- with a bit of adaption the symbol generator in https://github.com/KiCad/kicad-library-utils/tree/master/schlib/autogen/connector could be used to generate symbols for these. I would opt for a multi unit approach with these as din connectors come in 3 and 4 row variants which are simply not feasible otherwise.)
- The graphical style should be similar to our normal connector symbols. I would even suggest to use similar pin numbering (meaning use lower case letters) to increase cross compatibility. (it seems both lower and upper case letters are used by manufacturers of such connectors.)

**Comment by AndreaQ77** [comment]
I'd like to add an information...
In the symbols library there are 3 symbols of connectors 41612 that (in my opinion) are not usable, too long and with pin name inverted A1 becames 1A.
I show you...

image

**Comment by evanshultz** [comment]
@AndreaQ77 
Agreed. The existing symbols are bad an should be replaced.

@poeschlr @fauxpark @lorem-ipsum 
I haven't used the symbol generator before and had other things I planned to spend my time doing. Are any of you up for this task?

**Comment by evanshultz** [comment]
But back to this...

We could still merge a one-off symbol if desired. Here are the things I gather above that we want to do:
1. Use lower case letters.
1. Name the pins letter-number.
1. I would prefer symbols exactly like the ones I drew above since those are done with the symbol generator now. Since the connector you mention above has only rows A and C populated, the question is then to put A on the left of unit one with C on the left of unit two, or A and C on the same unit? I ask because the version with rows A, B, and C is available and we do want to support that. My preference is A on unit one and C on unit two with the B column missing from unit one.

**Comment by evanshultz** [comment]
With #2935 merged this can be closed. It includes a scripted `DIN41612_02x32_AC` symbol which should suffice.

It's still an outstanding point to remove the old and busted DIN41612 connector symbols. Perhaps it's best to do that here before moving to GitLab. @chschlue ?

**Comment by chschlue** [comment]
👍🏼

**Comment by evanshultz** [comment]
Thank you @AndreaQ77 ! We appreciate you taking the time and initiative to create this symbol and make a PR regardless of eventually closing it. And I apologize for taking so long to resolve this.

**Pull request closed without merging**
