### PR TITLE
Fix pin 9, 10, 11, 12, 13, 14 of 74LS157 and 74157

### PR DESCRIPTION
**Pull request by pushpull13**
Fix pin 9, 10, 11, 12, 13, 14 of 74LS157 in 74xx.lib and 74157 in 74xx_IEEE.lib

- http://www.ti.com/lit/ds/symlink/sn74ls157.pdf

### CODE REVIEW

**Comment by aewallin** [comment]
screenshot before and after changes would help review a lot.

**Comment by myfreescalewebpage** [comment]
Making the previous/proposed screenshots required for this PR.

Original:

74LS157:

ori_74ls157

74157:

ori_74157

This PR:

74LS157:

74ls157

74157:

**Comment by myfreescalewebpage** [comment]
@pushpull13 my analysis of this PR is that you have cross gates C and D for both sybmol, is it right ?

@evanshultz what do you think of this modification, is it breaking existing schematics ?

Cheers
Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Yeah, I would merge it. It's a bug because the 3rd gate doesn't use those pin numbers. It's a minor thing, but a relatively low impact to users, so I say go for it.

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks for the answer.

@pushpull13 can you solve the branch conflict, so we will be able to merge the fix. Thanks.

**Comment by pushpull13** [comment]
Sure I will do

**Comment by myfreescalewebpage** [comment]
To resolve confmict with CLI: https://github.com/AgileVentures/shf-project/wiki/Resolving-Pull-Request-merge-conflicts

And if you are using a desktop app, such as https://desktop.github.com/, this is usually a single button to press to get it solved.

Thanks.

**Comment by myfreescalewebpage** [comment]
@pushpull13 also realize just now you have work on your master branch, which is not good, you should create a new branch when making a PR, for the next time :)
Thanks again for the bug correction anyway !!

**Comment by evanshultz** [comment]
Perhaps we should hold on a bit.

This is, IMO, a legitimate bug fix so we should be interested in merging it. It is quite true as you said, @myfreescalewebpage , that using the master branch to submit a bug fix is not good practice. But that doesn't stop this branch from being merged.

@pushpull13 Are you still willing to resolve the branch conflicts? There is good info above. If you can do that, I don't see anything stopping this PR from being re-opened and merged. Please let us know.

**Comment by myfreescalewebpage** [comment]
@evanshultz the author made a duplicated PR, which has been merged this morning: https://github.com/KiCad/kicad-symbols/pull/1592

**Pull request closed without merging**
