### PR TITLE
Add alias for tps56339

### PR DESCRIPTION
**Pull request by drid**
Add alias for tps56339

https://www.ti.com/lit/ds/symlink/tps56339.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @drid 

Some few comments:
- [ ] The name of the pins is not the same of the main symbol, your alias can't be an alias
- [ ] Name of this symbol should be "TPS56339DDC"

Will do a complete review after this.

Joel

**Comment by drid** [comment]
I added as a new symbol but followed same pin placement as they are pin compatible

**Comment by myfreescalewebpage** [comment]
Thanks, yes it is a good practice. Full review below:

- [ ] You can remove the `-`in the description: `4.5V to 24V Input, 3A Output Synchronous Buck Converter, SOT-23-6` 
- [ ] Pin 2 should be Power Output
- [ ] Pin 6 should be Passive
- [ ] Pin offset should be 20mil (see travis error)

Joel

**Comment by drid** [comment]
Should these fixes be applied to TPS562200 since this is the origin if this symbol?

**Comment by myfreescalewebpage** [comment]
> Should these fixes be applied to TPS562200 too since it is the origin of this symbol?

If you have time it's always welcome to enhance the old symbols of the library :)

**Comment by myfreescalewebpage** [comment]
No more comment on this PR, merging.

**Pull request merged**
