### PR TITLE
Bq76940

### PR DESCRIPTION
**Pull request by jneiva08**
created symbol for BQ76920

Datasheet: http://www.ti.com/lit/ds/symlink/bq76920.pdf

bq76920

created symbol for BQ76930

Datasheet: http://www.ti.com/lit/ds/symlink/bq76930.pdf

bq76930

size down symbol of BQ76940

Datasheet: http://www.ti.com/lit/ds/symlink/bq76940.pdf

bq76940

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
Hi @jneiva08 
I'll be reviewing this ASAP. When you have time, please resolve the merge conflict(s).

**Comment by jneiva08** [comment]
Sorry for asking, it's my first time to have conflicts.
Can explain how should proceed? I don't mind making the change.

Thanks

**Comment by DanSGiesbrecht** [comment]
@jneiva08 nice, thanks for fixing that! I'll review this ASAP (hopefully later today).

**Comment by jneiva08** [comment]
when will begin the next round to can break compatibility?
If it is soon can wait, if it will take long can close this PR and open 2.

**Comment by DanSGiesbrecht** [comment]
That's a good question. @poeschlr , do you know the answer to this?

**Comment by poeschlr** [comment]
We would need to ask the devs how much changes will be accepted for version 5.1.0. But this one change should be acceptable in my opinion.

**Comment by antoniovazquezblanco** [comment]
Following the criteria applied by @poeschlr in https://github.com/KiCad/kicad-symbols/pull/757 I will move the target milestone to 6.0.0.

Sorry for that.

**Comment by jneiva08** [comment]
@DanSGiesbrecht, you thinks is still possible to split the new added in new PR?

**Comment by chschlue** [comment]
@jneiva08 Dan seems to be busy with other things lately, but by all means, go ahead.
Note that new additions will require package suffixes (PW/DBT).

**Comment by jneiva08** [comment]
@chschlue have created new PF for the symbols - https://github.com/KiCad/kicad-symbols/pull/2745
have already removed from this PR

**Comment by jneiva08** [comment]
@chschlue, make sense in this PR add DBT? have already updated in the new PR

**Comment by jneiva08** [comment]
@chschlue have made the changes you requested in the new branch, in this should rename to have DBT?
if the new branch is ready to merge let me know to fix conficts

**Comment by chschlue** [comment]
Yes, please add DBT.

**Comment by jneiva08** [comment]
@chschlue to fix this conflict only replace the old name/description by the new, right?

**Comment by chschlue** [comment]
@jneiva08 Oops. Sry. My bad. Should have paid more attention.

I somehow missed that 76940 was a fix from the start, not a new addition.
Now that we have a change in name *and* in the symbol itself I think the cleanest solution would be to add the new style BQ76940DBT while leaving the old BQ76940 alone, to be removed for v6.

**Comment by jneiva08** [comment]
@chschlue have fixed the issues, hope i didn't break anything.

the changes made only be merged on V6 (I hope)
Did add the other IC's but have now break to new branch

**Comment by myfreescalewebpage** [comment]
@jneiva08 can you solve the branch conflict please ?

**Comment by jneiva08** [comment]
@myfreescalewebpage,  hope i didn't miss anything

**Review by chschlue — APPROVED** [review]
Thanks.

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
