### PR TITLE
BUS Mini-PCIe: Add MP pin

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
According to discussion at https://github.com/KiCad/kicad-footprints/pull/1124, addition of MP pin (NC, Passive)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful

Capture

- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Note: I wonder about the name of the pin : NC or MP ? Not found examples in the library actually...

**Comment by myfreescalewebpage** [comment]
Just renamed "NC" to "MP" to solve travis error.

**Comment by myfreescalewebpage** [comment]
@evanshultz ping!

**Comment by evanshultz** [comment]
Thanks!

A little ugly that the pin number text (here it's a pin name) `MP` bangs into the symbol outline. But that's according to KLC for two-character pins and we want these symbols to mate with the new footprints.

**Pull request merged**
