### PR TITLE
Device: Add a new generic ABRG led

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://katalog.we-online.com/led/datasheet/150141M173100.pdf

Screenshot from 2019-05-16 15-25-32

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco I have made a review of your pull request:

- [ ] Reference should be `D`, not U
- [ ] You can uncheck "Place pin names inside" (position offset will be 0)

My reference is `LED_ARGB`

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
