### PR TITLE
Si5342/44/45: Jitter Attenuators / Clock Multipliers.

### PR DESCRIPTION
**Pull request by ObKo**
Datasheet: https://www.silabs.com/documents/public/data-sheets/Si5345-44-42-D-DataSheet.pdf

si5342

Footprint: https://github.com/KiCad/kicad-footprints/pull/2202

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @AUTHOR, thanks for contributing,

A few comments I have during my review:

Si5342A-D-GM
- [ ] Name should be "Si5342A-D" (the last digits are the temperature range which is discard in the library) - Same comment for the aliases
- [ ] Fp filter: `QFN*1EP*7x7mm*P0.5mm*`
- [ ] Pin length: 100mil (symbol < 100pins)
- [ ] NC pin 22 should be added, Invisible, on the border outline of the symbol

Si5344A-D-GM
- [ ] Name should be "Si5344A-D" (the last digits are the temperature range which is discard in the library) - Same comment for the aliases
- [ ] Fp filter: `QFN*1EP*7x7mm*P0.5mm*`
- [ ] Pin length: 100mil (symbol < 100pins)
- [ ] NC pin 22 should be added, Invisible, on the border outline of the symbol

Si5345A-D-GM
- [ ] Name should be "Si5345A-D" (the last digits are the temperature range which is discard in the library) - Same comment for the aliases
- [ ] Footprint has too large EP, should be `Package_DFN_QFN:QFN-64-1EP_9x9mm_P0.5mm_EP5.2x5.2mm`
- [ ] Fp filter: `QFN*1EP*9x9mm*P0.5mm*`
- [ ] Pin length: 100mil (symbol < 100pins)
- [ ] RSVD pin 5, 20, 21, 55 and 56 should be added, Invisible, on the border outline of the symbol

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hello @ObKo thanks, no more comment, just need to wait the footprint now

**Comment by chschlue** [comment]
FP merged.

**Comment by chschlue** [comment]
Oops.

FP merged. For real this time ;)

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by evanshultz** [comment]
FYI, if you look at the Travis details you should see a Restart Build button in the upper right that allows you to re-run CI without having to close and re-open the PR. I believe you need to log in, but you can do it with your existing GH account.
image

**Comment by myfreescalewebpage** [comment]
@evanshultz I know this button, but 95% of the time it is not visible for me. See following screenshot from an other PR.

Capture

I'm using Chrome, maybe it's because of the navigator ?

**Comment by chschlue** [comment]
Funny, I never noticed that button before.

**Comment by myfreescalewebpage** [comment]
ahahah maybe because you have this bug too :) sometimes I have it but it's very rarely

**Pull request merged**
