### PR TITLE
Add Abracon ABx8x5 RTCs

### PR DESCRIPTION
**Pull request by evanshultz**
Designed to have interchangeable symbols.

https://abracon.com/Precisiontiming/AB08X5-RTC.PDF
image
image

https://abracon.com/Precisiontiming/AB18X5-RTC.pdf
image
image

The package drawings are identical and at https://abracon.com/Support/PackageDrawing/Precisiontiming/AB08XX.PDF and https://abracon.com/Support/PackageDrawing/Precisiontiming/AB18XX.PDF (no idea why they need to be separate...). I chose a nearly-compatible footprint submitted at https://github.com/KiCad/kicad-footprints/pull/1199. The lead width and length is slightly different, but our footprint names don't capture that info so how could we tell? In addition, the footprint used is a VQFN but the height of that part and these RTCs are all in the same range so no real difference to the 3D model.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz, now reviewing this one :)

A few comments I have during my review:

For the 4 symbols:

- [ ] Footprint filter: I suggest `VQFN*1EP*3x3mm*P0.5mm*` (as done for TQFP, HTSSOP...)
- [ ] XO should be Output

Cheers,
Joel

**Comment by evanshultz** [comment]
Changed XO pin type. For the FP filter, I felt leaving off the `V` gave the most choices if the user doesn't keep the default footprint since the differences between QFN and VQFN and TQFN are often arbitrary. I alluded to this in the original post above, but maybe this is silly. What do you think?

**Comment by myfreescalewebpage** [comment]
Well actually in the library we have both: some device have complete package name `VQFN...` and some have `*QFN...`. I have a preference for the first one which is the best to not leave the place to questions during the reviews. I think the majority of users do not play with the package and keep the default anyway...

**Comment by evanshultz** [comment]
Understood. Since we're using the generator it's easy to make a footprint with any name, but some vendors call a package VQFN which is identical to a TQFN by another vendor. Quite messy. I changed to VQFN but this might be something to keep an eye on and see if we run into it frequently.

Thanks for reviewing!

**Comment by myfreescalewebpage** [comment]
Yes I agree, it's messy.
I think you made an unwanted modification on AB0805, EXTI has been renamed to EXT which is wrong.
Joel

**Comment by evanshultz** [comment]
Why yes, I did mess that up. Thanks for noticing. Fixed now.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
