### PR TITLE
Add Si5351x-B-Gx

### PR DESCRIPTION
**Pull request by einball**
This commit adds the Si5351A-B-GT (3 clock outputs) and the Si5351[A/B/C]-B-GM (8 outputs) programmable clock oscillators from Silabs. 

The datasheet can be found [here](https://www.silabs.com/documents/public/data-sheets/Si5351-B.pdf).

---
si5351a-b-gt
si5351a-b-gm
si5351b-b-gm
si5351c-b-gm
---
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @einball , thanks for contributing,

A few comments I have during my review:

Si5351A-B-GM:
- [ ] The description should ends with the package name: `, QFN-20`
- [ ] According to the ordering info page 29 of the datasheet, this part as no VCXO, to be removed in the description
- [ ] I do not agree with the package name, wrong EP size, this should be `Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm`. It does not exist and should be proposed scripted with footprint generator available at https://github.com/pointhi/kicad-footprint-generator
- [ ] The footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`

Si5351A-B-GT:
- [ ] The description should ends with the package name: `, MSOP-8`
- [ ] According to the ordering info page 29 of the datasheet, this part as no VCXO, to be removed in the description
- [ ] Pin 7 should be Power Input

Si5351B-B-GM:
- [ ] The description should ends with the package name: `, QFN-20`
- [ ] I do not agree with the package name, wrong EP size, this should be `Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm`. It does not exist and should be proposed scripted with footprint generator available at https://github.com/pointhi/kicad-footprint-generator
- [ ] The footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`

Si5351C-B-GM:
- [ ] The description should ends with the package name: `, QFN-20`
- [ ] According to the ordering info page 29 of the datasheet, this part as no VCXO, it has CLKIN, to be changed in the description
- [ ] I do not agree with the package name, wrong EP size, this should be `Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm`. It does not exist and should be proposed scripted with footprint generator available at https://github.com/pointhi/kicad-footprint-generator
- [ ] The footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`
- [ ] Graphic Style of pin 6 should be "Line"

All symbols:
- [ ] I2C/X1/XB etc. are not always at the same place across the devices, it should be great to decide a design and apply it on all devices, for example following the block diagrams pages 10/11 of the datasheet that are very nice.

Cheers,
Joel

**Comment by einball** [comment]
Thanks for your thorough review, Joel!

I have updated the symbols accordingly.

See KiCad/kicad-footprints/pull/1475 and kicad-footprint-generator/pull/311.

**Comment by myfreescalewebpage** [comment]
Great job done here @einball 
I just realized my last comment make you moving the VDDOA/B/C/D pins to the left, but this not acceptable in the KLC. I was expecting only a modifications of pins on the left side of the symbols. Please can you revert position of VDDO* pins to the top of the symbol ? Thanks. Then just need to wait the integration of the footprint.

**Comment by myfreescalewebpage** [comment]
Thanks, now just need to wait the footprint !

**Comment by einball** [comment]
Footprint has been merged.

**Comment by myfreescalewebpage** [comment]
@einball thanks for the info, merging the symbol.

**Pull request merged**
