### PR TITLE
Add LM5164 

### PR DESCRIPTION
**Pull request by Pizutti**
ADD LM5164 DC-DC buck
datasheet(1): [https://www.ti.com/document-viewer/LM5164/datasheet/pin-configuration-and-functions-snvsae38729#SNVSAE38729](url)
datasheet(2): [https://www.ti.com/lit/ds/symlink/lm5164.pdf?ts=1598311864250&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FLM5164%253FHQS%253DTI-null-null-octopart-df-pf-null-wwe](url)
Image: 
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Pizutti , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "LM5164DDA"
- [ ] Footprint should be `Package_SO:HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.1mm_ThermalVias`
- [ ] Description shoulds ends with the exact package name: `1A synchronous buck converter with ultra-low IQ, 6V - 100V input, adjustable output voltage, HSOP-8`
- [ ] PGOOD should be Open Collector
- [ ] EP should be Passive
- [ ] Regulators have input on the left and output on the right and moreover the dimensions of the symbol are too much important. Proposition below which is more conform with the lib:

Capture

Cheers,
Joel

**Comment by Pizutti** [comment]
New image: image

**Comment by myfreescalewebpage** [comment]
Thanks. Few new comments:

- [ ] You have duplicated the symbol. Please remove "LM5164"
- [ ] The size of the symbol is not aligned with the 100mil grid. Please decrease the top of the symbol by 50mil
- [ ]The previous fp filter was correct: `HSOP*1EP*3.9x4.9*P1.27mm*`
- [ ]Pin offset should be 20mil (travis error)

Joel

**Comment by Pizutti** [comment]
Hi Joel!

I haven't closed Kicad before making the commit, I believe this is the couse of the duplicated LM5164, i have another question, I'm on Windows 10, I'm runnig python mostly in Anaconda and could not find any way to use the Kicad Scripts to check the libs, any idea how I can do that? I'm not sure what is this 20mil offset.

Regards,
Pablo Pizutti

**Comment by myfreescalewebpage** [comment]
I don't remember where are the scripts exactly, I personally push to GitHub and then check if the travis result is nice or not.

For the pin offset see below: (should be 20mil)

Capture

Joel

**Comment by chschlue** [comment]
That reminds me...
https://gitlab.com/kicad/code/kicad/-/issues/5373

**Comment by chschlue** [comment]
Good news, problem solved.

**Comment by myfreescalewebpage** [comment]
Thanks! Merging

**Pull request merged**
