### PR TITLE
Add OPAx197 op amps

### PR DESCRIPTION
**Pull request by chschlue**
DS http://www.ti.com/lit/ds/symlink/opa197.pdf

OPA197xD
OPA197xDBV
OPA197xDGK
OPA2197xD
OPA2197xDGK
OPA4197xD
OPA4197xPW

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
Thanks for submitting these.
I haven't checked but, can't these be aliases of existing opamp symbols?

**Comment by chschlue** [comment]
It depends. The -DBV variant could be an alias of MCP6L91T-EOT, for example, but I don't think there are fully specified symbols for VSSOP-8 and TSSOP-14.

**Comment by diegoherranz** [comment]
It's a pity. As you say, there aren't fully specified symbols for VSSOP-8 and TSSOP-14, but a few of them can be aliases still:

- OPA197xD -> OPA333xxD
- OPA197xDBV -> MCP6L91T-EOT
- OPA197xDGK -> OPA1641 would work if it was fully defined... 
- OPA2197xD -> NCS2325D
- OPA2197xDGK -> LM2904 would work if it was fully defined... 
- OPA4197xD -> LM2902 would work if it was fully defined... 
- OPA4197xPW -> LM2902 would work if it was fully defined... 

Can you turn the 3 that match into aliases? We need to avoid creating extra symbols unless really required.
In fact, after merging this PR, some parts could be modified to make them fully defined. E.g. OPA2333xxDGK could become an alias of OPA2197xDGK better than an alias of LM2904 as it is at the moment.

Thanks!

**Comment by chschlue** [comment]
Done.
Thanks for checking the existing symbols.

**Comment by evanshultz** [comment]
FYI, I created https://github.com/KiCad/kicad-symbols/issues/164 to capture the work of splitting up this type of symbol by package.

**Comment by diegoherranz** [comment]
I've checked pinouts, footprints, footprint filters, descriptions and datasheet links and it all looks OK, so merging.

Thanks for your contribution!

**Pull request merged**
