### PR TITLE
Addition of INA333 Instrumentation Amplifer

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of INA333 Instrumentation Amplifier. I've created two symbols, one for the VSSOP variant, another for the WSON variant (with a hidden NC pin for the exposed pad)

Datasheet URL: https://www.ti.com/lit/ds/symlink/ina333.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aewallin** [comment]
the datasheet doesn't say much about the connection of PAD - except some generic notes on heat-sinking at the end.
I would think it is better to have a visible PAD-pin so it can optionally be used for something?

**Comment by myfreescalewebpage** [comment]
Hi @jamesrlucas , thanks for contributing,

A few comments I have during my review:

On the WSON version:
- [ ] The EP size is not correct, you should indicate the exact footprint
- [ ] The comment of @aewallin is correct, the EP pin hsould be available, type Passive. The name of expose pad are "EP" in the library. Possible correction:

Capture

No comment on the VSSOP version.

Cheers,
Joel

**Comment by jamesrlucas** [comment]
All done! I've created a new WSON footprint with the correct EP size and submitted it (linked above)

Thanks,
James

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by jamesrlucas** [comment]
The Footprint has now been merged :)

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by jamesrlucas** [comment]
Thanks!

**Pull request merged**
