### PR TITLE
Add CP2102N QFN28

### PR DESCRIPTION
**Pull request by lmoelleb**
Add the CP2102N usb bridge.

Based on the QFN-24 version with the following updates (besides the pin changes obviously):

- Pin length set to 0.1"
- Pins interfacing circuit moved to the right side, interface to USB port on the left.
- Active low pins marked as such (overline)
- Full pin names (secondary functionality).
- Stacked ground pins.

Datasheet:
https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf

image

I kept A01-G in the name to match the existing QFN24 chip. It's hardware revision (A), firmware (01), and temperature grade. I guess a hardware revision or firmware change **could** add pin functionality, though the temperature grade is not something I would include with a new symbol created from scratch.
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lmoelleb , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with the package name : `, QFN-28`. If you can fix the other CP2102N version on this subject, it's nice too so we will see the difference between the parts.
- [ ] Footprint is not correct, should be `Package_DFN_QFN:QFN-28-1EP_5x5mm_P0.5mm_EP3.35x3.35mm` (see also travis output)
- [ ] Footprint filter should be `QFN*1EP*5x5mm*P0.5mm*`
- [ ] Name of pin 1 should ne `DCD`
- [ ] Name of pin 1 should ne `DCD`
- [ ] Name of pin 1 should ne `DCD`

Ok for the other changes compared to the other variant.

Cheers,
Joel

**Comment by lmoelleb** [comment]
Updated screenshot:
image

**Comment by lmoelleb** [comment]
@myfreescalewebpage 
Change of VDD to passive gives a Travis error:
    Power pins should be of type POWER INPUT or POWER OUTPUT
     - Pin VDD (6) @ (0,1300) is of type PASSIVE
Anything I need to change to fix this, or can it be ignored in this case?

**Comment by myfreescalewebpage** [comment]
Thanks for the modifications!

A few details:

- [ ] Package name format in the description are "QFN-24" and "QFN-28", with "-" character.
- [ ] REGIN to the left of VDD is better IMO, it's suppose to come from the USB bus, see datasheet page 8. Proposition below:

capture

Joel

**Comment by lmoelleb** [comment]
image

**Comment by myfreescalewebpage** [comment]
Great job ! Thanks. No more comment to do, merging.
If you want to make the QFN-20 version too, that's with pleasure we will review it :)

Joel

**Comment by lmoelleb** [comment]
@myfreescalewebpage the QFN-20 pull request is created, so have fun :). It might be a day or two before I can address any comments.

**Pull request merged**
