### PR TITLE
Add split '240 and '244 symbols

### PR DESCRIPTION
**Pull request by evanshultz**
Logic symbols split into pieces are often helpful to place around the schematic, I think. Right now our library is mixed up. The existing '240 and '244 are single symbols but '125 is split. Here are split '240 and '244 until the entire lib is overhauled.

http://www.ti.com/lit/ds/symlink/sn74ls244.pdf
image
image
image
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
CI errors are existing from the '125 symbol I used to make these.

**Comment by evanshultz** [comment]
It looks like I missed a period in my email address so CLA is barfing. While Gmail doesn't care about that apparently the CLA does. What is the way to proceed? Obviously it's safe to say I agree.

**Comment by evanshultz** [comment]
For to add the symbol for hysteresis:
image

**Comment by myfreescalewebpage** [comment]
I know you agree with the CLA ;-)
Maybe you have changed your mail address or committed with another one ? CLA is based on the mail address or your account.
Merging.

**Pull request merged**
