### PR TITLE
Audio: Add CS4270 Codec

### PR DESCRIPTION
**Pull request by zonque**
The CS4270 is a 24-Bit, 192-kHz Stereo Audio CODEC in a TSSOP-24 package.

The datasheet is here:

  https://statics.cirrus.com/pubs/proDatasheet/CS4270_F1.pdf

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

image

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for submitting this nice symbol!

1. What about aligning SDIN to ADOUT and also the analog in/out pins? Perhaps digital and analog audio at the top with control signals below?
1. Would you slide FILT and VQ to the bottom of the right side and change to Passive type?
1. Please move pins 21 and 24 to the right side.

When you make changes, please don't force push so that reviewing is easier.

**Comment by zonque** [comment]
Thanks for the review. Changed accordingly.

image

**Comment by evanshultz** [comment]
Here is the current symbol:
image

Two things come to mind:
1. The top of the symbol can move down 100mil. Fortuitously, that also balances the rectangle height.
1. The mute pins will now have to cross over SDOUT. What about this?
image

**Comment by zonque** [comment]
Fine with that. Do you have a version that you can just commit or do you want me to replicate your changes?

**Comment by evanshultz** [comment]
I didn't save anything, just played around and took a screenshot.

**Comment by zonque** [comment]
Okay, added those changes now.

**Comment by zonque** [comment]
Any further comments on this?

**Comment by zonque** [comment]
Oh, sorry. Now.

**Comment by evanshultz** [comment]
Nice. Thanks!

**Pull request merged**
