### PR TITLE
Logic_LevelTranslator: Add SN74AVC4T245PW

### PR DESCRIPTION
**Pull request by zonque**
This is Dual 4-bit bus transceiver with configurable voltage translation
and 3-state outputs.

The datasheet is here:

  https://www.ti.com/lit/ds/symlink/sn74avc4t245.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @zonque , thanks for contributing,

A few comments I have during my review:

- [ ] Name of pin 15 should be `1~OE~`
- [ ] Name of pin 14 should be `2~OE~`
- [ ] Pins 14 and 15 are VCCA power doamin and should be moved to the left. See application example page 14 of the datasheet.

Cheers,
Joel

**Comment by evanshultz** [comment]
Just a quick note that removing the trailing tilde and leaving it render the pin name identically. I recall removing it in recent PRs.

**Comment by zonque** [comment]
Thanks for the review. All 3 issues addressed now!

**Comment by zonque** [comment]
image

**Comment by myfreescalewebpage** [comment]
Thanks @zonque for the fixes.
An additional comment: can you add an extra space between 2DIR and 1A1 pins by moding the 4 top pins 100mil to the top ? This will also permit to center the symbol.
Joel

**Comment by zonque** [comment]
Yes, much nicer, thanks.

image

**Comment by myfreescalewebpage** [comment]
Perfect, thanks !! Merging.

**Pull request merged**
