### PR TITLE
Led avago

### PR DESCRIPTION
**Pull request by jneiva08**
Added new led Avago/Broadcom ASMT-YTB7-0AA02 to already exist, and changed footprint filter to [#657](https://github.com/KiCad/kicad-footprints/pull/657) 

datasheet: https://docs.broadcom.com/docs/AV02-3793EN

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Because the dedicated foot print is 
LED_SMD:LED_Avago_PLCC6_3x2.8mm

Perhaps the FP should be changed from
LED?Avago?PLCC6*3x2.8mm*
into
LED?Avago?PLCC6**?**3x2.8mm*

**Comment by jneiva08** [comment]
Have done the modifications.
Thanks for your help.

**Comment by Misca1234** [comment]
Looks good, thx

**Comment by Misca1234** [comment]
The last change he made was the FP, into
LED?Avago?PLCC6?3x2.8mm*

But I recall a couple of discussion, about this
either the call of the day was to use '*' for one char, and another was '?' for one char

Best would be of course if kicad could create the FP it self, if the user choose a specific footprint,

**Pull request merged**
