### PR TITLE
Fix some footprints in Isolator.lib

### LINKED ISSUE #792: Incorrect footprints in Isolator.lib
As reported by @alaut at https://github.com/KiCad/kicad-symbols/issues/520#issuecomment-409347596:

>It appears to me that TLP291-4 and others in the __Isolators.lib__ library are associated with the wrong footprints. I'm not nearly experienced enough to make any reliable attempt to correct through these yet... though I plan to contribute sooner than later.
>
>For example. I'm not sure if technically the footprint associated with LTV-847S is correct or within a certain tolerance. Datasheet indicated 9mm width, footprint appears to be 9.53mm. I'm inclined to believe I'm wrong here.
>
>TLP291-4 is definitely wrong though by a lot unless I'm missing something. According to the [datasheet](http://bit.ly/2Oyhfaj), the pitch is 1.27mm not 2.54 as associated in _Package_DIP:SMDIP-16_W7.62mm_

I agree that TLP291-4 is definitely wrong, and LTV-847S looks suspicious as well.

### PR DESCRIPTION
**Pull request by dsa-t**
Fixes #792.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for tackling outstanding issues!

Can you please include datasheet links any other relevant information you found here in the PR comments to make review easier?

**Comment by dsa-t** [comment]
SFH617A-2X009T
SFH617A-2X019T
http://www.vishay.com/docs/83740/sfh617a.pdf

TLP185
https://toshiba.semicon-storage.com/info/docget.jsp?did=11791&prodName=TLP185

TLP185(SE
https://toshiba.semicon-storage.com/info/docget.jsp?did=14111&prodName=TLP185(SE

TLP291
https://toshiba.semicon-storage.com/info/docget.jsp?did=12884&prodName=TLP291

TLP291-4
https://toshiba.semicon-storage.com/info/docget.jsp?did=12858&prodName=TLP291-4

**Comment by evanshultz** [comment]
`SFH617A-2X009T` is a copy of `TLP281` but with the correct package, right? Since we can't know which package option the user will select, I think a different approach is better. See `VO615A` where I didn't assign a default footprint but instead constructed footprint filters that match all applicable footprints.

The Toshiba packages are odd sizes that don't match any footprints in our library. And since the footprints are in some cases smaller than the actual part it means collisions with a closely-placed component could happen. I don't like that. Would you be willing to make the correct footprints? (Even though these are NRND the package is still being used for active parts.) Rene's nice gullwing generator should make this relatively easy. We need:
- SOIC-4_4.55x3.7mm_P2.54mm
- SOIC-4_4.55x2.6mm_P1.27mm
- SOIC-16_4.55x10.3mm_P1.27mm

Package drawings here for easy reference:
TLP185:
image

TLP291:
image

TLP291-4:
image

I also notice that `TLP(SE` uses a disallowed characters according to http://kicad-pcb.org/libraries/klc/G1.1/. Let's change the open paren to a `x`. Who in God's name would make a PN like that?!

**Comment by antoniovazquezblanco** [comment]
@dsa-t will you be working on this anytime?

**Comment by antoniovazquezblanco** [comment]
@dsa-t ping!

Closing and reopening to see if CLA resets to the previous signed state and to re-trigger travis.

I would vote to submit the creation of footprints as an issue for the footprints repo to be done in the future. For the rest of the changes I will wait for @dsa-t to come up and if not I will try to take over this before 5.0.2.

**Comment by antoniovazquezblanco** [comment]
Re push in https://github.com/KiCad/kicad-symbols/pull/1177

**Pull request closed without merging**
