### PR TITLE
Fix active-low input prefixes

### PR DESCRIPTION
**Pull request by opatut**
This PR fixes various issues with pin naming as described in #2367 that are either incorrect or in violation of KLC S4.7. See the linked issue for a description of the problems and detailed discussions on the more disputable changes (notably `74173`).

### CODE REVIEW

**Comment by opatut** [comment]
I'm not sure how to handle the failing travis checks since I don't intend on fixing everything wrong with the changed symbols, just one certain type of problem. Does this qualify as an exception to ignore the build output or will I have to fix all the issues in all the improved symbols?

**Comment by chschlue** [comment]
It is generally not required to fix all bugs at once, but:
- [ ] Please change ~NSS to ~SS instead of NSS (see https://kicad-pcb.org/libraries/klc/S4.7/)

**Comment by chschlue** [comment]
@opatut ping

**Comment by opatut** [comment]
@chschlue Sorry I thought I had fixed and pushed all requested changes. There you go, now I think I have.

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
