### PR TITLE
Removed placeholder x form PIC18(L)F25/26K83x-x_SP. It is now PIC18(L…

### PR DESCRIPTION
**Pull request by fragraider**
…)F25/26K83-x_SP. The Dip package (SP) has no option at this possition, making the x misleading.

This error was discovered after merging:
https://github.com/KiCad/kicad-symbols/pull/1120
Details at the end of that thread. 

This pull request has therefore this single letter removed form the part numbers.

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/40001943A.pdf

billede

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Thanks @fragraider for this, good catch !

For me, regarding to product identification system page 840 of the datasheet, the part should be `PIC18F25K83-xSP`, `PIC18F26K83-xSP`, `PIC18LF25K83-xSP` and `PIC18LF26K83-xSP` (no "_").

Let me known what do you think.

Joel

**Comment by fragraider** [comment]
Hello Joel

I must admit that I do not really have an opinion:
- The "_" marks the spot where the footprint would have an /, but I find it visually disturbing, even ugly.
- No "_" would maybe leave the reader confuse as to where the temperature indication ends and the package indication starts. (If the reader is looking for such a hint).

I am certainly more than happy to remove the underscore, especially the more I look at your comment. The small x really differentiates the itself form the capital SP (And would so in the other footprints too).

Hannes

P.S.: All honor goes to @diegoherranz, he was really patient and helpful and found the issue right after he merged https://github.com/KiCad/kicad-symbols/pull/1120

**Comment by myfreescalewebpage** [comment]
Thanks for the answer, I have based my comment also on existing devices in the library. Most of them do not have "_", just look at the PIC18F family. Some few of t he PIC have "_" but I suspect this is not really conformed to the datasheet too. I also realize many do no discard the temperature letter, but they should.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Comment by fragraider** [comment]
I thought to just remove the underscore. Should it be decided to go back, I get a chance to learn how to return to a previous state in git :)

@myfreescalewebpage 
> I also realize many do no discard the temperature letter, but they should.

From the KLC I understood that every aspect of a part number should be preserved?
http://kicad-pcb.org/libraries/klc/S2.2/

Here is a screenshot of what was comited:
billede

**Comment by fragraider** [comment]
Thanks!

**Comment by myfreescalewebpage** [comment]
@fragraider next release will be 6.0, so it is permitted to break symbols, particularly to enhance them according to the KLC, if you wish, submit a PR we will review with pleasure :)

**Comment by fragraider** [comment]
@myfreescalewebpage
I think the symbol is currently compliant! I will soon get working on the versions for the other footprints :)

**Comment by fragraider** [comment]
@myfreescalewebpage
Doh, sorry, it took some time to get your comment... Yeah, would actually be a nice effort :)

**Comment by poeschlr** [comment]
@fragraider sadly this was wrong information. The next release will be 5.1.1 and after that 5.1.2, .... (v6 is at least two years away.)

This means for the next year or so we will need to be very careful of what to include. This particular pull request is on the brink to be honest and should have probably been delayed till we truly start with v6.

But it is low impact enough and fixes something that can be considered a bug if you squint hard enough. Meaning i will keep it in for 5.1.1. (Just be aware of that for the future.)

**Comment by fragraider** [comment]
@poeschlr I kinda started to make kopies for this component for each footprint available. Should that wait too (I.e. I would NOT make a pull request when I would be ready with the those)?

The currently, there is only the DIP package included.

**Comment by poeschlr** [comment]
Adding new things never is a problem. Changing existing assets in a way that breaks existing installations is. (This is mainly because kicad right now has no proper caching for symbols. The cache lib/rescue lib stuff simply has too many places where it can go wrong. It is unintuitive for users which leads to many projects being broken and sadly also breaks way to often even if the user does not really do something wrong. Not even wayne fully trusts that feature this is why we are advised to limit the impact of our changes.)

**Comment by fragraider** [comment]
@poeschlr Understood! Then I think we where good, but will not modify anything in the current library, thanks for the info!

**Comment by myfreescalewebpage** [comment]
Thanks @poeschlr for the info !

**Pull request merged**
