### PR TITLE
Adding Samtec ASP-134486-01 connector (ASP-134602-01 alias)

### PR DESCRIPTION
**Pull request by ki5libs**
Adding Samtec ASP-134486-01 connector (ASP-134602-01 alias)
[Datasheet](http://suddendocs.samtec.com/prints/asp-134486-01-mkt.pdf)
Part A (from 10 parts total) screenshot:
ASP_new

[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/1515)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks for this alias.
The review is ok for me but I would like @evanshultz who have a larger experience with connectors to have a look too: it's an alias of an existing connector. The original is THT, the new one is SMD version. I wonder for this kind of very specific part if they should be atomic or not.... ?
Joel

**Comment by myfreescalewebpage** [comment]
@evanshultz if you can share your experience here, thanks

**Comment by myfreescalewebpage** [comment]
@evanshultz ping! If you can look at my previous comment here please. Thanks Joel

**Comment by myfreescalewebpage** [comment]
Back to this PR, for me it's great.
@ki5libs can you solve the branch conflict then I will merge.
Thanks

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

conflict is solved.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
