### PR TITLE
Add OPA1612xxD operational amplifier

### PR DESCRIPTION
**Pull request by aurel32**
This is just an alias to the existing LM2904 OP amp. The SON-8 version would need to be aliased to a different symbol as it has an exposed pad, that's why this patch only concerns the SOIC-8 version.

The datasheet can be found there: http://www.ti.com/lit/ds/symlink/opa1612.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for contributing to KiCad! It's because of a willing community like you that the library can grow and improve.

You will find a list of rules and guidelines for the KiCad library at http://kicad-pcb.org/libraries/klc/. Please see that webpage for more information about the review items below.

This looks fine except for one thing: If you can change `OPA1612xxD` to `OPA1612AxD` I'll merge.

**Comment by aurel32** [comment]
Thanks for the review. I have just pushed a new version with the requested changes.

**Comment by evanshultz** [comment]
@aurel32 
I added this part to my PR at https://github.com/KiCad/kicad-symbols/pull/747 that touched the same library. I'd already started working on my PR, and doing all changes at once will avoid any branches being in conflict while pushing all changes to the library.

Is this OK with you? If so, do you mind closing this PR in favor of mine?

**Comment by aurel32** [comment]
> Is this OK with you? If so, do you mind closing this PR in favor of mine?

As long as the OPA1612 symbol get merged, I don't really care how it's done. I am therefore closing this PR.

**Pull request closed without merging**
