### PR TITLE
Add TPS703x and TPS704x

### PR DESCRIPTION
**Pull request by evanshultz**
- http://www.ti.com/lit/ds/symlink/tps703.pdf
image

- http://www.ti.com/lit/ds/symlink/tps704.pdf
image

I also fixed the pin name offset of the symbol I used as the seed.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
@antoniovazquezblanco I haven't actually had time to look at this yet, so I'll remove the `in review` tag until I have time to actually go through this PR.

**Comment by evanshultz** [comment]
Note that the footprints are missing pending resolution of how to name footprints with a top thermal pad.

**Comment by DanSGiesbrecht** [comment]
@evanshultz based on both datasheets, the parts don't have a top-facing exposed pad.

**Comment by evanshultz** [comment]
Oh right. Thank you. I confused myself. I'll make the missing footprint then...

**Comment by DanSGiesbrecht** [comment]
No problem!

**Comment by evanshultz** [comment]
Footprint submitted at https://github.com/KiCad/kicad-footprints/pull/995.

**Comment by evanshultz** [comment]
Dang. Messed up the footprint name. Fixed footprints submitted at https://github.com/KiCad/kicad-footprints/pull/1017.

**Comment by evanshultz** [comment]
@DanSGiesbrecht 
Since you picked up this PR, can you merge if all is well?

**Pull request merged**
