### PR TITLE
Added EFM32HG108F32 and EFM32HG108F64.

### PR DESCRIPTION
**Pull request by cnieves1**
Added EFM32HG108F32 and EFM32HG108F64.
Datasheet: https://www.silabs.com/documents/public/data-sheets/efm32hg-datasheet.pdf
  
imagen

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cnieves1 , thanks for contributing,

A few comments I have during my review:

EFM32HG108F32G-C-QFN24
- [ ] Name of the device should be "EFM32HG108F32-C-QFN24"
- [ ] Footprint filter should be `QFN*1EP*5x5mm*P0.65mm*`
- [ ] Name of pin 2 is "IOVDD_0"
- [ ] Name of pin 9 is "AVDD_2"
- [ ] Name of pin 12 is "AVDD_0"
- [ ] Name of pin 22 is "IOVDD_5"
- [ ] You can add a space between each port, it's usual for MCU in the lib

EFM32HG108F64G-C-QFN24
- [ ] Name of the device should be "EFM32HG108F64-C-QFN24"

EFM32HG308F32G-C-QFN24
- [ ] Name of the device should be "EFM32HG308F32-C-QFN24"
- [ ] Footprint filter should be `QFN*1EP*5x5mm*P0.65mm*`
- [ ] Name of pin 2 is "IOVDD_0"
- [ ] Name of pin 9 is "AVDD_2"
- [ ] Name of pin 12 is "AVDD_0"
- [ ] Name of pin 22 is "IOVDD_5"
- [ ] You can add a space between each port, it's usual for MCU in the lib

EFM32HG308F64G-C-QFN24
- [ ] Name of the device should be "EFM32HG308F64-C-QFN24"

Cheers,
Joel

**Comment by cnieves1** [comment]
Hi Joel,
Changed pin names, footprint filter and make some space between ports on right side.
Left side is unchanged so symbol size is not increased...

PDx are very close to DECOUPLE pin, but I wanted to keep power pins with same name at the same position, so EFM32HG108 and EFM32HG308 could be easily interchanged.

Device names are correct. SILabs changed the part number without documenting it in the datasheet. Don't ask me why... 

If you look at any distributor, you won't find any EFM32HGx08Fxx-C-QFN24 part number. Example at Mouser:
  https://www.mouser.es/Search/Refine?Keyword=%22EFM32HG108F32

I even asked a distributor, who asked technical people from SI Labs, and they confirmed it.

Thanks!

**Comment by cnieves1** [comment]
Captura de pantalla de 2020-04-07 22-12-18
Captura de pantalla de 2020-04-07 22-12-31

**Comment by myfreescalewebpage** [comment]
"I even asked a distributor, who asked technical people from SI Labs, and they confirmed it." => OK.

Extra space between all the port is better. The position of power pins to have both devices consistent is great.

Proposition based on 308, there is place for PD pins in front of PB7/PB8:

Capture

**Comment by cnieves1** [comment]
Here they are:
Captura de pantalla de 2020-04-09 00-14-40
Captura de pantalla de 2020-04-09 00-14-49

**Comment by myfreescalewebpage** [comment]
I'm sorry it doesn't looks very nice... We usually make an effort to have power pin centered and moreover DECOUPLE is Passive so should not be on the top. Why do you want to have something so much compact ?

**Comment by cnieves1** [comment]
Sorry, I didn't notice the DECOUPLE pin.
Here they are. Now IOVDD_0 and VSS power pins are centered. They are not as tall as your example, but I like these more:
Captura de pantalla de 2020-04-10 12-44-05
Captura de pantalla de 2020-04-10 12-44-12

**Comment by myfreescalewebpage** [comment]
Thanks, for me it's clearly better design. Hope you are also convinced :)
Merging.

**Pull request merged**
