### PR TITLE
Added TPS782xx LDO family in SOT-23.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: http://www.ti.com/lit/gpn/tps782

imagen

imagen

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by diegoherranz** [comment]
Thanks for your submission.

I think all these could be aliases of "TLV71209_SOT23-5" to avoid creating a new symbol. Could you do so if you agree?

Thanks.

**Comment by cnieves1** [comment]
I'm afraid that is not posible... Did you noticed this part has two GND pins while TLV71209 has only one GND pin?

**Comment by diegoherranz** [comment]
I had missed that. Good point.
I'll review as is, then.

Thanks!

**Comment by diegoherranz** [comment]
A couple of comments:
- The hidden GND pin should be passive. See [KLC S4.3](https://kicad-pcb.org/libraries/klc/S4.3/).
- TPS78222DDC doesn't seem to exist? Not in this package.

Thanks!

**Comment by diegoherranz** [comment]
Also, could you say SOT-23-5 instead of SOT-23 in the description fields? For consistency with other similar parts.
Thanks!

**Comment by diegoherranz** [comment]
Thanks for the changes.
Travis complains about the hidden GND pin but I think it's all correct (@KiCad/librarians, is this a known but?).
Merging.

**Pull request merged**
