### PR TITLE
added symbol for MCP73833/4

### PR DESCRIPTION
**Pull request by cyber-murmel**
added symbol for MCP73833/4 Stand-Alone Linear Li-Ion / Li-Polymer Charge Management Controller

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
https://ww1.microchip.com/downloads/en/DeviceDoc/22005a.pdf
- [x] An example screenshot image is very helpful

- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.55x2.48mm.kicad_mod
  - ~A new fitting footprint must be submitted if the library does not yet contain one.~
- [x] ~If there are matching footprint PRs, provide link(s) as appropriate~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] ~Give a reason behind any intentional library convention rule violation.~

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cyber-murmel , thanks for contributing,

A few comments I have during my review:

MCP73833:
- [ ] Name of the symbol should be `MCP73833-xxxMF`
- [ ] Description should ends with package name, please add `, DFN-10` at the end
- [ ] Pin name position offset should be 20mil
- [ ] The footprint is not correct, EP size is wrong. If the right footprint do not exist, you should create and submit it
- [ ] Footprint filter should be `DFN*1EP*3x3mm*P0.5mm*`
- [ ] Pin 6 and 8 should be Passive to avoid ERC errors

MCP73834:
- [ ] Name of the symbol should be `MCP73834-xxxMF`
- [ ] Description should ends with package name, please add `, DFN-10` at the end

Cheers,
Joel

**Comment by cyber-murmel** [comment]
FP PR: https://github.com/KiCad/kicad-footprints/pull/1573

**Comment by myfreescalewebpage** [comment]
@cyber-murmel the old MCP73833 and MCP73834 have not been removed in the contribution, please look at the diff at https://github.com/KiCad/kicad-symbols/pull/1632/files.
Also, I still not agree with the EP size, should be 1.65x2.39mm.
Finally, no footprint size in footprint filter.
Joel

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this PR is abandoned.

**Comment by 0xdec** [comment]
@myfreescalewebpage tried to fix this in #2384

**Comment by myfreescalewebpage** [comment]
@0xdec thanks!

**Pull request closed without merging**
