### PR TITLE
Rename SOIJ-8 footprint to SOIC-8W

### PR DESCRIPTION
**Pull request by Icenowy**
As SOIJ-8 is a name of the wide version of SOIC-8 only used by
Microchip, the footprint name is suggested to be changed to SOIC-8W.

Change the footprint reference in the symbol library to use the new
SOIC-8W name.

Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

---

This PR depends on the footprint PR https://github.com/KiCad/kicad-footprints/pull/1446 , as the corresponding symbol change.

### CODE REVIEW

**Comment by evanshultz** [comment]
I checked and this looks good to me too. Ready to merge when the footprint is merged.

**Comment by myfreescalewebpage** [comment]
Footprint has been Abandoned

**Comment by evanshultz** [comment]
@Icenowy 
After https://github.com/KiCad/kicad-symbols/pull/1651 was merged, this PR tried to change the -xxSS suffix Microchip ATtiny13 symbols. According to http://ww1.microchip.com/downloads/en/DeviceDoc/doc2535.pdf, those should be a 3.9x4.9mm SOIC8 so we're good. But the -xxS parts need this change. Can you please edit them?

@fauxpark 
I'd really appreciate getting your confirmation on this if you don't mind. TIA if you have a chance to take a look.

**Comment by Icenowy** [comment]
@evanshultz Changed. Symbols in `obsolete/` are not changed yet.

**Comment by evanshultz** [comment]
@Icenowy 
Great! Thank you! This looks good now. Would you mind correcting the affected symbols in `obsolete/`?

**Comment by fauxpark** [comment]
@evanshultz LGTM

**Comment by evanshultz** [comment]
Thank you, @Icenowy !

Good thought! While I do see a few descriptions with a trailing `W`, most don't. And KLC doesn't require much for descriptions. So, especially for a fix, I'll just merge it like this.
image

**Comment by fauxpark** [comment]
I meant the symbols with `SOIJ` in the description: https://github.com/KiCad/kicad-symbols/blob/master/MCU_Microchip_ATtiny.dcm#L52

**Comment by evanshultz** [comment]
Thanks @fauxpark ! I submitted https://github.com/KiCad/kicad-symbols/pull/3098 to address this.

**Pull request merged**
