### PR TITLE
Add HMC7992.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://www.analog.com/media/en/technical-documentation/data-sheets/HMC7992.pdf

image

footprint pr: https://github.com/KiCad/kicad-footprints/pull/1444

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A comment I have during my review:

- [ ] Footprint filter will be `LFCSP*1EP*3x3mm*P0.5mm*`

Else no comment, looks good ! Just need to wait this modification and the integration of the footprint.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@matthuszagh ar you still alive on this subject ? Footprint has been merged, only a single comment to fix on this symbol to merge it. Thanks for the update

**Comment by matthuszagh** [comment]
I've made the change. Thanks for the reminder.

**Comment by myfreescalewebpage** [comment]
Thanks, merging!

**Pull request merged**
