### PR TITLE
Dmg9926 udm

### PR DESCRIPTION
**Pull request by Electro707**
Adding the DMG9926UDM common-drain n-channel MOSFET.
Screenshot of the symbol in KiCad:
image
Screenshot of the pins table:
image
Link to the part's datasheet:
[https://www.diodes.com/assets/Datasheets/ds31770.pdf](https://www.diodes.com/assets/Datasheets/ds31770.pdf)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
   - A new fitting footprint must be submitted if the library does not yet contain one.
- [] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@Electro707 thanks for this symbol,

The design is not consistent with the other dual mosfet we have in the library. I think it will be better with something looking like IRFI4019H.

Will do full review after.

Joel

**Comment by Electro707** [comment]
@myfreescalewebpage My reasoning behind the filled background box is to distinguish a dual mosfet in one package versus 2 individual mosfets connected together (at least on the schematic side). But if it's more conventional not to have such an outline, I could remove it.

**Comment by myfreescalewebpage** [comment]
Yes please, for library consistency

**Comment by cp-aquila** [comment]
IMHO it would be best to copy `IRFI4019H` and change it. So that the two symbols can be exchanged against each other without rearranging the schematic.
The description should also mention `Dual Half Bridge` instead of just `Dual` so its obvious that the individual FETs are connected.

**Comment by Electro707** [comment]
@cp-aquila My symbol was originally based on that I think. The reason I changed the symbol is due to this part having 2 pins for both mosfet drains. So unless there is a way to stack up pins, I think the 2 pins should be separate.
I changed the description to `Dual Half Bridge`.
For reference, this is what the footprint current looks like after my last commit:
image

**Comment by cp-aquila** [comment]
You can and should stack the pins. See https://kicad-pcb.org/libraries/klc/S4.3/

**Comment by Electro707** [comment]
Screenshot of part after modification to make one of the drain pins invisible and stack it with the other drain pin. 
image

**Comment by myfreescalewebpage** [comment]
Hello @Electro707 and thanks @cp-aquila for the first steps of the review.

Last comment:

- [ ] Footprint filter should be `SOT?23*`

Joel

**Comment by Electro707** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
