### PR TITLE
Texas Instruments BQ2407x

### PR DESCRIPTION
**Pull request by jeanthom**
Hello,

Here's a symbol for Texas Instrument's BQ24072 and BQ24073 battery charger ICs.

bq24072

[Datasheet](http://www.ti.com/lit/ds/symlink/bq24072.pdf)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jeanthom , thanks for contributing,

A few comments I have during my review:

- [ ] According to packaging information, the device should be named BQ24072RGT and BQ24073RGT to not get troubles if the manufacturer add packages options in the future
- [ ] Footprint should be VQFN, not QFN, probably something like `VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm` is great, it does not exist, you should propose it in the footprint repo
- [ ] Footprint filter have no leading star
- [ ] Pins length should be 100mil only (symbol < 100pins)
- [ ] BAT pins should be stacked
- [ ] PGOOD and CHG pin can be on the top of the symbol, on the right is good
- [ ] BAT, ILIM, ISET, TMR and TS should be Passive to avoid ERC errors
- [ ] You are currently violating S3.1 that can be easily corrected by centering the symbol

Cheers,
Joel

**Comment by jeanthom** [comment]
I updated the symbol, to address most of your comments:

bq24072rqt

I don't think I will be able to properly center my component as its center is not on a 100mil grid.

Regarding BAT pin stacking, I read on KiCad's website that you can't do pin stacking with pin types other that Power input/Power output/Output. The battery pin is both a power input and output (this chip charges the battery, but also draws current from the battery). Should I keep the two BAT pins separate ?

**Comment by myfreescalewebpage** [comment]
Rules for pin stacking are at http://kicad-pcb.org/libraries/klc/S4.3/ and do not specify that only Power pins are concerned. However, there is a special attention to Power pins due to ERC checks to not get errors.

Exemple of similar device with correct pin stacking: LTC4156.

Joel

**Comment by jeanthom** [comment]
Thank's for the explanation. I set the BAT pins to Passive and stacked them up:
capture du 2019-02-16 08-27-45

**Comment by myfreescalewebpage** [comment]
Hi @jeanthom thanks for the fixes.

Several point not addresses yet. Additionally:
- [ ] I do not agree with the footprint, the expected one do not exist, you should submit it (using the scripting method for this one)
- [ ] The footprint filter should not contains the number of pins, and no "-". It will be `* VQFN*1EP*3x3mm*P0.5mm*` for this part.

Cheers,
Joel

**Comment by jeanthom** [comment]
Hi,

I fixed the footprint filter, but I don't understand why [VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm](https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm_ThermalVias.kicad_mod) is not the right footprint. It seems to fit perfectly the datasheet's drawings:

capture du 2019-02-17 21-40-32

**Comment by myfreescalewebpage** [comment]
@jeanthom the EP size is not the same. 1.6mm <> 1.68mm, even if it is a small difference, a new footpritn should be created.

**Comment by jeanthom** [comment]
Damn... Thanks for your perceptiveness, I will submit a footprint ASAP

**Comment by myfreescalewebpage** [comment]
@jeanthom any news here about the footprint ? If you have created a footprint pull request, can you give the link here ? Thanks, Joel

**Comment by myfreescalewebpage** [comment]
@jeanthom ping :)

**Comment by evanshultz** [comment]
Should IN be on top and PGOOD and CHG not? My understanding of KLC (http://kicad-pcb.org/libraries/klc/) is that power pins are on top so perhaps the request above was asking to put the open drain pins at the top of a side, and not the top of the symbol?

**Comment by myfreescalewebpage** [comment]
@evanshultz my request was to get open drain type on the right side yes, usually they are at the bottom of the right side in the library.

**Comment by jeanthom** [comment]
Hi! Sorry for the delay, I was busy for the last couple of weeks.

I haven't got time yet to create the footprint nor rework the symbol, I hope to get both done by the end of April.

**Comment by myfreescalewebpage** [comment]
No worries @jeanthom your pull request remains open, take your time to do it :) Thanks for your message!

**Comment by myfreescalewebpage** [comment]
Footprint has been proposed by another contributor: https://github.com/KiCad/kicad-footprints/pull/1605
Just need to update the footprint here.
Joel

**Comment by jeanthom** [comment]
Thanks for the information, I think I did the needed changes to use this footprint. Let's hope that the CI goes right :)

**Comment by myfreescalewebpage** [comment]
Thanks, looks great ! Just notice one of my previous comment is not correctly written:

- [ ] PGOOD and CHG pin CAN'T be on the top of the symbol, on the right is good

Can you fix it please ?
Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@jeanthom any news here ? Please also solve the branch conflict to continue.

**Comment by myfreescalewebpage** [comment]
@jeanthom ping !

**Comment by myfreescalewebpage** [comment]
No news of the original author, indicate the PR is abandoned.

**Comment by RICCIARDI-Adrien** [comment]
Hi,
This pull request adds BQ24072 and BQ24073, but they are now in library (see commit cb3140442e93dedfe2a06d7bcdad34567eef8453). This pull request may be closed.

**Pull request closed without merging**
