### PR TITLE
Added display NHD-C0220BiZ

### PR DESCRIPTION
**Pull request by aracosta1**
This is a 20x2 display from newhavendisplay.
Datasheet available at: http://www.newhavendisplay.com/specs/NHD-C0220BiZ-FSW-FBW-3V3M.pdf

I will create a separate pull request for the footprint

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1406

**Comment by myfreescalewebpage** [comment]
@aracosta1 I have not performed a full review, but I see on the screenshot that the silkscreen is not correct. When the device is soldered, the silkscreen should remain totally visible, so for this part it should follow all the corners and screw holes to achieve this.

**Comment by myfreescalewebpage** [comment]
Hi @aracosta1 , thanks for contributing,

A few comments I have during my review:

- [ ] Pin VOUT is Power Output and is better on the top of the symbol.
- [ ] RST is active low and should be renamed `~RST`
- [ ] In my opinion, RST is better below SDA/SCL.
- [ ] The size of the symbol can be reduce a little bit, I would like to propose the following design:

capture

Cheers,
Joel

**Comment by aracosta1** [comment]
Hi @myfreescalewebpage 

>    Pin VOUT is Power Output and is better on the top of the symbol.
This pin is should be tied to VDD or VSS with a capacitor, so it's not a real power output. This is why I put it on a side. Since it's normally tied to VSS maybe it's better on bottom and change the type to Passive.

>    The size of the symbol can be reduce a little bit, I would like to propose the following design:
I'll rearrange the way you propose, in fact it's visually better.

**Comment by myfreescalewebpage** [comment]
@aracosta1 not bad regarding to VOUT pin, Passive is great too for this symbol to avoid ERC errors in every configuration.

Ok for the design modification, I wil lreview with pleasure !

Cheers,
Joel

**Comment by aracosta1** [comment]
@myfreescalewebpage I implemented the changes, should be correct now.

**Comment by myfreescalewebpage** [comment]
Hello @aracosta1 you have moved VOUT to the bottom, I do not agree with this. A side is okay for this pin but bottom is reserved for negative power pins in the KLC.
Pins A and K can be moved 100mil to the top to get a symmetrical device regarding to pins C1+ and C1-.
Ok for footprint and footprint filter.
Joel

**Comment by aracosta1** [comment]
Hello @myfreescalewebpage I probably misnderstood your reply about VOUT tied to VSS, now its back on the left.
> Hello @aracosta1 you have moved VOUT to the bottom, I do not agree with this. A side is okay for this pin but bottom is reserved for negative power pins in the KLC.

> 
> Edit: please do not force push, this break the commit history and made the review harder to do for us. Just push to your branch to get the PR updated.

Sorry for the forced push, I messed up something in my branch and thougth it was not passed upstream.

**Comment by myfreescalewebpage** [comment]
Thanks for the fix.
Symbol ok according to me, waiting for the footprint before merging this.
Joel

**Comment by aracosta1** [comment]
Footprint has been submitted as PR [1406](
https://github.com/KiCad/kicad-footprints/pull/1406) and waiting for approval.

**Comment by myfreescalewebpage** [comment]
Yes.

**Comment by myfreescalewebpage** [comment]
@aracosta1 why closing this ? We can just keep it open until you or somebody else want to continue working on this device.

**Comment by aracosta1** [comment]
I closed it because it was created from the master branch of my repository and when I tried to open a new pull request for another symbol I found it was not possible. So I closed it to move the symbol in a branch and reopen it. If it’s a problem for you I’ll keep it open this way.

**Comment by poeschlr** [comment]
It is not a problem. (We generally just sometimes wonder why pull requests are closed.) Just link to this pull request once you open the new one.

**Pull request closed without merging**
