### PR TITLE
Add W9812G6KH SDRAM

### PR DESCRIPTION
**Pull request by joshtyler**
Add W9812G6KH SDRAM
[Datasheet](https://www.winbond.com/resource-files/da00-w9812g6khc1.pdf)
Pinout is p.4 of datasheet, table showing variants is p.3

The symbol is based off IS42S16400J-xC which is pin compatible, only changes are naming to some pins (GND->VSS, GNDQ->VSSQ, BAx->BSx), and properties such as value and datasheet.

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @joshtyler , thanks for contributing,

A few comments I have during my review:

- [ ] It seems the pinout and package is the same for all the symbol, in this case you can make only one and then create aliases for all the others
- [ ] Pin length should be 100mil
- [ ] You should stack VSSQ pins
- [ ] You should stack VSS pins
- [ ] Footprint filter should be `TSOP?II*22.2x10.16mm*P0.8mm*`
- [ ] The pin style of CLK should be Line (we do not use clock style in the official lib)

Cheers,
Joel

**Comment by joshtyler** [comment]
Thanks for the review @myfreescalewebpage.

Regarding pin length and stacking of pins, I left the pin length at 200mils, and didn't stack pins to allow easy migration between this part and IS42S16400J-xC (which already exists in the library and is pin compatible).

Is it better to make these changes, or keep the ability to swap between the two parts?

**Comment by myfreescalewebpage** [comment]
No it's better to make the changes to go in the direction where the symbol are conformed to the KLC.
If you want to update also the old symbols, this is always welcomed too :)
Joel

**Comment by joshtyler** [comment]
Sorry for the delay, I've now made the requested changes. 

I also stacked the power pins, because KLC S4.3 says they must be stacked unless the datasheet states one decoupling capacitor per pin (which it doesn't).

Stacking the pins left whitespace at the top and bottom, so I've reformatted the shape slightly.
image

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
