### PR TITLE
Add MCP2221A USB to I2C bridge components

### PR DESCRIPTION
**Pull request by andrewteasdale**
Added the Microchip MCP2221A USB to I2C/UART bridge chip in all 4 footprint varieties [DIP, QFN, SOIC, TSSOP]. The identical [but lower speed] Microchip MCP2221 is considered a mature product and is not recommended for new designs, and has therefore not been included in this pull request.

 - Product datasheet http://ww1.microchip.com/downloads/en/DeviceDoc/20005565B.pdf
 - Image of DIP/SOIC/TSSOP variants:
image
 - Image of DIP/SOIC/TSSOP variants:
image
 - Datasheet pin definitions:
image
Please advise if there are any improvements or changes to be made. Thanks!

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @andrewteasdale , thanks for contributing,

A few comments I have during my review:

MCP2221Ax-I-ML
- [ ] Name of the device should be "MCP2221AxML"

MCP2221Ax-I-P
- [ ] Name of the device should be "MCP2221AxP"

MCP2221Ax-I-SL
- [ ] Name of the device should be "MCP2221AxSL"

MCP2221Ax-I-ML
- [ ] Name of the device should be "MCP2221AxST"

Else no comment to do on the symbols.

Cheers,
Joel

**Comment by andrewteasdale** [comment]
Good spot Joel, I've amended accordingly. Thanks for reviewing.

**Comment by myfreescalewebpage** [comment]
Thanks for the quick change, merging now :)

**Comment by myfreescalewebpage** [comment]
@jamesrlucas why did you referenced this PR ?

**Comment by jamesrlucas** [comment]
I'm trying to work out what i've done - It wasn't intentional.

**Comment by myfreescalewebpage** [comment]
ok

**Comment by chschlue** [comment]
@jamesrlucas From the outside, it looks like you didn't do anything but pull the commit merging this PR into master into your own kicad-symbols fork.
But I have never seen Github add references because of that before. We'd be flooded if this was the case every time somebody updates his fork.

**Pull request merged**
