### PR TITLE
Add Panasonic AQ-H series solid state relays, DIP & SMD + zero cross & random

### PR DESCRIPTION
**Pull request by yankee14**
Add Panasonic's AQ-H series, triac-based, solid state relays. They come in DIP and SMD packages, as well as zero cross and random phase variants. Assorted current handling capabilities range from 300mA to 1.2A.

`kicad-symbols` PR: https://github.com/KiCad/kicad-symbols/pull/2602
`kicad-footprints` PR: https://github.com/KiCad/kicad-footprints/pull/2212
`kicad-footprint-generator` PR: https://github.com/pointhi/kicad-footprint-generator/pull/527

Datasheet: https://b2b-api.panasonic.eu/file_stream/pids/fileversion/2787

**I need advice on:**
1. How to create 7-pin footprints for these. I know that footprints these days are preferred to be scripted if possible, and I think I need help with that.
2. Please help me double check whether pins 5 and 6 are/should be common, and whether the triac drawing inside the symbol needs to be modified slightly. I am new to SSR's so I am still learning how they are setup.

Example zero cross SSR AQHx213y:
AQH0213

Example random phase SSR AQHx223y:
AQH0223

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cp-aquila** [comment]
There is a footprint that seems to match: `DIP-8-N7_W7.62mm`

**Comment by cp-aquila** [comment]
For the SO footprint, this is most likely the documentation you are looking for: 
grafik

Found here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO

I am not sure about the naming, is it `SO`, `SSO`,  or something else.
There is a footprint in the library that seems close to what you are looking for `SSO-8_6.7x9.8mm_P2.54mm_Clearance8mm`

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 , thanks for contributing,

A few comments I have during my review:

For all devices:
- [ ] Descriptions should ends with the package name, for example: `Zero Cross Opto-Triac, Vdrm 600V, Ift 10mA, IT 300mA, DIP-8`
- [ ] Footprint field should be completed
- [ ] I don't understand why pin 5 and 6 are stacked
- [ ] Pin 7 should be added, NC, Invisible, on the border outline of the symbol

Will do a new complete review when this will be fixed.

Cheers,
Joel

**Comment by yankee14** [comment]
@myfreescalewebpage and @cp-aquila thank you for the review,

Taking one thing at a time:
> Descriptions should ends with the package name, for example: Zero Cross Opto-Triac, Vdrm 600V, Ift 10mA, IT 300mA, DIP-8

Should it be DIP-8/SOIC-8 or DIP-7/SOIC-7? Just want to be sure. I will go ahead and change things as you've requested.

**Comment by yankee14** [comment]
>  I don't understand why pin 5 and 6 are stacked

As I said in my OP, I wasn't sure if they should be.

**Comment by myfreescalewebpage** [comment]
Just realized the package has no pin 7 !! I'm sorry, packages in the description should be DIP-7 and SOIC-7, and the pin 7 should not be added to the symbol. Can you revert this ?

AQH0223A has not the package in the description.

The symbol is very nice with pin 5 and 6 not stacked :)

Footprint filter to be completed (`DIP*W7.62mm*` and for SMD version you should submit the package I think)

**Comment by yankee14** [comment]
@myfreescalewebpage That's okay, I will fix these things tomorrow! Thanks for your help.

**Comment by yankee14** [comment]
Going to work on the footprint now. I will try to generate it by @cp-aquila's advice.

**Comment by yankee14** [comment]
For reference, here are the symbol screenshots now:

AQH0213
AQH0213A

**Comment by myfreescalewebpage** [comment]
Thanks, just need the missing footprint now.

**Comment by myfreescalewebpage** [comment]
2 comments I have forgotten:
- [ ] For "SSO-8-N7_6.4x9.78mm_P2.54mm" package, the footprint filter should be `SSO*N7*6.4x9.78mm*P2.54mm*`
- [ ] For "DIP-8-N7_W7.62mm" package the footprint filter should be `DIP*N7*W7.62mm*`

**Comment by yankee14** [comment]
@myfreescalewebpage thanks, I will fix it now! Please keep in mind that they may tell me to remove N7 from the footprint SSO-8 name. It may not even be appropriate to call it SSO yet. I am waiting for reviews on https://github.com/pointhi/kicad-footprint-generator/pull/527 and https://github.com/KiCad/kicad-footprints/pull/2212.

**Comment by myfreescalewebpage** [comment]
Sure, we will see what the footprint experts tell, I'm not the best at this job.
Else no more comment, just need to wait the footprint now.

**Comment by yankee14** [comment]
Awesome, thank you!

**Comment by yankee14** [comment]
I always get the footprint filter wrong, so let me know what it should be :)

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@yankee14 

AQH0223A:
- [ ] Fp to be fixed

AQH0213A and AQH0223A:
- [ ] Fp filter should be `SSO*6.4x9.78mm*P2.54mm*`

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, great job. Merging

**Comment by yankee14** [comment]
Thanks everyone. Catch ya'll over on gitlab.

**Pull request merged**
