### PR TITLE
Add PCA9548 I2C multiplexer

### PR DESCRIPTION
**Pull request by chemicstry**
Add PCA9548A I2C multiplexer

Datasheet: http://www.ti.com/lit/ds/symlink/pca9548a.pdf

Contains 4 footprint versions:
- PCA9548ADB - SSOP-24 - in library
- PCA9548ADW - SOIC-24 - in library
- PCA9548APW - TSSOP-24 - in library
- PCA9548ARGE - Texas RGE0024C (Package_DFN_QFN:Texas_RGE0024C_EP2.1x2.1mm)
  - https://github.com/KiCad/kicad-footprints/pull/1395

image

### CODE REVIEW

**Comment by chemicstry** [comment]
I'm not sure how to fix the pin offset CI error, can't seem to find such option in library editor

**Comment by DanSGiesbrecht** [comment]
Hi @chemicstry 
I'll have a look at this later today. To change pin offset CI error:
`Edit Symbol Properties` > `Pin Name Position Offset = 20`
gear
window

**Comment by chemicstry** [comment]
Thanks. Fixed.

Suggestion: make 20mils a default pin name spacing value in symbol editor.

**Comment by chemicstry** [comment]
Thanks for the review. Updated what you requested.

All these requested changes would also apply to the already existing part PCA9544A (4 channel) that I based my symbol on. Should I fix that one too or should it be a different PR?

**Comment by DanSGiesbrecht** [comment]
Thanks for the quick fixes. I don't have time to check it yet.

Up to you! Either works for me.

**Comment by DanSGiesbrecht** [comment]
Thanks for making those changes! I'll keep an eye out for the FP getting merged. Otherwise, this is good to go. :heavy_check_mark:

**Comment by HubertD** [comment]
Sorry @DanSGiesbrecht, @chemicstry, I just stumbled upon this PR.

I2C has a feature called "clock stretching" where the I2C slave can hold the clock line low to slow down the data rate or until it is able to answer a request.
Not all devices use this feature (and if they clearly don't, "input" is okay), but generally, I2C SCL and SDA pins should be "open collector" or "bidirectional" in my opinion.

Doing a "grep SCL *" in the current library shows all kinds of pin types for SCL pins, though.

**Comment by chemicstry** [comment]
Sorry for the late reply. The PCA9548A datasheet has no information about clock stretching, but there is a block diagram that implies SCL is input only.

image

So this device either does not do clock stretching or this diagram hides that functionality. I could change the symbols as requested. However, one of the footprints is stuck over [here](https://github.com/pointhi/kicad-footprint-generator/pull/290) preventing this symbol to be merged.

**Comment by evanshultz** [comment]
This was discussed before. SCL pins are inputs. SDA is bidirectional. This makes the ERC tool most valuable.

I'll have a look at the footprint now.

**Comment by evanshultz** [comment]
1. SC* and SD* pins are bidirectional. I think the screenshot Dan shows above is just one possible application. Sorry, but please change those pins back to Bidirectional type.
1. The package type (last part of the description) for this new symbol should be `VQFN-24`.
1. What is the difference between the TCA and PCA versions? http://www.ti.com/product/PCA9548A have a note "TCA9548A  - The device has the SAME FUNCTIONALITY and PINOUT as the compared device but is NOT an exact equivalent.   This P2P device has a wider voltage range (down to 1.65V) and performance enhancements (Reset and Power-On Reset)" which tells me they can be ALIASes and not unique symbols.

**Comment by chemicstry** [comment]
My bad, I missed that the TCA9548A already exists in the library. There is also PCA9544A and TCA9544A duplicates. I could fix them in this PR too (and their SCL/SDA pin types). But should I use the larger PCA9544A symbol style (spaces between output groups), or the compact TCA9548A?

**Comment by evanshultz** [comment]
*9548 can be an ALIAS of the existing *9548 where the packages match. For new packages, keep the same symbol design. Let's limit this PR to just adding PCA9548 to keep things more clean. I'd be happy if you want to figure out other corrections and submit them in a separate PR, though. Thanks!

**Comment by myfreescalewebpage** [comment]
Close/open to restart all testing on this PR.

**Comment by myfreescalewebpage** [comment]
@DanSGiesbrecht footprint has been merged for this PR.

**Comment by evanshultz** [comment]
@chemicstry 
I haven't seen Dan often in a while and I provided comments above. If you can address the outstanding items I noted above I'll review again and hopefully this is ready for merge.

**Comment by chemicstry** [comment]
Sorry, this one got lost in my todo list. I will try to fix this asap.

**Comment by chemicstry** [comment]
It should hopefully be OK now. I did everything from scratch, reusing existing symbols:
* Changed footprint for the existing `TCA9548AMRGER` to the new RGE0024C (previous QFN-24 had wrong thermal pad size)
  * Used it as an alias for `PCA9548ARGER`
* Created `PCA9548APWR` alias based on `TCA9548APWR`
* Created new symbol `PCA9548ADBR` (SSOP-24) based on `TCA9548APWR` (TSSOP-24) - same pinout
* Created new symbol `PCA9548ADWR` (SOIC-24) based on `TCA9548APWR` (TSSOP-24) - same pinout

**Comment by evanshultz** [comment]
Thanks!
1. Remove the trailing `R` from the symbol names. Not sure what this is but it's something non-functional like showing the parts are packaged in a reel.
1. Change pin name offset to 20mil (do for the TCA symbols too, please).

Just to note, the more compact style was used for all the new symbols. This is nice for interchangeability. Thank you.

Out of curiosity, do you know the difference between the `ARGE` and `AMRGE` suffixes for TCA9548?

**Comment by chemicstry** [comment]
Fixed as requested.

Regarding the `AMRGE` suffix, I have no idea. Part with this suffix appears only on some Chinese website. Maybe a typo?

**Comment by evanshultz** [comment]
Thanks!

For item 1, I only meant that for these new symbols. If the `R` disappears from symbols people are using now, their schematics will break. I tried to clearly note that item 2 applies to the TCA symbols as well, but I should have been more verbose for item 1. Sorry. Could you please re-add the `R` for the TCA symbols?

About `AMRGE`: Not a big deal. Just curious. The datasheet clearly shows it's a recent change and something worthy of having a new MPN:
image

**Comment by evanshultz** [comment]
Looks good. Thank you!

**Pull request merged**
