### PR TITLE
Adding MX25R3235F (except 12-WLCSP and USON-8 packages)

### PR DESCRIPTION
**Pull request by ki5libs**
Adding MX25R3235F (except 12-WLCSP package)
[Datasheet](http://www.macronix.com/Lists/Datasheet/Attachments/7534/MX25R3235F,%20Wide%20Range,%2032Mb,%20v1.6.pdf)
Screenshot of symbol with OPTION2: RESET
mx25r3235f_reset
Screenshot of symbol with OPTION2: HOLD
mx25r3235f_hold

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks for this contribution. The symbols for this kind of devices should now be atomic, not generic, meaning you should have a symbol for each package version, with correct footprint associated. Please proceed before we can start the review of this.
Joel

**Comment by ki5libs** [comment]
@myfreescalewebpage 

I've reworked symbols with these recommendations. I've found that corresponding USON-8 footprint missing in footprint library (WLCSP too) so decided to remove USON-8 version from this commit. So it contain 6 atomic symbols now: 2 kinds of pin 7 implementation multiplied on 3 package types.

**Comment by myfreescalewebpage** [comment]
Thanks, making a full review from this point.

All symbols:
- [ ] Pins length should be 100mil (symbol < 100pins)
- [ ] Can you find a way to align VCC with GND ?

MX25R3235FM1xx0 and MX25R3235FM1xx1:
- [ ] Footprint should be `Package_SO:SOP-8_3.9x4.9mm_P1.27mm`
- [ ] Footprint filter should be `SOP*3.9x4.9mm*P1.27mm*`
- [ ] Package name in the description should be SO-8

MX25R3235FM2xx0 and MX25R3235FM2xx0:
- [ ] Footprint should be `Package_SO:SOP-8_5.28x5.23mm_P1.27mm`
- [ ] Footprint filter should be `SOP*5.28x5.23mm*P1.27mm*`
- [ ] Package name in the description should be SO-8

MX25R3235FZNxx0 and MX25R3235FZNxx1:
- [ ] Expose pad pin 9 should be added and stacked with GND
- [ ] Footprint filter should be `WSON*1EP*6x5mm*P1.27mm*`

Cheers,
Joel

**Comment by ki5libs** [comment]
@myfreescalewebpage 

thanks for your review. Example of fixed symbol:

MX25R3235FM1xx0

I couldn't find footprints proposed by you for MX25R3235FM1xx0 and MX25R3235FM1xx1 (`Package_SO:SOP-8_3.9x4.9mm_P1.27mm`) and MX25R3235FM2xx0 and MX25R3235FM2xx0 (`Package_SO:SOP-8_5.28x5.23mm_P1.27mm`) in the library. Do you think that footprints specified by me are not correct?

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks for the fixes.

Regarding to the footprint, no, I double checked, they simply not exist in the library at this moment and you should submit them. They must be scripted with https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO

PS : I just realized I made a mistake previously, the package in the description should be "SOP-8", previous checklist updated.

Joel

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

after some delay I've added correspond footprints ([PR](https://github.com/KiCad/kicad-footprints/pull/1599)) and fixed this one.

**Comment by myfreescalewebpage** [comment]
Thanks !!! Footprint filter are still not correct, they should not contain the number of pins. Else, seems very nice.
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprints now.
Joel

**Comment by myfreescalewebpage** [comment]
@ki5libs can you solve conflict here ? Then maybe ready to go on this PR !

**Comment by ki5libs** [comment]
@myfreescalewebpage sure, done

**Comment by myfreescalewebpage** [comment]
@ki5libs thanks, every thing is ok for me now, merging!

**Pull request merged**
