### PR TITLE
Add IS31FL3731

### PR DESCRIPTION
**Pull request by fauxpark**
Another I2C LED matrix driver. QFN-28/SSOP-28.

sym

Datasheet: http://www.issi.com/WW/pdf/31FL3731.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @fauxpark , thanks for contributing,

A single comment I have during my review:

IS31FL3731-QF:
- [ ] Footprint should be `Package_DFN_QFN:QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm`, it does not exist, you need to submit it.

Cheers,
Joel

**Comment by fauxpark** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1620

**Comment by myfreescalewebpage** [comment]
@fauxpark footprint has been merged, waiting for update of th symbol to merge it.
Thanks,
Joel

**Comment by fauxpark** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
