### PR TITLE
Add LT1962 series of LDOs

### PR DESCRIPTION
**Pull request by byronhopps**
Add two symbols, one for the adjustable output version of the LDO and one for the fixed output version (with aliases for each output voltage).

http://cds.linear.com/docs/en/datasheet/1962fb.pdf

Screenshot of the adjustable version:
screen shot 2018-02-03 at 5 42 39 am

Screenshot of the fixed version:
screen shot 2018-02-03 at 5 43 29 am

Both parts use the MSOP-8 footprint from the Housings_SSOP library, which is compatible with the recommended footprint shown in the part datasheet.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for contributing!
1. Set pin text offset to 20mil.
1. Add the package name (`MSOP-8`) to the end of the description
1. Because all pins are shown, do not put the pin count in the FPfilter
1. Place the NC pins within the part body to avoid them getting accidentally connected.
1. Libraries names just changed. The footprint library is now called `Package_SO`.

**Comment by byronhopps** [comment]
Hello!

I've corrected the issues that you mentioned; please let me know if any further changes will be necessary

**Comment by byronhopps** [comment]
My apologies, I clicked the wrong button by accident!

**Comment by evanshultz** [comment]
Accidental clicks happen. Thanks for the contribution!

**Pull request merged**
