### PR TITLE
Added symbol for Analog Devices ADG715 octal SPST switch

### PR DESCRIPTION
**Pull request by andrasfuchs**
Added Analog Devices ADG715 (I2C switch array) to the library

image

Datasheet: http://www.analog.com/media/en/technical-documentation/data-sheets/ADG714_715.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
I see this is your first contribution to the KiCad libraries. Thanks for adding new symbols!

- Always include a datasheet link when contributing a symbol. This one is at http://www.analog.com/media/en/technical-documentation/data-sheets/ADG714_715.pdf.
- The keywords should not be a duplicate of the description
- The footprint filter should not contain the pin count but should have the body size and pin pitch; use `TSSOP*4.4x7.8mm*P0.65mm*`
- We have nice symbols for this type of part in the `Analog_Switch` library. Please base this symbol off one of those; see https://github.com/KiCad/kicad-symbols/pull/476 for a similar PR.
- The pins on the end of the switch should be Passive type.
- Would you be willing to contribute ADG714? This is not required.

**Comment by jkriege2** [comment]
Also: We usually have positive power-pins at the top edge and negative power-pins at the bottom edge. All other pins should be on the left/right edge!

**Comment by jkriege2** [comment]
comparably complex analog switch symbols in our lib are (just as a template for your symbol):
2018-05-01 07_48_27-symbol library editor - analog_switch d__kicad_kicad-symbols_analog_switch lib
2018-05-01 07_49_15-symbol library editor - analog_switch d__kicad_kicad-symbols_analog_switch lib

**Comment by andrasfuchs** [comment]
Thank you @evanshultz and @jkriege2 for the feedback!

* What do you guys think, should this component moved to the `analog_switch.lib` from the current `analog.lib`?
* I've added the switching components to the drawing similarly to the one in its datasheet. Is it ok this way?

image

**Comment by evanshultz** [comment]
Looking much nicer now.
- Please cut back the lines or enlarge the symbol so lines don't run over text.
- Yes, it should be in analog_switch.lib.

**Comment by andrasfuchs** [comment]
I had to set the pin-label-offset to 0 in order to avoid the VDD's intersection with the upper horizontal line. Is it still acceptable this way or should I make the whole drawing bigger?

image

**Comment by evanshultz** [comment]
- Pin name offset to 20mil will match the rest of the library and avoid bogus errors with our check script. So please set it to 20mil and enlarge the symbol.
- You also have all pin lengths at 150mil; please set to them to 100mil.
- At that point, you may shift the border up 50mil since there's excess space at the bottom. (Symbol centering isn't a strong rule and it's fine if the symbol isn't centered when it looks best.)
- IMO, the dashed lines add a lot of lines to the symbol and I don't personally like the overlapping; for this symbol I'd be happy to simply remove them as the symbol's function is still obvious. @jkriege2?

**Comment by andrasfuchs** [comment]
image

**Comment by andrasfuchs** [comment]
@evanshultz Thank you for your review! Yes, actually I did update KiCad to the latest nightly release.

@jkriege2 Let me know what to do with the dashed lines. Thanks!

**Comment by andrasfuchs** [comment]
I managed to somehow mass this pull request up, so let me close this, and resubmit it with the changes relevant to ADG715 only.

**Pull request closed without merging**
