### PR TITLE
Atmel

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR replaces https://github.com/KiCad/kicad-symbols/pull/95

The SAM micros are not transferred

### CODE REVIEW

**Comment by poeschlr** [comment]
I will move the connectors from the atmel legacy lib into the connector_specialized lib later on. (as soon as my cleanup PR is merged.)

Could you run your footprint field fixup script over these symbols? (Housing->Package, Pitch->P, ...)

**Comment by jkriege2** [comment]
Hi!

https://github.com/KiCad/kicad-symbols/pull/100 has been merged ... could you also fix the merge conflicts, so we can proceed with this?

JAN

**Comment by SchrodingersGat** [comment]
Conflicts fixed

**Comment by jkriege2** [comment]
Hi!

some symbols are in the wrong libs:
- All AT89* should go to MCU_Atmel_8051
- All AT90* should go to MCU_Atmel_AVRClassic

Could you move them before I merge?

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
These have now been fixed. Ok to merge?

**Pull request merged**
