### PR TITLE
new ldo regulator XC6210B332MR

### PR DESCRIPTION
**Pull request by TheSillyMouse**
New LDO regulator

Manufacturer: TOREX
Part Number: XC6210B332MR

Datasheet:
https://www.torexsemi.com/file/xc6210/XC6210.pdf

Screenshot:
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @TheSillyMouse , you should move not connected pin inside symbol's body, and also move part name and reference on top, outside of body.

**Comment by TheSillyMouse** [comment]
> Hi @TheSillyMouse , you should move not connected pin inside symbol's body, and also move part name and reference on top, outside of body.

Hi @aris-kimi the symbol is exactly the same as the existing one "XC6220B331MR". Which is already in the list.
I'll fix the reference and part name.
Thanks!

**Comment by aris-kimi** [comment]
You have moved part name and footprint value, you have left reference inside the body.

**Comment by diegoherranz** [comment]
If I'm not mistaken, this could be an alias of XC6220B331MR not to have another symbol. Could you turn it into an alias instead?

The NC placement is wrong on XC6220B331MR as mentioned above. That should be fixed, but it can go on a separate pull request (it's a bug). I'm happy to review that one too, ping me if it gets submitted.

Thanks!

**Comment by TheSillyMouse** [comment]
> If I'm not mistaken, this could be an alias of XC6220B331MR not to have another symbol. Could you turn it into an alias instead?
> 
> The NC placement is wrong on XC6220B331MR as mentioned above. That should be fixed, but it can go on a separate pull request (it's a bug). I'm happy to review that one too, ping me if it gets submitted.
> 
> Thanks!

Hi, @diegoherranz.
I turned it into an alias.

**Comment by diegoherranz** [comment]
Thanks for turning this into an alias. It makes it much easier to maintain the library if we reduce the number of symbols.

Just one comment. The datasheet URL points to the XC6220 instead of the XC6210.

Thanks!

**Comment by TheSillyMouse** [comment]
> Thanks for turning this into an alias. It makes it much easier to maintain the library if we reduce the number of symbols.
> 
> Just one comment. The datasheet URL points to the XC6220 instead of the XC6210.
> 
> Thanks!

Done.

**Comment by diegoherranz** [comment]
Thanks for the fix, it looks OK. Merging.

If you wanted to fix the XC6220B331MR on a separate PR, let me know and I would review it.

Thanks!

**Pull request merged**
