### PR TITLE
Added 2N7002K

### PR DESCRIPTION
**Pull request by 0xdec**
Added 2N7002K as an alias of BSS138
Datasheet: https://www.diodes.com/assets/Datasheets/ds30896.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@diegoherranz 
Are you going to take this? While `2N7002K` (and other parts not sole-sourced) has varying parameters depending on which datasheet you read, this is probably fine so this PR looks good to me.

**Comment by myfreescalewebpage** [comment]
I would just say it's better with no extra space before values and units. I would ask to remove the spaces before "A" and "V" in the description. @0xdec

**Comment by evanshultz** [comment]
No space is my preference too, but because of the inconsistency everywhere with descriptions that go back before I started helping out here, and no guidelines in KLC, I just merge if I have no other comments during a review. But that's me. Maybe I'm wrong?

**Comment by myfreescalewebpage** [comment]
I'm not against merging @evanshultz, I know this is something to review and fix in all lib.

**Comment by diegoherranz** [comment]
Yes, I was planning on taking this.

The main comment I wanted to make was that this device does include gate protection diodes.
When I worked on https://github.com/KiCad/kicad-symbols/pull/1237, I didn't include those with gate protection diodes since I thought that they would need a different symbol. Assuming that is the case, this would need a new symbol too. Although, obviously, it "works" with the symbol as is.

Any opinions on this?

Thanks!

**Comment by evanshultz** [comment]
IMO it's not worth it. This symbol still captures the device and the diodes don't add much. A note in the description wouldn't hurt, but I don't even think is necessary to merge.

Reviewing and polishing this library would be nice in the future, but I personally am in favor of merging as-is.

**Comment by 0xdec** [comment]
@myfreescalewebpage I also prefer no spaces in front of "A" and "V", but I just copied and modified the description from the existing 2N7002 devices. I'm happy to make any changes and rebase/force push if you think it's necessary.

**Comment by 0xdec** [comment]
@myfreescalewebpage fixed the extraneous spaces issue, and also went through and fixed them for every other component in Transistor_FET in #1619

**Comment by diegoherranz** [comment]
> IMO it's not worth it. This symbol still captures the device and the diodes don't add much. A note in the description wouldn't hurt, but I don't even think is necessary to merge.

OK. I'll merge.

Thanks, @0xdec, for your contribution.

**Pull request merged**
