### PR TITLE
PIC32MM0064GPL028-xML adding new part

### PR DESCRIPTION
**Pull request by TrashHammer**
Pic32mm addition to symbol library

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
http://ww1.microchip.com/downloads/en/DeviceDoc/60001324b.pdf
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible

image

- [ ] Ensure that the associated footprints match the [official footprint library]
- [ ] If there are matching footprint PRs, provide link(s) as appropriate(https://github.com/kicad/kicad-footprints)
Package_DFN_QFN:QFN-28-1EP_6x6mm_P0.65mm_EP4.25x4.25mm

- [ ] Check the output of the Travis automated check scripts - fix any errors as required
---
Pinout Image
Datasheet
image

Pin Table
image

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @TrashHammer , thanks for contributing,

A few comments I have during my review:

- [ ] Name should be "PIC32MM0064GPL028x-ML"
- [ ] VCAP should be power Output
- [ ] You can reduce the height of the symbol by 100mil

Please can you rebase so it will then be possible to merge, thanks

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@TrashHammer ping

**Comment by TrashHammer** [comment]
Got busy, I will do that within the hour.

**Comment by myfreescalewebpage** [comment]
Thanks a lot

**Comment by myfreescalewebpage** [comment]
Thanks. Last error to make travis happy: outline width should be 10mil

**Comment by TrashHammer** [comment]
I updated the PDF link and fixed outline error.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
