### PR TITLE
Add Onsemi MDBxxS, Bridge Rectifiers

### PR DESCRIPTION
**Pull request by yankee14**
Add Onsemi MDBxxS, Bridge Rectifiers in TSSOP-4 nonstandard package

Datasheet: https://www.onsemi.com/pub/Collateral/MDB8S-D.PDF

`kicad-symbols`: https://github.com/KiCad/kicad-symbols/pull/2802
`kicad-footprints`: https://github.com/KiCad/kicad-footprints/pull/2318
`kicad-footprint-generator`: https://github.com/pointhi/kicad-footprint-generator/pull/572

Screencaps:

MDB6S

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with complete package name: TSSOP-4 at the end
- [ ] Fp filter: `TSSOP*4.4x5mm*P4mm*`

Cheers,
Joel

**Comment by chschlue** [comment]
FP merged

**Comment by myfreescalewebpage** [comment]
Thanks.

@yankee14 last comment

- [ ] the package at the end of the description of the aliases should be "TSSOP-4", not just "TSSOP".

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
