### PR TITLE
Add generic symbol: LED_BARG

### PR DESCRIPTION
**Pull request by DanSGiesbrecht**
Added `LED_BARG` symbol to Device library. For use with this [Broadcom LED (warning, PDF download)](https://docs.broadcom.com/docs/AV02-0611EN). Also shown [here](https://www.digikey.ca/product-detail/en/HSMF-C113/516-2232-1-ND/2403198/?itemSeq=272568791) on Digikey.

symbol

This symbol matches other LED RGB symbols, and is throwing Travis warnings for off-center body and footprint filter issues. Advice on how to resolve is welcome.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Should you not name these to HSMF-C113 and HSMF-C115 ?
(there are many "led bargs" out there)
and be added to LED.lib 
(the foot print would be named Avago_HSMF-C113 and Avago_HSMF-C115



Add the data sheet link to the 
bild

**Comment by DanSGiesbrecht** [comment]
@Misca1234 thank you for looking into this.

My understanding is that all of the LEDs listed in the Device library are generic. What drives the decision to make this a generic symbol (as I have so far), versus making it an atomic symbol as you have suggested?

**Comment by DanSGiesbrecht** [comment]
Sorry the confusion! Yes, my intent is to make a generic symbol, and I will make a component-specific footprint soon.

**Comment by DanSGiesbrecht** [comment]
@Misca1234  just checking in - is there anything else that you would like changed?

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
