### PR TITLE
RF_Module: Added RF modules IQRF (DC)TR-52D(C)(T) and IQRF TR-72D(C)(T)

### PR DESCRIPTION
**Pull request by Roman3349**
Datasheet for the RF module IQRF (DC)TR-52D(C)(T): https://iqrf.org/weben/downloads.php?id=213
Datasheet for the RF module IQRF TR-72D(C)(T): https://iqrf.org/weben/downloads.php?id=337
Pull request for the footprint: https://github.com/KiCad/kicad-footprints/pull/733

Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Some screen shots would be nice, like this push
https://github.com/KiCad/kicad-symbols/pull/722


That is some nifty transceivers you found, they fit into a sim card reader

**Comment by Roman3349** [comment]
Hi @myfreescalewebpage,

RF module IQRF TR-x2D has to be inserted in SIM card holder. See 11th page of [datasheet](http://iqrf.org/weben/downloads.php?id=337). Unfortunately I forgot add holes `M1` and `M2` which can be used for mechanical fixation. Also I forgot add a pin `X5` for antenna connection on footprint for `IQRF TR-x2D` which hasn't got an antenna connector and PCB antenna.

But there are also RF modules (e.g. [IQRF TR-76D](http://iqrf.org/weben/downloads.php?id=441) or [IQRF TR-77D](http://iqrf.org/weben/downloads.php?id=536)) which can be inserted in SIM card holder (but you cannot use all pins) or SMT mounted.

I apologize for delay in this PR, so I'll try fix this PR ASAP.

Roman

**Comment by myfreescalewebpage** [comment]
No worries for the delay. If you add a pad for the antenna, so it didn't match anymore the SIM card holder... or I'm missing something...

**Comment by myfreescalewebpage** [comment]
No news from the original author, indicate this PR is abandoned.

**Pull request closed without merging**
