### PR TITLE
Add SE5004L.

### PR DESCRIPTION
**Pull request by matthuszagh**
Adding SE5004L
http://www.skyworksinc.com/uploads/documents/SE5004L_202393B.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] I would suggest to order GND pin from the left to the right pin 2 to pin 17, for consistency with the other devices in the libraries
- [ ] According to the datasheet, VREF is a Power Input, not an Input. It should also be moved to the top of the symbol. I would suggest to order the positive power inputs pin from the left to the right : VCC1/VCC2/VCC3/VREF. And also to center the entire group horizontally on the symbol.

Cheers,
Joel

**Comment by matthuszagh** [comment]
Thanks for the feedback Joel. Since VREF is optionally connected to SP1 and SP2 via a capacitor, think it makes sense to keep that on the top left? Everything else makes sense.

**Comment by matthuszagh** [comment]
I've updated the commit as well as a screenshot of the component. Let me know what you think.

**Comment by myfreescalewebpage** [comment]
Agreed, looks great. Can you also align horizontally reference and name fields ? Moreover, we usually put reference above.

@antoniovazquezblanco @DanSGiesbrecht The VREF pin on this symbol makes the KLC S4.4 error, do you know why ?

Joel

**Comment by matthuszagh** [comment]
Updated. I believe this is what you want for reference and name fields, but let me know if not.

**Comment by antoniovazquezblanco** [comment]
- VREF as far as I know is not a power input. It does not require a high power source to operate. It seems to be an input as only requires a reference voltage. If I am right, that pin should be of type Input.

- I would place VREF at the left (if it is not a power input). Just a mater of opinion I think.

- The symbol could use some pin stacking in the GND pins. Maybe VCC pins also (I don't know if the chip requires any decoupling capacitors or similar.)

**Comment by myfreescalewebpage** [comment]
@matthuszagh yes.

@antoniovazquezblanco VREF is to be discussed, I agree it does not require lots of power, but when submitting micro-controller, we put VDDA / VSSA on top and bottom and that's exactly the same behavior... Also, reference voltage output pin in the Kicad library are of type "Power Output" so it is logically connected to a Power Input in my opinion.

I'm not part of the people recommending pin stacking, so today I have adopted a neutral position which consist saying nothing about that ! I let the submitter doing the way he want.

**Comment by matthuszagh** [comment]
No worries, @myfreescalewebpage. I've made the changes and stacked the ground pins as per @antoniovazquezblanco's recommendation. I haven't done this for the VCC pins since they require bypass caps.

**Comment by poeschlr** [comment]
Stacking pins means they are placed on top of each other. So please move the invisible pins to the same position as the visible one. (This forces the pins to be always connected together, transferring responsibility from the circuit designer to the library designer.)

**Comment by matthuszagh** [comment]
@poeschlr apologies for that. Updated version is now up.

**Comment by myfreescalewebpage** [comment]
Can you move reference and name close to the box of the symbol as many others ? Example below.

49876155-08380680-fe23-11e8-9854-024e04b928df

**Comment by matthuszagh** [comment]
Done. Note that the reference and name are now off the 100mil grid, but maybe that's only an issue for pin positions?

**Comment by myfreescalewebpage** [comment]
> Note that the reference and name are now off the 100mil grid, but maybe that's only an issue for pin positions?

Yes it is, it's not applicable for reference and name.

@antoniovazquezblanco to my point of view it's ready to be merged.

Joel

**Comment by antoniovazquezblanco** [comment]
@myfreescalewebpage 

> I'm not part of the people recommending pin stacking, so today I have adopted a neutral position which consist saying nothing about that ! I let the submitter doing the way he want.

I don't like it very much. In the future, if we are lucky enough, we will see a feature in KiCad allowing to have both options (stacked and unstacked), but for the time being, the general librarian consensus is to provide stacked pins when possible in order to make symbols smaller and more convenient.

I will have a look at this in a minute.

**Pull request merged**
