### PR TITLE
Max3284E

### PR DESCRIPTION
**Pull request by jeremysiebers**
Added new component MAX3284E

https://datasheets.maximintegrated.com/en/ds/MAX3280E-MAX3284E.pdf

max3284e

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jeremysiebers** [comment]
Updated component current view:

max3284e

**Comment by Ratfink** [comment]
This PR also adds the MAX14783E, which you have already submitted in another PR.  Please remove it from this one.

**Comment by jeremysiebers** [comment]
- [X] This PR also adds the MAX14783E, which you have already submitted in another PR. Please remove it from this one.

**Comment by Ratfink** [comment]
Thanks for the contribution!

* The footprint filter should just be `SOT?23*`, since the number of pins gets filtered automatically.
* Pin 5 should be named `VL`.
* The drawing inside the symbol body is slightly off-center vertically.  It would be nice to fix that.

Once those small issues are fixed, I think this will be ready to merge.

**Comment by jeremysiebers** [comment]
Hello Evan,
I tried to make it smaller, but on a grid of 100 mInch it will not look as nice. 
Byt the way it is as big as the SP3481CN / CP.

Hello Ratfink, I've updated the symbol:

- [X] The footprint filter should just be SOT?23*, since the number of pins gets filtered automatically.
- [X] Pin 5 should be named VL.
- [X] The drawing inside the symbol body is slightly off-center vertically. It would be nice to fix that.

max3284e

**Comment by Ratfink** [comment]
I agree that it looks like this could be shrunk.  Something like this perhaps?


If you'd really rather not shrink it though, I could merge as-is.

**Comment by jeremysiebers** [comment]
I've shrunk the Max3284E symbol a bit like your example.

max3284e

**Comment by Ratfink** [comment]
Thanks for the contribution!

**Pull request merged**
