### PR TITLE
Added VIPer26LN with alias

### PR DESCRIPTION
**Pull request by aris-kimi**
Alias: VIPer26HN
Datasheet: https://www.st.com/resource/en/datasheet/viper26.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aris-kimi** [comment]
viper

**Comment by myfreescalewebpage** [comment]
Hi @aris-kimi , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter should be `DIP*N6*W7.62mm*`
- [ ] Package in the description should be "DIP-7"
- [ ] I don't really understand the lines in the symbol.... + I'm not sure the drawing on this symbol is useful
- [ ] VDD should be aligned with GND
- [ ] D pins should be stacked and should be on the right
- [ ] FB should be on the left
- [ ] LIM and COMP should be Passive

Cheers,
Joel

**Comment by aris-kimi** [comment]
@myfreescalewebpage i took advantage of a similar symbol, but i will redraw without internal graphics.
Thank you for the comments.

**Comment by aris-kimi** [comment]
viper

**Comment by aris-kimi** [comment]
@myfreescalewebpage i think we are done with this.

**Comment by myfreescalewebpage** [comment]
Hello

Thanks fro the quick fix.
Just realize FB will be better on the right sorry, please change
Also, D pins should be stacked (see previous comment).

Joel

**Comment by aris-kimi** [comment]
viper

**Comment by aris-kimi** [comment]
@myfreescalewebpage i feel we are ready to go now!!

**Comment by myfreescalewebpage** [comment]
lol it's a little bit early.
You just added the SOIC version and I have makes me realize the SOIC version is better than the DIP one. The SOIC version is fact is perfect, no comment on it.

On the DIP version:

- [ ] The pins 7/8 of the DIP version are "DRAIN" and not "D".
- [ ] Can you make the same design than the SOIC version so that the two chip can be exchanged easily. Just the NA pin whiwh is not present on the DIP, but it is good to have all the other pins at the same place.

Joel

**Comment by myfreescalewebpage** [comment]
Thanks for the modifications, no more comments :)

**Pull request merged**
