### PR TITLE
Add Maxim DS1210 Nonvolatile Controller Chip

### PR DESCRIPTION
**Pull request by b1ackmai1er**
[DS1210.pdf](https://github.com/KiCad/kicad-symbols/files/3364525/DS1210.pdf)
ds1210screenshot

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by b1ackmai1er** [comment]
Hi. 

Travis reports a fail but these are pre-existing fails.

No Travis fails on the DS1210 addition or issues related to closing #906 

Regards Phil.

**Comment by b1ackmai1er** [comment]
Update pin names and positions on AS4CM16SA to clear other Travis fails

image

**Comment by chschlue** [comment]
Sorry for the long delay.

Please revert the changes to unrelated symbols.
Also, DS1210 is apparently obsolete. Is there much benefit in adding it?

**Comment by b1ackmai1er** [comment]
Hello, 

Unrelated symbol changes have been reverted.

I don't think there is a policy not to support obsolete devices.

However, I can understand that librarians would prefer to be spend their time supporting current technology.

I can move this to obsolete\power management 

For discussion with other librarians, maybe add a new tag "obsolete" so that if they choose so new devices can by prioritized.

The symbols I haved added so far are mostly obsolete but are in support of the retrocomputing scene where new designs based on old technology are very active. I do have other parts to submit which are also obsolete.

Regards Phil

**Comment by myfreescalewebpage** [comment]
Hi @b1ackmai1er , thanks for contributing,

I have no objection to review old devices if they are still useful. As indicated above it's normal sometimes to have error reported on the other devices, in this case, just ignore and focus on your symbol.

I have no comment on your symbol, merging now.

Joel

**Pull request merged**
