### PR TITLE
Added DA14691 and DA14695

### PR DESCRIPTION
**Pull request by aectaan**
Added DA14691 and DA14695 Dialog Semiconductor BLE5.x MCUs
Datasheet: https://www.dialog-semiconductor.com/sites/default/files/da1469x_datasheet_3v1.pdf
DA14691
footprint PR: https://github.com/KiCad/kicad-footprints/pull/2188

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aectaan , thanks for contributing,

I have not made a full review, but a few comments at the moment:

- [ ] This is a new lib, you should add it to the "sym-lib-table" file
- [ ] Positive power inputs go on the top
- [ ] You can stack GND pins
- [ ] You can reduce the width of the symbol a lot, there is plenty of space lost
- [ ] XTALs at the bottom left or right is usually better to wire the crystals
- [ ] For MCUs we keep only the main function on pin name, this reduce again the width of the symbol.
- [ ] Descriptions should be ended with the package name (see other devices for examples)

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@aectaan ping

**Comment by aectaan** [comment]
Hi, @myfreescalewebpage, sorry for the long response.
- [x] This is a new lib, you should add it to the "sym-lib-table" file
- [x] Positive power inputs go on the top
_moved VSUP_RF to the top_
- [x]  You can stack GND pins
- [x] You can reduce the width of the symbol a lot, there is plenty of space lost
- [x] XTALs at the bottom left or right is usually better to wire the crystals
_XTALs and inductor moved to the bottom left_
- [x] For MCUs we keep only the main function on pin name, this reduce again the width of the symbol.
- [x] Descriptions should be ended with the package name (see other devices for examples)

Best regards, 
Egor

**Comment by myfreescalewebpage** [comment]
Thanks for the update. Following the last changes, you have plenty of travis error. Please fix before I continue the review.
Joel

**Comment by aectaan** [comment]
everything is ok, except 5.1 (footprints waits here https://github.com/KiCad/kicad-footprints/pull/2188)

**Comment by aectaan** [comment]
done

**Comment by myfreescalewebpage** [comment]
Thanks, great job done here ! just need to wait the footprint now.

**Comment by aectaan** [comment]
Hi Joel,
they are here https://github.com/KiCad/kicad-footprints/pull/2188

**Comment by myfreescalewebpage** [comment]
Yes I know. I'm not very good when I speak about footprints so I prefer somebody with more experience with that checking your pull request. Then when it will be done I will merge the symbol.
That's our normal procedure.

**Comment by aectaan** [comment]
Ok, thank you for help with my first PR!

**Comment by myfreescalewebpage** [comment]
You're welcome ! It was a great PR here, I'm surprised of the quality for your first contribution, it's very nice :)

**Comment by aectaan** [comment]
Hi @myfreescalewebpage,
Footprint was added yesterday, I think, that we can merge this PR

**Comment by aectaan** [comment]
@myfreescalewebpage footprint is ready, we can merge it :)

**Comment by myfreescalewebpage** [comment]
thanks to ping me, merging now :)

**Pull request merged**
