### PR TITLE
Adding MAX1112x ADCs

### PR DESCRIPTION
**Pull request by ki5libs**
Adding MAX1112x ADCs
[Datasheet](https://datasheets.maximintegrated.com/en/ds/MAX11120-MAX11128.pdf)
Example of 16-channel ADC:
MAX11126
Example of 8-channel ADC:
MAX11123
Example of 4-channel ADC:
MAX11120

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by ki5libs** [comment]
Hi @chschlue 

thank you for review and sorry for some delay. I've changed default footprints and names as you asked. And you are right, OVDD pin location is also changed, it's moved opposite to DGND.

**Comment by chschlue** [comment]
Thanks.
One more thing: please center the symbols.

**Comment by ki5libs** [comment]
Hi @chschlue 

centering is done

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
