### PR TITLE
DAC: AD9744

### PR DESCRIPTION
**Pull request by calebns**
210MSPS 14bit DAC  from AD
http://www.analog.com/media/en/technical-documentation/data-sheets/AD9744.pdf

image

### CODE REVIEW

**Comment by jkriege2** [comment]
Please set the footprint field to the appropriate footprint `Package_SSOP:TSSOP-28_4.4x9.7mm_P0.65mm` and the FPFilter accordingly to `TSSOP*4.4x9.7mm*P0.65mm*`

**Comment by calebns** [comment]
Fixed

**Comment by jkriege2** [comment]
Thanks for yoour contribution, JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 did you mean to merge

**Comment by jkriege2** [comment]
yes ... somehow I clicked next to the utton and closed the tab??? Now it's merged ;-)

**Pull request merged**
