### PR TITLE
Added Filter/0850BM14E0016

### PR DESCRIPTION
**Pull request by ppielorz**
Added 0850BM14E0016 balun.

image

Datasheet: https://www.johansontechnology.com/datasheets/0850BM14E0016/0850BM14E0016.pdf

Footprint pull-request: https://github.com/KiCad/kicad-footprints/pull/1539.
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @AUTHOR, thanks for contributing,

A single comment I have during my review:

- [ ] Format of footprint filter is not correct. Based on the existing footprint proposition, it should be `Filter*Johanson*1.6x0.8mm*`

Need to wait the footprint before merging this.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks. Waiting the footprint.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@ppielorz following integration of the footprint, you should update the footprint here. Thanks

**Comment by ppielorz** [comment]
Hi,
Footprint is already merged, can we continue with merging the symbol?

**Comment by myfreescalewebpage** [comment]
@ppielorz yes sure, see my last comment, the footprint filter need to be upgraded: `Balun*Johanson*1.6x0.8mm*` is great

**Comment by myfreescalewebpage** [comment]
@ppielorz ping!

**Comment by ppielorz** [comment]
@myfreescalewebpage pong, also footprint needed correction I this. Is everything ok now?

**Comment by myfreescalewebpage** [comment]
@ppielorz yes now every thing is great, merging. Joel

**Pull request merged**
