### PR TITLE
add Mini-Circuits TCP-2-10X power splitter

### PR DESCRIPTION
**Pull request by lorem-ipsum**
[Datasheet](https://ww2.minicircuits.com/pdfs/TCP-2-10X+.pdf), matching footprint PR:  https://github.com/KiCad/kicad-footprints/pull/1762
The outline follows the existing RF splitters (e.g. ADP-2-1W). I put the CON pin next to the SUM port as there was some space. I've also changed all pins to passive as this is a purely passive component without any specified direction.

Screenshot_20190802_160528
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @lorem-ipsum , thanks for contributing,

A single comment I have during my review:

- [ ] Datasheet link to be updated, seems now it is "https://www.minicircuits.com/pdfs/TCP-2-10X+.pdf"

Else ready to merge.

Cheers,
Joel

**Comment by lorem-ipsum** [comment]
Hi @myfreescalewebpage ,

thanks for the review, I've updated the datasheet URL.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
