### PR TITLE
Modified sensor DHT11

### PR DESCRIPTION
**Pull request by Misca1234**
Push of the sensor DHT11

Datasheet
http://akizukidenshi.com/download/ds/aosong/DHT11.pdf

Symbol push
https://github.com/KiCad/kicad-symbols/pull/1456

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1336

3D model push
https://github.com/KiCad/kicad-packages3D/pull/520

3D model script push
https://github.com/KiCad/kicad-packages3D-source/pull/205

bild

bild

bild

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@Misca1234 no comment here, just need to wait for the footprint.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Footprint was merged, merging the symbol.

**Comment by evanshultz** [comment]
As mentioned at https://github.com/KiCad/kicad-symbols/pull/586#issuecomment-448380298, pin 2 should have been called DATA. See page 3 of the datasheet above, for just one example.

**Comment by myfreescalewebpage** [comment]
@evanshultz sorry for that, not think to this when merging. @Misca1234 was creating a new PR each time a modification was required (!) for no reason so it was very difficult to follow the discussions on this symbol...

By the way, I don't think this is a trouble to call the pin DATA or IO due to the simplicity of this device...

**Pull request merged**
