### PR TITLE
Add ZENxxxVyyyAzzLS power protection and its alias

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://m.littelfuse.com/~/media/electronics/datasheets/polyzen_devices/littelfuse_polyzen_standard_polyzen_catalog_datasheet.pdf.pdf

imagen

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- Fill the symbol background.
- The symbol outline thickness should be 10mil.
- Set pin name offset to 20mil.
- Datasheet links are only in the DCM file, not in the symbol in the LIB file.
- I would prefer all capital letters in pin names.
- Can this symbol shrink any?
- There is only one footprint for the 'LS parts, so add a default footprint and footprint filter.
- If you submitted a new footprint please link it here.
- I think the in and out pins should be Passive type.
- Since these are marked as zener diodes, I think the ref des should be D and not U.
- Since you've added every member of the family, remove the generic symbol.
- Comma separate the voltages and current in the description.
- I would like to see the footprint name at the end of the description but it's a but complicated here. Do you see a nice, short name for this footprint?

**Comment by evanshultz** [comment]
Can you post a new screenshot?

**Comment by evanshultz** [comment]
- You don't need to duplicate electrical parameters in description and keywords. Please remove keywords.
- Let's name the footprint `Littelfuse_PolyZen-LS` and update the footprint filter to `Littelfuse*PolyZen*LS*`.
- Are you planning to submit a footprint? Currently it's missing and I prefer not to merge without it.
- Your pins are not on grid. You can use this:
```
# ZEN056V130A24LS
#
DEF ZEN056V130A24LS D 0 20 Y Y 1 F N
F0 "D" 0 350 50 H V C CNN
F1 "ZEN056V130A24LS" 0 250 50 H V C CNN
F2 "Diode_SMD:Littelfuse_PolyZen-LS" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
ALIAS ZEN059V130A24LS ZEN065V130A24LS ZEN098V130A24LS ZEN132V130A24LS ZEN164V130A24LS ZEN056V230A16LS ZEN065V230A16LS ZEN098V230A16LS ZEN132V230A16LS ZEN056V075A48LS ZEN132V075A48LS ZEN056V115A24LS
$FPLIST
 Littelfuse*PolyZen*LS*
$ENDFPLIST
DRAW
S -200 200 200 -100 0 1 10 f
X VIN 1 -300 100 100 R 50 50 1 1 P
X GND 2 0 -200 100 U 50 50 1 1 W
X VOUT 3 300 100 100 L 50 50 1 1 P
ENDDRAW
ENDDEF
```

Image of above:
image

**Comment by carlosromorgar** [comment]
Hi
This is the new screenshot

image


I am going to submit a footprint for this symbol.
Thanks
Regards

**Comment by evanshultz** [comment]
This looks good! Please fix the footprint filter: it's "el" and not "le". So tricky!

I'll look at the footprint.

**Comment by evanshultz** [comment]
This symbol looks good to me. But I just realized it's in `Diode` but I believe it should be in `Power_Protection`. Sorry about that. Can you please move this symbol to the right library and I can merge?

**Comment by carlosromorgar** [comment]
Thanks for your comments, @evanshultz 

I don't find the  `Power_Protection` library in the master branch of the repository. It is necessary to create it? Or it is my fault? Thank you in advance.
BR

**Comment by antoniovazquezblanco** [comment]
I believe it is present in our repo. Please update your master branch and the library list in the schematic editor tool to add all the available libraries in the repo.

https://github.com/iit-asi/kicad-symbols/blob/master/Power_Protection.lib

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
