### PR TITLE
added nRF52811

### PR DESCRIPTION
**Pull request by rs-development**
[Datasheet](https://infocenter.nordicsemi.com/pdf/nRF52811_PS_v1.0.pdf)

I have not integrated the mcu into my schematics but the layout seems straight forward, i used the existing nrf52xxx as template.

image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @rs-development , thanks for contributing,

A few comments I have during my review:

- [ ] Length of the pins should be 100mil (symbol < 100pins)
- [ ] Package in the description should be "QFN-32", not QFN32
- [ ] Package should be `Package_DFN_QFN:QFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm` (wrong ep size, if it does not exist you should submit it)
- [ ] Name of pin A6 should be `P0.21/~RESET`
- [ ] VDD pins should not be stacked
- [ ] Extra space between P0.20 and P0.25 is not useful, to be removed, decrease height of the symbol

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks for the corrections.

- [ ] Footprint filter should be `QFN*1EP*5x5mm*P0.5mm*`
- [ ] In my opinion you can center VDD pins on the device, as shown below.
Capture

Else, no more comment comment, just need to wait the footprint.

Cheers,
Joel

**Comment by evanshultz** [comment]
This symbol still looks overly tall. No extra space is required above the top pin and below the bottom pin on the right side.

**Comment by myfreescalewebpage** [comment]
Thanks @rs-development for the last fix. I agree with @evanshultz you can reduce the height, decrease by 100mil at the top and 100mil at the bottom.
Joel

**Comment by myfreescalewebpage** [comment]
@rs-development ping!

**Comment by myfreescalewebpage** [comment]
No news of the original author, indicate the PR is abandoned.

**Comment by rs-development** [comment]
@myfreescalewebpage Sorry for the delay, fixed your recommendations.

**Comment by myfreescalewebpage** [comment]
Thanks. Bug of VSS pin, the border should be reduced 100mil to the top.

Capture

**Comment by rs-development** [comment]
image

I think i moved the outline instead of reducing it. Is fixed. Should the CI not detect and visible pin on the outline?

**Comment by myfreescalewebpage** [comment]
Not sure it is easy to automate this test...
Thanks for the fix, no more comment, merging.

**Comment by daviid5** [comment]
@rs-development Pls check if 52810 and 52811 are pin compatible
If yes match the symbol
Note: VDD stacked in 52810 footprint
grafik

**Pull request merged**
