### PR TITLE
Add TPS5420D.

### PR DESCRIPTION
**Pull request by matthuszagh**
TPS5420D
http://www.ti.com/lit/ds/symlink/tps5420.pdf

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh, thanks for contributing,

A few comments I have during my review:

- [ ] footprint filter should be `SOIC*3.9x4.9mm*P1.27mm*` (without the first `*`)
- [ ] looking at other TPS54xxx symbol in the library, and at the datasheet of the TPS5420 I would say BOOT pin type should be set to Input.

KLC S4.2 accepted for this symbol

Cheers,
Joel

**Comment by matthuszagh** [comment]
Thanks Joel, I've made both changes. I also amended the footprint filter from #1262, which has the same problem.

**Comment by myfreescalewebpage** [comment]
> Thanks Joel, I've made both changes. I also amended the footprint filter from #1262, which had the same problem.

I was just making the review of it !

**Comment by myfreescalewebpage** [comment]
@matthuszagh yoou can simply push to your branch when updating the symbol, not force-push it. This permit to keep commit history in the PR and to not review everything each time you make a modification.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco this PR is ready to be merged according to me.

Joel

**Comment by SchrodingersGat** [comment]
Thanks @matthuszagh for the contribution and @myfreescalewebpage for the review :)

**Pull request merged**
