### PR TITLE
Add open collector symbol to 74 ports

### PR DESCRIPTION
**Pull request by hildogjr**
removed bck files

### CODE REVIEW

**Comment by hildogjr** [comment]
This pull request add the open collector symbol to several logic ports (Fix #2446):
Screenshot from 2020-01-17 22-01-49

Add open collector symbol to some analog comparators, moving it close to the output pin with correspondent open collector behaviour
Screenshot from 2020-01-17 22-03-41
:

**Comment by chschlue** [comment]
FYI: I proposed splitting comparator symbols into open collector and open drain types at https://github.com/KiCad/kicad-symbols/pull/2467.
The problem with your changes to comparators is that it also marks aliases which are actually push-pull parts.
Perhaps you could narrow this PR to logic only while I add OC symbols to #2467?

**Comment by hildogjr** [comment]
Some different parts (not variation of the same one) are marked as alias. Could you give me enunciate some of the part problems?

**Comment by chschlue** [comment]
Example:
ADCMP350/354/356 are aliases but 350/354 are open drain while 356 is push-pull.

**Pull request closed without merging**
