### PR TITLE
added aliases for OPA365

### PR DESCRIPTION
**Pull request by aracosta1**
Added the aliases for OPA365xx to the library.
documentation at [https://www.ti.com/lit/ds/symlink/opa365.pdf](https://www.ti.com/lit/ds/symlink/opa365.pdf)

SOIC version
image

SOT-23 version
image

---

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@aracosta1 is it still a draft ?

**Comment by aracosta1** [comment]
No, forgot to change the state

**Comment by myfreescalewebpage** [comment]
Hi @aracosta1 full review below:

OPA365xB
- [ ] Name should be "OPA365xxDBV"

OPA365xD
- [ ] Please remove special character in "Zerø" in the description

Joel

**Comment by aracosta1** [comment]
Looking at the datasheet also the OPA365xD should be renamed OPA365xxD to keep coherence

**Comment by myfreescalewebpage** [comment]
Yes sure ! Added to the review above.

**Comment by aracosta1** [comment]
I made the requested correction and updated the part names.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
