### PR TITLE
add BSP89 as alias and fix symbol of BSP129

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the [BSP89](https://www.infineon.com/dgdl/Infineon-BSP89-DS-v02_02-en.pdf?fileId=db3a30433b47825b013b4b8a07f90d55) as alias to the existing [BSP129](https://www.infineon.com/dgdl/Infineon-BSP129-DS-v01_42-en.pdf?fileId=db3a30433c1a8752013c1fc296d2395f). It also fixes the gate pin of the BSP129. The length was set to 100mils, causing the pin to end before the gate.

Screenshot_20190809_135412

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
This seems to be linked to https://github.com/KiCad/kicad-symbols/pull/1976

**Comment by electroniceel** [comment]
I don't think BSP89 is a correct alias of BSP129:

BSP89 is enhancement mode, BSP129 is depletion mode. These are different symbols.

The current symbol for BSP129 shows an enhancement fet which is wrong. I have just uploaded symbols for depletion mode FETs (including a fixed BSP129) in #2095 .

**Comment by lorem-ipsum** [comment]
I made the BSP89 a unique symbol instead of an alias to the BSP129. It is a copy of the current symbol of the BSP129 which is correct for the BSP89 (but not for the BSP129). Also added the enhancement mode to the description.

**Comment by evanshultz** [comment]
@lorem-ipsum 
Thanks!

Because the description for FETs is all over the place, I'll go ahead and merge this. But https://github.com/KiCad/kicad-symbols/issues/1617 is capturing this issue (and for other symbol types too) and perhaps we can standardize things later. For example, always include the FET type?

**Pull request merged**
