### PR TITLE
Add W25Q32JVZP

### PR DESCRIPTION
**Pull request by matthuszagh**
http://www.winbond.com/resource-files/w25q32jv%20revg%2003272018%20plus.pdf

image

footprint: https://github.com/KiCad/kicad-footprints/pull/1291

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by matthuszagh** [comment]
Good catch @myfreescalewebpage. Do you think it's really worthwhile keeping that one? I'm not even sure if a DFN exists with those specs.

**Comment by myfreescalewebpage** [comment]
> Do you think it's really worthwhile keeping that one?

Are you speaking of the footprint ?
If yes, can be kept but we will not review with a high priority.

**Comment by matthuszagh** [comment]
Ok, I've added the fp [here](https://github.com/KiCad/kicad-footprints/pull/1293).

I ended up removing the other footprint because I don't think it's worth the extra work it will take in review, especially since I don't know if any packages use it. If you really think it's worth keeping I can bring it back.

**Comment by myfreescalewebpage** [comment]
Thanks. No more comment on the symbol, need to wait the footprint now.

Joel

**Comment by myfreescalewebpage** [comment]
@matthuszagh no more comment here, footprint was merged, merging the symbol. Thanks for your contribution.

**Pull request merged**
