### PR TITLE
add LT3015Q

### PR DESCRIPTION
**Pull request by aewallin**
LT3015Q adjustable negative low noise voltage regulator in TO-263-5 package.

datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/3015fb.pdf

Screenshot:
lt3015q

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @aewallin, thanks for contributing,

Looks great, maybe you can enlarge a little bit the symbol vertically between pins SHDN/VIN and ADJ/OUT. @antoniovazquezblanco @DanSGiesbrecht what do you think about that ? Else, ready to be merged.

Cheers,
Joel

**Comment by aewallin** [comment]
We almost always use LT3015 (this one) together with LT1963 (PR #1169) - IMO best to make the symbols similar.
If the symbol shape is agreed on I can add these v-regulators in fixed-voltage output format and other footprints also.

**Comment by myfreescalewebpage** [comment]
@aewallin I agree we should treat both PR at the same time, I have the same remark for PR #1169.

Just adding below an example (LT3010) of what I mean by enlarging a little bit the symbol. This is to get a better consistency between symbols.

reg

**Comment by myfreescalewebpage** [comment]
@aewallin can you fix the footprint filter to `TO?263?5*` ?

**Comment by evanshultz** [comment]
Footprint filters should not have pin count, so don't include the `?5` part. Furthermore, use asterisks instead of question makes wherever possible and that applies to all instances here. Note that I haven't looked at anything else but the last comment.

**Comment by myfreescalewebpage** [comment]
@evanshultz ok. @aewallin so keep the footprint like that for that PR.

**Comment by aewallin** [comment]
fp-filter changed.
box enlarged.
library seems inconsistent on negative voltage regulators: to have Vin/Vout at bottom and GND at top, or like positive regulators Vin/Vout at top and GND at bottom. now using latter approach.
lt3015q

**Comment by aewallin** [comment]
> maybe you can provide a screenshot.

The two styles I was thinking about are below. Maybe it is best to have symbols KLC-compliant with GND down, and the user can flip with X/Y as appropriate for the schematic.

GND-down style on +v and -v:
dual-polarity-regulated-power-supply-1326579994

GND-up on -v, with a symmetryc drawing for a bipolar supply:
dual voltage

**Comment by myfreescalewebpage** [comment]
@aewallin agreed with you I have forgotten X flip possibility and just made a try. Your proposition sounds good and it respects the KLC so that's also very nice !

@antoniovazquezblanco I think this PR is ready to be merged.

**Comment by aewallin** [comment]
@myfreescalewebpage Looking at examples from the current regulator_linear library it looks like some ADJ/SENSE/FB pins are marked Passive, and some are marked Input.

Any opinion on this from a Librarian - I'll change the ADJ pin type here and in #1169, if there is consensus.

**Comment by myfreescalewebpage** [comment]
Any librarian about ADJ pin type question ? Thanks.

**Comment by antoniovazquezblanco** [comment]
@KiCad/librarians question above, please :)

**Comment by Misca1234** [comment]
Even if older merges is different I would argue to follow the data sheet,
according to page 14, 
SHDN should be input 
SENSE should be input

**Comment by DanSGiesbrecht** [comment]
I think that either passive or input is suitable for `ADJ`. I have seen it argued that it should be passive because you could feed it with a resistor-divider, but this wouldn't generate an ERC warning if the pin was an input. This could be suggested to be formalized in the KLC.

**Comment by Misca1234** [comment]
yes, the ERC .....

**Comment by aewallin** [comment]
after changes:
lt3015q

**Comment by poeschlr** [comment]
Regarding pin types: we are working on setting up an algorithm for determening which type to use. See https://github.com/KiCad/kicad-website/issues/342

**Comment by Misca1234** [comment]
I am happy with this little gem, any objections ?

**Comment by poeschlr** [comment]
Not from my side. As there are already so many reviews i am going to assume this is ok and simply merge. Thanks @aewallin for your great work here.

**Pull request merged**
