### PR TITLE
fixed I2C-pintypes (SCL in slaves INPUT) 

### PR DESCRIPTION
**Pull request by jkriege2**
- affected devices:
  - ADS128D818
  - BQ78350 
  - AS3935 
  - HDC1080
  - TMP411 
  - DS1621 
  - LTR-303ALS-01 
  - APDS-9301

- some other KLC-violationson the way (wrong FPFilters, made some pin-stacks, fixed broken datasheet, moved NC-pins to where they cannot be erroneously connected)

### CODE REVIEW

**Comment by Shackmeister** [comment]
Perhaps we should make SCL bidirectional if the device supports clock stretching https://www.i2c-bus.org/clock-stretching/
Which I believe most do

**Comment by evanshultz** [comment]
@jkriege2 
Sorry to let this linger! Can you fix branch conflicts and I'll take a look?

**Comment by jkriege2** [comment]
done!

**Comment by evanshultz** [comment]
@jkriege2 
Great! There is a good number of errors still. Do you want to fix anything else or merge this now?

@Shackmeister 
Holding the SCL bus "low" is not outputting a signal. SCL is only an input for all slave devices.

**Comment by jkriege2** [comment]
fixed several of the errors, some footprints are simply missing (don't have time to add them right now!).

i.e. please merge in this state, if there aren't any serious objections right now.

Thanks
JAN

**Pull request merged**
