### PR TITLE
Add symbol for 4021 shift register

### PR DESCRIPTION
**Pull request by dogtopus**
Datasheet (TI): https://www.ti.com/lit/ds/symlink/cd4021b.pdf
Datasheet (Nexperia): https://assets.nexperia.com/documents/data-sheet/HEF4021B.pdf

Somehow this is missing. Add it as somebody else and I might need it.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @dogtopus , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint filter should be only `SOIC*3.9x9.9mm*P1.27mm*` and `TSSOP*4.4x5mm*P0.65mm*` except if you can provide some other datasheet indicating the other package versions exist for this device
- [ ] Pin 10 graphic style should be "Line"

Cheers,
Joel

**Comment by dogtopus** [comment]
> Footprint filter should be only SOIC*3.9x9.9mm*P1.27mm* and TSSOP*4.4x5mm*P0.65mm*

That's true for Nexperia. However TI provides them in `DIP*W7.62mm*` and `SOIC*5.3x10.2mm*P1.27mm*` form factor as well. (See CD4021BE and CD4021BN respectively)

However I believe that `SOIC*7.5x10.3mm*P1.27mm*` was indeed added by mistake and I will remove it soon.

Also do I need to include multiple datasheets in case that different manufactures produces the same part of different form factors? If so, how?

> Pin 10 graphic style should be "Line"

This is the clock pin of the shift register so AFAIK it should have the clock graphic style. However I checked the other 4xxx symbols with the clock pin. Some of them had the clock pin set as clock, some don't. So my question is: is there any rule for when a clock pin does not need to be set as clock? Or it is just simply a historical thing and all new 4xxx symbols should not have the clock pins set as clock?

**Comment by myfreescalewebpage** [comment]
> That's true for Nexperia. However TI provides them in DIP*W7.62mm* and SOIC*5.3x10.2mm*P1.27mm* form factor as well. (See CD4021BE and CD4021BN respectively)

Great!

> However I believe that SOIC*7.5x10.3mm*P1.27mm* was indeed added by mistake and I will remove it soon.

Yes please, thanks!

> Also do I need to include multiple datasheets in case that different manufactures produces the same part of different form factors? If so, how?

It's not possible, just keep the current one.

> This is the clock pin of the shift register so AFAIK it should have the clock graphic style.

The KLC now indicate we do no more use other styles, we use only Line.

Joel

**Comment by dogtopus** [comment]
Resolved

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
