### PR TITLE
Atmel

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Pulled across the old `atmel.lib` library

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Lots of KLC errors here, too many that I want to spend any time on them right now.

**Comment by jkriege2** [comment]
Hi!

first of all: There are some conflicts ;-)
then some symbols went into the wrong libs:
1. All AT89* should go to MCU_Atmel_8051
2. All AT90* should go to MCU_Atmel_AVRClassic

**Comment by jkriege2** [comment]
Hi!

looking at this PR: https://github.com/KiCad/kicad-symbols/pull/53

We should think about one thing: Atmel was bought by Microchip this year ... so how do we deal with this? Should we put these µCs into MCU_Atmel or MCU_Microchip? I think people will expect them (at the moment) in the Atmel lib, but that will surely change with the next 1-2 years, when the brand name Atmel will get forgotten (I suspect)

**Comment by poeschlr** [comment]
As long as the chips are sold under the brand atmel i don't see a problem with keeping the current lib names. (Normally the brand name is kept for quite a while.)

**Comment by jkriege2** [comment]
Hi!

please have a look at these two PRs from @DerekGn:
- https://github.com/KiCad/kicad-symbols/pull/53
- https://github.com/KiCad/kicad-symbols/pull/50

They allready pull over and fix some of the ARM-µCs from Atmel ... Also he renamed them to Microchip already ... How should we deal with this conflict?

Best,
JAN

**Comment by DerekGn** [comment]
I created the first versions of the SAML and SAME parts in the atmel.lib.

The new versions in PR #53 and #50 should replace the ovelapping parts as they are better they follow the KLC more closely.

**Comment by jkriege2** [comment]
Fine with me ... I will merge the two PRs and @SchrodingersGat could you remove those from your PR?

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Which symbols do I need to remove from my PR?

**Comment by jkriege2** [comment]
Hi! you need to leave out the ones mentioned in the linked PRs:


## https://github.com/KiCad/kicad-symbols/pull/53
```
ATSAML21E15B-AUT
ATSAML21E15B-MUT
ATSAML21E16B-AUT
ATSAML21E16B-MUT
ATSAML21E17B-AUT
ATSAML21E17B-MUT
ATSAML21E18B-AUT
ATSAML21E18B-MUT
ATSAML21G16B-AUT
ATSAML21G16B-MUT
ATSAML21G17B-AUT
ATSAML21G17B-MUT
ATSAML21G18B-AUT
ATSAML21G18B-MUT
ATSAML21J16B-AUT
ATSAML21J16B-MUT
ATSAML21J17B-AUT
ATSAML21J17B-MUT
ATSAML21J18B-AUT
ATSAML21J18B-MUT
```

## https://github.com/KiCad/kicad-symbols/pull/100
```
ATSAME70J19A-AN
ATSAME70J20A-AN
ATSAME70J21A-AN
ATSAME70N19A-AN
ATSAME70N20A-AN
ATSAME70N21A-AN
ATSAME70Q19A-AN
ATSAME70Q20A-AN
ATSAME70Q21A-AN
```

**Comment by SchrodingersGat** [comment]
Ok, please refer to new PR here - https://github.com/KiCad/kicad-symbols/pull/108

**Pull request closed without merging**
