### PR TITLE
AD633/733/734, MAX333[A]

### PR DESCRIPTION
**Pull request by evanshultz**
Datasheets:
- https://datasheets.maximintegrated.com/en/ds/MAX333.pdf
- https://datasheets.maximintegrated.com/en/ds/MAX333A.pdf
- http://www.analog.com/media/en/technical-documentation/data-sheets/ADG633.pdf
- http://www.analog.com/media/en/technical-documentation/data-sheets/ADG733_734.pdf

Image:
image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ x ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ x ] An example screenshot image is very helpful
- [ x ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
After sorting out how to name the EP, mentioned at https://github.com/KiCad/kicad-footprints/pull/318, I'll submit the missing LFCSP footprint.

**Comment by evanshultz** [comment]
For some reason, MAXIM does not show the packages in the datasheets. I asked them for info:
- TSSOP, 20, 45.2mm^2: https://pdfserv.maximintegrated.com/package_dwgs/21-0066.PDF
- PDIP (N), 20: https://pdfserv.maximintegrated.com/package_dwgs/21-0043.PDF
- SOIC (W): https://pdfserv.maximintegrated.com/package_dwgs/21-0703.PDF
- SSOP 20: https://pdfserv.maximintegrated.com/package_dwgs/21-0056.PDF

**Comment by evanshultz** [comment]
@jkriege2 
You updated the symbols in this lib. Would you mind taking a look at this PR?

**Comment by jkriege2** [comment]
Looks good,

Thanks,
JAN

**Comment by jkriege2** [comment]
Hi!

looks good, thanks. Only the LFCSP-package is still missing ... I can merge without it existing, or wait if you want to post a PR for it?

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Please merge as is. I mentioned above I'll make the footprint.

**Pull request merged**
