### PR TITLE
Add ADA4898-1 in SOIC-8-1EP

### PR DESCRIPTION
**Pull request by aewallin**
https://www.analog.com/media/en/technical-documentation/data-sheets/ada4898-1_4898-2.pdf

PD and exposed-pad pins in addition to the usual op-amp pins. SOIC-8-1EP footprint.
ada4898-1yrdz

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by diegoherranz** [comment]
Thanks for submitting this symbol.
A few comments, very similar to https://github.com/KiCad/kicad-symbols/pull/1238:
- Regarding the exposed pad, the datasheet says the following which makes me think that the electrical type should be "Passive" and not "Power input". Could you change it?

> "Exposed Pad. Can be connected to the negative supply (−VS) or can be left floating."

- Could you add "single" and "opamp" to the keywords?

Thanks!

**Comment by aewallin** [comment]
Thanks for the review. Changes made as suggested:
ada4898-1yrdz

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments additionally to @diegoherranz :

- [ ] footprint filter should be `SOIC*EP*3.9x4.9mm*P1.27mm*`
- [ ] Pin EP text size is too small, should be 50mil, see travis output error S3.2 (just tried this is OK for 50mil even if there is not a lot of extra space in the symbol)

KLC S3.6 accepted for this symbol.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco PR ready to be merged according to me.

**Comment by myfreescalewebpage** [comment]
@aewallin we have a conflict due to other PR merged, can you solve it ? thanks.

Joel

**Comment by aewallin** [comment]
> @aewallin we have a conflict due to other PR merged, can you solve it ? thanks.

yep, done. Is it possible to get notificatoins from github when there's a new merge-conflict?
Is there some tool to check if the conflict is merged OK - especially if there are undesired changes to an already existing symbol?

I have added the footprint at the end of the description.

**Comment by myfreescalewebpage** [comment]
@aewallin great, yes following other PR it's good to add package name at the end of the description, thanks for the  modification.

I do not know if it is possible to get a notification when a merge conflict appears.

@antoniovazquezblanco PR ready to be merged following merge conflict resolution by @aewallin

**Comment by antoniovazquezblanco** [comment]
I think everything is fine.

Thank you both!

**Pull request merged**
