### PR TITLE
TPS821X0 Integrated Buck Modules

### PR DESCRIPTION
**Pull request by awygle**
Adds TPS82130, TPS82140, and TPS82150 integrated buck regulator modules.

Datasheet is http://www.ti.com/general/docs/lit/getliterature.tsp?genericPartNumber=tps82130&fileType=pdf

Footprint PR is https://github.com/KiCad/kicad-footprints/pull/931

image

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by awygle** [comment]
Whoops, scrubbed the extraneous commits from the branch.

The only remaining _fatal_ Travis error is the lack of footprint. The non-fatal Travis errors either contradict the KLC (VOUT is passive for pin stacking reasons) or I disagree with them (VIN may be a power input, but it's primarily an input, and belongs on the left). Let me know if I should obey the script anyway.

**Comment by Misca1234** [comment]
Hi

Thx for the contribution

Please change the following
Foot print filter from
Texas*MicroSiP?8*1EP*2.8x3.0mm*P0.65mm*
Into
Texas*MicroSiP*1EP*2.8x3.0mm*P0.65mm*

change all descriptions to end like this
for from
17V Input 3A Step-Down Converter MicroSiP Module with Integrated Inductor
into
17V Input 3A Step-Down Converter MicroSiP Module with Integrated Inductor**, μSiL-8**


What do you say about moving pin 8 to left side and move pin 7 to the right side ?
or at least move pin 8?

**Comment by awygle** [comment]
@Misca1234 I moved pin 8, but didn't move pin 7. I think it's cleaner to separate "control" signals from the power output side. I'll move it if you like though.

I also did those other things. I'll go through all my open PRs and add the packages to the descriptions as well.

**Comment by Misca1234** [comment]
Ok, thx

**Pull request merged**
