### PR TITLE
Relay: Add Panasonic ADW11 series

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: https://www.panasonic-electric-works.com/pew/es/downloads/ds_dw_hl_en.pdf

SYM PR: KiCad/kicad-symbols#1915
FP PR: KiCad/kicad-footprints#1638
3D PR: https://github.com/KiCad/kicad-packages3D/pull/572
3D SOURCE PR: easyw/kicad-3d-models-in-freecad#289

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Can it just be `ADW11`? The 'W' suffix is only on packaging and the datasheet clearly mentions 'ADW1'.
1. Please note a single coil in the description to differentiate if ADW12 is added later.
1. Can you show polarity of the coil?
1. I count an excessive number of rectangles and polylines in the symbol. Only 5 and 10, respectively, should be needed. Can you simplify it?

**Comment by antoniovazquezblanco** [comment]
Used a style more conforming to what currently exists in the lib:
imagen

**Comment by evanshultz** [comment]
Great! Just need the footprint.

**Comment by antoniovazquezblanco** [comment]
Depends on https://github.com/KiCad/kicad-website/issues/418

**Comment by antoniovazquezblanco** [comment]
Updated FP. FP merged.

**Comment by evanshultz** [comment]
Thanks!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
