### PR TITLE
Remove ATSAMD21G18A-AUT

### PR DESCRIPTION
**Pull request by aris-kimi**
Remove ATSAMD21G18A-AUT kept only -A

### CODE REVIEW

**Comment by aris-kimi** [comment]
@cpresser I saw this at the issues and did something. Tell me if we are good.

Thank you.

**Comment by cpresser** [comment]
Hi @aris-kimi 
This PR looks okay. But It will have to wait for v6.0. The issue was a reminder for that.
I marked this PR so we can look at it again once we are nearing 6.0.

**Comment by aris-kimi** [comment]
Hi @cpresser, thank you for your answer. So this means the pull request will remain open until then right??

**Comment by cpresser** [comment]
Correct.

**Comment by myfreescalewebpage** [comment]
Reference: https://github.com/KiCad/kicad-symbols/issues/2563

**Comment by myfreescalewebpage** [comment]
No more comment, @cpresser is right, should be merged with V6.

**Pull request merged**
