### PR TITLE
Adding MT3608 asynchronous DC-DC boost (step-up) converter.

### PR DESCRIPTION
**Pull request by persus**
Adding MT3608 asynchronous DC-DC boost (step-up) converter.

image

---

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
This is becoming annoying.
See https://github.com/KiCad/kicad-symbols/pull/2322#issuecomment-556957448

**Comment by persus** [comment]
Sorry.
https://www.olimex.com/Products/Breadboarding/BB-PWR-3608/resources/MT3608.pdf

**Comment by chschlue** [comment]
- [ ] Use manufacturer DS URL
- [ ] Change SW pin type to passive

**Comment by persus** [comment]
> * [ ]  Use manufacturer DS URL
> * [X]  Change SW pin type to passive

Manufacturer is Xi'an Aerosemi Tech Co. Ltd. There is no datasheet to find at the manufacturers site.

image

**Comment by chschlue** [comment]
> Manufacturer is Xi'an Aerosemi Tech Co. Ltd. There is no datasheet to find at the manufacturers site.

I see.

One more thing I missed: NC pin must be on or within the symbol's outline.

**Comment by persus** [comment]
I see. Like this?

image

**Comment by chschlue** [comment]
Thanks

**Pull request merged**
