### PR TITLE
Res us

### PR DESCRIPTION
**Pull request by Vlad-23**
US Resistor symbols (Networks Varistor Thermistor POT) was added to device lib. POT* was renamed to R_POT*

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
I guess I'm not opposed to it, and since we already have alternate styles for e.g. diodes, I suppose there's already some precedent for this.  I would want us to settle all the questions in #298 (that is, we should take all discussion that isn't specifically about this PR's changes over to #298) before merging this though.

**Comment by evanshultz** [comment]
@Vlad-23 
It's requested to attach an image of all symbols or footprints submitted. Could you do that for ease of discussion here? It would be nice to include the box style and US style for comparison in your image.

**Comment by Vlad-23** [comment]
Hi!
Image as you requested. I also included box style for comparison (except for networks), as you mentioned. I think _US prefix is fine because it's commonly called "US-Style" or "American". So it's more obvious than _ALT for most people.
[R_US_SCR.pdf](https://github.com/KiCad/kicad-symbols/files/1909243/R_US_SCR.pdf)

**Comment by evanshultz** [comment]
image

**Comment by jkriege2** [comment]
Ok, I would also be in favour of merging this ... but before we can proceed it would be good to fix some smaller style/implementation issues:
1. please shorten the pins to multiples of 50mil (e.g. there are a log with length 102mil). If you need lines in between, please add them as simple lines.
2. I saw you added `R_POT_US`, but no version `R_POT_TRIM`... is there a specific reason why you didn't add that quite commonly used symbol?
3. You added Thermistor_US and Thermistor_NTC_US, but no PTC variant ... could you please add that one too? Then we have the full basic set of thermistors
4. Please remove the FPFilters `SM0603` and `SM0805` from `Thermistor_US` (and `Thermistor`)

Best,
JAN

**Comment by Vlad-23** [comment]
Hi, JAN

I have fixed issues that you had mentioned. Can you please check it now?

res_scr

**Comment by jkriege2** [comment]
@evanshultz @SchrodingersGat @pointhi @poeschlr @Misca1234 @Ratfink 
I would merge this PR with the US resistors now, because already the limited set of symbols is a good start here. Before I would like to check two things with you guys:

1. Are there any more objections from your side(s)?
2. I think the rename POT_... to R_POT_... in this PR is fine and helps to organize them symbols a bit better in device.lib. Any objections on that?

Best,
JAN

**Comment by jkriege2** [comment]
Thanks for the work you put into this!

JAN

**Pull request merged**
