### PR TITLE
change CRLF to LF in a bunch of files

### PR DESCRIPTION
**Pull request by ppelleti**
So, I'm finding it impossible to work with the `kicad-symbols` repository, because git keeps insisting a bunch of files are modified when they're not.  This seems to be because the files have CRLF line endings.

Is there some reason I'm the only one having this problem?  Is there something I should be doing differently?

But I believe the KLC specifies files should have LF endings, in which case they should be changed anyway.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by diegoherranz** [comment]
+1
I've been suffering this. It's a pain to work with as is.

Thanks!

**Comment by evanshultz** [comment]
Yes, they should. See http://kicad-pcb.org/libraries/klc/G1.7/.

I think this was me. I'm a Windows user and I touched some or all of those files recently. I'm not aware of a way to make KiCad using a specific line ending when writing files so I convert the files manually after saving in KiCad (or rather auto-manually using Notepad++) - which I seemingly forgot to do here.

I recall having our repos catch this but apparently that only worked on footprint files. https://github.com/KiCad/kicad-library-utils/tree/master/schlib/rules doesn't have a rule for G1.7 but for footprints it's at https://github.com/KiCad/kicad-library-utils/blob/master/pcb/rules/G1_7.py. I created an issue for this at https://github.com/KiCad/kicad-library-utils/issues/259.

It looks to me like only line endings were changed. Please confirm that if you would and I'll merge. Sorry and thank you.

**Comment by ppelleti** [comment]
> It looks to me like only line endings were changed. Please confirm that if you would and I'll merge. 

Yes, I did not change anything.  This is just what git insisted on changing automatically, which should be the line endings.

> I'm not aware of a way to make KiCad using a specific line ending when writing files so I convert the files manually after saving in KiCad (or rather auto-manually using Notepad++)

Git ought to convert the CRLF to LF when you check files in.  (After all, that's the problem I'm having: that git wants to automatically convert CRLF to LF.)  Maybe you need to [adjust your git configuration](https://help.github.com/articles/dealing-with-line-endings/)?

Although I thought that the `text=auto` in the [.gitattributes](https://github.com/KiCad/kicad-symbols/blob/master/.gitattributes) file should already be configuring the line endings to be handled automatically?

**Comment by evanshultz** [comment]
Right, I thought that should do it as well. Not sure what's going on.

@SchrodingersGat
I think you set this up. Do you know for sure this was working and if or why things may have broken?

**Comment by evanshultz** [comment]
Ummm... I feel a bit embarrassed to say but I use the GitHub Desktop app unless I need to pop to the command line. I may have done something dumb on the opamp/comparator commit. I don't recall but I'll keep an eye on it.

**Comment by poeschlr** [comment]
The github desktop app might go through the github api instead of using git. 
This would explain why git settings do not help in that case.

**Pull request merged**
