### PR TITLE
Creation of a new lib for the STM32G4 series of MCU from ST Microelec…

### PR DESCRIPTION
**Pull request by eleinur**
Hi,
I've created a new schematic library for the STM32G4 series of MCU from ST Microelectronics.
The library contains 2 symbols.
The pinout is different (power supplies, boot0) compared to others ST MCU in the same packages. 
I've started with the smaller MCU of this family. If the two firsts are OK for you, I can continue with the others MCU of this family.
The footprints are the same than the others ST MCU.

Datasheet of the STM32G431 MCU
https://www.st.com/resource/en/datasheet/stm32g431kb.pdf

Matching footprints
Package_QFP:LQFP-32_7x7mm_P0.8mm
Package_QFP:LQFP-48_7x7mm_P0.5mm

Best regards

Oliver

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:
stm32g4_32pins
stm32g4_48pins

### CODE REVIEW

**Comment by cpresser** [comment]
Hello Oliver,

thanks for your first contribution :heart: 
In order to accept it you will have to sign the CLA. Then we will do a review of your PR. Thanks.

**Comment by eleinur** [comment]
Hello,
I don't manage to sign the CLA. The commit has been done using git on my professional PC and I don't manage to re-affect the commit to my personal email associated with my Github account. I've tried to all emails address in my github account but it doesn't work. Is it possible to recommit with the email of my Github account?
Bets regards.

**Comment by chschlue** [comment]
You can either rewrite all commits and force-push or add another address to your github account.

**Comment by cpresser** [comment]
> I don't manage to sign the CLA.
>

I had similar issues once. I think my solution was as described by @chschlue. 

Since there are multiple commits that need changing the solution described here might be the best one: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**OR**
If you don't feel confident with the git magic you can start from a clean repository, set the correct author in the local and/or repository config. Then copy the changed files into the new repository, create a branch and new commits. Finally push to github creating a new PR. In this case we will close this PR and work in the new PR.

**Comment by myfreescalewebpage** [comment]
@eleinur any news about the branch problem here ?

**Comment by eleinur** [comment]
> @eleinur any news about the branch problem here ?

@myfreescalewebpage Hi, the branch problem seems to block the normal process (I've generated conflicts). Sorry, it's my fault I forgot to change the user name. I don't know what should I do to move forward. The pull request only concerns two 2 lib files. Maybe we should close this pull request and reopen a new one from master branch. It may be easier.
FYI I've used the lib files I've created on several boards I've designed and manufactured. So I hope we find a way to integrate those components in Kicad libraries.

**Comment by myfreescalewebpage** [comment]
> Maybe we should close this pull request and reopen a new one from master branch. It may be easier.

If this is easier for you yes you can.

> So I hope we find a way to integrate those components in Kicad libraries.

With pleasure :)

**Pull request closed without merging**
