### PR TITLE
Add Nexperia PMEG SOT-1289 Schottky diodes

### PR DESCRIPTION
**Pull request by chschlue**
PMEG45A10EPD

https://github.com/KiCad/kicad-footprints/pull/1881

https://assets.nexperia.com/documents/data-sheet/PMEG45A10EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG45T15EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG45U10EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG030V030EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG030V050EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG040V030EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG040V050EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045T050EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045T100EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045T150EIPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045T150EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045V050EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045V100EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG045V150EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG050T150EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG050V030EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG050V150EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG060V030EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG060V050EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG060V100EPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG100V060ELPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG100V080ELPD.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG100V100ELPD.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue can you rebase your branches so it will be possible to review this PR ? Thanks, Joel

**Comment by chschlue** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks, no comment to do on this PR, just need to wait the footprint before merging. Joel

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Merging the symbol now

**Pull request merged**
