### PR TITLE
Add ADA4530-1

### PR DESCRIPTION
**Pull request by stephf0716**
Datasheet: http://www.analog.com/media/en/technical-documentation/data-sheets/ADA4530-1.pdf
Screenshot: 
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for adding this symbol!
- Page 11 says pin 3 can be connected to V- or left floating, so please make that pin visible and usable.
- You have selected the wrong footprint for this part.

Since pins 2 and 7 need to be separate pins, and using our standard opamp symbol, how about this:
image

```
# ADA4530-1
#
DEF ADA4530-1 U 0 20 Y Y 1 F N
F0 "U" 150 250 50 H V L CNN
F1 "ADA4530-1" 150 150 50 H V L CNN
F2 "Package_SO:SOIC-8-3.9x4.9mm_P1.27mm" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 SOIC*3.9x4.9mm*P1.27mm*
$ENDFPLIST
DRAW
P 5 0 1 10 -200 200 200 0 -200 -200 -200 200 -200 200 f
X + 1 -300 100 100 R 50 50 1 1 I
X ~ 2 0 300 200 D 50 50 1 1 P
X IC 3 0 -300 200 U 50 50 1 1 W
X V- 4 -100 -300 150 U 50 50 1 1 W
X V+ 5 -100 300 150 D 50 50 1 1 W
X ~ 6 300 0 100 L 50 50 1 1 O
X ~ 7 100 300 250 D 50 50 1 1 P
X - 8 -300 -100 100 R 50 50 1 1 I
ENDDRAW
ENDDEF
```

**Comment by evanshultz** [comment]
@stephf0716 
Will you be coming back to this PR soon?

**Comment by evanshultz** [comment]
@stephf0716 
I'd like to make some updates to this library before v5 (coming within the next week). Are you able to push to do more work on this PR within the next 24 hours, so I have time to work after you? Or do you mind if I incorporate my symbol above into my PR and close this PR? Please let me know, and either way thanks for contributing to KiCad!

**Comment by stephf0716** [comment]
@evanshultz
I can push to work on this. Looking forward to V5, thank you very much for the work!

**Comment by evanshultz** [comment]
Thanks! I'll try to review and merge as soon as I see a commit! :)

**Comment by stephf0716** [comment]
@evanshultz I think it should be okay to merge following previous commit to make pin 3 visible. Let me know if that isn't the case. I didn't update to the standard op amp symbol because that doesn't convey the buffered guard pins well.

**Comment by evanshultz** [comment]
Alright then. Thank you!

**Pull request merged**
