### PR TITLE
dsPIC33EP256MU810 Addition

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Addition of the dsPIC33EP256MU810 Microchip 16 bit Micro-Controller

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/70616g.pdf
---

Screenshot from 2020-04-27 20-19-37

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
Leaving that for the minute and pick it up in the morning fixing the errors then.

**Comment by myfreescalewebpage** [comment]
Hi @johnfwhitmore , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the symbol should be "DSPIC33EP256MU810xPT"
- [ ] Pin offset: 20mil (see travis error)
- [ ] Main function goes near to the border outline of the symbol, so for example pin 25 name should be "RB0/AN0/PGED3"
- [ ] VSS pin stacking error. The rule is first pin Power Input visible, the other VSS pin are invisible and Passive

Cheers,
Joel

**Comment by johnfwhitmore** [comment]
Sorry! Added this for a project that I got distracted from. I new that I had to tidy it up but completely forget to get back to it. Thank you for the reminder and your comments. Working it now...  Think I've cleared all errors. Might add a few other PIC's I'm using, just to get better at this.
Thanks again

**Comment by myfreescalewebpage** [comment]
@johnfwhitmore thanks for the update!
You have currently a strange result, the pin are away of the rectangle !!
Please check, then it will be ready for merging.
Joel
PS : at the moment the repo is locked, we will accept new contribution when KiCad v6 will be released

**Comment by johnfwhitmore** [comment]
Sorry I don't know how I missed the pins on the left floating away from the border. Checking it in now and looking over again.

On the locked repo, yes I put a symbol for the pic24fj256gb106 but when I want to do a PR I saw the warning about teh release of version 6. I'll hold off on that PR.

**Comment by myfreescalewebpage** [comment]
Thanks.
My last comment (sorry) : the name of the symbol should be "DSPIC33EP256MU810-xPT"
Joel

**Comment by myfreescalewebpage** [comment]
Thanks!!! Merging now

**Comment by johnfwhitmore** [comment]
Thank you for merging. See you when things are unlocked.

**Pull request merged**
