### PR TITLE
 AD9984A

### PR DESCRIPTION
**Pull request by ByReaL**
AD9984A

The AD9984A is a complete 10-bit, 170 MSPS, monolithic analog interface optimized for capturing YPbPr video and RGB graphics signals. Its 170 MSPS encode rate capability and full power analog bandwidth of 300 MHz support all HDTV video modes up to 1080p, as well as graphics resolutions up to UXGA (1600 × 1200 at 60 Hz).

*Replace this line with your commit message! Please provide a description of your pull request*

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for contributing to KiCad! It's because of a willing community like you that the library can grow and improve.

You will find a list of rules and guidelines for the KiCad library at http://kicad-pcb.org/libraries/klc/. Please see that webpage for more information about the review items below.

- Please sign the CLA above (you may need to adjust your email address).
- The info in the GitHub case above asks for screenshot, datasheet link, etc. Please do this to make reviewing faster.
- You will also see the Travis CI check has found many issues. Please address those.

Let us know if you have any questions and we'll help you get this symbol ready to merge. Thanks!

**Comment by poeschlr** [comment]
@ByReaL we are not able to use your contribution at all without you signing the licesense agreement. This is the agreement for us publishing your contribution under the kicad library license. (Meaning without your agreement we will need to close this.)

**Comment by evanshultz** [comment]
@ByReaL 
Please let us know if you're still interested in finishing this PR and also you must sign the CLA.

**Comment by myfreescalewebpage** [comment]
No response from original author, indicating this PR is Abandoned.

**Comment by chschlue** [comment]
Made obsolete by https://github.com/KiCad/kicad-symbols/pull/2134.
Closing.

**Pull request closed without merging**
