### PR TITLE
hmc431: NC pins should be tied to ground

### PR DESCRIPTION
**Pull request by matthuszagh**
Gerber files [here](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-hmc431lp4.html) show no-connect pins tied to center exposed pad and surrounding ground plane.

hmc431

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
The (spartan) datasheet doesn't mention anything of the sort and the (Hittite) eval PCB drawing also appears to show nothing but a guard ring, yet the newer eval board gerber seems plausible.

I would suggesting creating an NC pin stack (seperate from pins 15/25) to leave it to the user.

**Comment by matthuszagh** [comment]
That seems sensible to me. I've also added some vertical space so the pin names have more room with the new NC pin. Let me know your thoughts. Here's the new symbol

hmc431

**Comment by evanshultz** [comment]
Changing the pin locations isn't allowable during the KiCad v5 release. If they do, the symbol will change in schematics already designed and we won't break schematics since there is a way to add these NC pins without doing so. Please revert or undo those changes so the pins don't move. Thank you.

**Comment by matthuszagh** [comment]
Done.

hmc431

**Comment by chschlue** [comment]
Thanks.
Please change NC pin types to passive to avoid ERC errors.

**Comment by matthuszagh** [comment]
Done as well.

**Pull request merged**
