### PR TITLE
Symbol for PAM2306

### PR DESCRIPTION
**Pull request by jneiva08**
added symbol for PAM2306

datasheet: https://www.diodes.com/assets/Datasheets/PAM2306.pdf

The symbol is the following:

symbol

The PR for the footprint is: [#643](https://github.com/KiCad/kicad-footprints/pull/643)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Is this sold in all combinations of the output voltage, then there are a massive amount of aliases?
If you make a quick search on mouser.com your aliases shows up, 
but if you do the same search on digikey.com  you will also find 
PAM2306AYPBB
PAM2306AYPBK
PAM2306AYPAE

I guess there are more, but you could add these aliases at least.

**Comment by Misca1234** [comment]
@SchrodingersGat 
Sorry, the "request for a review" was a miss click from my side, you can ignore it

**Comment by jneiva08** [comment]
Added two missing alias

**Comment by poeschlr** [comment]
@Misca1234 looks like the agreement is already signed. I think the cla stuff sometimes does not properly update. Only way to get it working again is closing and reopening the pull request.

**Comment by Misca1234** [comment]
ok

**Comment by jneiva08** [comment]
@Misca1234 is something missing?
At some point the cla continuated gives error even always clicked to accepted

**Comment by Misca1234** [comment]
Naaa, I did a sweep over contributions that have not been merged and I saw this, 
btw, because the component only have one matching foot print, have you been thinking of adding it as dedicated foot print?

**Comment by jneiva08** [comment]
@Misca1234 
The was already added as dedicated footprint but it was not near of footprint. have already fixed.

**Comment by poeschlr** [comment]
Looks good to me, thanks

**Comment by jneiva08** [comment]
thanks for your time

**Pull request merged**
