### PR TITLE
Add W25Q32JVSS.

### PR DESCRIPTION
**Pull request by matthuszagh**
http://www.winbond.com/resource-files/w25q32jv%20revg%2003272018%20plus.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @matthuszagh , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint package in the description is not correct, should be "SOIC-8"
- [ ] I do not agree with the footprint, should be `Package_SO:SOIC-8_5.23x5.23mm_P1.27mm`, it does not exist and should be submitted
- [ ] Footprint filter will be `SOIC*5.23x5.23mm*P1.27mm*`

Else ok, copied from the other package version so it's good.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@matthuszagh any news here ? Thanks for the update, Joel

**Comment by matthuszagh** [comment]
Updated, will post the footprint pr when that's done.

**Comment by myfreescalewebpage** [comment]
Thanks, yes just need the footprint, then able to merge.

**Comment by matthuszagh** [comment]
footprint pr: https://github.com/KiCad/kicad-footprints/pull/1486

**Comment by myfreescalewebpage** [comment]
Merging following integration of the footprint.

**Pull request merged**
