### PR TITLE
Mechanical: Rename mounting holes to be consistent and update FPFilters

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
*Replace this line with your commit message! Please provide a description of your pull request*

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- To match the footprints, the suffix would be `_Pad` and not all uppercase.
- Could you also remove the other footprint filter since it won't work with the footprints at https://github.com/KiCad/kicad-footprints/tree/master/MountingHole.pretty?

I suppose the non-pad symbol is for NPTHs for PCB mounting. Kinda weird since this symbol does not appear in a netlist or BOM and there is a symbol in KiCad, but OK...

@poeschlr 
Do you want to retain these ref des prefix of `MK` for mounting holes? Seems odd. `MP` or `MT` or `W` seem better and more common to me.

**Comment by antoniovazquezblanco** [comment]
@poeschlr what should we do with the reference designator prefix?

**Comment by poeschlr** [comment]
Is there an official standard designator prefix for such parts? (I do not really see where MK comes from.)

My reasoning is that it is best to change it to something defined in an official standard than to change it to something that we define now just to change it to the correct thing in a few months (or even years)

**Comment by antoniovazquezblanco** [comment]
IEEE 315-1975:
- MK: hydrophone, microphone, telephone transmitter
- MP*: brake, clutch, mechanical interlock, mechanical part, miscellaneous mechanical part (bearing, coupling, gear, shaft)
- MT: accelerometer, measuring transducer, mode transducer, motional pickup transducer, primary detector
- W: bus bar, cable, cable assembly (with connectors), coaxial cable, conductor, distribution line, distribution path, Goubau line, strip-type transmission line, transmission line, transmission path, waveguide, wire

**Comment by antoniovazquezblanco** [comment]
From https://blogs.mentor.com/tom-hausherr/blog/tag/reference-designator/, the following image summarizes IPC-2612.

imagen

I think MH would be the way to go but I have no way of accesing IPC-2612.

**Comment by evanshultz** [comment]
Some more food for thought:
- http://www.pcblibraries.com/downloads/temp/Reference_Designators_8825188.pdf
- https://www.ee.iitb.ac.in/~spilab/Tips/ansii_graphic_symbols_for_electrical_and_electronics_daigrams_1993.pdf (probably the source of the copy above that lists MK but not for mounting holes)

I also support `MH` prefix for mounting holes. Seems the most obvious and possibly in alignment with some standard.

Also, the Pad symbol could have a footprint filter of `MountingHole*Pad*` so it only catches the ones with copper. The non-Pad will catch all mounting holes but that's the case now anyway and the user may want copper even without a net connection (clearance, screw hole land, etc.) so I'm OK with that.

**Comment by evanshultz** [comment]
One last thing: you can put a tilde in the datasheet field to avoid any check script errors. We've done that elsewhere and I don't know of any objections.

**Comment by antoniovazquezblanco** [comment]
> http://www.pcblibraries.com/downloads/temp/Reference_Designators_8825188.pdf

404 error

> One last thing: you can put a tilde in the datasheet field to avoid any check script errors. We've done that elsewhere and I don't know of any objections.

Will do with the other changes. Thanks

**Comment by antoniovazquezblanco** [comment]
Done. Any other request for changes?

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 @Ratfink 
I'm good to merge. Any other librarians have input? That was the only discussion raised by anyone but me above, so I'll merge with within 48 hours if there's no more comments.

**Comment by poeschlr** [comment]
As far as i can see (from looking at the files within githubs web interface) this is ok for me.  If you opened the files in kicad then this is ok to merge.

**Comment by antoniovazquezblanco** [comment]
@evanshultz is this a go?

Sorry for the ping and thank you very much!

**Comment by antoniovazquezblanco** [comment]
What do you wan't me to do? Rename to `_Pad`?

**Comment by evanshultz** [comment]
That would be great, if you don't mind. http://kicad-pcb.org/libraries/klc/G1.6/ indicates non-acronyms in symbol names should not be capital. If you don't want to, I can merge as-is and make another PR to fix that. Just asking since you've already found a similar issue and chased it down.

**Comment by antoniovazquezblanco** [comment]
@evanshultz Done!

**Comment by evanshultz** [comment]
That looks good.

@antoniovazquezblanco @poeschlr 
I just noticed the Housing has a ref des of MK. Does that be H or MP?

**Comment by antoniovazquezblanco** [comment]
I have no idea on what refdes a housing should have. Will wait for instructions.

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
v5 is scheduled for tagging/release on 9 Jul. I'll merge this as-is if we don't get input before then. Feel free to ping me if you would like.

Thanks again!

**Comment by evanshultz** [comment]
Nope. I'll merge as is then.

Thank you again!!

**Comment by antoniovazquezblanco** [comment]
Thank you for your work ;)

**Pull request merged**
