### PR TITLE
added ECS-2520MV-xxx-xx

### PR DESCRIPTION
**Pull request by Shackmeister**
OBS: I have no idea what I'm doing
Datasheet: https://www.ecsxtal.com/store/pdf/ECS-2520MV.pdf
footprint PR: https://github.com/KiCad/kicad-footprints/pull/1035

ecs_symbol

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
now only the footprint is missing

**Comment by cpresser** [comment]
There is already a similar component in the libs "Oscillator:ASE-xxxMHz"
Instead of drawing a new symbol, you could just add an alias.

**Comment by myfreescalewebpage** [comment]
Hi @Shackmeister , thanks for contributing,

A few comments I have during my review:

- [ ] It seems the datasheet link is wrong. Should be `https://www.ecsxtal.com/store/pdf/ECS-2520MV.pdf`
- [ ] We usually don't put number of pads in the footprint filter, I suggest `Oscillator*SMD*ECS*2520MV*2.5x2.0mm*`
- [ ] You can use capital letters for VDD
- [ ] You can change package in the description by removing unused spaces : ` 2.5x2.0mm SMD`, that's more consistent with footprints

Else seems ok.

@cpresser yes, but for this kind of symbol, it's good to have atomic part to avoid errors with the footprint.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@Shackmeister ping! Are you still alive on this subject ?

**Comment by evanshultz** [comment]
@Shackmeister Ping!

**Comment by Shackmeister** [comment]
@myfreescalewebpage 
Hi Joel 
Sorry for the delay and thanks for the review
I have pushed the fixes

**Comment by myfreescalewebpage** [comment]
Hi @Shackmeister no problem, thanks for the update. No more comment, merging!

**Pull request merged**
