### PR TITLE
Adding MAX3218

### PR DESCRIPTION
**Pull request by ki5libs**
Adding MAX3218 RS-232 Transceiver
[Datasheet](https://datasheets.maximintegrated.com/en/ds/MAX3218.pdf)
max3218

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @ki5libs looks good, only a small suggestion for the description:

```Dual RS-232 Transceiver, 1.8V to 4.25V, AutoShutdown, DIP/SSOP```

**Comment by evanshultz** [comment]
Here are a few more:
- Put the pin count at the end of the package types in the description above (`DIP-20/SSOP-20`).
- Pin length should be 100mil.
- Pin name offset will be 20mil.
- The words "LOGIC" and "R232" are unnecessary.
- The symbol is overly large. It can shrink both vertically and horizontally without affecting usability.
- Move V+ and V- closer to LX (move INVALID down).

**Comment by ki5libs** [comment]
@SchrodingersGat @evanshultz look now, please. 
I previously tried to save symbol compatibility with MAX232, but if you think that it's too large let's do it smaller.
max3218

**Comment by evanshultz** [comment]
Unfortunately this library is full of old symbols that aren't a good reference. This symbol, once merged, should be the reference for MAX3218!

Only a few thoughts left from me:
1. Spread apart the C pins so a cap can fit there.
2. It would be nice if there wasn't so much dead space at the bottom because of the GND pin collisions. I wonder if pins 2-4 could go down there and make that space usable? Up to you if you want to investigate.
3. V+ and V- are a bit tight since each need a cap. V+ shouldn't go closer to LX because of the diode. However, I'm fine with this as-is if you are.

**Comment by ki5libs** [comment]
@evanshultz I'm completely agree. Please look at the result.
max3218

**Comment by SchrodingersGat** [comment]
@ki5libs this looks great, we should match the other symbols to this one :) Thanks for the contribution

**Pull request merged**
