### PR TITLE
added ATSAME51J**A-AU

### PR DESCRIPTION
**Pull request by daviid5**
Next try with a seperate branch :D
@myfreescalewebpage 

image

http://ww1.microchip.com/downloads/en/DeviceDoc/60001507C.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Re-push of https://github.com/KiCad/kicad-symbols/pull/1607

**Comment by daviid5** [comment]
@myfreescalewebpage is there any further action needed from myself?

**Comment by myfreescalewebpage** [comment]
@daviid5 yes several, comments below:

- [ ] I disagree with the name of the parts, we never include temperature specific information, the parts should be `ATSAME51J18A-A`, `ATSAME51J19A-A` and `ATSAME51J20A-A`
- [ ] I disagree with the package, this should be `TQFP-64_10x10mm_P0.5mm`, not LQFP-64, description to be updated (please not the missing "-" in the package name in the description), footprint and footprint filter to be fixed.
- [ ] Pin Name Position Offset should be 20mil (see travis error)
- [ ] Positive power supply pins should not be stacked
- [ ] Pin length should be 100mil only (symbol < 100pins)
- [ ] Name of pin 21 should be `VDDIOB`
- [ ] Name of pin 52 should be `~RESET`
- [ ] RESET should be moved to the bottom left corner of the device for consistency with other symbols
- [ ] VDDCORE is Power Output and should be moved on the top of the symbol
- [ ] VSW is Power Input and should be moved on the top of the symbol
- [ ] The symbol is too large, too height, plenty of blank space. You can have a look to similar devices already in the lib to get yours consistent, for example ATSAME53J18A-M

Cheers,
Joel

**Comment by daviid5** [comment]
@myfreescalewebpage 
Well agree with most of your comments.
But regarding stacking of powerpins, there are discrepancy compared to other parts.
"ATSAME70J21A-AN" for example has stacked power pins
What is the "right" way?

**Comment by myfreescalewebpage** [comment]
@davidsrsb here are remaining comments:
- [ ] The package in the description are not correct, should `TQFP-64" at the end
- [ ] The footprint filter should be `TQFP*10x10mm*P0.5mm*`

Then this is ready to be merged.

> But regarding stacking of powerpins, there are discrepancy compared to other parts.
"ATSAME70J21A-AN" for example has stacked power pins
What is the "right" way?

I know, lots of symbols do not follow the last KLC rules. The rule is, "stack power pins only if the datasheet explicitly indicate a single capacitor is required". Else, do not stack.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@daviid5 descriptions are not fixed!

**Comment by daviid5** [comment]
@myfreescalewebpage I've forgotten to commit the dcm file ...

**Comment by myfreescalewebpage** [comment]
No worries, thanks :) No more comment, merging.

**Pull request merged**
