### PR TITLE
add RJ45 LAN transformer Würth 74920111211

### PR DESCRIPTION
**Pull request by hvraven**
This adds a RJ45 ethernet magjack from [Würth 74980111211](https://katalog.we-online.de/pbs/datasheet/74980111211.pdf). Symbol based on the Würth 7499010121A. Matching footprint in https://github.com/KiCad/kicad-footprints/pull/1888

Screenshot_20191003_193234

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
This fails travis, can you fix that first?
Then I will give it a review.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@hvraven are you still alive on this subject ? You have to modify the footprint has indicated by @cpresser . Thanks

**Comment by hvraven** [comment]
fixed the wrongly assigned footprint. Datasheet URL was also wrong, fixed this too.

**Comment by myfreescalewebpage** [comment]
@cpresser would you like to continue on this ?

**Comment by cpresser** [comment]
Done. Thanks for the reminder!

**Comment by myfreescalewebpage** [comment]
You're welcome :)

**Pull request merged**
