### PR TITLE
Added coupled inductor symbols, with different pinout.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.bourns.com/docs/Product-Datasheets/SRF1260.pdf

This is needed for footprint https://github.com/KiCad/kicad-footprints/pull/2152
Captura de pantalla de 2020-03-17 15-05-15
Captura de pantalla de 2020-03-17 15-05-37

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Regarding 'L_Core_Ferrite_Coupled_Small_13_24' violating S4.1, it has the same pin lenght as 'L_Core_Ferrite_Coupled_Small_13_24', and I think they should be the same.

**Comment by evanshultz** [comment]
See https://github.com/KiCad/kicad-symbols/pull/2376. I think the symbols are complementary, but likely whichever PR gets merged first will result in branch conflicts in the other PR.

**Comment by cnieves1** [comment]
@evanshultz: didn't find that PR before. Shall I close this PR? #2376 has one additional symbol this PR has not...

**Comment by evanshultz** [comment]
I believe the symbols are different so both PRs are useful. Just a note for the future that two different PRs were submitting similar symbols.

**Comment by evanshultz** [comment]
@cnieves1 
This looks fine to me except I'd like to name it without an underscore between the pin numbers. I can see why you grouped them this way, but I'd rather capture something in the description if this is necessary. Since users can see the symbol in the browser when selecting a part they will know the pins on each winding and other generic symbols put all the pin numbers together.

**Comment by cnieves1** [comment]
Name changed now..

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
