### PR TITLE
Partial revert of #445

### PR DESCRIPTION
**Pull request by fauxpark**
As noted in #445, the PR somehow removed the symbols added in #420 and #436.

(https://github.com/KiCad/kicad-symbols/pull/445/commits/eff2b3f7f0b9f0ae6f51f4980d54d519e5c1f8d5)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Dang. #445 started from an outdated branch and I missed it with everything else going on. Sorry about that, but thanks for catching it and fixing!

You noted this is only a partial fix, but it looks complete to me. Is there something left to do? (After answering this I'll merge.)

**Comment by fauxpark** [comment]
I meant that it was a partial revert of the PR - the only thing wrong with it was that the MOSFETs had been removed :)

**Comment by fauxpark** [comment]
Hey @evanshultz any update on this?

**Comment by evanshultz** [comment]
Nope. Just me remembering about it...

**Pull request merged**
