### PR TITLE
add diode to input side of LTV-814 to reflect AC input

### PR DESCRIPTION
**Pull request by clnhlzmn**
I added a diode to the input side of the LTV-814 because it's an AC input but the symbol had only one diode.

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing: 
https://optoelectronics.liteon.com/upload/download/DS-70-96-0013/LTV-8X4%20series%20201509.pdf
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible:
image
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.

  No change to footprint.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
  NA
- [x] Check the output of the Travis automated check scripts - fix any errors as required
  Travis OK.
- [x] Give a reason behind any intentional library convention rule violation.
  NA

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @clnhlzmn thanks for this enhancement.
Can you also update the datasheet link, it seems its is broken... Yours (https://optoelectronics.liteon.com/upload/download/DS-70-96-0013/LTV-8X4%20series%20201509.pdf) is great.
Joel

**Comment by clnhlzmn** [comment]
> 
> 
> Hello @clnhlzmn thanks for this enhancement.
> Can you also update the datasheet link, it seems its is broken... Yours (https://optoelectronics.liteon.com/upload/download/DS-70-96-0013/LTV-8X4%20series%20201509.pdf) is great.
> Joel

Sure!

**Comment by myfreescalewebpage** [comment]
Thanks for your very quick update !
Merging now.
Joel

**Comment by myfreescalewebpage** [comment]
The shorter PR of the KiCad history : opened and solved 19 minutes later !

**Comment by clnhlzmn** [comment]
> 
> 
> Thanks for your very quick update !
> Merging now.
> Joel

Thanks! This is my first accepted contribution to KiCad and I feel honored.

**Comment by myfreescalewebpage** [comment]
:) So I wish you welcome and be free to propose new symbols or enhancements !

**Pull request merged**
