### PR TITLE
Add MAX14830

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://datasheets.maximintegrated.com/en/ds/MAX14830.pdf
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1988

Screenshot:
max14830

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] I wonder if the pin should be arranged like on page 7 of the datasheet ?
- [ ] Pin 1 should be Input
- [ ] Pin 45 should be Input

Else, no comment, just need to wait the footprint before we can merge.

Cheers,
Joel

**Comment by jneiva08** [comment]
Arranged SPI pins to be like datasheet

Screenshot:
max14830

**Comment by myfreescalewebpage** [comment]
> Arranged SPI pins to be like datasheet

I was thinking to the pins on the right of the symbol (TxD, RxD etc). i trust in you this position is nice to have on a schematic. In this case, ok.

Just need to wait the footprint now.

**Comment by jneiva08** [comment]
I don't mind change again. 
I used as a base for the pins another PR (https://github.com/KiCad/kicad-symbols/pull/2316)

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@jneiva08 no more comment, merging the symbol following merge of the footprint. Thanks

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
