### PR TITLE
Add missing QFN packages for ATtiny2313A/4313

### PR DESCRIPTION
**Pull request by fauxpark**
Added ATtiny2313A/4313-MU as aliases of ATtiny2313V-10MU (4x4mm QFN-20), and ATtiny2313A/4313-MMH (3x3mm QFN-20) as a separate symbol.

sym

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/doc8246.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- The packages in the description could be named MLF-20 and VQFN-20 to differentiate them.
- The symbol `ATtiny2313V-10MU` has a footprint with an EP of 2.25mm sq, but the actual package is 2.6mm sq nominal. `ATtiny2313A-MMH` is using a 1.6mm sq EP footprint while the nominal package size is 1.55mm.

Yes, the latter EP/pad size difference is basically inconsequential but can we allow any exceptions when making footprints is so easy and it will be of benefit if the delta is larger? This makes me think an entire review of all Atmel footprints is likely to turn up at least some minor issues. I see #300, #335, #338, #340, etc. have all gone through this but there are probably stragglers.

**Comment by fauxpark** [comment]
What is the correct EP size for these then? I'm not sure how to calculate it.

I see this in the [YAML definition](https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_DFN_QFN/size_definitions/qfn-2x.yaml) for the 3x3mm QFN:

```yaml
# For backwards compatibility use 1.6mm even thought nominal would be 1.55
EP_size_x: 1.6
EP_size_y: 1.6
```

The 4x4mm footprint with the 2.25mm EP is not scripted, but there is one with a 2.5mm EP. Much closer but still too small.

**Comment by evanshultz** [comment]
I see.

Well, no reason not to add the actual size now that we've got a script and we're not concerned with backwards-compatibility on this new symbol. And for the 2.6mm one, no harm in making a correct footprint.

Would you like me to submit a PR with those two footprints using the script? Or perhaps you'd like to do this one?

**Comment by fauxpark** [comment]
Ah, the 1.6mm comes from our old friend [Atmel Appnote 8826](http://ww1.microchip.com/downloads/en/AppNotes/Atmel-8826-SEEPROM-PCB-Mounting-Guidelines-Surface-Mount-Packages-ApplicationNote.pdf). Is this what the "backwards compatibility" is referring to?

I think you might have a better idea of the appropriate values to plug into the generator, so by all means go ahead, if you have the time. Otherwise I'll have a crack at it.

**Comment by poeschlr** [comment]
@fauxpark wrote:
> What is the correct EP size for these then? I'm not sure how to calculate it.

I did not yet come around to add this to the KLC: https://github.com/KiCad/kicad-website/issues/332

By default the EP size should be equal to the nominal size of the metal pad (lead or slug) of the package.

If the manufacturer specifically states in the datasheet or appnote for this particular part that it should be sized differently then this size is to be used. (Your mentioned appnote however is not really fitting for the part in question.)

Even if there is a document sugesting a different size for the EP, care must still be taken. Especially if the suggested pad size is outside of the min/max size ranges for the package pad. (For larger suggestions it will most likely be that the pad will be a soldermask defined pad -> soldermask will have a cutout with the size inside the tolerance ranges.)

**Comment by evanshultz** [comment]
Footprints submitted at https://github.com/KiCad/kicad-footprints/pull/1005.

**Comment by evanshultz** [comment]
The footprints were merged so can you update the description and default footprint and footprint filter to match and then this is good to go. If you shrink the symbol that's fine with me, but for commonality with other packages I can understand leaving it alone.

**Comment by fauxpark** [comment]
I think I should fix the description in a separate PR because that also affects most of the QFN symbols. Currently they all just use "QFN" and their footprints are the same - it may require renaming or duplicating footprints to match what the datasheets call them.

**Comment by evanshultz** [comment]
Sure. The description can be done later. And any actual footprint renames later, if required.

**Pull request merged**
