### PR TITLE
Added TMC2130-TA to Driver_Motor

### PR DESCRIPTION
**Pull request by G-Pereira**
I added Trinamic TMC2130-TA bipolar stepper motor driver since I've created for a personal project. Hope this is useful to you!

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing: https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2130_datasheet.pdf
- [x] An example screenshot image is very helpful
tmc2130-TA
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
All Good!

### CODE REVIEW

**Comment by jneiva08** [comment]
On the description can you add the footprint name "TQFP-48"
GND_P and VS can you put one of the pins like [KLC S4.3](http://kicad-pcb.org/libraries/klc/S4.3/)

SDO_CFG0 probably should be input/output

**Comment by G-Pereira** [comment]
Hello, that is usefull but:
"Special Case: Pins of electrical type [Output, Power Output, Power Input] are special cases. Connecting these pins together causes ERC (electrical rule check) errors and must be avoided."

**Comment by poeschlr** [comment]
Regarding SDO:
If this pin would only be used for spi data out then it would best be set to tristate. However as it also has an alternative function as input (in SPI Mode 0) bidirectional is correct.

**Comment by G-Pereira** [comment]
I've changed that, thanks! Is it good?

**Comment by jneiva08** [comment]
did you update the symbol image?
The pin NC 6 and 47, should be on the edge

**Comment by G-Pereira** [comment]
I've fixed that now, thanks

**Comment by G-Pereira** [comment]
Is this good?

**Comment by G-Pereira** [comment]
@jneiva08 @poeschlr

**Comment by Misca1234** [comment]
If you want you can make the pin layout similar to the other TMC symbols, that is grouping the pin different.

Also, pins like CPO and CPI are usually made passive 
AIN_REF, 30,  is an input, it should preferable be on the left side
TST_MODE, 1,  is an input, it should preferable be on the left side

You should add a pin, GND, 49, that represent the pad on the belly, stack it ontop the GND stack

**Comment by myfreescalewebpage** [comment]
Hello @G-Pereira 

Same comment already done at https://github.com/KiCad/kicad-symbols/pull/866.

Thanks for your answer.

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Closing in favour of the new PR.

**Pull request closed without merging**
