### PR TITLE
Add SGL0622Z RF Amplifier

### PR DESCRIPTION
**Pull request by chmorgan**
image

https://www.qorvo.com/products/d/da001879
Footprint: https://github.com/KiCad/kicad-footprints/pull/2367

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @chmorgan , thanks for contributing,

A few comments I have during my review:

- [ ] Description should ends with package name ", DFN-8"
- [ ] keywords in lower case only is great
- [ ] Footprint filter should be `DFN*1EP*2x2mm*P0.5mm*`

Cheers,
Joel

**Comment by chmorgan** [comment]
Hi @myfreescalewebpage, pushed a commit to update the symbol with these changes. Thank you again for the review.

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by chmorgan** [comment]
@myfreescalewebpage thank you!

**Pull request merged**
