### PR TITLE
Added LM7171

### PR DESCRIPTION
**Pull request by Gabriel-06**
This is my first contribution, please let me know if I have done anything wrong. I have added LM7171 to the library.

Datasheet: [https://www.ti.com/lit/ds/symlink/lm7171.pdf](https://www.ti.com/lit/ds/symlink/lm7171.pdf)

Screenshot:
Screen Shot 2020-07-04 at 10 18 37 pm

Pin table:
Screen Shot 2020-07-04 at 10 22 22 pm

Footprints are present in current library (DIP-8 and SOIC-8).

Automated check gives one error: Violating S5.2. S5.2 is all correct, I have double-checked.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate (N/A)
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by Gabriel-06** [comment]
Edit - Fixed the 5.2 Violation. Forgot a *.

**Comment by myfreescalewebpage** [comment]
@Gabriel-06 no way to have it as an alias of another symbol ?

**Comment by Gabriel-06** [comment]
> @Gabriel-06 no way to have it as an alias of another symbol ?

No, it can't. I just double-checked again. None of the current single opamps have the same pins drawn and also have the same 2 footprints (DIP and SOIC).

**Comment by Gabriel-06** [comment]
Is this all good or does it still need action from me?

**Comment by myfreescalewebpage** [comment]
Thanks for the answer about the alias.
No, we have plenty of pull request to review actually, will to do yours soon. Currently still "Pending reviewer".
Joel

**Comment by Gabriel-06** [comment]
No worries, just wanted to double check it wasn't waiting on me :)

**Comment by myfreescalewebpage** [comment]
Making a review now :)

- [ ] We expect for the symbol now to have one version for each footprint. "LM7171xIM" and "LM7171xIN" for you here.
- [ ] Footprint and fp filter to be set accordingly
- [ ] Pin offset at 5 mil for triangle symbols
- [ ] NC pin to add on the symbol, invisible, not connected, on th border outline

Will do a full review after that

Joel

**Comment by Gabriel-06** [comment]
Just working on fixing these. What do you mean by having a 5mil offset for the pins? Do you mean the pin names (as in S3.6)?

**Comment by Gabriel-06** [comment]
Cool. Sorry about missing pin 1, not sure what happened there. Should be all fixed up!

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
