### PR TITLE
Mini-Circuits bandpass filter BPF-A355

### PR DESCRIPTION
**Pull request by aewallin**
Datasheet https://www.minicircuits.com/pdfs/BPF-A355+.pdf

Symbol is same as RBPF-246 (#1223) with different pin-numbering.

Footprint PR https://github.com/KiCad/kicad-footprints/pull/2196 

BPF-A355

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @aewallin thanks for this symbol.
No comment to do here, just need to wait the footprint.
Joel

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
