### PR TITLE
Add TCMT110x optocouplers

### PR DESCRIPTION
**Pull request by Schlumpf**
image
http://www.vishay.com/docs/83510/tcmt1100.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Could you use the same symbol we use for all other optocouplers (which has ~200mil pin-separation)?

This way it is easier to exchange couplers across the lib.
2018-01-29 22_01_24-symbol library editor - isolator d__kicad_kicad-symbols_isolator lib

**Comment by Schlumpf** [comment]
I could blow up the Symbol. But it would waste space. I copied the artwork from CNY17, what about shrinking the other optocouplers to save space?

**Comment by poeschlr** [comment]
The larger size allows for size compatibility with parallel passive components. (Filter or protection circuitry)

**Comment by jkriege2** [comment]
Thanks for your contribution,
JAN

**Pull request merged**
