### PR TITLE
PCF85263 / PCF85363: Create new RTC devices

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
New RTC devices PCF85263 and PCF85363 in SO-8, TSSOP-8 and TSSOP-10 packages.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing

https://www.nxp.com/docs/en/data-sheet/PCF85263A.pdf
https://www.nxp.com/docs/en/data-sheet/PCF85363A.pdf

- [X] An example screenshot image is very helpful

TSSOP-10 version:
Capture

TSSOP-8 and SO-8 versions:
Capture

- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

One warning about CLK pin, which is effectively an Output on this device.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Note: many commits due to merge in local branch on my fork.

**Comment by evanshultz** [comment]
1. '363 doesn't have an AT variant.
1. The AT symbol should use the SOIC and not SO footprint.

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks for the review, good catch for the SOIC version! Two points modified.

**Comment by evanshultz** [comment]
Thanks!

**Comment by myfreescalewebpage** [comment]
Thanks for your review !

**Pull request merged**
