### PR TITLE
Add APA102

### PR DESCRIPTION
**Pull request by cp-aquila**
Add APA102

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

grafik

* Datasheet http://www.led-color.com/upload/201604/APA102-2020%20SMD%20LED.pdf
* Footprint PR https://github.com/KiCad/kicad-footprints/pull/1389
* No default FP since this is an gerneric symbol for both the 5x5mm and 2x2mm sized component
* No intentional KLC violation

### CODE REVIEW

**Comment by DanSGiesbrecht** [comment]
Is there a reason that you deleted `WS2812B`?

**Comment by cp-aquila** [comment]
> Is there a reason that you deleted `WS2812B`?

No. I am just plain stupid sometimes. I started from WS2812B to make this symbol; and somehow failed to keep the original one.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
Hi @cp-aquila , thanks for contributing,

A few comments I have during my review:

- [ ] Footprint should be `LED_SMD:LED-APA102-2020`
- [ ] Footprint filter should be `LED*APA102*` (only one is expected)

Else, this looks good. Need to wait footprint acceptance before merging.

Cheers,
Joel

**Comment by cp-aquila** [comment]
Hi Joel,

thanks for the Feedback.
This LED is also available in a PLCC-6 package (https://cdn-shop.adafruit.com/datasheets/APA102.pdf)
Thats why I choose to make it a generic symbol and not an atomic one.

**Comment by cp-aquila** [comment]
> This LED is also available in a PLCC-6 package (https://cdn-shop.adafruit.com/datasheets/APA102.pdf)
> Thats why I choose to make it a generic symbol and not an atomic one.

Well... nevermind. The two versions have a different Pinout.
So I think the name of this symbol should also change to reflect this. I will be going with "LED-APA102-2020"

**Comment by cp-aquila** [comment]
I also added the PLCC-6 variant, while I am at it.
Datasheet: http://www.led-color.com/upload/201506/APA102%20LED.pdf

grafik

grafik

**Comment by poeschlr** [comment]
We would require two symbols even if the two symbols have the same pinout. this is because we require the footprint to be pre assigned for all symbols exept a few in special libraries (Device, Connector and to a degree the logic family libs)

**Comment by cp-aquila** [comment]
The last commit does indeed have two different symbols.

**Comment by myfreescalewebpage** [comment]
Hi @cp-aquila thanks for this enhancement,

New review following the addition of the second symbol:

APA102: 
- [ ] Name of the pins are also not the same, you should adjust to the datasheet : DI, CI, VCC, CO, DO
- [ ] Footprint filter should not contain the number of pins, `LED*RGB*PLCC*` is great

APA102-2020:
No comment to do, just need to wait footprint acceptance.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks @cp-aquila no more comment to do on this PR, merging.

**Pull request merged**
