### PR TITLE
added LTC3105

### PR DESCRIPTION
**Pull request by rs-development**
https://www.analog.com/media/en/technical-documentation/data-sheets/3105fb.pdf

image

I have created 2 Parts for 2 Footprints, please check the pinning!

### CODE REVIEW

**Comment by rs-development** [comment]
Don't really agree with MPPC as Input, it does output current. You're sure? @chschlue

**Comment by chschlue** [comment]
True, it does source 10µA.
But then, input can be connected to resistors, diodes, capacitors and power symbols.
Output connected to ground throws an ERC error.

Am I missing something here?

**Comment by rs-development** [comment]
Correct it can be connected to GND to disable MPPC function. So Output is not ok.

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
