### PR TITLE
Connector: Add a barrel jack connector symbol with reordered pins

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Connector: Add a barrel jack connector symbol with reordered pins

Barrel_Jack_Switch_Pin3Ring

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chmorgan** [comment]
Hi @piotr-wiszowaty, do you have a data sheet for a part that has this configuration to back up the reason for including it?

**Comment by piotr-wiszowaty** [comment]
Yes, an example is linked here: https://github.com/KiCad/kicad-footprints/pull/2112
Note, that only the second of the linked datasheets is correct.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
No comment to do, merging.

**Pull request merged**
