### PR TITLE
ADE7953 symbol

### PR DESCRIPTION
**Pull request by G-Pereira**
Added ADE7953 symbol but footprint is missing, hoping someone interested in doing the footprint, it's a "28-Lead  LFCSP_ WQ"
[Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADE7953.pdf)
ade7953

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi @G-Pereira,
unfortunately we cannot merge this part until a footprint is ready.
The package looks pretty similar to a QFN28 and could be generated by script.

**Comment by G-Pereira** [comment]
> Hi @G-Pereira,
> unfortunately we cannot merge this part until a footprint is ready.
> The package looks pretty similar to a QFN28 and could be generated by script.

I am currently working on that, thank you!

**Comment by G-Pereira** [comment]
Footprint pull-request submitted! :)

**Comment by G-Pereira** [comment]
> @G-Pereira can you solve the branch conflict hereto start the review ?

Done!

**Comment by myfreescalewebpage** [comment]
Thanks. Few comments:

- [ ] Name of the symbol should be "ADE7953xCP"
- [ ] Footprint and filter to be define. IMPORTANT NOTE: we cannot merge without the footprint. Moreover, please note in preparation of KiCad v6 the repo will be locked the 2020-09-01. No new footprint will be accepted during several weeks. If you wish to have the symbol merge quickly, I recommend you to submit the footprint quickly.
- [ ] Wrong package at the end of the description, should be "LFCSP-28"
- [ ] Pin 7 is missing, should be stacked with pin 8
- [ ] Pin 29 (expose pad) is missing, should be called EP and type Passive
- [ ] Please align DGND with VDD
- [ ] The position of the pin is strange. Something like schema on page 16 seems better. Or can you provide a sample schematic with this symbol ?
- [ ] Pin 26 is Bidirectional (for SDA)

Joel

**Comment by G-Pereira** [comment]
> Thanks. Few comments:
> 
>     * [ ]  Name of the symbol should be "ADE7953xCP"
> 
>     * [ ]  Footprint and filter to be define.
> 
>     * [ ]  Wrong package at the end of the description, should be "LFCSP-28"
> 
>     * [ ]  Pin 7 is missing, should be stacked with pin 8
> 
>     * [ ]  Pin 29 (expose pad) is missing, should be called EP and type Passive
> 
>     * [ ]  Please align DGND with VDD
> 
>     * [ ]  The position of the pin is strange. Something like schema on page 16 seems better. Or can you provide a sample schematic with this symbol ?
> 
>     * [ ]  Pin 26 is Bidirectional (for SDA)
> 
> 
> **IMPORTANT NOTE: we cannot merge without the footprint. Moreover, please note in preparation of KiCad v6 the repo will be locked the 2020-09-01. No new footprint will be accepted during several weeks. If you wish to have the symbol merge quickly, I recommend you to submit the footprint quickly.**
> 
> Joel

Should be all ok, exept for the footprint and filters. I appreciate your note but I have everything ready for review, including the footprint PR and a PR to add the corresponding footprint to the kicad-footprint-generator. Links are above.

**Comment by myfreescalewebpage** [comment]
I know. Do not hesitate to ping the reviewer :)

**Comment by G-Pereira** [comment]
Footprint is ready, footprint generator PR merged and footprint PR ready to be merged so I have updated this footprint and I have set the filter.

**Comment by chschlue** [comment]
FP merged.

**Comment by G-Pereira** [comment]
The symbol has the footprint and footprint filter assigned. Ready to merge this @myfreescalewebpage ?

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks for the ping. Yes ready to go.

**Pull request merged**
