### PR TITLE
Add MC100LVELT22 and MC100EPT22 LVTTL to LVPECL level translators

### PR DESCRIPTION
**Pull request by pgrudzinski**
https://www.onsemi.com/pub/Collateral/MC100EPT22-D.PDF
https://www.onsemi.com/pub/Collateral/MC100LVELT22-D.PDF
image
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by myfreescalewebpage** [comment]
Hi @pgrudzinski , thanks for contributing,

A few comments I have during my review:

For all devices:
- [ ] Missing a comma before the package name in the description, for example: `3.3 V Dual LVTTL/LVCMOS to Differential LVPECL Translator, SOIC-8`

Else no comment to do

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@pgrudzinski ping !

**Comment by pgrudzinski** [comment]
@myfreescalewebpage Corrected according to comment.

**Comment by myfreescalewebpage** [comment]
@pgrudzinski you have forgotten descriptions of MC100LVELT22D and MC100LVELT22DT
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by pgrudzinski** [comment]
@myfreescalewebpage I forgot about aliases. Should be fine now.

**Pull request merged**
