### PR TITLE
Add LT3032 and variants

### PR DESCRIPTION
**Pull request by ferdymercury**
https://www.analog.com/media/en/technical-documentation/data-sheets/3032ff.pdf

image
image

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @ferdymercury , thanks for contributing,

A few comments I have during my review:

- [ ] Regulators have a description format which is a little bit différent. I propose:
- LT3032: `150mA, Dual Low Dropout Linear Regulator, Positive/Negative Low Noise, Adjustable Output, DFN-14`
- LT3032-3.3: `150mA, Dual Low Dropout Linear Regulator, Positive/Negative Low Noise, 3.3V Output, DFN-14`
- LT3032-5: `150mA, Dual Low Dropout Linear Regulator, Positive/Negative Low Noise, 5V Output, DFN-14`
- LT3032-12: `150mA, Dual Low Dropout Linear Regulator, Positive/Negative Low Noise, 12V Output, DFN-14`
- LT3032-15: `150mA, Dual Low Dropout Linear Regulator, Positive/Negative Low Noise, 15V Output, DFN-14`
- [ ] Footprint filter should be `DFN*2EP*3x4mm*P0.5mm*` for both devices (see also my footprint comment at https://github.com/KiCad/kicad-footprints/pull/1081).
- [ ] LT3032 (adj): Pins 2 and 8 should be Input
- [ ] For both devices, pins 6 and 9 should be stacked
- [ ] For both devices, pin 15 is missing and should be stacked with pin 4
- [ ] For both devices, pin 16 is missing and should be stacked with pins 6 and 9
- [ ] Pins offset should be 20mil for both devices (see travis output)

Cheers,
Joel

**Comment by ferdymercury** [comment]
Thanks for your review. Issues fixed.

**Comment by myfreescalewebpage** [comment]
When stacking pins, one is visible, the other pin stacked on the first one must be invisible.

**Comment by ferdymercury** [comment]
corrected

**Comment by ferdymercury** [comment]
yep, fixed

**Comment by myfreescalewebpage** [comment]
Thanks. Good catch for missing fp.
No more comment, need to wait the footprint PR to be accepted now.

**Comment by myfreescalewebpage** [comment]
@ferdymercury following messages at https://github.com/KiCad/kicad-footprints/pull/1081 can you update this PR:
- [ ] Change footprint : `Package_DFN_QFN:Linear_DE14MA`
- [ ] Change footprint filter : `Linear*DE14MA*`
- [ ] Remove pin 15 and 16 (the new version has a specific pin format, https://github.com/KiCad/kicad-footprints/pull/981). We will need to wait the acceptance of this PR to merge the symbol.
Cheers,
Joel

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-footprints/pull/981 is just updating the footprint, but it already exists so no need to wait to merge this symbol once it's ready. :)

**Comment by myfreescalewebpage** [comment]
@evanshultz it is required because the PR https://github.com/KiCad/kicad-footprints/pull/981 remove pins 15 and 16. Do I understand this impact has not been evaluated on the symbols ?

**Comment by evanshultz** [comment]
I believe I checked this before but I again used my little script, which otherwise seems to work well, to search for `DE14MA` in the default footprint of any symbol. And since it's so specialized it must be a default footprint. I get no hits so, no, I believe this footprint is not currently being used by any symbols.

**Comment by ferdymercury** [comment]
I see.

Should I remove then pins 15 and 16 from the symbol?

Should I remove https://github.com/pointhi/kicad-footprint-generator/pull/235 from the script generator repo?

Thanks

**Comment by evanshultz** [comment]
Yes, you can make your symbol work with the simplified footprint I proposed at https://github.com/KiCad/kicad-footprints/pull/981. @myfreescalewebpage , if I split off just that footprint would you merge it?

Yes. The footprint generated by that script is not correct. This one will likely always be hand-created.

**Comment by myfreescalewebpage** [comment]
@evanshultz yes I can make a review if you split it like already done on a previous device.

**Comment by ferdymercury** [comment]
Fixed, thanks

**Comment by evanshultz** [comment]
Footprint submitted at https://github.com/KiCad/kicad-footprints/pull/1442.

**Comment by myfreescalewebpage** [comment]
Merging following integration of the footprint and final review of the symbol. Thanks for the job here !

**Pull request merged**
