### PR TITLE
Battery_Management: Add BQ24133

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Screenshot from 2019-04-23 12-40-07

http://www.ti.com/lit/ds/symlink/bq24133.pdf

https://github.com/KiCad/kicad-footprints/pull/1460

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @antoniovazquezblanco , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device should be "BQ24133RGY" to avoid conflict if the manufacturer adds package options
- [ ] Description should ends with package name `, Texas PVQFN-N24`
- [ ] Footprint filter should not contains the pin count, I suggest `Texas*R*PVQFN*N*EP2.05x3.1mm*`
- [ ] VREF should be Power Output
- [ ] STAT should be Open Collector
- [ ] TTC should be Passive
- [ ] CELL should be Passive

Cheers,
Joel

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Just notice I made a mistake about the footprint filter, it should not contains the EP size too. Corrected my previous comment. @antoniovazquezblanco can you fix it please ?

**Comment by antoniovazquezblanco** [comment]
👌

**Comment by myfreescalewebpage** [comment]
Thanks, waiting for the footprint before merging.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Comment by antoniovazquezblanco** [comment]
NOTE TO SELF: This will need footprint fields updates after those are merged.

**Comment by evanshultz** [comment]
Just merged footprint and kicked off CI here. All green.

**Comment by myfreescalewebpage** [comment]
@antoniovazquezblanco 
I would suggest:
- [ ] Package name at the end of the description "Texas R-PVQFN-N24" (not seen this before)
- [ ] Footprint filter should not contain the number of pins: `Texas*RGY*R*PVQFN*N*`
Joel

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by myfreescalewebpage** [comment]
Thanks @antoniovazquezblanco , merging.

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
