### PR TITLE
add HMC394 counter/prescaler in QFN-24

### PR DESCRIPTION
**Pull request by aewallin**
https://www.analog.com/media/en/technical-documentation/data-sheets/hmc394.pdf

- VCC pins stacked
- GND pins stacked
- EP pin stacked on GND-pins (datasheet says EP is GND)
- EP is 2.8mm square, so footprint with 2.7mm square EP-pad should work (?)

hmc394lp4

example circuit from datasheet: (pin17 should be not-OUT)
hmc_spec

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
Travis says: Pinstack @ (0,600) have different names

- Should the EP-pin just be named GND? 
- OR should it be EP, visible, and separate from the GND-pin stack?

**Comment by poeschlr** [comment]
If EP is always GND then rename it as GND.
Otherwise make it visible and put it next to the GND pin stack.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] There is an extra space in the description after "2.2 GHz" and before the comma, to be removed
- [ ] Footprint EP need to match, please can you create "QFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm" and "QFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_ThermalVias" (copy/paste existing 2.7x2.7mm + enlarge EP) and submit a PR ?
- [ ] Footprint filter should be `QFN*1EP*4x4mm*P0.5mm*`

Cheers,
Joel

**Comment by aewallin** [comment]
I'm not sure about the footprint.
The datasheet drawing shows a pad-size of [2.65, 2.95] square.
https://www.analog.com/media/en/technical-documentation/data-sheets/hmc394.pdf
The package name ends in LP4E. This guide has suggested land pattern:
https://www.analog.com/media/en/quality/hmc-qtr/QTR_05006.pdf

e.g. for LP4E it has an EP-size pad size of 0.110" with a 0.098" soldermask-opening - including a chamfer for pin1.

I am not familiar with the QFN scripts - what is the workflow for creating a new scripted footprint?
lp4

**Comment by myfreescalewebpage** [comment]
Well, you make me doubt... I was understanding [2.65-2.95] is averaged to 2.8mm with 0.15mm margins but this is not sure...

@poeschlr @evanshultz maybe you are more familiar with this kind of footprint ? What is your opinion ?

Thanks,
Joel

**Comment by myfreescalewebpage** [comment]
@aewallin any news here ? Maybe you had a look to script of QFN package at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON ?
Thanks for the update
Joel

**Comment by aewallin** [comment]
- while I've been passive @matthuszagh has created the footprint needed here for another HMC part - great! https://github.com/KiCad/kicad-footprints/pull/1283
- merge-conflict resolved by rebasing on current master.

**Comment by myfreescalewebpage** [comment]
@aewallin thanks for this !! I just made a complete review because it's a long time I have not work on this. Several additional comments:
- [ ] VCC pins should not be stacked
- [ ] All pins should be 100mil (symbol<100pins)
- [ ] I think A0 to A4 should be moved to the left of the symbol

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
