### PR TITLE
Add shielded SIM card

### PR DESCRIPTION
**Pull request by Schlumpf**
it's a copy of the original generic SIM card symbol, but with SH pin

grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] ~Provide a URL to a datasheet for the symbol(s) you are contributing~ **generic symbol**
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] ~If there are matching footprint PRs, provide link(s) as appropriate~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.
  - **generic symbol**
  - **variant of existing symbol**

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Schlumpf , thanks for contributing,

A single comment I have during my review:

- [ ] Can you put SH on the left as done on "JAE_SIM_Card_SF72S006" symbol ?

Cheers,
Joel

**Comment by Schlumpf** [comment]
Done :)

**Comment by myfreescalewebpage** [comment]
Thanks. I have forgotten some Travis error on the last review:

- [ ] Pin offset to be fixed
- [ ] Footprint is not correct, should be empty for this device, like "SIM_Card" symbol.

The other warning are normal.

Joel

**Comment by Schlumpf** [comment]
I changed the pin offset of both variants (shielded and unshielded) to 20mil.
But I don't get your second point. The footprint field is empty. There is set a footprint filter, the same as unshielded variant.

**Comment by myfreescalewebpage** [comment]
Thanks for the fix. Sorry the second point is not correct, probably I was checking another symbol at the same time...
No more comment, merging.
Joel

**Pull request merged**
