### PR TITLE
74xx: Add 74LCX07

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Screenshots:
74lcx07_symbol
74lcx07_descr
74lcx07_fpfilter

### CODE REVIEW

**Comment by Ratfink** [comment]
Thank you for making this contribution to the KiCad library!  I see two little issues that I'd like to get fixed before I merge this.

* Please change the keyword "inverter" to "buffer".
* Please change the outputs to electrical type "Open collector".

**Comment by piotr-wiszowaty** [comment]
Done.

**Comment by Ratfink** [comment]
Thanks!  It looks like you forgot to change the electrical type of the outputs on units B–F, so once that's fixed I think this will be ready to merge.

**Comment by piotr-wiszowaty** [comment]
Output types corrected.

**Comment by Ratfink** [comment]
Thanks for the contribution!

**Pull request merged**
