### PR TITLE
Ma8601

### PR DESCRIPTION
**Pull request by dudelectric**
Push of
Prolific MA8601 
http://www.prolific.com.tw/US/ShowProduct.aspx?p_id=271&pcid=164
https://datasheetspdf.com/pdf-file/1312067/Prolific/MA8601/1

sshotma8601

### CODE REVIEW

**Comment by dudelectric** [comment]
Hi @myfreescalewebpage thanks for your time

1. Have you got a better datasheet link from the website of the manufacturer?
The manufacture website doesn't provide full datasheet information about the chip, the full datasheet can be downloaded from this link [https://datasheetspdf.com/pdf-file/1312067/Prolific/MA8601/1](url)

2. The footprint schema in the datasheet can't be clearly understood. Where have you found the dimension of the package?
From the manufacturer website, it says "Package Type : SSOP28" 
image
also from the datasheet
image

3. Name of pin 25 should be ~PWRJ
Just Updated

4. You can probably move down the pins 18 to 26 on the left, this will leave more space between VBUS_IN and VDD5.
Just updated.

Cheers
Sigit

**Comment by aris-kimi** [comment]
>     * [ ]  Have you got a better datasheet link from the website of the manufacturer ?
@myfreescalewebpage , i also searched for this, but no luck. Not even from distributor.

**Comment by myfreescalewebpage** [comment]
Thanks for the update. About the package, SOP-28 is great for me, but the dimensions are not sure. You selected 3.9x9.9mm. Are you able to verify it ? Maybe if you can measure on the real chip if you have one?

**Comment by chschlue** [comment]
The datasheet is very low quality and hard to read, but MO-137 variant AF is legible.
That's a 3.9x9.9mm SSOP, so the footprint choice should be correct.

**Comment by dudelectric** [comment]
@myfreescalewebpage  this IC is pin to pin compatible with MOAI MA8601.
[MA8601_V1.01_Datasheet(2).pdf](https://github.com/KiCad/kicad-symbols/files/5116325/MA8601_V1.01_Datasheet.2.pdf)

I found the datasheet from this blog:
https://pluspda.ru/blog/aliexpress/30683.html
https://www.dropbox.com/s/gmmnomkmdpt1ied/MA8601_V1.01_Datasheet.pdf?dl=0

this also has better Package description (page 11)
image

These are pic of real chip i have
image
image

**Comment by myfreescalewebpage** [comment]
Thanks for the confirmations! Merging now.

**Pull request merged**
