### PR TITLE
Added Wuerth_750315371

### PR DESCRIPTION
**Pull request by aris-kimi**
Datasheet: https://www.we-online.com/catalog/datasheet/750315371.pdf

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2386

100% custom design, arcs, lines and body.

Edit:
wetrsm

Travis:
```
Violating S3.3

    Symbol outline and fill requirements

    Component outline is thickness 1mil, recommended is 10mil

    Component background is filled with FOREGROUND color, recommended is filling with BACKGROUND color

  Violating S5.1

    For components with a single default footprint, footprint field is filled with valid footprint

    filename

    Specified footprint does not exist

     - Footprint file Transformer_SMD:Transformer_Wuerth_750315371 was not found
```
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@aris-kimi thanks, no comment to do. Waiting the footprint. Joel

**Comment by chschlue** [comment]
FP merged

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
