### PR TITLE
NLSV2T244

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Added three footprint variants of the same IC
- Dual non-inverting level translator
- Datasheet: http://www.onsemi.com/pub/Collateral/NLSV2T244-D.PDF
- One variant requires the footprint here - https://github.com/KiCad/kicad-footprints/pull/1502
- Symbol copied from existing logic level translators
- Only KLC issue is that the footprint isn't merged yet.

image

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Remove `R2G` from the symbol names since that's non-functional.
1. You've got pins 4 and 5 swapped.

**Comment by SchrodingersGat** [comment]
Good catch on the pins. Changes made.

**Comment by evanshultz** [comment]
Just update this to use the OnSemi footprint name, since it was changed.

**Comment by SchrodingersGat** [comment]
Done!

**Comment by evanshultz** [comment]
The footprint looks good. Please update the filter and we're ready to merge.

**Comment by SchrodingersGat** [comment]
Oops, sorry for missing that one

**Comment by evanshultz** [comment]
I think we haven't been doing leading asterisks. What about smacking `OnSemi` up front?

**Comment by SchrodingersGat** [comment]
Ok, done

**Pull request merged**
