### PR TITLE
Add TPS2419

### PR DESCRIPTION
**Pull request by jneiva08**
Add TPS2419 SOIC and TSOP

Datasheet: http://www.ti.com/lit/ds/symlink/tps2419.pdf

Screenshot:
TPS2419

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Should RSET be Passive type?
1. RSVD can stack on GND. The datasheet is clear that it must be grounded.
1. Can the symbol shrink, especially pulling in the right side? Being centered isn't so important.
1. How does the symbol look connected to a FET symbol?
1. Change the ? in the footprint filters to a *.

**Comment by jneiva08** [comment]
@evanshultz , have made major of modifications. still missing point 3.

> 4. How does the symbol look connected to a FET symbol?

tps2419

Probably can move BYP to be near of A (anode) pin. that way can shrunk in hight

Now Travis is giving error because of RSVD is stacked with GND. Change the name of RSVD to GND?

**Comment by evanshultz** [comment]
Or move RSET to the right side? I think we can leave non-power pins on the top for this symbol because it looks and works better, and I like your version better, but since I wanted to know myself here's another option with only GATE on the top just as an experiment:
image

Yes, stacked pins must have the same name.

And one thing I missed before: Please change the name of pin 5 to be all capital letters.

**Comment by jneiva08** [comment]
Changed the symbol to be more compact

tps2419

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
