### PR TITLE
add OPA569 high-current opamp in SO-20 PowerPAD

### PR DESCRIPTION
**Pull request by aewallin**
http://www.ti.com/lit/ds/symlink/opa569.pdf

OPA569

footprint: https://github.com/KiCad/kicad-footprints/pull/1547

KLC issues
- pin length: as drawn the pins would be at same Y-coordinate, but requires >300mil pin for the longest one, and to match the triangle not all pin lengths are modulo 50 mils.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by aewallin** [comment]
updated screenshot
OPA569

**Comment by myfreescalewebpage** [comment]
@evanshultz I have assigned this to you because you have an important experience with the triangle symbols and this one is a little bit complicated.
Cheers,
Joel

**Comment by aewallin** [comment]
@evanshultz, @myfreescalewebpage  + others: footprint is now merged - so that label can be removed. thanks.

**Comment by aewallin** [comment]
Fixed footprint assignment to this PR: https://github.com/KiCad/kicad-footprints/pull/1547

remaining KLC warnings are about overlong pins (due to the large triangle...)

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

Finally the review:

- [ ] Name should be "OPA569DWP"
- [ ] Fp filter: `SO*1EP*7.52x12.825mm*P1.27mm*`

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@aewallin ping

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
