### PR TITLE
adding symbols for Gas Discharge Tubes

### PR DESCRIPTION
**Pull request by thedm**
Adding symbols for 2 and 3 pin Gas Discharge  Tubes.

Symbol and some apllications can be found [here](https://www.littelfuse.com/~/media/electronics/datasheets/gas_discharge_tubes/littelfuse_gdt_catalog_datasheet.pdf.pdf)

Symbol also defined by ISO 7000 [3-Pin] (https://www.iso.org/obp/ui#iec:grs:60417:6195) [2-Pin] (https://www.iso.org/obp/ui#iec:grs:60417:6194)

screenshot2
screenshot

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@thedm nice symbols

I suggest to have the symbols looking like https://www.littelfuse.com/~/media/electronics/datasheets/gas_discharge_tubes/littelfuse_gdt_catalog_datasheet.pdf.pdf page 2, with an arrow on the third pin of the 3 pins version, and with the dot centered vertically.

on GDT_3pins:
- [ ] There is a small dot in bottom right corner, to be removed
- [ ] I suggest to fix the pin offset if possible

Joel

**Comment by thedm** [comment]
I deleted the dots and modified the Drawing so it is more smilar to the schematic in the document of littlefuse.
 
screenshot4
screenshot3

**Comment by myfreescalewebpage** [comment]
Hello @thedm 
Thanks for the fixes.
However, for GDT_2pin you changed the description and it's now wrong: should be "with 2 pins".
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
