### PR TITLE
MCU_ST_STM32G0: Add STM32G071KxT / STM32G071KxU

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
MCU_ST_STM32G0: Add STM32G071KxT / STM32G071KxU
Datasheet: https://www.st.com/resource/en/datasheet/stm32g071kb.pdf
STM32G071KxT

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Hello @piotr-wiszowaty your pull request is duplicate of https://github.com/KiCad/kicad-symbols/pull/2332 but I have no news of the author. If you wish to continue working on this you can check his PR.
The symbol should be separated because the footprint are not the same.
Joel

**Comment by piotr-wiszowaty** [comment]
Yes, pinouts of _KxUxN (in PR #2332) and _KxU (PR #2788) are different. 
I'd say the latter PR shouldn't be marked as duplicate of the former one.

**Comment by myfreescalewebpage** [comment]
So do you want to continue this PR ? If yes I remove the duplicate label and we can :)

**Comment by piotr-wiszowaty** [comment]
Yes, certainly.

**Comment by myfreescalewebpage** [comment]
Thanks.
The red line to follow is to create one symbol per package, even if the pin assignment is the same.
However, for this parts, UQFN have one pin more: the expose pad, which need to be added to the symbol.
=> Can you split with two symbols, assign the correct footprints and footprint filter for each of them please ? Then will do a full review.
Joel

**Comment by myfreescalewebpage** [comment]
Thanks @piotr-wiszowaty now a full review:

STM32G071KxT:
- [ ] Main function goes next to the border: name of pin 2 should be `OSC32_IN/PC14`, name of pin 3 should be `OSC32_OUT/PC15` and name of pin 6 should be `~RST/PF2`
- [ ] Name of pin 25 should be `PA14/BOOT0`

STM32G071KxU
- [ ] Package in the description should be "UFQFPN-32"
- [ ] Footprint should be `Package_DFN_QFN:UFQFPN-32-1EP_5x5mm_P0.5mm_EP3.45x3.45mm_ThermalVias` (to be submitted)
- [ ] Fp filter: `UFQFPN*1EP*5x5mm*P0.5mm*`
- [ ] Main function goes next to the border: name of pin 2 should be `OSC32_IN/PC14`, name of pin 3 should be `OSC32_OUT/PC15` and name of pin 6 should be `~RST/PF2`
- [ ] Name of pin 25 should be `PA14/BOOT0`
- [ ] Pin 33 should be stacked with VSS

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Sorry just realized I made an error for pin 6, name should be `~RST~/PF2` to have the right design

**Comment by piotr-wiszowaty** [comment]
Footprint: [#2458](https://github.com/KiCad/kicad-footprints/pull/2458).

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment just need to wait the footprint now

**Comment by piotr-wiszowaty** [comment]
The footprints are here: https://github.com/KiCad/kicad-footprints/pull/2458.

**Comment by myfreescalewebpage** [comment]
Thanks for the footprint.
Still the stacking error to be fixed, please.
Joel

**Comment by piotr-wiszowaty** [comment]
Fixed - checklib.py shows no errors. However the KLC S4.3 states that stacked pins must have the same electrical type.
Isn't that a contradiction?

**Comment by myfreescalewebpage** [comment]
It's because it depends of the types
Thanks for the update

**Comment by piotr-wiszowaty** [comment]
Ah, yes.
An annotation in point 5 would clarify things a little.
Something like "(except for Output, Power Output, Power Input; see below)".

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
