### PR TITLE
Added LM199/399 voltage reference

### PR DESCRIPTION
**Pull request by PatrickBaus**
I added the LM199/399 precision buried Zener reference. I will add the shielded TO-46 case of the LM399 in a seperate pull request:

https://www.analog.com/media/en/technical-documentation/data-sheets/199399fc.pdf

Updated: New screenshot to reflect the changes made to the icon
screenshot from 2019-02-19 09-39-29

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
- Since the standard diode symbol in our library is unfilled, can you use that style?
- There is no reason not to use the standard pin length of 100mil.
- I think all pins should be Passive type.
- This seems overly large. Here is a simplified and shrunk version incorporating the points above. See what you think and then use it, play around on your own, or let me know what you're thinking.
image
```
# LM399
#
DEF LM399 U 0 40 Y N 1 F N
F0 "U" 150 50 50 H V L CNN
F1 "LM399" 150 -50 50 H V L CNN
F2 "" 0 100 50 V I C CNN
F3 "" 0 100 50 V I C CNN
ALIAS LM199
$FPLIST
 TO?46*
$ENDFPLIST
DRAW
C -100 -60 10 0 1 0 F
C 100 -60 10 0 1 0 F
S -150 100 150 -100 0 1 10 f
P 14 0 1 0 -100 -100 -100 -40 -80 -40 -80 -15 -120 -15 -120 10 -80 10 -80 35 -120 35 -120 60 -80 60 -80 85 -100 85 -100 100 N
P 2 1 1 0 100 -60 -100 -60 N
P 2 1 1 0 100 100 100 -100 N
P 3 1 1 0 30 -30 30 -60 30 -90 N
P 3 1 1 0 70 60 130 60 130 50 N
P 4 1 1 0 -30 -30 -30 -90 30 -60 -30 -30 N
P 4 1 1 0 70 0 130 0 100 60 70 0 N
X ~ 1 100 200 100 D 50 50 1 1 P
X ~ 2 100 -200 100 U 50 50 1 1 P
X ~ 3 -100 200 100 D 50 50 1 1 P
X ~ 4 -100 -200 100 U 50 50 1 1 P
ENDDRAW
ENDDEF
```

**Comment by PatrickBaus** [comment]
@evanshultz

**Comment by PatrickBaus** [comment]
@evanshultz: :+1: 
I think the shrunk version works nicely. I used the filled diodes, because they were a little closer to the Linear/ADI original symbol, but I suppose it is only a matter of getting used to the new symbol :)

I would consider pin 3 and 4 as power pins though, because they power the internal heater. This is not passive device, but rather a transistor regulating the temperature (hence the second diode), so I would prefer to go with power pins on pin 3 and 4.

I will update my PR accordingly.

**Comment by evanshultz** [comment]
Regarding pin type, our transistors and diodes use Passive pin types and this is the same. I do see what you're saying about consuming power and being "power pins". I'll merge it like this since analog pins are a bit fuzzy anyway and I don't see an application where the ERC engine will incorrectly flag this with either pin type we discussed.

Should pin 3 have a "+" by it for clarity? What do you think?

Thanks!

**Comment by evanshultz** [comment]
I would not like to include the LM199 since it's obsolete. Please remove it.

Also, this needs a default footprint assigned since you mentioned you'll submit it. This will wait until the footprint is ready to avoid have a footprint-less symbol in the library.

**Comment by PatrickBaus** [comment]
Alright, I did remove the venerable LM199, I just included it for the sake of completeness. I also added polarity indicators. Looks nice that way.

screenshot from 2019-02-19 20-39-14

Concerning the footprint. I will have to add this to the TO-46 generator script. Gotto work myself through it first though. Hopefully tonight.

**Comment by myfreescalewebpage** [comment]
@PatrickBaus are you still working on this ? Any news of the footprint ?

**Comment by PatrickBaus** [comment]
Yes, I am still on it. I am almost done with the project, that has the LM399 in it. Once done, I will have the time to polish the changes.

**Comment by evanshultz** [comment]
@PatrickBaus 
I fixed the branch conflict, but you pushed this PR from your master branch. I highly suggest you create a branch from master for all PRs.

If you can submit the footprint I'll review it and then we can do this symbol. We are migrating from GitHub soon so I hope you're able to find time in the next few days. Thanks for coming back to this!

**Comment by PatrickBaus** [comment]
Thank you very much for the PR @evanshultz. Initially I wanted to include the TO-46-4 footprint into the generator, but I have my doubts that this was good idea back then, because the this footprint is rather special anyway due to the extra thermal shield. I will do a PR from the [kicad-footprints](https://github.com/kicad/kicad-footprints) repo and also add my 3D model.  Hopefully later today.

**Comment by PatrickBaus** [comment]
I have added the footprint now. I will add the 3d model later today. So far the FreeCAD export is looking good. I only need to make sure that it conforms to all rules.

**Comment by evanshultz** [comment]
Thanks!

Please add 1, TO-46-4` to the end of both descriptions. And assign a default footprint to both. It looks that will complete LM199.

Is the heatshield only for LM399, and is it part of the package or a separate piece? I'm unclear from the datasheet, to me.

**Comment by PatrickBaus** [comment]
Thank you so much for bearing with me. I thought I had already removed the obsolete LM199, but back then I only removed the alias. I have now removed it.
The heat shield comes with the LM399. It can be removed, but not without damage, so it is part of the LM399. The LM199 and LM299 are both obsolete and were different grades regarding the temperature range. The LM399 is the only grade available today.

**Comment by PatrickBaus** [comment]
I still need to fix the footprint filter

**Comment by PatrickBaus** [comment]
Thank you for your patience. I have added the manufacturer specific footprint Analog_TO-46-4_ThermalShield.

**Comment by evanshultz** [comment]
No problem. This is looking good, and we still have ~24 hours to get it into 5.1.7 so I'm sure we can do it.

Just one small change: please put an asterisk instead of a question mark after `Analog` in the footprint filter. We only use question marks where required. For TO-??? packages the use of question marks has broadened over time, but after the manufacturer name I only recall seeing asterisks. Thank you!

**Comment by PatrickBaus** [comment]
All done. Thanks a lot for the time spent teaching :+1:

**Comment by chschlue** [comment]
> This is looking good, and we still have ~24 hours to get it into 5.1.7 so I'm sure we can do it.

Sorry if this wasn't clear, but I wasn't planning to cherry-pick every addition to the v5 branch but generally just bug fixes.
Is there anything special about this addition?

**Comment by evanshultz** [comment]
@PatrickBaus 
I just merged the footprint and this is all good now. Thank you!

@chschlue 
Oh. Nothing special, just a nice contribution. I thought you were waiting to tag footprints until that time, and since footprints are stored in the board file it won't affect a design if footprints change. Thus, I was expecting the latest footprint repo would make it into the 5.1.7 release and only the symbol library would require any careful changes for bugfixes. My mistake if I misunderstood.

**Comment by chschlue** [comment]
I could do that if you're able to weed out breaking changes and push a PR including the rest (and get that peer reviewed to be sure) today.
Symbol merges carry a risk of not getting merged cleanly and breaking file formats, so I don't want to get too careless about it.

Footprints are a different pair of shoes, though.

**Comment by evanshultz** [comment]
You do you thing. Whatever you planned is fine. I just misunderstood.

**Pull request merged**
