### PR TITLE
Add digital isolator HCPL-9000

### PR DESCRIPTION
**Pull request by ferdymercury**
https://www.broadcom.com/products/optocouplers/industrial-plastic/digital-optocouplers/digital-isolators/hcpl-9000

Use with Package_DIP:DIP-8_W7.62mm_LongPads

------------

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the official footprint library
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by ferdymercury** [comment]
image

**Comment by ferdymercury** [comment]
I reworked the symbol

image

**Comment by myfreescalewebpage** [comment]
Hi @ferdymercury , thanks for contributing,

A few comments I have during my review:

- [ ] Name of the device is "HCPL-9000" not "HCPL9000"
- [ ] Please rework isolation barrier according to the last standard (single line dash)
- [ ] Rework symbol reference and name (no bold) to be consistent with all other devices
- [ ] Why using long pad for this device ?
- [ ] Use capital letters for pin names
- [ ] You are currently violating KLC S3.6 that can be corrected, see travis output

Cheers,
Joel

**Comment by ferdymercury** [comment]
Fixed all, thanks for the review!

**Comment by ferdymercury** [comment]
image

**Comment by myfreescalewebpage** [comment]
@ferdymercury thanks.

There is a missing line return at the end of the definition of your symbol (`ENDDEF`) and before the ILD74 part in the lib file (starting with `#` ). You have probably made something manually ? Screenshot of the git diff below. The library cannot be correctly opened with this error and I cannot correctly check your enhancements...

capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@ferdymercury thanks.

Just also seen: the footprint is missing in the description. Add `, DIP-8`add the end.

Else, sounds good.

Joel

**Comment by ferdymercury** [comment]
The HCPL 9000 is available in 8-pin PDIP, 8-pin Gul Wing, 8-pin SOIC packages

Should I add these to the fp filter?

**Comment by ferdymercury** [comment]
Changed, thanks!

**Comment by myfreescalewebpage** [comment]
@ferdymercury thanks.

@antoniovazquezblanco this PR is ready to be merged according to me.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
