### PR TITLE
Addition of MAX17501 DC-DC Converter

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of MAX17501 series of DC converter

I've created two symbols, one for the fixed output versions (Pin 7 is NC) and the adjustable version (Pin 7 is for a compensation network)

Datasheet Link: https://datasheets.maximintegrated.com/en/ds/MAX17501.pdf

Travis is suggesting to place power pins on the top, however the VCC pin is for a decoupling capacitor, and I've left the VIN pin on the left for a cleaner schematic look (I used the MAX17572 as a template)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jamesrlucas** [comment]
Bump please?

**Comment by myfreescalewebpage** [comment]
Hi @jamesrlucas , thanks for contributing,

A few comments I have during my review:

For both symbols:
- [ ] The footprint is not correct. You should select the exact footprint, particularly regarding EP size
- [ ] EP should be stacked with GND has required by the datasheet

Cheers,
Joel

**Comment by jamesrlucas** [comment]
All done! I've submitted a new [footprint PR](https://github.com/KiCad/kicad-footprints/pull/2248) to cover the new footprint required

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by jamesrlucas** [comment]
Right, I've just had to update the footprint names to match those generated by the footprint generator script, [Link here](https://github.com/pointhi/kicad-footprint-generator/pull/548)

**Comment by chschlue** [comment]
FP merged.

**Comment by chschlue** [comment]
These should be suffixed `xTB` to exclude temp range, BTW.

**Comment by myfreescalewebpage** [comment]
Good catch here too @chschlue 
The name of the symbols should be "MAX17501AxTB", "MAX17501BxTB" etc.
Joel

**Comment by jamesrlucas** [comment]
Done :)

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
