### PR TITLE
Add SHT3x-DIS digital humidity sensors

### PR DESCRIPTION
**Pull request by lorenz**
Adds the SHT3x(A)-DIS family of humidity sensors from Sensirion.

Based on #2491 which seems to be abandonend. I adressed all concerns raised in that PR and cleaned up the metadata.

SHT3x-symbols

[Datasheet SHT3x-DIS](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Datasheets/Sensirion_Humidity_Sensors_SHT3x_Datasheet_digital.pdf)
[Datasheet SHT3xA-DIS](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Datasheets/Sensirion_Humidity_Sensors_SHT3xA_Datasheet.pdf)

The A variants are AEQ-100 automotive variants of the same sensor.
These use a customized DFN-8 footprint (https://github.com/KiCad/kicad-footprints/pull/2369).

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @lorenz , thanks to continue the job on this device,

A single comment I have during my review:

- [ ] SCL is Input  for I2C devices in the lib

Cheers,
Joel

**Comment by lorenz** [comment]
Should now be fixed :)

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by chschlue** [comment]
FP merged.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
