### PR TITLE
Add CC430F513xIRGZ

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: http://www.ti.com/lit/ds/symlink/cc430f5137.pdf#page=128
Footprint: https://github.com/KiCad/kicad-footprints/pull/2189

Captura de pantalla de 2020-04-01 15-26-35
Captura de pantalla de 2020-04-01 15-26-56

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [X] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cnieves1** [comment]
Captura de pantalla de 2020-04-01 15-28-25

**Comment by myfreescalewebpage** [comment]
Hello @cnieves1 

For MCU we usually keep only the main pin function, can you simplify the names please ? Will do a full review after.

Joel

**Comment by cnieves1** [comment]
Done
Captura de pantalla de 2020-04-27 11-41-09

**Comment by myfreescalewebpage** [comment]
Thanks. Full review below:

- [ ] The name of the devices should be "CC430F5137xRGZ", "CC430F5135xRGZ" and "CC430F5133xRGZ"
- [ ] Pin 25 should be Input
- [ ] Pin 31 should be Power Input
- [ ] Name of pin 34 is "GUARD"
- [ ] Name of pin 40 should be `~RST`
- [ ] Maybe you can exchange RST and TEST, so RST is near to the JTAG interface ?

Joel

**Comment by cnieves1** [comment]
Hi Joel,
Instead of exchanging RST and TEST, I 
Captura de pantalla de 2020-04-29 08-17-57

**Comment by cnieves1** [comment]
Hi Joel,
Instead of exchanging RST and TEST, I moved the  debug port near RST near RST pin.
I think it is better because there is usually a pull-up resistor connected to RST pin and RST pin is close to power supply pins this way.

Captura de pantalla de 2020-04-29 08-17-57

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint now.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
@cnieves1 i have merged the footprint for this symbol. After thinking to the footprint I suggest to indicate the "ThermalVia" footprint by default here in the symbol. Can you modify the footprint please ?
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
