### PR TITLE
Various symbol fixes

### PR DESCRIPTION
**Pull request by evanshultz**
Replaces https://github.com/KiCad/kicad-symbols/pull/325.

Update [ADC128D818 ](http://www.ti.com/lit/ds/symlink/adc128d818.pdf)and several fixes in the FET library. New part is [FDS2734](http://www.onsemi.com/pub/Collateral/FDS2734-D.pdf).

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@jkriege2 
Can you help to review this and get all these symbol updates done? Note the one Travis error is not an error as that symbol (and it's ALIASes) are now all an ALIAS of a compatible symbol.

**Comment by jkriege2** [comment]
Hi!

this looks mostly good to me ... but there is a slight bug in our check-scripts, which I fixed here: https://github.com/KiCad/kicad-library-utils/pull/214 (If you have time, please merge that ;-)

If you run the fixed scripts on Transistor_FET.lib, you get these additional errors:
```
Checking symbol 'FDS6890A':
  Violating S4.3
    Rules for pin stacking
    Pinstack @ (100,-200) (unit 1) have different names
     - Pin ~ (7) @ (100,200)
     - Pin D (8) @ (100,200)
    Pinstack @ (100,-200) (unit 2) have different names
     - Pin D (5) @ (100,200)
     - Pin ~ (6) @ (100,200)
Checking symbol 'IRF7324':
  Violating S4.3
    Rules for pin stacking
    Pinstack @ (100,-200) (unit 2) have different names
     - Pin ~ (5) @ (100,200)
     - Pin D (6) @ (100,200)
Checking symbol 'IRF7343PBF':
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin G (2), @ (-200, -50)mil
     - Pin G (4), @ (-200, -50)mil
```

Could you still fix these? Then I can merge!

Thanks,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Thanks! I merged the fix to the check scripts and fixed the items above. The first two I used x1 and x2 pin names for the two different FETs, and for the last one IRF7343 was already an ALIAS in addition to a unique symbol so I removed the unique symbol and left it as an ALIAS (the lib file loads fine in KiCad).

**Comment by jkriege2** [comment]
Thanks for the fix!

JAN

**Pull request merged**
