### PR TITLE
Add support for USR USR-C322 3Mbps UART-WIFI Module.

### PR DESCRIPTION
**Pull request by cybertale**
Signed-off-by: Song Qiang <songqiang1304521@gmail.com>

Add support for USR USR-C322 3Mbps UART-WIFI Module.

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing

https://www.usriot.com/download/WIFI/USR-C322%20User%20Manual%20V2.3.pdf

- [ ] An example screenshot image is very helpful

usr-c322-sym

- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate

https://github.com/KiCad/kicad-footprints/pull/1154

- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
> Travis cannot pass because it has a associated footprint PR that has not been merged.

Don't worry, we will take this into account. Thank you :)

**Comment by myfreescalewebpage** [comment]
Hi @cybertale , thanks for contributing,

A few comments I have during my review:

- [ ] Can you move the device to "RF_WiFi" library (that's a new one in which we have all WiFi modules). If you haven it, it's because you need to solve branch conflict before by merging the master in your branch.
- [ ] Can you change the keyword to `WiFi IEEE802.11 b/g/n` for consistency with another device.
- [ ] Name of pin 4 should be `~RESET` to get the over bar
- [ ] Name of pin 21 should be `~RELOAD` to get the over bar
- [ ] Name of pin 22 should be `~READY` to get the over bar
- [ ] Name of pin 23 should be `~LINK` to get the over bar
- [ ] READY and LINK pins type should be Open Collector
- [ ] SOP0 and SOP1 should be kept visible, type Passive and grouped with SOP2 to allow user wiring them if required in a specific application
- [ ] SOP2 type should be Passive
- [ ] ANA_DC-DC should be kept visible, type Passive to allow user wiring it if required in a specific application
- [ ] Regarding to GPIO, I have a big big doubt because of the schematic page 14. Seems all pins can be turned to GPIO isn't it ? Moreover, the numbers you have assigned to your GPIOs is not consistent... Would say the schematic page 14 is better, and you need to rename all pins. What is your feedback of using this module ? Thanks.

Cheers,
Joel

**Comment by cybertale** [comment]
Hi @myfreescalewebpage, thanks for your time for reviewing! I'm a bit busy this week, will get it done in my spare time!

**Comment by myfreescalewebpage** [comment]
Hi @cybertale 
No worries, thanks.
Joel

**Comment by cybertale** [comment]
Hi Joe , sorry for the late, I made all the changes you requested except the last one. I drew this component with referring the pin definitions on page 10-11. It seems like it has some conflicts with schemetic on page 14. 
My opinion is changing all the possible GPIO lines to GPIO, and numbering them from 0. Because if I name all the GPIO lines as page 14 suggests, it would be difficult to give pin 2/3 a proper GPIO index.
Do you think I should add SPI_* to pin 33-37? These pins have never been mentioned in pin definitions and manuals but only this schematic.
@myfreescalewebpage

**Comment by myfreescalewebpage** [comment]
Hi @cybertale thanks for your answer,

> it would be difficult to give pin 2/3 a proper GPIO index.

Not understood.

Maybe you can push the modifications already done, then will do a new review because it's a long time ago I have not looked at this symbol. Thanks,

Joel

**Comment by myfreescalewebpage** [comment]
@cybertale any news here ? Thanks, Joel
PS : you also have a branch conflict to solve now

**Comment by cybertale** [comment]
@myfreescalewebpage Hi Joel, I updated the symbol and resolved the conflict, all changes you requested are made except the last one, which need to be discussed I think.

**Comment by myfreescalewebpage** [comment]
@cybertale thanks for the fixes!
You should use capital letters for the pins 4,21,22,23.
The last point is about GPIOs and there is two purposes:
- UART pins can also be GPIO (minor point at the moment)
- GPIO number you have assigned are not specified in the datasheet, and it's a trouble for me. I do not found GPIO number anywhere, how do you know pin 2 is GPIO0 etc ? How do you use them in the software ?
Joel

**Comment by cybertale** [comment]
@myfreescalewebpage Hi Joel, I suspect all the GPIO pins were intentionally left without numbering because they may be available some day but not available now. I went their website and downloaded all the manuals about this module but didn't find any part telling us how to use its GPIO. 
And I actually numbered pin 2 as GPIO0 just because it's the first GPIO pin in the pinout table in page 10 of the manual. 
After the searching, I think your idea was better, I should use pin numbering from page 14, but what's stopping me is that pin 2 in page 10's table is GPIO but NC_ATNSEL1 in page14.
What do you think I should do with this?

**Comment by myfreescalewebpage** [comment]
To understand completely and answer your question: today, the user manual of the module only indicate how to use the uart interface with AT commands, to access the WiFi interface, right? You are using the module with an external microcontroller?
If answer yes to this, maybe in this case we can keep the numbering you have already proposed, and it will still be possible to modify it in the future.

**Comment by myfreescalewebpage** [comment]
@cybertale ping :)

**Comment by cybertale** [comment]
> @cybertale ping :)

That's right, so it is OK now, and this PR should just wait until the corresponding footprint one is got merged, right?

**Comment by myfreescalewebpage** [comment]
@cybertale no, you have remaining modification, please see my previous comment at:
https://github.com/KiCad/kicad-symbols/pull/1236#issuecomment-453123156 (use of capital letters)
Joel

**Comment by cybertale** [comment]
@myfreescalewebpage Hi Joel, how about this time?

**Comment by myfreescalewebpage** [comment]
@cybertale thanks for the update, looks good.
I was wondering about the height of the symbol while reading again this pull request. it is possible to easily reduce it by moving all left pins to the top. You can arrange NC pins to achieve this. Can you do it ?
Else, just need to wait the footprint.
Joel

**Comment by cybertale** [comment]
@myfreescalewebpage I moved 2 NC pins to the bottom for space, is this OK?

**Comment by myfreescalewebpage** [comment]
Looks great, thanks !
Yes NC on the bottom or top is allowed :)

**Comment by myfreescalewebpage** [comment]
@cybertale just notice after the integration of the footprint that you have made a case mistake in the footprint. This should be "RF_WiFi" instead of "RF_Wifi". Can you this, then the symbol is ready to merge.
Thanks,
Joel

**Comment by cybertale** [comment]
@myfreescalewebpage I'm not sure my change is the one you mentioned. I've only found this was wrong and fixed it. 
webwxgetmsgimg

**Comment by myfreescalewebpage** [comment]
It is, thanks. No more comment, merging. Thanks for the great job here!
PS: in the future please do not force push, this is very complicate to review
Joel

**Pull request merged**
