### PR TITLE
Texas Instruments PGA112/PGA113 programmable gain amplifier footprint

### PR DESCRIPTION
**Pull request by jeanthom**
Hi !

pga11x

PGA113 is an alias to PGA112 (they share the same pinout, but their gain ranges differ)

Datasheet : [PGA112/PGA113/PGA116/PGA117](http://www.ti.com/lit/ds/sbos424c/sbos424c.pdf)

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jeanthom** [comment]
I did sign the CLA for this repo (a few of my PR have been merged successfully), I don't understand why the CLA check isn't OK on this PR.

**Comment by poeschlr** [comment]
CLA is fixed now. (closing and reopening the pull request did the trick)

**Comment by evanshultz** [comment]
@jeanthom 
It seems this PR hasn't gotten much attention. Are you willing to finish it up if I review it? Of course, the branch conflicts must be resolved before merging.

**Comment by jeanthom** [comment]
Yup I will do the necessary changes if there are any.

**Comment by evanshultz** [comment]
- Please add the gain ranges in the description so we can differentiate these symbols.
- Remove "VSSOP" from the keywords (this can be searched from the description).
- Set the pin name offset to 20mil.
- Ref des should move to the top left.
- GND pins are Power Input type (yes, it seems weird).
- This symbol looks bigger than it needs to be. Here is a compressed version of the symbol which works and is much smaller. It could grow vertically by 100mil top and bottom to spread things out. I would have liked to put VIN and VOUT across from each other but that forced the symbol size to grow a lot. You may update to this version if you like, or perhaps try to make a smaller version yourself:
image
```
# PGA112
#
DEF PGA112 U 0 20 Y Y 1 F N
F0 "U" -250 350 50 H V R CNN
F1 "PGA112" 50 350 50 H V L CNN
F2 "Package_SO:TSSOP-10_3x3mm_P0.5mm" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
ALIAS PGA113
$FPLIST
 TSSOP*3x3mm*P0.5mm*
$ENDFPLIST
DRAW
S -300 300 300 -300 0 1 10 f
X AVDD 1 -100 400 100 D 50 50 1 1 W
X DVDD 10 0 400 100 D 50 50 1 1 W
X CH1 2 -400 100 100 R 50 50 1 1 I
X VCAL/CH0 3 -400 0 100 R 50 50 1 1 I
X VREF 4 -400 -200 100 R 50 50 1 1 I
X VOUT 5 400 -200 100 L 50 50 1 1 O
X GND 6 0 -400 100 U 50 50 1 1 W
X SCLK 7 400 200 100 L 50 50 1 1 I
X DIO 8 400 100 100 L 50 50 1 1 B
X ~CS 9 400 0 100 L 50 50 1 1 I
ENDDRAW
ENDDEF
```

And of course, you will need to correct the branch conflict.

**Comment by jeanthom** [comment]
pga11x

**Comment by evanshultz** [comment]
I would like some space between VOUT and the SPI bus since they're totally different domains of data. Do you find a nice way to do that? Otherwise it looks good to me.

**Comment by jeanthom** [comment]
At the expense of making the symbol a bit bigger:
pga11x

**Comment by evanshultz** [comment]
Hmmm... the origin is in the lower left corner. Can you center the rectangle on the origin and then try to keep the width and height balanced around the axis?

**Comment by jeanthom** [comment]
pga11x

**Comment by evanshultz** [comment]
OK. The centering rule is weak so having this symbol be unbalanced will be fine. Thanks!

**Pull request merged**
