### PR TITLE
Bno55

### PR DESCRIPTION
**Pull request by jneiva08**
Added BNO055 to Sensor_Motion

Datasheet: https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST_BNO055_DS000_14.pdf

symbol:
bno_sch

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Pin 4, nBOOT_LOAD_PIN is active low, please add an ~ in front of the text
Pin 9, CAP, "cap" pins are usually marked as "passive", not a deal breaker , but

Package "indication" is missing in the description, change the description from
 Absolute orientation sensor, 9-axis sensor fusion
To
 Absolute orientation sensor, 9-axis sensor fusion, LGA

**Comment by jneiva08** [comment]
Leave screenshot of symbol and properties.

symbol

properties

**Comment by Misca1234** [comment]
Looks good to me, any objections for merging ?

**Comment by evanshultz** [comment]
- Please update the description to `Intelligent 9-axis absolute orientation sensor, LGA-28` to better match datasheet text and include pin count.
- You can add optional text before the package type if you want, like `Sensor Fusion`, `I2C, UART`, etc.
- Remove duplicate text from keywords that is in the description.
- Should this be a manufacturer-specific footprint? There are several other Bosch footprints at https://github.com/KiCad/kicad-footprints/tree/master/Package_LGA.pretty. @poeschlr?
- I'd like to see pin 9 moved towards the bottom since it's just a cap to ground.
- Place PS0 and PS1 on the VDDIO/GNDIO side since that's the voltages those pins can connect to.
- Would it make sense to put pins 4 and 10 across from each other?
- Is there a better arrangement of COM pins since one is only an input? Should it be on the left?

**Comment by evanshultz** [comment]
It's always helpful to post a new screenshot if there are visual changes. Here is the symbol now:
image

- Only ground pins should be on the bottom.
- It's often nice to spread apart crystal pins so that the crystal symbol can fit between them.

Here's another approach that puts all the interface pins (going to a MCU) on the left side and all the pins that connect to a static voltage (local to this IC) on the right side. You don't have to take this symbol as is, but it's another idea to consider:
image
```
# BNO055
#
DEF BNO055 U 0 20 Y Y 1 F N
F0 "U" -450 650 50 H V L CNN
F1 "BNO055" 500 650 50 H V R CNN
F2 "Package_LGA:LGA-28_5.2x3.8mm_P0.5mm" 0 0 50 H I C CNN
F3 "" 0 200 50 H I C CNN
$FPLIST
 LGA*5.2x3.8mm*P0.5mm*
$ENDFPLIST
DRAW
S -500 600 500 -600 0 1 10 f
X PIN1 1 -500 400 100 R 50 50 1 1 N N
X GND 2 -100 -700 100 U 50 50 1 1 W
X VDD 3 -100 700 100 D 50 50 1 1 W
X ~nBOOT_LOAD_PIN 4 -600 100 100 R 50 50 1 1 I
X PS1 5 600 -400 100 L 50 50 1 1 I
X PS0 6 600 -300 100 L 50 50 1 1 I
X PIN7 7 -500 200 100 R 50 50 1 1 N N
X PIN8 8 -500 -100 100 R 50 50 1 1 N N
X CAP 9 600 -500 100 L 50 50 1 1 P
X BL_IND 10 -600 0 100 R 50 50 1 1 O
X COM0 20 -600 -200 100 R 50 50 1 1 B
X ~nRESET 11 -600 500 100 R 50 50 1 1 I
X PIN21 21 500 200 100 L 50 50 1 1 N N
X PIN12 12 500 400 100 L 50 50 1 1 N N
X PIN22 22 500 100 100 L 50 50 1 1 N N
X PIN13 13 500 300 100 L 50 50 1 1 N N
X PIN23 23 500 -100 100 L 50 50 1 1 N N
X INT 14 -600 300 100 R 50 50 1 1 O
X PIN24 24 500 -200 100 L 50 50 1 1 N N
X GNDIO 15 100 -700 100 U 50 50 1 1 P N
X GNDIO 25 100 -700 100 U 50 50 1 1 W
X GNDIO 16 100 -700 100 U 50 50 1 1 P N
X XOUT32 26 600 0 100 L 50 50 1 1 O
X COM3 17 -600 -500 100 R 50 50 1 1 I
X XIN32 27 600 500 100 L 50 50 1 1 I
X COM2 18 -600 -400 100 R 50 50 1 1 B
X VDDIO 28 100 700 100 D 50 50 1 1 W
X COM1 19 -600 -300 100 R 50 50 1 1 B
ENDDRAW
ENDDEF
```

**Comment by jneiva08** [comment]
Sorry for not understanding what you described to do.

now looks like you recomended
imu

**Comment by evanshultz** [comment]
No problem. A picture is worth a thousand words.

I'll assume my suggestion is OK with you too (it doesn't have to be!) and merge. Thanks!

**Pull request merged**
