### PR TITLE
add AAT4610B

### PR DESCRIPTION
**Pull request by balcer**
*Replace this line with your commit message! Please provide a description of your pull request*

http://www.skyworksinc.com/uploads/documents/201937A.pdf

aa
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @balcer, thanks for contributing,

A few comments I have during my review:

- [ ] Descriptions should end with the package name `, SOT-23-5`
- [ ] SET pins must be Passive to avoid ERC errors

Else sounds good !

Cheers,
Joel

**Comment by balcer** [comment]
Thanks @myfreescalewebpage. Done

**Comment by myfreescalewebpage** [comment]
Hi @balcer thanks for the modification. However, you added the package name to t he keyword instead of the description. Also do not forget the comma: `Current Limited Load Switch, SOT-23-5`
Joel

**Comment by balcer** [comment]
Done

**Comment by myfreescalewebpage** [comment]
@balcer same problem than #1544

**Comment by balcer** [comment]
@myfreescalewebpage Now should be ok. Sorry for the problems.

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
