### PR TITLE
Ade7763

### PR DESCRIPTION
**Pull request by Duckle29**
Added the single-phase power metering IC ADE7763

The symbol is a duplicate of the tripple-phase ADE7758 with the relevante changes made

- different pin names
- different pins
- different description and datasheet
- different footprint
- different footprint filter

---

[Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADE7763.pdf)

image

image
image

No aliases

- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by Duckle29** [comment]
Moved pins: 
image

**Comment by Duckle29** [comment]
image

Moved DVDD and DGND to be symmetric with analog power pins around vertical axis

**Comment by myfreescalewebpage** [comment]
Hi @Duckle29 , thanks for contributing,

A comment I have during my review:

- [ ] The name of the device should be "ADE7763xRS"

Else no comment, good job!

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@Duckle29 ping

**Comment by Duckle29** [comment]
@myfreescalewebpage Sorry for the disappearance weren't home for a month of work :P

**Comment by myfreescalewebpage** [comment]
No worries, I have ping you because it was very easy to fix :)
Merging.

**Pull request merged**
