### PR TITLE
Add NXP MCU MKV11Z128VLF7

### PR DESCRIPTION
**Pull request by michalkona**
NXP MCU MKV11Z128VLF7 for motor control applications was added.

Datasheet: https://www.nxp.com/docs/en/data-sheet/KV11P64M75.pdf

Screenshot:
MKV11Z128VLF7

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @michalkona , thanks for contributing,

A few comments I have during my review:
 
- [ ] You can decrease the height of the device by 100mil at the bottom

Cheers,
Joel

**Comment by michalkona** [comment]
The symbol cannot be placed on the middle (Violating S3.1), that's why bottom part of symbol is long.

**Comment by myfreescalewebpage** [comment]
It will not be at the exact middle, there will be an offset of 50mil. This is an info in travis, not an error, to permit the design. We accept the symbol in this case.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
