### PR TITLE
- added Infineon BTN8982TA Half-Bridge to Power_Management library ( …

### PR DESCRIPTION
**Pull request by daviid5**
added Infineon BTN8982TA Half-Bridge to Power_Management library ( https://www.infineon.com/dgdl/Infineon-BTN8982TA-DS-v01_00-EN.pdf?fileId=db3a30433fa9412f013fbe32289b7c17 )
added NEXPERIA PSMN5R2-60YL N-Channel Mosfet to Transistor_FET library ( https://assets.nexperia.com/documents/data-sheet/PSMN5R2-60YL.pdf  )

btn8982ta

psmn5r2-60yl

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
You got the CLA figured out. Great!

Your branch was created from an older commit. Can you please update your branch to HEAD?

BTN...
- Why did you place this in Power_Management?
- There is a space at the front of your description.
- Perhaps just use the datasheet description of `High Current PN Half Bridge`.
- Please `TO-263-7` at the end of your description.
- Please add a default footprint.
- Pins are not on a 100mil grid.
- The outer box is not 10mil thickness.
- Set pin text offset to 20mil.
- All pins are of type Input but they should not be.
- I think VS can move to the top and GND can move to the bottom nicely.
- Stack the OUT pins.
- Flipping the positions of pins 5 and 6 may help since pin 5 won't connect to other symbols.
- You may look at my similar symbols at https://github.com/KiCad/kicad-symbols/pull/410 to see if you would like to copy the design of having FET symbols inside with a control block.

PSMN...
- Remove `Power` to conform to existing part descriptions.
- Similarly, change `Rds` to `Ron` in the description.
- Did you an existing symbol and then edit it?
- Please add a default footprint.

Some of these items can be found in the Travis CI check scripts. You can see the results from clicking the "Details" link above. If you have any questions please ask!

**Comment by daviid5** [comment]
BTN
I looked at the other parts in the Power_Management lib and thought that thats the right lib.
I don't think that this parts belongs to Transistor_FET, because the BTN is not just a Mosfet, it contains the gate driver, over current protection, sensing and so on ...
regarding to S4.4 of the http://kicad-pcb.org/libraries/klc/ I now changed Pin 8 to an "output"

I changed the Footprint now to the TO-263-7_TabPin8

Just a side node, I think a search function for searching footprints would be really nice


PSMN
I'm relatively shure that I used an existing symbol and edited it, but I cannot remember which one it was

sry that this takes a bit longer, this is my first contribution ...

**Comment by evanshultz** [comment]
BTN..
- I recall a discussion about where to place "smart FETs" like this. Power_Management is where all these parts ended up so it's fine for this symbol. I wanted a user opinion from you.
- Would you consider adding a box in the symbol for the control circuitry? Maybe also naming the OUT pins `~` and drawing the line right to the symbol outline? Perhaps something similar for VS and GND? Right now it's two FET symbols floating in a box which doesn't give a good indication how things are connected and other symbols I can recall have a bit more detail.
- Pin OUT is now Output type, not Passive. It does not fall into any category given in S4.4 and I mentioned above by Passive is correct.
- Footprint filter should be `TO*263*7*TabPin8*` (we prefer asterisk unless there's a reason not to).

While I'm not all that familiar with it, there is a footprint search tool. Go to place a footprint on a PCB and you will see this:
image

The "Search by Keyword" doesn't seem to work (or I'm not using it right), but the "List All" function will allow you to enter some text from which to filter all footprints in your library. See here:
image

Is that what you wanted to do?

Everything is good. No need to apologize for anything. Thanks for your contribution!

**Comment by daviid5** [comment]
btn8982ta_3
You meant it like this?

regarding searching:
No I was looking for a possibility to search for an footprint when I'm defining an footprint of an symbol in the schematic editor.
In this window a search function would be nice ;)
kicad_lib-browser

**Comment by evanshultz** [comment]
Yeah! That's looking nice. Can you shrink the symbol a little bit?

I thought what I wrote above would help with searching. It's not integrated into the symbol editor, but would allow typing in strings to look at all footprints. Maybe I misunderstood. If you want to view footprints while searching, I don't think you can. Adding a footprint preview to the dialog I added above might be helpful. If there is a feature missing from KiCad, you can always submit a bug at https://bugs.launchpad.net/kicad.

**Comment by evanshultz** [comment]
I submitted https://bugs.launchpad.net/kicad/+bug/1763200, which snips out the relevant parts of our conversation and hopefully captures the request to both filter footprint name and also preview. I believe that's what you ultimately want, right?

**Comment by daviid5** [comment]
btn8982ta_4
I now changed the symbol to this, that's better?

Yeah, your bug report/feature request describes what I'm looking for.

**Comment by evanshultz** [comment]
Nice! Move in pins 1 and 7, then thin the lines for consistency, and push those changes. Looks about ready to merge.

**Comment by evanshultz** [comment]
- I forgot to delete the pin count in the footprint filter change above. Please modify to `TO*263*TabPin8*`.
- The ref des and value are rather far from the symbol body. Can you move them closer?

A few more lines could be thinned and the symbol could be shrunk a bit to center it horizontally (the pins then lie on +/-300mil). Here is my modifications:
image

```
# BTN8982TA
#
DEF BTN8982TA U 0 20 Y Y 1 F N
F0 "U" 200 200 50 H V L CNN
F1 "BTN8982TA" 200 100 50 H V L CNN
F2 "Package_TO_SOT_SMD:TO-263-7_TabPin8" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 Package_TO_SOT_SMD:TO*263*TabPin8*
$ENDFPLIST
DRAW
C 100 -230 11 1 1 0 F
C 100 -90 11 1 1 0 F
C 100 0 11 1 1 0 F
C 100 90 11 1 1 0 F
C 100 230 11 1 1 0 F
S -200 300 200 -300 0 1 10 f
P 2 0 1 0 10 -235 -50 -235 N
P 2 0 1 0 10 85 -50 85 N
P 2 0 1 0 100 0 200 0 N
P 2 0 1 0 100 90 100 -90 N
P 3 0 1 0 100 -230 100 -300 100 -270 N
P 4 0 1 0 -200 250 -50 250 -50 -250 -200 -250 N
P 2 1 1 0 30 -230 100 -230 N
P 2 1 1 10 30 -210 30 -250 N
P 2 1 1 0 30 -160 100 -160 N
P 2 1 1 10 30 -140 30 -180 N
P 2 1 1 0 30 -90 100 -90 N
P 2 1 1 10 30 -70 30 -110 N
P 2 1 1 0 30 90 100 90 N
P 2 1 1 10 30 110 30 70 N
P 2 1 1 0 30 160 100 160 N
P 2 1 1 10 30 180 30 140 N
P 2 1 1 0 30 230 100 230 N
P 2 1 1 10 30 250 30 210 N
P 2 1 1 0 100 -230 100 -160 N
P 2 1 1 0 100 160 100 230 N
P 2 1 1 0 100 300 100 230 N
P 3 1 1 0 10 -85 10 -235 10 -235 N
P 3 1 1 0 10 235 10 85 10 85 N
P 4 1 1 0 40 -160 80 -145 80 -175 40 -160 F
P 4 1 1 0 85 160 45 145 45 175 85 160 F
P 4 1 1 0 100 -230 130 -230 130 -90 100 -90 N
P 4 1 1 0 100 90 130 90 130 230 100 230 N
P 4 1 1 0 110 -140 115 -145 145 -145 150 -150 N
P 4 1 1 0 110 180 115 175 145 175 150 170 N
P 4 1 1 0 130 -145 115 -170 145 -170 130 -145 N
P 4 1 1 0 130 175 115 150 145 150 130 175 N
X ~ 1 100 -400 100 U 50 50 1 1 W
X IN 2 -300 100 100 R 50 50 1 1 I
X INH 3 -300 200 100 R 50 50 1 1 I
X ~ 4 300 0 100 L 50 50 1 1 P N
X SR 5 -300 -200 100 R 50 50 1 1 I
X IS 6 -300 -100 100 R 50 50 1 1 O
X ~ 7 100 400 100 D 50 50 1 1 W
X ~ 8 300 0 100 L 50 50 1 1 P
ENDDRAW
ENDDEF
#
```

What do you think? You are not required to accept this, I'm just playing around a bit.

**Comment by evanshultz** [comment]
Thanks! The ref des and value were not moved. Also, you can set the lines to 0mil thickness instead of a fixed 6mil line width? Then it's ready to merge.

**Comment by Ratfink** [comment]
@evanshultz This should be ready now, though you might remove the library name from BTN8982TA's footprint filter.

**Comment by evanshultz** [comment]
@daviid5 
The statement above is correct. Can you accept my apology and please change the footprint filter to `TO*263*TabPin8*`? Then either of us can merge. Thanks!

**Comment by daviid5** [comment]
@evanshultz done, hopefully now the it's ready

**Comment by evanshultz** [comment]
Yes, it is. Thanks so much for contributing to KiCad!

**Comment by fauxpark** [comment]
@evanshultz I just noticed this PR appears to have reverted #420, could you take a look at it or should I just resubmit?

**Pull request merged**
