### PR TITLE
WCH CH340C

### PR DESCRIPTION
**Pull request by gcormier**
CH340C is a crystal-less variant of the CH340G. It is identical, other than the crystal pins for the G now being no connect.

Violation - Some inputs are on the right. I intentionally kept the exact same layout for the symbol as the G series, as I felt if a designer wanted to switch to the C variant, it would require no changes to the connections in the KiCad schematic - delete the G, drop in the C.

Datasheet in Chinese unfortunately : https://datasheet.lcsc.com/szlcsc/Jiangsu-Qin-Heng-CH340C_C84681.pdf

New CH340C:
image

Existing CH340G:
image

### CODE REVIEW

**Comment by gcormier** [comment]
Don't forget datasheet drama in #814 :)

**Comment by cp-aquila** [comment]
related: https://github.com/KiCad/kicad-symbols/pull/2159

**Comment by gcormier** [comment]
Well crap! Shall I close?

**Comment by cp-aquila** [comment]
> 
> 
> Well crap! Shall I close?

No need. Those are different parts, so two PRs are okay.
The only downside is that there will most likely be merge conflicts for the 2nd PR after the first is merged.

**Comment by myfreescalewebpage** [comment]
@gcormier no comment to do on this pull request except you need to rebase. Then ready to merge. Joel

**Comment by gcormier** [comment]
@myfreescalewebpage First time re-basing, I think it worked? What a pain..

**Comment by myfreescalewebpage** [comment]
Its not. https://github.com/KiCad/kicad-symbols/pull/2209/files should list only your modifications.

**Comment by gcormier** [comment]
I think it'll be faster to just do a new branch, copy and paste the changes and do a new PR, does that work for you?

**Comment by myfreescalewebpage** [comment]
Ok for me if it's easier for you!

**Comment by gcormier** [comment]
#2599 open, will close this one.

**Pull request closed without merging**
