### PR TITLE
Correct FP assignment for LTC4001

### PR DESCRIPTION
**Pull request by poeschlr**
The wrong EP size was used in the assigned footprint
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1210

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/4001f.pdf

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @poeschlr 

Agreed with the change. Can be merged as soon as the footprint is accepted.

Cheers,
Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Sorry. I didn't refresh the page and missed that you assigned yourself and reviewed this already.

**Comment by myfreescalewebpage** [comment]
@evanshultz  no worries :)

**Comment by poeschlr** [comment]
footprint merged

**Pull request merged**
