### PR TITLE
Add single version of ltc6752 high speed comparator

### PR DESCRIPTION
**Pull request by cp-aquila**
Add single version of ltc6752 high speed comparator
* SC-70 variant as new symbol
* SOT-23-5 variant as alias. Pin names here are not 100% correct (V+, V-). I don't think that is a problem. Otherwise a new symbol would be required.

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/6752fc.pdf

grafik
grafik
grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cp-aquila , thanks for contributing,

A few comments I have during my review:

LTC6752xSC6
- [ ] Footprint filter should be `SC?70*`
- [ ] Can you make the design with the same size of the triangle compared to LTC6752xS5 ?
- [ ] Pin 5 is Input

Cheers,
Joel

**Comment by cp-aquila** [comment]
Hi Joel,

thanks for the review.
I added some commits to fix the issues found.
It seems like travis is taking a holiday. Clsoing and re-opening this PR did not help either.

The local run of the check-scripts does output this:
grafik

**Comment by myfreescalewebpage** [comment]
Travis now back!
I made a mistake about the footprint filter, it should be `SOT?363*`
Joel

**Comment by myfreescalewebpage** [comment]
Hello @cp-aquila 
Please `SOT?363*`, I try to have something uniformed when merging and for that it's better to not have the front `*` :)
Joel

**Comment by cp-aquila** [comment]
Sorry, this took long.
Do we also want to update any other footprint-filters in that lib? That would be a simple regular-expression search-replace.

**Comment by cp-aquila** [comment]
Reference:
grafik

**Comment by myfreescalewebpage** [comment]
Thanks.
Yes I know some symbols have a leading '*' but it's no more expected since a long time.
If you have want to help by changing the symbols in the library it's always welcome, this kind of modification don't need to wait a major release. However, for such kind of details i don't know if it's required to spent energy on it....
No more comment on this pull request, merging.
Joel

**Pull request merged**
