### PR TITLE
AT89xxxx-xx Symbol Fixes

### PR DESCRIPTION
**Pull request by daab4848**
**Pull Request Details** 
-----------------------------------------------------------------
**Part Name**: AT89C2051/C4051-PU
**Part Manufacturer**: Microchip
**Datasheet URL**: 
AT89C2051-PU (2K Byte Flash): http://ww1.microchip.com/downloads/en/DeviceDoc/doc0368.pdf
AT89C4051-PU (4K Byte Flash): http://ww1.microchip.com/downloads/en/devicedoc/doc1001.pdf
**Current Footprint Library**: MCU_Atmel_8051
**Associated fix list**: https://github.com/KiCad/kicad-symbols/issues/272

**Symbol Screenshot**:
image

image

#############################################################################

**Part Name**: AT89C2051/4051-SU
**Part Manufacturer**: Microchip
**Datasheet URL**: 
AT89C2051-SU (2K Byte Flash): http://ww1.microchip.com/downloads/en/DeviceDoc/doc0368.pdf
AT89C4051-SU (4K Byte Flash): http://ww1.microchip.com/downloads/en/devicedoc/doc1001.pdf
**Current Footprint Library**: MCU_Atmel_8051
**Associated fix list**: https://github.com/KiCad/kicad-symbols/issues/272

**Symbol Screenshot**:
image

image

#############################################################################

**Part Name**: AT89S2051/S4051-24PU
**Part Manufacturer**: Microchip
**Datasheet URL**: http://ww1.microchip.com/downloads/en/DeviceDoc/doc3390.pdf
**Current Footprint Library**: MCU_Atmel_8051
**Associated fix list**: https://github.com/KiCad/kicad-symbols/issues/272

**Symbol Screenshot**:
image

image

#############################################################################

**Part Name**: AT89S2051/S4051-24SU
**Part Manufacturer**: Microchip
**Datasheet URL**: http://ww1.microchip.com/downloads/en/DeviceDoc/doc3390.pdf
**Current Footprint Library**: MCU_Atmel_8051
**Associated fix list**: https://github.com/KiCad/kicad-symbols/issues/272

**Symbol Screenshot**:
image

image

#############################################################################

**Additional Comments & Questions**

-This PR is brought to you by its insomniac contributor. And Early Grey. Hot.
------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up the integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by fauxpark** [comment]
Already on it ;) #373

**Comment by daab4848** [comment]
>Already on it ;) https://github.com/KiCad/kicad-symbols/pull/373

@fauxpark I think your library fixes don't include mine, as the ones I'm working literally only have AT89C2051/C4051-PU, AT89C2051/C4051-SU, AT89S2051/S4051-24PU, AT89S2051/4051-24SU symbols in it.

**Comment by evanshultz** [comment]
@daab4848 
But his PR will break yours, because library names will change. And it will probably create branch conflicts here even if the library names didn't change.

Can you detail exactly what you changed, so we can make sure nothing gets missed? I don't see anything above talking about what you fixed, so perhaps you can summarize instead of me spending time digging through commit logs.

**Comment by daab4848** [comment]
@evanshultz 
> MCU_Atmel_8051.lib:AT89*2051-SU: Loads of off-grid pins and no FPfilter
1. Essentially, I just fixed the off-grid pins for the AT89C2051/C4051 (-PU and -SU versions) and for the AT89S2051/S4051 (-24PU and -24SU versions) in the MCU_Atmel_8051 symbol library.
2. Renamed the AT89S2051/S4051-PU and AT89S2051/S4051-SU symbols to have a "24" in them (datasheet indicates that this is the clock speed i.e. the AT89Sxxxx versions run at 24MHz). So they were renamed as AT89S2051/S4051-24PU and AT89S2051/S4051-24SU.
3. Changed pin name offset from 40mil to 20mil
4. Changed pin number and name to 50mil.
5. Filled description, keywords, and datasheet for all symbols.
6. Fixed the footprint filters.

**Comment by fauxpark** [comment]
1. Already done
2. Didn't catch that the names were wrong
3. Already done
4. Already done
5. Already done? I did a lot of work on the Atmel MCU DCMs recently, the descriptions might need a little more consistency though
6. I added the NC and EP pins to all symbols, so there is no need to add the pin count to the footprint filter. None of the 8051 symbols have either anyway

**Comment by daab4848** [comment]
@evanshultz @fauxpark 
Since thes AT89xxxx symbols already have most of the fixes done, then this PR is surely redundant. Apologies for the mix-up. Anyway to delete/remove this PR?

**Comment by Ratfink** [comment]
You should be able to close it yourself with the "Close pull request" button below the comment box.  If you write a message first, the button changes to "Close and comment".

**Comment by evanshultz** [comment]
I'll just go ahead and close it while I'm here. The branch is now broken anyway.

@fauxpark @daab4848 
I've added the open items here to https://github.com/KiCad/kicad-symbols/issues/387. Would you all work together to address the remaining items, after discussion if needed. Assuming you're still willing to help.

**Pull request closed without merging**
