### PR TITLE
Driver_Motor: Add TI DRV8837/37C/38

### PR DESCRIPTION
**Pull request by florolf**
- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
 - http://www.ti.com/lit/ds/symlink/drv8837.pdf
 - http://www.ti.com/lit/ds/symlink/drv8837c.pdf
- [x] An example screenshot image is very helpful
drv8837
drv8838
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
- Please remove "with" from the 8838's description.
- Add "PWM input" to the 8837 and 8837 descriptions (for clarity about the differences).
- Then all need "WSON-8" added to the end of the description for the package type and pin count.
- You've shorted the thermal pad to GND. While the datasheet shows this, I don't see that it says this must be done. In that case, please make the pad a separate pin. Or if I missed this requirement please let me know where it is.
- Pins 2 and 3 should just be Output type.
- The motor symbol (Motor:Motor_DC) is taller than the OUT1 to OUT2 pin spacing (it is 500mil tall). What about a taller (instead of wide) symbol style that fits the motor symbol between the OUT* pins? This isn't required, I'm just proposing it for your consideration.

**Comment by antoniovazquezblanco** [comment]
@florolf Would you be addressing the changes requested above?

Thanks!

**Comment by antoniovazquezblanco** [comment]
I am interested in using this device in one of my designs. I had a version I did not submit yet. I will be taking over this PR in order to get a review of the symbol before I send it into production if @florolf does not continue with it.

Thanks

**Comment by antoniovazquezblanco** [comment]
Overtaken in https://github.com/KiCad/kicad-symbols/pull/1408

**Comment by antoniovazquezblanco** [comment]
Done in a new PR

**Pull request closed without merging**
