### PR TITLE
MV267 symbol, with variant MV317

### PR DESCRIPTION
**Pull request by aewallin**
Morion OCXO oscillator MV267 symbol, with a variant (same pin numbers/function) MV317

Datasheets:
http://www.morion.com.ru/catalog_pdf/MV267.pdf
https://www.morion-us.com/catalog_pdf/mv317.pdf

Screenshot:
morion_ocxo_mv267

Footprint PR: https://github.com/KiCad/kicad-footprints/pull/1108

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
New symbol design, similar to existing VCXOs
ocxo_morion_mv267

**Comment by antoniovazquezblanco** [comment]
Footprint merged

**Comment by myfreescalewebpage** [comment]
Hi @aewallin, thanks for contributing,

A few comments I have during my review (basically the same as https://github.com/KiCad/kicad-symbols/pull/1199):

- [ ] Part name is very long for no reason. I would suggest "MV317" and MV267.
- [ ] There is no footprint. The two devices have different package, so I suggest it should be added and the devices must be separated, no alias.
- [ ] Is Uref an Output ?

Where have you found pad numbering ? This is consistent with the footprint so it's okay, that's just a question.

Cheers,
Joel

**Comment by aewallin** [comment]
- names shortened
- footprints assignled
- Uref is a voltage reference output, and can be used e.g. with a potentiometer to se the Uin voltage
- Manufacturer doesn't provide pin numbers so I have made them up
- symbol split into two
mv317
mv267

**Comment by myfreescalewebpage** [comment]
Closing/opening to be travis execution.

**Comment by myfreescalewebpage** [comment]
Thanks @aewallin 

Comment following modification of packages:
- [ ] Footprint filter of MV267 should be `Oscillator*OCXO*Morion*MV267*`
- [ ] Footprint filter of MV317 should be `Oscillator*OCXO*Morion*MV317*`

Joel

**Comment by myfreescalewebpage** [comment]
Thanks ! Now travis is happy :)
No more comment on this PR, merging.

Joel

**Pull request merged**
