### PR TITLE
Add LT1711 comparator

### PR DESCRIPTION
**Pull request by aewallin**
https://www.analog.com/media/en/technical-documentation/data-sheets/171112f.pdf

This could be a variant of an existing symbol, but then we loose tight coupling to the footprint.
This part is available only in MSOP-8, so maybe deserves its own symbol?

lt1711

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Sometimes it goes mad. Closing and reopening the PR should fix it.

**Comment by antoniovazquezblanco** [comment]
See :)

**Comment by aewallin** [comment]
meh, probably not doing it right here..  (tried "git rebase master" locally, and the fixed conflict in .lib file)

maybe I can export the single new symbol, close this PR, branch off the updated master, and submit a new PR?

**Comment by aewallin** [comment]
33 files changed can't be right. should probably close this one and create a new PR with just the new symbol.

**Comment by myfreescalewebpage** [comment]
@aewallin by merging the master upstream, it does not solve this ?

If not, probably it's the best solution...

Joel

**Comment by aewallin** [comment]
clearly my git-fu is not working today :)
I'll close this and reopen a new one.

**Pull request closed without merging**
