### PR TITLE
Add Diodes Incorporated PAM2301 series buck converters

### PR DESCRIPTION
**Pull request by MacroYau**
Added symbols for Diodes Incorporated PAM2301CAAB330 (with alias for PAM2301CAAB120 and PAM2301CAABADJ). Adapted from the existing PAM2305 series symbol (same pins but different numbering).

Datasheet: https://www.diodes.com/assets/Datasheets/PAM2301.pdf

PAM2301

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi. A minor observation. Why is not "Vin" in uppercase like others?

**Comment by MacroYau** [comment]
@gmsotavio I adopted the previously-admitted PAM2305 symbol's labeling which uses `Vin`. Indeed, I also think it is a better idea to uppercase it. I am pushing a revision soon.

**Comment by myfreescalewebpage** [comment]
Hi @MacroYau, thanks for contributing,

A few comments I have during my review:

PAM2301CAAB120 / PAM2301CAAB330
- [ ] I'm not able to download the datasheet, is the link correct ?
- [ ] The description should finish with the complete package name : TSOT-23-5
- [ ] Name of pin 5 is "VOUT"
- [ ] Type of pin 3 should be Power Output

PAM2301CAABADJ
- [ ] Why the datasheet link refer to PAM2305 ?
- [ ] The name of pin 5 is different than the fixed output voltage versions, should be a different symbol, not an alias
- [ ] The description should finish with the complete package name : TSOT-23-5
- [ ] Type of pin 3 should be Power Output

Joel

**Comment by myfreescalewebpage** [comment]
@MacroYau ping

**Comment by MacroYau** [comment]
Hi @myfreescalewebpage, thanks for reviewing! I have fixed the issues you mentioned.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
