### PR TITLE
Add Microchip MCP1501 family voltage reference

### PR DESCRIPTION
**Pull request by yankee14**
Add Microchip MCP1501 family voltage reference.

`kicad-symbols`: https://github.com/KiCad/kicad-symbols/pull/2783
`kicad-footprint-generator` for WDFN-8: https://github.com/pointhi/kicad-footprint-generator/pull/612
`kicad-footprints` for WDFN-8: https://github.com/KiCad/kicad-footprints/pull/2457

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/20005474E.pdf

This voltage reference comes in the following fixed voltage outputs:

- 1.024V
- 1.25V
- 1.8V
- 2.048V
- 2.5 V
- 3V
- 3.3V
- 4.096V

And the following packages:

- SOT-23-6
- SOIC-8
- WDFN-8

The WDFN package does not yet exist in the footprint library. `kicad-footprint-generator` seems to have no python script available for generating DFN packages, so I will await advice on what to do.

I think I messed up making the alias for the WDFN part; it might contain too much information, and I may need question marks in some places instead of asterisks. I always get these wrong every time I submit symbols...

My library may be corrupted due to the bug I've outlined here: https://github.com/KiCad/kicad-symbols/pull/2778#issuecomment-638467353

Screencaps:

MCP1501-10_SOIC

MCP1501-10_SOT

MCP1501-10_WDFN

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by yankee14** [comment]
New screencap:

MCP1501-10_SOIC

**Comment by myfreescalewebpage** [comment]
Hi @yankee14 , thanks for contributing,

A few comments I have during my review:

MCP1501-10_SOIC
- [ ] Name of the symbol should be "MCP1501-10xSN". Same logic for the aliases
- [ ] Fp filter `SOIC*3.9x4.9mm*P1.27mm*`
- [ ] Pin 8 can be called "FB" (also seen this in the datasheet) and the symbol will be better

MCP1501-10_SOT
- [ ] Name of the symbol should be "MCP1501-10xCH". Same logic for the aliases
- [ ] Footprint to be completed
- [ ] Fp filter `SOT?23*`

MCP1501-10_WDFN
- [ ] Name of the symbol should be "MCP1501-10xRW". Same logic for the aliases
- [ ] Footprint to be completed
- [ ] Fp filter `WDFN*1EP*2x2mm*P0.5mm*`
- [ ] Pin 8 can be called "FB" (also seen this in the datasheet) and the symbol will be better

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@yankee14 thanks for the update. Two footprints still missing in the symbols.

**Comment by myfreescalewebpage** [comment]
Thanks, just need to wait the footprint

**Comment by yankee14** [comment]
@myfreescalewebpage ping

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
