### PR TITLE
Add WM8731

### PR DESCRIPTION
**Pull request by robinolejnik**
added WM8731 audio codec in different versions:
WM8731SEDS (SSOP-28)
WM8731CLSEFL (QFN-28, different pinout)
WM8731CSEFL (alias of WM8731CLSEFL, different supply voltage range)

Datasheet:
https://statics.cirrus.com/pubs/proDatasheet/WM8731_v4.9.pdf

image
image

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @robinolejnik , thanks for contributing,

A few comments I have during my review:

WM8731CLSEFL
- [ ] Footprint filter should not include the EP size `QFN*1EP*5x5mm*P0.5mm*` is ok
- [ ] VMID should be Passive and move to the right of the symbol.
- [ ]  You should align AGND with AVDD and HPGND with HPVDD
- [ ] Maybe CLKOUT above XTI/XTO is better for the wiring of the crystal

WM8731SEDS
- [ ] VMID should be Passive and move to the right of the symbol.
- [ ]  You should align AGND with AVDD and HPGND with HPVDD
- [ ] Maybe CLKOUT above XTI/XTO is better for the wiring of the crystal

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@robinolejnik ping

**Comment by robinolejnik** [comment]
image
image
Messed up updating my repo. I think I fixed it adequately.

@myfreescalewebpage Thanks for your review. I included all the corrections you proposed.

Robin

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment.

**Comment by robinolejnik** [comment]
Thank you!

**Pull request merged**
