### PR TITLE
Microchip MCU SAME

### PR DESCRIPTION
**Pull request by DerekGn**
See https://github.com/KiCad/kicad-library/pull/1872 for screenshots

http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-11296-32-bit-Cortex-M7-Microcontroller-SAM-E70Q-SAM-E70N-SAM-E70J_Datasheet.pdf

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the symbol(s) you are contributing
- [X] An example screenshot image is very helpful
- [X] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by DerekGn** [comment]
Lib passes build but build script failes for some other reason

**Comment by poeschlr** [comment]
The script fails because you are missing the entry in the sym-lib-table for this new lib.

**Comment by DerekGn** [comment]
I assume I just add an entry to the end of the file?

**Comment by bobc** [comment]
"MCU_Microchip_SAME70" is quite specific, there are only 9 E70 parts. It might be better to call it "MCU_Microchip_SAME" ?

**Comment by DerekGn** [comment]
Fair point, I renamed to aligh with the microchip/atmel product category.

**Comment by jkriege2** [comment]
Please fix conflict and remove pin-count from FPFilters!

Thanks,
JAN

**Comment by jkriege2** [comment]
PS: Just a note: There is a PR that also would pull over these µCs: https://github.com/KiCad/kicad-symbols/pull/95 ... We should decide in teh discussion there how to deal with this conflict!

**Comment by DerekGn** [comment]
This PR is a mess. I will create another clean one.

**Pull request closed without merging**
