### PR TITLE
add Mini-Circuits directional coupler ADC-10-1R

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/pdfs/ADC-10-1R.pdf

adc-10-1r

Footprint: https://github.com/KiCad/kicad-footprints/pull/1148

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
Footprint was merged, however with a new name. This symbol should be changed to use the new fp-name.

**Comment by aewallin** [comment]
adc-10-1r

**Comment by myfreescalewebpage** [comment]
Hi @aewallin , thanks for contributing,

A few comments I have during my review:

- [ ] You can add impedance in the description
- [ ] We usually put reference in top left corner and name in top right corner - Actually you have reference at a strange position which not very convenient...
- [ ] You should add NC pins 4 (Type Not Connected, not visible) because the pin count is not specified in the footprint (KLC S4.5 http://kicad-pcb.org/libraries/klc/S4.5/)

Cheers,
Joel

**Comment by aewallin** [comment]
Now:
adc-10-1r

**Comment by myfreescalewebpage** [comment]
@aewallin fp filter to be updated on this one.

Joel

**Comment by aewallin** [comment]
- off-grid NC hidden pin, otherwise travis OK.

Now looks like so:
adc-10-1r

**Comment by myfreescalewebpage** [comment]
Thanks @aewallin No more comment, merging.

Joel

**Pull request merged**
