### PR TITLE
Added AS72651

### PR DESCRIPTION
**Pull request by Puchinger**
Added AS72651
[link](https://ams.com/documents/20143/36005/AS7265x_DS000612_1-00.pdf/08051c8a-a7f6-6231-7993-2d3fe0bf38b8)
Screenshot at 2019-03-28 09:31:15

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Puchinger , thanks for contributing,

A few comments I have during my review:

- [ ] Description and keywords can be crossed, this is better.
- [ ] Description should ends with the full package name, modify to `Smart 18-Channel VIS+NIR Spectral_ID Sensor with Electronic Shutter, LGA-20`
- [ ] Name of pin 1 should be `~SLV1_RES`
- [ ] I wonder about type of pin 1, do you know when it is an input ? According to me it is an Output.
- [ ] Name of pin 2 should be `~RES`
- [ ] I wonder about type of pin 4, do you know when it is an input ? According to me it is an Output.
- [ ] I wonder about type of pin 5, do you know when it is an output ? According to me it is an Input.
- [ ] Name of pin 6 should be `~CS`
- [ ] Type of pin 11 should be Input
- [ ] Name of pin 20 should be `~SLV2_RES`
- [ ] NC pins should be moved to the border outline of the symbol
- [ ] The symbol is very large for no reason. You should pack it a bit in width and height. Proposition below (all previous points not fixed in this screenshot).

Capture

Cheers,
Joel

**Comment by Puchinger** [comment]
@myfreescalewebpage
Thank you for your review!
I have corrected the mistakes.
Here a new screenshot:
Screenshot at 2019-04-09 22:16:00

**Comment by myfreescalewebpage** [comment]
Thanks, just one point to fix, you have written description in place of keywords and keywords in place of the description. Please switch them :)

**Comment by Puchinger** [comment]
@myfreescalewebpage
Everything should fit now

**Comment by myfreescalewebpage** [comment]
Yes, thanks! Merging.

**Pull request merged**
