### PR TITLE
Filter: Add 1FP45-0R - EMI filter

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Filter: Add 1FP45-0R - EMI filter

Datasheet: https://filtercon.com.pl/wp-content/uploads/2019/07/Karta-katalogowa-FP-12-1.pdf

1FP45-0R

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the symbol(s) you are contributing
- [ ] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by piotr-wiszowaty** [comment]
Footprint: [https://github.com/KiCad/kicad-footprints/pull/1966](https://github.com/KiCad/kicad-footprints/pull/1966)

**Comment by myfreescalewebpage** [comment]
Hello @piotr-wiszowaty 

I have not verified every thing, but at the moment:
- [ ] Can you fix the descriptions of the aliases (you just copy/paste the main symbol)
- [ ] Can you rebase your branch so I can continue the review

Thanks,
Joel

**Comment by piotr-wiszowaty** [comment]
I'm not sure what's wrong with the alias descriptions - they are the same for all of the components in this sub-family in accordance with the datasheet.

**Comment by myfreescalewebpage** [comment]
There is a problem now with your branch. See https://github.com/KiCad/kicad-symbols/pull/2313/files
The voltage and/or current in the descriptions were not correct.

**Comment by piotr-wiszowaty** [comment]
diff with master shows only my changes - what is the problem with the 1FPxx branch?

**Comment by myfreescalewebpage** [comment]
Seems the status of your branch is now OK. Can you fix the descriptions please ?

**Comment by piotr-wiszowaty** [comment]
Yes, but I still do not understand what's wrong with them:
* I can see them all in the library browser,
* They are all the same as the parts differ only by their frequency characteristics and not by current/voltage rating.

**Comment by myfreescalewebpage** [comment]
Just took two of the aliases you have made:
- 1FP45-1R is 250VAC 1A but you indicated 0.5A
-  1FP64-2R is 250VAC 2A but you indicated 0.5A

So....

**Comment by piotr-wiszowaty** [comment]
You are completely right. It turns out the distributor which I bought 
the components from and based the symbol on provides
an incorrect version of the datasheet 
(https://www.tme.eu/Document/c532f99b805f3981a0ea6c4609c8138b/FILTERCON-FP.pdf).
I'm fixing the descriptions right away.

**Comment by myfreescalewebpage** [comment]
Thanks! Merging now.

**Pull request merged**
