### PR TITLE
Add NCN4555MNR2G

### PR DESCRIPTION
**Pull request by jneiva08**
Added NCN4555MNR2G

Datasheet: https://www.onsemi.com/pub/Collateral/NCN4555-D.PDF
Footprint: https://github.com/KiCad/kicad-footprints/pull/1458

Screenshot:
ncn455

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

- [ ] I disagree with the symbol name, the datasheet indicate the QFN version is "MN suffix" so the symbol should be "NCN4555MN"
- [ ] No comma in the keywords
- [ ] Pin offset should be 20mil (KLC error S3.6, see travis result)
- [ ] Expose pad is missing (pin 17) and should be stacked with GND pin 10
- [ ] You can reduce a little bit the size of the symbol as shown below if you want, let me known:

capture

Else sounds good, just need to wait the footprint.

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage , have made alterations you recommended. the symbol don't look exactly to yours
ncn4555

**Comment by myfreescalewebpage** [comment]
Your proposition is great too :) Just realize we can switch pins 13 and 14 or 9 and 11 so that the CLK is in front of SIM_CLK and RST in front of SIM_RST. Can you address it ? Thanks.

**Comment by myfreescalewebpage** [comment]
@jneiva08 thanks for the modifications, no more comment here, just need to wait the integration of the footprint to merge this.

**Comment by jneiva08** [comment]
@myfreescalewebpage yesterday have received some NCN4555MNR2G from Farnell.

Have tried to verify if GND (pin 10) have continuity to EP, but it doesn't have.
Probably is better to remove EP from GND.

In MPU-9250 the EP isn't connected to GND.

**Comment by myfreescalewebpage** [comment]
@jneiva08 that's not because you have continuity that the pad should not be connected to ground. I have just read a more complete description in the datasheet page 9:

> The exposed pad of the QFN−16 package will be connected to the ground as well as the unconnected pins (NC). A relatively large ground plane is recommended.

So, I think we should (you should also in your design) stack the EP and all the NC pins too (we have keep NC pins not connected at this moment but I'm no more sure we have to).

Let me known,
Joel

**Comment by myfreescalewebpage** [comment]
PS : MPU-9250 do not respect KLC at all (pins are too long, graphic style of pin is not correct, too much lost space, Power Input on the right etc.)

**Comment by myfreescalewebpage** [comment]
@jneiva08 merging following integration of the footprint.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
