### PR TITLE
Add NXP i.MX6 CPUs

### PR DESCRIPTION
**Pull request by tpambor**
Add NXP i.MX6 Dual, Dual Plus, Quad and Quad Plus CPUs into a new CPU_NXP_IMX library.

The symbol is split into multiple symbols based on the power domains which roughly equal the functional units of the SOC.

Datasheet: https://www.nxp.com/docs/en/data-sheet/IMX6DQCEC.pdf

Footprint PR: KiCad/kicad-footprints#1033

Screenshots:

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x

------------
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by tpambor** [comment]
No changes, just forced push to rerun CI after footprint has been merged.

**Comment by myfreescalewebpage** [comment]
Hi @AUTHOR, thanks for contributing,

A few comments I have during my review:

- [ ] Descriptions should ends with the package name, please add `, BGA-624` at the end
- [ ] Layout size is not expected in the footprint filter, you can change to `BGA*21.0x21.0mm*P0.8mm*`
- [ ] N11 name and position are not correct, should be modified to `VDD_ARM23_CAP` and stacked with other pins with the same name
- [ ] Same width for all units should be good, maybe you can enlarge units B, L, R, S, T, V, W and reduce unit P ?
- [ ] I like the name of the unit in the unit itself. You have indicated power domain (PLL OUT, SNVS CAP, etc) like that, but it is nice to have a name for all the other units (USB, GPIO, ENET, ...). Spaces are allowed for this texts.
- [ ] SDx_CMD is not always placed at the same place between SDx_CLK and SDx_DAT0. You can move SDA_CMD or the three others for consistency.

That's an amazing symbol with so much pins !! Difficult to review but you have done a great work on it, there is so few errors ! I'm confident with you about the choice of the position of the pins on the units. Where are you working to propose this kind of symbol ? Are you working on some System-On-Module board ?

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@tpambor ping! Are you still alive on this subject ?

**Comment by tpambor** [comment]
Sorry for the delay. I incorporated all your feedback @myfreescalewebpage

**Comment by myfreescalewebpage** [comment]
Thanks @tpambor for the fixes, great job here !

Two comments:
- [ ] MLB pins for the newly added parts should be all named NC as indicated in the datasheet https://www.nxp.com/docs/en/data-sheet/IMX6DQPIEC.pdf page 154 (invisible and type not connected is okay).
- [ ] The four pins of unit B are "Not Connected" but remains visible, which triggers a travis error. I would like to have them "Passive" to avoid the errors.

Cheers,
Joel

**Comment by tpambor** [comment]
Thanks for the quick review. I performed the requested changes.

**Comment by myfreescalewebpage** [comment]
Ok for me, thanks for this amazing contribution ! Merging.

**Pull request merged**
