### PR TITLE
Add 62256 based on the existing 628128

### PR DESCRIPTION
**Pull request by jdmarble**
62256_DIP28_SOP28

To create this, I copied the 628128_DIP32_SSOP32 and renamed it 62256_DIP28_SOP28.
I changed the symbol properties to match the new part.
I removed the extra pins, fixed the numbering, and recentered the part.

Like the 628128, there are multiple manufacturers of the 62256:

* [Samsung KM62256C](https://www.futurlec.com/Datasheet/Memory/62256.pdf)
* [Hitachi HM62256B](https://web.mit.edu/6.115/www/document/62256.pdf)
* [Cypress CY62256](https://ecee.colorado.edu/~mcclurel/Cypress_SRAM_CY62256.pdf)

Rather than follow the letter of KLC G2.1 and use a fully specified symbol,
I matched the precedent set by the 628128 and made this a generic symbol.

Similarly, I maintained conformity with the existing 628128 with the I/O pin naming.
The naming varies depending on the manufacturer,
so I used the same names as the 628128.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @jdmarble thanks for this symbol

I understand the way to create this symbol. However, this is no more recommended to do like that and I would really prefer to have one device per package, with the correct footprint associated.

In this example this will be "KM62256CLP" and "KM62256CLG". If you know other manufacturers providing the same device you can add some aliases.

On the symbol itself, no comment to do.

Joel

**Comment by jdmarble** [comment]
Thanks for the guidance!

I've made the KM62256CLP (with aliases) fully specified. I did not create a KM62256CLG version because there are no matching SOP packages.

**Comment by myfreescalewebpage** [comment]
I have an issue while opening the library, see screenshot below. This is sometimes the case when merging master as you have done.

Capture

There is missing liens at the end of your device definition in the lib file at line 1256:
ENDDRAW
ENDDEF

**Comment by jdmarble** [comment]
Thanks for finding that. Looks like I fixed it an another problem with the footprint filter.

**Comment by myfreescalewebpage** [comment]
Just one remaining comment

- [ ] Description of the HM62256BLP should be terminated with the package name as done for the others

Else, very good job done here !
Joel

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
