### PR TITLE
Oscillator: add LTC6905-XXX

### PR DESCRIPTION
**Pull request by ChristianHirsch**
Add [LTC6905-XXX](https://www.analog.com/media/en/technical-documentation/data-sheets/6905xfa.pdf) family of precision, fixed frequency silicon oscillators.

image

### CODE REVIEW

**Comment by aewallin** [comment]
description should end with the footprint e.g. ",SOT-23" (S6.3.1.a)
otherwise looks good.

**Comment by ChristianHirsch** [comment]
@aewallin thanks for reviewing. Fixed the description.

**Comment by chschlue** [comment]
Please don't force push after a review has started.

**Comment by ChristianHirsch** [comment]
@chschlue fixed your comments

**Comment by chschlue** [comment]
Thanks

**Pull request merged**
