### PR TITLE
Added EFM8UB3 Devices

### PR DESCRIPTION
**Pull request by LeSpirou**
Added three MCU devices to MCU_SiliconLabs: EFM8UB31F40G-A -QFN20, -Q…

…FN24, -QSOP24

Violated KLC Rules:
S3.1 Reason: To maintain the 100mil pin grid spacing all symbols off centered by (0,+50)

Datasheet: https://www.silabs.com/documents/public/data-sheets/efm8ub3-datasheet.pdf

grafik
grafik
grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by LeSpirou** [comment]
I'm sorry for all inconviences I made. I'm here to learn and contribute something back to KiCAD.

**Comment by LeSpirou** [comment]
Violated KLC Rules:
S3.1 Reason: To maintain the 100mil pin grid spacing all symbols off centered by (0,+50)
S4.4 Reason: VDD pin has the electrical passive since it does _also_ source power, depending on the configuation.

**Comment by myfreescalewebpage** [comment]
Hi @LeSpirou , thanks for contributing,

A few comments I have during my review:

EFM8UB30F40G-A-QFN20
- [ ] Description should ends with package name `8051-compatible microcontroller, 48 MHz, 2.3 to 5.5V, 40K flash, 3.25K RAM, -40 to +85 C, QFN-20` is great
- [ ] Fp filter: `SiliconLabs*QFN*1EP*3x3mm*P0.5mm*`
- [ ] Pins length should be 100 mil for this symbol (< 100 pins)
- [ ] VDD should be Power Input
- [ ] Pin 11 is missing
- [ ] Pins 9 and 10 should be Bidirectionnal
- [ ] You should order pins by groups (P2.x together, etc) with a separation of 200mil between groups. PLease separate also USB pins, this is another group

EFM8UB31F40G-A-QFN24
- [ ] Description should ends with package name `8051-compatible microcontroller, 48 MHz, 2.3 to 5.5V, 40K flash, 3.25K RAM, -40 to +85 C, QFN-24` is great
- [ ] Fp filter: `QFN*1EP*4x4mm*P0.5mm*`
- [ ] Pins length should be 100 mil for this symbol (< 100 pins)
- [ ] VDD should be Power Input
- [ ] Pins 9 and 10 should be Bidirectionnal
- [ ] You should order pins by groups (P2.x together, etc) with a separation of 200mil between groups. PLease separate also USB pins, this is another group

EFM8UB31F40G-A-QFN24
- [ ] Description should ends with package name `8051-compatible microcontroller, 48 MHz, 2.3 to 5.5V, 40K flash, 3.25K RAM, -40 to +85 C, QSOP-24` is great
- [ ] Fp filter: `QSOP*3.9x8.7mm*P0.635mm*`
- [ ] Pins length should be 100 mil for this symbol (< 100 pins)
- [ ] VDD should be Power Input
- [ ] Pins 11 and 12 should be Bidirectionnal
- [ ] You should order pins by groups (P2.x together, etc) with a separation of 200mil between groups. PLease separate also USB pins, this is another group

Cheers,
Joel

**Comment by LeSpirou** [comment]
EFM8UB30F40G-A-QFN20
EFM8UB31F40G-A-QFN24
EFM8UB31F40G-A-QSOP24

**Comment by LeSpirou** [comment]
@myfreescalewebpage Hi Joel
I adjusted the symbols according your comments. Just to let you know.

**Comment by myfreescalewebpage** [comment]
Great job done ! No more comment, merging.

**Pull request merged**
