### PR TITLE
Add BAS19

### PR DESCRIPTION
**Pull request by jneiva08**
Add BAS19 to 21

Datasheet: https://www.diodes.com/assets/Datasheets/Ds12004.pdf
Screenshot:
image

Used same symbol of BAS16W

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] Provide a screenshot of the symbol(s) from the symbol editor with the pin types visible
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [x] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing additional info like the screenshot of the symbol editor pin table (or for high pin counts converted to csv) sorted in the same way as the pin table in the datasheet and a direct link to the datasheet page that contains the pin table.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 , thanks for contributing,

A few comments I have during my review:

BAS20 and BAS21:
- [ ] Datasheet links are not correct

Cheers,
Joel

**Comment by jneiva08** [comment]
@myfreescalewebpage, thanks for letting me know, I hope it's correct now.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Comment by jneiva08** [comment]
Thanks for your time

**Pull request merged**
