### PR TITLE
Add 74HC(T)1/237

### PR DESCRIPTION
**Pull request by fauxpark**
A 3-to-8 line decoder/demultiplexer with address latches. SOIC/SSOP-16.

sym

Datasheet: https://assets.nexperia.com/documents/data-sheet/74HC237.pdf

TI also makes it in DIP: http://www.ti.com/lit/ds/symlink/cd74hc237.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the symbol(s) you are contributing
- [x] An example screenshot image is very helpful
- [x] Ensure that the associated footprints match the [official footprint library](https://github.com/kicad/kicad-footprints)
  - A new fitting footprint must be submitted if the library does not yet contain one.
- [ ] If there are matching footprint PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @fauxpark , thanks for contributing,

A single comments I have during my review:

- [ ] Height should be reduced by 100mil to avoid extra space between Y7 and bottom of the symbol

Cheers,
Joel

**Comment by fauxpark** [comment]
@myfreescalewebpage - if I shrink the height any more, the script will complain about it either being off-center or having off-grid pins.

**Comment by myfreescalewebpage** [comment]
> if I shrink the height any more, the script will complain about it either being off-center or having off-grid pins.

It will make an information that the symbol is not perfectly centered but it is acceptable.

> The TI datasheet also seems to include the 74HC137 and the HCT variants of both. Should I add these as aliases?

Sure you can !

**Comment by fauxpark** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Thanks, merging!

**Pull request merged**
