### PR TITLE
Added AP65111

### PR DESCRIPTION
**Pull request by DecadoPL**
https://www.tme.eu/Document/6fc4ea95d789e43795384f666d828c26/AP65111.pdf

image

It fits Package_TO_SOT_SMD:TSOT-23-6

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the CLA.

**Comment by myfreescalewebpage** [comment]
@DecadoPL thanks for this contribution,

Some few comment about this PR:

- [ ] Can you sign the CLA, which is a mandatory condition to accept your contribution ? Thanks.
- [ ] Name of the device should be `AP65111WU`
- [ ] Description can be enhanced for consistency with other devices, I propose `1.5A, 500KHZ Buck DC/DC Converter, adjustable output voltage, TSOT-23-6`
- [ ] Same comment for keywords: `1.5A 500KHz PWM Buck DC/DC`
- [ ] Pin position offset should be 20mil
- [ ] Footprint filter should be `TSOT?23*`
- [ ] Symbol is not centered (see travis log)
- [ ] Datasheet link can't be on TME website, please provide a link on the device manufacturer website
- [ ] Name of pin 1 is "IN"
- [ ] GND is pin 3, SW is pin 2
- [ ] SW should be Power Output
- [ ] BST should be Passive to avoid ERC errors
- [ ] The symbol is too large, I propose the following for consistency with similar devices:

Capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@DecadoPL ping! Are you still alive on this ?

**Comment by DecadoPL** [comment]
@myfreescalewebpage i will be soon. I need to learn how to use all those check tools and other things and then ill fix it.

**Comment by myfreescalewebpage** [comment]
Work continue on the new PR, closing this one.

**Pull request closed without merging**
